### ISSUE TITLE
Страница "Вхід в систему". Нет ссылки на хелп по регистрации.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#100]
Сделать ссылку на раздел документации:
http://help.a10.com.ua/start/register

**Comment by alex-kukhtin** [comment]
А она там вообще нужна?

**Comment by alex-kukhtin** [comment]
Теперь там море ссылок :-)

**Comment by alex-kukhtin** [comment]
Закрывай нафиг

**Comment by mik-man** [comment]
А ссылки на хелп по регистрации так и нет. Ну и ладно.
