### ISSUE TITLE
При выставлении счета нельзя указать цену с "в т. ч. НДС"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1000]
Похоже, ошибка появилась после нового функционала в свойствах прайс-листов: цена с ндс, без ндс
в общем, кнопка ндс в т. ч. не активная 
![image](https://user-images.githubusercontent.com/38099938/61524424-1a180280-aa1f-11e9-9dab-2e843f4aaef6.png)

**Comment by AlexeyTishkin** [comment]
В документах "Счет исходящий", "Расходная накладная", "Акт оказанных услуг", "Акт оказанных услуг с материалами" изменено поведение свойства "ПДВ в т.ч.". Теперь значение этого свойства зависит от значения свойства вида цены "Ціна з ПДВ". Если вид цены в документе не выбран, то значение можно менять вручную.

**Comment by kattrina-brekhova** [comment]
поняла, дяк!!
