### ISSUE TITLE
Розрахунково-платіжна відомість и Оборотная ведомость по 661 счету: при расчете зарплаты за 2 половину месяца не учитываются уже расчитаные налоги, а суммы налогов с авансовой ведомости суммируются к зарплатной за 2 половину месяца

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1002]

**Comment by kattrina-brekhova** [comment]
начислила аванс и выплатила налоги
в Ведомости начисления зарплаты за 2 половину месяца указываю общее количество отработанных дней в периоде
![image](https://user-images.githubusercontent.com/38099938/61541608-a5f25480-aa48-11e9-8756-56d1b2094209.png)
Ошибка: в расчетно-платежной ведомости к суммам начисленных налогов по зарплате добавляются суммы налогов по авансу. например:
![image](https://user-images.githubusercontent.com/38099938/61541819-041f3780-aa49-11e9-9ef8-ba0da6175624.png)

Денисенко: оклад 6000 * 18% ПДФО = 1080. в оборотке сумма 1542,86 , то есть еще и 462,86 которые были начислены в авансе
вот они
![image](https://user-images.githubusercontent.com/38099938/61542257-d71f5480-aa49-11e9-9186-4c389e8ba394.png)

**Comment by Illya-Lykhachov** [comment]
Как посмотреть? Это тестовый аккаунт?

**Comment by kattrina-brekhova** [comment]
на сервисе, в этом аккаунте готовлю лабораторки для университета
логин behappy120486@gmail.com
пароль behappy1204

**Comment by Illya-Lykhachov** [comment]
Ошибка в последовательности создания и проведения документов.
Id	DateCreated	DateApplied
66303	2019-07-19 08:49:11.620	**2019-07-19 13:25:15.640** - Начисление аванса
66394	**2019-07-19 12:50:37.820**	2019-07-19 14:12:21.050 - Расчётная ведомость
В момент создания **и заполнения** расчётной ведомости, документ начисления аванса ещё не был проведен. Поэтому удержания и ЕСВ с аванса не учтены при расчёте удержаний и ЕСВ при расчёте. Аналогичная ситуация повторилась и в феврале

**Comment by kattrina-brekhova** [comment]
да, я вносила изменения. перепроводила, удаляла, сохраняла....

**Comment by kattrina-brekhova** [comment]
этот нюанс может быть починен? или допускается только строгий алгоритм проведения?

**Comment by kattrina-brekhova** [comment]
посмотрите пожалуйста еще это ишью https://github.com/a2develop/bugTracker/issues/1005

**Comment by kattrina-brekhova** [comment]
в этом же акке

**Comment by Illya-Lykhachov** [comment]
Перезаполни расчётную ведомость и подтянутся суммы удержаний из аванса. Здесь не должно быть ноль!
![image](https://user-images.githubusercontent.com/35328100/61695727-b18d9600-ad3c-11e9-8b92-fe21295db92f.png)

**Comment by Illya-Lykhachov** [comment]
> этот нюанс может быть починен? или допускается только строгий алгоритм проведения?

Только строгий алгоритм.

**Comment by kattrina-brekhova** [comment]
Хорошо, пройдусь еще раз, спасибо

**Comment by kattrina-brekhova** [comment]
Дело не во времени начисления зарплаты....
я удалила и заново начала вводит документы, та же история
в расчетно платежной ведомости сидит сумма по налогам по авансу и по зарплате (она не вычитывает уже начисленные и выплаченные по авансу налоги)
![image](https://user-images.githubusercontent.com/38099938/61700513-7d6aa300-ad45-11e9-8a24-8349ce17de1e.png)
Денисенко: оклад 6000 * 18% ПДФО = 1080. в оборотке сумма 1542,86 , то есть еще и 462,86 которые были начислены в авансе
вот они
![image](https://user-images.githubusercontent.com/38099938/61700701-9ffcbc00-ad45-11e9-863b-ee84b7c6e96a.png)
за месяц НДФЛ у меня должен быть 12 934,28. но показывает большее число на сумму аванса
![image](https://user-images.githubusercontent.com/38099938/61700760-bacf3080-ad45-11e9-9d97-0ff1d742e60d.png)

по остальным налогам так же

**Comment by kattrina-brekhova** [comment]
я дико извиняюсь, но опять ошибка повторилась
убила, заново создала такую же последовательность документов: начисление аванса - выплата по кассе, насисление зарплаты / выплата по банку и то же задвоение налогов по всем обороткам

**Comment by kattrina-brekhova** [comment]
ура, все работает, спасибище!!
