### ISSUE TITLE
Выплата дивидендов - добавить операцию

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1004]
Вітаю, підкажіть будь-ласка яким чином здійснювати проводки під час прийняття рішення, нарахування та виплати дивідендів учаснику-фізособі. Маю на увазі:

1. Прийнято рішення про виплату дивідендів. Як відобразити бухгалтерський облік ДТ 441; Кт 443.

2. Нараховано дивіденди.  Дт443; Кт 6713

3. Утримано ПДФО.  Дт6713; Кт641/ПДФО

4. Утримано ВЗ.  Дт6713; Кт642

5. Перераховано до бюджету ПДФО. Дт6413; Кт311

6. Перераховано до бюджету ВЗ. Дт.642; Кт.311

7.Виплачено дивіденди. Дт6713; 311\

Предлагается часть проводок бухсправкой оформить, и добавить операцию Выплата дивидендов в  платежку.

**Comment by AlexeyTishkin** [comment]
Добавлена операция "Виплата дивідендів". Дб 671 - Кр 311.
