### ISSUE TITLE
начислили больничные, проводка Д... - К663. Но при выдаче денег 663 счет не учитывается, а списывает с 661, висят остатки

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1005]
начисление больничных пошло на 663 счет
![image](https://user-images.githubusercontent.com/38099938/61630269-fc9d9f80-ac8f-11e9-9265-2c4cb0c5d410.png)
значит и выплата должна идти с 663 счета
а у нас выплата больничных в том числе формируется с 661
![image](https://user-images.githubusercontent.com/38099938/61630355-28b92080-ac90-11e9-9ea2-137cb785cc86.png)
![image](https://user-images.githubusercontent.com/38099938/61630370-3078c500-ac90-11e9-9bc1-7fd99aef8d3d.png)
и висят остатки по 661 счету
![image](https://user-images.githubusercontent.com/38099938/61630396-44bcc200-ac90-11e9-8b73-c3dc6e80f903.png)

**Comment by Illya-Lykhachov** [comment]
Данные аккаунта здесь:
https://github.com/a2develop/bugTracker/issues/1002

**Comment by kattrina-brekhova** [comment]
да, аккаунт:
логин behappy120486@gmail.com
пароль behappy1204

**Comment by kattrina-brekhova** [comment]
и здесь еще есть проблема:
https://github.com/a2develop/bugTracker/issues/1001
