### ISSUE TITLE
Не подтягивается из Актов ГПХ в Д4 табл.6 период начисления в графу 11.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1010]
При отображении гпх должно автоматически заполняться графа 11, месяц и год, за которые проведено начисление.
![image](https://user-images.githubusercontent.com/42540074/61873319-59969100-aeee-11e9-8ff1-d6764cc2a801.png)

**Comment by Illya-Lykhachov** [comment]
Исправлено
