### ISSUE TITLE
Добавить механизм редактирования Начального баланса

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1011]
Пользователь ввел начальный баланс по запасам, но ошибочно ввел цену не закупочную, а продажную. Теперь по этому запасу ввел сто накладных, партия списана. А цену в начальном балансе откорректировать не может, так как надо распроводить, а партии списаны, или часть партий.

Нужно добавлять механизм редактирования проведенного документа. Но документ по вступительному балансу - универсальный, нужно смотреть..

Для начала редактировать цену.

**Comment by AlexeyTishkin** [comment]
Сделал.
