### ISSUE TITLE
Уведомление о приеме. Нужна возможность создавать несколько отчетов в одном периоде.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1015]
Сейчас выдается такое сообщение, и непонятно, какие реквизиты совпадают.
![image](https://user-images.githubusercontent.com/42540074/62133467-7e707700-b2e7-11e9-81f9-3cc954fefc09.png)
Исправить проверку дубликатов для уведомлений

**Comment by GalinaLuk** [comment]
Добавила ишью https://github.com/a2develop/bugTracker/issues/1018, что касается 1015 - отчетов такого типа  должно быть разрешено сдавать неограниченное количество, потому что их может быть сколько угодно за месяц, и похоже, может быть несколько даже за день. 

Этот вопрос в налоговой мне не удалось выяснить, но лично я, чтобы не попасть на штраф, сделала бы следующим образом:
Если уже отправлен отчет и возникла необходимость в тот же день принять на работу еще одного сотрудника, то я отправила бы отменяющую форму на первый отчет, и далее отправила бы новый правильный отчет с двумя новыми сотрудниками в нем. Таким образом, мне понадобилось бы в течении 1 дня отправить три таких отчета

**Comment by htrofymova** [comment]
готово. Буде проводитися скільки завгодно звітів. Створення скасовуючих звітів - під відповідальність користувача.
