### ISSUE TITLE
Bug: сообщение о неправильном вводе пароля исчезает при вводе с Enter

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#102]
Криво ведет себя форма логина.
Если после набора неправильного пароля кликнуть мышкой на "Увійти" - все ОК, появляется сообщение о неверном пароле.
Если после набора неправильного пароля нажать Enter - сообщение о неправильном пароле появляется и мгновенно исчезает, остается подсказка "Введите пароль" под полем пароля.

**Comment by alex-kukhtin** [comment]
Fixed in 7163
