### ISSUE TITLE
В Общей оборотно-сальдовой ведомости по 362 счету на конец периода по Дб и Кр висят одинаковые суммы, которые появились в результате курсовой переоценки дебиторки. Нормально ли это?

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1022]
![image](https://user-images.githubusercontent.com/38099938/62467865-6a23f280-b79d-11e9-9014-0892121aedca.png)
![image](https://user-images.githubusercontent.com/38099938/62467903-8031b300-b79d-11e9-8d19-ee47a7b5a57d.png)
почему они не закрылись, не понимаю?

**Comment by kattrina-brekhova** [comment]
суммы сформированы операцией «Операційна курсова різниця (витрати)».

**Comment by htrofymova** [comment]
как это можно посмотреть? или это у клиента?

**Comment by kattrina-brekhova** [comment]
нет, у меня. на сервисе
логин behappy120486@gmail.com
пароль behappy1204

**Comment by htrofymova** [comment]
исправлено
