### ISSUE TITLE
К обсуждению: переоценка валюты на дату баланса отражается в общей ОСВ, но конечное сальдо в ОСВ по счетам в банке в валюте не меняется и ручная проводка не отражается

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1024]
![image](https://user-images.githubusercontent.com/38099938/62473298-1ddeaf80-b7a9-11e9-930c-5260c26ba777.png)

![image](https://user-images.githubusercontent.com/38099938/62473370-4666a980-b7a9-11e9-93de-847f2b8e0edd.png)

![image](https://user-images.githubusercontent.com/38099938/62473408-58e0e300-b7a9-11e9-8ba8-380b2d0be4f0.png)

**Comment by AlexeyTishkin** [comment]
В "Бухгалтерской справке" нужно добавить аналитики "Валюта", "Расчетный счет".

**Comment by kattrina-brekhova** [comment]
да, таких строк в ней нету

**Comment by AlexeyTishkin** [comment]
> да, таких строк в ней нету

Поэтому и не попадает в отчет по счетам.

**Comment by htrofymova** [comment]
нужно сделать еще пару операций курсовых разниц, уже с привязкой к текущему счету.

**Comment by htrofymova** [comment]
додала в "Курсові різниці", операції Операційна курсова різниця (витрати) та Операційна курсова різниця (дохід). Якщо рахунок по дебету або кредиту  312, то з'являється можливість обрати  банківській рахунок.
