### ISSUE TITLE
Расчеты по ГПД и ЗП 949 добавить в зп. остальные в ГПД.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1028]
Расчеты по ГПД (и ЗП тоже)
надо дать возможность бухгалтеру настраивать на какой счет относить затраты по начислениям сотрудникам. Директору начисления производятся за счет админрасходов, что устраивает, А остальным сотрудникам - на 23 счет. Напоминаю, у меня две неприбыльные благотворительные орг-ции, проектным сотрудникам начисляем в Дт 949.  В принципе, по штатным я пока выкручиваюсь, бухсправкой закрываю 23-й на 949 счет неадминдеятелей. А с ГПД-шниками - беда: начисления все идут на 91-й с закрытием на 23-й. С такой цепочкой  я буду выглядеть совсем нехорошо, закрывая 23-й на 949-й. 
В связи с этим предложение - дать возможность в свойствах сотрудника указывать, в дебет какого счета относить расходы по ЗП/ГПД физлица. Если не задано - начисляется по схеме "по-умолчанию", если задано, то счет из свойств подставлять.
И очень надо в начисления ЗП/ГПД добавить привязку к проектам. Тоже предлагаю в свойствах ФЛ предусмотреть поле для выбора проекта (для ГПД - в договоре ГПД это поле логичнее), и при наличии такого значения цеплять проект к операции.

**Comment by Illya-Lykhachov** [comment]
Сделал в части использования счёта затрат в договоре ГПХ.
С проектами понятно для ГПХ, а для обычной заплаты пока нет. Можно в должность проект добавить или выбирать в строках расчётной ведомости (тогда один сотрудник сможет работать в разных проектах, но не в одном месяце).

**Comment by Illya-Lykhachov** [comment]
пора закрывать
