### ISSUE TITLE
Бухсправка - просят добавить некоторые элементы

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1029]
Так же просятся проекты в бухсправку. есть операции, с которыми я пока не морочу голову разработчику, провожу бухсправкой, и без проекта они выпадают из отчетов (по проекту).
Просьба привязать к 39-му счету справочник услуг в качестве основной аналитики (дабы в бухсправке можно было выбрать какую позицию я закрываю на затраты, и отчет построить по ОУ). Удобно и логично контролировать в разрезе ОУ движение по этому счету (подписка период.изданий, долгосрочные лицензии - что я оприходовала, и как чего списываю по периодам на затраты).

Зоя Степанова

**Comment by htrofymova** [comment]
Готово, кроме отчета "с перламутровыми пуговицами".
Объекты учета - выбираются все виды.

**Comment by htrofymova** [comment]
Отчет сделаю отдельным issue. А по бух.справке - закрывать, наверно, можно.
