### ISSUE TITLE
Оплата покупателя с комиссией - уточнить отображение долга в списке Бета операций

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1033]
Кейс: Выставлен счет на сумму 100 грн. в т.ч. НДС 16,67. На основании создается оплата, по умолчанию вид операции: Оплата покупателя. Стоит сумма 100 грн. 
Выбираем операцию Оплата покупателя с комиссией, Здесь клиенту бы пояснение (!!!!). какую именно сумму туда прописывать, а то сразу не заметит, что у него от контрагента переплата на 361 висит. 

 Ставим вручную сумму 80,00 грн. и 20 грн сумма комиссии. В назначении платежа указывается автоматически изначально, в т.ч. ПДВ 16,67 грн. Это не меняем. 
Но как только мы заменили сумму со 100 на 80, в графе У тому числі ПДВ  рассчиталась новая сумма ндс -- 13.33 грн. Она смущает клиента. 
![image](https://user-images.githubusercontent.com/42540074/62946746-f5c70000-bde9-11e9-8870-efa4f9f05cae.png)

Дальше, все проводим, выполняем отгрузку в свой срок. По ведомостям все норм.
![image](https://user-images.githubusercontent.com/42540074/62946807-1000de00-bdea-11e9-8868-2e9daef0dd12.png)
 
А вот в списке Бета-операций висит этикетка. что Счет оплачен частично, клиент должен доплатить 20 грн. Это важно убрать!
![image](https://user-images.githubusercontent.com/42540074/62946835-1ee79080-bdea-11e9-9936-4b20598121d6.png)

**Comment by kattrina-brekhova** [comment]
расписала корректный кейс с точки зрения налогового учета https://github.com/a2develop/bugTracker/issues/1034
