### ISSUE TITLE
Оплата покупця з комісією: кейс

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1034]
у налоговой есть 2 позиции отражения дохода для ЕН по платежам эквайринга:
1. Базой является только сумма, зашедшая на счет (к примеру 80 гривен). Это следует из НКУ: база налогообложения - только все зашедшие деньги на счет. Этой же логикой руководствуются при отражения доходов в инвалюте - то есть комиссия, списанная банком самостоятельно, уменьшает базу налогообложения единщика
2. Базой является вся сумма, которую отправил покупатель (к примеру 100 гривен). Эту позицию налоговики поддерживают в письмах разъяснениях и в частных консультациях. В поддержку этой позиции также и то, что покупатель в 1дф показывает нашего фопа с суммой в 100 гривен.
Клиент, которому понадобилась эта операция, также хочет, чтобы при расчете ЕН, в доходе отразилось 100 гривен (а не 80).
Также в назначении платежа банк указывает полную сумму отправленную покупателем и сумму комиссии. Это является для нас основанием формировать платежное поручение в БукКипер с комплекной проводкой.
Для фопов 1, 2, 3 группы базой налогообложения является 100 гривен. для фопов 3 группы - плательщиков НДС - 83,33 (НДС 16,67).
НДС должен считаться из суммы по выставленному счету и которую отправил покупатель, а не с той, которая нам поступила на счет.
Предлагаю комплексные проводки следующие:
Д311 - К361 100
К631 (банк) - Д311 20
Д93 - К631 (банк) 20
Таким образом, цепочка документов закроется. 
Банковская выписка с ее назначением является поводом для формирования этих проводок. Обороты по банку тоже пойдут.

**Comment by kattrina-brekhova** [comment]
еще аргументы в пользу такой позиции:
1) комиссия банка является не чем иным, как расходами продавца товаров, поэтому не должна уменьшать его доходы от продажи;
2) в квитанции (чеке) платежного терминала также отражается вся сумма покупки без уменьшения на комиссию банка.
и еще, хоть в ЗИР и написано, что доходом является «вся сумма, поступившая на расчетный счет», налоговики эту фразу трактуют и так, что: фактически продавцу поступила бОльшая сумма, с нее банк удержал комиссию и зачислил на счет разницу, расписав эти суммы в выписке - а они расписаны.

**Comment by kattrina-brekhova** [comment]
соответственно в БК в платежном поручении указываем 100 гривен, сумму комиссии 20 гривен. ндс расчитываться должно со 100 гривен

**Comment by AlexeyTishkin** [comment]
> Д311 - К361 100
К631 (банк) - Д311 20
Д93 - К631 (банк) 20

В таком случае наша отчетность не будет совпадать с выпиской из банка. Реально у нас не было движения по р/с в виде прихода 100 грн и расхода 20 грн. Был только приход 80 грн.

**Comment by AlexeyTishkin** [comment]
А зачем прогонять это через 631 ?

**Comment by AlexeyTishkin** [comment]
> расписав эти суммы в выписке - а они расписаны

Насколько я помню, клиент говорил, что выписке нет ни общей суммы Счета, ни суммы комисиии. Есть только сумма поступления, а остальные суммы он должен искать в программе.

**Comment by kattrina-brekhova** [comment]
наша отчетность - это оборотно-сальдовая ведомость?
кроме как для внутренней аналитики она нигде не используется. проблемы появляются, когда несоответсвие между задекларированным доходом и фактически перечисленными нам деньгами
 
можно не проганять по 631. а можно проганять для дополнительной аналитики суммы комиссий за период

вроде Галя сказала, что в назначении стоит сумма комиссии
и когда я работала с подобными платежами по виза, то в банковской выписке в назначении все было расписано

**Comment by AlexeyTishkin** [comment]
> наша отчетность - это оборотно-сальдовая ведомость?

Да. И это было первым требованием клиента: он не хотел завышать приход и делать фиктивный расход.

**Comment by kattrina-brekhova** [comment]
и кстати нельзя утверждать несоответсвие оборотно-сальдовой ведомости по 311 с выпиской.
потому как в книгу доходов и расходов тоже нужно показывать сумму фактического платежа от покупателя - на 100 гривен

**Comment by AlexeyTishkin** [comment]
Описанная ситуация решается существующими шаблонами: Оплата от покупателя и Оплата банківських послуг. Нет никакого смысла показывать комиссию по каждому платежу.

**Comment by kattrina-brekhova** [comment]
ну что ж, по сегодняшнему разговору с клиентом, у него мнение, что нужно показывть в доходе 100 гривен

**Comment by AlexeyTishkin** [comment]
> фактического платежа от покупателя

Фактический платеж - 80 грн. Это то, что реально зашло на р/с.

**Comment by kattrina-brekhova** [comment]
нет, фактический - это то, что нам отправили

**Comment by AlexeyTishkin** [comment]
> ну что ж, по сегодняшнему разговору с клиентом, у него мнение, что нужно показывть в доходе 100 гривен

:)

Ну тогда Оплата от покупателя и Оплата банківських послуг.
В Оплате от покупателя 100 грн, в Оплата банківських послуг 20 грн.
И ничего нового придумывать не надо.

**Comment by kattrina-brekhova** [comment]
ну я не из головы придумала это. читала в консультациях, статьях, на порталах
не показывать в доходе разницу комиссии - это занижать доход, из-за чего проблем с налоговой не обберешься!

**Comment by kattrina-brekhova** [comment]
удобнее когда одним документом можно провести 2 операции, тем более когда они связаны!

**Comment by kattrina-brekhova** [comment]
операции связаны. можно двумя операциями - когда то мы так и проводили. но хотелка была, чтоб 1 документом 2 операции провести

**Comment by AlexeyTishkin** [comment]
В таком случае нет смысла комиссию проводить по каждому поступлению. Одной суммой за день.

**Comment by AlexeyTishkin** [comment]
> хотелка была

Отдельную операцию делали именно из-за того, чтобы не показывать фиктивное движение денег.

**Comment by kattrina-brekhova** [comment]
Галя не разобралась, мы не выяснили кейс прежде чем делать новую операцию.

**Comment by kattrina-brekhova** [comment]
но это же удобнее, когда десятки эквайринга за день и можно их провести быстро комплексной операцией! и когда не нужно высчитывать по каждому платежу комиссию и их суммировать!!!
если много таких платежек - это можно сойти с ума

**Comment by AlexeyTishkin** [comment]
В чем ошибка ? Зачем bug ?

**Comment by kattrina-brekhova** [comment]
в том, что эта операция занижает базу налогообложения

**Comment by AlexeyTishkin** [comment]
Комиссию можно проводить не общей операцией, а на каждую оплату. Сумма комиссии все равно вносится руками.

**Comment by AlexeyTishkin** [comment]
> в том, что эта операция занижает базу налогообложения

Так она для этого и была сделана :)
Для новой постановки она не предназначена.

**Comment by kattrina-brekhova** [comment]
если эту операцию не изменить, то ее не должно быть в сервисе, так как она занижает базу налогообложения. а потом клиенты, которых прижучат - не дай бог, придут к нам

**Comment by kattrina-brekhova** [comment]
и мы будем крайние за то, что продаем неправильный софт

**Comment by AlexeyTishkin** [comment]
А клиент понял, что у него в программе движение по банку не будет совпадать с отчетностью банка ? И согласился с этим ?

**Comment by AlexeyTishkin** [comment]
"Клиент очень не хочет показывать в выписке полную сумму с комиссией и потом отдельно в выписке комиссию, потому что фактически она ему не поступает" - это из первоначального общения.

**Comment by kattrina-brekhova** [comment]
клиент может не понимать, что такая операция уменьшит задекларированный доход и не знать, что он подает отчетность с ошибками. и будет уверен, что у него все в порядке, до момента проверки. а потом - неожиданность и штраф

**Comment by kattrina-brekhova** [comment]
потому что изначально мы тоже глубоко не копали. хотя кому как не нам предусмотреть все последствия подобных операций

**Comment by kattrina-brekhova** [comment]
главное чтоб сальдо пошло на конец и на начало дня. а если в оборотке в сервисе с обороткой в клиент банке не сходятся десятки гривен - господи, ну на что это влияет? бухгалтер на это не обрати внимания, это не существенно

**Comment by AlexeyTishkin** [comment]
В таком случае "Оплату с комиссией" убираем. Ничего нового не добавляем, пользуемся двумя существующими.
Ждем фидбека от других клиентов по такому же кейсу.

**Comment by GalinaLuk** [comment]
Я не считаю, что я не разобралась, а скорее недорассмотрела все вопросы, когда писала ишью в первый раз. Считаю что я не учла вопрос корреткного отражения НДС и закрытия цепечики в варианте представления для Беты, и  клиент хотел именно так видеть комиссию, как она есть сейчас, его смущали только незакрытые сообщения (оплачено частково) и он дополнительно просил чтоб они все-таки выглядели как завершенные операции. Сейчас, когда Настя подняла этот же вопрос по поводу НДС, я перезвонила этому же клиенту и спросила его. Оказалось, что он ведет два предприятия ФЛП на едином налоге и юрлицо на общей системе. Я спросила на примере 80 и 100, как он отражает базу для этих налогов. Он сказал, что конечно он берет 100, и это было бы очень стремно брать 80 (он просто изменил свою позицию по сравнению с тем, что было раньше). Если спрашивать мое мнение как от разработчика программного обеспечения, который должен предлагать то, что соответствует законодательству, считаю что второй вариант (100-20) некорректен. То есть, я именно так бы вела как бухгалтер, но не предлагала бы этот вариант как разработчик. Возможно, имеет смысл сделать сразу 2 варианта - чтобы был выбор поступить и так, и так. Я написала обо всем этом Максиму, и он сказал, что будет это решать после релиза.

**Comment by AlexeyTishkin** [comment]
> его смущали только незакрытые сообщения (оплачено частково) и он дополнительно просил чтоб они все-таки выглядели как завершенные операции

Это исправим.

**Comment by kattrina-brekhova** [comment]
перед тем как исправлять, давайте согласуем необходимость этой операции. потому что даже, если у клиента исправится, и у него будет красивая оборотка, у него будет некрасивый отчет по ЕН

**Comment by AlexeyTishkin** [comment]
> считаю что второй вариант (100-20) некорректен

Согласен. С фиктивными операциями бухгалтер может "химичить" сам, но делать такую операцию стандартной - нельзя.

**Comment by AlexeyTishkin** [comment]
> у него будет некрасивый отчет по ЕН

База отражения в начислении налогов - отдельный вопрос. Если законодательно обосновано, что в качестве базы нужно использовать "фактически продавцу поступила бОльшая сумма", а не "только сумма, зашедшая на счет" то нужно менять алгоритм начисления налогов.

**Comment by kattrina-brekhova** [comment]
на сегодняшний день у дфс есть 2 позиции и 2 письма разъяснения. киевская область считает, что в базу налогообложения включать только сумму, зашедшую на счет. ровенская область - что всю сумму - то есть бОльшую
завтра будут этот вопрос обсуждать с аудиторами

**Comment by Anestezia** [comment]
Интересно и другое, допустим, мы приняли решение єту операцию: Оплата покупця з комиссией, убрать. А что будет с документами, которые клиенты уже посоздавали? Как система отреагирует?

**Comment by AlexeyTishkin** [comment]
> А что будет с документами, которые клиенты уже посоздавали?

Останутся. Нельзя будет создать новую.

**Comment by Anestezia** [comment]
По большому счету это у нас может быть операция Приход и Расход в одном платежном поручении-операции (выписке). И проводки совместные от двух операций: Приход 100 грн, в т.ч. НДС 16.67, и Расход на банковские услуги 20 грн. 
311 - 361 == 100 грн. База налогообложения 100 грн.

92 - 311 == 20 грн.
791 - 92 == 20 грн.

А не примазывать к 20 гривнам комисии 361 клиентский счет. Комиссия -- это не его проблема. Это пока мое мнение. (Можно, в зависимости от ситуации заменить 92 на 93. Тут надо определиться).

**Comment by Anestezia** [comment]
> > А что будет с документами, которые клиенты уже посоздавали?
> 
> Останутся. Нельзя будет создать новую.

А если понадобится распровести, откорректрировать, то потом уже ее не проведет. А если попытается скопировать?

**Comment by AlexeyTishkin** [comment]
> По большому счету это у нас может быть операция Приход и Расход в одном платежном поручении-операции (выписке).

Не может быть такого в одной строке выписки. Только приход или расход.

**Comment by AlexeyTishkin** [comment]
> 311 - 361 == 100 грн. База налогообложения 100 грн.

Обсудили же уже... Это - фиктивное движение.

**Comment by AlexeyTishkin** [comment]
> А если понадобится распровести, откорректрировать, то потом уже ее не проведет. А если попытается скопировать?

Все сможет сделать.

**Comment by Anestezia** [comment]
комиссию 20 грн. с 361 убрать предлагаю, и только.

**Comment by GalinaLuk** [comment]
Я была сегодня у аудитора и еще читала законодательство. 
I. Аудитор однозначно рекомендует
1. по банковской выписке учитывать сумму без комиссии банка (в нашем варианте "80")
2. включать сумму комиссии банка в том числе и в доход (только смотреть, чтобы не задваивалось в зависимости от системы учета) - это позиция осторожного налогоплательщика, который не хочет в дальнейшем иметь проблем с налоговой.
Таким образом, если мы оставим эту операцию в Буккипере, действительно придется совместно обсудить и сделать правки в алгоритме начисления налогов и в базе налогообложения - единого налога, налога на прибыль и НДС. Возможно, потянет за собой еще какие-то отчеты, надо будет проверять.
И еще, он рекомендует вынести расчеты по эквайрингу на какой-то отдельный счет/субсчет  (например 333 или 3331) - для того чтобы было легко и удобно видеть суммы по нему и сверять, например если есть квитанции или отдельные выписки банка по эквайрингу. В этом варианте есть нюансы, поскольку если мы будем пропускать через 333 или другой счет, это означает, что сумма не будет проходить по 361 - и это плохо (на мой взгляд). Поэтому здесь тоже нужно обсуждать коллективно. Возможно ли например, эквайринговые операции вести в разрезе проэктов? или создать специально для них какой-то отдельный вид договора, который будет означать отдельный аналитический учет налогов (как, например, для типа "услуги" мы же создали отдельную услугу аренды)?
В принципе, автоматизированная таким образом сложная операция с эквайрингом (если мы ее сделаем) будет существенно упрощать учет предпринимателям, желающим работать с pos-терминалами, и будет нашим преимуществом для работы в Буккипере - потому что безналичный оборот все равно увеличивается, а объем наличности уменьшается в бизнесе.

II. В природе существует позиция безбашенного налогоплательщика на едином налоге, которые готовы отражать только те суммы в учете, которые фактически зайдут на счет.
Для них можно предусмотреть такой вариант  - снятия отметки  ☑, 
которая по умолчанию будет стоять и означать включение комиссии банка в базу налогообложения. Т.е. если убирается птичка, то комиссия не будет включаться в доход, а отражаться так, как считается сейчас - "доход 80" и все дальнейшие подсчеты на их усмотрение.

III. и я бы предложила в эту операцию добавить еще одну ☑
Она стоит по умолчанию и означает, что оплата (в данной цепочке по этому счету) закрывается полностью - т.е. пользователь самостоятельно подтверждает полное  закрытие цепочки.
Если же так случится, что была оплачена только часть суммы с эквайрингом, а остальная часть зайдет позже - он должен будет снять эту птичку и для системы учета будет понятно, что это частичная оплата.

Не знаю реально ли сделать, что я написала, из-за того, что я не понимаю, как устроены те алгоритмы, по которым это работает. Готова обсуждать и думать как по-другому, если найдется возможность объяснить ситуацию, почему это невозможно.

**Comment by kattrina-brekhova** [comment]
ну вот, ничего нового. те же 2 позиции, которые законом никак не урегулированы ((((

**Comment by GalinaLuk** [comment]
Ну для меня много чего поменялось. Я не надеялась, что мне может аудитор сказать что-то новое с точки зрения законодательства, но хотела понять, как они ведут на практике - если до встречи я говорила, что я сама вела бы по принципу "100-20" как бухгалтер (хоть и не согласна с этим, но не понимала, как по-другому достичь правильного учета), то теперь я точно знаю, что я бы вела по "80", подтягивая хвосты дохода в виде комиссии вручную - и так будет правильно, хоть и напряжнее. Если же сделать подтягивание таких комиссий автоматом в системе учета - это будет волшебно.

**Comment by kattrina-brekhova** [comment]
Галя, а с НДС? сумма ндс уменьшает базу налогообложения ЕН. она уменьшается на 16,67? 100/6

**Comment by kattrina-brekhova** [comment]
отважные и безбашные плательщики 3 группы с НДС должна уменьшить 80 грн на 16,67 (или на 13,33)?

**Comment by GalinaLuk** [comment]
На какую сумму выписывать НН, если первое событие — отгрузка? Клиент сказал, что он бы хотел на 100, а не на 80 показывать. К тому же, я как контрагент прекратила бы общение с поставщиком, так как у меня бы в НН было 100 — сумма, которую я отправила, а он бы мне закрыл только 80?
Все остальное как в обычном учете, как если бы на счет поступило 100, а не 80

**Comment by kattrina-brekhova** [comment]
у 3 группы плательщиков ндс, ен рассчитывается с поступления на счет - минус сумма ндс
100 - 16,67
или 100 - 13,33
или 80 - 16,67
или 80 - 13,33
?? :)

**Comment by GalinaLuk** [comment]
отважные и безбашные плательщики 3 группы с НДС должна уменьшить 80 грн на 16,67 (или на 13,33)? 
- Если они берутся вести это ручками (самим подгребать свою комиссию не системой), то и выписывать НН будут сами на свое усмотрение. Короче, что хотят, то пусть и делают. Просто если будет эта птичка, которая позволяет им не вносить в доход 20, то с НДС пусть решают сами, как им лучше выписывать. По их логике, они должны выписывать на 80. Но я не предлагаю давать эту возможность автоматом. Это технически неразумно делать. Не будут же они уменьшать в % соотношении каждую налоговую накладную? Я думаю, что НДС особо выпендриваться не будут (очень легко нарваться на внеплановую проверку из-за несоответствия НДС и единого налога) и будут использовать базу 100. 
Кто может пойти на отражение базы 80, так это единоналожники без НДС - которые точно не перешагнут порог дохода (их и ухватить не за что - они не сдают никакие другие данные, чтобы было с чем сравнить). Если налоговая по итогам проверки добавит эквайринг в доход, и потом еще получится, что они уже перешагнули порог единщика, то сложно представить какие будут штрафы. Но эти должны будут судиться, чтобы доказать свою правоту по закону. С другой стороны, если у них будут хорошие юристы, они могут и выиграть.

**Comment by GalinaLuk** [comment]
у 3 группы плательщиков ндс, ен рассчитывается с поступления на счет - минус сумма ндс
100 - 16,67
или 100 - 13,33
или 80 - 16,67
или 80 - 13,33
?? :)
Если это будет наш автоматизированный учет комиссии, то отражается поступление только 80 грн, налоговая выписывается на 100 (в т.ч. НДС 16,67). При этом будет меняться алгоритм начисления налогов, чтобы так посчитать. И нужно будет показывать (разворачивать цифры - откуда они взялись для подсчета налога)

**Comment by GalinaLuk** [comment]
Если мое предприятие заявило, что оно платит комиссию, а не я — покупатель, то пусть и платит. И уберет комиссию с 361 счета (аналитика Клиент) Пусть туда себя ставит мое предприятие, раз оно платит.
Настя, я хочу понять, какие последствия видишь ты, чего не вижу я:  для пользователя бухгалтерии все будет выглядеть и рассчитываться так, как будто на счет поступило 100 грн. Единственная нестыковка которая точно останется - это сумма реально поступивших средств на счет никогда не совпадет с суммой отгрузки - и разница будет в сумме комиссии. Все остальное - база для НДС, Налога на прибыль и Единого налога будет рассчитываться так, как будто предприниматель их все же получил - именно 100 на счет с дальнейшими налоговыми последствиями соответственно системе учета.

**Comment by Anestezia** [comment]
> Если мое предприятие заявило, что оно платит комиссию, а не я — покупатель, то пусть и платит. И уберет комиссию с 361 счета (аналитика Клиент) Пусть туда себя ставит мое предприятие, раз оно платит.
> Настя, я хочу понять, какие последствия видишь ты, чего не вижу я: для пользователя бухгалтерии все будет выглядеть и рассчитываться так, как будто на счет поступило 100 грн. Единственная нестыковка которая точно останется - это сумма реально поступивших средств на счет никогда не совпадет с суммой отгрузки - и разница будет в сумме комиссии. Все остальное - база для НДС, Налога на прибыль и Единого налога будет рассчитываться так, как будто предприниматель их все же получил - именно 100 на счет с дальнейшими налоговыми последствиями соответственно системе учета.

Изначально вопрос в том, что клиент заплатил (361 клиентский) всю сумму по счету, а БукКипер считает, что есть недоплата от клиента. Этого быть не должно, поэтому я и говорю, что раз клиент не платит комиссию, то  и нечего ее на него вешать в учете.

**Comment by kattrina-brekhova** [comment]
> > расписав эти суммы в выписке - а они расписаны
> 
> Насколько я помню, клиент говорил, что выписке нет ни общей суммы Счета, ни суммы комисиии. Есть только сумма поступления, а остальные суммы он должен искать в программе.

разные банки указывают по разному. Приватбанк не указывает аналитику входящего платежа, айбокс банк делает двумя разными операциями, альфабанк прописывает суммы комисии

**Comment by kattrina-brekhova** [comment]
общались сегодня с нашим бухгалтером - она бы не использовала операцию "оплата з комісією".
у нее есть єквайринг по другой фирме. на проводит двумя разніми платежами:
Д311 - К361
Д92 (банк) -  К311
и ей все-равно, что реальные обороты по банковской выписке меньше, чем обороты в программе, на суммы показанной комиссии
относительно единщиков. она считает, что объектом налогообложения является 100 гривен (то есть сумма счета - сумма, которую отправил покупатель), а не 97 гривен (которые реально зашли на счет)

**Comment by kattrina-brekhova** [comment]
вот єквайринг Таса
![image](https://user-images.githubusercontent.com/38099938/65414466-73742780-ddfc-11e9-86db-a062e609cbe1.png)

**Comment by Anestezia** [comment]
Это точно не правильно: 
![image](https://user-images.githubusercontent.com/42540074/72982738-769e1500-3de8-11ea-9938-bf4a8dadbd68.png)
![image](https://user-images.githubusercontent.com/42540074/72982796-91708980-3de8-11ea-9919-037112875eb4.png)
Тут бы кнопку по аналогии с НДС -- Комиссия в т.ч. и ставить сумму комиссии не на 361 счет, а на 92/93. Сумма по налоговой накладной тоже должна закрываться клиенту та, которую он заплатил - в моем последнем примере это 108 грн. А не 116 и не 100.

**Comment by kattrina-brekhova** [comment]
операцию закрываю
так как есть реальные сторонники не включать сумму комиссии в базу налогообложения
пока в ЗИР указаний ВКЛЮЧАТЬ - НЕТ
