### ISSUE TITLE
Корректировка отчета по Единому налогу

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#1037]
В отчете j0103507 ЕН для плательщиков 3-й группы
сделать подсвечивающую рамку в 5-м разделе, если не выбран налоговый орган
[
![Снимок экрана в 2019-08-15 15-52-09](https://user-images.githubusercontent.com/46449132/63095886-0a83cf00-bf75-11e9-8341-6ad8689df489.png)
](url)

**Comment by AlexeyTishkin** [comment]
Валидатор на этом поле есть и работает.

**Comment by AlexeyTishkin** [comment]
Нужны подробности для того, чтобы повторить.
