### ISSUE TITLE
Авансовый отчет, поменять формат даты прикрепленного документа

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1038]
Сейчас:
 м\дд\гг, а лучше дд/мм/гг, а то когда будет 3/05/19, то по старому и не докажешь, что это от пятого марта.
На примере, от 14 августа
![image](https://user-images.githubusercontent.com/42540074/63100390-ae727800-bf7f-11e9-9261-e6c1e8d67377.png)

**Comment by htrofymova** [comment]
готово
