### ISSUE TITLE
Експорт запасов: при реализации ОС, переведенного в состав товаров, по дебету идет списание не с 286 счета, а с 152

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1040]
перевела ОС в состав товаров
![image](https://user-images.githubusercontent.com/38099938/63161643-39f41380-c029-11e9-871a-8603a9a770e1.png)
сделала инвойс, создала таможенную декларацию
![image](https://user-images.githubusercontent.com/38099938/63161764-83dcf980-c029-11e9-8327-9cf47d621185.png)
в итоге она у меня подхватили 152 счет
в оборотке по 286 и 152 висят остатки, не закрываются операции
![image](https://user-images.githubusercontent.com/38099938/63161807-a4a54f00-c029-11e9-824a-e6dbce0bac10.png)
![image](https://user-images.githubusercontent.com/38099938/63161856-c4d50e00-c029-11e9-99ed-4bef7536400b.png)

на сервисе
логин behappy120486@gmail.com
пароль behappy1204

**Comment by kattrina-brekhova** [comment]
вот и в балансе эта строка с минусом 
![image](https://user-images.githubusercontent.com/38099938/63181952-0087cc00-c05a-11e9-916e-4733d8b3d6e8.png)

**Comment by htrofymova** [comment]
В общем-то, это не bug а enchancement. Возможность продажи необоротных активов на экспорт на самом деле не реализована. То, что в инвойсе можно выбрать объект необоротных активов, на данный момент является "неявной возможностью". Пока не будет полностью реализован экспорт необоротных, я эту "неявную возможность" отключу.
