### ISSUE TITLE
Создание с нуля (не на основании) операции Повернення вид покупця: не работают поля договор, склад, проект, таблица

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1041]
![image](https://user-images.githubusercontent.com/38099938/63165886-5ac26600-c035-11e9-9954-3816b76c6f53.png)

в сервисе

**Comment by AlexeyTishkin** [comment]
Создать полностью вручную нельзя. Нужно обязательно выбрать основание. После выбора поля заполняются из родительского документа.
