### ISSUE TITLE
Взаємозалік заборгованостей: вопрос о необходимости отражения НДС

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1042]
![image](https://user-images.githubusercontent.com/38099938/63175424-aa605c00-c04c-11e9-982b-eeb90044e100.png)

![image](https://user-images.githubusercontent.com/38099938/63175458-b8ae7800-c04c-11e9-8d64-c461ac78f70b.png)

![image](https://user-images.githubusercontent.com/38099938/63175505-d085fc00-c04c-11e9-904b-2dd5a1f742df.png)

на сервисе
логин behappy120486@gmail.com
пароль behappy1204

**Comment by kattrina-brekhova** [comment]
ввела сумму долга вручную, поставила галочку в т .ч. с ПДВ
в итоге НДС добавилась к сумме взаимозачета
![image](https://user-images.githubusercontent.com/38099938/63176293-5787a400-c04e-11e9-83dd-59fd3ada27cb.png)
![image](https://user-images.githubusercontent.com/38099938/63176316-62423900-c04e-11e9-9795-659c013f7827.png)
возможно причина в том, что у меня уже в прайс-листах заложено НДС... или не в ту сторону думаю...
вопрос - насколько вообще нужна в этом документе строка "в т. ч. с НДС"? на что она влияет? ведь в 361 и 631 задолжость и так учитывает налоговый кредит и налоговое обязательство.

**Comment by htrofymova** [comment]
1. Задолженность покупателя не заполняется, потому, что она не привязана к контракту, если контракт убрать - заполняется. 
2. По ПДВ - думаю, что его надо убрать вообще. Читала вот тут, но может есть что-то посвежее. https://i.factor.ua/ukr/journals/nibu/2016/november/issue-92/article-23106.html

**Comment by kattrina-brekhova** [comment]
точно. єто я по невнимательности

**Comment by kattrina-brekhova** [comment]
А зачем нужна эта функция?
если здесь речь идет о денежном долге будь то: за неоплаченные товары или не возвращенные предоплаты и т.д...
ндс начисляется на 1 из двух событий - оплата или поставка. а взаимозачет не входит ни в одно из этих событий

**Comment by kattrina-brekhova** [comment]
это посвежее будет
правда это индивидуальная консультация, но я по сути согласна
https://www.profiwins.com.ua/uk/letters-and-orders/ink/13643-3688-18.html
главное там в самом низу:

Статтею 601 ЦКУ визначено, що зобов’язання припиняється зарахуванням зустрічних однорідних вимог, строк виконання яких настав, а також вимог, строк виконання яких не встановлений або визначений моментом пред’явлення вимоги.

Виходячи із зазначеного, обома контрагентами при постачанні товарів/послуг повинні бути визначені податкові зобов’язання, а при отриманні товарів/послуг - податковий кредит.

Припинення зобов’язань шляхом зарахування зустрічних однорідних вимог не змінює визначені податкові зобов’язання/податковий кредит таких контрагентів.

**Comment by htrofymova** [comment]
ПДВ - убрала
