### ISSUE TITLE
Юзер видит лишние фирмы

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1043]
1.  Юзер видит фирмы, к которым есть явный запрет доступа. А не должен.
         обсуждение: https://bookkeepersaas.slack.com/archives/CLNKL1XJP/p1566294768000500

**Comment by AndriyNesterenya** [comment]
2. Ошибка при создании банка из МФО
The MERGE statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_Agents_CompanyCreated_Agents". The conflict occurred in database "Segment1_master", table "a2.Agents"
Один счет добавился нормально (IBAN). Все последующие - не хотят
PS Удалил первый счет IBAN - ничего не изменилось.
Но теперь не дает повторно создать тот же IBAN - пишет, на красной всплывалке, что счет уже существует

**Comment by alex-kukhtin** [comment]
Done 7532
