### ISSUE TITLE
Ошибка при создании банка из МФО

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1044]
Ошибка при создании банка из МФО
The MERGE statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_Agents_CompanyCreated_Agents". The conflict occurred in database "Segment1_master", table "a2.Agents"
Один счет добавился нормально (IBAN). Все последующие - не хотят
PS Удалил первый счет IBAN - ничего не изменилось.
Но теперь не дает повторно создать тот же IBAN - пишет, на красной всплывалке, что счет уже существует

https://bookkeepersaas.slack.com/archives/CLNKL1XJP/p1566295937001400?thread_ts=1565963954.001000&cid=CLNKL1XJP

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Проверено - ОК
