### ISSUE TITLE
Невидно кто из пользователей имеет доступ к юр.лицу

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1046]
Под учеткой админа тенанта, в разделе "Мои фирмы" не отображаются пользователи, которые имеют доступ к юр.лицам

Как я понимаю для этого и сделана вкладка - "Пользователи"

![image](https://user-images.githubusercontent.com/42002015/63347480-d71fb680-c35f-11e9-9da9-77b021d734f3.png)

**Comment by alex-kukhtin** [comment]
Done in 7537
