### ISSUE TITLE
Раздел Бухгалтерия. В док-е по операции Видаток з каси на рахунок в банку сделать возможность создавать док по операции Надходження на рахунок в банку з каси

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#105]

**Comment by Illya-Lykhachov** [comment]
Эта операция есть, только в кассовых операциях как приходная

**Comment by kattrina-brekhova** [comment]
Я не увидела функции, как в аналогии со счетом: когда, не выходя из документа, на его основании можно создать акты и накладные
Есть ли здесь такая возможность? Было бы хорошо, если можно

**Comment by Illya-Lykhachov** [comment]
Приняли в работу
