### ISSUE TITLE
Банковская выписка в мультифирме 

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#1054]
Импортирую по апи выписку, открываю первую, чтобы провести, выбираю вид операции и после этого происходит автозамена - подставляются наименование и реквизиты 1-й фирмы (при создании тенанта) , а не той, с которой я работаю в текущий момент. Т.е. после выбора вида банковской операции меняется хозяин операции

**Comment by AndriyNesterenya** [comment]
Подтверждаю.
Имею две фирмы.
В обоих есть счет с настройками Приватовского API
В первой по счету (с которой регистрировались) с виду все ОК.
При работе с выпиской у позднее добавленной фирмы происходит следующее:
Собственно выписка отображается, позволяет импортировать.
Даже отображается в списке выписок.
При переключении куда угодно (входящие/исходящие/черновики и т.д.) импортированные выписки из списка исчезают.
Но если заново попробовать импортировать выписку за эти периоды - пишет "Вже існує"

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Работает вроде бы уже

**Comment by AlexeyTishkin** [comment]
> Работает вроде бы уже

Закрываем ?
