### ISSUE TITLE
В списке договоров по отдельному контрагенту отображается удаленный договор.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1055]
![image](https://user-images.githubusercontent.com/42540074/63440071-e4a86f80-c437-11e9-96c4-2fc745c6d75b.png)
А в общем списке договоров его уже нет, соответственно.
![image](https://user-images.githubusercontent.com/42540074/63440139-fdb12080-c437-11e9-8a4d-c1c1726103d2.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
