### ISSUE TITLE
[Улучшайзинг] - список КВЕД

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1057]
При добавлении кодов в список КВЕД (и последующего использовании списка КВЕДов в отчетах) в таблице КВЕД у фирмы и в последствии в отчетах КВЕДы отображаются в порядке добавления.

Было бы крайне полезно (нагляднее и искать глазами удобнее) во всех случаях сортировать список по цифромому коду КВЕД по возрастанию, если это возможно.

**Comment by AlexeyTishkin** [comment]
Сделал.
Если где-то не так, то напиши конкретное место.
