### ISSUE TITLE
[UX] Создание фирм + создание юзеров

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1058]
Упражнялся с фирмами и юзерами.

Наехал на два не-UXных момента.

1. После создания фирмы во закладке Користувачі меню "Мои фирмы" светится пустое поле с текстом "_Тут має бути список користувачів з ролями для вибраної фірми_"
Хорошо бы там иметь ссылку на меню пользователей.

2. Новый пользователь в меню "Користувачі" создается бесправным без ролей. Для начала назначения ролей нужен лишний клик на тулбаре, в котором нужную кнопку еще найти и распознать надо.
Предлагаю после создания пользователя автоматически запускать мастер ролей.

https://bookkeepersaas.slack.com/archives/CLNKL1XJP/p1566403342006700?thread_ts=1566124545.003900&cid=CLNKL1XJP

**Comment by alex-kukhtin** [comment]
Проект не забывай назначать на issue!
