### ISSUE TITLE
Возможность вводить серию и номер паспорта в строку ИНН сотрудника (физлица)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1059]
И также добавить во всплывалке соответствующий комментарий

**Comment by Illya-Lykhachov** [comment]
Сделано. Только не комментарий, а валидатор

**Comment by alex-kukhtin** [comment]
Hint надо!!!!
"В это поле вводится ИНН (10 цифр) или серия и номер паспорта (две буквы и 6 цифр)
