### ISSUE TITLE
Виплата. Картки -- выводится не то сообщение-подсказка. Не к той операции.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1060]
Здесь должно ссылаться на ведомость, а не на ПІБ и ІПН.
![image](https://user-images.githubusercontent.com/42540074/63500267-3ef60e80-c4d2-11e9-9791-986e345b0cd2.png)

**Comment by alex-kukhtin** [comment]
Там все правильно. Надо только расширить описание.
Или указывается в ведомости.
Это сообщение к счету.

**Comment by Illya-Lykhachov** [comment]
Неправильно "ИНН и номер карты указывается в примечании к платежу". Это выплата по ведомости в которой **список**. Т.е. там много ИННов и карт. В примечание это не поместить.
ИНН и карты указываются в примечании платёжки на конкретного сотрудника, когда не используется зарплатный проект и, соответственно, нет ведомости.

**Comment by alex-kukhtin** [comment]
Блин. Баннер к СЧЕТУ
Напишите в баннере.
"Если это выплата чуваку, то в назначении указывается ИНН и номер карты, если это выплата зарплаты по ведомости, то номер и дата ведомости на выплату зарплаты."

Не усложняйте без необходимости.

Щас будешь кучу кода вставлять, чтобы баннер красивый сделать.

P.S.  Это не обсуждение. это прямой приказ :-)

**Comment by htrofymova** [comment]
готово
