### ISSUE TITLE
МОЖНО ТЕСТИРОВАТЬ Multicompany/Multiuser

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1062]
- Придбання
- Необоротні активи
- Бухгалтерія
  - Рахунки
  - Платежі
  - Платежі в валюті
  - Каса
  - Підзвіт
  - Початковий баланс
  - Бухгалтерська довідка
- Персонал
- Зарплата
- Звітність

**Comment by AlexeyTishkin** [comment]
* Придбання

**Comment by AndriyNesterenya** [comment]
Продажі - операції
http://dev.a2start.com/sales/operations
В списке операций не открываются ссылки "Оплата покупця на рахунок в банку" в доп инфе по счету
Ошибка: File not found 'document/payment_order_in/model.json'

![image](https://user-images.githubusercontent.com/38098758/63715823-4b20f980-c84d-11e9-91e5-c49651527602.png)


https://bookkeepersaas.slack.com/archives/CLNKL1XJP/p1566846069011200?thread_ts=1565963954.001000&cid=CLNKL1XJP

**Comment by AndriyNesterenya** [comment]
Если в выписке полезть в Додатково, и на поле Проекта ткнуть на три вертикальных точки - получится
![image](https://user-images.githubusercontent.com/38098758/63716631-1a41c400-c84f-11e9-83a5-bc13565988d6.png)
если потом ткнуть на само поле Проекта - 
![image](https://user-images.githubusercontent.com/38098758/63716690-465d4500-c84f-11e9-80a2-03a176e10e16.png)

**Comment by AndriyNesterenya** [comment]
В выписке в операции "Повернення коштів постачальником" нет возможности выбрать основание.
В случае возврата денег за неоказанную услугу основание для возврата - исходный счет? платеж - предоплата?
