### ISSUE TITLE
Не полностью обновляется список операций при удалении дочерних документов 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1065]
Если у операции есть дочерние документы - в списке имеется собственно дочерний документ, исходный документ, и открывающееся по (+) доп инфо.
![image](https://user-images.githubusercontent.com/38098758/63517784-5516c580-c4f8-11e9-8921-00828da8a40e.png)

Если дочерний документ удаляется - из списка автоматом пропадает удаленная операция, но (+) с расшифровкой продолжает висеть пока не перезагрузится страница.

![image](https://user-images.githubusercontent.com/38098758/63518138-0fa6c800-c4f9-11e9-863f-af421f54135a.png)

Все бы ничего, но клик по уже несуществующему документу прогнозируемо дает красную ошибку "File not found 'document/cash_warrant_out/model.json'"
![image](https://user-images.githubusercontent.com/38098758/63518210-3664fe80-c4f9-11e9-83cb-8484ad85ce7f.png)
что однозначно низачОт.

**Comment by AlexeyTishkin** [comment]
Исправил.
