### ISSUE TITLE
[мелочь] Не копипастится общая сумма во входящем и исходящем счетах.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1066]
Во входящем  и исхродящем счете копипастится все, что надо, кроме общей суммы
![image](https://user-images.githubusercontent.com/38098758/63520933-35829b80-c4fe-11e9-8f24-1e0db1e2087d.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
