### ISSUE TITLE
Нужно понятное описание ролей

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1067]
![image](https://user-images.githubusercontent.com/26379138/63544356-c2911900-c52d-11e9-9cd6-471e31711d92.png)

Нужно написать понятное описание ролей
(тексты в базе a2security_tenant)

**Comment by kattrina-brekhova** [comment]
https://drive.google.com/file/d/1SPcP0K4EvNLjf1FmXlYVLcLszGOnVALR/view?usp=sharing

перечень возможностей каждой роли
в 255 символов не влазит.
лучше бы увеличить поля.
если нет - тогда буду думать, как сократить
желтым выделила то, что не понятно мне (о каком "налаштуванни" идет речь?)
в описание заносила функционал из матрицы доступа https://docs.google.com/spreadsheets/d/19MDak9NTlYtY7wngpmL-TGcXQBf8S2sCdV7Cb-FzC2s/edit#gid=693985213 и из того, что прошлась ручками
кто больше работал в тестировании - пусть перепроверит меня

**Comment by alex-kukhtin** [comment]
Сделано
