### ISSUE TITLE
Расходная накладная: криво отображается код УКТЗЕД - отображается только артикул

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1068]
В расходной накладной и ее печатной форме криво отображается код УКТЗЕД
Точнее не отображается вообще - в настройках переключаемся на код УКТЗЕД - отображается артикул.

![image](https://user-images.githubusercontent.com/38098758/63582042-f9544700-c5a0-11e9-91dc-1b537a1d23ec.png)

В настройках товара на примере код УКТЗЕД заполнен

**Comment by AlexeyTishkin** [comment]
Диалог называется "Налаштування форми для друку". Настраивается отображение ПЕЧАТНОЙ формы.

**Comment by AlexeyTishkin** [comment]
В рабочей поиск только по артикулу.

**Comment by AndriyNesterenya** [comment]
Ага... Чуток неинтуитивно - пипл дергается.
Попробую объяснить :)

**Comment by AlexeyTishkin** [comment]
В планах от форм отказаться, а диалог не должен ассоциироваться с видом на печати.
