### ISSUE TITLE
"Transaction (Process ID хх) was deadlocked"  - ошибка при проведении счета

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1069]
Ковырялся на Dev в Продажах на уровне создать счет - создать оплату - создать накладную - все пораспроводить и поменять и обратно попроводить.
При проведении счета (ничего выдающегося - просто счет) наехал на невиданное ранее сообщение:
"Transaction (Process ID 67) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."
Со второго раза этот же счет спокойно провелся и позже проблем не возникало.

**Comment by alex-kukhtin** [comment]
Вроде починили. Надо наблюдать
