### ISSUE TITLE
Приказ о приеме на работу - нельзя выбрать "посаду"

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#1073]
Приказ о приеме на работу - нельзя выбрать "посаду", проводит документ без этого поля, и не подсвечивает его красным.
http://dev.a2start.com/personnel/employee

**Comment by Illya-Lykhachov** [comment]
![image](https://user-images.githubusercontent.com/35328100/63762847-39326b80-c8cc-11e9-8b16-8fa56626eb33.png)
Не повторяется. И выбрать даёт и не проводит (кнопка активна, но ничего не делает)

**Comment by GalinaLuk** [comment]
Других людей с другими должностями нормально проводит. 
Что делать, давать права на свой тенат?

**Comment by GalinaLuk** [comment]
Из необычного - установлен низкий оклад (2 тыс грн - это 0,25 ставки)

**Comment by GalinaLuk** [comment]
![Снимок экрана в 2019-08-27 13-03-54](https://user-images.githubusercontent.com/46449132/63763416-5ca9e600-c8cd-11e9-8e66-4a94606c2bbf.png)
