### ISSUE TITLE
Документы старого образца, начиная от Счета - Только просмотр - Глючит режим Внести коригування и Змінити

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1075]
![image](https://user-images.githubusercontent.com/42540074/63766320-97168180-c8d3-11e9-9479-026b4eeab4a1.png)
Внести коригування

![image](https://user-images.githubusercontent.com/42540074/63766341-a269ad00-c8d3-11e9-82aa-6e19873238e1.png)
Змінити

**Comment by AlexeyTishkin** [comment]
Сделал.
