### ISSUE TITLE
Только просмотр - Регл. отчеты - Выход без сохранения созданного отчета с глюком.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1077]
![image](https://user-images.githubusercontent.com/42540074/63766982-0f317700-c8d5-11e9-886b-7b562aaf8481.png)

**Comment by AlexeyTishkin** [comment]
Нужны подробности. Судя по картинке - это открытие авансового отчета в старом интерфейсе (форме).

**Comment by alex-kukhtin** [comment]
А как ты туда попала?

**Comment by Anestezia** [comment]
Как попала не знаю, повторить не могу, может что-то уже подкорректировали по этому вопросу. Но есть другой. Создаются из режима "Только просмотр" додатки к отчетам. Дальше ничего с ними сделать нельзя, но они висят уже прикрепленные и пустые. 
![image](https://user-images.githubusercontent.com/42540074/64160274-5de69000-ce44-11e9-9d60-d4b5c3576a73.png)

**Comment by AlexeyTishkin** [comment]
> Создаются из режима "Только просмотр" додатки к отчетам

Испраил.
