### ISSUE TITLE
Печатные формы документов: Наказ про прийняття на роботу, про звыльнення, про надання выдпустки - плохая видимость, серые строки практически не видны на печати

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1078]

**Comment by kattrina-brekhova** [comment]
в тексте должно быть не серым а черным
проблема решается только если пересохранить приказ в ворде и серый текст заменыить черным. но это не удобно

**Comment by Illya-Lykhachov** [comment]
Сделал метки потемнее во всех печатных документах. Достаточно?

**Comment by kattrina-brekhova** [comment]
распечатали. лучше чем вчера. но все-равно серое. у нас лазерный принтер. на струйном будет еще хуже. нужен черный цвет

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/63843814-afe46d00-c98f-11e9-92c1-7b72fa544f85.png)

**Comment by DenisClone** [comment]
сейчас RGB: 105,105,105
а нужно RGB: 0,0,0

**Comment by Illya-Lykhachov** [comment]
готово
