### ISSUE TITLE
Смена реквизитов при формировании счета для клеинта

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1079]
При формировании счета на оплату сервиса для клиента, указываем наши реквизиты в Привате (теперь для всех клиентов).
Через Приват нам удобней сейчас обрабатывать поступления.

**Comment by alex-kukhtin** [comment]
Напиши здесь реквизиты.

**Comment by alex-kukhtin** [comment]
Или мне в телегу скинь

**Comment by DenisClone** [comment]
Реквизиты уже есть в сервисе. Насколько я знаю, мы формируем эти счета для всех кто пришел с "privatmarket". Теперь такой же счет нужно формировать всем тенантам.

**Comment by alex-kukhtin** [comment]
Блин. Спросишь еще у меня что-нибудь.
Я тебе тоже отвечу - оно уже есть в базе данных :-)
