### ISSUE TITLE
[улучшайзинг] В выписке разрешить "Запам`ятати цей рахунок" для проведенных выписок

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1083]
Опыт показал, что народ в упор не видит в выписках надписи "Запам`ятати цей рахунок" (даром, что цветом выделено).
![image](https://user-images.githubusercontent.com/38098758/63791863-09538a00-c905-11e9-9a56-f3966f40fc73.png)
Потом со временем раздупляются, а в уже проведенной выписке эта штука неактивна и запомнить счет без распроведения уже нельзя.

Не стоит ли разрешить сохранение счета у контрагента на проведенных выписках?

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by kattrina-brekhova** [comment]
где вы там видите "запам’ятати цей рахунок"?
![image](https://user-images.githubusercontent.com/38099938/64726841-2630b580-d4e0-11e9-8199-e36c8fb80715.png)

**Comment by AlexeyTishkin** [comment]
> где вы там видите "запам’ятати цей рахунок"?

Есть что запоминать ? Счет как был выбран ? Если отменить проведение - появится ?

**Comment by kattrina-brekhova** [comment]
а, есть!
