### ISSUE TITLE
Косяк в верстке в Выписках (Проекты)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1084]
Если в выписке полезть в Додатково, и на поле Проекта ткнуть на три вертикальных точки - получится
![image](https://user-images.githubusercontent.com/38098758/63716631-1a41c400-c84f-11e9-83a5-bc13565988d6.png)
если потом ткнуть на само поле Проекта - 
![image](https://user-images.githubusercontent.com/38098758/63716690-465d4500-c84f-11e9-80a2-03a176e10e16.png)

https://bookkeepersaas.slack.com/archives/CLNKL1XJP/p1566848312012900?thread_ts=1565963954.001000&cid=CLNKL1XJP

**Comment by alex-kukhtin** [comment]
Вроде ж уже поправили.

**Comment by AndriyNesterenya** [comment]
Да, не обновилось у меня.
