### ISSUE TITLE
Отчет Оборотная ведомость по складу: возможно ли в отчете создать колонку с ценой продажи

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1088]
потенциальный клиент, занимается производством  и продажей продукции, цена на которую сезонно отличается. ему нужна аналитика стоимости продукции на складе по цене продажи
с прайс-листами работает. я не знаю, как это сделать технически, но может возможно, чтоб эта информация отражалась.

у нас есть рядок "цена", но НЕ бухгалтера не понимают, что это реальная себестоимость
![image](https://user-images.githubusercontent.com/38099938/63920718-1ded6a80-ca4a-11e9-9994-0f034a6092cb.png)
возможно есть смысл поменять название этой колонки

**Comment by AlexeyTishkin** [comment]
В отчетах, которые показывают обороты за период, добавить цену прайс-листа невозможно. Цена в периоде может меняться каждый день.

**Comment by AlexeyTishkin** [comment]
Если клиента интересует "стоимости продукции на складе по цене продажи", то можно сделать отчет, типа "Остаток на складе в ценах прайс-листа". В нем будет отображен только остаток (на определенную дату) и цена из прайс-листа, которая действует на эту же дату. Ну и сумму, соответственно.

**Comment by kattrina-brekhova** [comment]
да, именно оно!

**Comment by AlexeyTishkin** [comment]
Тогда надо с ним согласовать:
1. Отчет строится на определенную дату (дата одна, нет начала и конца).
2. В отчете только группа колонок "Сальдо на кінець".
3. В отчете выбирается прайс-лист и вид цены.
4. Колонка "Ціна" - цена из выбранного вида цены на выбранную дату.

**Comment by AlexeyTishkin** [comment]
Если да - создать новый issue, а этот закрыть.

**Comment by kattrina-brekhova** [comment]
и соответвенно общее количество и полная стоимость продукции по заданной цене

**Comment by AlexeyTishkin** [comment]
Ну да, группа колонок "Сальдо на кінець": кол-во, цена прайс, сумма = кол-во * цена прайс.

**Comment by kattrina-brekhova** [comment]
пока пусть висит. клиент потенциальный, выносит мозг третий день, не сказал о своем решении

**Comment by Anestezia** [comment]
1. Насчет самой формы складского отчета, говорит, что даже наименование колонки Цена не есть корректным, потому что это и не цена продажи, и не себестоимость, так как не включает в себя зп, аренду, логистику. 
2. Его кейс - Производство, пользуется нашими операциями Виготовлення и Рецептура. Но там не хватает нематериальных затрат. 
3. 1.Предлагает в отчет о складских остатках, валовий прибуток, розрахунок з контрагентами,  добавить отбор по цене (вид цены или прайс), чтоб можно было подставлять свою цену (себестоимость, посчитанную вручную), цену продажи, сводить  разницу. Ему четко нужно видеть, на какой товарной позиции сколько 
3.2. Либо возможность выгрузить в ексель, вручную колонку с ценой заменить на другую колонку со своими данными, а потом обратно затянуть в систему. (что куда будет разноситься -- не понятно)
4. Предлагает сделать самонаборный "Конструктор звітів", чтоб можно было по колонкам добавлять нужный параметр: Контрагент, товар, ціна реалізації...ще щось.
