### ISSUE TITLE
Создать еще одну папку по контрагентам для начисления и оплаты налогов и сборов

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#109]
![31275807_1973444546239720_7719211882057302016_n](https://user-images.githubusercontent.com/38099938/39311986-066dcb3e-4977-11e8-872b-8af4ec6d62b4.png)

**Comment by AlexeyTishkin** [comment]
К обсуждению... Я для фискальных отчетов сделал справочник "Фискальная служба", находится Бухгалтерия - Справочники - Фискальная служба. В частности, для фискальных отчетов нужны налоговые инспекции.
"Контрагенты для начисления и оплаты налогов и сборов" попадают в структуру "Фискальной службы" ? Или нужен еще один справочник ? Или нужно переформатировать справочник "Фискальная служба" ?

**Comment by kattrina-brekhova** [comment]
Просто казначейство в платежном поручении я пока создавала сама. И в качестве контрагента оно не попадает ни в категорию продавцов, ни покупателей

**Comment by Illya-Lykhachov** [comment]
Фискальные службы - это не то. Нужно добавить ещё один вид контрагентов "Бюджет"

**Comment by MaksymTikhomirov** [comment]
> Фискальные службы - это не то. Нужно добавить ещё один вид контрагентов "Бюджет"

+++

**Comment by Illya-Lykhachov** [comment]
Вадим. Для контрагентов нужно добавить ещё одну роль "Бюджет" (получатели налогов и взносов). Это просто фильтр дополнительных свойств не предполагается.

Алексей. Фискальные службы нужно перенести в контрагенты, добавить роль "Фискальные службы" и закладку со свойствами. У налоговых есть код ЕГРПОУ, значит они могут участвовать в хозяйственной деятельности и выступать нашими контрагентами. В отчёты-справочники-фискальные службы просто отфильтруй их из контрагентов, и диалог создания/изменения используй контрагентовый.

**Comment by kattrina-brekhova** [comment]
Добрый вечер. А есть уже справочник по бюджетам?

**Comment by Illya-Lykhachov** [comment]
Уточнение:
- добавляем роль "Госорганы". Сюда относятся фискальные службы, органы статистики и прочие мздоимцы и контролёры.
- фискальная служба одна и это свойство нашего предприятия (ссылка на контрагента-госорган).

**Comment by nik-man** [comment]
"Держоргани" понятное, но как-то не звучит. Ну и, наверное, могут быть негосударственные контролирующие организации, международные например? Еще торговые палаты, объединения, фонды. Может просто "Організації" ? Хотя, может, я заморачиваюсь.

**Comment by AlexeyTishkin** [comment]
Фискальные службы сделали по другому: [584](https://github.com/a2develop/app/issues/584)
