### ISSUE TITLE
Возможность ввести паспорт вместо ИНН в свойствах физлица-контрагента

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1100]
С последующим подтягиванием в НН и другие связанные доки (если есть), как есть, без префиксов.
![image](https://user-images.githubusercontent.com/42540074/64009361-66775780-cb20-11e9-9d4a-57a75181060b.png)

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AlexeyTishkin** [comment]
> С последующим подтягиванием в НН

Физ. лицо не может быть плательщиком НДС, поэтому в НН будет условный ИНН.

**Comment by Anestezia** [comment]
Проверила, физлицо не ругается на ввод паспорта в списке контрагентов, а нн идет с условным кодом. Дало создать фоп с таким же паспортом, плательщика НДС и в НН подставилось.
