### ISSUE TITLE
Под ролью бухгалтер попадает на несуществующий урл

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1104]
Создал нового пользователя, дал ему доступ к основному предприятию, роль бухгалтер.
При первом входе в учетку (залогинился), такая ошибка.
Откуда то подтягивается лишний /home/ в урле.

![image](https://user-images.githubusercontent.com/42002015/64017636-c8d95380-cb32-11e9-8f5a-2c0225540516.png)

У Лёши была такая последовательность перед ошибкой:
Роль бухгалтер. Закрыл закладку. Открыл новую и захожу на сервер. Сразу открывает этот урл.

**Comment by DenisClone** [comment]
Устойчиво повторил:
1. Из закладки или истории браузера (или еще откуда) открываем урл: http://dev.*******.com/home
2. Логинимся под бухгалтером
3. При входе в урл добавляется лишний  /home/

**Comment by alex-kukhtin** [comment]
done in 7596
