### ISSUE TITLE
РКО - операция "возврат дене покупателю: при выборе системного контрагента - кинцевый споживач, сервис воспринимает его как юрика

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1105]
![image](https://user-images.githubusercontent.com/38099938/64018636-a3017e00-cb35-11e9-9d2f-46514ba6b6ae.png)

здесь странная ситуация - выдача денег всегда происзодится конкретному физику на основании паспорта. 
у нас нет возможности указать в даном документе конкретного физика его паспорты данные, чтоб распечатать док и дать РКО на подпись получателю денег
если же мы будем создавать отдельного физика, у нас по нему будет идти возврат
но в конечном потребилете эта операция не отразиться

**Comment by htrofymova** [comment]
исправлено.
Конкретного физика заполняем в поле "Представник отримувча", его пасп, данные - "Документ, що засвідчує особу отримувача"
