### ISSUE TITLE
Быстрый  выбор произвольного периода/даты в выпадающем календаре

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#1108]
https://docs.google.com/document/d/1YULz9duZ0PRzUG7wQmMDhmxMLIbaUuzfYUs5nQgM5ac/edit?usp=sharing

Внутри 2 картинки, которые предлагают
1. Сверху добавить две ячейки для  ручного ввода дат
2. Возле названия "месяц" и "год" при нажатии на треугольник сделать выпадающий список для выбора опций
Ищу еще

**Comment by GalinaLuk** [comment]
Этот вариант не предлагаю, но привожу в пример, как бывает:
https://tables.finance.ua/ru/currency/cash/-/ua,0,7oiylpmiow8iy1smadi/usd/2#2:0
![4](https://user-images.githubusercontent.com/46449132/64063237-42884480-cbfa-11e9-8057-4c24db95067c.png)

**Comment by kattrina-brekhova** [comment]
да, об этом недавно настя просила здесь https://github.com/a2develop/bugTracker/issues/1330
