### ISSUE TITLE
[Улучшайзинг] Админка (раздел ТЕНАНТИ) - дополнительный функционал для мультифирмы/мультиюзера

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1109]
С внедрением мультиюзерности/мультифирменности назрели изменения в админке (раздел ТЕНАНТИ):
1. Необходимо добавить отображение количества фирм.
2. Желательно добавить отображение списка наименований фирм тенанта в таблицу явно + во всплывающее окно с инфой
3. Исправить глюк - не сортируется список по кол-ву пользователей

![image](https://user-images.githubusercontent.com/38098758/64080838-ea883580-cd00-11e9-86fc-610e3d2dd71b.png)

**Comment by MaksymTikhomirov** [comment]
+++
Важно

**Comment by AndriyNesterenya** [comment]
+ туда же стоит добавить какое-то визуальное выделение (в идеале с возможностью сортировки) тенантов с вручную назначенными тарифами.
... раз уж у нас такая возможность есть и скорее всего аутсорсеры и им подобные будут ходить торговаться.

**Comment by alex-kukhtin** [comment]
Done in 7554

**Comment by alex-kukhtin** [comment]
Насчет ручных тарифов - пишите отдельный issue. Там надо сделать хотя-бы их визуализацию.

**Comment by AndriyNesterenya** [comment]
Во всплывающем окне (выделено на картинке вверху) осталась только инфа по юзерам, кол-во фирм не отображаеся, что нелогично нифига

**Comment by alex-kukhtin** [comment]
А что это за картинка?
Админка уже пару недель как другая.

**Comment by AndriyNesterenya** [comment]
Текущий вид админки на Сервисе:

![image](https://user-images.githubusercontent.com/38098758/65232483-e79b8c00-dad9-11e9-9efb-4df5a5421877.png)

![image](https://user-images.githubusercontent.com/38098758/65232532-feda7980-dad9-11e9-93f2-8579c295ba3f.png)

**Comment by AndriyNesterenya** [comment]
Текущие соображения по желаемому виду таблички в Тенанты/Статистике:
Поля:
1. Тенант
2. Створенний (дата/час)
3. Логін
4. Ім'я
5. Кількість користувачів (+ обязательно сортировка! + желательно список логинов)
6. Кількість фірм (+ открывалка по клику с ЕДРПОУ+Названием)
7. Кількість транзакцій
8. Остання транзакція (дата/час)
9. Розмір БД
10. Залишок на рахунку
11. Статус (юзер-не юзер)

Пример таблички:
[Табличка в админку-Статистика.xlsx](https://github.com/a2develop/bugTracker/files/3702626/-.xlsx)

Хотелки вообще: 
- Сворачиваемое левое меню (на мелких экранах жрет много места);
- [Тенанти-Користувачі] Поиск по полю Примітка (отлавливать кто кого привел из франчей, осоденно если клиента заводили более чем через одни руки);
- [Біллінг-Оплати] Фильтр по периоду (хотя бы квартал, месяц, в идеале - как везде);
- [Біллінг-Оплати] Сортировка/выбор по регистрации (privat, sonata, sales etc.);
- [Біллінг-Оплати] Экспорт в Эксель с учетом фильтра по периоду и и регистрации;
- [Біллінг-Користувачі] Добавить ID клиента в данные таблицы "Нарахування та оплати" (куда проваливаешься при клике на юзере)
- [Біллінг-Користувачі] переименовать столбец "ID" в "Тенант" или "ID клиента" или выводить не только номер тенанта, а и символьную метку типа 1806 -> SA-1806  (в разных местах ID у нас значит то номер платежа, то номер тенанта, путаемся)
