### ISSUE TITLE
Отпуск: при расчете отпускных, на которых припадают праздничные дни из периода следует автоматически вычесть праздничные и нерабочие дни 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1110]
положение 100, пункт 7
https://zakon.rada.gov.ua/laws/show/ru/100-95-%D0%BF

Святкові та  неробочі  дні  (стаття  73  Кодексу законів про 
працю України) ( 322-08 ),  які припадають на період відпустки,  у 
розрахунок тривалості відпустки не включаються і не оплачуються. 
( Абзац другий пункту 7 в редакції Постанови КМ N 348 ( 348-95-п ) 
від 16.05.95 )

**Comment by kattrina-brekhova** [comment]
в приказе на отпуск можно подкорректировать кол-во дней, но в расчетную ведомость автоматически попадает кол-во дней с праздником
в ведомости можно в ручную так же внести правильное кол-во дней

**Comment by Illya-Lykhachov** [comment]
Сделано. Добавлен календарь.
