### ISSUE TITLE
Из операции "Приймання-передача в операційну оренду" создавать оплату

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1113]
У них кейс, аренда у физлица земельного участка. Приход через этот акт сделать-то можно, а как оплатить (прямо из него)? Они у себя на 39 насчитывают ар.плату (затраты будущих периодов), а потом выплачивают из кассы.

**Comment by htrofymova** [comment]
готово. 
Операции оплаты :  ДТ 685 - КТ 301 (311). 39 бух.справкой пусть закрывают.
