### ISSUE TITLE
Доработка админки для механизма мультифирменность

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1115]
1. Предлагаю сделать цифру «количество пользователей» в виде ссылки которая открывает окно со статистикой по пользователям в этом тенанте (для меня например, это более интуитивно).

![image](https://user-images.githubusercontent.com/42002015/64175886-f7be3500-ce64-11e9-93f1-f85f3ccd5708.png)

2. Необходимо добавить информацию о количестве фирм и их данные. Это можно сделать новым пунктом «Фирмы» в разделе «Тенант» (по подобию пункта «Пользователи»). В таблице отображать такие данные: Clientid, логин админа, полное название, ЕДРПОУ, телефон, почта, адрес

Обязательно количество фирм нужно отображать и в пункте «Тенанты» в виде цифры в отдельном столбце (по аналогии с отображением количества пользователей). И так же выводить окно со статистикой, содержание: короткое название, ЕДРПОУ.

3. Добавить индикацию / сортировку / отображение тенантов с вручную измененными тарифами.

4. Еще была мысль добавить поле с комментарием о клиенте. Пример: “нужны бумажные акты”, “производство/услуги”, “нервный” или еще что.

**Comment by alex-kukhtin** [comment]
Вроде все сделано в 7554.
И не пиши по несколько пунктов в одном issue! Ну сколько раз просить?
