### ISSUE TITLE
Оплата любых других налогов, кроме встроенных. Нужна.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1116]

**Comment by alex-kukhtin** [comment]
1. Налог на недвижимость
2. Пени и штрафы
3. И, пожалуй, "Прочие налоги".
Там все равно указывается в назначении платежа.
А получаетель - один хрен, всегда казначейство.

**Comment by AlexeyTishkin** [comment]
Проводки какие ?

**Comment by Anestezia** [comment]
Начисление 92 - 641
Выплата 641 - 311. 
Возникает вопрос аналитики, все налоги скопом будут валиться на 641 и их четко не отделить. Например, акциз и недвижимость, и земля. Что делать в этом случае?

**Comment by Anestezia** [comment]
и штрафы на 642

**Comment by AlexeyTishkin** [comment]
Добавлена операция "Перерахування інших податків". Дб 6419 - Кр 311. При выборе данной операции в платежном поручении/строке банковской выписки появляется селектор "Податок".

**Comment by AlexeyTishkin** [comment]
Начисление в операцию перечисления не вписывается, т.к. для каждого налога свой механизм. К примеру, акциз начисляется так же как НДС и на 92 не относится.
По поводу начислений - нужен отдельный issue с формализацией.

**Comment by AlexeyTishkin** [comment]
Для перечисления штрафов по налогам используем операции по перечислению самих налогов. Т.е. для перечисления штрафа по единому налогу используем "Перерахування єдиного податку".

**Comment by Anestezia** [comment]
641/«Податок з реклами», екологічний податок/641, Рентна плата/641, Транспортний податок (збір) 641,

 Туристичний збір/642, збір за здійснення деяких видів підприємницької діяльності (642/«Торгові патенти»), 
Є ще пенсійний збір (наприклад, при купівлі авто) 642, та не ЄСВ.  В принципе можно по тому же принципу на 642 сделать операцию Інші обов'язкові платежі.

**Comment by AlexeyTishkin** [comment]
Добавил.
