### ISSUE TITLE
[multiuser Security BUG] По ссылке с окна приветствия дополнительный пользователь имеет доступ к свойствам основной фирмы тенанта

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1117]
Ситуация:
Имею аккаунт с основной фирмой А.
В своем аккаунте создаю доп. фирму В.
Создаю пользователя, имеющего полный доступ к доп. фирме В, которому запрещен доступ ко всем остальным фирмам тенанта.
Результат: 
При этом у юзера с полными правами на фирму В нет возможности править реквизиты фирмы В
![image](https://user-images.githubusercontent.com/38098758/64194256-55fc0f80-ce87-11e9-89e8-61e37eaea81e.png)
Зато по ссылке с окна приветствия это юзер чудно попадает в мастер свойств основной фирмы аккаунта А.

**Comment by AndriyNesterenya** [comment]
Ситуация лечится демонстрацией ДРУГОГО приветственного окна для доп. юзеров, в котором сказано, что по всем вопросам обращайтесь к администратору с мылом + телефоном из свойств главного юзера.
Или вообще приветственное окно дополнительным не показывать.

Ну или нужно давать юзерам с полными правами возможность править фирмы, к которым есть полный доступ (что делать с ссылко на старом окне приветствия - все равно неясно).

**Comment by alex-kukhtin** [comment]
Починил

**Comment by AndriyNesterenya** [comment]
Все починилось, кроме ситуации когда у юзера права "Только просмотр" - он все равно видит дашбоард может с приветственого окна править параметры текущей фирмы

**Comment by AndriyNesterenya** [comment]
... ничего не изменилось. Юзер с правами "только просмотр" может править свойства фирмы, на которую у него только просмотр

**Comment by alex-kukhtin** [comment]
Таки починил вроде.
