### ISSUE TITLE
Сохранять свормированный счет на оплату сервиса БК, и показывать его в админке для удобного разнесения оплат

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1119]
При нажатии клиентом кнопки - "Сформировать счет" на оплату сервиса БК, сохранять калькуляцию выбранных им услуг (блок "расчет тарифа"), с привязкой к номеру счета.
В админке можно добавить новый пункт "Счета" в разделе "Биллинг", и в нем выводить все такие сохраненные счета с указанием id и логина тенанта.

**Comment by alex-kukhtin** [comment]
А смысл какой? Если юзер десять раз кнопку нажмет, я тебе десять счетов сохраню. Что ты с ними делать будешь?

**Comment by alex-kukhtin** [comment]
Я могу тебе показать текущее состояние, все предыдущие и когда оно менялось.

**Comment by alex-kukhtin** [comment]
Состояние меняется когда юзер добавляет/удаляет фирму/юзера.

**Comment by DenisClone** [comment]
В принципе подойдет и такой вариант.
Мне казалось, что там есть дополнительно выбор периода оплаты (количество месяцев).
Но в текущем состоянии ЛК, вполне подойдет ваш вариант.

**Comment by alex-kukhtin** [comment]
Закрывайте это нафиг. Непонятно, что с этим делать.
