### ISSUE TITLE
Перенос из Исходящего счета в Акт услуг с материалами Названия для печати, отсутствует для материалов.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1123]
Счет исходный
![image](https://user-images.githubusercontent.com/42540074/64256101-682f8980-cf2b-11e9-9644-99bb5e65240c.png)
Акт
![image](https://user-images.githubusercontent.com/42540074/64256124-7382b500-cf2b-11e9-9fb2-85dc9c76ccf3.png)
Услуга попала со вторым названием, а материал нет.
В самом документе ее не видно, но на печать выводятся по обеим позициям. 
Стоит сделать, чтоб и в самом документе было видно, а то путаница будет.

**Comment by AlexeyTishkin** [comment]
Сделал.
