### ISSUE TITLE
Мои фирмы. Проверка дубликатов

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1127]
Сейчас проверка дубликатов выполняется внутри ТЕКУЩЕЙ фирмы. 
В результате нельзя создать НОВУЮ, если в ТЕКУЩЕЙ есть контрагент с таким-же ЕДРПОУ.

**Comment by alex-kukhtin** [comment]
Done. Надо проверить.

**Comment by AndriyNesterenya** [comment]
Вроде полечилось.
Заводил новые фирмы и контрагентов с одним ЕДРПОУ в разных комбинациях - пока без проблем
