### ISSUE TITLE
Отправка e-mail из сервиса

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1128]
Мы собираемся сделать автоотправку писем с сервиса.
Надо разобраться, что нужно сделать, чтобы не попасть в спам при массовых рассылках.

**Comment by DenisClone** [comment]
Принял.
Предварительно: если будем отправлять через smtp gmail, то проблем не будет.

**Comment by DenisClone** [comment]
Собрал все в Слаке:
https://bookkeepersaas.slack.com/archives/CJQJ3KZFS/p1568032232000900
