### ISSUE TITLE
Аренда у физлица авто/земли/помещения - реализовать

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1129]
Добавить возможность компании арендовать у физлица автомобиля/земельного участка/нежилого помещения

**Comment by AndriyNesterenya** [comment]
Из обсуждения на бух форуме
"- ФОП орендує офіс у фізособи. ПДФО сплачує за неї сам. А військовий збір? Якщо так, то коли саме?

-В момент выплаты аренды, перечисляете оба налога. ВЗ для всех счет один, а вот ндфл с аренды на отдельный счет 85 11010400 00
Назва податку
ПОДАТОК НА ДОХОДИ ФIЗИЧНИХ ОСIБ, ЩО СПЛАЧУЄТЬСЯ ПОДАТ АГЕНТАМИ IЗ ДОХОДIВ ПЛАТНИКА ПОДАТКУ IНШИХ НIЖ З/П

-ВС платится одновременно с НДФЛ и не забудьте про 1 ДФ
"

**Comment by kattrina-brekhova** [comment]
коды в 1ДФ по этим операциям
https://github.com/a2develop/bugTracker/issues/1338

**Comment by Anestezia** [comment]
Login: vitaukrainets@gmail.com
Доброго дня, підкажіть, як провести у програмі 1. акт надання послуг з оренди транспортного засобу у фізичної особи (авто директора) - 685 рахунок 2. утримання з нарахованої суми ПДФО та ВЗ 3. а також з даної суми(після вирахування ПДФО та ВЗ) утримується 25% аліментів


До бази обкладення ЄСВ входять такі виплати фізособі (не суб’єкту підприємницької діяльності): заробітна плата, лікарняні, декретні, а також винагорода за виконання робіт (надання послуг) за цивільно-правовими договорами (ч. 1 ст. 7 Закону № 2464). Відносини, які виникають при укладенні договору оренди, відповідно до ЦКУ не мають ознак правовідносин, що регулюють виконання робіт або надання послуг. Із цим погоджуються і фіскали, про що свідчить їх роз’яснення, розміщене в підкатегорії 301.03 БЗ. Тому дохід фізособи у вигляді орендної плати ЄСВ не обкладається

Отже, за Вашим посиланням оформлення даної операції (оренди авто у ФО) провести неможливо, так як автоматично нараховується 22 % ЄСВ, і проводки відповідно на 661 рах, а потрібно рахунок 685

**Comment by Illya-Lykhachov** [comment]
Два варианта:
1. В существующий договор ГПХ добавить признак "Аренда" и все акты по нему проводить по особым правилам.
2. Сделать отдельный документ "Начисление арендной платы физлицу". Вопрос: в какой раздел сервиса его поместить (это как бы и не зарплата, и не персонал)
В любом случае, придётся делать ещё один метод начисления и во все методы добавить "признак дохода"

**Comment by kattrina-brekhova** [comment]
документ "Начисление арендной платы физлицу". Вопрос: в какой раздел сервиса его поместить (это как бы и не зарплата, и не персонал) — по логике это "придбання"

**Comment by kattrina-brekhova** [comment]
новые кода с апреля
https://news.dtkt.ua/accounting/reposts/60204

**Comment by Illya-Lykhachov** [comment]
сделано

**Comment by kattrina-brekhova** [comment]
вроде все ок
в отчеты попадает
ишью закрываю
