### ISSUE TITLE
Invoice на услугу (импорт услуг) - добавить

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1130]
Нет возможности создать входящий инвойс на услугу.

Инвойс - оплата - акт выполненных работ.

**Comment by AndriyNesterenya** [comment]
по возможности срочно - платящим юзерам надобно постоянно.

**Comment by AlexeyTishkin** [comment]
Нужны подробности:
1. Проводки по каждой операции.
2. Отражение НДС.
3. Отражение в регламентированных отчетах.

**Comment by AlexeyTishkin** [comment]
Сделал.
