### ISSUE TITLE
Не удаляется тенант, не подтвердивший мыло

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1133]
Не могу удалить тенант 1702 из админки

![image](https://user-images.githubusercontent.com/42002015/64532905-1451e580-d31b-11e9-9aee-dcc9c70db210.png)

**Comment by alex-kukhtin** [comment]
Повторить не могу. Все удаляется.

**Comment by DenisClone** [comment]
Да, сейчас все ОК.
