### ISSUE TITLE
новая операция: выдача денег в банк через инкасаторскую службу"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1136]
различие между операцией "выдача денег в банк" от "выдачей через инкассаторов" в получателе.
в случае самостоятельного внесения - ставим сотрудника https://github.com/a2develop/bugTracker/issues/1135
в случае с инкассацией ПАТ "Альфабанк" через інкасаторську службу
основание "інкасація торговльної виручки"
сума - заполняет предприятие
одержав, дата, подпись - не заполняется

**Comment by htrofymova** [comment]
готово

**Comment by kattrina-brekhova** [comment]
супер, спасибо!
