### ISSUE TITLE
Документы по ЗП не видят возврата ЗП. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1137]
Кейс: Начислена и выплачена зарплата. Позже оказалось, что ошибочно перечислили не на тот счет, и банк деньги вернул. Выписка затянута (Повернення ЗП) проведено. 
661 в этом случае закрылся, расход и приход(от возврата) по нему видны. А вот сам документ Выплата зп по банку, созданный из ведомости начисления, считает, что уже зп выплачена и возврата не видит. Не видит возврата и отчет Розрахунково-платіжна відомість. 

В лучшем случае, просто нельзя повторно уже на правильній счет из єтой ведомости начисления выплатить зп. В худшем, если выплатить ее отдельным доком, то следующая зп не выплатится, так как система считает, что по сотруднику переплата.

**Comment by Anestezia** [comment]
Очень просят это решить в кратчайшие сроки, работа стоит, дальше продвинуться нормально не могут.

**Comment by Illya-Lykhachov** [comment]
Сделано
![image](https://user-images.githubusercontent.com/35328100/65658799-d00c5800-e031-11e9-8d88-48ad75fa8bb4.png)

**Comment by Anestezia** [comment]
Из аванса не работает?

**Comment by Illya-Lykhachov** [comment]
Ведомости на выплату без разницы откуда она сделана, из аванса или начисления зп
