### ISSUE TITLE
Рахунок (вхідний і вихідний). Бажано зробити підказку, что зв'язани документи можна зробити тільки для проведенного рахунку.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#114]
Для непроведенных счетов справа можно сделать какую-то пометку справа:
"Щоб створити операції на основі цього документа, його треба провести"
Ее должно быть хорошо видно для непроведенных документов.

Примерно так:
![2018-06-20 2](https://user-images.githubusercontent.com/35918141/41654870-7a3cb09c-7493-11e8-9aca-93c9ba1f0b56.png)

**Comment by nik-man** [comment]
Отзыв тестера:
![2018-06-20](https://user-images.githubusercontent.com/35918141/41654368-e82b018c-7491-11e8-8240-71c18e2f254a.png)

**Comment by AlexeyTishkin** [comment]
А почему именно по этому поводу должно быть сообщение ? Так на каждое "можете" можно по предложению написать... Можете сохранить, але... Можете роздрукувати, але... Можете подивитися проводки, але...

**Comment by AlexeyTishkin** [comment]
Предлагаю продолжить практику Ильи и делать это при помощи общих алертов. Добавил в счета - посмотри.

**Comment by AlexeyTishkin** [comment]
Сделал в счете входящем.

**Comment by AlexeyTishkin** [comment]
Что, в итоге, решаем ?
