### ISSUE TITLE
Компенсация за неиспользованный отпуск

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1141]
По увольняемому сотруднику откорректировала компенсацию за неиспользованный отпуск вручную. Ожидания оправдались, спасибо. НО! При формировании отчета  Расчетно-платежная ведомость для печати красивого результата выяснилось, что в нее не подтягивается компенсация, только сумма по окладу. Печально.
Очень нужен такой же вариант (вручную сумма) для отпускных. Сотрудник в отпуске, а сумма отпускных по окончании сентября будет начислена некорректно. Очень печально. Зоя

**Comment by Illya-Lykhachov** [comment]
И отчёт и суммы руками
