### ISSUE TITLE
Нужны операции с разменной монетой, субсчет 301.1. Кейс пользователя

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1148]

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/1112 - дубль, закрываю

**Comment by kattrina-brekhova** [comment]
Согласно положению Нацбанка 148 от 29.12.2017:
Тобто, розмінна монета, отримана з каси підприємства або залишена в скриньці РРО з попереднього дня, має проводитися через РРО за допомогою операції «службове внесення». 
то есть, предусмотрены операции "отримання з каси підприємства розмінної монети"
проводка в учете Д301.1 - К301
нужна операция "надходження в касу розмінної монети" Д301 - К301.1

**Comment by htrofymova** [comment]
готово. 
1. Бухгалтерія-Довідники: добавлен справочник Підрозділи - создаются подразделения; внутри подразделения - создаются кассьі.
2. Бухгалтерія-Каса: для кассовьіх ордеров длобавленьі операции Внесення до РРО и Винос з РРО; для єтих операция добавлена возможность указать аналитику - Реєстратор.
3. Бухгалтерія-План рахунків: для счета 303 добавлен отчет Оборотно-сальдова відомість по касовим реєстраторам.

**Comment by kattrina-brekhova** [comment]
все супер! 
не понятна операция "инкасация (касса)" . єто по єтой теме? https://github.com/a2develop/bugTracker/issues/1136

**Comment by htrofymova** [comment]
инкассация - заготовка для #1136
