### ISSUE TITLE
Нужна операция в стиле "Возврат суммы банковской гарантии"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1149]
Наехал на ситуацию:
Оформлялась банковская гарантия под обеспечение собственными средствами.
Была перечислена некая сумма на счет банка.
Срок гарантии прошел - деньги вернулись на расчетный счет.
А провести по-человечески - непонятно как.

**Comment by htrofymova** [comment]
А перечисление на банковский счет какой операцией провели?

**Comment by Anestezia** [comment]
Резервування грошових коштів під видану банком гарантію доцільно відобразити проводкою: Дт 313 — Кт 311 (а при їх поверненні — зворотною проводкою: Дт 311 — Кт 313).

Комісію банку за забезпечення гарантії слід віднести до адміністративних витрат (Дт рахунка 92). Адже плата за розрахунково-касове обслуговування та інші послуги банку згідно з п. 18 П(С)БО 16 належить до адміністративних витрат підприємства.

Що стосується інших «тендерних» витрат, наприклад оплати послуг спеціалізованих інтернет-сайтів з надання електронних майданчиків послуг, то їх слід розглядати як витрати на збут (Дт рахунка 93). Оскільки вони спрямовані на реалізацію товарів (робіт, послуг).

**Comment by htrofymova** [comment]
Добавлены 2 операции: 
Платеж контрагенту - Резервування коштів під банківську гарантію : Дт 313 — Кт 311;
Входящий платеж - Повернення суми банківської гарантії: Дт 311 — Кт 313.
Для комиссии банка есть операция - Оплата банківських послуг.

**Comment by AndriyNesterenya** [comment]
Упражнялся на своем реальном кейсе.

Нашел в выписке платежи по гарантии - реквизиты есть.
![image](https://user-images.githubusercontent.com/38098758/71844533-08aadb80-30cf-11ea-830b-b8d2281287b0.png)

выбираю операцию "Резервування коштів під банківську гарантію" - все пропало
![image](https://user-images.githubusercontent.com/38098758/71844627-355ef300-30cf-11ea-8b1c-599cb8592b8e.png)

с возвратом та же история

**Comment by kattrina-brekhova** [comment]
> Упражнялся на своем реальном кейсе.
> 
> Нашел в выписке платежи по гарантии - реквизиты есть.
> ![image](https://user-images.githubusercontent.com/38098758/71844533-08aadb80-30cf-11ea-830b-b8d2281287b0.png)
> 
> выбираю операцию "Резервування коштів під банківську гарантію" - все пропало
> ![image](https://user-images.githubusercontent.com/38098758/71844627-355ef300-30cf-11ea-8b1c-599cb8592b8e.png)
> 
> с возвратом та же история

исправлено?

**Comment by htrofymova** [comment]
В этих операциях контрагентом должен быть банк. Точнее, нельзя самому себе такое перечислить. Вы же делаете "платіж контрагенту", а не "переказ між своїми рахунками". Если в жизни это не так, то расскажите как надо.
