### ISSUE TITLE
Договори. При создании операции теряется фокус.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#115]
Любой отдел, Придбання, Продажи, Запаси.
Раздел Договори.
Выбрать договор, перейти в расширенный список.
Создать документ. Сохранить и закрыть.
Список договоров теряет фокус.

**Comment by alex-kukhtin** [comment]
Ну вот куда ты спешишь? Сделает Вадим обновление, как в контрагентах. Оно и починится.

**Comment by AlexeyTishkin** [comment]
Для объектов сделал.

**Comment by nik-man** [comment]
Проверил. Порядок.
Остались договора.

**Comment by shevchuk-vadim** [comment]
Для договоров сделал.

**Comment by nik-man** [comment]
Проверил, порядок.
