### ISSUE TITLE
О разделении счетов по разным юр.лицам внутри одного тенанта

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#1151]
В связи с введением мультитенантности, нужно доработать функционал формирования счетов на оплату сервиса, т.к. усложняется процесс разнесения оплат и формирования актов.

1.	В ЛК, в разделе «Состояние счета» добавляем чек-бокс «Платить от одного юр.лица»
По умолчанию он активирован и возле кнопки «Сформировать счет» находится поле с выбором всех юр.лиц в этом тенанте. Это юр.лицо будет подставляться в сформированный счет.
(тут нужно подумать, возможно это вообще нужно сделать отдельным списком, в котором можно заводить произвольные юр.лица)
Если клиент снимает птичку, то у него в разделах «Мои фирмы» и «Логины» появляются дополнительные параметры.
2.	В разделе «Мои фирмы», в карточке каждой фирмы, на вкладке «Общая информация» добавляем поле «Расходы выставлять на:» и выбор из списка всех юр.лиц в этом тенанте.
Админ тенанта должен проставить по каждой фирме, юр.лицо на которое будут выставляться расходы.
3.	Такая же точна ситуация и с разделом «Логины». Для каждого логина кроме админа тенанта нужно добавить поле «Расходы выставлять на:» с выбором списка юр.лиц.
4.	В результате, при нажатии на кнопку «Сформировать счет» клиент получит либо один бланк с выбранным юр.лицом, либо получит несколько счетов, с разбивкой в зависимости от настроек.

**Comment by alex-kukhtin** [comment]
Нет. Жуткие и непонятные навороты. Нафига это вообще?

**Comment by alex-kukhtin** [comment]
Не будет этого.
Все фирмы внутри тенанта - это личные проблемы владельца тенанта.
Нас они никоим образом не касаются.

**Comment by AndriyNesterenya** [comment]
Клиенты-аутсорсеры и владельцы холдингов с тобой люто-бешено не согласны.
Хотят и настаивают на возможности платить за фирмы из тенанта со счетов соответствующих фирм.
И если мы видим аутсорсеров-аудиторов своими клиентами - фишка с выбором плательщика таки необходима :(

**Comment by alex-kukhtin** [comment]
Выбор - пофиг. Это не важно.
Важно то, что платежи никогда и ни при каких условиях не разбиваются по фирмам/логинам.
Грубо - есть тенант, есть его стоимость и оплаты.
А кто платит - нам пофиг.

**Comment by AndriyNesterenya** [comment]
нам-то пофиг.
А бухам-аутсорсерам - не пофиг.
И они уже бесятся.
А бедная Настя руками лепит им счета и акты.
