### ISSUE TITLE
Странное поведение Платежки-мемориального ордера Списання до бюджету зобов'язань з ПДВ.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1153]
Если создать в выписке операцию Списання до бюджету зобов'язань з ПДВ, то создается платежка-мемориальный ордер. Она отображается в списке платежей потом после проведения. Если ее открыть и снять с проведения, то потом провести тут же уже нельзя. Кнопка Провести активна, нажимаешь, а ничего не происходит.

В самой выписке эта строка  остается проведенной. 
Также, если саму платежку распровести в самой выписке, то ордер подкрепленный никуда не девается и его можно открыть, а вот провести нельзя изнутри. так как ничего не происходит при нажатии на кнопку Провести. 

Остается только распровести и заново провести сам рядок выписки.

**Comment by AlexeyTishkin** [comment]
Подробней, не могу повторить. Отменил проведение. Провести активна, при нажатии документ проводится.
