### ISSUE TITLE
Внести коригування контрагента в Імпорті запасів - Договор либо обнулять либо подставлять нужный

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1155]
Если отредактировать контрагента, а по старому уже введен договор, то при подстановке нового контрагента остается старый договор по старому контрагенту. Убирается только после распроведения вручную. Если просто снять проведение. а потом тут же провести ничего не меняя, то договор по новому контрагенту не подтягивается. Более того, этот договор наследуется в платежку на основании.

**Comment by AlexeyTishkin** [comment]
Сделал.
