### ISSUE TITLE
Платежи - Основание - добавить в список подбора не только счета неоплач. но и накладные

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1157]
Главное, чтоб не дублировало потребность в оплате. Т.е. сделать так: если есть в цепочке счет, то он главный и он -- основание для оплаты, а если нет, то накладная. Ведь многие счета не вводят, а сразу накладные. (Возможно внутри нужен некий признак, привязана ли накладная к счету).

**Comment by AlexeyTishkin** [comment]
Сделал.
