### ISSUE TITLE
В Edge косячит переключение на API в настройках выписки Привата

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1158]
В Edge на окне настроек выписки переключалка на АПИ выглядит неактивной, при наведении мышки показывает запрещающий значок, но физически кликнуть и переключиться дает.
(На скриншоте значка-курсора не видно)

![image](https://user-images.githubusercontent.com/38098758/65704173-b4836a80-e08e-11e9-8e7e-51c200ba4574.png)

**Comment by alex-kukhtin** [comment]
Не могу повторить.
