### ISSUE TITLE
Bug: В Акте выполненных работ в Придбанні послуг не подтягивается цена при выборе услуги из списка. 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#116]
В Акте выполненных работ в Придбанні послуг не подтягивается цена при выборе услуги из списка.
При Реализации - все ОК

**Comment by AlexeyTishkin** [comment]
При реализации подставляется цена из прайс-листа. А в случае приобретения откуда брать цену ?

**Comment by AndriyNesterenya** [comment]
Решили, что так и надо. 
Отбой.
