### ISSUE TITLE
Отчет 1ДФ: нужна автоматизация отражения сумм доходов и налогов, уплаченных физикам-контрагентам-арендодателям, признак доходов код 106

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1161]

**Comment by Anestezia** [comment]
К сожалению так и не нашли в Вашей программе ,отношения с арендодателями физлицами ,
Арендодателя (физ лицо) , к сожалению нельзя отнести к списку поставщиков, так как по ним насчитывается ВЗ и ПДФО .

Нет возможности начислить орендную плату , и как следствие -выплатить ее с оплатой пдфо и вз. Есть только расчеты с поставщиками , но это не поставщики , это по сути - Кредиторы физ лица . и выплаты должны идти как розрахунок з инш. кредиторам ф.л .


Илья Лихачёв, [05.09.19 11:15]
Если нужно, то придётся в "Персонал", кроме договоров ГПХ и аренду добавлять. Нужно выяснить:
 - как эти налоги/взносы отразить в 1ДФ;
 - не отражается ли аренда в персонификаци для соцстраха (Додаток 4);
 - как выплачивать арендные платежи и перечислять налоги/взносы в бюджет.

**Comment by kattrina-brekhova** [comment]
НДФЛ, начисляется при выплате арендной платы физлицу, уплачивается по местонахождению арендатора (налогового агента).
Отражение в форме № 1ДФ налога и сбора проводится в периоде, в котором такое начисление происходит, уточняющий расчет в таком случае не представляется. Код доходов с признаком 106.
В персонификации Д4 суммы не отражаются - по ним не начисляется ЕСВ.

**Comment by kattrina-brekhova** [comment]
сейчас я попробовала начисление НДФЛ провести бух справкой
![image](https://user-images.githubusercontent.com/38099938/65779906-4fdd1400-e151-11e9-99c7-e587ae993cc2.png)
однако это никак не повлияло на сумму взаиморасчетов с физиком
![image](https://user-images.githubusercontent.com/38099938/65780026-89158400-e151-11e9-8161-8730a7fae714.png)

по факту нужно чтоб с суммы акта с физиком удерживался НДФЛ и ВС и отражение в 1ДФ

**Comment by kattrina-brekhova** [comment]
относительно ЕСВ: не облагается, потому что это не трудовые отношения. 
аренда устанавливается в рамках гражданско-правового договора, к трудовым отношениям не относится

**Comment by Illya-Lykhachov** [comment]
Ну мы же этот вопрос решили. Аренда оформляется договором ГПХ и отражается в учёте актом к нему. Закрывайте уже это issue и отпишитесь клиенту.
