### ISSUE TITLE
Ведомость на выплату зарплаты наличкой: копейки изъяли, на повестке дня - НБУ рекомендует выплаты зарплаты проводить в суммах, кратных 10 коп с соответсвцющим переносом копеек на след месяц

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1164]
пока из клиентов еще ничего никто не просил. но возможно будут просьбы возможность выплаты с перенесением копеек 1,2,3,...9 на следующий период
![image](https://user-images.githubusercontent.com/38099938/66034297-a9f32600-e511-11e9-8b52-acb725fc9d31.png)
![image](https://user-images.githubusercontent.com/38099938/66034314-b1b2ca80-e511-11e9-987d-83f079eb2a5b.png)

**Comment by Illya-Lykhachov** [comment]
До 10 копеек по умолчанию, меньше уже нельзя
