### ISSUE TITLE
Импорт базы контрагентов: открывает окно с ошибкой

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1165]
![image](https://user-images.githubusercontent.com/38099938/66115474-94493380-e5d9-11e9-90ac-faa2ca08a6f6.png)

**Comment by AlexeyTishkin** [comment]
Импорт ? Или экспорт в Excel ?

**Comment by AlexeyTishkin** [comment]
Если экспорт - то исправил.

**Comment by kattrina-brekhova** [comment]
экспорт! да, спасибо
