### ISSUE TITLE
ВЕД-Бета Операции - Некорректное отображение остатков по оплате

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1166]
В Придбання - Операції (beta) есть строка (скриншот)
![image](https://user-images.githubusercontent.com/42540074/66297775-ffa44580-e8f8-11e9-9a93-0d6812f2b98f.png)
смутило вот это Оплачено частково. Залишок: 97 364,81 Потому что есть оплата на полную сумму (скриншот)
![image](https://user-images.githubusercontent.com/42540074/66297816-12b71580-e8f9-11e9-8917-dd91683618b2.png)
101396,48 грн - 4031,67 $ = 97364,81 грн Что, конечно же, не верно

**Comment by AlexeyTishkin** [comment]
Исправил
