### ISSUE TITLE
справочник ПОСАДИ: со встроенного справочника класификатора професий не подгружается профессия с кодом 1210.1

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1169]
![image](https://user-images.githubusercontent.com/38099938/66389002-ff2aae00-e9cf-11e9-9422-ed2e4d127ce8.png)
эта професия не подгрузилась 
![image](https://user-images.githubusercontent.com/38099938/66389036-1073ba80-e9d0-11e9-89c0-0f1955fed8b3.png)
в итоге ничего нет
![image](https://user-images.githubusercontent.com/38099938/66389057-21bcc700-e9d0-11e9-8273-7a88190325ae.png)

**Comment by Illya-Lykhachov** [comment]
неправда Ваша. Всё подгружается

**Comment by kattrina-brekhova** [comment]
подгружается в справочнике професии
![image](https://user-images.githubusercontent.com/38099938/67480488-af531480-f668-11e9-8363-2883da027532.png)

но через справочник посади не загружается
![image](https://user-images.githubusercontent.com/38099938/67480551-d6114b00-f668-11e9-914c-76a4808fe102.png)

![image](https://user-images.githubusercontent.com/38099938/67480563-dc072c00-f668-11e9-93e4-a76e64e0ed47.png)

**Comment by Illya-Lykhachov** [comment]
Не могу повторить на своём аккаунте. Давай пароль от test@3

**Comment by kattrina-brekhova** [comment]
логин test@3.ua
пароль behappy1204

**Comment by kattrina-brekhova** [comment]
ВАТ "Есфель"

**Comment by Illya-Lykhachov** [comment]
Тонкий глюк, Исправил
