### ISSUE TITLE
Отримання рахунку : при открытии не подтягивает номер

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#117]
При клике на ранее созданную операцию "Отримання рахунку" в открывшемся окне не показывает номер рахунку. 

В других операциях номера подтягиваются нормально.

**Comment by AlexeyTishkin** [comment]
Во входящих счетах, накладных,  актах номер изменил формат на строковый. В существующих номер отображаться не будет, только если не внести заново.

**Comment by AndriyNesterenya** [comment]
Создаю, например, "Придбання послуг" - акт.
сохраняю - система автоматом присваивает ему номер какой попало по порядку, в списке операций появляется операция с номером.
Захожу в операцию - поле номера пустое.
Что я делаю не так?

Если тут считаем, что номер берем с чужого акта, и он должен назначаться принудительно при вводе - нужно проверять непустое поле номера при создании, ИМХО.

**Comment by AlexeyTishkin** [comment]
В данном случае при создании нужно указать номер. Автонумерации нет, это входящий номер. В следующем обновлении пустой номер будет подсвечиваться красным.

**Comment by AndriyNesterenya** [comment]
Прекрасно, закрываем
