### ISSUE TITLE
Раздел НА Не работает поиск среди документов по названию контрагента

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1170]
Например, ГО "СТЕЙТВОТЧ". Пишу ГО -- выводит все ГО. Пишу СТЕЙТ, стейт -- не ищет.
![image](https://user-images.githubusercontent.com/42540074/66398046-be3d9400-e9e5-11e9-84bb-b46d746d0369.png)
![image](https://user-images.githubusercontent.com/42540074/66398066-c8f82900-e9e5-11e9-9400-d5b91e3031fd.png)

**Comment by htrofymova** [comment]
Все работает: просто буковка "С" в названии ГО "СТЕЙТВОТЧ" - латинская.

**Comment by Anestezia** [comment]
Тогда должно по другим вариантам буквосочетаний искать. Я пробовала разными кусками, с больших и маленьких букв. У меня сработало только на вотч и все.
