### ISSUE TITLE
Личный кабинет - Начисления абонплаты, убрать в колонке Период название месяца и поставить срок, напр. 29.08 по 29.09

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1172]
![image](https://user-images.githubusercontent.com/42540074/66400182-a9fb9600-e9e9-11e9-8ede-58b2b64a747e.png)
А то получается, например, клиент зарегистрировался 29 марта и получил бесплатный месяц по 29 апреля. 29 апреля ему начислится абонплата и период будет указан Апрель. Получается по актам, что не было бесплатного месяца. 
Нужно вот так период указывать в личном кабинете
 ![image](https://user-images.githubusercontent.com/42540074/66400484-3908ae00-e9ea-11e9-9222-8cd2bf913b80.png)

**Comment by alex-kukhtin** [comment]
done in 7567
