### ISSUE TITLE
[Улучшайзинг] Новая админка - замечания

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1174]
Все красиво, и уже решает кучу проблем

Из замеченных недостатков:

- [Тенанти-Користувачі] Нет поиска по тексту в Примітці
- [Біллінг-Оплати] Нет опции sales в селекторе регистраций (остальные есть)

**Comment by AndriyNesterenya** [comment]
+ всплыло ранее незамеченное.

Если клиент регался через чей-то домен - ему присваивается текстовая метка типа SA-1111
А если этот же клиент делает себе доп. фирмы - у этих фирм получается SE-1112
Конторе так выгоднее :) но рефералы могут напрячься.

**Comment by alex-kukhtin** [comment]
Таки все сделано. Проверяте

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/66994365-cd070380-f0d5-11e9-9f53-5039642e970f.png)

На всплывающем окне предупреждения об удалении стоит явно и жирным шрифтом указывать номер тенанта и логин удаляемого юзера.
Для проверки, на случай косолапости.

**Comment by AndriyNesterenya** [comment]
+ хорошо бы поставить ограничение, чтобы удалить можно только тенанты с неподтвержденной почтой

**Comment by alex-kukhtin** [comment]
Блин, а сейчас как?
Попробуй удалить любой другой.

**Comment by alex-kukhtin** [comment]
Последний раз прошу. Дальше застрелюсь и все. Не пиши разные задачи в одном issue.
