### ISSUE TITLE
Команда "Изменить тип" ТМЦ при отсутствии проведенных документов.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1175]
Для облегчения участи клиентов, успевших не глядя импортировать или ввести все ТМЦ с типом "Товар" нужно сделать команду "Изменение типа" и разрешить менять тип ТМЦ например с "Товар" -> "Готова продукція" (возможно какие-то еще комбинации) при отсутствии проведенных документов.
При наличии таковых документов - предупреждать и просить распровести.

**Comment by AlexeyTishkin** [comment]
Сделал
