### ISSUE TITLE
Если создать счет и сделать его не активным, то в разделе Рахунки-Бухгалтерия его уже нельзя увидеть

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1177]
В разделе Рахунки-Бухгалтерия создала счет, сделала его не активным. обновила или перешла на другую страницу, вернулась и увидела:
![image](https://user-images.githubusercontent.com/42540074/66563818-45fedc00-eb67-11e9-9bdb-40e39294ac94.png)
Должен быть способ показывать не активные, если активного счета и меню с работой с этими счетами.

**Comment by alex-kukhtin** [comment]
Если все счета неактивные, то их не видно.  
Как по мне - ну очень уж искусственный кейс.

**Comment by alex-kukhtin** [comment]
done in 7596
