### ISSUE TITLE
Відомість РРО: выбираю РРО, после нажатия кнопки "провести" он исчезает

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1178]
![image](https://user-images.githubusercontent.com/38099938/66649172-284c7800-ec36-11e9-8cb2-6c32fe46580f.png)
![image](https://user-images.githubusercontent.com/38099938/66649202-42865600-ec36-11e9-9831-cd40ee240a48.png)

**Comment by kattrina-brekhova** [comment]
странно, но при этом в 303 по РРО сумма попадает 
![image](https://user-images.githubusercontent.com/38099938/66650330-0accdd80-ec39-11e9-84db-1724c576a9be.png)

**Comment by AlexeyTishkin** [comment]
Исправил
