### ISSUE TITLE
Операция "Инкасация РРО": в отчет "Оборотно-сальдовая ведомость по кассовых реестраторах" по кредиту 303 счета не попадает сумма инкасации. во всех остальных отчетах по 303 счету сумма операуци попадает

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1179]
![image](https://user-images.githubusercontent.com/38099938/66650648-c8f06700-ec39-11e9-9ecf-98577aa0320f.png)
![image](https://user-images.githubusercontent.com/38099938/66650676-dd346400-ec39-11e9-9c0d-ea14951e06b3.png)

![image](https://user-images.githubusercontent.com/38099938/66650694-e9b8bc80-ec39-11e9-9929-a22ec100fd8c.png)

![image](https://user-images.githubusercontent.com/38099938/66650718-f63d1500-ec39-11e9-807a-9fdcf49d301e.png)

![image](https://user-images.githubusercontent.com/38099938/66650744-02c16d80-ec3a-11e9-92ec-4e04e0f1783d.png)

**Comment by htrofymova** [comment]
исправлено
