### ISSUE TITLE
Проведение/отмена проведения ранее созданных операций : не меняет признак "проведено" при возврате в окно списка

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#118]
В списке операций кликаем на ранее созданной операции;
Переходим в окно операции;
Проводим или отменяем проведение этой операции;
Закрываем окно :

- в списке операций не изменяется состояние метки "Проведено", пока вручную не обновим окно списка.

**Comment by AlexeyTishkin** [comment]
Где именно ? Посмотрел Продажи - Операции - все ок.

**Comment by nik-man** [comment]
Речь идет о списке операций через расширенный список су/оу/договорах.
Там метка "Проведено" не появляется сразу.
Приходится нажимать кнопку "Обновить"

**Comment by alex-kukhtin** [comment]
Fixed in 7173
