### ISSUE TITLE
Отчет РРО - Ввод на основании - Налоговой накладной неплатнику

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1181]
к отчетам РРО прикрепить возможность создавать налоговую накладную на неплатника, чтоб отдельно всю номенклатуру не набирать. 

Только надо описать все особенности: точное название контрагента, условный ИНН и причину.

Возможно будет просто Кинцевий споживач, но выбор, возможно, надо оставить.  условный ИНН и причина - в автоподстановку с возможностью редактирования.

П.С. Заодно это будет заделом для всех НН на неплательщика НДС, где уже давно просили автоподстановку причины и условного ИНН.

**Comment by Anestezia** [comment]
Складена по підсумку операцій на кінець дня.

**Comment by AlexeyTishkin** [comment]
> П.С. Заодно это будет заделом для всех НН на неплательщика НДС, где уже давно просили автоподстановку причины и условного ИНН.

Условный ИНН для неплательщика сейчас должен подставляться.

В обычной реализации причина какая ? Постачання неплатнику податку ?

**Comment by AlexeyTishkin** [comment]
Сделал.
