### ISSUE TITLE
на основании операции "отримання послуг від інших дебіторів" создавать операцию по оплате "перерахування послуг іншим дебіторам.

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1187]
сейчас на основании акта делается операция "оплата постачальнику" где 631 счет
так же нелогична операция "оплата постачальнику з каси" с 631 - на основании акта с 377 счетом
пока из клиентов никто ничего не говорил

**Comment by AlexeyTishkin** [comment]
Сделал.
