### ISSUE TITLE
ОСВ по рахункам в банках, пустой список в подборе счетов

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1189]
![image](https://user-images.githubusercontent.com/42540074/67497468-aec97680-f686-11e9-9630-c12f2437e805.png)
а на самом деле счетов вот сколько
![image](https://user-images.githubusercontent.com/42540074/67497497-bab53880-f686-11e9-85fb-a7ae0c0821e9.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
