### ISSUE TITLE
Невозможно создать новые контрагенты непосредственно из нового документа

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#119]
![31723448_1975898575994317_4600609478159630336_n](https://user-images.githubusercontent.com/38099938/39509929-99a6d27e-4df0-11e8-9de7-0e860531492f.png)

**Comment by nik-man** [comment]
Не только создание. Изменить свойства тоже нельзя.

**Comment by AlexeyTishkin** [comment]
Исправлено.
