### ISSUE TITLE
Опечатка ЕДПОУ на странице свойств фирмы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1190]
https://service.bookkeeper.kiev.ua/home/cabinet/show/3
Особистий кабінет - Мої Фірми - вкладка Загальна інформація

Опечатка ЕДПОУ вместо ЕД**Р**ПОУ

![image](https://user-images.githubusercontent.com/38098758/67717035-9da99e00-f9d5-11e9-8f98-5cfc53f4dd4e.png)

**Comment by AndriyNesterenya** [comment]
Не забываем, пжлст.
Одну ж буковку вставить - и проблемы нет.

**Comment by AlexeyTishkin** [comment]
Исправил.
