### ISSUE TITLE
Обсуждение! Бланк выставляемого счета - расписывать по разным объектам учета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1192]
![image](https://user-images.githubusercontent.com/42540074/67779511-6981bc00-fa6d-11e9-8187-011d76a571e4.png)
Сбоку есть таблица, в которой расписано, сколько лицензий и каких. Как насчет в печатной форме тоже как-то расписывать количество и номенклатуру в таком же ключе. Чтоб напрямую тянуло не только сумму, но и табличную часть.
![image](https://user-images.githubusercontent.com/42540074/67779522-6f779d00-fa6d-11e9-87c6-0edf219de1fc.png)

**Comment by alex-kukhtin** [comment]
Нет. Попробуй написать там не 1275 грн, а, например 2000 и скажи, что в этом случае должно быть в счете?

**Comment by Anestezia** [comment]
Тогда, если сумма не фиксированная, то пусть будет самонаборная (в смысле с селекторами) таблица, за которую услугу и сколько платит клиент. Или таблица статичная, а клиент распихивает суммы по ячейкам. Поставить проверку, если сумма не сходится с той, которая по счету автоматом выставилась.
