### ISSUE TITLE
[Улучшайзинг] Новая админка - дашбоард

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1194]
Для облегчения жизни Максу хочется добавить на дашбоард админки кроме статистики оплат по дням за последние 30 дней еще и статистику оплат за последние 12 месяцев.
Или одновременно или с возможностью переключения 30 дней/12 мес.
В идеале в обеих статистиках исключить оплаты с пометкой "Бонус"

**Comment by AndriyNesterenya** [comment]
+ вспомнилась неприятная особенность.
На сегодня на диаграме оплат вообще не отображаются дни, когда оплат не было - такие дни просто пропускаются.

Низачот, потому как искажает картину динамики, и хорошо бы пустые дни тоже отображать

**Comment by alex-kukhtin** [comment]
Done (10.12.2019)
