### ISSUE TITLE
Лажа с названиями контрагента

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1195]
Имеем проблему, водящую в заблуждение юзера.
В свойствах контрагента пишем, что в документах будет выводиться ПОЛНОЕ название контрагента.
![image](https://user-images.githubusercontent.com/38098758/67949808-10429580-fbf1-11e9-9c6b-bf56ef1d05a6.png)

А в счетах-накладных реально выводим сокращенное.
![image](https://user-images.githubusercontent.com/38098758/67949684-d07bae00-fbf0-11e9-8c6a-e8f3fa765ce4.png)

**Comment by AlexeyTishkin** [comment]
Нужен полный перечень печатных форм, где не выводится полное наименование.

**Comment by AndriyNesterenya** [comment]
Да везде...

- Рахунок (вхід)
- Акт виконаних робіт
- Видаткова накладна
- Вхідний платіж (оплата по банку)
- Прибутковий касовий ордер (оплата по касі)
- Рахунок (вихідний)
- Видатковий касовий ордер - собственное название
- Платіжне доручення

И собственное название и название контрагента выводится краткое, а не полное.
По логике вещей краткое должно выводиться, если полное не заполнено.

**Comment by AlexeyTishkin** [comment]
Сделал.
