### ISSUE TITLE
Опять неприбыльные просьбы

### ISSUE THREAD

**Issue by htrofymova** [a2develop/bugTracker#1198]
В операциях "Безоплатне одержання запасів", "Введення в експлуатацію ОЗ, НМА" сделать возможность вьібрать 48-й счет (как в кассовом ордере и платежном поручении).
В "Бухгалтерскій довідці" також - операція "Визнання операційного доходу за рахунок цільових надходжень"

**Comment by htrofymova** [comment]
"Введення в експлуатацію ОЗ, НМА" сделала

**Comment by Anestezia** [comment]
В операцию "Визнання операційного доходу за рахунок цільових надходжень" сделать выбор счета.

**Comment by AlexeyTishkin** [comment]
Вместо выбора счета добавлена отдельная операция "Безоплатне одержання необоротних активів".
Тестирование [здесь](https://github.com/a2develop/testing/issues/472).
