### ISSUE TITLE
Добавить операцию Переказ між своїми рахунками у валюті

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1199]
Не очень удобно, что нет возможности перевода между своими счетами в иностранной валюте. В Райффайзен Банк Аваль у клиентов есть основной и транзитный долларовые счета. Валюта приходит на основной, а до 20 июня 2019, когда действовала обязательная продажа - 50% суммы в долларах перечислялось на транзитный счет. Также транзитный счет используется для продажи остатка в валюте. Сейчас, чтобы отразить историю в операциях, приходится делать проводки: 1. Исходящий платеж с основного счета на счет в банке (хотя это наш счет), операция "Перерахування валюти для продажу" 2. Входящий платеж на транзитный счет, операция "Повернення непроданої валюти" или "Надходження придбаної валюти", хотя ни то, ни другое не отражает сути

**Comment by AlexeyTishkin** [comment]
Добавил.
