### ISSUE TITLE
Платежное поручение - оплата поставщику: при выборе документа основания - накладной, сумма платежа становится такой же как и в накладной. изначально в платежку вносила другую сумму

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1202]
создаю платежное поручение, ввожу сумму. потом указываю документ - основание - накладную - на сумму большую чем платежное поручение. сервис автоматически подставляет сумму из накладной

**Comment by AlexeyTishkin** [comment]
Так и должно быть. При выборе наследуются все реквизиты, в т.ч. неоплаченная сумма Счета/Накладной/Акта. При желании после выбора сумму можно изменить.
