### ISSUE TITLE
Проблемы при заполнении декларации ЕН ФОП - мультифирменность

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1203]
1. если в другой фирме уже существует отчет за этот период - в новой фирме отчет создаваться не хочет
![image](https://user-images.githubusercontent.com/38099938/68307515-0cf94f00-00b4-11ea-93df-54c7703488cb.png)
нажимаю ок и снова провести - проводит

2. при нажатии через декларацию ЕН на документ расчета налогов - чтоб открыть
![image](https://user-images.githubusercontent.com/38099938/68307589-30bc9500-00b4-11ea-9737-20c94a10d1c8.png)

выдает такую ошибку
![image](https://user-images.githubusercontent.com/38099938/68307632-416d0b00-00b4-11ea-8eee-22b5adbda448.png)

3. создаю отчет за 2 квартал по новой фирме. в строку 13 (нараховано за попередній звітний період - значення рядка 12 декларації за попередній період) вписывается сумма другая, чем в рядке 12 декларации из новой фирмы. смотрите:

в отчете за 1 квартал вот так
![image](https://user-images.githubusercontent.com/38099938/68307779-72e5d680-00b4-11ea-968b-0aebdba9a841.png)

в отчете за 2 квартал вот так
![image](https://user-images.githubusercontent.com/38099938/68307819-82651f80-00b4-11ea-9bd7-0acaa48ea71a.png)

внимание! эта сумма - 6700 - наследует данные отчета за 1 квартал первой фирмы

![image](https://user-images.githubusercontent.com/38099938/68307882-99a40d00-00b4-11ea-8d71-3530218c7a85.png)

о чем жаловалась клиентка

**Comment by AlexeyTishkin** [comment]
Исправил
