### ISSUE TITLE
Переведіть текст помилки українською

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1208]
![image](https://user-images.githubusercontent.com/38099938/68854440-b65bc880-06e4-11ea-9f7c-9da6277f6063.png)

ошибка нормальная, правильная. начала создавать налоговую. потом в другом окне изменила на другую фирму. поэтому налоговая не провелась - мол я находилась в другой фирме.

**Comment by AlexeyTishkin** [comment]
Перевел.
