### ISSUE TITLE
Вопрос отображения МФО в Счете и Платежках

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1209]
Переходный период вроде как продлен до 12.01.20. Из разъяснений о заполнении платежки везде приведена эта картинка. Код банка при применении айбан, 0.
![image](https://user-images.githubusercontent.com/42540074/68874006-2da35380-0709-11ea-8bba-3f9cbb6523a7.png)

**Comment by AlexeyTishkin** [comment]
В Счете в реквизитах в случае IBAN, МФО вообще не показывать ?

**Comment by AlexeyTishkin** [comment]
Сделал.
