### ISSUE TITLE
Почему в расходном кассовом ордере по операции "оплата поставщику" может быть выбрано юр. лицо, а в возврат покупателю или оплата другим дебыторам - только ФЛ или ФЛП?

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1211]

**Comment by htrofymova** [comment]
Попыталась найти ответ... Не знаю, почему. Если нужно убрать ограничение - уберу.

**Comment by kattrina-brekhova** [comment]
когда-то - в сентябре 2018 - мы обсуждали эту тему: так как в расходном ордере обязательно нужно указывать фио получателя и его подпись, решили ограничить подобные операции с кассы только на физ лиц и фопов
сейчас смотрю, что в ордере предусмотрена строка для указания получателя (представителя получателя)
но если честно прямого запрета в законодательстве (кроме как ограничений расчетов предприятиями между собой) я не нахожу. а если есть лимит по расчетам между предприятиями, значит эти операции законны
поэтому считаю, раз у нас есть строка для указания фио представителя компании, есть смысл снять запрет

**Comment by kattrina-brekhova** [comment]
http://www.visnuk.com.ua/uk/publication/100004908-bezpechna-robota-z-gotivkoyu

**Comment by htrofymova** [comment]
готово
