### ISSUE TITLE
Платежное поручение: оплата других налогов: неявная верстка и окна с выбором налога (прячется за окном "комментарий"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1213]
![image](https://user-images.githubusercontent.com/38099938/69145079-7d9d6400-0ad5-11ea-91d4-be8f256d0cdc.png)

**Comment by kattrina-brekhova** [comment]
то же самое "перерахування инших обоязкови платежив"

**Comment by alex-kukhtin** [comment]
Done in 7585
