### ISSUE TITLE
В свойствах объекта учета сразу отображать счет учета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1217]
![image](https://user-images.githubusercontent.com/42540074/69246113-c83fde80-0bb0-11ea-9b87-40aad5d90e32.png)

**Comment by AlexeyTishkin** [comment]
В каком месте и в каком виде ?

**Comment by Anestezia** [comment]
Есть место над окном Ставка ПДВ. Там просто указать его, без подбора. справочно.

**Comment by AlexeyTishkin** [comment]
Сделал.
