### ISSUE TITLE
Вопрос: Почему в 1420 баланса при нулевых движениях по 441-442 счету есть сумма.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1218]
[Загальна оборотно-сальдова відомість.xlsx](https://github.com/a2develop/bugTracker/files/3875034/-.xlsx)
[Фінінсовий звіт.pdf](https://github.com/a2develop/bugTracker/files/3875040/default.pdf)

**Comment by AlexeyTishkin** [comment]
В данном случае это корректировка равенства баланса.
Актив = 1131.8
Пасив = 1131.9
Разница = -0.1 идет в 1420.
Погрешность образовывается из-за перевода оборотов в тыс. грн.: суммы делятся на 1000 и округляются до 1-го знака.

**Comment by Anestezia** [comment]
Все равно спрашивают, почему именно в эту строку идет такая корректировка, ведь это не правильно, если по тем счетам нет движений

**Comment by AlexeyTishkin** [comment]
Тогда нужна формализация заполнения отчета.
В данном конкретном случае что делать с не равенством баланса в тыс. грн ? В грн баланс сходится.

**Comment by AlexeyTishkin** [comment]
Почему есть сумма - понятно.
Если нужно менять алгоритм заполнения, то отдельный issue с описанием алгоритма.

**Comment by Anestezia** [comment]
А если добавить сразу сообщение всплывающее, чтоб бухгалтер уже сам выбирал, в какую ячейку закинуть эту погрешность? С себя ответственность снимем, клиента предупредим, что имеет место погрешность. 

Возможно, с полным разворотом расчета со знаками после запятой в тыс.грн.
Или сделать внутренний отчет-расшифровку (Детальніше, как в документе Нарахування податків) и там эту информацию предоставить. Я думаю, это значительно облегчит работу бухгалтеру, сразу будет видно, где и что пошло.

**Comment by AlexeyTishkin** [comment]
> Или сделать внутренний отчет-расшифровку

Как именно расшифровывать ? Вот в этом конкретном случае что должно быть написано ?

**Comment by AlexeyTishkin** [comment]
> чтоб бухгалтер уже сам выбирал, в какую ячейку закинуть эту погрешность

Для этого нужно самим понимать какие варианты есть.

**Comment by kattrina-brekhova** [comment]
изучала этот кейс
неравенства могут быть, такое случается
дельту округлений нужно вводить в строки баланса, которые не проверяется
например, строки по налогам, по зарплате, по расчетным счетам, по установному капиталу вносить не нужно
а вот в строках запасов, дебиторки и кредиторки можно отразить эту дельту

**Comment by AlexeyTishkin** [comment]
Вместо 1420 в какую именно строку переместить ?

**Comment by kattrina-brekhova** [comment]
если отвечать прямо, то скорее сюда подойдут следующие строки (если это Баланс) 1100 (1101, 1102, 1103, 1104), 1125, 1615
если это отчет субъекта малого предпринимательства, то строки: 1100, 1125, 1615
если это упрощенный отчет субъекта малого предпринимательства, то: 1100, 1155, 1615

**Comment by AlexeyTishkin** [comment]
Одной строкой обойтись можем ? В балансе 1420 меняем на какую ?

**Comment by kattrina-brekhova** [comment]
а вот не уверена
а если в выбранном нами строке у клиента не будет никаких сумм? и если дельта минусовая пойдет
а если все-таки служебное сообщение, мол при округлении результатов строк баланса возникла дельта между пассивом и активом. откорректируйте сумму разницы в ручном режиме. рекомендуемые строки баланса такие то.....

**Comment by AlexeyTishkin** [comment]
> а если все-таки служебное сообщение

Можно и сообщение :)
Тогда полный текст, пжл.

**Comment by kattrina-brekhova** [comment]
добро, надо подумать

**Comment by kattrina-brekhova** [comment]
При заповненні звіту виникла дельта заокруглення рядків, і призвела до того, що підсумки Активу та Пасиву не збігаються. В ручному режимі відкорегуйте необхідний рядок на суму різниці.
Рекомендовано використовувати рядки: 1100, 1125, 1155, 1615.

**Comment by kattrina-brekhova** [comment]
важно, чтоб это сообщение выпадало только если разница между активом и пасивом только из-за округления
до какого момента это делать? во время "провести", или до этого? после "заполнить"?
есть всплывающее окно что сумма актива и пассива не совпадают (но они вызваниы ошибками в учете). а округления - это не ошибка

**Comment by kattrina-brekhova** [comment]
и нужно обдумать, эта дельта будет показываться в каком-то из рядков другим цветом вместе со всплывающим сообщением?
или это просто служебное сообщение при нажатии "провести"?

**Comment by AlexeyTishkin** [comment]
Только при нажатии "Заполнить". Там получение оборотов, расчет, округление. На проведении контроль равенства Актива Пасиву. Почему нет равенства (ошибка в учете, округления) уже неизвестно, т.к. пользователь после заполнения может редактировать данные.

**Comment by AlexeyTishkin** [comment]
> и нужно обдумать, эта дельта будет показываться в каком-то из рядков другим цветом

Будет только в сообщении.

**Comment by kattrina-brekhova** [comment]
> Только при нажатии "Заполнить". Там получение оборотов, расчет, округление. На проведении контроль равенства Актива Пасиву. Почему нет равенства (ошибка в учете, округления) уже неизвестно, т.к. пользователь после заполнения может редактировать данные.

+++

**Comment by Anestezia** [comment]
Предупреждение, это хорошо, но нужно его в правильном месте и без уже сделанного распределения, или скинуть остаток округления в ячейку и тут же выдать это сообщение. Типа мы закинули сюда, но вам рекомендуется проверить вручную

**Comment by AlexeyTishkin** [comment]
Сообщение будет после нажатия "Заполнить". Никакого распределения не будет. Сумма разницы только в сообщении.

**Comment by AlexeyTishkin** [comment]
Автоматическая корректировка погрешности округления в строку 1420 заменена сообщением. В случае возникновения погрешности сообщение выдается в момент заполнения отчета (кнопка "Заполнить").

**Comment by kattrina-brekhova** [comment]
а решили только для отчета Фінансовий звіт суб'єкта малого підприємництва делать?
а для остальных форм стат отчетности?

**Comment by AlexeyTishkin** [comment]
> а решили только для отчета Фінансовий звіт суб'єкта малого підприємництва делать?

Ну именно в нем возникла проблема. В первом сообщении прикреплен pdf клиента.

**Comment by AlexeyTishkin** [comment]
> а для остальных форм стат отчетности?

Там тоже есть проблемы ?
Изначально эти отчеты делал Вадим. Я разбирался только с S0110011.

**Comment by kattrina-brekhova** [comment]
ну вообще такая ситуация может возникнуть с любым стат отчетом
и я общалась с бухгалтерами - не зависимо - это статотчет малого или большого предприятия (баланс) - и все они говорили, что строка 1420 для дельты округления не годится

**Comment by kattrina-brekhova** [comment]
лучше дать юзеру самому решать куда внести эту дельту

**Comment by AlexeyTishkin** [comment]
> ну вообще такая ситуация может возникнуть с любым стат отчетом

Тогда остальные отчеты надо проверять на этот кейс...
Пример отчета с проблемой делаем на тестовом аккаунте и отдельный issue.

**Comment by kattrina-brekhova** [comment]
Леша, тогда если сообщение отдельно для этого отчета, оно должно быть таким:

При заповненні звіту виникла дельта заокруглення рядків, і призвела до того, що підсумки Активу та Пасиву не збігаються. В ручному режимі відкорегуйте необхідний рядок на суму різниці.
Рекомендовано використовувати рядки: 1100, 1125, 1615

я просто не знала, что это только для 1 отчета, думала, что оптом для всей статотчетности делаем

**Comment by kattrina-brekhova** [comment]
> 
> Тогда остальные отчеты надо проверять на этот кейс...
> Пример отчета с проблемой делаем на тестовом аккаунте и отдельный issue.

а как проверить?
служебное сособщение возникает при автоматическом заполнении отчета
ввести операциями цыфры из оборотки, которую пользователь дал?

**Comment by AlexeyTishkin** [comment]
> а как проверить?

Для S0110011 простой кейс проверки: https://github.com/a2develop/testing/issues/475#issuecomment-581874538

По поводу остальных отчетов - я не знаю... Можно попробовать по такому же принципу. Смысл в том, что:
1. Обороты до округления должны сходиться.
2. Заполнено несколько строк. При округлении каждой возникает общая погрешность.
3. Обратить внимание на строки, которые согласно оборотов должны быть пустые.

**Comment by AlexeyTishkin** [comment]
> думала, что оптом для всей статотчетности делаем

Одна проблема - один issue :)

**Comment by kattrina-brekhova** [comment]
> > думала, что оптом для всей статотчетности делаем
> Одна проблема - один issue :)

а как же тогда? во всех отчетах разные коды строчек

**Comment by AlexeyTishkin** [comment]
> во всех отчетах разные коды строчек

Поэтому каждый отчет индивидуально и рассматриваем...

**Comment by kattrina-brekhova** [comment]
проверила баланс, разницу вносит в 1420 строку
![image](https://user-images.githubusercontent.com/38099938/73760889-afd66d80-4776-11ea-9094-b9a3871a973d.png)

**Comment by AlexeyTishkin** [comment]
> проверила баланс, разницу вносит в 1420 строку

Пример отчета с проблемой делаем на тестовом аккаунте и отдельный issue.

**Comment by kattrina-brekhova** [comment]
хорошо, сделаю отдельным ишью
в упрощенном отчете малого предпринимательства такая ошибка не вылазит. там кредит по 631 и дебет по 681 отдельно считает одной суммой в строке 1155
не знаю, может есть смысл с другими счетами проверить

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/73761881-19a34700-4778-11ea-9378-a787f9b70477.png)

**Comment by kattrina-brekhova** [comment]
логин test@3.ua

пароль behappy1204

фирма "чупакабра"
