### ISSUE TITLE
Видатковий касовий ордер - Выдача с кассы в банк: Нельзя выбрать получателя

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#122]
Кому будут выдаваться деньги? Если это не инкассация, а деньги в банк сдает уполномоченный сотрудник, то в РКО нужно указать данные такого физ лица. ??

**Comment by kattrina-brekhova** [comment]
Если это не случай с инкассацией, то на практике, банки, принимая такую наличку, выдают квитанцию, где указывают "принято от ООО "Буккипер" через Сидоренко Вячеслав Вячеславович"...

**Comment by shevchuk-vadim** [comment]
Так и должно быть. Цитата из положения о ведении кассовых операций:
Реквізити у видатковому ордері "Одержав", "Дата", "Сума", "Підпис одержувача", дані документа, що засвідчує особу отримувача [які заповнюються отримувачем готівки (додаток 3 до цього Положення)] та в прибутковому ордері "Прийнято від" не заповнюються в касових ордерах, які оформляються на загальну суму проведених установою/підприємством касових операцій (видача готівки за видатковими відомостями, електронними платіжними засобами, здавання готівки до банку, отримання готівки з банку за чеком та оприбуткування її в касі). Інші реквізити в касових ордерах та видаткових відомостях є обов'язковими до заповнення.

**Comment by kattrina-brekhova** [comment]
++
