### ISSUE TITLE
Расходные кассовые ордера: в электронной форме документов нужно создать строку "Додаток", где можно указывать прикрепленные документы к расходу (супровідна відомість інкасатора, квитанція, платіжна відомість...)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1221]
на даный момент строка "додаток" есть в печатной форме документов, но это предполагает только внесение информации от руки

**Comment by kattrina-brekhova** [comment]
речь идет об операциях: выдача денег на счет в банке, инкассация банком, выплата зарплаты по платежной ведомости

**Comment by htrofymova** [comment]
готово
