### ISSUE TITLE
[Улучшайзинг] Админка - ID юзера кривое

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1226]
В админке в разделе Просування в таблице регистраций конкретного партнера в колонке ID выводится ненужное шопопало, которое информаци не дает и только сбивает с толку.

Туда хорошо бы номер выводить тенанта.

![image](https://user-images.githubusercontent.com/38098758/69958338-41262b00-150d-11ea-8fcf-fffddcb46527.png)

**Comment by alex-kukhtin** [comment]
Это Id юзера. Добавлю тенант.
