### ISSUE TITLE
[Улучшайзинг] Личный кабинет - при выставлении счета давать выбирать фирму

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1240]
С введением мультифирменности все больше народу просит сделать возможность при выставлении счета выбирать фирму, на имя которой выставляется счет.

Видимо, стоит делать в комплексе с https://github.com/a2develop/bugTracker/issues/1225

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/1151 -- одного поля ягоды?

**Comment by AndriyNesterenya** [comment]
Да. Я этого issue не видел :(
