### ISSUE TITLE
Роли "Менеджер з закупівель" и "Менеджер з продажу" 

### ISSUE THREAD

**Issue by htrofymova** [a2develop/bugTracker#1245]
Меню ПРИДБАННЯ.
При попытке создать (открыть) оплату по банку (кассе). 

![image](https://user-images.githubusercontent.com/43743331/70654580-4a2aa100-1c5f-11ea-905e-664f4cba560b.png)

Меню ЗАПАСИ.
Кнопка [Нова операція] как бы запрещена:
![image](https://user-images.githubusercontent.com/43743331/70655220-89a5bd00-1c60-11ea-9126-534a68f56ee9.png)
 НО! при аккуратном нажатии на стрелочку - работает. При попытке создать операции из раздела Продажи или связанные с необоротными активами и комиссионной торговлей - аналогичная ошибка (см. 1-ю картинку).

Для роли "Менеджер з продажу" - аналогично, только в меню ЗАПАСИ ошибка вьіпадает на раздел Придбання.

**Comment by AlexeyTishkin** [comment]
Исправил.
