### ISSUE TITLE
Бухгалтерия | Платежи | Экспорт в Excel

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1246]
Если платежей много, то повторяется шапка.
Надо в стимулсофте режим поставить "все на одной странице" 

Возможно надо формат передать в параметры. Для ворда разбивать, а для экселя - нет.

**Comment by alex-kukhtin** [comment]
![image](https://user-images.githubusercontent.com/26379138/70785880-0be2ce00-1d94-11ea-88a8-3a62d9a725a3.png)

**Comment by AlexeyTishkin** [comment]
Это управляется параметрами экспорта. В команде экспорта нужен доступ к этим параметрам.
![image](https://user-images.githubusercontent.com/35917940/72062722-07e99380-32e1-11ea-922e-6124f5f7486c.png)

**Comment by alex-kukhtin** [comment]
Сделал в 7610.
Сделал "по умолчанию". Выключать не понадобиться, как по мне.
После релиза проверишь и закроешь issue.
