### ISSUE TITLE
[Docs] Дописать в инструкцию по импорту замечание об откусывании Excel нулей слева 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1248]
Написать в инструкции по импорту, что Эксель может откусывать незначащие в числовом смысле нули слева у кодов типа ЕДРПОУ и прочих артикулов, что ведет к проблемам.

Порекомендовать делать соотв. поля текстовыми или ставить слева кавычку, а-ля '00001234

**Comment by kattrina-brekhova** [comment]
в хэлпе нет смысла это писать, потому что нет прямой ссылки на соответствую страницу в хэлпе (и нет самой страницы)
может есть смысл 1-2 предложениями это здесь написать?
![image](https://user-images.githubusercontent.com/38099938/72715263-d42c2a80-3b78-11ea-9f16-fcfeb4d53187.png)

**Comment by kattrina-brekhova** [comment]
вот в этой инструкции пунктом 4 дополнить:
Excel не відображає «0», з яких можуть початися ЄДРПОУ (ІПН). Ці коди в таблиці Excel доповніть цифрами «0» зліва так, щоб числове значення ЄДРПОУ містило 8 знаків. Наприклад, «00415487».
![image](https://user-images.githubusercontent.com/38099938/74974019-2b017a00-542d-11ea-94d2-90d86e468052.png)

**Comment by kattrina-brekhova** [comment]
по объектам учета тоже может быть такая проблема?

**Comment by kattrina-brekhova** [comment]
в хэлпе по контрагентам описала этот момент
