### ISSUE TITLE
[Улучшайзинг] - в личном кабинете - Стан рахунку в выставлении счета сделать селектор фирм из тенанта

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1253]
Хочу в Личном кабинете в разделе Стан рахунку сделать селектор с выбором любой фирмы из текущего тенанта.

Цель - дать возможность хозяину тенанта выставить счет на любую фирму из тенанта на произвольную сумму.

**Comment by alex-kukhtin** [comment]
Done (02.01.20)
