### ISSUE TITLE
[Bug] Тенанти - Тенанти не работает поиск по ОСНОВНОМУ ЕДРПОУ

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1255]
[Bug] Тенанти - Тенанти не работает поиск по ОСНОВНОМУ ЕДРПОУ

**Comment by alex-kukhtin** [comment]
done

**Comment by AndriyNesterenya** [comment]
Поиск отрабатывает четко.
Поломалось отображение фирм (предположительно на 2м сегменте).
![image](https://user-images.githubusercontent.com/38098758/71682501-95385f80-2d98-11ea-9081-730a48bf3bf9.png)
в старом тестовом тенанте с моими ЕДРПОУ фирмы во всплывалке показываются,
в свежесозданном аккаунте - нет

**Comment by alex-kukhtin** [comment]
Проверь, плиз.
Вроде сделал все, что сязано с сегментами.
