### ISSUE TITLE
[BUG] В выписке Укрсиба вместо даты операции подтягивается дата документа

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1258]
Клиенты жалуются, что выписке Укрсиба вместо даты операции подтягивается дата документа.
А документ может быть создан черт знает когда заранее.
Во вложении - ZIP-архив с примером выписки.
В строке 28 операция прошла 20го, а документ датирован 16м числом.

[УкрсибВыписка_строка 28.zip](https://github.com/a2develop/bugTracker/files/3996255/_.28.zip)

**Comment by AlexeyTishkin** [comment]
Колонка "Дата операцiї" с временем. При импорте ошибка: Invalid external date 20.12.2019 10:40

**Comment by alex-kukhtin** [comment]
Done (02.01.20)
