### ISSUE TITLE
Нет документа по зарплате: Відомість на виплату грошей ??

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#126]
Не нашла ни в одном разделе сервиса Ведомость на выплату зарплаты (из кассы). ??
Выдача зарплаты расходными кассовыми ордерами не может заменить полноценную ведомость. Если на предприятии работает больше 10 человек - заводить на каждого из них отдельный ордер не вариант...
При этом, Ведомость может не формировать проводки (мы заранее не знаем, сколько сотрудников получит зп, а какая часть будет депонирована
Было бы хорошо, если к РКО можно было бы подтягивать документ основание - Ведомость на выплату зп. А в самом РКО уже прописывать сумму такой выдачи, ссылаясь на эту Ведомость

**Comment by Illya-Lykhachov** [comment]
В работе https://app.zenhub.com/workspace/o/a2develop/app/issues/581
