### ISSUE TITLE
[BUG] Мультифирменность - подхватывает API Привата из основной фирмы при создании новой со счетом в Привате

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1260]
Поймал косячок с мультифирменностью.
Суть проблемы:
Имеется основная фирма аккаунта со счетом в Приватбанке + с настроенным API в выписке.
Создается дополнительная фирма а этом же аккаунте.
Создается новый юзер, имеющий полные права на доп. фирму и запрет доступа к основной фирме (вариант для буха-аутсорсера или мини-холдинга).
Заводится счет доп. фирмы в том же Привате.
Логинимся под новым юзером, идем в выписку по приватовскому счету - видим настройки API основной фирмы.

**Comment by AndriyNesterenya** [comment]
При этом тест настроек API проходит, но кнопка Импортировать неактивна.
Изменение настроек API у доп фирмы меняет настройку API основной фирмы.

**Comment by alex-kukhtin** [comment]
Done (02.01.20).
Проверяйте ВНИМАТЕЛЬНО!
