### ISSUE TITLE
Новая форма платежки и т.п. с 13.01.2020

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1262]
Нужна новая форма платежек и чеков до 13.01.2020 - пора убрать МФО
Подробности:
https://news.dtkt.ua/state/cash-handling/58929
https://bank.gov.ua/legislation/Resolution_06112019_127

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/71661408-c001c400-2d56-11ea-97a0-fdf29a706499.png)

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/71661485-f8090700-2d56-11ea-8337-1701186f32c9.png)

**Comment by AndriyNesterenya** [comment]
Зацепить должно формы:

- платіжного доручення;
- платіжної вимоги-доручення;
- платіжної вимоги;
- розрахункового чека;
- інкасового доручення.

**Comment by AlexeyTishkin** [comment]
> Зацепить должно формы:

У только "Платежное поручение".

**Comment by AlexeyTishkin** [comment]
Сделал.
