### ISSUE TITLE
Новая форма декларации на прибыль - уже за 1 квартал 2020

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1264]
https://news.dtkt.ua/accounting/reposts/59657

**Comment by kattrina-brekhova** [comment]
по этому отчету измененения подготовлю позже

**Comment by kattrina-brekhova** [comment]
ЗМІНИ В ДЕКЛАРАЦІЇ:

1. Декларацію з ПНП доповнено новим блоком «Податкові зобов’язання, інші штрафні санкції та пені, визначені відповідно до Податкового кодексу України, не пов’язані з виправленням помилок» з рядками 35–37:

рядок 35 — суми збільшення податкового зобов’язання за порушення вимог цільового використання вивільнених від оподаткування коштів;
рядок 36 — штрафні санкції за порушення положень п. 41 підрозд. 4 розд. ХХ ПКУ;
рядок 37 — пеня, нарахована на виконання вимог ст. 1231, пп. 142.1–142.3, п. 41 підрозд. 4 розд. ХХ ПКУ.

було
![image](https://user-images.githubusercontent.com/38099938/75256308-efc7c800-57eb-11ea-9c1c-f09c05e5f31d.png)

буде
![image](https://user-images.githubusercontent.com/38099938/75256463-2998ce80-57ec-11ea-90a8-dd0f2e7e1079.png)

2. Уточнено редакцію рядка 26 декларації з ПНП щодо відображення сум збільшення (зменшення) податкового зобов’язання звітного (податкового) періоду, що уточнюється (див. таблицю).

було:
![image](https://user-images.githubusercontent.com/38099938/75256731-93b17380-57ec-11ea-880e-5b4779bd8091.png)
«Збільшення (зменшення) податкового зобов’язання звітного (податкового) періоду, що уточнюється (позитивне (від’ємне) значення (рядок 19 — рядок 19 Податкової декларації з податку на прибуток підприємств, яка уточнюється)) або рядок 26 таблиці 2 додатка ВП до рядків 26–29, 31–33 Податкової декларації з податку на прибуток підприємств (+, –)»

буде:
![image](https://user-images.githubusercontent.com/38099938/75256771-a9269d80-57ec-11ea-902f-4efed301c68e.png)
«Збільшення (зменшення) податкового зобов’язання звітного (податкового) періоду, що уточнюється (позитивне (від’ємне) значення (рядок 19 — рядок 19 Податкової декларації з податку на прибуток підприємств, яка уточнюється, або рядок 35 — рядок 35 Податкової декларації з податку на прибуток підприємств, яка уточнюється)), або рядок 26 таблиці 2 додатка ВП до рядків 26–29, 31–33, 35 Податкової декларації з податку на прибуток підприємств (+, –)»

3. Блок «Наявність додатків10» доповнено новою графою для відмітки про наявність додатку ПП «Інформація про суми податкових пільг» та графу «ФЗ» розділено на графи: «П(С)БО» та «МСФЗ».

було
![image](https://user-images.githubusercontent.com/38099938/75256925-e428d100-57ec-11ea-8728-57aee451a4e0.png)

стало
![image](https://user-images.githubusercontent.com/38099938/75256951-eee36600-57ec-11ea-8c97-ace8500ca7d4.png)

новая форма:
https://drive.google.com/file/d/1QWh9iwmOQrbZIPKBFctjaiIRpHnGyCA3/view?usp=sharing

**Comment by kattrina-brekhova** [comment]
ЗМІНИ В ДОДАТКАХ:

новий додаток ПП
https://drive.google.com/file/d/18g1mWr3gJzCUUTDRo_c0hC2KehcrYB6g/view?usp=sharing

**Comment by kattrina-brekhova** [comment]
ЗМІНИ В ДОДАТКАХ яких в нас не має — нові бланки:

ВП
https://drive.google.com/file/d/1MWq05BuWKz7xNygJeS56KRkSIp3Gw5pJ/view?usp=sharing

ПН
https://drive.google.com/file/d/1VJtEFnf-gLp0jyZ0UVl7uLcYVKOuXzWz/view?usp=sharing

**Comment by kattrina-brekhova** [comment]
ЗМІНИ В ДОДАТКУ РІ:

1. Додаток РІ доповнено новим рядком 4.1.4.1 «позитивна різниця між сумою будь-яких виплат (винагород) страховим посередникам та іншим особам за надані послуги щодо укладання (пролонгації) договорів страхування та сумою нормативу витрат на виплати страховим посередникам, що розраховані за методикою, визначеною уповноваженим органом, що здійснює державне регулювання у сфері ринків фінансових послуг, за погодженням з центральним органом виконавчої влади, що забезпечує формування та реалізує державну фінансову політику (підпункт 141.1.3 пункту 141.1 статті 141 розділу ІІІ Кодексу)» розділу 4 «Інші різниці».

було:
![image](https://user-images.githubusercontent.com/38099938/75258579-5a2e3780-57ef-11ea-9ad2-473d1f23cbd7.png)

стало:
![image](https://user-images.githubusercontent.com/38099938/75258682-8944a900-57ef-11ea-9cf1-e0c365a18e1e.png)

2. у рядках 3.1.6, 3.1.6.1, 3.1.6.2, 3.1.7 розділу 3 «Різниці, які виникають при здійсненні фінансових операцій» назву різниць узгоджено з положеннями п.п. 140.5.4 ПКУ в частині непоширення цього підпункту на активи з права користування за договорами оренди.

рядок 3.1.6 БУЛО: 
![image](https://user-images.githubusercontent.com/38099938/75259128-328b9f00-57f0-11ea-8073-6c0340ec301e.png)

СТАЛО
Сума 30 відсотків вартості товарів, у тому числі необоротних активів (крім активів з права користування за договорами оренди), робіт та послуг, придбаних у неприбуткових організацій, внесених до Реєстру неприбуткових установ та організацій на дату такого придбання, крім випадків, коли сума вартості товарів, у тому числі необоротних активів (крім активів з права користування за договорами оренди), робіт та послуг, придбаних у таких організацій, сукупно протягом звітного (податкового) року не перевищує 25 розмірів мінімальної заробітної плати, встановленої законом на 01 січня звітного (податкового) року, та крім бюджетних установ Накопичувального фонду, недержавних пенсійних фондів і неприбуткової організації, яка є об'єднанням страховиків, якщо участь страховика у такому об'єднанні є умовою проведення діяльності такого страховика відповідно до закону (підпункт 140.5.4 пункту 140.5 статті 140 розділу ІІІ Податкового кодексу України)

РЯДОК 3.1.6.1 ТА 3.6.2 БУЛО:
![image](https://user-images.githubusercontent.com/38099938/75259259-6797f180-57f0-11ea-93d2-68418eec27d3.png)

СТАЛО:
3.1.6.1
Сума 30 відсотків вартості товарів, у тому числі необоротних активів (крім активів з права користування за договорами оренди), робіт та послуг, придбаних у нерезидентів (у тому числі пов'язаних осіб – нерезидентів), зареєстрованих у державах (на територіях), включених до переліку держав (територій), затвердженого Кабінетом Міністрів України відповідно до підпункту 39.2.1.2 підпункту 39.2.1 пункту 39.2 статті 39 розділу І Податкового кодексу України (підпункт 140.5.4 пункту 140.5 статті 140 розділу ІІІ Податкового кодексу України)
3.6.2
Сума 30 відсотків вартості товарів, у тому числі необоротних активів (крім активів з права користування за договорами оренди), робіт та послуг, придбаних у нерезидентів, організаційно-правова форма яких включена до переліку, затвердженого Кабінетом Міністрів України відповідно до підпункту «г» підпункту 39.2.1.1 підпункту 39.2.1 пункту 39.2 статті 39 розділу І Податкового кодексу України, які не сплачують податок на прибуток (корпоративний податок), у тому числі податок з доходів, отриманих за межами держави реєстрації таких нерезидентів, та/або не є податковими резидентами держави, в якій вони зареєстровані як юридичні особи (підпункт 140.5.4 пункту 140.5 статті 140 розділу ІІІ Податкового кодексу України)

РЯДОК 3.1.7
БУЛО 
![image](https://user-images.githubusercontent.com/38099938/75259341-88f8dd80-57f0-11ea-85fa-3b43e54c4168.png)

СТАЛО
 Розмір різниці між вартістю придбання товарів, у тому числі необоротних активів (крім активів з права користування за договорами оренди), робіт, послуг та вартістю, визначеною виходячи з рівня ціни, визначеної за принципом «витягнутої руки» (підпункт 140.5.4 пункту 140.5 статті 140 розділу ІІІ Податкового кодексу України)

ДОДАТОК
https://drive.google.com/file/d/158xxRzKFupFEG3TtgToKPDaRKi849QGE/view?usp=sharing

**Comment by AlexeyTishkin** [comment]
Новые формы налоговой отчетности: Податкова декларація з податку на прибуток підприємств (J0100118, F0100703), Додаток РІ - Різниці (J0111818, F0171803), Додаток АМ - Інформація щодо нарахованої амортизації (J0110618, F0170603).
