### ISSUE TITLE
Новая форма декларации по НДС - за январь 2020

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1265]
https://news.dtkt.ua/accounting/reposts/59899

https://news.dtkt.ua/accounting/reposts/59813

**Comment by AlexeyTishkin** [comment]
Есть описание изменений (что добавили/изменили/убрали) ?

**Comment by kattrina-brekhova** [comment]
пока нахожу крохи. на следующей неделе изучу еще источники, повыбираю

**Comment by kattrina-brekhova** [comment]
собираю с миру по нитке
это еще осенняя информация, когда был проект приказа

внесення змін до форми податкової декларації з ПДВ, зокрема:

додатка 6, доповнивши його відповідними реквізитами (код пільги, сума пільги тощо);
додатка 4, виключивши дві графи „МФО” та їх цифрові поля.
Крім того, проєктом наказу передбачено внесення змін до Розрахунку податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України. А саме, пропонується доповнити такий розрахунок відповідними реквізитами („Звітний новий”, „Уточнюючий” тощо)

**Comment by kattrina-brekhova** [comment]
вот приказ, которым вносятся изменения в отчетность НДС
https://tax.gov.ua/zakonodavstvo/podatkove-zakonodavstvo/nakazi/74175.html

вносять зміни до:

форми податкової декларації з ПДВ;
уточнюючого розрахунку податкових зобов’язань із ПДВ у зв’язку з виправленням самостійно виявлених помилок;
Розрахунку податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник податку на додану вартість, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України;
Порядку № 21.

**Comment by kattrina-brekhova** [comment]
собранные изменения в декларации ндс + додатки + уточненке

https://drive.google.com/file/d/12Jd1zSiA_z-MeI7OqHZlv4xZ7QfB6UNx/view?usp=sharing

форму расчета ндс обязательств неплательщика ндс по операциям приобретения у нерезидентов  скачивайте отсюда в экселе https://tax.gov.ua/zakonodavstvo/podatkove-zakonodavstvo/nakazi/74175.html

у меня при выгрузке и загрузке на гугл док меняется размер ячеек и некорректно отражает информацию экселевского файла

**Comment by AlexeyTishkin** [comment]
Сделал: Податкова декларація з податку на додану вартість (J0200121, F0200121), Приложение 1 - Розрахунок коригування сум податку на додану вартість (J0200521, F0200421), Приложение 5 - Розшифровки податкових зобов'язань та податкового кредиту в розрізі контрагентів (J0215121, F0215121).

**Comment by AlexeyTishkin** [comment]
Сделал: Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок (J0217021, F0217021).

**Comment by AlexeyTishkin** [comment]
Сделал: Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України (J0215521, F0215521).
