### ISSUE TITLE
Исчезла возможность поменять Основной счет 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1266]
После убирания счетов из реквизитов фирмы нельзя переставить галку "Основной" с первого созданного счета на любой другой, созданный позже.

У первого созданного счета есть чекбокс "Основний"
![image](https://user-images.githubusercontent.com/38098758/71771246-bcca2c00-2f40-11ea-9ad7-ebb59b4dc19b.png)

у всех последующих - нет
![image](https://user-images.githubusercontent.com/38098758/71771248-c5226700-2f40-11ea-9357-ef46fe3508aa.png)

**Comment by alex-kukhtin** [comment]
Леша. Все последующие - сделаны клиент-банком.
И они ВАЛЮТНЫЕ (но в гривне!)

**Comment by AlexeyTishkin** [comment]
Исправил.
