### ISSUE TITLE
Косяки при печати незаполненного счета или инвойса.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1268]
Мелкий не особо важный косяк:
Если в незаполненном исходящем счете (не выбран плательщик и номенклатура одновременно и не добавлено строк) нажать на "Надрукувати" - получается вот такая некрасивость:
![image](https://user-images.githubusercontent.com/38098758/71834858-e0b07d80-30b8-11ea-971c-1bd346ac88ca.png)

Если хоть что-то выбрать или добавить строк - печатается нормальная форма с таблицей.
Та же хрень во входящем счете.
Во входящем инвойсе вообще выдает ошибку "Property 'TDocument.Rows'. Object TDocument (Id=0) not found"
Исходяший инвойс вообще на нынешний диалог не переделали - остался старый вариант, зато все печатается.

В трезвом уме никто такого делать не будет, но если захотят таким способом напечатать пустой бланк счета - будет обидно :)
Предлагаю делать кнопку печати неактивной, пока руками не будет введено хоть что-то.

**Comment by AlexeyTishkin** [comment]
Кнопки "Надрукувати", "Експортувати" отображаются только после ввода пользователем каких-то данных.
