### ISSUE TITLE
При нажатии на цифру (синюю) оборотов в ОСВ в Мозиле открывается меню перехода в другие отчеты, но курсор проходит насквозь.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1269]

**Comment by alex-kukhtin** [comment]
Исправил. Будет в следующем билде (7610).
После релиза, когда обновится билд, надо будет проверить и закрыть этот issue.

**Comment by Anestezia** [comment]
сейчас проверила. На деве работает в мозиле
