### ISSUE TITLE
Счет исходящий. Добавить селектор расчетного счета.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#127]
Вообще говоря, у фирмы может быть несколько активных расчетных счетов.

**Comment by AlexeyTishkin** [comment]
Сделал выбор счета.

**Comment by AlexeyTishkin** [comment]
Что решаем по поводу отображения нескольких счетов ?

**Comment by nik-man** [comment]
Насчет нескольких расчетных счетов не знаю,
а этот ишью можно закрывать. ))
