### ISSUE TITLE
Перезагружать страницу при первичном вводе реквизитов Моей фирмы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1271]
Уже несколько обращений с проблемами было из-за того, что при заполнении реквизитов базовой "моей фирмы" с приветственного окна после регистрации главное окно не перегружается, в селекторе выбора фирм остается Моя фирма, народ тупит и начинает новые создавать.

Оч. хочется после сохранения данных в мастере Моей фирмы перегружать главное окно, как мы это делаем при создании дополнительных фирм

**Comment by alex-kukhtin** [comment]
Done (7619)
