### ISSUE TITLE
Подсказка по Свифт коду не видна, появляется скрол.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1272]
![image](https://user-images.githubusercontent.com/42540074/72084054-7d6a5980-330b-11ea-8025-992955b9db45.png)

**Comment by Anestezia** [comment]
Также нет валидатора при введении Свифт-кода на отечественный банк. Можно вводить любой формат.

**Comment by AlexeyTishkin** [comment]
Отображение сообщения исправил.

**Comment by AlexeyTishkin** [comment]
> Также нет валидатора при введении Свифт-кода на отечественный банк.

Повторить не смог. Подробней.
