### ISSUE TITLE
Добавить название компании на печатные отчеты

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1273]
У нас сейчас на печатных кроме собственно данных печатается 1) название самого отчета/ведомости +2) период
Типа
"Загальна оборотно-сальдова відомість
Період: 09.01.2020"

С введением мультифирменности ИМХО нужно выводимть еще и название фирмы, иначе будут путаться.

**Comment by alex-kukhtin** [comment]
А теперь, пожалуйста, список отчетов в студию.
Поскольку искать будет напряжно.

**Comment by AndriyNesterenya** [comment]
По большому счету ВСЕ наши отчеты (которые Звіти в левом меню каждого раздела) инфы о фирме не содержат.
ИМХО достаточно в верхней строке каждого отчета выводить имя текущей фирмы + ЕДРПОУ.
Если хочешь - слеплю полный перечень.

**Comment by AndriyNesterenya** [comment]
ЗЫ Оборотна відомість по складу,  которая присутствует в списке Звітів в разделах Купівля-Продаж-Запаси (http://dev.a2start.com/reports/entities/warehouseturnoversheetentity/) это один отчет с разными параметрами или три разных отчета?

**Comment by alex-kukhtin** [comment]
Если урл один - то один отчет. Если разные - то разные.

**Comment by alex-kukhtin** [comment]
> По большому счету ВСЕ наши отчеты (которые Звіти в левом меню каждого раздела) инфы о фирме не содержат.
> ИМХО достаточно в верхней строке каждого отчета выводить имя текущей фирмы + ЕДРПОУ.
> Если хочешь - слеплю полный перечень.

Мне надо, чтобы кто-то (например ты :-) составил себе полный список отчетов и заставил/проконтролировал, чтобы это было добавлено везде.
Иначе будет как всегда.

**Comment by AndriyNesterenya** [comment]
- [x] Відомість за розрахунками з покупцями/постачальниками (Купівля-Продаж)
http://dev.a2start.com/reports/agents/turnoversheetagent631/

- [x] Відомість за розрахунками з покупцями/постачальниками в валюті (Купівля-Продаж)
http://dev.a2start.com/reports/agents/turnoversheetagent632/

- [x] Відомість за розрахунками з іншими дебіторами  (Купівля)
http://dev.a2start.com/reports/agents/turnoversheetagent377/

- [x] Оборотна відомість по складу (Купівля-Продаж-Запаси)
http://dev.a2start.com/reports/entities/warehouseturnoversheetentity/

- [x] Прайс-лист
http://dev.a2start.com/reports/entities/pricelist/

- [x] Оборотна відомість по складу
http://dev.a2start.com/reports/entities/warehouseturnoversheetentity/

- [x] Валовий прибуток
http://dev.a2start.com/reports/entities/grossprofit/

- [x] Оборотність запасів
http://dev.a2start.com/reports/entities/inventoryturnover/

- [ ] Відомість за необоротними активами
http://dev.a2start.com/fixassets/reports/materialreport/

- [ ] Відомість по групах необоротних активів
http://dev.a2start.com/fixassets/reports/statementgroup/

- [ ] Інвентарна картка обліку основних засобів
http://dev.a2start.com/fixassets/reports/inventorycard/
Тут еще мелкая лажа с датой
![image](https://user-images.githubusercontent.com/38098758/72243828-8ef67e80-35f5-11ea-903f-2f0e0d321b7d.png)

- [x] Загальна оборотно-сальдова відомість
http://dev.a2start.com/reports/accounts/turnover/

- [ ] Оборотно-сальдова відомість по касі
http://dev.a2start.com/reports/cash/turnover/

- [x] Оборотно-сальдова відомість по рахунках в банках
http://dev.a2start.com/reports/bank_accounts/turnoversheetbankaccount/

- [x] Оборотно-сальдова відомість по рахунках в банках в валюті
http://dev.a2start.com/reports/bank_accounts/turnoversheetbankaccountcurrency/

- [x] Відомість за розрахунками з іншими кредиторами
http://dev.a2start.com/reports/agents/turnoversheetagent685/

- [ ] Cписок прийнятих
http://dev.a2start.com/reports/hr/hiredlist/

- [ ] Cписок співробітників
http://dev.a2start.com/reports/hr/employeelist/

- [ ] Середньооблікова кількість працівників
http://dev.a2start.com/reports/hr/employeesaveragenumber/

- [ ] Розрахунково-платіжна відомість
http://dev.a2start.com/reports/hr/payrollturnover/

- [ ] Розрахункові листи
http://dev.a2start.com/reports/hr/payrollslips/

- [x] Схеми рахунків
http://dev.a2start.com/reports/account/scheme/0?AccCode=661

- [x] Реєстр документів 
http://dev.a2start.com/reports/account/registerofdocuments/0?AccCode=661

- [x] Реєстр проводок
http://dev.a2start.com/reports/account/registeroftransactions/0?AccCode=661

**Comment by Anestezia** [comment]
Предлагаю также внизу подписантов добавить. Может пригодиться.

**Comment by Illya-Lykhachov** [comment]
В Розрахункові листи название и подпись не нужны. Этот отчёт печатается и нарезается на куски. Каждому сотруднику по куску

**Comment by htrofymova** [comment]
В Инвентрной карте необоротных активов - это не лажа. Инвентарная карта строится не за период , а на конец выбранного периода, потому так и написано в заголовке.

**Comment by alex-kukhtin** [comment]
> В Инвентрной карте необоротных активов - это не лажа. Инвентарная карта строится не за период , а на конец выбранного периода, потому так и написано в заголовке.

Значит надо убрать возможность выбора "За все время" и написать более понятно метку.

**Comment by htrofymova** [comment]
Почему убрать? Это нормальный выбор для этого отчета. И почему не  понятно написано?

**Comment by Illya-Lykhachov** [comment]
![image](https://user-images.githubusercontent.com/35328100/72407930-d867da80-3769-11ea-9f7d-d3b1d3166636.png)

Для этого отчёта нелогичен именно период. Ведь нужна только **одна** дата. Стоит заменить контрол в фильтре на DateTimePicker

**Comment by htrofymova** [comment]
> ![image](https://user-images.githubusercontent.com/35328100/72407930-d867da80-3769-11ea-9f7d-d3b1d3166636.png)
> 
> Для этого отчёта нелогичен именно период. Ведь нужна только **одна** дата. Стоит заменить контрол в фильтре на DateTimePicker

готово

**Comment by AndriyNesterenya** [comment]
Уберите Done
Названий на документах не видно пока

**Comment by AlexeyTishkin** [comment]
Сделано.
