### ISSUE TITLE
В расчет при увольнении добавить Ведомость на выплату

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1275]

**Comment by Anestezia** [comment]
1. В этот документ "Розрахунок зарплати при звільненні" добавить 
еще один раздел  - "Розрахунки" В нем показать развернутую сумму по 661 счету на дату и соответственно "К выплате"
2. Сделать нормальную печатную форму с разделом "Стан розрахунків на дату".

**Comment by Illya-Lykhachov** [comment]
Сделал специальную печатную форму для увольнения.

**Comment by Anestezia** [comment]
У них такой кейс, что 26.12 они человека уволили, а 27.12 приняли по новому проекту под новое финансирование. А в расчет при увольнении во вторую таблицу попадают данные не на дату увольнения как последний день, а за весь Грудень. Они возмущаются, что так быть не должно. 

Вот их формы, которые они себе делают
![image](https://user-images.githubusercontent.com/42540074/73435267-fbd97a80-4350-11ea-8e63-fb703224bac9.png)
[Розрахунок компенсаціі відпускних(Ілляшенко).zip](https://github.com/a2develop/bugTracker/files/4133109/default.zip)
Также просят, чтоб расчет отпускных был расписан, а то возникают споры по сумме.Откуда такую именно сумму получили.

**Comment by Illya-Lykhachov** [comment]
Это не будет работать в простой зарплате. Там нет понятия сотрудник (нет приёма и увольнения), а есть только физик.

**Comment by Anestezia** [comment]
Пусть хоть в Персонале работает. В просто ЗП итак нет кадров.

**Comment by Illya-Lykhachov** [comment]
> У них такой кейс, что 26.12 они человека уволили, а 27.12 приняли по новому проекту под новое финансирование. А в расчет при увольнении во вторую таблицу попадают данные не на дату увольнения как последний день, а за весь Грудень. Они возмущаются, что так быть не должно.

Проверил. Неправда ваша. В Розрахункова відомість при звільненні попадают обороты и сальдо только на дату увольнения включительно

**Comment by Illya-Lykhachov** [comment]
Переделал печатную форму расчётной ведомости при увольнении
