### ISSUE TITLE
Начисление налогов для ФОП - Неправильный подсчет, если в периоде были изменения ставки и т.д.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1277]
1. Кейс: ФОП зарегился с начала мая, первый месяц, согласно законодательства, работает на Общей системе. По факту доходов не получал — ждал, когда перейдет на ЕП, так как нужно РРО ставить. 
Насчитываем налоги: Берем сразу 2 квартал 2019 года. Нажимаем в документе Бух.справка - Начисление налогов Розрахувати. 
Соответственно, за 4 месяц удаляем налоги, так как вообще не были зарегены, за 5 месяц оставляем только ЕСВ, ЕП удаляем, Остается вот что: А сумма внизу  НЕ МЕНЯЕТСЯ!!!
![image](https://user-images.githubusercontent.com/42540074/72264050-b6177500-3622-11ea-9553-e11157e73ee7.png)
Когда-то про такие вещи говорили, что нужна в настройках фирмы Точная дата начала работы, и, возможно, как-то предусмотреть переход на разные системы налогообложения в отчетном периоде. (Одна моя подруга 3 раза переходила за год)

2. Расширяем кейс туда же. Есть потребность также удалить строку с начислением ЕП за 1 месяц, так как ушли на Налоговые каникулы — все законно, ЕП не платили.
![image](https://user-images.githubusercontent.com/42540074/72264132-d6473400-3622-11ea-9182-3da36037d459.png)
Вот результат:
![image](https://user-images.githubusercontent.com/42540074/72264149-de06d880-3622-11ea-834d-dee6ee44317e.png)
В отчет суммы попадают правильно, сбоку документы-основания все с теми же неправильными цифрами
![image](https://user-images.githubusercontent.com/42540074/72264384-55d50300-3623-11ea-98b7-534939fa33ee.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Считает правильно, но даже после обновления страницы в списке отображается полная сумма
![image](https://user-images.githubusercontent.com/42540074/72977811-ee1a7700-3ddd-11ea-8183-f0a5fe141de0.png)
![image](https://user-images.githubusercontent.com/42540074/72977863-04c0ce00-3dde-11ea-924a-86d8567d888d.png)
как минимум, одна сумма такая должна быть.
В отчете также показывается полная возможная сумма, а не фактическая
![image](https://user-images.githubusercontent.com/42540074/72978011-4ea9b400-3dde-11ea-93b7-9cd7cfbbfe88.png)

**Comment by htrofymova** [comment]
не могу повторить
