### ISSUE TITLE
Отчет ФОП по Единому пенсионному взносу (за себя) - Срочная доработка

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1278]
1. Автоматом подставляется база начисления за 2018 год вместо сумм за 2019.
![image](https://user-images.githubusercontent.com/42540074/72268762-17dbdd00-362b-11ea-9d5e-84ff48dc3fe5.png)
2. И еще из наблюдений, нет привязки к дате начала деятельности, в том числе, и к той, которая непосредственно указана в основной таблице, и к той, согласно которой создан документ Начисление налогов
![image](https://user-images.githubusercontent.com/42540074/72268829-38a43280-362b-11ea-9b0f-2c0152289cff.png)
3. Здесь в примере от налоговой стоит 0, если кто-то был на общей системе в начале деятельности, а у нас 0 невозможно поставить
![image](https://user-images.githubusercontent.com/42540074/72268892-5d98a580-362b-11ea-9e91-31995cf159d0.png)
![image](https://user-images.githubusercontent.com/42540074/72268915-64bfb380-362b-11ea-80c1-a0667f03d3b2.png)
4. При стирании сумм лишних, сумма внизу автоматом также не пересчитывается

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Все правильно подставляется, внизу подсчет по всем колонкам есть. Тут одна маленькая заковыка: с одной стороны нужны нули при заполнении 3 столбца, когда удалили сумму. Но что делать с нулями за все полугодие? 
![image](https://user-images.githubusercontent.com/42540074/72978455-2e2e2980-3ddf-11ea-8095-8975f3476dce.png)
Предлагаю оставить там редактируемое значение. При удалении пусть будет пусто, как в других колонках. Автозаполнение нулями убрать, но если человек сам ввел 0,00, то пусть это значение текстовое, так сказать, не исчезает.

**Comment by Anestezia** [comment]
В хмл идет без нулей. Это только визуально так. Закрываю.
