### ISSUE TITLE
Счет (входящий и исходящий). Добавить подсказку для неактивной кнопки "Провести".

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#128]
Для пользователя может быть непонятно, почему документ нельзя провести.
Надо бы добавить тултип типа:
"спочатку виправте помилки" или "треба повністю заповнити документ".
Вообще, надо бы добавить во все документы, но хотя бы для счетов.
Счета может выписывать самый необученный оператор.

**Comment by AlexeyTishkin** [comment]
Почему "хотя бы". Должно быть безобразно, но единообразно.

**Comment by nik-man** [comment]
Та вот не знаю как такой ишью создать.
Напишу "во всех документах" -- никто не начнет. ))
А для каждого документа -- будет 20 одинаковых ишью. ))

**Comment by AlexeyTishkin** [comment]
Так и написать "Документы. Кнопка Провести...". Все должно быть одинаковое: тосты, алерты, подсказки.

**Comment by nik-man** [comment]
Кстати, да... все тултипы должны быть с маленькой буквы. Но я даже боюсь поднимать эту тему. )))

**Comment by nik-man** [comment]
Проверил.
