### ISSUE TITLE
Кнопку Экспорт в XML во всех непроведенных регламентированных отчетах не скрывать, а отображать как Disabled

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1282]
Кнопку Экспорт в XML во всех непроведенных регламентированных отчетах не скрывать, а отображать как Disabled

Новые юзера дергаются и нервничают, когда не видят возможности экспортнуть.

**Comment by alex-kukhtin** [comment]
Ну и в лучших (новых) традициях - найти все эти отчеты и написать здесь их список.
Это надо сделать Леше.
Чтобы тестировщик мог проверить.

**Comment by AlexeyTishkin** [comment]
Список основных отчетов:

F0103306 Податкова декларація платника єдиного податку - фізичної особи - підприємця (квартальна)
F0103404 Податкова декларація платника єдиного податку - фізичної особи - підприємця (річна)
F0100702 Податкова декларація з податку на прибуток підприємств
J0100117 Податкова декларація з податку на прибуток підприємств
F0200121 Податкова декларація з податку на додану вартість
J0200121 Податкова декларація з податку на додану вартість
F0217021 Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок
J0217021 Уточнюючий розрахунок податкових зобов'язань з податку на додану вартість у зв'язку з виправленням самостійно виявлених помилок
F0215521 Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України
J0215521 Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ, які постачаються нерезидентами, у тому числі їх постійними представництвами, не зареєстрованими платниками податків, на митній території України
F0500105 Податковий розрахунок сум доходу, нарахованого (сплаченого) на користь платників податку, і сум утриманого з них податку (Форма № 1ДФ)
J0500105 Податковий розрахунок сум доходу, нарахованого (сплаченого) на користь платників податку, і сум утриманого з них податку (Форма № 1ДФ)
F3000412 Звіт про суми нарахованої заробітної плати (доходу, грошового забезпечення, допомоги, надбавки, компенсації) застрахованих осіб та суми нарахованого єдиного внеску на загальнообов’язкове державне соціальне страхування (Форма № Д4)
J3000412 Звіт про суми нарахованої заробітної плати (доходу, грошового забезпечення, допомоги, надбавки, компенсації) застрахованих осіб та суми нарахованого єдиного внеску на загальнообов’язкове державне соціальне страхування (Форма № Д4)
J0101911 Звіт про використання доходів (прибутків) неприбуткової організації
J3001001 Повідомлення про прийняття працівника на роботу
F3001001 Повідомлення про прийняття працівника на роботу
J0103507 Податкова декларація платника єдиного податку третьої групи (юридичні особи)
F0100110 Податкова декларацiя про майновий стан i доходи (для підприємців)
F3000512 Звіт про суми нарахованого доходу застрахованих осіб та суми нарахованого єдиного внеску
J0103803 Податкова декларація платника єдиного податку четвертої групи
J0303308 Розрахунок частки сільськогосподарського товаровиробництва
S0100113 Баланс (Звіт про фінансовий стан)
S0100213 Звіт про фінансові результати (Звіт про сукупний дохід)
S0111003 Спрощений фінансовий звіт суб'єкта малого підприємництва
S0110011 Фінансовий звіт суб'єкта малого підприємництва
S0500909 Звіт про експорт (імпорт) послуг

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by kattrina-brekhova** [comment]
кнопка видна
когда нужно не активна
после проведения работает во всех отчетах
