### ISSUE TITLE
Рабочие графики - 6-дневная неделя

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1283]
Хотелка от клиента:
"в зарплатній відомості за замовчуванням указана 5 дений робочий день. Та у нас 6ти дений робочий день. Нам потрібно щоб було вказано 25 робочих днів, але були незміні 160 годин."

![image](https://user-images.githubusercontent.com/38098758/72678312-52bb9600-3aad-11ea-9829-cb85e25bb396.png)

![image](https://user-images.githubusercontent.com/38098758/72678319-5ea75800-3aad-11ea-9f7b-e82e4e6f231e.png)

В обсуждении прозвучало от Кухтина:
![image](https://user-images.githubusercontent.com/38098758/72678334-826a9e00-3aad-11ea-90f6-3e7b0195a6a9.png)
Я предлагаю очень простое решение, которое не запрещает изменения потом.
1. Добавить в эту таблицу еще один график - "6-ти дневка"
2. В ведомость начисления добавить комбик "График"
3. Профит.

**Comment by Illya-Lykhachov** [comment]
Между 2 и 3 в каталог нормы рабочего времени для 6-ти дневки. Дни и часы берутся из норм, а не из графика :(
Сделаю пока один график на весь документ, иначе для каждой строки придётся в каталог лазить или организовывать кеш

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/149145733-e48e1143-4006-4f3d-a179-146395dec109.png)
Редактируются дни и часы, также при увеличении количества плановых рабочих дней количество часов сохраняется. При проведении остаются изменения.
