### ISSUE TITLE
Приходный кассовый ордер на возврат денег поставщиком: не подтягивает документ-основание - у меня это накладная на возврат

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1286]
вот возвратная накладная
![image](https://user-images.githubusercontent.com/38099938/72726874-2d548800-3b92-11ea-89e2-9b98410d6c88.png)

в приходном кассовом ордере строка "документ-основание" не активны
![image](https://user-images.githubusercontent.com/38099938/72726984-74427d80-3b92-11ea-89d7-d979e851fcf5.png)

**Comment by htrofymova** [comment]
Возникли вопросы: что к чему привязывать, касается также и платежного поручения:
1. Если приходная накладная не оплачена?
2. Если приходная накладная оплачена?
3. Если это услуги и оплачен выставленный счет, акта нет?
4. Если услуги и акт есть?
5. Если услуги и нет ни счета, ни акта, оплатили по договору? 
6. По товару, наверно, тоже могут оплатить аванс без счета по договору.
7. А вот тут вот просят привязывать к счету
https://github.com/a2develop/bugTracker/issues/941
Нужен какой-то глобальный подход.

**Comment by kattrina-brekhova** [comment]
1. здесь движения по банку не будет, только возврат товара
2. вечером вернули стулья, а утром вернули деньги - это редкий зверь, но бывает - здесь расходную накладную. это если работают без счетов
3. основание счет
4. такого не бывает, принятые услуги никто не возвращает
5. здесь основания нет. в платежных документах указывается договор, который указывался в платежке по операции оплата покупателя
6. могут. тогда тоже ничего. договор только
7. тоже верно. забыла о существовании счетов ))

к примеру, вот платежное поручение на оплату поставщику
здесь можно выбрать и счет и акт и накладную
![image](https://user-images.githubusercontent.com/38099938/73347950-2fed6680-4291-11ea-9525-bc151c85f498.png)
я считаю, что есть смысл установить выбор по счету и накладной по возвращенным от покупателя товарам
чтоб не возвращаться больше к этому вопросу, дать возвожность выбора еще и расходной на отгруженный товар покупателю - это если вдруг все-таки вечером стулья, а утром деньги
итого: счет, расходная накладная, накладная на возвращенные товары

**Comment by AlexeyTishkin** [comment]
Я думаю, что возврат денег нужно привязывать к отправке денег. Т.е. операцию "Повернення коштів постачальником" привязывать к операции "Оплата постачальнику". По факту он может вернуть нам только ту сумму, которую мы ему первоначально перечисляли и эта сумма напрямую не связана ни со Счетом, ни с Приходной накладной.

**Comment by AlexeyTishkin** [comment]
В случае привязки денег к деньгам существует только один вариант, без вариаций: Счет, Накладная, без привязки.

**Comment by kattrina-brekhova** [comment]
в общем-то правильно
летом покупала обувь. платила картой. обувь не подошла, на следующий день вернула и мне выдали деньги с кассы
какую здесь привязку?

**Comment by AlexeyTishkin** [comment]
> платила картой. обувь не подошла, на следующий день вернула и мне выдали деньги с кассы

Не совсем тот кейс :) В этом случае покупатель - не персонифицированный, т.е. нет никаках привязок. Кстати, сколько делал такие возвраты - всегда возвращали на карту.

Но если есть желание, то можно расход из кассы привязать к приходу по банку.

**Comment by kattrina-brekhova** [comment]
я тоже первый такой возврат повстречала, и меня заинтересовало как связать такое в учете

**Comment by AlexeyTishkin** [comment]
> я тоже первый такой возврат повстречала, и меня заинтересовало как связать такое в учете

Ну в данном конкретном случае: оплата картой - эквайринг - просто деньги на счет, без указания отправителя, возврат из кассы - служебный вынос - тоже обезличенный. Т.е. нет никаких связей.

**Comment by Anestezia** [comment]
На данный момент строка документ-основание в ордере активна. Подтягивается основание - Ордер на платеж контрагента по счету. Если платилось по счету через банк, а не через кассу, то список основания пуст.  
В цепочке документов отображается этот возврат средств, но статусы не меняются, Оплачено полностью. И в списке операций Бета этого возврата по кассе нет вообще. 
![Screenshot_44](https://user-images.githubusercontent.com/42540074/149156989-330cc2d0-9272-4e15-ae0f-0fa1438ae5fb.png)
![Screenshot_45](https://user-images.githubusercontent.com/42540074/149157143-4a09b4ef-b2f2-4990-8f2d-c8192fca84e7.png)

**Comment by htrofymova** [comment]
Для повернення грошей документом-підставою є тільки переказ грошей. якщо платили через банк, то і повернення через банк (каса так само), така логіка. Відображення в переліку документів  наразі адекватне.

**Comment by Anestezia** [comment]
Для повернення грошей документом-підставою є тільки переказ грошей. якщо платили через банк, то і повернення через банк (каса так само), така логіка. 
Наразі так і працює. Оплату по банку і по касі можна обрати як підставу для повернення.
