### ISSUE TITLE
Прибутковий касовий ордер на отримання цільового фінансування: какая-то лажа со строкой-селлектором "Вид надходжень" в самой форме документа

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1287]
в правой части документа все отлично выбрает
![image](https://user-images.githubusercontent.com/38099938/72733304-42d0ae80-3ba0-11ea-816f-48de6b66a7d9.png)

а в самом документе при входе в селлектор не видно названия рядов для выбора
![image](https://user-images.githubusercontent.com/38099938/72733345-5845d880-3ba0-11ea-87f0-867e638b6220.png)

**Comment by htrofymova** [comment]
не подтверждается

**Comment by kattrina-brekhova** [comment]
прикольно
у меня уже тоже получилось
