### ISSUE TITLE
Клиент-банк загрузка выписки. Сделать кнопку "Очистить"

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1289]
После загрузки файла есть возможность только загрузить выписку.
Если я ошибся, и выбрал не тот файл, то повторить невозможно. Надо закрывать окно и начинать по новой.
Надо сделать кнопку "Очистить", чтобы можно было повторить загрузку файла.

**Comment by AlexeyTishkin** [comment]
Добавил.
