### ISSUE TITLE
Добавить группу объектов в отчеты

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1291]
![image](https://user-images.githubusercontent.com/26379138/72890525-bd253e00-3d1a-11ea-937b-7356047d90df.png)

**Comment by alex-kukhtin** [comment]
И во все отчеты, связанные с объектами учета.

**Comment by alex-kukhtin** [comment]
![image](https://user-images.githubusercontent.com/26379138/72890713-358bff00-3d1b-11ea-8fbb-677baf27935e.png)

Сюда тоже

**Comment by alex-kukhtin** [comment]
Стар, перенеси эту лабуду в Jira и разбей на подзадачи

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by kattrina-brekhova** [comment]
работает, перепроверила
