### ISSUE TITLE
Ведомость амортизации

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1292]
У клиента 3 000 объектов ОС
При заполнении ведомости амортизации БК пишет, что недопустимое кол-во строк
какой там запрет?

**Comment by Illya-Lykhachov** [comment]
пробуйте

**Comment by kattrina-brekhova** [comment]
а как попробовать
у кого из нас сейчас будет больше 3000 ОС
уже после релиза связаться с пользователем?

**Comment by htrofymova** [comment]
я так понимаю, что уже сейчас пользователь может попробовать.

**Comment by kattrina-brekhova** [comment]
где попробовать?
на сервисе?

**Comment by htrofymova** [comment]
да

**Comment by kattrina-brekhova** [comment]
а, уже на сервисе исправлена?
завтра напишу тогда юзеру

**Comment by kattrina-brekhova** [comment]
работает
