### ISSUE TITLE
Оборотка по счету в банке. Расшифровка. Неправильный урл.

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1293]
![image](https://user-images.githubusercontent.com/26379138/72900919-6d9e3c80-3d31-11ea-8aec-3fdab8cdfb8a.png)

**Comment by alex-kukhtin** [comment]
Если нажать оранжевую кнопку - появляется очень странное окно.

**Comment by AlexeyTishkin** [comment]
Исправлено
