### ISSUE TITLE
Внесення майна до статуту - при введении нескольких объектов разных типов все идет на один счет

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1296]
![image](https://user-images.githubusercontent.com/42540074/72988015-2a58d200-3df4-11ea-8b1b-1910fefe9811.png)
все они в этом списке. Авто - ос, идея - немат, дымоход - інші. Проводки другие должны быть:

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
да, ок
