### ISSUE TITLE
Получение дивидендов добавить в операции платежи полученные.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1297]
Одно предприятие может получать дивиденды от другого.

**Comment by AlexeyTishkin** [comment]
Проводки ?

**Comment by Anestezia** [comment]
https://i.factor.ua/ukr/journals/nibu/2017/march/issue-18/article-25628.html

**Comment by htrofymova** [comment]
готово.
Добавлена операция:
одержання дивідендів: дт 311 кт 373.
Так же для бух.справки добалены операции для дивидендов от инвестиций по методу участия в капитале:
нарахування дивідендів (інвестор) : дт 373 кт 141 
дохід від участі в капіталі: дт  141 кт 721
втрати від участі в капіталі: дт 961 кт 141.
Обьічное начисление дивидендов дт 373 кт 731 - можно сделать бухгалтерской стравкой вручную.
