### ISSUE TITLE
Заголовок диалога выбора договора

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/bugTracker#130]
![image](https://user-images.githubusercontent.com/35917940/39670131-a922a52a-5106-11e8-87a9-d9fb4d036e6e.png)

**Comment by AlexeyTishkin** [comment]
А при чем здесь локализация ?

**Comment by nik-man** [comment]
Ну, локализация означает неправильный перевод,
с некоторой натяжкой -- любой неправильный текст. :)
Можно, наверное завести отдельный тег "неверная надпись"
