### ISSUE TITLE
Дополнения 1 и 5 к Уточненке НДС воспринимаются как основные Доп.1,5 в Декларации и не проводятся в одинаковом периоде.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1300]

**Comment by AlexeyTishkin** [comment]
В Приложениях, которые создаются из уточняющего расчета добавлено свойство "Номер нового звітного/уточнюючого документа". При создании равно 1.
Принцип следующий: первое подаваемое приложение имеет тип "Звітний" и номер равный 0 (в этом случае номер указывать не надо и он не отображается). Для каждого последующего приложения этого же типа для данного отчётного периода тип должен быть "Звітний новий" или "Уточнюючий" и значение номера увеличивается на единицу. При создании приложения с типом "Звітний новий" или "Уточнюючий" номер устанавливает в 1, последующая нумерация осуществляется пользователем вручную.

**Comment by AlexeyTishkin** [comment]
Тестируем [здесь](https://github.com/a2develop/testing/issues/467)

**Comment by Anestezia** [comment]
Да, работает.
