### ISSUE TITLE
Банківська виписка - не запрещаются ПДВ/без ПДВ

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#1301]
В проведенной строке выписки не запрещаются радиокнопки "ПДВ/без ПДВ"
![image](https://user-images.githubusercontent.com/26379138/73052271-67bd6e00-3e8d-11ea-83bf-930ffb2db3f8.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
