### ISSUE TITLE
Бухгалтерская справка - формирование уставного фонда: не правильно формирует проводку: Д401-К401

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1302]
в самой бух справке правильно Д46 -К401
![image](https://user-images.githubusercontent.com/38099938/73194552-091a1d80-4135-11ea-8e30-e1f80e117abc.png)

но зайдя в проводки не правильно:
![image](https://user-images.githubusercontent.com/38099938/73194571-12a38580-4135-11ea-93b8-69b6a6ea2650.png)

![image](https://user-images.githubusercontent.com/38099938/73194594-1931fd00-4135-11ea-8278-922ec951e10f.png)

**Comment by htrofymova** [comment]
исправлено
