### ISSUE TITLE
не подается баланс (фин отчет субъекта малого предпринимательства) через сонату и не сохраняем в xml

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1303]
![image](https://user-images.githubusercontent.com/38099938/73194816-70d06880-4135-11ea-9771-02ddfee5740a.png)
![image](https://user-images.githubusercontent.com/38099938/73194842-7b8afd80-4135-11ea-826d-dd7dd0870832.png)

**Comment by kattrina-brekhova** [comment]
упрощенный отчет малого сбъекта малого предпринимательства тоже не подается
и полноценный Баланс не подается

**Comment by AlexeyTishkin** [comment]
Исправлено.
