### ISSUE TITLE
Курсовая разница (доход) -- копейка не идет. Кейс.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1304]
Выписка банка (почистила только персонифицированные данные получателя/плательщика, вот цифры они так дают:
![image (3)](https://user-images.githubusercontent.com/42540074/73436003-60490980-4352-11ea-9927-9e01c49a0f12.png)
не знаю, как считает банк, курсовая разница у них 0,01 в доход, сумма грн.остатка увеличивается, мне нужно исполнить состояние на счете так, как в выписке банка, т.е.  Дт 312  - Кт 714 = 0,01
Я выбираю операцию доход от курсовых разниц, мне надо оно, которое доход, но БК со мной не согласен:
![image (4)](https://user-images.githubusercontent.com/42540074/73436061-78208d80-4352-11ea-9027-cb5d9662a857.png)
Просто бухсправкой я не привяжу 312 к расчетному счету. Если проигнорю 312-й без привязки к р/с, то в дальнейшем, подозреваю, эта копейка все равно вылезут мне боком в пересчетах той же курс.разницы.
П.С.: После исправления  прошлого негаразда с КР  продолжила проведение: расчет КР (все ОК - полечилось), потом продажу валюты. Результат от продажи валюты у меня были убытки (расход), БК нарисовал доход, еще больше увеличивая зависший остаток на 334-м. Но этот счет хоть без привязки к р/с, ручная бухсправка выручила.

**Comment by htrofymova** [comment]
Не понятно, что такое прошлый негараз?
А по картинкам:
У нас считает себестоимость валюты от введенного оф.курса,  
Для расчета надо определиться, что считать фиксированным: официальный курс или себестоимость валюты. Но все равно тот оф. курс, который у них в выписке не получится, если указанную в выписке себестоимость разделить на сумму валюты. 
Делать бух.справку, чтобы они могли подгонять под выписку банка?

**Comment by Anestezia** [comment]
Привет!
Состояние мое истерическое....
Никак невозможно "договориться" с программой в плане курсовых разниц. Вычислила я в чем негаразд. В расчет курсовых разниц заложен принцип  определить разницу между курсом на текущую дату и курсом по фактическим данным на счете, причем этот курс не берется из справочника на предыдущую дату, а вычисляется делением суммы в грн на сумму в валюте. Полученная разница курсов умножается на сумму в валюте, и округляется для отражения в учете до 2-х знаков.
Вот этот метод и дает погрешность. Имею печальку - по результату переоценки сумма в грн получилась на копейку меньше, чем сумма, которая списалась (списали всю сумму в валюте, гривневый эквивалент к списанию рассчитан как сумма валюты умноженная на курс на текущую дату, эта сумма в БК соответствует сумме в  выписке) ... Должно быть на счете абсолютный ноль, а надо мной издевается копейка по кредиту... от которой я не могу избавиться. Бухсправкой не рискую, т.к. там нет возможности указать в качестве аналитики счета 312 конкретный валютный счет. Я уже писала -  подозреваю,  что такая попытка откорректировать состояние счета  мне все равно вылезет боком.
Предлагаю метод расчета, который исключает выше описанную ситуацию.
Сумма  дохода/убытка от переоценки валюты = округлено(сумма остатка в валюте*курс на дату) - сумма остатка в грн
Почему я настаиваю на таком методе - чтоб "было безобразно, но однообразно". И это серьезно, поскольку как раз  однообразность подхода к расчету суммы в грн в разных ситуациях позволит достигнуть одинакового результата.
Надеюсь, понятно изложила... и убедительно...
PS Это я никак декабрь не могу закрыть... Годовой отчет... в эксел переходить?

**Comment by htrofymova** [comment]
исправлено округление. Добавлена возможность ручного ввода себестоимости валюты (для "подгонки" под выписку)
