### ISSUE TITLE
К операциям раздела Бухгалтерия подвязать новые ссылки на хэлп

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1306]
документ со ссылками:
https://drive.google.com/file/d/1WGlCB3F_l4p--LLerc3YsUkfSiykOyRs/view?usp=sharing

**Comment by htrofymova** [comment]
В основном - готово.
Есть пожелание:
для множественных бюджетных и обязательных платежей созданы две операции: 
"Перерахування інших податків" и "Перерахування інших обов'язкових платежів", для которых выбираются конкретные налоги или платежи. Таким образом, ссылки можно привязать только две, а не на каждый налог/платеж отдельно.

**Comment by kattrina-brekhova** [comment]
хорошо
тогда нужно будет внести изменения в структуре хэлпа
создам 2 отдельные страницы по этим налогам, остальные убью
дам знать
