### ISSUE TITLE
Операция Вступительный баланс по зарплате: изменение текста подсказки

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1307]
Залишок у взаєморозрахунках зі співробітником по зарплаті (Кредитовий залишок 661 рахунка). Якщо сальдо 661 за Дебетом, сума вказується зі знаком мінус.

Залишок у взаєморозрахунках зі співробітником по інших виплатах (Кредитовий залишок 663 рахунка). Якщо сальдо 663 за Дебетом, сума вказується зі знаком мінус.

Строка "Початковий баланс. Заробітна плата (661)" = Початковий баланс. Виплачені суми

**Comment by Illya-Lykhachov** [comment]
Сделано.
Заодно убрал возможность создавать старые документы вступительного баланса
