### ISSUE TITLE
Bug-недоделка: Не ставится автоматом галочка роли контрагента для Банка

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#131]
На странице контрагентов при условии установки селектора роли контрагента в "Банки" при создании нового контрагента в свойствах автоматом не устанавливается галочка на роль "Банк".

У покупателей с поставщиками все ОК.

**Comment by AndriyNesterenya** [comment]
Чёто не вижу исправления.

**Comment by AndriyNesterenya** [comment]
Како было - како есть
![image](https://user-images.githubusercontent.com/38098758/39677021-2903fb60-517d-11e8-91bb-2fd92e88fa54.png)

**Comment by nik-man** [comment]
Сейчас работает правильно.
Возможно, настройка на сервере не была обновлена.
Так часто бывает, разработчик исправл баг, выложил на гитхаб,
сообщил об исправлении, а на сервере обновление появляется на след. день.

**Comment by AndriyNesterenya** [comment]
Есть, обновилось.
