### ISSUE TITLE
Таблица 1 Нарахування ЄСВ до звіту F3000512 (форма Д5 річна) для ФОП - не проводится

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1310]
кнопка "провести" не активная
![image](https://user-images.githubusercontent.com/38099938/73751379-abef1f00-4767-11ea-8175-a738e1bb6a19.png)
а сам отчет без проведения этого документа не проводится
![image](https://user-images.githubusercontent.com/38099938/73751412-bc9f9500-4767-11ea-8071-2ec923fe566e.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by htrofymova** [comment]
но, все-таки, лучше заполнять налоговую в свойствах Моей фирмы.

**Comment by kattrina-brekhova** [comment]
орган налоговой ввели
почем-то ошибку такую дает при создании додатка
![image](https://user-images.githubusercontent.com/38099938/73838058-7c015380-481b-11ea-9613-1f25a1d27767.png)

**Comment by htrofymova** [comment]
исправлено
