### ISSUE TITLE
Баланс: дельта округления и строка 1420: сделать служебное сообщение вместо автоматического отнесения разницы

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1312]
использовала эти данные, внесла вступительным балансом
![image](https://user-images.githubusercontent.com/38099938/73761751-efea2000-4777-11ea-808e-1b31e941d449.png)
в балансе отражается разница  в 1420 строке
причем по 152 и 642 счетам в строках остатки не показывает
там большие числа округлений?

![image](https://user-images.githubusercontent.com/38099938/73762982-7eab6c80-4779-11ea-98da-fc606c2c08c7.png)

![image](https://user-images.githubusercontent.com/38099938/73763053-94b92d00-4779-11ea-9be3-af799c760d56.png)

![image](https://user-images.githubusercontent.com/38099938/73763204-c8945280-4779-11ea-98db-380df62b0bab.png)

![image](https://user-images.githubusercontent.com/38099938/73763263-dcd84f80-4779-11ea-9c93-12d862511eb6.png)

![image](https://user-images.githubusercontent.com/38099938/73763322-f1b4e300-4779-11ea-8c95-ce89573d1eee.png)

![image](https://user-images.githubusercontent.com/38099938/73763370-01342c00-477a-11ea-8039-6e31c41b7fd1.png)

**Comment by kattrina-brekhova** [comment]
логин test@3.ua

пароль behappy1204

фирма "чупакабра"

**Comment by AlexeyTishkin** [comment]
> причем по 152 и 642 счетам в строках остатки не показывает
там большие числа округлений?

Округление до целого. В S0110011 округление до 1-го знака.

**Comment by AlexeyTishkin** [comment]
> логин test@3.ua

На будущее - общий тестовый аккаунт: test@a2.net.ua, пароль 123123. Все примеры в нем.

**Comment by AlexeyTishkin** [comment]
Сделал сообщение.

**Comment by kattrina-brekhova** [comment]
работает, спасибо
запомню
