### ISSUE TITLE
Бухгалтерська довідка нарахування податків загальна система оподаткування: заменить проводки + чтоб результат попадал в строку 2300 отчета фин результаты (форма2)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1314]
бух справка, расчет налогов общая система:

Дт 98 Кт 641 - нарахування податку,

Дт 791 Кт 98 - списання витрат з податку нa прибуток на фінансовий результат.

результат должен попасть в строку 2300 отчета о фин результатах

**Comment by kattrina-brekhova** [comment]
нужно проконтролировать, чтоб изменение проводок не поломало автоматическое заполнение баланса и налога на прибыль для общей системы
а также для упрощенцев заполнение отчетов, в которых используются операции расчета налогов

**Comment by kattrina-brekhova** [comment]
для юр лица 3 группа эти проводки тоже должны быть применены

Дт 98 Кт 641 - нарахування податку,

Дт 791 Кт 98 - списання витрат з податку нa прибуток на фінансовий результат.

**Comment by htrofymova** [comment]
Для юр.лиц 3 группа начисляется единый налог.
https://i.factor.ua/journals/nibu/2016/september/issue-71/article-21085.html
публикация за  2016 год, конечно, но все-таки: дт 92 - кт 641

Для юр.лиц общей системы - готово.

**Comment by kattrina-brekhova** [comment]
> Для юр.лиц 3 группа начисляется единый налог.
> https://i.factor.ua/journals/nibu/2016/september/issue-71/article-21085.html
> публикация за 2016 год, конечно, но все-таки: дт 92 - кт 641
> 
не спорю

**Comment by kattrina-brekhova** [comment]
для общей системы отражает в строке 2300 ф2

я смотрю информацию в этой статье, что упрощенцы тоже должны показывать эти суммы в отчете
![image](https://user-images.githubusercontent.com/38099938/73939468-32376c80-48f2-11ea-918a-b9d0493ce632.png)

делаем отдельное ишью, это закрываем?
