### ISSUE TITLE
заполнение строки 1620 баланса - не попадает военный сбор и налоги/платежи по 642 счету

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1318]
![image](https://user-images.githubusercontent.com/38099938/73946955-6b2a0e00-48ff-11ea-87bd-08e8ef8a56e8.png)

**Comment by AlexeyTishkin** [comment]
Проверил - попадает.
Нужен пример на тестовом аккаунте.

**Comment by kattrina-brekhova** [comment]
странно
я у себя вчера не перепроверила
позвоню клиентке попрошу ее данные

**Comment by AlexeyTishkin** [comment]
Там же в тысячах, с округлением.

**Comment by kattrina-brekhova** [comment]
ага
у меня попадает 642 счет
нужно ее данные посмотреть
