### ISSUE TITLE
лажа с заполнением Додатка АМ к отчету на прибыль

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1319]
на начало года у меня не было ОС
![image](https://user-images.githubusercontent.com/38099938/73952172-5c475980-4907-11ea-9623-1348daa087e9.png)

делаю отчет за 1 квартал, все хорошо

![image](https://user-images.githubusercontent.com/38099938/73952238-6f5a2980-4907-11ea-9217-8489335fa0e8.png)

во 2 квартале уже начинается свистопляска - в качестве данных на начало периода использует  итог на конец прошлого квартала. аналогично и 3 квартал

![image](https://user-images.githubusercontent.com/38099938/73952946-543be980-4908-11ea-9e4c-62ba269c78db.png)

это не правильно в заполнении отчета внутри года

да, в 1 квартале следующего года, данные должны попасть с итогового остатка на конец прошлого года. внутри года нужно ставить всегда то, что было реально вначале года. если 0. значит 0 и 2 и 3 и за весь год

![image](https://user-images.githubusercontent.com/38099938/73953564-463a9880-4909-11ea-9ac3-8c8768cba5ec.png)

еще: удалила отчеты за все кварталы и сделала годовой

начальная сумма ОС попадает тоже не 0... а вот то, что у меня осталось после последней начисленной амортизации в каком-то из месяцев

(в 4 квартале амортизация не начисляла)

![image](https://user-images.githubusercontent.com/38099938/73953904-b8ab7880-4909-11ea-8ddb-c7bd18611bf7.png)

**Comment by AlexeyTishkin** [comment]
А сумма амортизации должна попадать тоже с начала года ?

**Comment by AlexeyTishkin** [comment]
Переделал.

**Comment by kattrina-brekhova** [comment]
работает
