### ISSUE TITLE
Бухгалтерська довідка вручну: странное поведение отражения суммы документа в общем списке

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1320]
показываю:
вот список доков:
![image](https://user-images.githubusercontent.com/38099938/74045165-f6290800-49d4-11ea-9cf9-964d640fb8cd.png)

открываю бух справку вручну
ничего не меняю, а просто например сморю проводки
![image](https://user-images.githubusercontent.com/38099938/74045221-0b9e3200-49d5-11ea-862b-653b6d0fd02e.png)

закрываю и смотрю на список доков
а сумма где-то пропала
![image](https://user-images.githubusercontent.com/38099938/74045268-1bb61180-49d5-11ea-80da-b677f6a7c398.png)

ну, ок, тыцаю например в другой пункт меню и снова возвращаюсь в бух справку
сумма появилась
![image](https://user-images.githubusercontent.com/38099938/74045332-37b9b300-49d5-11ea-9825-9b6ad98520e4.png)

такое поведение касается только ручных бух справок

**Comment by htrofymova** [comment]
исправлено
