### ISSUE TITLE
при расчете аванса через раздел зарплата а потом расчете зарплаты через раздел персонал неправильно указывает суммы

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1321]
начислила аванс
![image](https://user-images.githubusercontent.com/38099938/74093819-1691b900-4ae0-11ea-8f7b-6b05292ba4a5.png)
выплатила
расчитала зарплату
![image](https://user-images.githubusercontent.com/38099938/74093824-28735c00-4ae0-11ea-8432-a77d94ce4115.png)
создаю ведомость на пополнение карточных счетов
и такая сумма выходит
![image](https://user-images.githubusercontent.com/38099938/74093828-3c1ec280-4ae0-11ea-97d7-a413eb737bed.png)

хотя по идее должна быть 2332,74
5610 - 1 494,50 - 124,54 - 2 167,71

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/74093860-aa638500-4ae0-11ea-9d18-4c8556249acf.png)

![image](https://user-images.githubusercontent.com/38099938/74093867-bc452800-4ae0-11ea-878c-1ae56411febe.png)

**Comment by kattrina-brekhova** [comment]
на деве
test@3.ua
behappy1204
Чупакабра

**Comment by Illya-Lykhachov** [comment]
Исправлено. В т.ч. на сервисе
