### ISSUE TITLE
гривневое платежное поручение по операции "надходження коштів від продажу валюти" - не проводится, дает ошибку

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1324]
![image](https://user-images.githubusercontent.com/38099938/74144363-4686ac80-4c05-11ea-8449-841e4c3b0c01.png)

**Comment by kattrina-brekhova** [comment]
"сохранить" - єта же ошибка

**Comment by htrofymova** [comment]
Это настоящий номер счета? Потому что он длиннее 29 знаков

**Comment by kattrina-brekhova** [comment]
нет конечно
от фонаря
в этом может быть ошибка?
сейчас перепроверю с другим счетом

**Comment by kattrina-brekhova** [comment]
точно
да, с другим номером провелось
сори за панику
спасибо
![image](https://user-images.githubusercontent.com/38099938/74668005-039c7a00-51ad-11ea-8ed5-c36b4e7fe16c.png)
