### ISSUE TITLE
Предложение: заменить текст автоматического ответа на письма клиентов на почту саппорт

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1327]
сейчас єто выглядит так:

Ви маєте рацію, таке питання є актуальним. Так зроблено щоб користувачам було легше вносити дані в систему, що є важливим для правильної роботи онлайн-сервісу. В подальшому, вірогідно, ми вирішимо це питання таким чином, який ви запропонували.

Дякуємо, що допомагаєте нам зробити сервіс ще краще.

Лучше нейтральнее:

Дякуємо за звернення. Найближчим часом ми вирішемо ваше питання і з вами зв’яжемось.

Дякуємо, що допомагаєте нам зробити сервіс краще.

**Comment by AndriyNesterenya** [comment]
Сделал

**Comment by kattrina-brekhova** [comment]
дякую
