### ISSUE TITLE
при расчете аванса и зп сотрудник, по которому создан приказ на отпуск без сохранения зарплаты все-равно попадает в ведомость

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1328]

**Comment by Illya-Lykhachov** [comment]
Исправлено

**Comment by kattrina-brekhova** [comment]
все равно попадает
![image](https://user-images.githubusercontent.com/38099938/74436920-efd0db00-4e6f-11ea-96a0-9793244f5b08.png)
![image](https://user-images.githubusercontent.com/38099938/74436948-fcedca00-4e6f-11ea-9ed7-d60d86a04e85.png)
