### ISSUE TITLE
Персонал - Зарплата: дать возможность ручного ввода сумм ЗП в случае, если оклад не устанавливается приказом, а насчисляется сдельно/по табелю

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1329]
Есть куча схожих кейсов, когда у нас пытаются вестись компании с большим кол-ыом наемных сотрудников, ЗП которым насчитывается исходя из фактически отработанных дней/часов.
Такие люди часто считаю табель ручками в Экселе, а потом руками вводят что насчитали в ведомость 1С Бухгалтерии, чего хотят и от нас.
И все это с сохранением приказов о приеме на работу, отпусках и больничных.

Наобсуждали тезисно следующее:

Илья Лихачёв
То есть все хотят сдельшину вместо повременки
Можно в приказе о приёме на работу добавить метод начисления, и в расчетной ведомости каждому сотруднику или начислять по окладу или вводитт сумму сдельной оплаты

Anastaciia Lugovtseva
хотя, если они каждый месяц будут менять оклад, то аванс сидеть по каждому высчитывать — тот еще гемор. Либо его вообще не показывать, либо насчитывать стандартный аванс, а в ведомости на выплату уже руками ставить всем по 1000 грн. А потом в Расчете зп эта задолженность будет выплачена.
Это если калькулятором зп не пользоваться, потому что Кадры тоже нужны.

Прошу обсуждения и продолжения.

**Comment by AndriyNesterenya** [comment]
Пока предлагаю ничего не делать и сил на это не тратить.
Настина схема с назначением оклада каждый месяц всему списку сотрудников по трудоемкости  для буха не особо отличается от ручного ввода цифр в месяц
В уши страдающим бузам внес - будут пробовать

**Comment by Illya-Lykhachov** [comment]
Дал возможность вносить сумму начисления вручную, как в авансе, больничных, отпускных...

**Comment by MaksymTikhomirov** [comment]
Уря!

**Comment by Anestezia** [comment]
Есть, работает.
