### ISSUE TITLE
Амортизация закрытие 9 кл. счетов. добавить проводку

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1331]
Неприбыльщики спрашивали, 
9й класс счетов  на 791 закрывать

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Почему-то не могу провести амортизацию, не активна кнопка.

**Comment by htrofymova** [comment]
Ввели в эксплуатацию ОЗ с ликвидационной стоимостью превышающей первоначальну, в результате отрицательные и нулевые суммы амортизации. 
Добавила проверок.
