### ISSUE TITLE
ОСВ по 48му счету

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1333]
"1. 48 по аналитике, ее отчет мы не будем делать только стандартную ОСВ по счету. Дальше хай вставляет в свю форму копипастом. "

Dmytro Saltovets
Цільове фiнансування і цільові надходження

Alex Kukhtinadmin
Ok. Issue на Галину. Она сделает и привяжет к 48-м счетам.

Dmytro Saltovets
щас он синтетический, предлагается сделать аналитическим и аналитикой названой "Цільове фiнансування і цільові надходження"

**Comment by htrofymova** [comment]
готово в первом приближении

**Comment by htrofymova** [comment]
Готово. 
Так же добавлен Контрагент в бух.справку для операции "Визнання операційного доходу за рахунок цільових надходжень"
