### ISSUE TITLE
Таблицы 5 и 6 отчета Д4 (ЕСВ): сотрудники, которые выходят в отпуск без сохранения зп (например уход за ребенком) должны попадать дополнительной строкой в отчет

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1335]
кейс такой:
сотрудница ушла на больничный по родам, который заканчивается 27.01.
и с 28. идет в отпуск без сохранения
оба события должны попадать различными строками в отчет
ну или если до 27.01. сотрудник работает, а потом уходит с 28.01. в отпуск без сохранения зп — то тоже должны попадать разными строками
то есть, 1 строка - дата, когда заканчивается трудовой период 27.01
и 2 строка - когда начинается отпуск без зп - 28.01

**Comment by kattrina-brekhova** [comment]
в таблицу 6 тоже должны попадать дни без сохранения зп

**Comment by kattrina-brekhova** [comment]
Таблицю 5. Відомості про трудові відносини осіб та період проходження військової служби складають та подають лише у випадках, якщо протягом звітного місяця:

із застрахованою особою було укладено, або розірвано трудовий, або цивільно-правовий договір (на виконання послуг);
застрахованій особі надана, або в неї закінчилася відпустка у зв’язку з вагітністю та пологами, а також догляду за дитиною;
особу було переведено на іншу посаду у того ж страхувальника;
особа вперше вступила на військову службу, або її закінчила.
Якщо протягом податкового періоду з однією і тією ж особою було розірвано і знов укладено договір, в таблиці робиться два записи по такій особі з датами цих подій. У випадку надання, або закінчення відпустки, в таблиці також зазначаються ці дати. Відомості про початок та закінчення цивільно-правових відносин в рамках договору виконання послуг заносяться відповідно до строків, зазначених в самому договорі. А в рамках договору – відповідно до акту про надання послуг.

Розберемо алгоритм заповнення колонок таблиці.

У колонці 6 ставте «1», якщо особа, якій нараховано дохід – громадянин України. І «0» - іноземець.

У колонці 7 необхідно вказати вид роботи: основне місце, або за сумісництвом.

У колонці 8 зазначається категорія застрахованої особи, де:

«1» – наймані працівники з трудовою книжкою;
«2» – наймані працівники без трудової книжки (частіше за все такими робітниками є сумісники;
«3» – особи, які виконують послуги за цивільно-правовими договорами;
«4» – особи, яким надано відпустку по догляду за дитиною від 3 до 6 років;
«5» – особи, яким надано відпустку у зв’язку з вагітністю та пологами;
«6» – особи, яким надано відпустку по догляду за дитиною до 3 років;
«7» – особи з числа військовослужбовців, особи рядового і начальницького складу, які отримують допомогу у зв’язку з вагітністю та пологами;
«8» – особи з числа військовослужбовців, особи рядового і начальницького складу.

**Comment by kattrina-brekhova** [comment]
Таблиця 6. Відомості про нарахування заробітної плати (доходу, грошового забезпечення) застрахованим особам складають та подають всі суб’єкти господарювання, які у звітному місяці використовували працю фізичних осіб за трудовими та цивільно-правовими договорами. В ній зазначаються дані про суми нарахованих доходів, які входять до бази ЄСВ, а також інформація про застрахованих осіб. Також ця таблиця є підставою для складання Таблиці 1 звіту за формою Д4.

За загальними правилами на кожного працівника формується один рядок. Але існують винятки, згідно з якими на працівника складається більше одного запису. Зокрема, вони стосуються:

нарахованих виплату у звітному місяці, що відрізняються за базою ЄВ та розмірами ставок;
нарахованих виплат за майбутні періоди (відпускні, допомога при вагітності та пологах);
нарахованих виплат за минулий період (тимчасова непрацездатність, допомога при вагітності та пологах);
нарахованих виплат за виконану роботу (надані послуги) за періоди, строк виконання яких перевищує календарний місяць;
нарахованих виплат за відпрацьований час після звільнення;
нарахованих виплат у зв’язку з донарахуванням суми різниці між розміром мінімальною зарплатою та фактично нарахованою у звітному місяці.

Так, в колонці 9 потрібно вказати коди категорії застрахованих відоповідно до додатку 2 Порядку № 435. Найбільш поширеними кодами є:

«1» - для застрахованих осіб на загальних підставах;
«2» - для застрахованих осіб – працюючих інвалідів (розмір нарахувань ЄСВ – 8,41%);
«5» - для фізичних осіб-підприємців на загальній системі оподаткування;
«6» - для фізичних осіб-підприємців на спрощеній системі оподаткування;
«26» - для фізичних осіб, які виконують роботи (надають послуги) за цивільно-правовими договорами;
«29» - для нарахувань по тимчасовій непрацездатності;
«42» - для нарахувань допомоги у зв’язку з вагітністю та пологами.

**Comment by Illya-Lykhachov** [comment]
Насчёт отражения отпуска без сохранения зарплаты в таблице 6, не согласен. Согласно рашифровке кодов типов начислений: "10 – нарахована сума заробітку (доходу) за дні відпустки"
Во-первых **нарахована сумма**. Т.е. если начисленной суммы нет, то отражать не нужно (нечего).
Во-вторых. Для беспланого отпуска нет кода вида начислений, код 10 не подходит по определению.
Во-третьих. Если сотрудник ушёл в отпуск по уходу на 3 года, по нему все 3 года нужно рисовать пустые строки?

**Comment by Illya-Lykhachov** [comment]
Таблица 5. Добавил рожениц и мамашек

**Comment by kattrina-brekhova** [comment]
> Насчёт отражения отпуска без сохранения зарплаты в таблице 6, не согласен. Согласно рашифровке кодов типов начислений: "10 – нарахована сума заробітку (доходу) за дні відпустки"
> Во-первых **нарахована сумма**. Т.е. если начисленной суммы нет, то отражать не нужно (нечего).
> Во-вторых. Для беспланого отпуска нет кода вида начислений, код 10 не подходит по определению.
> Во-третьих. Если сотрудник ушёл в отпуск по уходу на 3 года, по нему все 3 года нужно рисовать пустые строки?

согласна, в 6 таблице только указывается в случае:

нарахованих виплат за минулий період (тимчасова непрацездатність, допомога при вагітності та пологах);
