### ISSUE TITLE
Курсовые разницы -- не активно Дополнительно Договор и Проект

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1337]
![image](https://user-images.githubusercontent.com/42540074/74652137-0d62b500-518e-11ea-8e0a-f7e46ebc1907.png)
Нет возможности их заполнить. ГО спрашивали, если есть разница.

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Есть. Теперь интересно, в каком отчете можно этот документ увидеть в разрезе проектов.
