### ISSUE TITLE
отчет 1ДФ: попадают суммы по наемным (код 101) и по ГПХ (код 102). а что с суммами по аренде от физлиц (рухоме, нерумоме) майно? у них кода 127 и 106 соответственно. как можно автоматизировать чтоб эти операции попадали в отчет?

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1338]

**Comment by Illya-Lykhachov** [comment]
Зачем движимое имущество относить на 127 код? 106 подходит для любой аренды.
"Дохід вiд надання майнa в лізинг, оренду абo суборенду (строкове володіння тa/абo користування), визначений у порядку, вcтановленому пунктом 170.1 стaтті 170 Кодекcу (пп. 164.2.5 п164.2 cт. 164 Кодексу)."
127 это вообще "Прочее" - 
"Інші доходи крім сум грошового зaбезпечення, грошових винагород та інших виплaт, одержаних військовослужбовцями, особами pядового і начальницького складу органів внyтрішніх справ, Державної кримінально-виконавчої cлужби України, Державної служби cпеціального зв’язку та захисту iнформації України, державної пожежної охорони, oрганів і підрозділів цивільного захисту, пoдаткової міліції у зв’язкy з виконанням обов’язків нeсення служби (пiдпункт 164.2.20 пyнкту 164.2 статті 164 pозділу IV Кодексу)."

**Comment by kattrina-brekhova** [comment]
налоговики в письме вот так пишут
http://cv.sfs.gov.ua/media-ark/news-ark/380643.html

с апреля кстати добавятся новые кода

**Comment by kattrina-brekhova** [comment]
новые кода https://news.dtkt.ua/accounting/reposts/60204

**Comment by Illya-Lykhachov** [comment]
Заодно в акт ГПХ от Зои.
"От нахіба ви так перестарались в отражении суммы "До сплати" - от начислено отняли все, что можно, включая ЕСВ???" 
![Zoya](https://user-images.githubusercontent.com/35328100/81140944-c48ff080-8f73-11ea-8e41-87777da04951.png)

**Comment by Illya-Lykhachov** [comment]
сделано

**Comment by kattrina-brekhova** [comment]
что-то не так с актом, не проводится
![image](https://user-images.githubusercontent.com/38099938/81786157-fc64de00-9507-11ea-929e-a1ba5259a522.png)

![image](https://user-images.githubusercontent.com/38099938/81786184-038bec00-9508-11ea-9ee4-c756e782da5d.png)

**Comment by Illya-Lykhachov** [comment]
исправлено
