### ISSUE TITLE
доработка операции получение НА в аренду: нельзя правильно провести

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1339]
1. в качестве "передает" указывается склад. видимо должен быть контрагент
2. создаю НА в справочнике "объекты учета"
![image](https://user-images.githubusercontent.com/38099938/74676644-1f108080-51bf-11ea-9c50-e0676c24ace7.png)
но в введении в экплутацию не видит
![image](https://user-images.githubusercontent.com/38099938/74676751-65fe7600-51bf-11ea-85a2-9c8c0c149609.png)

**Comment by htrofymova** [comment]
готово
