### ISSUE TITLE
НА  - Добавить аналитику Проект в Акты приймання/передачі об'єктів немат активов.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1340]
![image](https://user-images.githubusercontent.com/42540074/74733925-099a6580-5256-11ea-9a0c-92a6ee0d92c8.png)
Просят ГО

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Да, в Придбання есть. А в Продаж тоже может добавить? Тем, кто типа нас, торгует ПО, может пригодиться.
