### ISSUE TITLE
Бухгалтерская справка расчет курсовой разницы продажа валюты - поломана логика: доходы отражает как расходы, а расходы как доходы

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1341]
продала 100 долларов
курс НБУ (24,331) меньше чем муждубанковский, по которому была продажа (24,40)
![image](https://user-images.githubusercontent.com/38099938/74734509-5f234200-5257-11ea-8da8-167a478f3ceb.png)

в бухсправке 
![image](https://user-images.githubusercontent.com/38099938/74734601-8da11d00-5257-11ea-859f-1ca72cbcbdbd.png)
![image](https://user-images.githubusercontent.com/38099938/74734623-985bb200-5257-11ea-8e35-5f712eb9f9e3.png)

![image](https://user-images.githubusercontent.com/38099938/74734647-a4e00a80-5257-11ea-9c66-430fe7867061.png)

**Comment by kattrina-brekhova** [comment]
курсовая разница — расход — видит доходом
продала 100 долларов
курс НБУ (24,331) больше чем муждубанковский, по которому была продажа (22,00)
![image](https://user-images.githubusercontent.com/38099938/74735034-89293400-5258-11ea-995b-e569f92fb0c9.png)
![image](https://user-images.githubusercontent.com/38099938/74735056-92b29c00-5258-11ea-8864-c8f299f16497.png)

**Comment by kattrina-brekhova** [comment]
по операции курсовая разница покупка валюты таких проблем не наблюдается

**Comment by htrofymova** [comment]
Все навпаки:
1. перерахування валюти для продажу - ще не є продажем. В обліку - по курсу НБУ на дату перерахування.
2. курс продажу - це курс за яким була продана валюта, вказується в платіжці на зарахування гривень, зазвичай у призначенні платежу, наприклад: "Гривні від вільного продажу... по курсу...".  
3. Сума гривень від продажу - не є сумою гривнєвого еквіваленту в платіжці на переказ валюти для продажу (2440), а є сумою платіжки по зарахуванню гривень від продажу валюти (2433,10).

Курсові різниці нараховуються між сумою по курсу продажу та офіційним курсом на дату продажу: якщо курс НБУ більше курсу продажу - витрати, навпаки - дохід.
![image](https://user-images.githubusercontent.com/43743331/74751732-5e4dd880-5276-11ea-8e7a-16574eb9ae25.png)

**Comment by kattrina-brekhova** [comment]
постепенно заполняю бух справку:
выбираю валюту, курс у меня автоматически подтянул (я заранее завела в справочнике)
![image](https://user-images.githubusercontent.com/38099938/74757388-99540a00-527e-11ea-9687-0aeaab9f5592.png)

сумма в валюте - та сумма, которую я продала. и автоматически у меня расчитывается себестоимость валюты за курсом нбу
![image](https://user-images.githubusercontent.com/38099938/74757476-b8529c00-527e-11ea-8728-3854ec249121.png)

логично, что я понимаю, что в бух справке уже указана сумма проданной валюты, ее себес за курсом нбу,....а у меня еще есть одна цыфра - это та сумма, которая зашла на расчетный счет. и не сильно задумываясь в рядок "сума продажу" я ввожу сумму которой здесь недостает - вырученную за продажу валюты
![image](https://user-images.githubusercontent.com/38099938/74757724-11223480-527f-11ea-9a8f-d4a0dd3af11a.png)

сегодня клиентка с истерикой позвонила и говорит, что у нас не правильно
и я сама месяца 3 уже точно не заглядывала в эту операцию (работает - не ламаем), что позабыла алгоритм заполнения

и описываю поведение среднестатистического юзера

**Comment by kattrina-brekhova** [comment]
и в даном примере курс НБУ ниже, чем то, что зашло на счет
значит мы имеет доход

**Comment by kattrina-brekhova** [comment]
мы ведь получили 2440
а учитывалось в системе 100 долларов = 2 433,10

**Comment by htrofymova** [comment]
правильно. Смотрела старые примеры. Все правильно. Надо проверять.

**Comment by kattrina-brekhova** [comment]
и эти проводки правильные для ситуации, когда курс НБУ выше, чем к нам зашло на счет
![image](https://user-images.githubusercontent.com/38099938/74762203-0919c300-5286-11ea-9d1b-5fee45529d88.png)

то есть в логике операции все-таки что-то не так?

**Comment by htrofymova** [comment]
в "старых" операциях (август) все правильно. А новые - навпаки. ПРоверю и исправлю

**Comment by htrofymova** [comment]
готово

**Comment by kattrina-brekhova** [comment]
дяк
