### ISSUE TITLE
Юрлицо 3 группы -- Проценты по текущему счету и по депозиту должны включаться в доход (Бух. справка, Налоги)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1344]
Проценти, отримані від банку за користування коштами на рахунку (як депозитному, так і поточному), включаються до доходу юридичної особи — платника єдиного податку третьої групи.

**Comment by htrofymova** [comment]
готово.

**Comment by Anestezia** [comment]
Отлично! Работает.
