### ISSUE TITLE
к обсуждению кейс: налогообложение ФОП 3 группы доходы по % по остаткам - нужно включить в налогообложение

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1345]
с депозитом выяснили - что налогооблагает банк
а с остатком на счете не все так однозначно:
https://www.profiwins.com.ua/uk/letters-and-orders/ink/15261-4042-19.html
![image](https://user-images.githubusercontent.com/38099938/74957527-57f36400-5410-11ea-9e1e-cb801ec70f9f.png)

полагаю, что нужно допилять, чтоб операции получения % по остатках на валютном и гривневом счете включались в налогооблагаемый доход
сейчас он не включается
![image](https://user-images.githubusercontent.com/38099938/74957690-98eb7880-5410-11ea-9028-f9370c842a06.png)

![image](https://user-images.githubusercontent.com/38099938/74957748-aacd1b80-5410-11ea-9751-4a8dd0e68a35.png)

![image](https://user-images.githubusercontent.com/38099938/74957832-cafcda80-5410-11ea-8f5e-e9266c60a280.png)

**Comment by htrofymova** [comment]
готово
