### ISSUE TITLE
Повернення товару не учитывается в задачах Операций Бета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1346]
Є пов'язані документи: Рахунок - Видаткова накладна - Накладна на повернення. А на головному меню світиться - рахунок потребує оплати. Документи розпровести не вдається

![image](https://user-images.githubusercontent.com/42540074/75051790-31e4c700-54d7-11ea-81d0-df8387dc6c95.png)

**Comment by htrofymova** [comment]
готово
