### ISSUE TITLE
Нужна адекватная операция на Повернення товарів від комісіонера, а то на складе комитента не учитывается выбытие.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1347]

**Comment by htrofymova** [comment]
Добавлены две операции: "Повернення товарів від комісіонера", "Повернення товарів комітенту". Создаются на основе, соответственно, расходной накладной "Передача товарів на комісію" и приходной "Отримання товарів від комітента".

**Comment by Anestezia** [comment]
Работает. И из Накладной если делать, и просто без привязки из операций. В обоих документах.
