### ISSUE TITLE
Добавить Посаду подписанта в первичные документы и счета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1355]
Прохання додати посаду особи, яка підписує документ від імені підприємства. Відповідно до ПОЛОЖЕННЯ про документальне забезпечення записів у бухгалтерському обліку документ має містити ПОСАДИ і прізвища осіб, відповідальних за здійснення господарської операції. На сьогодні в системі Буккіпер при обранні посадової особи в документ додається лише Прізвище та ініціали, тож по-правильному доводиться дописувати посаду вручну.

**Comment by htrofymova** [comment]
готово.

**Comment by Anestezia** [comment]
Есть!
