### ISSUE TITLE
ведомость амортизации: в некоторых периодах не хочет рассчитывать - пишет, что в этом периоде амортизация уже рассчитана, хотя документов проведенных за этот период нет + странное поведение при расчете ведомости

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1357]
такое подозрение, что она не хочет создавать ведомость по тем периодам, по которым были созданы ведомости, но потом я их удаляла
знаю, звучит как бред
но иного понимания нету
еще 5 минут назад создала ведомость за апрель, потом удалила
а теперь уже не могу это сделать - пишет, что уже расчитана была

![image](https://user-images.githubusercontent.com/38099938/76094404-3fb44500-5fcb-11ea-9f9a-a5069471ff36.png)

хотя вот все доки по амортизации, которые у меня есть

![image](https://user-images.githubusercontent.com/38099938/76094451-55296f00-5fcb-11ea-9e6c-3efb900bea7e.png)

еще интересное 

таки пытаюсь за апрель рассчитать - она не дает, пишет, что уже рассчитана амортизация

делаю ход конем, меняю период
к примеру на май, она заполняет 

![image](https://user-images.githubusercontent.com/38099938/76094718-c1a46e00-5fcb-11ea-8d15-75bfab302553.png)

а теперь меняю дату и провожу апрелем с текущими за май данными

![image](https://user-images.githubusercontent.com/38099938/76094809-e4cf1d80-5fcb-11ea-914e-53c17415cc68.png)

**Comment by kattrina-brekhova** [comment]
на бете
test@3.ua
behappy1204

фирма ОмегО

**Comment by htrofymova** [comment]
исправлено
