### ISSUE TITLE
Создание операции. Печать/экспорт нового пустого документа не работает.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#136]
Из любого раздела "Операции" создать операцию и сразу нажать "Печать/експорт"
Результат - пустая страница.
Чтобы появилась печатная форма, приходится внести хоть какое-нибудь изменение в документе.

**Comment by AlexeyTishkin** [comment]
А что ты печатать собрался ? Документа то нет.

**Comment by MaksymTikhomirov** [comment]
> А что ты печатать собрался ? Документа то нет.

А если вдруг захотелось РАСПЕЧАТАТЬ И ОТ РУКИ ЗАПОЛНИТЬ?
  бггг

**Comment by AlexeyTishkin** [comment]
> РАСПЕЧАТАТЬ И ОТ РУКИ ЗАПОЛНИТЬ?

:) Пустографка все равно не напечатается...

**Comment by nik-man** [comment]
Любой новый документ можно напечатать пустым. Достаточно просто добавить пробел в примечание и будет печататься пустой бланк. Но если ничего не делать -- то кнопка "печать/экспорт" выводит пустой экран.
Мне кажется, это не совсем правильно. Или пусть печатает пустой бланк или выводит сообщение "Заполните документ" или будет неактивна. Думаю, пустой бланк предпочтительнее.

**Comment by AlexeyTishkin** [comment]
> Любой новый документ можно напечатать пустым.

Новый напечатать нельзя. Ничего нет.

> Достаточно просто добавить пробел в примечание

Это уже не новый. В этом случае документ уже есть в базе.

**Comment by Illya-Lykhachov** [comment]
"Пустографка" - в сад. Нужно кнопку "Печать/экспорт" сделать disabled, если Модель.$isNew=true

**Comment by AlexeyTishkin** [comment]
В товарных документах сделал.

**Comment by nik-man** [comment]
Может правильнее написать "Спочатку заповнить документ." або "Спочатку внесить дані." ?
Ведь печать становится возможной после появления данных в документе.

**Comment by AlexeyTishkin** [comment]
> Ведь печать становится возможной после появления данных в документе.

Печать становится возможной после появления документа, даже без данных.

**Comment by nik-man** [comment]
Ок.
