### ISSUE TITLE
Ведомость амортизации: кнопка "провести" не активна

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1363]
![image](https://user-images.githubusercontent.com/38099938/76629780-8368fa80-6547-11ea-9d79-874260274db9.png)

**Comment by htrofymova** [comment]
В одной из строк сумма амортизации = 0 (ввод в эксплуатацию очень старый, не заполнен "термін корисного використання", сейчас такое сделать невозможно). Сделала, чтобьі это бьіло видно "красньім".

**Comment by kattrina-brekhova** [comment]
ага
точно
спасибо
