### ISSUE TITLE
виготовлення ОЗ: указала материалы и расходы при изготовлении, но в строка "ликвидационная стоимость" подствечена красным - мол не может быть больше первичной стоимости. расчет первичной стоимости происходит только после проведения документа. указать ликвидационную стоимость получается только распроведя документ

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1364]

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/76747763-53596b80-6782-11ea-9501-0071e2d4e05e.png)

закладка необоротний акти подствечивает, что есть ошибка (имеется в виду строка "ликвидационная стоимость")
![image](https://user-images.githubusercontent.com/38099938/76747862-826fdd00-6782-11ea-8038-62fc33e66056.png)
и провести нельзя
только если удалив значение со строки ликвидац стоимость
![image](https://user-images.githubusercontent.com/38099938/76747923-97e50700-6782-11ea-8e4e-557c4f50d990.png)

**Comment by kattrina-brekhova** [comment]
введя все расходы программа считает перичную стоимость только после проведения
это не проведенный документ
![image](https://user-images.githubusercontent.com/38099938/76748619-bef00880-6783-11ea-9f77-4f94136bd53d.png)

**Comment by kattrina-brekhova** [comment]
кстати, в панели управления нет блок-схемы" выготовлення" - так и задумано или забыли?

**Comment by htrofymova** [comment]
Переделала расчет суммы.
На панели управления заменила:  "Виготовлення" замість "Поліпшення" (так как "Поліпшення" не актуально теперь).

**Comment by kattrina-brekhova** [comment]
спасибо
а почему не актуально?
я что-то пропустида?
операция создается только с пунтка "операции"?

**Comment by htrofymova** [comment]
не пропустила, забыла, мы даже обсуждали ( в телеграмме 27/01). Нельзя теперь относить затраты на ремонт ОС на увеличение стоимости.

**Comment by kattrina-brekhova** [comment]
это в связи с изменением методологии - вот то что недавно было?

**Comment by kattrina-brekhova** [comment]
операция улучшение ОС формирует такие проводки
![image](https://user-images.githubusercontent.com/38099938/76768289-76484780-67a3-11ea-8366-af8773918b52.png)

**Comment by htrofymova** [comment]
операция, какя была, такая и осталась, просто делать ее не нужно, или нельзя, наверно.

**Comment by kattrina-brekhova** [comment]
так, все вспомнила
ок
дякую
