### ISSUE TITLE
[Bug] Косяк с версткой в Счете - Панель управления.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1365]
Имеем косяк.
Если у счета больше 3х отгрузок - картинка не влазит в окно и не скроллится влево
![image](https://user-images.githubusercontent.com/38098758/76964748-dd910380-692b-11ea-80ff-334ec8aeaad1.png)

Это та панель управления, которая слева на окне счета.
![image](https://user-images.githubusercontent.com/38098758/76964875-10d39280-692c-11ea-914f-9e854cad693c.png)

**Comment by alex-kukhtin** [comment]
Done
