### ISSUE TITLE
В валютные операции нужно получение возвратной помощи (или кредита от банка)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1366]

**Comment by htrofymova** [comment]
Добавлено 4 операции: 
Отримання кредиту в валюті: ДТ 312 - КТ 502 (долгосрочный);
Отримання кредиту в валюті (до 12 міс.): ДТ 312 - КТ 602 (краткосрочный, до 12 месяцев);
Погашення кредиту в валюті:  ДТ 502 - КТ 312;
Погашення кредиту в валюті (до 12 міс.): ДТ 602 - КТ 312.
Для начисления курсовых разниц по телу кредита в списки счетов для операций "Операційна курсова різниця (витрати/дохід)" добалены счета : 502, 602,
