### ISSUE TITLE
Добавить операции от инвестора: Взнос в уставной капитал другого предприятия

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1369]
Надо операцию для инвестора сделать с двумя проводками, чтобы в платежке сразу формировались. 

Бухгалтерський облік у інвестора. Як ми вже зазначали, придбаваючи в емітента корпоративні права, інвестор фактично придбаває фінансову інвестицію. При цьому така інвестиція, як правило, є довгостроковою. Адже корпоративні права отримуються з метою отримання доходу протягом часу, що перевищує 1 рік. Такі інвестиції слід відображати за дебетом рахунка 14 «Довгострокові фінансові інвестиції».

Зазначений рахунок має три субрахунки. На субрахунку 141 відображають інвестиції пов’язаним сторонам за методом участі в капіталі, на субрахунку 142 — інші інвестиції пов’язаним сторонам, а на субрахунку 143 — інвестиції непов’язаним сторонам.

![image](https://user-images.githubusercontent.com/42540074/77535075-9c0bd580-6ea2-11ea-9d46-971aa8d04c0b.png)

У нас есть операция в платежах Перерахування коштів іншим кредиторам дт 685 кт 311
Как вторую часть сделать специальную операцию для бухсправки.

**Comment by htrofymova** [comment]
готово.
