### ISSUE TITLE
раздел персонал: акт за договором цпх - неправильно отражения чистой и грязной сумм вознаграждения

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1374]
сумма за договором 20 000
![image](https://user-images.githubusercontent.com/38099938/78684202-dfc9fa80-78f8-11ea-95d9-f6a03662e9c5.png)
сумма к выплате должна быть за минусом налогов = 16 100
![image](https://user-images.githubusercontent.com/38099938/78684368-0b4ce500-78f9-11ea-974f-afcfb8642378.png)
в печатной форме документа стоит, что сумма вознаграждения исполнителя 20 000
так и должно быть

грязная сумма для рассчета берется из договора та, которую мы указали как вознагражение исполнителю

**Comment by Illya-Lykhachov** [comment]
Исправлено
