### ISSUE TITLE
Перенос информации по прошлым начислениям ЗП из Начального баланса для расчета Средней по отпуску.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1377]
У меня сотрудник работает с 1.01.19. Базу я начала вести 1.01.20. Создала Начисление ЗП только за 2 месяца. А остальные ЗП указала в Начальном балансе по ЗП. Ранее был разговор, что при расчете отпускных эти месяцы учитываются. оказалось — нет.
Вот начальный баланс:
![image](https://user-images.githubusercontent.com/42540074/79326143-0c929900-7f1b-11ea-8d81-142fde2e9383.png)
сотруднику за прошлые месяцы все выплачено, в остатках по 661, 663 ничего не ставлю.
![image](https://user-images.githubusercontent.com/42540074/79326194-22a05980-7f1b-11ea-9e2d-351e4c83ff6d.png)
Итог:
![image](https://user-images.githubusercontent.com/42540074/79326271-3fd52800-7f1b-11ea-85be-87cd5483c519.png)

**Comment by Illya-Lykhachov** [comment]
Исправлено
