### ISSUE TITLE
отчет по есв таблица 6: отпуск без сохранения зп сотрудника на целый месяц должен показываться в таблице

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1378]
задача касается месяцев выхода в отпуск и его окончания
я в бк дала сотруднику отпуск на месяц, но он в таблицу не попал
а должен был и заполняются такие колонки:
9 - прочерк
10 - прочерк
11 - месяц
14 - кол-во дней отпуска (весь месяц)
15 - кол-во дней труд отношений
18 - 0
19 - 0
21-0,00

**Comment by kattrina-brekhova** [comment]
у нас в БК обязательно нужно заполнить колонку 9 (незаполненная считается ошибкой)
но так поняла, что в случае с отпуском без сохранения зп она не заполнятся

**Comment by Illya-Lykhachov** [comment]
Если суммы взноса нулевая, то и в отчёт этот сотрудник не попадает.
Читаем название отчёта "**Сведения о начислении зарплаты**". Нет начислений - нет сведений.

**Comment by kattrina-brekhova** [comment]
по тем месяцам, в которых сотрудник ушел в отпуск или вышел из него, даже без начисления зп сотрудник отражается в 6 таблице

**Comment by kattrina-brekhova** [comment]
я по этой теме вебинар слушала
и Мойсеенко 100% об этом упоминала
конечно, сотрудник не попадает в месяц неначисления зп, если в этом периоде не было "значимых" дат - выхода на работу, ухода в отпуск

но если эти даты были, они показываются в таблице

собственно, колонка 14 для этого и предназначена - кол-во дней без сохранения зп
