### ISSUE TITLE
таблица 6 отчета с есв: нужно чтобы доначисление есв по минималке делалось отдельной строкой - сейчас БК лепит одной строкой

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1379]
кол-во дней отпуска без сохранения зп должно показываться в колонке 14
![image](https://user-images.githubusercontent.com/38099938/79732766-c9f70500-82fc-11ea-8ff1-07f72c3402e0.png)

в колонке 21 должна указываться сумма начисленного есв (даже на ту маленькую часть начисленной зарплаты)? а в строку ниже — сумма доначисления
![image](https://user-images.githubusercontent.com/38099938/79733050-35d96d80-82fd-11ea-80c6-7ba5dc45e5c0.png)

**Comment by kattrina-brekhova** [comment]
доначисление нужно делать с кодом 13. не получается это сделать

или может это не совсем поняла заполнение этой таблицы, и для начисления нужно добавить строку для этого сотрудника и проставить нужные данные?

**Comment by kattrina-brekhova** [comment]
ага, поняла. буккипер лепит все в одну строку, но нужно разбивать

**Comment by kattrina-brekhova** [comment]
вот так нужно
![image](https://user-images.githubusercontent.com/38099938/79734172-f57aef00-82fe-11ea-8fe4-8c63d923c46a.png)

**Comment by kattrina-brekhova** [comment]
но бывает, что не нужно доначислять, если совместитель

**Comment by Illya-Lykhachov** [comment]
Доначисление правильно отражается в отчёте. Если оно есть.

![image](https://user-images.githubusercontent.com/35328100/81899072-ac971d00-95c2-11ea-9c9b-89398ef8a5f0.png)

![image](https://user-images.githubusercontent.com/35328100/81899001-82455f80-95c2-11ea-9574-21fada5a9184.png)
