### ISSUE TITLE
Счет исходящий. Селектор расчетного счета. Ошибка создания нового расчетного счета.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#138]
Создать или открыть счет на оплату.
Раскрыть список расчетных счетов.
Попытаться добавить новый.
![create_acc_from_account](https://user-images.githubusercontent.com/35918141/39926708-b298f0f6-5538-11e8-8123-bb18763653ff.png)

**Comment by AlexeyTishkin** [comment]
Это проблема не "Счета исходящего". Расчетный счет сейчас нигде не создается/изменяется.

**Comment by nik-man** [comment]
В свойствах субъектов и моей фирмы создается.

**Comment by AlexeyTishkin** [comment]
Так и из счета уже работает...
