### ISSUE TITLE
Инвентарная карточка ОУ НА СЕРВИСЕ  - не выставляет дату (стоит по умолчанию 2999 год - никак не меняется), на деве такой проблемы не наблюдается

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1380]
![image](https://user-images.githubusercontent.com/38099938/79877303-c050c880-83f4-11ea-966b-e4ddcd6606e3.png)

![image](https://user-images.githubusercontent.com/38099938/79877337-c9da3080-83f4-11ea-959b-f25ae0af8a66.png)

**Comment by htrofymova** [comment]
Изменено.
Так как "в жизни" "Инвентарная карта" содержит ВСЕ данные о необоротном активе, т.е. выбор периода не имеет смысла, то теперь отчет "Инв.карта ОЗ" строится ВСЕГДА на текущую дату, дату поменять нельзя.

**Comment by Anestezia** [comment]
Да, теперь без даты. 
![image](https://user-images.githubusercontent.com/42540074/80700568-9aa77b80-8ae6-11ea-8005-7b3fd5034180.png)
