### ISSUE TITLE
Начальный баланс НА - не начислять амортизацию, если стоимость+износ+ликвидационная стоимость=0.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1381]
Ввожу нач. остатки, стоимость 10 000,00, износ 9000,00, ликвидационная стоимость - 1000,00. Год изготовления  2019, срок эксплуатации 10 месяцев. В ведомость амортизации попадает. Объект Чугунок.
![image](https://user-images.githubusercontent.com/42540074/79986616-00778000-84b5-11ea-9ea9-019824d2adb1.png)
![image](https://user-images.githubusercontent.com/42540074/79986641-09685180-84b5-11ea-842b-43afb71e8474.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Все ок.
