### ISSUE TITLE
бланк отчета S0110011 заменить на S0110012 (форма 1м)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1384]
изменилось?
1. название:
Фінансова звітність малого підприємства

2. появились дополнительные строки для отражения нематериальных активов

![image](https://user-images.githubusercontent.com/38099938/80392555-00fa8700-88b8-11ea-8ff2-f5b00c20774d.png)

**Comment by kattrina-brekhova** [comment]
алгоритм заполнения такой же, как и в балансе
![image](https://user-images.githubusercontent.com/38099938/80399489-f0e7a500-88c1-11ea-93a8-aa7727fc15cc.png)

РЯДОК 1000: Відображають вартість об’єктів, віднесених до складу нематеріальних активів.
До підсумку балансу включають залишкову вартість, яку визначають як різницю між первісною вартістю та сумою накопиченої амортизації, що наводять у дужках.

Тобто відображають різницю рядків 1001 та 1002

РЯДОК 1001: Дт субрахунків рахунка 12 «Нематеріальні активи»
або якщо за спрощеним планом рахунків: Дт рахунка 10 «Основні засоби» (вибірка по нематеріальних активах)

РЯДОК 1002: Кт субрахунку 133 «Накопичена амортизація нематеріальних активів»
або якщо за спрощеним планом рахунків: Кт рахунка:
13 «Знос необоротних активів» (вибірка за нематеріальними активами)

**Comment by htrofymova** [comment]
готово

**Comment by MaksymTikhomirov** [comment]
Спасибо!

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/81168265-5a8d4080-8f9f-11ea-948a-9dc3f8c9a613.png)

еще название нужно изменить Фінансова звітність малого підприємства

https://i.factor.ua/ukr/journals/buh911/2019/july/issue-29/article-45583.html

![image](https://user-images.githubusercontent.com/38099938/81169309-519d6e80-8fa1-11ea-93e4-11c673717742.png)

**Comment by htrofymova** [comment]
исправлено
