### ISSUE TITLE
Косяки в верстке и печати "АКТ ПРИЙОМУ-ПЕРЕДАЧІ ОБ'ЄКТА НЕМАТЕРІАЛЬНИХ АКТИВІВ"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1386]
Нашлись косяки при печати "АКТ ПРИЙОМУ-ПЕРЕДАЧІ ОБ'ЄКТА НЕМАТЕРІАЛЬНИХ АКТИВІВ"

1. При экспорте подставляется странное имя файла "_.._printforms_act_out_IA"

2. Если полное название контрагента не помещается в одну строку - обрезается и при печати и при экспорте в PDF (причем по-разному)

Печать:
![image](https://user-images.githubusercontent.com/38098758/80732259-b9246b80-8b14-11ea-9375-0871eb744fb0.png)

Экспорт:
![image](https://user-images.githubusercontent.com/38098758/80732338-d6593a00-8b14-11ea-8470-de6ac9cb6b0f.png)

**Comment by htrofymova** [comment]
готово
