### ISSUE TITLE
[Улучшайзинг] добавить текстовое название к операции "Створення рецептури"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1387]
Нарисовалось неудобство для производства.
У нас все рецептуры имеют номер, но не имеют имени/названия.
В результате когда нужно найти и проверить или изменить рецептуру на конкретную продукцию в списке невозможно.
Народ выкручивается путем выписывания названий в Примітку, но выглядит криво и нелогично.

Просят или добавить отдельное поле названия, или выводить имя готовой продукции вместо или рядом с названием операции.

![image](https://user-images.githubusercontent.com/38098758/80747684-7b334180-8b2c-11ea-8c06-b1033dc6a720.png)

**Comment by htrofymova** [comment]
готово.
