### ISSUE TITLE
Видатковий касовий ордер "оплата іншим кредиторам": відмінити заборону вибору контрагентом юридичну особу

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1390]
![image](https://user-images.githubusercontent.com/38099938/81781537-ee5f8f00-9500-11ea-9ded-35a414e543c0.png)

![image](https://user-images.githubusercontent.com/38099938/81781570-020af580-9501-11ea-953e-1ee49c557e19.png)

**Comment by kattrina-brekhova** [comment]
єто сообщение появляется на "провести"
кнопка "сохранить" не активна

**Comment by htrofymova** [comment]
готово

**Comment by kattrina-brekhova** [comment]
странно, но у меня по прежнему не проводится
![image](https://user-images.githubusercontent.com/38099938/81912747-b0816a00-95d7-11ea-81e3-589ffd9dbf49.png)

![image](https://user-images.githubusercontent.com/38099938/81912776-baa36880-95d7-11ea-9351-6206b7c29a40.png)

на деве

test@3.ua
behappy1204

ТОВ Омего
