### ISSUE TITLE
нужна операция выплаты больничных с 663 счета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1391]
у клиента зашли деньги с ФСС (больничные)
видимо еще за прошлый год - они их вводили вступительным балансом
теперь их нужно выплатить
сейчас больничные начисления идут по 663 счету
но выплата по 661

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/1005

**Comment by Anestezia** [comment]
Прошу зробити так, щоб у платіжному дорученні при перерахунку із Спецрахунка Фонду соц страхування лікарняних співробітнику відображалась проводка Д 663 К 311, а не Д 661  К311. і закривався рахунок 663!
Платіжне доручення надсилаю. Персей
![image](https://user-images.githubusercontent.com/42540074/127023056-cd6e6734-5538-429b-a3a4-184e54260fed.png)
![image](https://user-images.githubusercontent.com/42540074/127023088-c41e066c-656f-4b55-92b0-4bf9320925b3.png)

**Comment by htrofymova** [comment]
Сделала такой вариант: больничньіе начисляются по кт 663 (как и бьіло); в операции "Виплати ..." добавила проводку дт 663 кт 661 на сумму больничньіх. вьіплата з/п, как и раньше, всей суммой по дт 661. Т.о. закрьівется 663 счет.
