### ISSUE TITLE
ведомость выплаты зарплаты на карточки: при создании на основании расчетной ведомости - создается и проводится. если делать отдельной ведомостью - нет

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1396]
кнопка "сохранить" не активная
при попытке проведения

![image](https://user-images.githubusercontent.com/38099938/83156803-85386800-a10b-11ea-973b-1f6740aebe04.png)

дев
ТОВ ОМЕГО

test@3.ua
behappy1204

**Comment by Anestezia** [comment]
1. Создать ведомость на выплату по банку.
2. Выбрать зарплатный проект - кнопка "Зберегти" не активна
3. Нажать кнопку "Заповнити" или дату поменять, а потом назад вернуть, или номер. Любое изменение. Кнопка "Зберегти" становится активной и можно сохранить и  проводить.
