### ISSUE TITLE
ведомость РРО: не видит перемещенный товар

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1398]
переместила товар на нужный склад
![image](https://user-images.githubusercontent.com/38099938/83172738-b707f980-a120-11ea-8485-424391e0e592.png)

продала с этого склада
![image](https://user-images.githubusercontent.com/38099938/83172994-0ea66500-a121-11ea-82c6-0767330e0d02.png)

![image](https://user-images.githubusercontent.com/38099938/83173018-1534dc80-a121-11ea-8ab9-b61ee7b47620.png)

но при создании ведомости РРО товар не видит

![image](https://user-images.githubusercontent.com/38099938/83173092-2f6eba80-a121-11ea-8d32-9afdf08485da.png)

**Comment by kattrina-brekhova** [comment]
и вообще не видит товар
оприходовала товар на нужный склад - и все равно не видит

**Comment by htrofymova** [comment]
исправлено
