### ISSUE TITLE
Операция Оплата банковских процентов по кредиту в валюте

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1400]
Просят Сплату відсотків по валютному кредиту. Дт 915 кт 684. Нет такой операции в банке и никак вручную ее создать тоже не могут
не могут именно в банковской выписке операцией закрыть, и теперь не идет остаток. Кредит погасили, а теперь проценты по нему.
дт 915 кт 684 — сделали в бухсправке начисление процентов. А теперь фактическую оплату их желают.

**Comment by htrofymova** [comment]
готово. Добавила 2 операции: для гривны и валюты
