### ISSUE TITLE
операция Переміщення ТМЦ: при нажатии на строку выбора ОУ выдает ошибку 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1401]
![image](https://user-images.githubusercontent.com/38099938/83404737-d8643080-a413-11ea-8ad6-6b1ec1751ae3.png)

**Comment by htrofymova** [comment]
Прямо сейчас вносятся изменения. Извините за временные неудобства

**Comment by kattrina-brekhova** [comment]
пардон
не мешаю)
