### ISSUE TITLE
Нет проводки в Формування Відомості РРО. Нужно срочно так как касса не сходится!

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1402]
![image](https://user-images.githubusercontent.com/42540074/84490996-96a57680-acac-11ea-822f-602ca8d72a55.png)
![image](https://user-images.githubusercontent.com/42540074/84491029-a1600b80-acac-11ea-8233-62dc24953a86.png)

**Comment by htrofymova** [comment]
готово
