### ISSUE TITLE
новая операция "выручка по эквайрингу" не попадает в базу налогообложения?

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1403]
хотела проверить, какая сумма попадает в базу налогообложения - с комиссией, или без
в итоге в расчете налогов, этой операции вообще не оказалось
![image](https://user-images.githubusercontent.com/38099938/84777352-266b5d80-afea-11ea-961b-706400b5fa84.png)

![image](https://user-images.githubusercontent.com/38099938/84777399-35521000-afea-11ea-8ef0-d5afbac8496d.png)

как так?
в таких операциях ведь тоже есть нюанс
хоть продажа и состоялась, например, 31.12, а деньги зашли 03.01, то сумма продажи через эквайринг попалает в базу уже следующего периода - 03.01

Якою датою в Книзі обліку доходів і витрат записати отримані оплати?

В Книгу обліку доходів і витрат записи вносяться однією сумою в гривнях з копійками за підсумком кожного дня. Одночасно окремими сумами записуються готівкові та безготівкові доходи.

Отримавши оплату через термінал, підприємець не має справу з готівкою. Тому така розрахункова операція для підприємця є «безготівковою».

А безготівкові операції відображаються в Книзі доходів на дату надходження коштів на рахунок в банку. Про це свідчить і п. 292.6 ст. 292 ПКУ: датою отримання доходу платника ЄП є дата надходження коштів платнику ЄП у грошовій (готівковій або безготівковій) формі.

Отже, 29 грудня вказується 10 000 гривень

03 січня записується 5 000 гривень.

**Comment by kattrina-brekhova** [comment]
речь идет о фоп 3 группа

**Comment by htrofymova** [comment]
исправлено

**Comment by kattrina-brekhova** [comment]
не попадает, что-то не так делаю?

![image](https://user-images.githubusercontent.com/38099938/85690975-c0af5d80-b6dc-11ea-9de6-77e2f2d5ff13.png)

![image](https://user-images.githubusercontent.com/38099938/85691028-cd33b600-b6dc-11ea-9918-ba986239072a.png)

![image](https://user-images.githubusercontent.com/38099938/85691061-d4f35a80-b6dc-11ea-9b13-6177423221e1.png)

![image](https://user-images.githubusercontent.com/38099938/85691123-e50b3a00-b6dc-11ea-914d-e6880cf5dc62.png)

**Comment by htrofymova** [comment]
готово
