### ISSUE TITLE
Додати можливість створювати декілька Накладних та актів з Авансового звіту.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1404]
![image](https://user-images.githubusercontent.com/42540074/85291903-cbcb7900-b4a3-11ea-96b7-034d77af40dd.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/91274265-19f04780-e787-11ea-9122-9395254ee8d9.png)
![image](https://user-images.githubusercontent.com/42540074/91274328-2eccdb00-e787-11ea-9249-56530a9c3e12.png)
![image](https://user-images.githubusercontent.com/42540074/91274407-4e640380-e787-11ea-9f16-b6ea9da863d8.png)

У меня покупка в один день у двух разных контрагентов, агропостач и нова линия. А вторая накладная или акт создается только на первого контрагента без возможности редактирования. Просьба открыть редактирование контрагента в акте и накладной, созданных на основании авансового отчета.

**Comment by htrofymova** [comment]
готово
