### ISSUE TITLE
Текст примера счета и платежки -- изменение

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1405]
Мы платник ПДВ с 24.06
Нужно будет добавить в текст Счета клиенту в ЛК данные об этом,

после номера ЄДРПОУ запятая, и пишем ІПН 419913726555, запятая и в следующей строке Є платником  податку на прибуток на загальних підставах.

**Comment by Anestezia** [comment]
"запятая и в следующей строке Є платником податку на прибуток на загальних підставах." Это тоже, как я поняла, надо?
![image](https://user-images.githubusercontent.com/42540074/94143612-c140c700-fe78-11ea-86a4-15f07df52b51.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Есть.
