### ISSUE TITLE
Шапка счета + ПДВ + система налогообложения

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1406]
Выяснилось, что в "шапку"  счета  прочих документов не попадает информация о номере плательщика ПДВ и вообще о системе налогообложения.

Хорошо бы если в настройках фирмы стоит галка "Є платником ПДВ" поле номера плательщика непустое - выводить в шапку под строкой с ЕДРПОУ текст
**_Є платником ПДВ
ІПН ХХХХХХХХХХХХХХХ_**

+если в поле "Система оподаткування" стоит "Платник податку на загальних підставах" - выводить отдельной строкой
**_Є платником податку на прибуток на загальних підставах_**

+если в поле "Система оподаткування" стоит любой "Єдиний податок ...."   - выводить отдельной строкой
**_Є платником єдиного податку_**

**Comment by htrofymova** [comment]
Добавлено в следующие "прочие" документы:
рахунок (продаж), видаткова накладна, акт виконаних робіт (продаж), накладна на повернення постачальнику, накладна на повернення від покупця.
Если еще в какие-то "прочие" нужно добавить, перечислите, пожалуйста.

**Comment by Anestezia** [comment]
Есть, в перечисленных документах. и на едином и на общей
