### ISSUE TITLE
Производство, Рецептуры: реализовать возможность включать в Рецептуру ранее произведенные объекты (полуфабрикат?)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1407]
Имеем реальный кейс в качестве иллюстрации:
Компания закупает полиамидную нить и производит из нее веревку (у нас при этом эта самая веревка после Акта производства есть Готовой продукцией).
Произвольная часть этой веревки тут же продается.
Другая часть является сырьем/комплектующим для производства более сложной продукции, типа стропов и страховочных поясов.
А наша "Рецептура" не позволяет использовать готовую продукцию в качестве входящих элементов.

Задача - минимальными усилиями таковую возможность реализовать.

Обсуждались варианты:
1. "Просто" разрешить включать готовую продукцию в Рецептуру. (но были возражения со стороны учета)
2. "Как в 1С" иметь возможность "перебросить со счета на счет", т.е. сменить тип с "Готовой продукции" на "Товар"
3. Ввести понятие Полуфабрикат, и изменить Рецептуру, чтобы на выходе по выбору получать или полуфабрикат или готовую продукцию, тдт  ввести новую отдельную Рецептуру для полуфабрикатов.

**Comment by htrofymova** [comment]
"Просто" разрешила включать готовую продукцию в Рецептуру и Акт изготовления. Не нашла именно запретов (только рекомендации) использовать готовую продукцию опять в производстве без перевода в сырье-материалы. Пусть попробуют.

**Comment by Anestezia** [comment]
Есть, работает
