### ISSUE TITLE
Документы для "Повернись Живим" и благотворителей 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1408]
Реализовать два документа для Повернись живим
Письмо - заявку на благотворительную помощь + Акт приема-пережачи юлаготворительной помощи
Печатные формы: 
[587 лист.xlsx](https://github.com/a2develop/bugTracker/files/4884862/587.xlsx)
[587 акт.xlsx](https://github.com/a2develop/bugTracker/files/4884863/587.xlsx)

Желательно успеть до конца июля.

**Comment by kattrina-brekhova** [comment]
вроде ок
можно изменить еще название пункта раздела "благодійна допомога військовим" или "благодійна допомога військового характеру" - чтоб народ понимал о чем єто

**Comment by AndriyNesterenya** [comment]
Косячит заявка по верстке при попытке добавить строку
![image](https://user-images.githubusercontent.com/38098758/87978456-165b0800-cad9-11ea-8550-32975401cd6e.png)
или несколько строк
![image](https://user-images.githubusercontent.com/38098758/87980381-350ece00-cadc-11ea-86ce-ec7f6e4ea669.png)

**Comment by AndriyNesterenya** [comment]
Если я правильно понимаю, нужна связь между заявками и актами.
Акт должно быть можно связать с заявкой + из заявки должно быть можно создать акт.
Предполагаю, что может понадобиться вариант связи одной заявки с несколькими актами.

**Comment by AndriyNesterenya** [comment]
Косяки по Заявке:
1. Позволяет провести без выбора контрагента
2. Ссылка на Акт/реализацию после поведения неактивна
![image](https://user-images.githubusercontent.com/38098758/87979581-f88ea280-cada-11ea-9868-8078a42169a6.png)
3. На печатной форме не влазит дата. 
Думаю, там перенос между номером и датой потерялся.
![image](https://user-images.githubusercontent.com/38098758/87979728-2d9af500-cadb-11ea-9fe9-b8e4223181e7.png)

**Comment by AndriyNesterenya** [comment]
В Акте - те же косяки с версткой при добавлении строк(и), что по одной, что списком
![image](https://user-images.githubusercontent.com/38098758/87981518-0b56a680-cade-11ea-89f4-ec9dd09bdc6e.png)

**Comment by AndriyNesterenya** [comment]
Косяк при печати - рвет список на разные листы
![image](https://user-images.githubusercontent.com/38098758/87981650-45c04380-cade-11ea-826a-cf1cb3dd2ed6.png)
и при печати и при экспорте в PDF

Если открываем для всех - не забыть подправить надписи, забитые сейчас жестко на печатные формы - название фонда, реквизиты и т.п.

**Comment by AndriyNesterenya** [comment]
Ошибка при попітке редактировать проведенній документ 
"Dialog 'chatmodify' not found in model inventory/charity
at A2v10.Request.RequestModel.get_CurrentDialog() at A2v10.Request.BaseController.<RenderElementKind>d__40.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at A2v10.Web.Mvc.Controllers.ShellController.<Render>d__22.MoveNext()"

**Comment by htrofymova** [comment]
готово
