### ISSUE TITLE
Расчет налогов ЕН 3 группа - в Реєстр документів по нарахуванню податків не отражаются документы для определения базы налогообложения: юрлицо 3 группа ЕН

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1415]
![image](https://user-images.githubusercontent.com/38099938/87933771-85fbd380-ca96-11ea-9554-36b1532b55a5.png)

![image](https://user-images.githubusercontent.com/38099938/87933803-91e79580-ca96-11ea-84dd-9682da8efe2e.png)

![image](https://user-images.githubusercontent.com/38099938/87933838-a2980b80-ca96-11ea-9d27-76351bb055dc.png)

**Comment by htrofymova** [comment]
исправлено
