### ISSUE TITLE
нужно, чтоб на основании счета (где есть материалы и услуги) можно было сделать не только акт с использованием материалов, но и отдельно Акт + удалив в акте материалы - отдельно и Расходную

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1416]
клиент просит, чтоб на основании счета (где есть услуга и материалы (у него в данном случае - оборудование)) можно было создать отдельно акт (у нас он создается по умолчанию) и расходную накладную
БК не понимает этого
и после удаления оборудования в акте, при создании новой реализации на основании этого же счета БК предлагает снова создать Акт. а нужна расходная

**Comment by htrofymova** [comment]
Исправлено: есть уже такая операция "Реалізація послуг з матеріалами" - вот она и будет создаваться.

**Comment by kattrina-brekhova** [comment]
делаю счет

![image](https://user-images.githubusercontent.com/38099938/100985429-a5326380-3554-11eb-8bba-78f7c2f94b1a.png)

на основании делаю реализацию. удаляю из акта материалы

![image](https://user-images.githubusercontent.com/38099938/100985609-ddd23d00-3554-11eb-91fc-5a8ae3e6ee0f.png)

провожу чисто акт

![image](https://user-images.githubusercontent.com/38099938/100985659-e9256880-3554-11eb-8f0f-8e207db7d8fe.png)

и теперь на основании счета хочу на материалы создать расход. но мне дает снова создать акт, а не расходную, и уже только на материалы акт

![image](https://user-images.githubusercontent.com/38099938/100985833-1c67f780-3555-11eb-886e-f9577cda244e.png)

а нужна расходная

**Comment by htrofymova** [comment]
сделано же, можно закрьіть
