### ISSUE TITLE
Во вступительном балансе по счетам 48 класса просят реализовать аналитику - строку "проекты"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1417]
бухгалтеру нужно распределение сумм вступительного баланса по проектах нужно для отчета Оборотная ведомость по проектах
очень просит сделать в операциях вступительного баланса аналитику строки по проектам - ее интересует счет 484
или в бухгалтерской справке ручной проводки ввести строку аналитику проект, чтоб можно было распределить вступительные остатки по проектах и они не зависали
ей и то и то бы подошло - как нам будет проще...
проблема в том, что вступительный остаток на 484 висит и сложно сориентироваться к какому проекту относится и не может сгруппировать средства по проектах

**Comment by htrofymova** [comment]
В бухгалтерской  справке "Вручну" есть проект. 
![image](https://user-images.githubusercontent.com/43743331/88241257-44377c80-cc92-11ea-96d6-35bfc2c32aca.png)

**Comment by kattrina-brekhova** [comment]
бух справка в текущем виде не совсем решает задачу

![image](https://user-images.githubusercontent.com/38099938/88262504-01e16000-ccd1-11ea-86b6-da6c54bbb61f.png)

она дала только оборот в разрезе проэкта и сальдо не сформировала
![image](https://user-images.githubusercontent.com/38099938/88262564-1cb3d480-ccd1-11ea-85a4-55979445f591.png)

я так понимаю задача в том, чтоб на начало периода иметь сальдо в разрезе конкретных проэктов

**Comment by htrofymova** [comment]
Чтобы операции попали в остатки, надо поставить дату ранее начала ведения учета в буккипере, например, 
30.12.1899

**Comment by kattrina-brekhova** [comment]
ничего не меняется
![image](https://user-images.githubusercontent.com/38099938/89498137-5521db00-d7c6-11ea-94e2-ea7c49fe894f.png)

![image](https://user-images.githubusercontent.com/38099938/89498303-ac27b000-d7c6-11ea-8000-00e30b225347.png)

![image](https://user-images.githubusercontent.com/38099938/89498361-c82b5180-d7c6-11ea-99a1-e58efe691fbb.png)

при этом операция в списке документов после проведения куда-то теряется

![image](https://user-images.githubusercontent.com/38099938/89498434-ec872e00-d7c6-11ea-9c3b-6d2d0c94c8be.png)


может я туплю?

**Comment by htrofymova** [comment]
добавила [Проект] в карточку нач.баланса - раздел "Інше"
