### ISSUE TITLE
Печатная форма счетов, накладных, актов. Отображать цену Без ПДВ, или з ПДВ, в зависимости от ситуации

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1418]
Просят, чтоб отображалось то, что в таблице, при наборе документа
![image](https://user-images.githubusercontent.com/42540074/89387615-6b1e9580-d70b-11ea-9ece-d1401e0591de.png)
А не так: 
![image](https://user-images.githubusercontent.com/42540074/89387751-9b663400-d70b-11ea-8b2a-8fa37b9b49f9.png)

Срочная просьба от Индзахиста!

**Comment by htrofymova** [comment]
Сделано, 
Следующим образом:
1. Если стоит "птица" [ПДВ в т.ч.], то в печатной форме будут заголовки "Ціна з ПДВ", "Сума з ПДВ", содержимое колонок - тоже с ПДВ.
2. Если "птица" [ПДВ в т.ч.] не стоит, то заголовки остаются стандартными "Ціна", "Сума", содержимое колонок также стандартно - без ПДВ.
3. В итогах: самая первая строка теперь называется "Разом без ПДВ".
