### ISSUE TITLE
Операция "Возврата тела депозита"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1419]
Банк приход, нет специальной операции для возврата тела депозита. 
Приходится использовать перемещение между собственными счетами. 
С недавних пор эта операция попадает в базу налогообложения для единоналожников, т.е. расчёт сумм налога поплыл.

**Comment by htrofymova** [comment]
Добавлены две операции:
1. Перерахування грошових коштів на депозитний рахунок: дт 351 - кт 311
2. Повернення основної суми депозита: дт 311 - кт 351
