### ISSUE TITLE
Об’єкти обліку: при изменении Властивостей об’єкта обліку, кнопка "Вид" не активная, и не дается редактированию

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#142]
![32419261_1980897825494392_9211841686047555584_n](https://user-images.githubusercontent.com/38099938/39969531-a6e25d34-56e5-11e8-9e6b-993b4e78863c.png)

**Comment by AlexeyTishkin** [comment]
Вид объекта можно определить только при создании. У существующего объекта изменить его нельзя.

**Comment by kattrina-brekhova** [comment]
ой, а как же тогда быть? например, все ввела правильно, а только группа указана неправильно....
через копирование и изменение этого параметра?

**Comment by nik-man** [comment]
А зачем запрещать изменение вида объекта учета?

**Comment by kattrina-brekhova** [comment]
Может, я не совсем понимаю, под группой я подразумеваю Вид
Скопировать, изменить, получилось
Но например объект учета хочу перенести из "Сировина..." в "Запасные части".. получается, что только копированием? 
![32350057_1980911972159644_5653134168012357632_n](https://user-images.githubusercontent.com/38099938/39969922-c4f0e75e-56eb-11e8-8db2-c3651d50f333.png)

**Comment by AlexeyTishkin** [comment]
От этого зависит принцип проведения.

**Comment by AlexeyTishkin** [comment]
> Может, я не совсем понимаю, под группой я подразумеваю Вид

Есть отдельное свойство "Группа".

> Но например объект учета хочу перенести из "Сировина..." в "Запасные части".. 

Перенести из одного вида в другой - нельзя. Под видом подразумевается балансовый счет. Его можно установить только при создании.

**Comment by kattrina-brekhova** [comment]
Правильно ли я понимаю, что под Группой подразумевается классификация объектов учета по каким-то общим свойствам?
Ною, потому что не совсем понимаю, что в хэлпе писать :)

**Comment by AlexeyTishkin** [comment]
> Правильно ли я понимаю, что под Группой подразумевается классификация объектов учета по каким-то общим свойствам?

Все таки группа или вид ?
Вид = балансовый счет, т.е. Товары = 281, Топливо = 203 и т.д.
Группа - свойство для группировки.

**Comment by kattrina-brekhova** [comment]
Интуитивно понятно, о чем идет речь - счета, на которых учитываются объекты. сам термин Вид путает

**Comment by AlexeyTishkin** [comment]
> сам термин Вид путает

Можем переименовать. Как ?

**Comment by kattrina-brekhova** [comment]
Бухгалтерський рахунок
Балансовий рахунок
так понятнее

**Comment by AlexeyTishkin** [comment]
Коля, вынеси на обсуждение, пжл.
