### ISSUE TITLE
Просят добавить в бух.справку действующую аналитику Проекты по всем счетам

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1420]
![image](https://user-images.githubusercontent.com/42540074/89400143-22bba380-d71c-11ea-99e1-fee8faff59b7.png)
Можно начать с 48, 154, 23, 9 кл.

**Comment by htrofymova** [comment]
Есть же проект! Один на всю бух.справку, никаких ограничений по заполнению проекта - НЕТ!
