### ISSUE TITLE
Сделать автоподстановку значения БЕЗ ПДВ в НН, в указанную графу в операциях на освобожденные от налогообложения

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1422]
У ПН, яка оформлена на звільнені від ПДВ операції, у лівому верхньому куті в графі «Складена на операції, звільнені від оподаткування» ставиться позначка «Без ПДВ» (п. 201.3 ПК).

НН на освобожденные операции
Составляется на операции, которые освобождены от обложения согласно ст. 197 НКУ и подразд. 2 разд. XX НКУ. Заполнение НН имеет такие особенности:

1. В шапке — в поле «Складена на операції, звільнені від оподаткування» — ставим «Без ПДВ».

**Comment by htrofymova** [comment]
Уже есть и, видимо, давно. Нужно сменить ставку вот здесь:
![image](https://user-images.githubusercontent.com/43743331/89922201-6411ee80-dc07-11ea-93f5-7426fe2503df.png)
