### ISSUE TITLE
Исправить 0 на пустое значение в графе 11 НН при выписке НН без ндс

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1424]
Звонила клиентка, говорит от нас пришла Налоговая накладная, и типа показывает у нее в программе, что она с ошибкой. В графе 11 стоит 0,00, а должно быть вообще пусто.

Буккипер поставил в 11 строке налоговой "0", Соната этот "0" проверила как без ошибок. Налоговая эту нн зарегила, как правильно оформленную. Не знаю. Есть ли смысл делать корректировку. думаю нет так как все так без ндс операция))) а есть такое положение, что зарегистрированная налоговой службой нн является правильной))). но исправить для последующих налоговых надо в обязательном порядке.

**Comment by Anestezia** [comment]
[нн 903 код.pdf](https://github.com/a2develop/bugTracker/files/5055935/903.pdf)
код пільги складається з 8 цифр

а ноль треба прибрати

глянуть в консультации последний пункт

**Comment by Anestezia** [comment]
Здесь внутри проведенной НН графа 11 в Буккипере ничего, 
![image](https://user-images.githubusercontent.com/42540074/89928303-4d23ca00-dc10-11ea-93c6-2bffe53c7f9f.png)
Когда в сонату переносится, то появляется ноль в ней
![image](https://user-images.githubusercontent.com/42540074/89928404-73e20080-dc10-11ea-83f1-0ff489ebe9d8.png)
и в самом хмл файле ноль есть
![image](https://user-images.githubusercontent.com/42540074/89928269-3c735400-dc10-11ea-8e5e-d44b0ad01fd4.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
В сонате все ок, в хмл тоже.
