### ISSUE TITLE
Изменить реквизиты в формируемом счете в личном кабинете

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1425]
Изменился счет и МФО Приватбанка в реквизитах Буккипера
Нужно внести изменения в бланк формируемого в личном кабинете счета. 

Вместо 
Р/р UA553007110000026008052662772 в ПЕЧЕРСЬКА ФIЛIЯ АТ КБ "ПРИВАТБАНК" в м. Київ

написать
Р/р UA143052990000026009046211222 в АТ КБ "ПРИВАТБАНК"

**Comment by htrofymova** [comment]
готово
