### ISSUE TITLE
Додати можливість створити компенсуючу податкову накладну, де продавець і отримувач -- Власна фірма

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1427]

**Comment by htrofymova** [comment]
Добавлена опепрация "Податкове зобов'язання (компенсуюче)". Искать с разделе ПРИДБАННЯ

**Comment by Anestezia** [comment]
Все есть. 
Тут дополнительный момент: единицы измерения, которые подставляются автоматом при выборе объекта и не редактируются в НН
 Соната выдает такое. В ней можно поменять, а если сразу сдавать без редактирования во внешней проге, то так и будет, и может не приняться
![image](https://user-images.githubusercontent.com/42540074/94136848-38249280-fe6e-11ea-9b5d-6a99d77d680b.png)

![image](https://user-images.githubusercontent.com/42540074/94136878-42df2780-fe6e-11ea-8da6-4ecbf628619d.png)

**Comment by Anestezia** [comment]
![image](https://user-images.githubusercontent.com/42540074/94138524-f0533a80-fe70-11ea-973b-48c451557783.png)
![image](https://user-images.githubusercontent.com/42540074/94138549-f812df00-fe70-11ea-9ca2-6272f38ec09d.png)
![image](https://user-images.githubusercontent.com/42540074/94138573-ffd28380-fe70-11ea-85f6-03dc574e2200.png)
![image](https://user-images.githubusercontent.com/42540074/94138603-0bbe4580-fe71-11ea-956a-7491634bd18b.png)
![image](https://user-images.githubusercontent.com/42540074/94138679-25f82380-fe71-11ea-9c98-86a648e5b659.png)
![image](https://user-images.githubusercontent.com/42540074/94138766-432cf200-fe71-11ea-9e95-f1884a86f717.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Странным образом из этого

![image](https://user-images.githubusercontent.com/42540074/95431762-61f1b500-0956-11eb-9081-c903611a0561.png)
в Сонате при передаче появилось вот такое
![image](https://user-images.githubusercontent.com/42540074/95431804-72099480-0956-11eb-8d39-b5e0343b7b9f.png)
Добавились данные в столбцах.
И дальше непонятно что творится при проверке сонатовской
![image](https://user-images.githubusercontent.com/42540074/95431929-a2513300-0956-11eb-8a4d-de61d6a77dd6.png)
здесь, наверное, лишняя точка у грн 
![image](https://user-images.githubusercontent.com/42540074/95432275-20153e80-0957-11eb-9acd-d27be8300b0a.png)
![image](https://user-images.githubusercontent.com/42540074/95433614-da597580-0958-11eb-8a5a-a2a6a1c5a823.png)
здесь пустая графа передалась нулем, и далее тоже
![image](https://user-images.githubusercontent.com/42540074/95433676-f1986300-0958-11eb-9102-2fe681274a6f.png)
![image](https://user-images.githubusercontent.com/42540074/95433711-fd842500-0958-11eb-8d30-9a119c18616e.png)
Когда стоит код ставки. то и графа 11 не проходит проверку на пустоту
![Uploading image.png…]()

**Comment by Anestezia** [comment]
Осталось только в хмл файле в графе Код ставки при переносе убрать 0, чтоб было просто пустое значение.

**Comment by htrofymova** [comment]
готово
