### ISSUE TITLE
Не выведены подписанты в кассовом ордере на выплату зп, в печатной форме они есть

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1433]
![photo_2020-10-15_14-46-03](https://user-images.githubusercontent.com/42540074/96121940-6fc8ac80-0ef9-11eb-9119-84d3c0872af2.jpg)

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Есть, работает. Немного не влезает при экспорте документа длинное название нашей фирмы в шапке, нужен перенос побольше

**Comment by Anestezia** [comment]
Есть, влезает
