### ISSUE TITLE
У Виготовленні додати можливість обирати зі списку  запасів - Матеріали с\г призначення

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1434]
![image](https://user-images.githubusercontent.com/42540074/96127462-1498b900-0efd-11eb-8653-cd5e11eb85b6.png)

**Comment by htrofymova** [comment]
Готово. Проверить "Створення рецептури" также.

**Comment by Anestezia** [comment]
Есть, работает
