### ISSUE TITLE
Запаси. Звіти. ОСВ по складу. Изменить склад. Сохранить. Ошибка.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#144]
![2018-05-13](https://user-images.githubusercontent.com/35918141/39970426-da6087ea-56f3-11e8-894e-81acea6d1373.png)
Отдел "Запаси". Раздел "Звіти". Отчет "Оборотна відомість по скаду"
Открыть, изменить склад "Всі склади" на "Основний склад"
Закрыть. Предложить сохранить. Согласиться. Ошибка.

**Comment by alex-kukhtin** [comment]
Fixed in 7189
