### ISSUE TITLE
при расчете амортизации программа не учитывает данные, внесенные в карточку вступительного баланса, и превышает сумму месячной амортизации за последний месяц эксплуатации

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1442]
обратилась клиентка
у нее такая история с ОС
внесла 01/01 вступительным балансом ОС
![image](https://user-images.githubusercontent.com/38099938/97146509-a364cb80-1770-11eb-9933-85960402df66.png)
уже была начислена какая-то амортизации (похоже не прямолинейным методом)
ПВ 3080
АМ 1399,13
Срок использования 10 мес
ЛВ 100

Расчитываю амортизацию:
01/20, 02/20, 03/20, 04/20, 05/20 по 298 гривен (3080 - 100)/10 = 298 грн

на июнь сумма стоимости ОС остается 90,87
3080 - 100 = 2980
2980 - 1399,13 - 5*298 = 90,87

но в июне программа считает амортизацию по фиксированной сумме 298 грн
![image](https://user-images.githubusercontent.com/38099938/97147149-b6c46680-1771-11eb-9ecd-e2320459eff7.png)

![image](https://user-images.githubusercontent.com/38099938/97147175-c04dce80-1771-11eb-84dd-fd5c0fadcde5.png)

![image](https://user-images.githubusercontent.com/38099938/97147198-cb086380-1771-11eb-94e2-4a256cb305fb.png)

**Comment by htrofymova** [comment]
готово

**Comment by kattrina-brekhova** [comment]
нашла интересный момент
делаю перемещение этого фонда в состав, удерживаемых для продажи, и сумма ампортизации идет полностью на сумму первичной стоимости
это правильно?
если мы указывали в карточке объекта ликвидационную стоимость 100 грн
значит, сумма амортизации должна быть 2 980
![image](https://user-images.githubusercontent.com/38099938/97582648-aaa10900-19fe-11eb-9ff8-89f9d27cf2a1.png)

![image](https://user-images.githubusercontent.com/38099938/97582700-b7bdf800-19fe-11eb-8f5a-db9586964ff0.png)

![image](https://user-images.githubusercontent.com/38099938/97582894-f5228580-19fe-11eb-99b7-72cb25e2bec8.png)

получается программа не засчитала, что мы указали в карточке вступительного баланса ликвидационную стоимость 100 гривен, так как она посчитала амортизацию на всю сумму

**Comment by htrofymova** [comment]
ликвидационная стоимость тут ни при чем
