### ISSUE TITLE
Проводки "Визнання доходу" для ОСББ, вопросы

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1443]
Login: lyudshv@gmail.com
ЯК відкоригувати проводки? Це неприбуткова організація. Всі витрати збираються на 94 рах. Рахунки 92, 93, 91 рах., 23 рах. - не використовуються. При проведенні розрахунково-касового обслуговування створюється провадка Дт 92 Кт 311. Нам потрібно ДТ 949 кТ 311. Дт 791 Кт 949. І одночасно визнається дохід в сумі понесених витрат Дт 484 Кт 719 Дт 719 Кт 791 Як ці проводки відкоригувати або їх правильно налаштувати, щоб вони в майбутньому формувалися правильно?
![image](https://user-images.githubusercontent.com/42540074/97849735-a70dca80-1cfb-11eb-9e8a-489396058203.png)
Проводки складаються такого плану
А мені потрібно Дт 949 Кт 311
Кт 791 Дт 949
Дт 484 Кт 719
Дт 719 Кт 791
У неприбутковій організації дохід визнається в сумі понесених витрат. Це ОСББ. ВСІ витрати збираються на одному рахунку Це рах. 949

есть, кстати, операция в бух.справке для визнання доходу

**Comment by htrofymova** [comment]
готово.
Добавлены две опрации для ОСББ: по банку и по бух.справке

**Comment by Anestezia** [comment]
Работает
