### ISSUE TITLE
новая форма декларации по прибыли - за 1 квартал 2021. но есть вероятность, что налоговики настоят на новой форме отчета за 4 квартал 2020

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1446]

**Comment by kattrina-brekhova** [comment]
наказ Минфин від 29.10.2020 р. №649. здесь же новые показатели отчета и его изменения

https://news.dtkt.ua/state/laws-and-regulations/66442

вот статья про изменения, которые вводят в отчет
https://news.dtkt.ua/accounting/reposts/66441

**Comment by kattrina-brekhova** [comment]
https://blank.dtkt.ua/blank/239

http://sfs.gov.ua/elektronni-formi-dokumentiv/podatok-na-pributok-pidpriemstv/podatkova-deklaratsiya-z-podatku-na-pri/

**Comment by kattrina-brekhova** [comment]
https://tax.gov.ua/data/material/000/006/58768/Forms_deklar.htm

**Comment by Anestezia** [comment]
J0100119
--
1) В таблице 9 основной декларации: 

При проведении исчезает отметка "Іноземної компанії" и "інституту спільного інвестування у вигляді утворення без статусу юридичної особи2"
![Screenshot_10](https://user-images.githubusercontent.com/42540074/115025644-4a2d5780-9eca-11eb-8508-d880c49ce345.png)

2) Указывают на наличие Додатка КІК, у нас в отметках его нет
![image](https://user-images.githubusercontent.com/42540074/115025733-6204db80-9eca-11eb-8fd3-a5693ca25e73.png)
![image](https://user-images.githubusercontent.com/42540074/115025797-70eb8e00-9eca-11eb-97df-180d880c9922.png)

**Comment by htrofymova** [comment]
готово
