### ISSUE TITLE
в расчете налогов бухсправкой неправильно считается сумма дохода у фоп-комиссионера на ЕН: нужно включать только комиссионное вознаграждение, а программа тянет все деньги, полученные за проданный комиссионный товар

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1448]
у меня фоп 3 группы:
получила товары
![image](https://user-images.githubusercontent.com/38099938/101355354-1d738e80-389f-11eb-86bc-30984d73849e.png)

продала товары 2-мя расходными
![image](https://user-images.githubusercontent.com/38099938/101355378-26fcf680-389f-11eb-91d7-cccf68f7a516.png)

получила оплаты на сумму 64 000

составила акт комиссионера
![image](https://user-images.githubusercontent.com/38099938/101355451-4136d480-389f-11eb-81b3-448b4b097638.png)

![image](https://user-images.githubusercontent.com/38099938/101355464-4562f200-389f-11eb-96ae-0e039b153469.png)

при расчете налогов
![image](https://user-images.githubusercontent.com/38099938/101355493-4dbb2d00-389f-11eb-959c-3e523585d181.png)

а нужно в базу только 6 400 включить

**Comment by kattrina-brekhova** [comment]
логика программы понятна
видимо проблема в том, что оплата зашла как от обычных операций
![image](https://user-images.githubusercontent.com/38099938/101355596-76dbbd80-389f-11eb-9ba9-bcac19cda0e7.png)

и никаких дополнительных признаков не указать
но так неправильно

**Comment by htrofymova** [comment]
готово

**Comment by kattrina-brekhova** [comment]
я указала, что вознаграждение комиссионера НЕ ВЫЧИТЫВАЕТСЯ ИЗ СУММЫ ПРОДАЖИ, а перечисляется комитентом отдельно
вот что у меня вышло
![image](https://user-images.githubusercontent.com/38099938/102979315-9402c400-450e-11eb-81e5-36347f9468fe.png)

![image](https://user-images.githubusercontent.com/38099938/102979403-af6dcf00-450e-11eb-854c-88eb6cc219f3.png)

смотрите только расчет за 23 число
![image](https://user-images.githubusercontent.com/38099938/102979449-c14f7200-450e-11eb-971c-08933228b1a5.png)

**Comment by kattrina-brekhova** [comment]
если ставить галочку "сума вознаграждения удерживается" расчет такой же
![image](https://user-images.githubusercontent.com/38099938/102979695-19867400-450f-11eb-8b3a-b49decd48555.png)

![image](https://user-images.githubusercontent.com/38099938/102979720-23a87280-450f-11eb-89a9-fe16deb4cd29.png)

**Comment by kattrina-brekhova** [comment]
в общем, логика ясна
но в случае, если вознаграждение не удерживается, а перечисляется комитентом, то получается задваивание

**Comment by htrofymova** [comment]
надо подумать

**Comment by htrofymova** [comment]
придумалось, проверяйте

**Comment by kattrina-brekhova** [comment]
прекрасно!
