### ISSUE TITLE
ОСВ по складу. При сбросе склада поле совсем очищается.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#145]
![2018-05-14 reps no stores](https://user-images.githubusercontent.com/35918141/40004627-bf4e9ad6-579e-11e8-97bd-72c274c17584.png)

Команда называется "Очистити" и она действительно очищает.
После обновления появляется подпись "Всі склади"
Может правильнее сразу писать "Всі склади" ?

**Comment by AlexeyTishkin** [comment]
Наверное, правильнее будет не выводить "Все склады". Т.е. склад выбран - остатки по нему, не выбран - остатки по всем. Такая логика в диалоге выбора объектов в Счете и Расходной накладной.

**Comment by AlexeyTishkin** [comment]
Теперь "Все склады" не выводится.
