### ISSUE TITLE
Схема с получением целевых средств на покупку НА, оплатой и приходом

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1450]
Витрати неприбуткових організацій формуються відповідно до П(С)БО-16.
Враховуючи особливості діяльності, неприбуткові організації можуть вести
аналітичний облік витрат за напрямками, проектами.
В багатьох документах вашої програми аналітичний облік по проектам
відсутній,наприклад в бухгалтерській довідці,Акті введення основниз засобів
в експлуатацію і т.д.
Також в програмі немає всіх необхідних проводок для відображення в
бухгалтерському обліку використання цільового фінансування для придбання
основних засобів для власних потреб.
Прикдад типових для всіх неприбуткових організацій господарських операцій
для придбання основних засобів для власних потреб:

№ Зміст операції
Дт Кт
1 Надходження коштів на придбання основних засобів 311
48

2. Перераховані кошти на основні засоби 685
311

3. Оприбутковані основні засоби 151,152
685

4. Введено в експлуатацію основний засіб 10
151,152

5. Віднесення суми цільового фінансування
на доходи майбутніх періодів одночасно з
введенням в експлуатацію основного засобу 48
69

6. Нарахування амортизації методом, визначеним у обліковій
політиці
831 131

7. Визначення доходу від цільового фінансування
одночасно з нарахуванням амортизації 69
745,746

**Comment by htrofymova** [comment]
Сделала новую операцию для приходной накладной: "Придбання необоротних активів за рахунок коштів цільового фінансування": дт 152 или 153 - кт 48. Остальное уже реализовано. 
151 счет - отдельная история: получают целевое финансирование, платят, приходуют от поставщика, перемещают на 151, услуги относят на 151 в акте, признают доход.
831 счета не будет, так как 8 класс у нас не ведется.
