### ISSUE TITLE
Ошибка при создании начального баланса из импорта объектов

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1451]
Не можливо добавить "початковий баланс" на "Запаси" при імпорту товарі з файлу. Вручну можливо. Самі товари імпортуються без помилок.
Я внесла изменения в номер документа — активировалась кнопка Зберегти, а провести таки нет. Я закрыла, полезла в Початковий баланс по Запасам — документа этого там нет, даже как черновика, я открыла один из добавленных объектов учета, операции конкретно по нему — Прайс-черновик есть, Поч.баланс — нет.
![image](https://user-images.githubusercontent.com/42540074/102208948-c3934a00-3ed8-11eb-900b-b04373519b08.png)
![image](https://user-images.githubusercontent.com/42540074/102208967-cbeb8500-3ed8-11eb-8953-3f9fb41bba92.png)
![image](https://user-images.githubusercontent.com/42540074/102209031-e0c81880-3ed8-11eb-919f-b52269e4fbef.png)

**Comment by htrofymova** [comment]
исправлено
