### ISSUE TITLE
Несоответствие количества дней отпуска в приказе и в Расчетной ведомости, если были праздники

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1457]
![image](https://user-images.githubusercontent.com/42540074/103777954-4ae85f00-503a-11eb-8002-7cddc5bc74a5.png)
![image](https://user-images.githubusercontent.com/42540074/103778024-59cf1180-503a-11eb-94ab-6217af2b2433.png)
Возможно, следует установить не календарное наследование по датам, а из ячейки количество дней отпуска.

**Comment by htrofymova** [comment]
нема чого виправляти
![image](https://user-images.githubusercontent.com/43743331/177506523-2b8071b0-ce2c-4136-83c8-3a69ee63d7f8.png)

**Comment by Anestezia** [comment]
Обчислюємо суму відпускних: множимо середньоденну на тривалість відпустки. У тривалості відпустки не враховуємо святкові і неробочі дні. 

Тобто, якщо у періоді відпустки календарних днів 11, то ми в нашому наказі виправляємо їх на 10, як у прикладі. і ця кількість повинна з наказу - виправлена, бути і в розрахунку ЗП на вкладці Відпустка, а там наразі відображається кількість календарних днів.  Це і малось на увазі в кейсі.

**Comment by htrofymova** [comment]
я перевірила - в наказі така сама кількість днів, що і в розрахунку, до того ж привела картинку.

**Comment by Anestezia** [comment]
Вона така сама, але це не вірно, якщо були святкові дні. Святковий день не оплачується, тобто якщо в прикладі календарних днів ставиться 11, то ми в наказі вручну виправляємо на 10 днів і оплачуємо 10 днів. І далі ці 10 днів повинні йти і в розрахунок ЗП. 

Задачу знімаю, адже можна в розрахунку ЗП відредагувати також.
