### ISSUE TITLE
Диалог курса валюты. Объединить с диалогом свойств валюты.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#146]
Сейчас найти, где устанавливается курс валюты -- сложновато.
Но, даже если решить этот вопрос, один диалог проще двух.

**Comment by AlexeyTishkin** [comment]
Свойства валюты устанавливаются один раз. Курс - каждый день. Зачем для установки значения курса заходить в свойства валюты ?

**Comment by AlexeyTishkin** [comment]
Кнопка "Свойства" и "Курсы" всегда рядом.
