### ISSUE TITLE
Собственное предприятие в контрагентах или переброс средств самому себе через 48 счет

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1462]
Кейс

Доброго дня..
На кожний діючий проект відкривається новий рахунок в банку (така умова гранта надавачів)
Коли надходять кошти по проекту робимо проводку  ДТ311  КТ484.
Коли в проекті задіяні тільки ФОПи все гаразд.Але коли є трудові  угоди і згідно  яких необхідно
виплачувати заробітну плату два рази на місяць(не зважаючи чи є кошти на рахунку проекту,а він діє.
Гранта надавач затримує перерахування) необхідно робити по банку  переміщення коштів з рахунку іншого проекту.
На рахунок проекту,де не хватає коштів ,  ДТ311 КТ484( отримання цільового фінансування з іншого власного рахунку)
,з рахунку проекту,який надає кошти  ДТ 484 КТ311 (перерахування цільового фінансування з іншого власного рахунку.
І отримувач і платник той самий.
Якщо робити звичайне переміщення між своїми рахунками:
ДТ311  КТ 333   надходження з іншого власного рахунку
ДТ 333 КТ311 видаток на інший власний рахунок,то
 Кошти на рахунок перераховуються,виплату робимо,а по
рахунку 484(робимо оборотку по проектах) виплачено більше,чим є в наявності коштів

**Comment by htrofymova** [comment]
Добавлены две операции:
Надходження коштів цільового фінансування з іншого власного рахунку
Видаток коштів цільового фінансування на інший власний рахунок
Операции выбираются в выписке. На закладке "Додатково" выбирается "Вид надходжень" (вместе с ним выбирается 483, 482 или 484 счет). Там же выбирается Проект.
