### ISSUE TITLE
свойство сотрудника "Підписує накладні" перенести в свойство "Посади", и название "Підписує Видаткові накладні"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1463]
![image](https://user-images.githubusercontent.com/38099938/104740329-82e55580-5750-11eb-9af7-3ddb8a4b295f.png)

**Comment by htrofymova** [comment]
Все-таки, я думаю, что не нужно переносить. Получится, что эта подпись будет привязана к должности и все сотрудники с таой должностью будут подписантами, а смысл вроде бы ж в том, что бы подписант такой был один.

**Comment by kattrina-brekhova** [comment]
Галина, а вы таки правы
значит, все правильно изначально сделали
