### ISSUE TITLE
Поч.баланс-банк-формувати проводку по властивості розрахункового рахунку

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1466]
Некоторые счета идут на 351, 184 и т.д. счета, а проводка при внесении нач.остатков формируется по 311. Потом в оборотке из банковской выписке этих начальных остатков не видно.
![image](https://user-images.githubusercontent.com/42540074/105181329-5789ae80-5b34-11eb-8e0b-7783e36f19e6.png)
![image](https://user-images.githubusercontent.com/42540074/105181426-71c38c80-5b34-11eb-8872-a436a9834366.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Пока по счетам все по-старому. И в Начальном балансе на 311 вместо 184 идет. и в оборотке из банковской выписки тоже начального остатка не видит по 184.

**Comment by htrofymova** [comment]
исправила
