### ISSUE TITLE
У контрагента ФОПа автоматом пишет, что он "Є платником податку на прибуток на загальних підставах"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1468]
Контрагент - ФОП 3 група, плательщик НДС, в печатной форме акта пишет "платник податку на прибуток...."
Как исправить?
В карточке контрагента мы можем только поставить Платит он НДС или нет, группу не поставить. А в акте действительно пишет у фопа, что Платник на загальних

Ключевое, что это КОНТРАГЕНТ, там нет системы налогообложения, а он может быть и на едином.

**Comment by htrofymova** [comment]
В диалог свойст контрагента добавлена возможность заполнить систему налогообложения.

**Comment by Anestezia** [comment]
Важно это перенести в печатную форму актов, которые по всей реализации
