### ISSUE TITLE
расчет зарплаты: автоматически не отражается кол-во рабочих дней в периоде

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1469]
![image](https://user-images.githubusercontent.com/38099938/106122578-8cfc5080-6161-11eb-9ce2-4d3c0ef03d53.png)

**Comment by Anestezia** [comment]
Это влияет на отпускные, при расчете за январь ставит 0 дней, хотя вручную в расчете ЗП эти дни по графику и фактически проставлены были. В результате неправильно рассчитывается среднедневная

**Comment by htrofymova** [comment]
заполнила графики рабочего времени на 2021
