### ISSUE TITLE
"Відомість по взаєморозрахунках з постачальниками" имеет неверный заголовок.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#147]
Придбання. Звіти. Відомомість по взаєморозрахунках за постачальниками.
![2018-05-15](https://user-images.githubusercontent.com/35918141/40052571-f00cb66e-5846-11e8-88bd-f473d3f7f305.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
