### ISSUE TITLE
автоматическое заполнение баланса (форма 1-мс): с строку 1420 не  попадает сумма убытка, указанная в прошлом периоде

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1472]
из-за этого и неправильно расчитывается прибыль (убыток) текущего года
баланс пассив 19
![image](https://user-images.githubusercontent.com/38099938/107121402-e0297e00-689a-11eb-9f05-4fc53ee4b1ba.png)
баланс пассив 20
![image](https://user-images.githubusercontent.com/38099938/107121430-064f1e00-689b-11eb-9b8d-0ed9a79ebe06.png)
оборотка 19
![image](https://user-images.githubusercontent.com/38099938/107121439-1cf57500-689b-11eb-9dff-750306dff4fb.png)

**Comment by htrofymova** [comment]
исправлено
