### ISSUE TITLE
новый объединенный отчет с ЕСВ и ЕН для ФОП 1-3 груп

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1475]
3 группа будут оставлять впервые отчет по новой форме за 1 квартал в апреле-мае
https://buhgalter911.com/uk/news/news-1055472.html

**Comment by kattrina-brekhova** [comment]
https://tax.gov.ua/data/material/000/006/58768/Forms_deklar.htm

но у них какая-то лажа с формами, они не соответствуют порядку заполнения
пока ни новых форм ни розъяснений от минфина

https://bookkeeper.kiev.ua/novi-formi-ob-yednanoyi-zvitnosti-ne-vidpovidayut-vimogam-poryadku-zapovnennya/

**Comment by AndriyNesterenya** [comment]
Похоже, в налог шарашит всю сумму дохода.

У ФОП 3 группы на Деве:
![image](https://user-images.githubusercontent.com/38098758/114031412-0613d480-9884-11eb-9972-f6ffbda0a6ff.png)

**Comment by htrofymova** [comment]
исправила
