### ISSUE TITLE
"Безоплатне одерження Немат.активів" - убрать статус "Потребує оплати" 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1476]

**Comment by htrofymova** [comment]
сейчас стоит статус "не потребує оплати". Убрать совсем? т.е. не писать ничего в статусе оплаты?

**Comment by Anestezia** [comment]
Да, лучше убрать, чтоб в черновиках и бета операциях не висело. Пусть будет полностью закрыто.
