### ISSUE TITLE
Бухгалтерія. Звіти. ОСВ по кассе. Нет проверки дат.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#148]
![2018-05-15 osv_ _ _](https://user-images.githubusercontent.com/35918141/40055671-645978ea-5851-11e8-9b4e-3ed082e46757.png)
Нет проверки, чтобы вторая дата была меньше первой.
Или может вообще надо вставить новый селектор периода.

**Comment by shevchuk-vadim** [comment]
Добавил выбор периода вместо двух отдельных дат.
