### ISSUE TITLE
Початковий баланс по банку -- попадает на 312 счет, хотя валюта счета - гривня

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1481]
![image](https://user-images.githubusercontent.com/42540074/107938773-83ab1a80-6f8e-11eb-9072-5d98fd03048c.png)
![image](https://user-images.githubusercontent.com/42540074/107938790-89a0fb80-6f8e-11eb-819b-90b25b88f014.png)
![image](https://user-images.githubusercontent.com/42540074/107938810-9160a000-6f8e-11eb-8189-9889bd25b3c5.png)

**Comment by htrofymova** [comment]
исправлено
