### ISSUE TITLE
При экспорте данных контрагентов не экспортируется поле Юр. адрес, Факт. адрес

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1482]
При экспорте данных контрагентов не экспортируется поле Юр. адрес, Факт. адрес
Можно решить? Нужно для переноса в другую учетку
![image](https://user-images.githubusercontent.com/42540074/108058885-54171380-705d-11eb-8e49-b83100017d95.png)

**Comment by htrofymova** [comment]
добавила
