### ISSUE TITLE
При формуванні розрахункових листків місяці перемішані.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1483]
![image (19)](https://user-images.githubusercontent.com/42540074/108061255-b6bdde80-7060-11eb-985b-ed37890da3c9.png)

**Comment by htrofymova** [comment]
Добавила сортировку по периоду з/п. Хотя, этот отчет имеет смысл строить за один расчетный период (месяц), а за несколько периодов - как-то странно и не понятно, зачем.
