### ISSUE TITLE
вступительный баланс по заборгованості підзвітної особи - в отчете подотчетного лица неправильное отражение суммы - отражается как "перевитрата", хотя по сути это выдача

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1489]
вступительный баланс
![image](https://user-images.githubusercontent.com/38099938/110786581-fb5e2380-8274-11eb-890b-ba4c1b3ca1c9.png)

проводка правильная 
![image](https://user-images.githubusercontent.com/38099938/110786644-0ca73000-8275-11eb-8eb3-8067522ac630.png)

а в отчете подотчетного лица видит как долг ПЕРЕД сотрудником
![image](https://user-images.githubusercontent.com/38099938/110786815-411aec00-8275-11eb-8e41-d54a6b2e9699.png)

оборот по 372 и сальдо считает правильно 
![image](https://user-images.githubusercontent.com/38099938/110786998-817a6a00-8275-11eb-911b-d55844d51a47.png)

проблема только в электронной и печатной версии документа

![image](https://user-images.githubusercontent.com/38099938/110787133-aa9afa80-8275-11eb-9f35-8a6b03f0e5db.png)

эксперитментировала со вступительным балансом, когда долг перед сотрудником - там все правильно

**Comment by htrofymova** [comment]
исправлено
