### ISSUE TITLE
Справочник валют единый для всех фирм в тенанте, если валюта не использовалась, ее не дает удалить, потому что в другой фирме она есть.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1491]
![image](https://user-images.githubusercontent.com/42540074/112617117-38a5e200-8e2d-11eb-9732-2c185177c4d5.png)
Из счетов на фирме у меня только гривневый
Пытаюсь удалить валюту из справочника (USD), система сообщает:
![image](https://user-images.githubusercontent.com/42540074/112617206-55dab080-8e2d-11eb-9504-3d7986768e84.png)
Операций по этой валюте нет
![image](https://user-images.githubusercontent.com/42540074/112617266-6854ea00-8e2d-11eb-9605-245211e5c84f.png)
 Информация с другой фирмы внутри тенанта, даже курс проставлен с другой фирмы.

**Comment by htrofymova** [comment]
Где информация-то? Пустой отчет. Ну, и пусть будет валюта, мешает что ли? Нет валюты, ну, и не стройте валютные отчеты. А курсы - они вообще у всех одинаковые, по определению или даже "по жизни".
