### ISSUE TITLE
Валюта по умолчанию в валютных отчетах всегда ставится USD, даже если она удалена из справочника и операций по ней не было.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1492]
Отчеты Оборотно-сальдова відомість по рахунках в банках  в валюті" та "Відомість по розрахунках з покупцями в валюті", "Відомість за розрахунками з постачальниками в валюті"  

1. Завела новую фирму на новом акке. 
2. В справочнике валют по умолчанию Доллар и Евро.
3. Зашла в отчет Відомість за розрахунками з покупцями в валюті - там по умолчанию доллар стоит. 
4. Тут же в этой ведомости зашла в выбор валюты и удалила доллар, только евро оставила.
5. Зашла в Справочники валют, там Гривня и Евро. 
6. Снова открываю отчет Відомість за розрахунками з покупцями в валюті - Там снова по умолчанию Доллар, хотя его уже нет в системе.

**Comment by htrofymova** [comment]
Сделала, чтобы в валюных отчетах по умолчанию была одна из валют, по которым есть проводки. На диалог выбора валют - не распространяется, т.е. там все валюты, какие есть у тенанта.
