### ISSUE TITLE
Оплата покупця з комісією - Продажи - Новые операции - Пересмотреть статус

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1493]
1. Выставлен счет на сумму 8400 грн. 
2. Произведена оплата - операцией Оплата покупця з комісією (фото выше). 8300 + 100 (комис)
3. Операции новые - Статус Оплачено частково, залишок 100 грн. Это как-то неправильно. Долг по клиенту будет висеть? Он все заплатил. Если логически, то может там нужна разбивка по контрагентам на Покупателя и Банк по этой сумме в аналитике.
![image](https://user-images.githubusercontent.com/42540074/112619330-e0bcaa80-8e2f-11eb-8ecd-4b9fff030670.png)

**Comment by htrofymova** [comment]
готово
