### ISSUE TITLE
При расчете отпуска средняя не учитывает количество дней в 01,02.03 месяцах 2021 года. Ставит 0 дней. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1496]
![image](https://user-images.githubusercontent.com/42540074/113408906-e6c70400-93b8-11eb-9889-37cd852ece58.png)
Возможно все месяца 2021 года будут по 0 дней считаться при расчёте отпуска.

**Comment by htrofymova** [comment]
исправлено
