### ISSUE TITLE
Идет доначисление до минимальной ЕСВ в месяце увольнения с работы при неполном отработанном месяце. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1498]
![image](https://user-images.githubusercontent.com/42540074/113713230-be5c4400-96ef-11eb-94b1-67194eb464d5.png)
Кейс: сотрудник был в отпуске с 04.01.22 по 14.01.22, а потом сразу уволился. Отпускные ему оплачены. Отработанных дней 0 за январь. Приказ на увольнение проведен, уволен с 17.01.22. Денег ему не должны.
И тут идет доначисление до минималки по ЕФСС. В месяце увольнения.
![image](https://user-images.githubusercontent.com/42540074/149128050-790a75b2-70a8-4b03-a08e-df11fb9a0e43.png)
![image](https://user-images.githubusercontent.com/42540074/149128204-5b203adc-fdf8-4fb5-b96c-c12844f850ac.png)

**Comment by htrofymova** [comment]
нема чого виправляти, треба робити Розрахунок зарплати при звільненні, щоби все було правильно.
![image](https://user-images.githubusercontent.com/43743331/177509136-522caf74-bc99-4f35-9949-f6fd97571bfd.png)
