### ISSUE TITLE
Включить аналитику по контрагенту в Початковий баланс-Інше-По счету. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1499]
Кейс: Початковий баланс - Інше - Створити документ - вносим по 484 счету. Выглядит до проведения так
![image](https://user-images.githubusercontent.com/42540074/115010789-7fc84580-9eb6-11eb-9778-f9a7ea6b4f09.png)
После проведения так: Табличная часть с контрагентом исчезает
![image](https://user-images.githubusercontent.com/42540074/115010831-8ce53480-9eb6-11eb-9c09-098bf4b8b1c9.png)
И в отчете по 484 Контрагент Не заповнено
![image](https://user-images.githubusercontent.com/42540074/115010868-9cfd1400-9eb6-11eb-9ca4-71b69138c519.png)

**Comment by htrofymova** [comment]
готово
