### ISSUE TITLE
обєднаний звіт роботодавці - всі помилки

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1500]
заголовна частина
1. 
![image](https://user-images.githubusercontent.com/38099938/115025380-f1f65580-9ec9-11eb-9d32-a8a0fe4c9b16.png)

![image](https://user-images.githubusercontent.com/38099938/115025869-8791e500-9eca-11eb-834d-10931af84cbe.png)
у нас звітний новий, тобто 1 
![image](https://user-images.githubusercontent.com/38099938/115025993-a4c6b380-9eca-11eb-9330-14898e6542ff.png)

**Comment by kattrina-brekhova** [comment]
3 колонки, де має бути відображена інформація помісячно
тобто 7 - в січні (1), 7 - в лютому (2), ....
![image](https://user-images.githubusercontent.com/38099938/115026290-fcfdb580-9eca-11eb-9322-3113f5b581ad.png)

**Comment by kattrina-brekhova** [comment]
сума винагороди за договорм цпх
в мене було тільки в березні, відповідно має потрапити в колонку 3
а потрапила в першу
![image](https://user-images.githubusercontent.com/38099938/115026779-91681800-9ecb-11eb-9eec-c5493a5d50cf.png)

**Comment by kattrina-brekhova** [comment]
далі:
рядок 1
![image](https://user-images.githubusercontent.com/38099938/115027381-51556500-9ecc-11eb-87ab-ba221bcf1f1f.png)
сюди має потрапляти сума зарплати + за договрами цпх теж помісяно
тобто 1.1 + 1,2 + 1,3..... (потрібно мені мабуть було ще й лікарняні провести, але це вже після того як це виправимо давайте)
так от, у нас потрапила в місяць 1 сума за місяць 3 (березень) 
![image](https://user-images.githubusercontent.com/38099938/115027548-88c41180-9ecc-11eb-8edc-5f50e63c1ec7.png)

крім того, в рядок 1.2 в березні не потравило нарахування за договором цпх
![image](https://user-images.githubusercontent.com/38099938/115027627-9bd6e180-9ecc-11eb-8fc8-c0584a07a268.png)

**Comment by kattrina-brekhova** [comment]
тут з усім згодна, окрім того, що березневі суми потрапили у місяць 1
![image](https://user-images.githubusercontent.com/38099938/115030735-18b78a80-9ed0-11eb-83d9-d537a9cdaee0.png)

**Comment by kattrina-brekhova** [comment]
Д1:

номер місяця
![image](https://user-images.githubusercontent.com/38099938/115033005-98deef80-9ed2-11eb-97e1-e37c7076426e.png)

**Comment by htrofymova** [comment]
звіт доопрацьован, перевіряйте
