### ISSUE TITLE
НН - ошибки с заповнением

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1501]
создаю в апреле за март
указывает, что старая форма, требует перезагрузки
![image](https://user-images.githubusercontent.com/38099938/115228942-0f6e2e00-a11b-11eb-956f-e289dc12f68e.png)

создаю НН со ставкой 17%, не заполняет раздел А
![image](https://user-images.githubusercontent.com/38099938/115228982-1f860d80-a11b-11eb-8a7c-4b3008c834f5.png)

**Comment by htrofymova** [comment]
исправлено
