### ISSUE TITLE
Довідка про доходи - добавить возможность выбирать период отображения данных 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1503]
1. Указать любой период, не обязательно от текущей даты (в бухгалтерии много любителей задним числом данные вводить)
2.  Возможность построить справку за год, а не за полгода. Это несколько раз просили клиенты.

**Comment by Anestezia** [comment]
Человек выходит на пенсию, и ему нужно формировать справку о доходах за большой период сразу, за любой от даты формирования. Реальный кейс

**Comment by htrofymova** [comment]
"Довідка" теперь будет формироваться за установленньій Глобальньій период. Если период = "За весь час", то по-умолчанию будет за последние 6 месяцев. Бонусом сделан фильтр по Глобальному периоду для списа документов по сотруднику.
