### ISSUE TITLE
единый отчет фоп - недоработки в печатной форме

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1504]
в отчете есть 7 раздел
![image](https://user-images.githubusercontent.com/38099938/116065101-52864f00-a68f-11eb-821a-e60ababd9ffa.png)
у нас его нет
![image](https://user-images.githubusercontent.com/38099938/116065127-59ad5d00-a68f-11eb-8891-e15382210f64.png)

в додатке есть название 9 раздела
![image](https://user-images.githubusercontent.com/38099938/116065183-6df15a00-a68f-11eb-817c-33706cc74b61.png)
у нас нет названия
![image](https://user-images.githubusercontent.com/38099938/116065214-76499500-a68f-11eb-9911-6ef963a9fcb7.png)

но рядок 21 в декларации и додаток 1 за 1 квартал не заполняем и не подаем, так как этот додаток аналог формы формы д5, которую фоп подавал раз в год, поэтому этот додаток и строку 21 в декларации заполняем и подаем по итогам года

**Comment by htrofymova** [comment]
исправленор
