### ISSUE TITLE
Поправить вид отчета "Розрахунково-платіжна відомість"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1506]
![Screenshot_2](https://user-images.githubusercontent.com/42540074/116696083-1a05ae80-a9ca-11eb-8438-bbcfcd8150b6.png)
![Screenshot_1](https://user-images.githubusercontent.com/42540074/116696088-1b36db80-a9ca-11eb-9c14-13240557be6b.png)

**Comment by htrofymova** [comment]
А не нужно строить этот отчет "За весь час". Какой в этом смысл? 
Убрала такую возможность. А также, если глобальный период больше 1 месяца, то отчет строится за текущий месяц. Внутри период можно менять, как и прежде.
