### ISSUE TITLE
Персонал. Звіти. Синий шрифт названий отчетов.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#151]
![2018-05-15](https://user-images.githubusercontent.com/35918141/40062619-4dfba27c-5864-11e8-92ce-b39cb1c3d761.png)
Вообще, не знаю, как лучше. Синий тоже красиво.

**Comment by nik-man** [comment]
Гиперлинк, да. В остальном интерфейсе не гиперлинк.
Как правильно?

**Comment by AlexeyTishkin** [comment]
Специально делали так, чтобы отчет можно было открыть кликнув на любой области его расположения. А в случае с гиперлинком - клик только на нем.

**Comment by nik-man** [comment]
Интерфейс должен быть везде одинаковый или нет?

**Comment by nik-man** [comment]
Ты зануда! ))

**Comment by Illya-Lykhachov** [comment]
привел список к единообразию
