### ISSUE TITLE
Счет / invoice - срок оплаты до ХХ дней сделать кастомизиуемым

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1510]
1. Сейчас **в счете** имеем поле (пустое по умолчанию), в котором можно задавать дату оплаты.
Если поле оставить пустым - выводится "в течение 3х дней"

Масса народу просит двух вещей:
Возможности настраивать значение по умолчанию произвольно 
Возможность не выводить вообще срок оплаты, если не указано явно.

2. Сейчас **в invoice** имеем жестко забитое в текст печатной формы
"Payment according hereto may be made not later than _______________./ Оплата за цим інвойсом може бути здійснена не пізніше _______________."
Хотят того же - возможности не выводить этот текст вообще без особой надобности.
Перекликается с идеей редактируемого текста из https://github.com/a2develop/bugTracker/issues/1507

**Comment by htrofymova** [comment]
сделала для Рахунка - на закладке Для друкованої форми. Invoice - отдельная пестня

**Comment by Anestezia** [comment]
Для счета обычного подтверждаю, настраивается текст или отключается полностью. В инвойсе настройка есть, но текст не убирается в печатной форме. Зато срок оплаты хорошо проставляется в печатную форму через Сплатити до:

**Comment by AndriyNesterenya** [comment]
Косяки в Инвойсе:
- В поле Beneficiary’s bank: вместо англ. названия попадает МФО
- При экспорте в PDF все, что под таблицей, уезжает на вторую страницу.
- механизм колонтитулов не работает вообще. Было бы полезно весь наш "подвал"  запихать  в нижний колонтитул.
- ограничения на объем колонтитулов слишком строгие, нужно в районе 2000 знаков каждый IMHO. 
- Поля Предмет и Условия.... хорошо бы сделать редактируемыми, в идеале задаваемыми по логике колонтитулов с возможностью индивидуальной правки.
- Совсем в идеале в украинской версии выбирать между Виконавець/Постачальник в зависимости от того, что продаем, товар или услугу.
[Кривой Invoice № 0622-1.pdf](https://github.com/a2develop/bugTracker/files/8854532/Invoice.0622-1.pdf)

**Comment by AndriyNesterenya** [comment]
Изменения вижу.
Но глючит:
При попытке воспользоваться Настройками на вкладке "Для друкованої форми" появляется всплывающее окно и все виснет
![image](https://user-images.githubusercontent.com/38098758/175142199-1ec883a8-1c55-4fda-844d-6f5882565f6e.png)

Идея была в том, чтобы твои "Абзацы" (раз уж побили единый текст на куски) по умолчанию наполнить кусками нашего текста.
Хотел побаловаться с этим - но пока не смог.

**Comment by AndriyNesterenya** [comment]
Для истории:

All charges of correspondent banks are at the Supplier’s expenses. / Усі комісії банків-кореспондентів сплачує виконавець.

This Invoice is an offer to enter into the agreement. Payment according hereto shall be deemed as an acceptation of the offer to enter into the agreement on the terms and conditions set out herein. Payment according hereto may be made not later than _______________./ Цей Інвойс є пропозицією укласти договір. Оплата за цим Інвойсом є прийняттям пропозиції укласти договір на умовах, викладених в цьому Інвойсі. Оплата за цим інвойсом може бути здійснена не пізніше _______________.

Please note, that payment according hereto at the same time is the evidence of the work performance and the service delivery in full scope, acceptation thereof and the confirmation of final mutual installments between Parties. / Оплата згідно цього Інвойсу одночасно є свідченням виконання робіт та надання послуг в повному обсязі, їх прийняття, а також підтвердженням кінцевих розрахунків між Сторонами.

Payment according hereto shall be also the confirmation that Parties have no claims to each other and have no intention to submit any claims. The agreement shall not include penalty and fine clauses. /
Оплата згідно цього Інвойсу є підтвердженням того, що Сторони не мають взаємних претензій та не мають наміру направляти рекламації. Договір не передбачає штрафних санкцій.

The Parties shall not be liable for non-performance or improper performance of the obligations under the agreement during the term of insuperable force circumstances. / Сторони звільняються від відповідальності за невиконання чи неналежне виконання зобов’язань за договором на час дії форс-мажорних обставин.

Any disputes arising out of the agreement between the Parties shall be settled by the competent court at the location of a defendant. / Всі спори, що виникнуть між Сторонами по договору будуть розглядатись компетентним судом за місцезнаходження відповідача.

**Comment by htrofymova** [comment]
Исправила. 
Еще уточнение про п. 1. поле Beneficiary’s bank - МФО отображается не вместо, а до англ названия банка. Англ название нужно заполнить,тогда оно будет отображаться после МФО

**Comment by htrofymova** [comment]
Для истории - то зайве, збережено в 3-х місцях

**Comment by AndriyNesterenya** [comment]
> Исправила. Еще уточнение про п. 1. поле Beneficiary’s bank - МФО отображается не вместо, а до англ названия банка. Англ название нужно заполнить,тогда оно будет отображаться после МФО

Да, нашел.
Это отдельная моя боль - чтобы настроить SWIFT и анг ланвание банка нужно сильно и неинтуиривно извратиться.
Не придумал еще как лечить.
Была мысль при установке галочки ЗЕД показывать под полем собственного названия ссылку ссылку на https://service.bookkeeper.kiev.ua/accounting/catalogs и тектстом "не забудьте настроить английское название банка и егойный СВИФТ в соотв. справочнике".
Как ссделать ссыль прямо на справочник банков не нашел.

**Comment by AndriyNesterenya** [comment]
ЗЫ А нужен ли вообще МФО нашего банка в инвойсе?

**Comment by MaksymTikhomirov** [comment]
> ЗЫ А нужен ли вообще МФО нашего банка в инвойсе?

Отож

**Comment by AndriyNesterenya** [comment]
Ага, открылись настройки.
Тут не видно, что поля непустые - сбивает с толку.
![image](https://user-images.githubusercontent.com/38098758/175348228-4c887910-24fe-46ff-ad2f-c67599a3fd7f.png)

**Comment by htrofymova** [comment]
> > ЗЫ А нужен ли вообще МФО нашего банка в инвойсе?
> 
> Отож

як скажете. Так було с самого початку

**Comment by htrofymova** [comment]
> Ага, открылись настройки. Тут не видно, что поля непустые - сбивает с толку. ![image](https://user-images.githubusercontent.com/38098758/175348228-4c887910-24fe-46ff-ad2f-c67599a3fd7f.png)

не можу повторити

**Comment by htrofymova** [comment]
виправила (порожні абзаци)

**Comment by AndriyNesterenya** [comment]
От тепер кросівоє, і нас взагалі влаштовує зовсім.
Одне зауваження - якщо пробувати писати адресу вбо умови з переводом рядка, в результаті чого вистот таблиці збільшується на пару рядків - весь текстовий блок їде на другу сторінку.
Частково проблему вирішує видалення зайвого пустго місця на у виділених ячейках.
![image](https://user-images.githubusercontent.com/38098758/175961763-608e114a-7d0e-4fdc-9ea6-b74d6dd990fe.png)

Що там має бути за нинішньою ідеєю?

**Comment by htrofymova** [comment]
У блоці Customer (Supplier) Bank Information  - це ж і є те саме англійське найменування банку, треба його заповнити. МФО, до речі, прибрати?
З адресою - щось зробити спробую...

**Comment by htrofymova** [comment]
готово

**Comment by AndriyNesterenya** [comment]
Кросівоє!
Про назву англійською - це я протупив.
В мене в бойовому аккаунті все заповнено, а не Деві не було назви.
МФО мабуть таки варто прибрати, бо сенсу в цій інформації нуль, а зайвий рядок зекономимо.
![image](https://user-images.githubusercontent.com/38098758/176390274-b0f2d153-20a8-4a8b-8a59-1cdb98f7cd36.png)
