### ISSUE TITLE
просят разделить акцызный сбор в розничной торговле (пиво, табачка), возможно отдельный внутренний отчет

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1511]
Добрый день, мы продаем 2 подакзицных товара:
Табачные изделия и пиво.
Необходимо разделить каким то образом сумму акциза за месяц по этим категориям, т.к. оплачивать нужно отдельно.
Как сформировать отчет по акцизу за месяц Д1.3. и Д1.4?
СПасибо
--
С уважением,
Шумаков Тимур
+380508220447

**Comment by htrofymova** [comment]
в раздел Роздріб - Звіти добавлен отчет "Звіт до декларації акцизного податку"
