### ISSUE TITLE
Додати в платіжні доручення можливість робити операції по 655 рахунку - Страхування майна

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1513]
Доброго дня! У Платіжному доручення "Операція" у випадаючому списку, коли  обираю "Страховий платіж", то робить проводку на 654 "За індивідуальним страхування", а мені потрібно на 655 "Страхування майна".  Чи можна якось вирішити це питання? 
З повагою, Оксана
Головний бухгалтер ТОВ "Персей-Безпека"

**Comment by htrofymova** [comment]
Добавлена операция: Страховий платіж (страхування майна)
