### ISSUE TITLE
При рассчете средней для выплаты отпускных и больничных не правильно учитываются праздничные дни. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1514]
Если нет возможности забивать календарь, то хоть сделайте регулируемое поле для самостоятельно ввода пользователем количества дней в году для рассчета.

**Comment by Anestezia** [comment]
Доброго дня! При розрахунку середньої ЗП для відпускних невірно рахує кількість днів. Не враховує дні лікарняних (не додає)! В результаті чого Середньоденна сума невірна так, як ділить на неправильну суму днів за 12 місяців. Скріни прикладу  додаю!
[Відпускні.docx](https://github.com/a2develop/bugTracker/files/6878574/default.docx)

**Comment by Anestezia** [comment]
При нарахуванні середньоденної суми для лікарняних невірно рахується кількість днів: віднімає святкові дні! 
При розрахунку середньоденної зп для лікарняних беруться всі календарні дні! Віднімаються календарні дні за попередні лікарняні і самі суми лікарняних, а також віднімаються дні відпустки без збереження зп.
Персей

**Comment by htrofymova** [comment]
готово, треба перевірити різні варіанти
