### ISSUE TITLE
Добавить функцию "Вручну" и "Додаткові нарахування" в операцию "Розрахунок зарплати при звільненні"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1516]
![image](https://user-images.githubusercontent.com/42540074/126948865-32f54481-3b1a-46e5-9ac1-0456b57b3b89.png)

Добрий день,
підкажіть, будь ласка! Звільнився працівник. Через Персонал - Кадри був складений наказ про звільнення і  спроба заповнити розрахунок зарплати про звільнення.  
1. Чи можливо в цей розрахунок додати функцію "вручну" стосовно нарахування оплати робочого часу (в розрахунку компенсації невикористанної відпустки ця функція  присутня), є специфіка в нарахуванні зарплати.
2. Я не змогла в цей розрахунок внести індексацію з/пл за відпрацьованний час, нема куди.

**Comment by Anestezia** [comment]
Кейс: Человек отработал декабрь и зп ему выплатили. Дальше выходные, потом он берет отпуск с 4.01.22 по 14.01.22, в приказе на отпуск ему пишет 11 дней. Но 7 число выходной и учитываться не должно. Поэтому меняем в приказе не отпуск вручную на 10 к.д. отпуска. 

Дальше, он решил уволиться с 17.01.22, поэтому в январе отработанных дней будет 0. За отпускные с ним еще 4.01. расчитались. 1) Нужно ли делать расчет при увольнении, если таблица будет пустой?
2) В этой таблице 0 компенсации за неиспользованный отпуск, 0 отработанных в январе дней, но отпуск показывается. И при этом показывается 11 дней без права редактирования, соответственно, и сумма начисления отпускных увеличена. В результате, мы ему еще должны и налоги тоже начислены. Сделать ничего нельзя.

![image](https://user-images.githubusercontent.com/42540074/149123158-30bdcdc3-19a4-4f07-8ea0-32966300c7af.png)

**Comment by htrofymova** [comment]
додала відмітку "вручну" для "Нараховано (робочий час)". Індексація/премія - вже додано раніше.
