### ISSUE TITLE
Додати податкові соціальні пільги в "Наказ на прийняття" та "Встановлення пільги"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1518]
Доброго дня.
Ми Вами спілкувались по питанню податкової пільги
https://buhgalter911.com/uk/spravochniki/oplata-truda/rozmir-podatkovoyi-socialynoyi-1025102.html
Це інформація про застосування пільги На дітей є звичайна пільга і  підвищена, якщо один із батьків сам виховує дітей. 
В системі немає такої опції.
![image](https://user-images.githubusercontent.com/42540074/126964549-391227a6-1a18-4d09-8410-af0062e98fdd.png)
![image](https://user-images.githubusercontent.com/42540074/126965024-19e8e869-ca6e-4744-9739-6d13e4cc963a.png)

**Comment by Anestezia** [comment]
Доброго вечора. В мене питання стосовно соціальної пільги. Мені проговорювали, що будуть внесені корективи.У вас зараз є тільки опція-100% суми пільги (1135 грн. на дитину) +діти. Мені необхідно щоб ви ще додати 150%+діти (150 % суми пільги (1702,50 грн. на дитину) – платник податку, який: є одинокою матір’ю (батьком), вдовою (вдівцем) або опікуном, піклувальником – у розрахунку на кожну дитину віком до 18 років; Підкажіть коли буде це виправлено. Дякую

**Comment by htrofymova** [comment]
готово
