### ISSUE TITLE
Добавить в Начальный баланс по НА дату начала отсчета срока использования

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1519]
![Screenshot_6](https://user-images.githubusercontent.com/42540074/131148440-4f5df3ae-d013-443b-ac39-e9ed546bfd59.png)
Иначе неправильно насчитывается амортизация.

**Comment by htrofymova** [comment]
У нас для начисления износа реализован только прямолинейный метод. Износ расчитывается по формуле: (первоначальная стоимость - ликвидационная стоимость ) / количество месяцев эксплуатации.
Стесняюсь спросить, к какому месту тут "дата начала отсчета срока использования"? Что это за дата такая вообще? Есть дата ввода в эксплуатацию, начиная с месяца следующего за которой и начисляется износ.
Если необоротный актив вводится в начальном балансе, то это уже означает, что он введен в эксплуатацию, т.е. дата ввода в эксплуатацию наступила, когда-то в прошлом. Нужно правильно ввести цифры в начальный баланс и будет правильно начисляться износ. Впрочем, я уже об этом неоднократно говорила-писала. 
В примере с картинки - износ уже не начисляется.

**Comment by Anestezia** [comment]
В Карточке начального баланса нет даты ввода в эксплуатацию. И нет возможности узнать, от какой даты начинать отсчет месяцев использования. Изготовить могли в 2018 году, а продать изделие в 2019, или купить и положить на склад, а ввести в эксплуатацию в 2020.
Допустим, мой актив выпущен  в январе 2021 года, тогда же введен в эксплуатацию. с февраля должна начисляться амортизация. БК насчитывает сумму 45 000/29 месяцев использования = 1551,72. Прямо с января почему-то. И не принимает в рассчет, что указана сумма амортизации (я так понимаю, уже ранее начисленная в другой программе = 9310.32) Получается, что если в январе ввели, с февраля должно идти начисление, 6 месяцев уже начислялось, значит раньше 6 месяца этот актив вообще не должен быть в ведомости амортизации? 
![image](https://user-images.githubusercontent.com/42540074/132315158-e9c75778-85fe-44e5-896a-71c85a34b3ae.png)
Он появляется не то, что ранее 6 месяцев, а еще и до своего рождения, в декабре 2020 года.
![image](https://user-images.githubusercontent.com/42540074/132315595-a5a0c17b-17d8-46f6-a48d-d70670234fbf.png)

Значит, может все же нужна графа Дата ввода в эксплуатацию?

**Comment by htrofymova** [comment]
еще раз. НА введен в учет начальньім балансом, следовательно, УЖЕ введен в єксплуатацию, и не в январе, и не в феврале или еще когда, а "до начала времен". Поєтому износ для таких НА начисляется в ЛЮБОМ периоде. Если хотите соблюсти датьі, то надо вводить в експлуатацию, как положено: Актом ввода в експлуатацию, тогда износ начнет начисляться с месяца, следующего за месяцем ввода. Сумма же износа для прямолинейного метода рассчитьівается (цитирую уже сама себя) по формуле: (первоначальная стоимость - ликвидационная стоимость ) / количество месяцев эксплуатации. При чем здесь ранее начисленньій износ? А Дату ввода в експлуатацию может и стоило б добавить в начальньій баланс, но только для полнотьі справочной информации, типа, чтобьі в карточке отображалась/печаталась, больше ни для чего.
