### ISSUE TITLE
Счет входящий. Печать. Вторая страница чуток неправильная.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#152]
![2018-05-16 39](https://user-images.githubusercontent.com/35918141/40104584-6abea36a-58f9-11e8-981f-1af45eee8d10.png)

Причем, если строк 40 и больше, то уже хорошо, шапка переносится.

**Comment by nik-man** [comment]
Вот пример документа в тестовом аккаунте:
http://dev.a2start.com/document/invoice_in/edit/5828

**Comment by AlexeyTishkin** [comment]
Проблема в Стимулсофте. Буду общаться...

**Comment by AlexeyTishkin** [comment]
Исправил.
