### ISSUE TITLE
Продажи -Операции - статусы сделать более различимыми цветами

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1522]
![image](https://user-images.githubusercontent.com/42540074/133580141-29ba114a-d619-4a74-9472-1e1cbc905769.png)
Тут просят, например, Очікує оплати сделать желтым. Не два оттенка синего, два оттенка зеленого, а более ясно различимые.

**Comment by htrofymova** [comment]
перекрасила статусы

**Comment by Anestezia** [comment]
Супер! Спасибо!
