### ISSUE TITLE
[Особистий кабінет] - кривое назначение платежа в формируемом из Личного кабинета счете

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1524]
В личном кабинете формируем счет с кривым назначением.

1. В счете на оплату в назначении пишем только "Передплата за ліцензії на використання ПЗ «BookKeeper SaaS»"
А нужно с номером тенанта или счета, в стиле "Передплата за ліцензії
на використання ПЗ «BookKeeper SaaS» згідно рахунку № 726/210916 від 16.09.2021. Без ПДВ."

2.  В платежке кривая последовательность и ненудній шаблон телефона 
Сейчас пишем "Згідно рахунку № 726/210916 від 16.09.2021 Передплата за ліцензії
на використання ПЗ «BookKeeper SaaS», користувач +380XXXXXXXXX."
Стоит поменять местами "Передплптп за... згідно рахунку" и что-то сделть с телефоном.
Телефон или подтягивать из свойств клиента или убрать "користувач +380XXXXXXXXX" вообще

![Рахунок BKPR](https://user-images.githubusercontent.com/38098758/133586886-2f66e10d-625f-4132-b845-abba4fdd9d29.jpg)

**Comment by htrofymova** [comment]
А зачем пункт 1. ? Это же счет! В наименовании услуги писать номер тенанта или счета? Это же не назначение платежа.

**Comment by htrofymova** [comment]
назначение платежа изменила

**Comment by AndriyNesterenya** [comment]
> А зачем пункт 1. ? Это же счет! В наименовании услуги писать номер тенанта или счета? Это же не назначение платежа.

Эти черти тупо копипастят в назначение платежа то, что видят в счете.
А мы, не видя номера тенанта (который есть в номере счета), не можем нормально разнести оплаты.
ИМХО проще добавить в счет то же самое, что в платежке.
Или хотя бы номер тенанта добавлять типа "Користувач SE-XXX"

**Comment by AndriyNesterenya** [comment]
> назначение платежа изменила

Наблюдаю, зачОт

**Comment by Anestezia** [comment]
Нормальный бухгалтер при заполнении назначения платежа не номенклатуру туда тулит, а именно указывает документ-основание, например, счет, номер и дата. Телефон я бы в маске оставила вместе с номером тенанта, так будет больше шансов на нормальную идентификацию.
