### ISSUE TITLE
новая форма отчета для работодателей f j 0500107 за 3 квартал

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1525]
код формы отчета f j 0500107

**Comment by kattrina-brekhova** [comment]
F/J 0500107 - Податковий розрахунок сум доходу, нарахованого (сплаченого) на користь платників податків – фізичних осіб, і сум утриманого з них податку, а також сум нарахованого єдиного внеску;
F/J 0510107 - Відомості про нарахування заробітної плати (доходу, грошового забезпечення) застрахованим особам Додаток 1 до Податкового розрахунку сум доходу, нарахованого (сплаченого) на користь платників податків - фізичних осіб, і сум утриманого з них податку, а також сум нарахованого єдиного внеску (Д1) (пункт 1 розділу IV);
J0510207 - Відомості про осіб, які доглядають за дитиною до досягнення нею трирічного віку та відповідно до закону отримують допомогу по догляду за дитиною до досягнення нею трирічного віку та/або при народженні дитини, усиновленні дитини, та осіб із числа непрацюючих працездатних батьків, усиновителів, опікунів, піклувальників, прийомних батьків, батьків-вихователів, які фактично здійснюють догляд за дитиною з інвалідністю, дитиною, хворою на тяжке перинатальне ураження нервової системи, тяжку вроджену ваду розвитку, рідкісне орфанне захворювання, онкологічне, онкогематологічне захворювання, дитячий церебральний параліч, тяжкий психічний розлад, цукровий діабет I типу (інсулінозалежний), гостре або хронічне захворювання нирок IV ступеня, за дитиною, яка отримала тяжку травму, потребує трансплантації органа, потребує паліативної допомоги, якій не встановлено інвалідність, а також непрацюючих працездатних осіб, які здійснюють догляд за особою з інвалідністю I групи або за особою похилого віку, яка за висновком медичного закладу потребує постійного стороннього догляду або досягла 80-річного віку, якщо такі непрацюючі працездатні особи отримують допомогу, надбавку або компенсацію відповідно до законодавства, та нарахування сум єдиного внеску за патронатних вихователів, батьків-вихователів дитячих будинків сімейного типу, прийомних батьків, якщо вони отримують грошове забезпечення відповідно до законодавства Додаток 2 (Д2) (пункт 2 розділу IV);
J0510307 - Відомості про осіб, які проходять строкову військову службу Додаток 3 (Д3) (пункт 3 розділу IV);
F/J 0510407 - Відомості про суми нарахованого доходу, утриманого та сплаченого податку на доходи фізичних осіб та військового збору Додаток 4 ДФ (пункт 4 розділу IV);
F/J 0510507 - Відомості про трудові відносини осіб та період проходження військової служби Додаток 5 (Д5) (пункт 5 розділу IV);
F/J 0510607 - Відомості про наявність підстав для обліку стажу окремим категоріям осіб відповідно до законодавства Додаток 6 (Д6) (пункт 6 розділу IV).

**Comment by kattrina-brekhova** [comment]
Що ж змінилося у додатку №4ДФ?

Зміни стосуються лише введення окремого розділу ІІІ у додатку 4ДФ щодо бюджетних грантів. Але всі роботодавці та податкові агенти отримали оновлену форму єдиної звітності. 

Зокрема, у додатку 4ДФ з'явився розділ ІІІ зі зазначенням інформації про доходи у вигляді бюджетного гранту.

Відповідно Довідник ознак доходів також доповнили кодами для позначення суми доходу у вигляді бюджетного гранту (201, 202, 203).

**Comment by kattrina-brekhova** [comment]
Нумерація в єдиній звітності

Звертаємо увагу! Податківці вже вказували, що для кожного звітного кварталу розпочинається своя нумерація єдиної звітності. Нумерація ведеться у хронологічному порядку незалежно від її типу і не продовжується в наступних кварталах.

У додатках Д1, Д2, Д3, 4ДФ, Д6 до єдиної звітності у рядку 02 в реквізиті «номер місяця в кварталі» вказується номер місяця в межах звітного кварталу від 1 до 3. А саме при нумерації для додатків за ІІІ квартал 2021 року вказується: 1 – для липня; 2 – для серпня; 3 – для вересня.

Номер додатка до розрахунку зазначається в межах одного виду додатку. Кожен вид додатку нумерується окремо.

**Comment by kattrina-brekhova** [comment]
https://tax.gov.ua/elektronna-zvitnist/spetsializovane-klientske-program/

**Comment by htrofymova** [comment]
готово
