### ISSUE TITLE
В програмі невірно відображено кількість святкових днів у травні .

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1527]
Доброго дня.

В програмі невірно відображено кількість святкових днів у травні .

Кількість святкових днів у травні три : 1,2,9

Робочих днів = 18

Для розрахунку середньої зарплати 31-3=28 днів. В програмі=29 ???

Як наслідок невірно розраховується середня заробітна плата.

Вкотре звертаюсь з проханням виправити цю помилку.

Томара Войтех
ТОВ "ЄВРОТЕЛЕКОМ"
вул. Волинська, 10
03151, Київ, Україна
Тел.: +38 099 915 91 59

**Comment by htrofymova** [comment]
исправлено
