### ISSUE TITLE
Расчет ЕСВ по инвалидам

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#153]
считает по ставке 22%
![photo_2018-05-16_11-49-01](https://user-images.githubusercontent.com/38099938/40106869-919cf7e2-58ff-11e8-8237-36a93c111f8e.jpg)
![photo_2018-05-16_11-50-03](https://user-images.githubusercontent.com/38099938/40106874-9654bf2c-58ff-11e8-9105-ae4e49ea03fd.jpg)
![photo_2018-05-16_11-51-47](https://user-images.githubusercontent.com/38099938/40106879-9a927110-58ff-11e8-900c-83f9dbfa9337.jpg)

**Comment by Illya-Lykhachov** [comment]
Исправлено
