### ISSUE TITLE
Сделать полосу прокрутки в списке фирм при выведении списка всех фирм и кнопки настройки.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1530]
Если фирм больше 20-25 в тенанте, то при отображении списка не все доступны для переключения.
![Screenshot_22](https://user-images.githubusercontent.com/42540074/144652294-729bbfd3-5a05-4001-965f-5cee2c61bc43.png)
![Screenshot_18](https://user-images.githubusercontent.com/42540074/144652297-7f3fed21-8113-4222-9a12-f5fab30e5dd0.png)
![Screenshot_19](https://user-images.githubusercontent.com/42540074/144652298-640bc9fb-9425-4488-9467-78afcfc6f914.png)
![Screenshot_20](https://user-images.githubusercontent.com/42540074/144652299-1e3eecf7-4d82-4664-b9f9-2b8081ea03ff.png)
![Screenshot_21](https://user-images.githubusercontent.com/42540074/144652301-08034c2f-f454-4f0a-8685-3b47ee68b7cb.png)

**Comment by alex-kukhtin** [comment]
Сделано в версии 7892
