### ISSUE TITLE
Сумма по доходу от курсовых разниц должна попадать в доход в документе Начисление налогов, юр.лицо 3 группа.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1531]
На данный момент сумма курсовых разниц туда не попадает. В строке Доход Показывается гривневый эквивалент всей суммы купленной валюты.

**Comment by htrofymova** [comment]
какая проводка?

**Comment by htrofymova** [comment]
я писала в телегу, повторю здесь:
Если по-нормальному делать: 1. Оплата покупця(в валюті) дт 312-кт 362 - гривненвьій еквивалент попадает в доход. вносится тот документ, которьій именно от покупателя по инвойсу, там и курс НБУ будет тот, что надо. Если ета валюта по частям или вся продается. то ето уже не доход! он и не будет зачисляться с 362 счета и в доход не попадет ; 2. Перерахування валюти для продажу дт 334- кт 312. 3. Зарахування грн від продажу валюти дт 311 - кт 334. Еще может бьіть валлютньій платеж между своими счетами дт334 - кт 312 и дт 312 - кт 334. В доход берется только дт 312- кт 362 - и ето правильно.
Для справки: гривневьій еквивалент существует только в валютньіх операциях (проводках), зачисление гривньі от продажи валютьі - ето не гривневьій еквивалент, так что вообще не понятно о чем идет речь.
А для курсовьіх разниц, очень прошу, напишите конкретную проводку, которая должна попадать в доход.

**Comment by htrofymova** [comment]
добавила в "доходную часть" проводку дт334 - кт 711
