### ISSUE TITLE
Пересмотреть статус операции от Инвойса. Закрывать операцию Инвойс+Экспорт услуг+Оплата, и Инвойс+Оплата

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1532]
Кейс клиента: В продажах выставили инвойс, к нему подкрепили Експорт Послуг и Оплату покупця в валюте.  Статус операции — Очікує відвантаження. 
Експорт послуг еще старый документ, может поэтому он не берется в расчет при формировании статусов?
![image](https://user-images.githubusercontent.com/42540074/147086728-58a34491-8959-4701-b429-816b68bf8217.png)
![image](https://user-images.githubusercontent.com/42540074/147086773-3ec84690-2c07-471d-973e-190e444df15b.png)

**Comment by htrofymova** [comment]
готово
