### ISSUE TITLE
Сделать запрет расчета зп за месяц по сотрудникам, по которым уже была начислена зп в других ведомостях

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#154]
Или добавить возможность удалять строчки по сотрудникам, ко которым зп уже была  начислена

Это предотвратит дублирование начисления

Даст возможность рассчитать увольняющегося сотрудника, не затрагивая остальных

И удобнее, если зп начисляют отдельными ведомостями по различным магазинам или участкам

**Comment by kattrina-brekhova** [comment]
ага, получается!! а как быть с расчетом увольняющегося сотрудника в середине месяца? как начислить ему зп и компенсации, не начисляя суммы остальному персоналу?

**Comment by Illya-Lykhachov** [comment]
это пока не реализовано
