### ISSUE TITLE
Кривое название файла экспорта "Акт приймання-передачі об'єкта нематеріальних активів"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1541]
При попытке экспорта из операции Продаж об'єктів нематеріальних активів формирует файл с именем "_.._printforms_act_out_IA.pdf"
Надо бы людское читаемое имя типа "Акт приймання-передачі об'єкта нематеріальних активів №"

**Comment by htrofymova** [comment]
готово
