### ISSUE TITLE
Граничный доход для применения Налоговой соц. льготы поставить включительно, а не До указанного значения

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1542]
граничний розмір доходу, до якого застосовується податкова соціальна пільга, впродовж всього 2022 року складатиме:

2481 грн. × 1,4 = 3473,4 ≈ 3470 грн.

![image](https://user-images.githubusercontent.com/42540074/151400696-463db24f-d8d2-44eb-9681-c55f3a0e271a.png)

**Comment by htrofymova** [comment]
готово,перевіряйте
