### ISSUE TITLE
Дополнить варианты применения налоговой соц. льготы к ндфл.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1543]
https://balance.ua/news/post/nsl-na-detey-2022/

**Comment by htrofymova** [comment]
які саме варіанти додавати?

**Comment by htrofymova** [comment]
У нас просили таке;
1. Одинока мати* (одинокий батько), вдова (вдівець), опікуни, опікуни з дітьми до 18 років
(підвищена «дитяча» ПСП у розмірі 150 % від загальної ПСП – 1 860,75 грн. (1 240,50 х 150 %)
І далі там перелік у табличці сум, відповідно до кількості дітей.
2.  150 + діти ми додали вже. А ще там є коли тільки один батько є і діти при ньому, і також коли багато дітей і хтось з них інвалід
3. Якщо в сім'ї дитина з інвалідністю
(підвищена «дитяча» ПСП – 1 860,75 грн.)** 
Табличка присутня з кількістю дітей і сумами
4. Одинокий батько і дитина з інвалідністю
(підвищена «дитяча» ПСП – 1 860,75 грн.)

**Comment by htrofymova** [comment]
Додала комбіновану льготу для батьків з дітьми-інвалідами. Все інше вже є.

**Comment by Anestezia** [comment]
Комбінована пільга працює. Значення окладу для застосування пільги Включно.
