### ISSUE TITLE
Кодифікатор адміністративно-територіальних одиниць та територій територіальних громад заменить.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1545]
Об'єкт териториально-адмінистративного устрою
 Также просили его вкрутить прямо в отчеты, чтоб можно было выбирать. 
[kodyfikator.xlsx](https://github.com/a2develop/bugTracker/files/8049956/kodyfikator.xlsx)

**Comment by htrofymova** [comment]
готово
