### ISSUE TITLE
Косяк в Договорах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1546]
Косяк а ссылке при клике на предмет договора на /accounting/contract попадаем не в нужный договор, а на новый список догворов с выделенным первым попавгимся по списке договором.
Неудобно до жути и приводит к ошибкам.

Если сложно - добавить на добавить бы на второй экран к столбцу предмет договора еще и название контрагента

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Є вказані зміни.
