### ISSUE TITLE
Кривая верстка в НА

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1547]
В меню Необоротні активи /fixassets/dashboard на Панелі управління кривая верстка в правом блоке "Бухгалтерський облік необоротних активів"
Длинный текст в стоблце Рахунок не влазит в окно

![image](https://user-images.githubusercontent.com/38098758/170669569-6ad64595-79ad-4f53-ad57-855341a1e7af.png)

**Comment by htrofymova** [comment]
переделала

**Comment by MaksymTikhomirov** [comment]
@AndriyNesterenya проверь плиз и закрой, если все норм
