### ISSUE TITLE
Косяк в Контрагентах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1548]
Косяк в ссылке при клике на контрагента /sales/partner попадаем не в нужного контрагента, а на новый список контрагентов с выделенным первым по списку.

Точно та же ситуация, что была исправлена в №1546
https://github.com/a2develop/bugTracker/issues/1546

**Comment by htrofymova** [comment]
исправла

**Comment by Anestezia** [comment]
При клике на контрагента попадаем теперь в информацию о выбранном контрагенте с списке контрагентов.
