### ISSUE TITLE
Довіреність

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1550]
Реалізувати можливість створювати типову форму довіреності на основі видаткової накладної.

Наказ про затвердження форми:
https://zakon.rada.gov.ua/rada/show/v0192202-96#Text

Бланк в Ворді наприклад тут:
https://yurporada.kiev.ua/uk/tipov-dokumenti/skachat-blank-doverennosti.html

Бланк в Екселі наприклад тут:
https://www.salary.net.ua/downloads/--/116----2--excel/download.html

**Comment by htrofymova** [comment]
самостійний документ. Бо немає сенсу прив'язувати по накладної, тем паче видаткової

**Comment by AndriyNesterenya** [comment]
Є трошки косячків.

- не друкує МФО (мабуть варто взагалі прибрати і залишити тільки IBAN)
- не друкує кому видана довереність.
- якщо паспорт вносити с "ким виданий" - не влазить в рядок і обрізається/не переноситься.
- написи під рядками (найменування організації постачальника) та (№ і дата наряду) виводяться на рядок вище, ніж треба
- поле "№ і дата наряду" варто назвати більш широко, бо крім наряду це може бути рахунок, накладна, щось ще. Щось в стилі "отримання цінностей за (назва, № і дата документу)"

![image](https://user-images.githubusercontent.com/38098758/182709086-51ca9222-76a7-45c8-a072-cec9f32727e3.png)

**Comment by AndriyNesterenya** [comment]
В нових рпераціях нема Довіреності в переліку
![image](https://user-images.githubusercontent.com/38098758/183891822-d3ca5645-c55f-47f1-973d-27883eb6dc9c.png)
В "застарілих" є.

**Comment by AndriyNesterenya** [comment]
Ім'я файлу при експорті _inventory_documents_power_of_attorney_power_of_attorney.pdf
Варто було б зробити Довіреність №ХХХ
