### ISSUE TITLE
[Пропозиція] додати на друковані форми для ФОП опціональне поле для віртуальної назви ТМ

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1552]
Прийшов запит від клієнта - додати можливість ФОПу мати на документах  додаткову назву.
Досить розповсюджена ситуація, коли організаційно в буккіпері ведуть умовного ФОП Зюбенко, і при цьому хочуть на рахунках/актах мати назву проекта, бренда, магазина, у випадку з Мішкою - OwlWeb Studio.
Як на мене - ідея непогана.

**Comment by MaksymTikhomirov** [comment]
Погоджуюсь. Часто ФОП є власником ТМ, яку хоче відображати на бланках. Ще один приклад - "Соната", ФОП Чорновус
