### ISSUE TITLE
[Bug] Не відображається ознака "Роздрібний" в списку складів

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1555]
В /inventory/catalogs зникла ознака (Тип) "Роздрібний"
![image](https://user-images.githubusercontent.com/38098758/178973419-6ce06b36-0911-4144-bec7-8864ac3d0eff.png)

Хоча галка в параметрах стоїть
![image](https://user-images.githubusercontent.com/38098758/178973507-0713410e-d54c-4f0d-8c11-9ddb0ad55c24.png)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Наразі при постановці галочки Роздріб у довіднику складів - Тип - Роздрібний відображається.
