### ISSUE TITLE
Акт звірки / Акт звірки по договору

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1557]
Запрос від клієнта: Акт звірки в прозрізі договорів
Але вирішили робити просто акт звірки та звірку по кожному договору окремо.

[АКТ ЗВІРКИ в розрізі договорів.xls](https://github.com/a2develop/bugTracker/files/9159305/default.xls)

**Comment by htrofymova** [comment]
Додала фільтр по договору. Тобто один договір = один Акт. НЕ один Акт по всіх (в розрізі) договорах.
