### ISSUE TITLE
Уведомление про принятие на работу: с 2022 года действует новая форма J3001002 — нужно обновить

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1560]
запрос клиента:
Форма J3001001 не експортується до Приватбанку, тому що вже не існує. Там форма для гіг-контрактів J3001002.

статья на дебет кредит, с ссылкой на форму
https://news.dtkt.ua/labor/labor-relations/73987-z-5-sicnya-dije-nova-forma-povidomlennya-pro-priinyattya-na-robotu

**Comment by htrofymova** [comment]
вже J3001003. Готово
