### ISSUE TITLE
 К операции Придбання об'єктів нематеріальних активів сделать оплату по кассе и по банку. В банковской выписке в списке оснований отображать и эту операцию.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1563]
В банковской выписке как основание он не выдается, в самой операции нет возможности прикрутить оплату. 
В статусах висит Очікує оплати

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
1.Так, у платіжному дорученні і банківській виписці можна обрати як Підставу цю операцію. 
2. З самого документу Придбання об'єктів нематураільних активів оплату не зробити. 
3. В касових ордерах така операція як Підстава не обирається.

**Comment by Anestezia** [comment]
Так, по касі також можна обрати цю операцію як документ-підстава, але не підтягується сума. Поле залишається пустим. У платіжці сума одразу підтягується.
