### ISSUE TITLE
В акті виконаних робіт, створеному на підставі рахунку, немає можливості після розпроведення відредагувати Проект. Поле не активне.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1566]
У попередніх періодах (2018-2021рр)створено та оприбутковано рахунок, на його основі акт виконаних робіт та платіжне доручення на оплату послуг постачальнику. Згодом було виявлено помилку, а саме невірно/не зазначено проект. Щоб її виправити було розпроведено весь пакет документів. У рахунку на оплату проект є можливість змінити. У платіжному дорученні змінити проект можна після видалення підстави(рахунку) та повторного його заведення вже відкоригованого варіанту. У акті виконаних робіт можливості змінити проект не має. Можливо є якась технічна можливість це виправити?

1. Створено Рахунок - Оплату по банку- Акт. 
2. Розпроведено Рахунок - Оплату - Акт.
3. В рахунку проект відредаговано. 
4. В оплаті (по банку) поле Проект не редагується. В акті також. 
5. В оплаті є кнопка Видалити підставу. Після видалення Проект редагується вручну і також, якщо обрати заново підставу (відредагований рахунок), то проект наслідується з рахунку.
6. В Акті вказано Документ-підстава, але немає кнопки Видалити підставу.

Таке ж питання по Договору.

**Comment by htrofymova** [comment]
Проект (договір) успадковується з документа-підстави, тож взагалі не редагується. Якщо в документі-підстві проект (договір) змінили, то пов'язані документі не можуть цього "бачити", треба створити їх заново. Якщо вже такі маніпуліції з документами, то чи не простіше створити новий Акт? Можна, звісно, в Акті теж зробити "видалити підставу".

**Comment by Anestezia** [comment]
Просто в інших документах є така кнопочка, а в акті немає.
