### ISSUE TITLE
Лист-замовлення нюансы печати

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1569]
1. На печать выводится два варианта: Для військових і Для цивільних, а в экспорт идет только вариант Для військових.
2. Для друку - Посада в давальному відмінку по-разному отыгрывается в разных формах. Для військових - правильно, а для цивільних повинна бути в родовому. 
![Screenshot_81](https://user-images.githubusercontent.com/42540074/189491891-aa1886ef-6f25-4030-80e9-5d49e38170ae.png)
![Screenshot_79](https://user-images.githubusercontent.com/42540074/189491892-456eebbd-de48-4052-a2e9-98cfa48f44de.png)
![Screenshot_80](https://user-images.githubusercontent.com/42540074/189491894-5bc7248b-3c7d-4205-b9b6-3b334ee88562.png)
3. Опечатка в слове Одно/Одна в варианте для цивільних.
![Screenshot_76](https://user-images.githubusercontent.com/42540074/189491961-e9b6a471-a4d9-47b4-8467-db4c146e1be8.png)
4. В варіанті Для цивільних Бенефіціар на другій сторінці - наслідується повна назва замість скороченої. І не влазить.
![Screenshot_77](https://user-images.githubusercontent.com/42540074/189492104-3c2d67bc-e454-4403-a612-7643c6be2753.png)
5. У варіанті Для військових дивне формулювання, можливо, потребує уточнення.
![Screenshot_78](https://user-images.githubusercontent.com/42540074/189492253-2c1f9d59-e888-4bf2-8bc8-11a0a9850c56.png)

**Comment by Anestezia** [comment]
6. Номери розрахункових рахунків не тягнуться ні в нашого підприємтсва, ні в контрагента в обох документах. 
7. У варіанті Для цивільних замало місця для адреси.

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Чи існує форма Листа-замовлення для цивільних при друку? Зараз видається Акт.

**Comment by Anestezia** [comment]
Тут одразу всі питання знялись. Єдине маленьке: у формі листа є запрос одразу з назвою бенефіціару писати і код з адресою, в карточці контрагента є дані про ЕДРПОУ та адресу, але вони в лист не тягнуться.
  
![Screenshot_115](https://user-images.githubusercontent.com/42540074/193005632-0d26a42d-ebb5-4f05-a0a3-a84e8d4d2952.png)
