### ISSUE TITLE
Акт приймання-передачі благодійної допомоги - Друк

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1570]
1. Тільки один варіант при експорті документа. Для військових
2. Не вистачає місця для адреси та посади, не тягнеться номер розрахункового рахунку обох представників в обох документах.
![Screenshot_82](https://user-images.githubusercontent.com/42540074/189493696-a8ed3fc2-aae2-4c40-a0bc-f0cf31bfd74d.png)
3. Опечатка в слове Одно/Одна в обох варінтах.
![image](https://user-images.githubusercontent.com/42540074/189494004-403a4cfb-ce5d-47f2-a396-a132c63d00c9.png)

4. В обох варіантах  Бенефіціар на другій сторінці - наслідується повна назва замість скороченої. І не влазить. В варіанті для військових також не влізе  № військової частини, формування. 
![image](https://user-images.githubusercontent.com/42540074/189493991-83c0641e-c9c1-415b-8c7f-3176064b258e.png)
5.  Питання щодо розділу Благодійна допомога. Звернула увагу, що всі проведені документи все одно "Висять" у чернетках. Скажіть, будь-ласка, щось не закінчено по проводках?

Для кожного листа-замовлення я створюю акт прийому-передачі і провожу документи. Жодного третього кроку мені програма не пропонує, і документи висять у чернетках. 

![file_312](https://user-images.githubusercontent.com/42540074/189494398-d260ffe6-c297-4711-920a-b5fc7bbf480e.jpg)

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Ще момент: в обох формах актів таке формулювання: 
![Screenshot_112](https://user-images.githubusercontent.com/42540074/192996576-b11ff62f-b699-4406-8cc7-93025cb029f3.png)
2) У експорті все одно тільки одна форма надається. Для військових. Цивільна для експорту в ворд та ексель не доступна.

**Comment by Anestezia** [comment]
Також мало місця чи немає переноса для назви Благодійника. Якби вони помінялись місцями у прикладі, то назва би не влізла. 
![Screenshot_113](https://user-images.githubusercontent.com/42540074/192998149-06e1ab04-7b32-43b4-9ffb-ad35d7ea6135.png)
Те, що пишеться у вкладці Для друку в налаштуваннях - переноситься і на інші підприємтсва тенанту. Тобто потрібно постійно стежити та змінювати. 
![image](https://user-images.githubusercontent.com/42540074/192998476-636668eb-0b92-4fc4-9785-e2fc2bd95ad5.png)

**Comment by Anestezia** [comment]
Підписи переносяться на іншу сторінку , та благодійник - повна назва у вигляді для військових, а бенефіціар - скорочена.  Може благодійнику теж скорочену назву ?
![Screenshot_114](https://user-images.githubusercontent.com/42540074/192999593-4a7bf4b0-08c3-4724-8272-a177a84e42c1.png)
