### ISSUE TITLE
Нарахування податків - Деталізація - питання

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1571]
Питання: роблю нарахування податків за 3 квартал по фоп, ставлю дату документа 30.09.22, а деталізація йде по 29.09.22?

Щось із завданим періодом по кнопці Деталізація. Зайшла в обраний період у вже сформованому звіті, було вказано Поточний квартал. 
Натиснула кнопку Оновити, скинуло на 01.01.22, а потім тут же в періоді, не виходячи зі звіту знову обрала Поточний квартал. Видало вже 01.07.22-30.09.22. 
При повторному натисканні на Оновити дата не змінюється. Залишається період 01.07.22-30.09.22.

Якщо в налаштуваннях фірми вказано фоп 2%, то в Нарахуванні податків розраховується помісячно. Наприклад, 31.07.22 дата документа, Розраховується за 07 місяць. А деталізація йде за квартал
![image](https://user-images.githubusercontent.com/42540074/189640660-ba203eb6-bc9f-49a5-ad7f-6a105f0892f9.png)

**Comment by htrofymova** [comment]
полагодила
