### ISSUE TITLE
не створюється другий - кінцевий акт на підставі рахунку, з якого спочатку були реалізовані послуги частково

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1572]
кейс: выставляю счет на услуги , на основании счета оплату и реализацию - акт (не на всю сумму). потом создаю еще одну реализацию, чтоб закрыть сумму счета, а программа выдает такое
![image](https://user-images.githubusercontent.com/38099938/190397091-5d34fbdf-f8a8-45d6-b662-b779f7371cd2.png)

**Comment by Anestezia** [comment]
А кількість послуг розбили відповідно до суми? Наприклад, у першому акті 0,2 послуги, і в другому акті 0,8 послуги.

**Comment by kattrina-brekhova** [comment]
сума першого акту менша ніж сума рахунку
на другий акт видає таку помилку

**Comment by htrofymova** [comment]
так і є, тобто Настя права! Кількість теж треба розділити

**Comment by Anestezia** [comment]
Так, не важливо, менша сума чи більша, а справа в кількості. Ділити відповідно до бажаної суми акта, і можна створвати декілька актів до самого закриття. Пізніші акти самі праставляють дробний залишок кількості.
