### ISSUE TITLE
ліквідація ОЗ та оприбуткування матеріалів після ліквідації ОЗ - неправильні рахунки 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1577]
При списанні ОЗ в програмі робиться проведення Дт 91 Кт 106, а вже потім на 23. 
Це методично не вірно. Згідно інструкції про використання плану рахунків використовується рахунок 976 «Списання необоротних активів» відображається залишкова вартість списаних необоротних активів та витрати, пов’язані з їх ліквідацією (розбирання, демонтаж).

![image](https://user-images.githubusercontent.com/38099938/192288293-98cd3a52-13f4-434a-8c63-7a17f38cc4fc.png)

![image](https://user-images.githubusercontent.com/38099938/192288360-d01dde43-cc02-42c2-8b47-633c6dd07c46.png)

рахунок (91) тягне з картки ОЗ, якщо проставити, наприклад, 93, то використаний буде він

![image](https://user-images.githubusercontent.com/38099938/192288536-f5e77a9d-860c-4513-a5c6-e8afcfeedb72.png)

Але вірно має бути так: Списання здійснюється з використанням субрахунку 976 «Списання необоротних активів». Виглядає це таким чином:

списання ОЗ у частині залишкової вартості (ЗВ) – Дт 976 Кт 10х;
списання ОЗ у частині накопиченого зносу (амортизації) – Дт 131 Кт 10х.

Крім того під час ліквідації утворюють запаси (цегла, металобрухт). Вони оприбутковуються Дт 209 Кт 746. В акті оприбуткування дає тільки 719 рах. 

Потрібно змінювати, доопрацьовувати

Звернулась викладач з універу, вважаю, що для навчання такі проводки не можемо давати для засвоєння студентам

**Comment by htrofymova** [comment]
то в нас помилка була :( 
виправила. 746 рахунок додала

**Comment by kattrina-brekhova** [comment]
дякую
