### ISSUE TITLE
звіти по проектах по 92 и 949 счетам - просят клиенты

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1578]

**Comment by htrofymova** [comment]
Додала фільтр Проект до звіту Реєстр документів, який є для всіх рахунків. Також підключила для 92 та 949 звіт Оборотна відомість по проектах. ОСВ по дебіторам-кредиторам вже мають фільтр проект.

**Comment by Anestezia** [comment]
Супер!!! Є.  фільтр просили сльозно і по 311. Є!
