### ISSUE TITLE
При изменении оклада не с начала месяца, а в середине, все дни месяца зарплаты считаются уже по новому окладу

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#158]
![photo_2018-05-16_16-00-31](https://user-images.githubusercontent.com/38099938/40118454-aaf0fc0c-5922-11e8-8055-dec88d5ef550.jpg)
![photo_2018-05-16_16-00-59](https://user-images.githubusercontent.com/38099938/40118455-ad022d90-5922-11e8-9551-ed0f9aa49a97.jpg)

**Comment by Illya-Lykhachov** [comment]
Так и есть, при расчёте зарплаты мы берём значение оклада на конец месяца. По другому **пока** не получится - нет табеля выходов, а без него мы не можем точно сказать сколько дней отработано по старому окладу, а сколько по новому.
Для простой зарплаты, которая решается одним документом "Расчётная ведомость", есть только один вариант - запретить менять оклад и перемещение на другую должность в середине месяца, только с первого числа.
Для полноценной реализации потребуется документ "Табель выходов" (иначе не определить кол-во дней работы по старому окладу и новому) и начисление повременной зарплаты и расчёт обязательных удержаний и начислений на ФОТ придётся проводить разными документами (в начислении 2 строки, а в удержаниях обязательно одна). Кстати, даже при полноценной зарплате пользователи крайне редко меняют значения тарифов в середине месяца (лишний геморрой).
Принимается к реализации вариант для простой зарплаты.

**Comment by kattrina-brekhova** [comment]
Ага, ясно... Ишью закрываю
