### ISSUE TITLE
Бухгалтерська довідка: курсові різниці дохід, 632, 362 рахунок

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1585]
Кейс:
оприбуткували товар від імпортера, на суму 1000євро, за умовним курсом 35 грн/євро. не оплачували
закриваємо квартал, на дату балансу робимо переоцінку кредиторської заборгованості
курс на 30/09 став нижчим, умовно 30 грн/євро
тобто маємо заплатити менше, у нас виникає дохід, проводка Д632 - К714
![image](https://user-images.githubusercontent.com/38099938/195551676-e8fdd787-b127-4658-8562-bdc8d4a82bc2.png)

в рядку "офіційний курс грн за 1 євро" автоматично виставився із довідника на дату операції
в ряку "сума в валюті" вказує суму операції в валюті
в рядку "сума" маю вказати суму першої операції (оприбуткування товарів) за курсом, який діяв на дату оприбуткування 
![image](https://user-images.githubusercontent.com/38099938/195552308-1758bebc-50f0-44c9-a9d8-80e6d8b30e14.png)

5 000 гривень мало потрапити в дохід, але у нас підсвічується червоним

спробуємо з 362 рахунком
тут правильно підсвічується, бо справді у нас витрати виникають (оскільки курс зменшився, ми відвантажили товари на суму 35 000 грн, а нам заплатять лише 30000), тому правильним буде так, і в нас 362 рахунок працює
![image](https://user-images.githubusercontent.com/38099938/195552994-9f3825e6-f519-4073-9b2a-935b1c4ab3ae.png)

спробую погратися, якщо курс виріс
наприклад, оприбуткували імпортрий товар на суму 35 000 грн (1000 доларів), на дату балансу курс виріс до 40 грн/долар
отже ми маємо заплатити на 5 000 гривень більше, в нас витрати
з цією операцією по 632 рахунку все добре
![image](https://user-images.githubusercontent.com/38099938/195554026-84112994-3f15-422a-88a3-3045e55e929d.png)

а ось з 362 рахунком в кейсі, коли ми продали товар, нам не заплатили, а курс виріс, то ми маємо отримати більше грошей, і це буде нашим доходом - теж наплутано в системі, і воно не працює
дивіться, курс на дату балансу 40 грн/долар
курс долара на дату відвантаження товару 35 грн/долар
тож дебіторська заборгованість збільшилась на 5 000 грн, ми маємо збільшити 362 рахунок і повісити за кредитом цю суму на 714 рахунок
але підсвічується червоним
![image](https://user-images.githubusercontent.com/38099938/195555664-34a36b50-c2aa-4dbe-99de-2dbb025a3e90.png)

отже, в програмі не працює два кейси:
1. курс валюти зріс, і ми маємо відобразити наші доходи за 362 рахунком
2. курс валюти знизився і ми маємо відобразити доходи за 632 рахунком

**Comment by htrofymova** [comment]
готово.

**Comment by kattrina-brekhova** [comment]
працює, дякую
