### ISSUE TITLE
Додати 280 адвокатське об'єднання до довідника організаційно-правових форм/оновити класифікатор

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1586]
![image](https://user-images.githubusercontent.com/42540074/196151462-346024fd-b7ab-404d-9fd1-2f10a4c9c017.png)
https://www.olza.com.ua/zakon_kopfg

**Comment by htrofymova** [comment]
додала

**Comment by Anestezia** [comment]
280 є, а 281?

**Comment by Anestezia** [comment]
280 Адвокатське об’єднання

281 Адвокатське бюро
321 Житлово-будівельний кооператив**)

322 Гаражний кооператив**)
415 Судова система
950 Садівниче товариство**)

* Чинним законодавством не передбачається створення та державна реєстрація нових підприємств та організацій з такими організаційно-правовими формами            

** Державна реєстрація нових юридичних осіб з такими організаційно-правовими формами не передбачається

**Comment by Anestezia** [comment]
280, 281, 415 є.
