### ISSUE TITLE
Інвентаризація - внесення списком

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1589]
Запаси - Інвентаризація - Додати списком - Ці позиції відсутні на вказаному складі, окрім Zara - Провести
![image](https://user-images.githubusercontent.com/42540074/199020001-4d533298-1077-428d-835f-9f636432b657.png)
Після проведення додаються ще позиції, всі, які є на вказаному складі, а не тільки ті, які обрав користувач. Обрані користувачем позиції також присутні, хоча вони і не з цього складу. 

![Screenshot_34](https://user-images.githubusercontent.com/42540074/199022169-92dbedb0-b527-4ac8-bf1d-41c9c7e7bdfb.png)
Ось що на складі: На сьогодні там тільки автомобілі.
![image](https://user-images.githubusercontent.com/42540074/199022474-78b0fae5-1231-4fd3-bf4a-19b7c1f39143.png)
![image](https://user-images.githubusercontent.com/42540074/199024677-63e5db81-4053-4007-8d45-065f4b0bde2d.png)
Склад обов'язковий для заповнення. І з нього тягнуться залишки. А взагалі користувачу потрібно не всі об'єкти вносити, а тільки з обраної групи.

**Comment by htrofymova** [comment]
готово,Треба перевірити
