### ISSUE TITLE
Додати колонку Код ІПН/ЄДРПОУ в список Податкових накладних або при експорті файлом

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1592]
![image](https://user-images.githubusercontent.com/42540074/200375386-bf99dbae-86e6-45c8-adc7-7fc7c0419915.png)
![image](https://user-images.githubusercontent.com/42540074/200375489-c70f7b88-233f-4793-a021-b65f4967b28e.png)
Це потрібно для звірки при заповненні декларації ПДВ та додатків, де пишуться не назви контрагентів, а коди.

**Comment by htrofymova** [comment]
додала при експорті в Excell.
