### ISSUE TITLE
Вид робочого часу Відрядження

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1593]
Відповідно до ст. 121 КЗпП працівникам, які направляються у службове відрядження, оплата праці за виконану роботу здійснюється відповідно до умов, визначених трудовим або колективним договором, і розмір такої оплати праці не може бути нижчим середнього заробітку.

До денного заробітку працівника, який має порівнюватися із середньоденним заробітком, при оплаті періоду відрядження включаються всі елементи зарплати, які працівник отримує згідно з умовами трудового, колективного договору у місяці, у якому його направляють у відрядження: оклад, доплати, надбавки, премії, індексація тощо. Допомога у зв'язку з тимчасовою непрацездатністю, період коли за працівником зберігається середня зарплата відповідно до законодавства, не включається до денної заробітної плати працівника при порівнянні.

Мінсоцполітики в листі від 26.07.2018 р. №142/0/103-18 також повідомляє, якщо робота працівника у святковий (неробочий) день провадилася за змінним графіком, тобто в межах місячної норми робочого часу для цього працівника, оплата проводиться у розмірі одинарної годинної або денної ставки понад оклад.

У випадку, коли працівника наказом (розпорядженням) по підприємству залучали до роботи у святковий (неробочий) день у його вихідний день, тобто понад місячну норму, оплата праці в цьому випадку проводиться у розмірі подвійної годинної або денної ставки понад оклад.

Згідно зі ст. 62 КЗпП надурочними вважаються роботи понад встановлену тривалість робочого дня (ст. 52, 53 і 61 КЗпП).

При цьому слід зазначити, що обчислення середньої заробітної плати у випадках службових відряджень передбачається у пп. «ж» п. 1 Порядку №100.

У абз. 3 п. 2 Порядку №100 зазначено, що в усіх інших випадках збереження середньої заробітної плати (крім, відпусток) середньомісячна заробітна плата обчислюється виходячи з виплат за останні 2 календарні місяці роботи, що передують події, з якою пов'язана відповідна виплата. Працівникам, які пропрацювали на підприємстві, в установі, організації менше 2-х календарних місяців, середня заробітна плата обчислюється виходячи з виплат за фактично відпрацьований час.

![Screenshot_6](https://user-images.githubusercontent.com/42540074/201075275-3b7e9e9f-5abf-474f-82e6-a0f48b504ea7.png)

Відповідно до пп. «в» п. 4 Порядку №100 при обчисленні середньої заробітної плати у всіх випадках її збереження згідно з чинним законодавством не враховуються компенсаційні виплати на відрядження і переведення (добові, оплата за проїзд, витрати на наймання житла, підйомні, надбавки, що виплачуються замість добових).

Крім перелічених у цьому пункті виплат, при обчисленні середньої заробітної плати за останні два місяці, також не враховуються виплати за час, протягом якого зберігається середній заробіток працівника (за час виконання державних і громадських обов'язків, щорічної і додаткової відпусток, відрядження тощо) та допомога у зв'язку з тимчасовою непрацездатністю.

Отже, у разі відрядження такого працівника у квітні 2019 р. з розрахункового періоду, у якому теж було відрядження, що оплачувалося за середньоденним заробітком, для обчислення середньоденної зарплати за два місяці не враховуються оплата за дні відрядження, що оплачувалися за середнім заробітком, та дні відрядження (вони виключаються з розрахункового періоду).

![Screenshot_7](https://user-images.githubusercontent.com/42540074/201075542-a907b7bc-f641-4c26-8d12-9752d9ed8260.png)

**Comment by Anestezia** [comment]
https://www.uhy-prostor.com/blog/oplata-za-dni-vidryadzhennya/

**Comment by htrofymova** [comment]
додала в Додаткові нарахування можливість ввести суму оплати у відрядженні вручну.
