### ISSUE TITLE
Лікарняний лист: не работает кнопка Провести

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#160]
![photo_2018-05-17_10-44-48](https://user-images.githubusercontent.com/38099938/40163438-7734b9ba-59bf-11e8-91d9-6df710cc3e2d.jpg)

**Comment by Illya-Lykhachov** [comment]
Так там же валидаторы красные. Сначала нужно исправить ошибки.
В приведенном случае дата больничного листа не может быть раньше даты окончания болезни. Больничный, как правило, оформляется при выписке. Хотя в последнем могу ошибаться.
В любом случае проблема не в самом проведении, а в правильности бизнес-логики документа

**Comment by kattrina-brekhova** [comment]
ой, точно... спасибо!
