### ISSUE TITLE
Фінансовий звіт мікропідприємтсва S0111006: проблема при імпорті в ЕК не подача через помилку невірний кода КОТАТТГ

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1606]
компанія зареєстрована в Печерському районі києва, в буккіпері в звіті підтягую відповідний код (цей код відповідає і тому коду, який пропонує ЕК
відповідно назва файлу формується з перший цифр
кабінет не приймає і каже, що невірний код КОТАТТГ

при створенні звіту чере ЕК вручну назва файлу інша, звіт прийнято

**Comment by htrofymova** [comment]
назва інша, але яка саме?

**Comment by kattrina-brekhova** [comment]
ось КАТОТТГ через ЕК

![photo_2023-01-17_17-28-26 (2)](https://user-images.githubusercontent.com/38099938/230412060-a6a55a7a-dd82-4983-bd6f-aab02d3aa9a2.jpg)

такий же вказали і в звіті в Буккіпер

UA80000000000624772

По фінансовому звіту мікропідприємства допускаю що проблема в самій зашифрованиій назві xml файлу, що в буккіпері 

![photo_2023-01-19_17-52-45](https://user-images.githubusercontent.com/38099938/230413120-c5ab5da7-1103-47eb-9618-2e201ae4fd77.jpg)

знаходила таку інформацію і перевіряла яку назву файлу формую БК і яку назву формує ЕК

ось файлу звіту назва з ЕК 26550044906233S0111006100000000451220222655

ось назва файлу звіту з БК 803610044906233S011100610000001122022

що підтягує в перші цифри назви звіту ЕК - може це статистика?

заповнювала звіт в ЕК вручну всіма тими ж даними, що і в БК, і вказувала той же КАТОТТГ - єдина відмінність у назві файлу

В ЕК дійсно формує з іншою назвою - якимось іншим територіальним кодом, чи що, не розумію

якщо потрібно - вишлю обидва звіти з ЕК і з БК

**Comment by kattrina-brekhova** [comment]
звіт не приймало через таку помилку 
![photo_2023-01-17_18-02-31](https://user-images.githubusercontent.com/38099938/230416355-60a7cc4f-47c3-4514-91ad-d8f0cfe2a804.jpg)

**Comment by kattrina-brekhova** [comment]
в цьому році звіт через кабінет податкової прийнято
