### ISSUE TITLE
помилка з нормою амортизації НА при модернізації

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1611]
проходжу кейс по одному з наших клієнтів
облік НА
31.12.2021 ввели в евсплуатацію НА на суму 240 000, строк корисного використання - 12 місяців, відповідно помісячня амортизація - 20 000
в січні та лютому нараховують амортизацію, 20 000
буккіпер рахує все правильно
в березні проводять поліпшення, на 60 000
в цьому місяці амортизація має нараховуватись в сумі первісної вартості (без врахування поліпшення), 20 000, буккіпер рахує правильно
але з квітня амортизація має нараховуватись із врахуванням цього поліпшення
тобто 240 000 - 60 000 (амортизація за 3 місяці) + 60 000 (поліпшення) = 240 000 / 9 (місяці використання, що залишились) = 26 666,66

але буккіпер вказує амортизацію 25 000

так не має бути

у нас термін корисного використання 12 місяців
нарахована сума амортизації 60 000
терімн ще не розрахованої амортизації 9 місяців
давайте порахуємо

240 000 (первісна) - 60 000 (амортизація за січень-березень) + 60 000 (модернізація) = 240 000

ліквідаційна вартість 0 грн
якщо ми будемо нараховувати амортизацію по 25 000, у нас за 9 місяців амортизація буде 225 000
тобто на кінцеь строку використання у нас ще залишиться 15 000 грн, і це ніяк не 0

https://dtkt.com.ua/school/ukr/2004/40/40sc1.html

https://consulting.dtkt.ua/state/other/8901

![image](https://user-images.githubusercontent.com/38099938/216291096-8c134073-2757-4695-a61c-bb4c91267a34.png)
![image](https://user-images.githubusercontent.com/38099938/216291251-b7e79b6e-705f-494a-83ea-de34c95f1791.png)

**Comment by kattrina-brekhova** [comment]
також потрібно проконтролювати суму амортизації, якщо такі НА були введені початковим балансом і в них ще залишився термін використання

**Comment by kattrina-brekhova** [comment]
в картці початкового балансу через те, що немає дати введення в експлуатацію також застосовується такий принцип амортизації

я ввела в балансову вартість первісну вартість + суму модернізації (240 000 + 60 000) і нараховану амортизацію за 3 місяці (60 000)

за логікою минулого приклада, амортизація мала б бути 26 666,67, буккіпер рахує 25 000

![image](https://user-images.githubusercontent.com/38099938/216547368-595bc1f6-d954-47e4-95cb-6dc1b47e8907.png)


![image](https://user-images.githubusercontent.com/38099938/216547267-6bbf5b45-d862-4e67-b9b3-8a97b2ba09fe.png)

**Comment by kattrina-brekhova** [comment]
перевіряю розрахунок амортизації
взяла такий самий кейс НА на 240 000, термін - 12 місяців, первісна амортизація по 20 000
в експлуатація з 31.12.2022
січень, лютий - амортизація по 20 000
в березні поліпшення на 60 000
амортизація (якщо об’єкт не виводиться з експлуатації, а я його не виводила), має йти в березні також на 20 000 і лише з квітня вже враховувати суму модернізації
в березні амортизація взала суму 20 000 та ще й всю суму поліпшення 60 000 = 80 000 

![image](https://user-images.githubusercontent.com/38099938/222384094-8d8553a8-a5d4-44d8-954c-bb6a2555299b.png)

**Comment by kattrina-brekhova** [comment]
перевіряла без кейса зміни терміну корисного використання в акті модернізації

**Comment by htrofymova** [comment]
виправила

**Comment by kattrina-brekhova** [comment]
так, в наступній відомості рахувало правильно
26 666,67
але я повидаляла нарахування амортизації за січень та лютий і видалила акт модернізації
натомість тепер січнем рахує неправильно, замість 20 000, бере 26 666,67
![image](https://user-images.githubusercontent.com/38099938/222491803-5f68ebef-50dc-41ce-b6ce-1b29015844e1.png)

тобто по суті крім введення в експлуатацію зараз нічого немає по цьому обєкту
![image](https://user-images.githubusercontent.com/38099938/222492084-c64d2d0b-a8df-4fbb-822d-059351b8efbb.png)
