### ISSUE TITLE
розрахунок лікарняних: в базу нарахованих сум для розрахунку середньоденної не мають потрапляти лікарняні

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1636]
Виплати, які не входять до фонду оплати праці (наприклад, лікарняні, декретні, разова матеріальна допомога, добровільне медстрахування), у розрахунку лікарняних участі не беруть.
https://buhplatforma.com.ua/article/8643-rozrahunok-lkarnyanih-u-2021-rots#:~:text=%D0%92%D0%B8%D0%BF%D0%BB%D0%B0%D1%82%D0%B8%2C%20%D1%8F%D0%BA%D1%96%20%D0%BD%D0%B5%20%D0%B2%D1%85%D0%BE%D0%B4%D1%8F%D1%82%D1%8C%20%D0%B4%D0%BE,%D0%BF%D0%BE%D1%82%D1%80%D0%B0%D0%BF%D0%B8%D0%BB%D0%B0%20%D0%B4%D0%BE%20%D0%B1%D0%B0%D0%B7%D0%B8%20%D0%BD%D0%B0%D1%80%D0%B0%D1%85%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F%20%D0%84%D0%A1%D0%92.

перевірила кейс
нарахувала повний місяць хвороби
![image](https://user-images.githubusercontent.com/38099938/229820406-1c3e5268-b32a-4562-80a7-88362e0c204f.png)

нарахувала лікарняні
![image](https://user-images.githubusercontent.com/38099938/229820565-1902547e-ee6d-4cc9-bfe6-88e8cc807e25.png)

![image](https://user-images.githubusercontent.com/38099938/229820666-2b613948-435d-42ab-98a4-bf2c8bfd4c36.png)

в наступному місяці знов хвороба
![image](https://user-images.githubusercontent.com/38099938/229820786-814c4b53-792b-4a2f-a9eb-3cd303599724.png)

до розрахунку лікарняних потрапила сума лікарняних попередніх періодів, не мала б
![image](https://user-images.githubusercontent.com/38099938/229821081-1557f059-d933-4568-902f-2a83afd534a3.png)

**Comment by kattrina-brekhova** [comment]
перевіряю на дев, все одно в бзу потравляють лікарняні
![image](https://user-images.githubusercontent.com/38099938/230911924-7364c263-4b52-4053-b17a-681959af8b03.png)

**Comment by kattrina-brekhova** [comment]
https://zakon.rada.gov.ua/laws/show/1266-2001-%D0%BF

у розрахунок лікарняних не входять календарні дні, не відпрацьовані з поважних причин, - тимчасова непрацездатність, відпустка у зв’язку з вагітністю та пологами, відпустка для догляду за дитиною до досягнення нею трирічного віку та шестирічного віку за медичним висновком, відпустка без збереження заробітної плати, призупинення дії трудового договору у зв’язку з військовою агресією Російської Федерації проти України. це якщо коротко. винятків для днів за рахунок підприємства немає

всі ньанси розписані в цій постанові. в тому числі те, що я скинула - це пункт 3

**Comment by htrofymova** [comment]
виправила

**Comment by kattrina-brekhova** [comment]
дякую
