### ISSUE TITLE
Запасы. Ввод вступительных остатков. Отсутствует.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#164]

**Comment by AlexeyTishkin** [comment]
Для товара сделал. Запасы - Початковий баланс.
Уточняю: тестируем на dev, на azure появится в ближайшем релизе.

**Comment by nik-man** [comment]
Да, для запасов работает.
Еще надо для бух.счетов и расчетов с контрагентами.
Делать новый ишью?

**Comment by AlexeyTishkin** [comment]
Я думаю, что да. По разделам.
