### ISSUE TITLE
об’єднаний звіт для роюотодавців: є проблеми з автоматизацією розрахунків і нарахувань

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1647]
1. титульна частина звіту: не виокремлюються доходи інвалідам.
зокрема, маю нарахування за квітень, 1 інвалід
![image](https://user-images.githubusercontent.com/38099938/235890121-fca88a67-cc4a-4862-ac8f-52e9c37dc5fd.png)
загальна сума за документом 85 000
отут мало би бути таке відображення
![image](https://user-images.githubusercontent.com/38099938/235890341-d851d23e-17f1-43ea-a92a-7d193fc7c064.png)

рядок 2 - 85 000
рядок 2.1. - 74 000
рядок 2.2 11 000 - (інвалід)

2. додаток 1. не разповнює код типу нарахувань (рядок 9).

**Comment by htrofymova** [comment]
стосовно 2. код типу нарахувань заповнюється згідно цього: https://zakon.rada.gov.ua/laws/show/z0111-15#Text
