### ISSUE TITLE
Регистрация. Имя попадает в поле емейла.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#165]
Сразу после регистрации при первом входе
на странице Входа,
автозаполнение подставляет в поле "Email" значение из поля "Ім'я"

![2018-05-18](https://user-images.githubusercontent.com/35918141/40240846-35bdc2c0-5ac2-11e8-92b1-5b5e2f4206d6.png)

**Comment by AndriyNesterenya** [comment]
Вроде уже исправлено? Регистрился на beta - правильно предложило запоминаться.

**Comment by MaksymTikhomirov** [comment]
Нет, все так же глючит. Только что проверено.

**Comment by nik-man** [comment]
![2018-05-21 2](https://user-images.githubusercontent.com/35918141/40309843-a192ad8c-5d13-11e8-8cca-57cd633c5067.png)
Проверил еще раз. Браузер подхватывает поле "Имя" как логин.

**Comment by nik-man** [comment]
Может это чем-то поможет -- страница Входа воспринимается правильно.
![2018-05-22 ok](https://user-images.githubusercontent.com/35918141/40352766-68c7b43e-5db8-11e8-9d0a-30a8575b38a8.png)
