### ISSUE TITLE
В рецептуру і, як наслідок, в Виготовлення додати у таблиці Готова продукція та Матеріали 10 знаків після коми у поле Кількість.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1651]
![Screenshot_103](https://github.com/a2develop/bugTracker/assets/42540074/f18b4250-c4ce-4a8f-9c19-a51602e9d872)
![Screenshot_104](https://github.com/a2develop/bugTracker/assets/42540074/ed1899b9-b03e-4c58-88da-9a55959d61fe)
![Screenshot_105](https://github.com/a2develop/bugTracker/assets/42540074/984e7bd9-2646-4296-bb26-6e36029427d4)
 
Також зробити це відображення на друку та в експортованих файлах.

**Comment by htrofymova** [comment]
пропозиція: вести облік в дрібних одиницях виміру.
