### ISSUE TITLE
Накладна на вивантаження на основі видаткової накладної

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1662]
Просять дати можливість на основі видаткової накладної створювати таку собі Накладну на відвантаження з складу, яка фактично повторює видаткову, але не містить інформації про вартість.

Для повного щастя можна додати "Всього найменувань: ХХ" щоб комірник не провтикав.

**Comment by AndriyNesterenya** [comment]
В принципі вже ОК.
Для повного щастя хочуть в header'і ше й Постачальника перед отримувачем, щоб можна було в руки отримувачу дати

**Comment by htrofymova** [comment]
готово

**Comment by AndriyNesterenya** [comment]
Для повного щастя не вистачає 
Можливості не тільки надрукувати, а ще й експортувати.
і назви файлу експорту для цьієї форми замість "Видаткова накладна № Х" щось типу "Накладна на відвантаження № Х"

**Comment by htrofymova** [comment]
готово
