### ISSUE TITLE
Лист-замовлення на благ. допомогу - Просять форму для цивільних.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1673]
![Screenshot_43](https://github.com/a2develop/bugTracker/assets/42540074/0d676e72-e834-498c-aa69-fef07617b8c4)

**Comment by Anestezia** [comment]
![Screenshot_50](https://github.com/a2develop/bugTracker/assets/42540074/e8667b10-b656-4e1f-ac84-0aeb2ceaf140)

**Comment by htrofymova** [comment]
надайте зразок Листа для цивільних
