### ISSUE TITLE
З картки контрагента не тягнуться паспортні дані у лист-замовлення благ. допомоги, хоча вони заповнені

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1674]
![image](https://github.com/a2develop/bugTracker/assets/42540074/a68f9c15-706f-4e51-b874-4f5b21f0312f)
![image](https://github.com/a2develop/bugTracker/assets/42540074/a3c41412-47a0-41b0-acb3-04e369b64e09)

**Comment by Anestezia** [comment]
![Screenshot_49](https://github.com/a2develop/bugTracker/assets/42540074/faf446d1-55c0-4359-b7ea-bfe2c04d3c1e)

**Comment by htrofymova** [comment]
надайте зразок Листа для цивільних
