### ISSUE TITLE
Акт/накладна на фіз особу - прибрати "Платник податку"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#1679]
При формуванні акту виконаних робіт / накладної для фізичної особи в друковани
"Не є платником ПДВ
Є платником податку на прибуток на загальних підставах"
що брехня.

Варто прибрати цей текст для фіз осіб, контрагентів типу "Інше" і можливо нерезидентів.

**Comment by AndriyNesterenya** [comment]
Схоже, поламалося виведення даних про контрагента.

Було
![image](https://github.com/a2develop/bugTracker/assets/38098758/84df842d-f6c6-4f45-8237-2acecf942da9)

стало 
![image](https://github.com/a2develop/bugTracker/assets/38098758/02b5688d-d065-48e0-bd3c-2435e3192f96)

**Comment by AndriyNesterenya** [comment]
У звичайної юр особи:
Код ЄДРПОУ обізвано ІПН
зникла приписка про статус платника ПДІ/єдиного податку

**Comment by AndriyNesterenya** [comment]
У Фіз особи звичайної наче все ОК

А от для "Інше" можна прибрати ІПН
![image](https://github.com/a2develop/bugTracker/assets/38098758/cf5edfa8-34a3-43de-9e2a-3ebf736976a1)

**Comment by htrofymova** [comment]
виправила
