### ISSUE TITLE
Акт звірки з нерезидентами, в валюті чи в гривні.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1685]

**Comment by kattrina-brekhova** [comment]
може цей звіт краще назвати Акт звірки взаєморозрахунків з нерезидентами?
тому що дані в звіті виводяться в гривні
я не знаю, як просили клієнти - чи в гривні чи в валюті
хіба що якщо якби були стовпчики у валюті і в гривні - то назва б відповідала суті
