### ISSUE TITLE
Расходная накладная. Недостачи при списании. Чего не хватает?

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#169]
При проведении накладной с несколькимя строками, если чего-то из товаров не хватает, выдает сообщение "Кількість у документі перевищує кількість залишку".
Только непонятно какого именно товара.

Единственный способ выяснить это -- открывать весь список товара и сравнивать остаток в диалоге и кол-во в документе в каждой строчке.

Наверное, надо как-то указывать каких позиций недостаточно.

**Comment by AlexeyTishkin** [comment]
Переделал. Попробуй.

**Comment by nik-man** [comment]
Да, хорошо.
Только валидатор недостатка может оставаться для проведенного документа.
В тестовой базе расходная:
http://dev.a2start.com/document/waybill_out/edit/5963

![2018-05-23](https://user-images.githubusercontent.com/35918141/40422457-14ef89d2-5e98-11e8-9b18-5f6e89bc8915.png)

Было 30, успешно списано 17, осталось 13,
но валидатор думает, что мы хотим еще 17 продать.

**Comment by AlexeyTishkin** [comment]
Для проведенного исправил.

**Comment by nik-man** [comment]
Проверил. Ок.
