### ISSUE TITLE
Создание документа из списка Контрагентов. "Оплата в кассу" создается без возможности редактирования.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#17]
"Оплата покупця в касу"
"Оплата постачальнику из каси"
В отделах "Придбання" и "Продажі"
Документи создаются с полями, закрытыми для редактирования.

**Comment by AlexeyTishkin** [comment]
В разделе "Бухгалтерия" тоже. Интерфейс то общий.

**Comment by shevchuk-vadim** [comment]
Это было потому, что во все бухгалтерские документы не попадал вид операции при создании из контрагента и договора.
Исправлено, проверьте.

**Comment by nik-man** [comment]
Да, все ок. Спасибо.
