### ISSUE TITLE
Придбання. Контрагенти. Сброс фильтра не сбрасывает значение селектора.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#170]
![2018-05-21 -](https://user-images.githubusercontent.com/35918141/40306333-ecfea22e-5d06-11e8-95db-d2e700d7d9b4.png)

Список отображается правильно, без фильтра. А значение в селекторе остается.

**Comment by alex-kukhtin** [comment]
Fixed in 7203
