### ISSUE TITLE
Внутри системы желательно сделать чат поддержки пользователя.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#171]
Запрос на будущее.(капец мне)

Туда же можно вставить кнопку "Сообщить об ошибке"

Почему хорошо именно внутри системы? Чат будет знать, на какой странице находится пользователь и будет сразу информировать об это сотрудника техподдержки.
С одной стороны сотруднику будет легче понять, где у пользователя проблема,
с другой стороны -- можно собирать статистику, на каких участках больше всего вопросов.

Хотя и на продающем сайте тоже нужен чат.

В общем-то, чат будет в любом случае. Вопрос только какой и где. ))
Для начала хорошо бы прицепить самый простой (и ненавязчивый) в системе, просто оценить, насколько он востребован.

**Comment by MaksymTikhomirov** [comment]
+++
Пора начинать об этом думать
