### ISSUE TITLE
Розпізнавати аналітику по бухгалтерським довідкам - контрагент, співробітник. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1714]
Кейс: 1. Визнання доходів / витрат за рахунок фонду, контрагента вказано. 
2. Зробити звіт Реєстр документів по 482/483/484 рахункам з фільтром Контрагент.
3. Цю операцію не відображено у звіті.

**Comment by htrofymova** [comment]
Стосовно саме кейсу: Визнання доходів / витрат за рахунок фонду треба робити бухгалтерською довідкою на вкладці Бухгалтерська довідка (НЕ Вручну !!!), там для цього операції створені. Тоді все скрізь потрапляє.

**Comment by htrofymova** [comment]
В Реєстрі документів фільтр Контрагент присутній.

**Comment by Anestezia** [comment]
Так, є в реєстрі документів через План рахунків.
