### ISSUE TITLE
Учетная запись. Возможность сменить имя входа (емейл).

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#172]
Наверное, нужно будет сделать возможность сменить емейл с сохранением аккаунта.
Например пользователь зарегистрировался под емейлом "vatnik@mail.ru", а потом захотел изменить имя входа на "vishivatnik@ukr.net"

**Comment by AndriyNesterenya** [comment]
Имя входа (IMHO) менять незачем вообще.
мейлы, телефоны, имена - вполне может быть нужно.
Я в таком случае предложил бы отказаться от мейла в качестве логина.
Чуть более геморройно при регистрации (заставляем юзера придумать себе уникальный логин по каким-то правилам), зато потом мейлы, телефоны и все остальные атрибуты можно менять как угодно.

**Comment by alex-kukhtin** [comment]
Я против. Все (google, ms, facebook) уже давно отказались от логинов. Мейл подтвержден - он и есть логин. Можно еще сделать вход по номеру телефона, но он тоже должен подтверждаться через СМС.
