### ISSUE TITLE
У звітність не підтягується поштовий індекс з картки фірми

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1720]
![Screenshot_10](https://github.com/a2develop/bugTracker/assets/42540074/fce004ac-2960-4d38-b68a-c55dc98761ed)
![Screenshot_11](https://github.com/a2develop/bugTracker/assets/42540074/ecd0f842-1509-4533-abad-7792f5c09999)

**Comment by htrofymova** [comment]
Додала окрему властивість Індекс.
