### ISSUE TITLE
Нужен расходный кассовый ордер на выплату зп по Ведомости

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#174]
Любая выдача денег, в том числе и по Ведомости, закрывается ордером. Ведомость уже формирует проводки, как быть, чтобы они не двоились - я не знаю.
У меня был опыт, что мы ведомость проводили, а такой расходный ордер только сохраняли в программе и печатали

**Comment by Illya-Lykhachov** [comment]
В операции выдачи зарплаты, кроме печатного документа "Платёжная ведомость" добавлен документ "Расходный кассовый ордер"

**Comment by kattrina-brekhova** [comment]
а что с номерацией ордера? он подтягивает номер ведомости. но в кассовой книге номер должен быть следующим по расходным ордерам. и нет возможности редактировать номер

**Comment by Illya-Lykhachov** [comment]
сделаю связанный документ РКО

**Comment by nik-man** [comment]
А если зарплата выплачивается с расчетного счета на карту?

**Comment by kattrina-brekhova** [comment]
для этого реализована банковская операция "выплата зарплаты"
