### ISSUE TITLE
додаток 5 до об'єднаного звіту роботодавця: не змінюється і не піддається редагуванню взагалі поля іпн та піб посадових осіб

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1746]
<img width="746" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/2d2d7eeb-38ce-4c7d-9987-ff522bf8b1e0">

по іншим додаткам такого не спостерігається

**Comment by htrofymova** [comment]
підписи переносяться з головного звіта
