### ISSUE TITLE
акт/накладна на підставі рахунку, де не вказан проєкт: просять можливість активувати поле проєкт для вибору

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1749]
кейс наступний: отримують рахунок від постачальника, наприклад 2 оренди (складське та офісне приміщення). компанія веде облік витрат за проєктами (за вимогами псбо вони ці витрати фіксують за статтями - в нашому випадку ці статті витрат - проєкти). відповідно оренда складскього приміщення - це одна стаття витрат буде (один проєкт), а оренда офісного приміщення - інший.
для цього вони розмежовують ці витрати - і на підставі рахунку складають два акти, де хочуть вказати різні проєкти для такої аналітики. якщо в рахунку вказати один проєкт, то він буде в обох актах. але для цілей розмежування витрат їм це не підходить. а якщо не вказувати проєкт, то поле проєкт в акті не активне.

**Comment by htrofymova** [comment]
крім того, в режимі "Редагувати проведений" Проєкт можна змінювати у будь якому випадку
