### ISSUE TITLE
[Beta] При попытке провести начальный баланс ошибка "Could not find stored procedure 'a2.WaybillStart.Apply'."

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#175]
Пошел в Об’єкти обліку.
Добавил пару наименований.
Выбрал одно из наименований, вошел в Операции.
Выбрал "Початковий баланс" - работает, сохраняется.
При нажатии на "Провести" -  "Could not find stored procedure 'a2.WaybillStart.Apply'."

![image](https://user-images.githubusercontent.com/38098758/40448209-8803a62a-5edd-11e8-9e4e-9df6f296a2e7.png)

**Comment by AndriyNesterenya** [comment]
PS при этом добавить количество, сохранить, сохранить и закрыть получается без проблем. 
Но без Проведения на складе товар не появляется.

**Comment by AlexeyTishkin** [comment]
Будет исправлено в релизе 25/5.

**Comment by AlexeyTishkin** [comment]
Исправлено.
