### ISSUE TITLE
просять, щоб можна було виводити на друк в акті номер рахунку, на підставі якого був створений акт

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1752]
можливо, це якась позначка в акті - по типу виводити на друк рахунок (на кшталт колонтитулів та інформації в рахунку, що рахунок діє протягом 3 днів)

**Comment by kattrina-brekhova** [comment]
https://github.com/a2develop/bugTracker/issues/1743

**Comment by Anestezia** [comment]
В акті у нас є зайве поле, яке в ньому не потрібне. Може замінити його?

![photo_2024-02-14_15-48-13](https://github.com/a2develop/bugTracker/assets/42540074/2207bc8e-e153-4386-a6fb-e486ec1199b0)
![photo_2024-02-14_15-43-59](https://github.com/a2develop/bugTracker/assets/42540074/5b224e3d-28d0-4403-9085-d30eb717d4b8)
