### ISSUE TITLE
декларація з пдв: злетіло заповнення рядка 5, яке заповнюється на підставі експорту (послуг)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1755]
<img width="745" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/a6322ab1-e941-417d-9b0c-ac0092218c23">

заповнила вручну, минулий місяць заповнювалось автоматично

<img width="541" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/693c732f-2c9b-49ea-aabd-e9dc6e4c7f15">

**Comment by htrofymova** [comment]
ніколи не заповнювалось. Що має потрапляти?

**Comment by kattrina-brekhova** [comment]
значить мені здалось, що раніше заповнювалось
я беру з інвойсів (та певно треба і з митних декларацій), у яких пдв 0 з кодом 901
можливо ще й інші коди, я цього не знаю
може тоді поки на паузу, щоб не помилитись
