### ISSUE TITLE
покращення Розрахункової відомості

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1758]
1. в друковану форму Розрахункової відомості додати або колонку ІПН, або в колонку ПІБ, додати додаткову інформацію ІПН
обов’язковий для документів тривалого зберігання ІПН співробітника
можливо замість колонки посада, професія (як виходитиме)
<img width="713" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/99e677bb-976d-4282-b99c-9206f9635df1">

2.Хвороба ФССУ – Хвороба СС, Внесок
ФССУ замінити на ЄСВ. ФССУ на теперішній час не існує

<img width="759" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/299a2d08-87bf-436b-b04f-c8a24410a5bd">

3. При експортуванні Розрахункової відомості випадають дані колонки Відрядження,
тобто у файлі-ексель графа Відрядження пуста, незважаючи на те, що у вкладці
додаткові нарахування суми мають місце.
 (скрін 1)

4. у Наказі при прийнятті на роботу є реквізит: пільга з ПДФО
100%. Кожний працівник, як правило, має право за застосування цієї пільги і
застосування обмежується тільки розміром доходу. В об’єднаній звітності по ЗПЛ
ознака податкової пільги проставляється на базі цих даних НЕЗАЛЕЖНО ВІД ТОГО
БУЛА НАДАНА ЦЯ ПІЛЬГА ЧИ НІ. Але необхідно ознаку пільги проставляти тільки у
випадку ії фактичного надання. Такий підхід звісно використовується і при інших
ПСП

5. Велике прохання скасувати формат суми 8,666.72 у Відомості на поповнення
карткових рахунків. Такий формат з’являється при експорті в файл-ексель. Були б
дуже вдячні за можливість експорту даного файлу з двома колонками: ІПН (у
текстовому форматі) і сума (в числовому форматі, з двома цифрами після коми). Цей
файл в подальшому може бути використаний при імпорті у програму Клієнт-банк
Райффайзен.

6. Бажано також розділити графи Індексація і Премія, так як з 2024 року поновлено
обов'язковість нарахування індексації.

**Comment by htrofymova** [comment]
1, 2, 3, 5 - зробила.
4 - пільга в звіт так і заповнюється
6 - може пізніше - окреме ішью: створити окремі нарахвання індексація і премія, наразі це одне.

**Comment by kattrina-brekhova** [comment]
п. 2. так і залишилось ЄФСС
<img width="778" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/43ef63d1-8a94-4824-a639-13ad4b76b1da">

він не існує з червня 2023 року https://youcontrol.com.ua/catalog/company_details/40210180/

певно тут треба навіть не ЄСВ, а ПФУ https://wiki.legalaid.gov.ua/index.php/%D0%9D%D0%B0%D1%80%D0%B0%D1%85%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%BB%D1%96%D0%BA%D0%B0%D1%80%D0%BD%D1%8F%D0%BD%D0%B8%D1%85_%D0%BF%D1%80%D0%B0%D1%86%D1%96%D0%B2%D0%BD%D0%B8%D0%BA%D0%B0%D0%BC,_%D1%8F%D0%BA%D1%96_%D0%BF%D1%80%D0%B0%D1%86%D1%8E%D1%8E%D1%82%D1%8C_%D0%BD%D0%B0_%D0%BF%D1%96%D0%B4%D0%BF%D1%80%D0%B8%D1%94%D0%BC%D1%81%D1%82%D0%B2%D1%96_%D0%BC%D0%B5%D0%BD%D1%88%D0%B5_6_%D0%BC%D1%96%D1%81%D1%8F%D1%86%D1%96%D0%B2#:~:text=%D0%A1%D1%82%D1%80%D0%B0%D1%85%D0%BE%D0%B2%D1%96%20%D0%B2%D0%B8%D0%BF%D0%BB%D0%B0%D1%82%D0%B8%20%D1%82%D0%B0%20%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%20%D0%BF%D0%B5%D1%80%D1%88%D0%B8%D1%85,%D0%B7%D0%B0%20%D1%80%D0%B0%D1%85%D1%83%D0%BD%D0%BE%D0%BA%20%D0%9F%D0%B5%D0%BD%D1%81%D1%96%D0%B9%D0%BD%D0%BE%D0%B3%D0%BE%20%D1%84%D0%BE%D0%BD%D0%B4%D1%83%20%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8.

**Comment by kattrina-brekhova** [comment]
п. 4. не зовсім згодна
наприклад, Крівошеєв, 10 тис оклад
<img width="785" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/15804675-0d58-495e-b3a5-aa43dd93d6d7">

пільга в наказі
<img width="665" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/176ff07f-56fc-42bd-875c-6f3ca2c21641">

в розрахунок пільга не застосовувалась
<img width="755" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/bfa93b12-9507-47c1-8050-4e85af4ff9fd">

ознака пільги є
<img width="776" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/28381314-e048-47ac-a268-35f066b2fbf5">


а от в Колосенко не показана пільга 
<img width="749" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/90757c19-1bf1-45d5-ab3f-effedd28e363">
ось нарахування
<img width="803" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/cf5fad04-520b-4e5d-91d5-bad902abcf2a">

в наказі є пільга. наказів про зміну пільги нема
<img width="650" alt="image" src="https://github.com/a2develop/bugTracker/assets/38099938/18b05215-0be3-407c-a702-236281b6facc">
