### ISSUE TITLE
Кейс з нерезидентами в гривні

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1776]
Наразі маємо вихідні та вхідні платежі для нерезидентів по гривневим рахункам. 

Також ці платежі наразі неможливо прив'язати до документу-підстави.

На нерезидента можна виставити інвойс, та з нього можна зробити платіж тільки по 312 рахунку, у платіжці вибір операцій тільки по валютних. 

Стандартний рахунок на нерезидента виставити неможливо. Як і накладну. 

В гривневих платіжках для нерезидента немає можливості обрати за підставу виписаний інвойс.

**Comment by Anestezia** [comment]
Можливо, додати в інвойс як валюту, Гривню. При цьому з інвойсу можливість створити Оплату в валюті інвойса.

**Comment by htrofymova** [comment]
1. Платежі в гривні з нерезидентами проводяться по 362 тв 632 рахунках.
2. Інвойси можна обрати в якості підстави в таких платежах.
