### ISSUE TITLE
[Beta] Мелкий баг при создании оплаты из входящего счета (кривой номер счета в Підставі)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#179]
Создаем входящий счет, вводим реальный номер счета от поставщика.
Создаем оплату по банку из этого счета.
Оплата создается корректно, но в блоке "Підстава" справа выводится не реальный номер счета из самого счета, а по всей видимости порядковый номер документа в системе.

![image](https://user-images.githubusercontent.com/38098758/40535070-b43b15aa-6010-11e8-9373-615555c42e59.png)

![image](https://user-images.githubusercontent.com/38098758/40535079-bedaee86-6010-11e8-8396-a18e54e5f65b.png)

**Comment by AlexeyTishkin** [comment]
В счете номер - это строка. Любые символы.
