### ISSUE TITLE
[Предложение] В объектах учета и т.д. для ФОП на 5% устанавливать ставку ПДВ 0% по умолчанию.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#180]
Сейчас при создании нового объекта учета по умолчанию для всех товаров устанавливается Основная ставка 20% ПДВ.

Предлагаю: при создании объекта проверять 
1. Не ФОП ли создает 
и  
2. Галку НДСа в свойствах профиля 
и если это таки ФОП и при этом не плательщик ПДВ и 3% по умолчанию устанавливать 0%.

Признаки эти из экономии не проверять каждый раз, а держать в свойствах сессии (или как оно у вас там устроено).
Не принципиально, но если решится ценой  проверки пары условий - заметно экономит время.

**Comment by AlexeyTishkin** [comment]
Ставка в свойствах объекта не должна зависеть от того является плательщиком НДС "наше предприятие" или не является. Ставку 0% нужно устанавливать только для тех объектов, которые реально освобождены от НДС.

**Comment by shevchuk-vadim** [comment]
Согласен с Алексеем.

**Comment by AndriyNesterenya** [comment]
Понял, улетаю
