### ISSUE TITLE
Додати можливість обирати у якості підстави/створювати платежі на підставі Рахунку/Інвойса, по якому було повернення або часткове повернення оплати.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1809]
кейс на часткове повернення грошей. Тож по цьому інвойсу/рахунку вже не дає прикріпити інший платіж-доплату. Просять це пофіксити. Повністю замінити рахунок, по якому була перша оплата некоректно через те, що частина коштів по ньому таки пройшла.

Тож потрібна можливість зсередини рахунку/інвойсу робити ще один платіж/платежі та у банку використовувати на вкладці Додатково цей інвойс/рахунок як підставу для оплати.

**Comment by htrofymova** [comment]
зробила в рахунку. Вкладку Додатково у виписці - поки не чіпаємо
