### ISSUE TITLE
[Предложение] В оплате по банку автоматически заполнять реквизиты плательщика/получателя, если счет единственный

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#181]
При создании оплаты по банку можно сэкономить юзеру кучу времени, если подставлять автоматически реквизиты плательщика/получателя.

Однозначно имеет смысл, если счет единственный хотя бы у кого-то из участников.
Подставлять ли основной при наличии других - не уверен.

**Comment by shevchuk-vadim** [comment]
Чтобы счет подставлялся в документ, его нужно пометить, как основной. Это интуитивно непонятно?
Можно первый созданный счет автоматически помечать, как основной.

**Comment by AndriyNesterenya** [comment]
Пожалуй, это вполне годный метод.
Народ не заботится понятием основной счет, пока он единственный.
Как у своей фирмы, так и у контрагента.
Помечать первый счет основным с возможностью последующего изменения по мере добавления - вполне разумно.

**Comment by AndriyNesterenya** [comment]
НО!
В моем личном случае - у меня 1 счет и он помечен основным.
Реквизиты НЕ подставляются по состоянию на 25.05 версия 7196

**Comment by MaksymTikhomirov** [comment]
> Можно первый созданный счет автоматически помечать, как основной.

++++

**Comment by shevchuk-vadim** [comment]
При создании первого счета сделал установку признака "Основной".

Что касается "Реквизиты НЕ подставляются по состоянию на 25.05 версия 7196", то я не могу это воспроизвести. У меня при подстановке контрагента в платежное поручение (гривневое) основной счет подставляется.
В валютное платежное поручение никакой счет пока не подставляется.
