### ISSUE TITLE
Передивитись проводки для "Придбання необоротних активів за рахунок коштів цільового фінансування"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1823]
Доброго дня. 1.) При створенні "Прибуткової накладної" вибравши операцію "Придбання необоротних активів за рахунок коштів цільового фінансування" відображена некоректна проводка, а саме Дт15 Кт 484 замість Дт15 Кт631 (оскільки це була купівля товару за цільові кошти, а не безоплатно отримання/оприбуткування тобто проводки мають бути іншими).В дані статті https://avstudy.com.ua/tsilove-finansuvannya-dlya-pidpriyemstva-yak-oblikovuvati/ Витяг із статті : "Придбання основних засобів за рахунок цільового фінансуванняОдним з поширених направлень підтримки підприємств є цільове фінансування придбання основних засобів. Ми не будемо наразі окреслювати коло надавачів таких сум, а зосередимося на нюансах бухобліку цих операцій. Отримані цільові кошти підприємство відображає за Дт 311, 312 «Поточні рахунки в іноземній валюті» Кт 48 «Цільове фінансування і цільові надходження».Якщо цільове фінансування отримане в іноземній валюті, то для її перерахунку у гривневий еквівалент використовують курс НБУ на дату зарахування інвалютних сум (п. 5 НП(С)БО 21 «Вплив змін валютних курсів»).Витрати на придбання основних засобів, у тому числі МНМА, які включають до їх первісної вартості відповідно до п. 8 НП(С)БО 7 «Основні засоби») «збирають» за Дт 152, 153 у кореспонденції з кредитом відповідних субрахунків 20, 22, 66, 65, 631, 685 тощо. Введення основних засобів в експлуатацію відображають за дебетом рахунків 10 «Основні засоби», 11 «Інші необоротні матеріальні активи» Кт 152, 153.". Буду дуже вдячна якщо Ви операцію перейменуєте наприклад замість слова "Придбання" напишете "Оприбуткування" для правильності відображення купівлі товару в програмі.2.) Додайте в програмі можливість заводити 3х сторонні договори.3) Також додайте 3х сторонні накладні/акти,чи нову операцію по 3х сторонніх накладних/актах з подвійними проводками Дт6851 Кт631; Дт93 Кт 6851.Ваша програма Нам дуже сподобалась і ми хочемо стати Вашими новими клієнтами). Надіємся Ви допишете нові зміни в програмі. Дякую, Хорошого дня.

**Comment by kattrina-brekhova** [comment]
вважаю, що операцію придбання за рахунок цільового фінансування варто перейменувати в "оприбуткування"
і зробити ще одну операцію -  придбання, з рахунком 631 - "придбання за рахунок цільового...."
проводки при введенні в експлуатацію таких об'єктів обліку будуть ідентичні
