### ISSUE TITLE
особливості нарахування єсв для інвалідів в дія сіті + особливості нарахування єсв, якщо резидент не відповідає вимогам

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1827]
звернувся клієнт стосовно оподаткування Дія Сіті винагороди інваліду-співробітнику. Враховуючи те, що норми частини чотирнадцятої прим. 1 ст. 8 Закону № 2464 є імперативними щодо конкретного кола платників єдиного внеску – резидентів Дія Сіті, сплата єдиного внеску у разі дотримання вимог, визначених пп. 2, 3 частини першої, п. 10 частини другої ст. 5 Закону № 1667, здійснюються у розмірі мінімального страхового внеску, в тому числі за осіб з інвалідністю, які працюють у резидента Дія Сіті. При цьому мінімальний страховий платіж розраховується як добуток мінімального розміру заробітної плати на ставку єдиного внеску у розмірі 22 відсотка.програма розраховує ЄСВ з 8,41%, а повинна 22% з мінімалки

**Comment by kattrina-brekhova** [comment]
https://zak.tax.gov.ua/media-ark/news-ark/print-612559.html#:~:text=5%20%D0%97%D0%B0%D0%BA%D0%BE%D0%BD%D1%83%20%E2%84%96%201667%2C%20%D0%B7%D0%B4%D1%96%D0%B9%D1%81%D0%BD%D1%8E%D1%8E%D1%82%D1%8C%D1%81%D1%8F,%D0%B2%D0%BD%D0%B5%D1%81%D0%BA%D1%83%20%D1%83%20%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80%D1%96%2022%20%D0%B2%D1%96%D0%B4%D1%81%D0%BE%D1%82%D0%BA%D0%B0.

**Comment by kattrina-brekhova** [comment]
б) на суму винагороди фізичним особам за виконання робіт (надання послуг) за гіг-контрактами, укладеними у порядку, передбаченому Законом № 1667, – у розмірі мінімального страхового внеску.

При цьому мінімальний страховий внесок – сума єдиного внеску, що визначається розрахунково як добуток мінімального розміру заробітної плати на розмір внеску, встановлений законом на місяць, за який нараховується заробітна плата (дохід), та підлягає сплаті щомісяця (п. 5 частини першої ст. 1 Закону № 2464). Частиною п’ятою ст. 8 Закону № 2464 визначено, що єдиний внесок для всіх платників єдиного внеску (крім пільгових категорій) встановлюється у розмірі 22 відсотка.

Водночас, відповідно до частини тринадцятої ст. 8 Закону № 2464 єдиний внесок для підприємств, установ і організацій, фізичних осіб – підприємців, у тому числі тих, які обрали спрощену систему оподаткування, в яких працюють особи з інвалідністю, встановлюється у розмірі 8,41 відс. визначеної п. 1 частини першої ст. 7 Закону № 2464 бази нарахування єдиного внеску для працюючих осіб з інвалідністю.

Враховуючи те, що норми частини чотирнадцятої прим. 1 ст. 8 Закону № 2464 є імперативними щодо конкретного кола платників єдиного внеску – резидентів Дія Сіті, сплата єдиного внеску у разі дотримання вимог, визначених пп. 2, 3 частини першої, п. 10 частини другої ст. 5 Закону № 1667, здійснюються у розмірі мінімального страхового внеску, в тому числі за осіб з інвалідністю, які працюють у резидента Дія Сіті. При цьому мінімальний страховий платіж розраховується як добуток мінімального розміру заробітної плати на ставку єдиного внеску у розмірі 22 відсотка.

**Comment by kattrina-brekhova** [comment]
тобто сума єсв з інвалідів резидентів дія сіті = 22% * мінімальний розмір заробітної плати

**Comment by kattrina-brekhova** [comment]
Норми ч. 141 ст. 8 [Закону про ЄСВ ](https://zakon.rada.gov.ua/laws/show/2464-17#Text)є імперативними щодо конкретного кола платників єдиного внеску — резидентів Дія Сіті.

Сплата єдиного внеску в разі дотримання вимог, визначених пп. 2, 3 ч. 1 ст. 5 [Закону № 1667](https://zakon.rada.gov.ua/laws/show/1667-20#Text), здійснюються в розмірі мінімального страхового внеску (22 % від МПЗ), в тому числі за осіб з інвалідністю, які працюють у резидента Дія Сіті (див. [категорію 201.04.01 ЗІР](https://zir.tax.gov.ua/main/bz/view/?src=ques&id=12333)).

Отже, резидент Дія Сіті має нараховувати страховий платіж за працівника з інвалідністю в розмірі 22 % від МЗП.

Водночас резидент Дія Сіті, який у відповідний календарний місяць не відповідає вимогам, визначеним пп. 2, 3 ч. 1 ст. 5 [Закону № 1667](https://zakon.rada.gov.ua/laws/show/1667-20#Text), нараховує єдиний внесок працівникам, які у нього працюють, у розмірі 22 % на суму фактично нарахованої заробітної плати (винагороди).

Для осіб з інвалідністю єдиний внесок нараховується в розмірі 8,41 % на суму фактично нарахованої заробітної плати таким працівникам (див. [категорію 201.04.01 ЗІР](https://zir.tax.gov.ua/main/bz/view/?src=ques&id=12753)).

Отже, якщо у звітному місяці резидент Дія Сіті не відповідав вимогам, то ЄСВ слід нараховувати в розмірі 8,41 % на суму фактично нарахованої заробітної плати таким працівникам з інвалідністю.

**Comment by kattrina-brekhova** [comment]
https://ibuhgalter.net/ru/articles/1256#:~:text=%D0%92%D0%BE%D0%B4%D0%BD%D0%BE%D1%87%D0%B0%D1%81%20%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%20%D0%94%D1%96%D1%8F%20%D0%A1%D1%96%D1%82%D1%96%2C%20%D1%8F%D0%BA%D0%B8%D0%B9,%D0%BD%D0%B0%D1%80%D0%B0%D1%85%D0%BE%D0%B2%D0%B0%D0%BD%D0%BE%D1%97%20%D0%B7%D0%B0%D1%80%D0%BE%D0%B1%D1%96%D1%82%D0%BD%D0%BE%D1%97%20%D0%BF%D0%BB%D0%B0%D1%82%D0%B8%20(%D0%B2%D0%B8%D0%BD%D0%B0%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B8).

**Comment by kattrina-brekhova** [comment]
отже, якщо резидент дія сіті не відповідає вимогам - ставка єсв для працівників 22%. одночасно ставка єсв для інвалідів (в періоди, у яких резидент не відповідає вимогам) = 8,41%

**Comment by htrofymova** [comment]
Дадано відмітку на Розрахунковій відомості
