### ISSUE TITLE
[Beta] Баг :  Не сохраняется метка "Платник ПДВ" в свойствах контрагента.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#183]
Не сохраняется метка "Платник ПДВ" в свойствах контрагента.

Заполняем ИПН, ставим галку, выбираем дату
![image](https://user-images.githubusercontent.com/38098758/40577317-63323f9c-610c-11e8-9028-1dec517077fb.png)

Сохраняем/закрываем, повторно открываем - ни записи, ни галки нет
![image](https://user-images.githubusercontent.com/38098758/40577321-8778fcc4-610c-11e8-86ca-b5befdd24fd6.png)
Иногда при нажатии на "Сохранить и закрыть" виден красный значок ошибки на курсоре.

Попутно соображения :
1. Нормальному человеку нереально догадаться, что контрагенту нужно ставить признак плательщика НДС во вкладке про Регистрации...
ИМХО и ИПН и галку НДСника нужно выносить на видное место, желательно на первую вкладку свойств.
2. Дату регистрации контрагента нормальному человеку взять просто неоткуда (за исключением случаев смены статуса контрагентом в процессе).

**Comment by Illya-Lykhachov** [comment]
дату убрали, признак перенесли в визард
