### ISSUE TITLE
Нарахування відпускних за рахунок резерву відпусток, 471 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1839]
Просять у вид витрат у властивостях посади додати рахунок 471. Точніше, не в загальний список нарахування всієї ЗП, а тільки щоб відпустка окремо формувала проводку за цим рахунком. 
Або розмістити це у картці Фізособи у Персонал+ЗП.

**Comment by Anestezia** [comment]
![image](https://github.com/user-attachments/assets/8e9a3bd0-9115-4ee8-90fb-735b3fde0559)
Або сюди?

**Comment by htrofymova** [comment]
додано відмітку навкладці Відпустки документа Розрахункова відомість
