### ISSUE TITLE
 По 661 та 651 в звіт Реєстр проводок (аналітика), щоб був відбір по працівникам (контрагентам)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#1841]

**Comment by htrofymova** [comment]
Реєстр проводок - це суто бухгалтерський звіт. Той що заналітикою - специфічний звіт з додатковими стовпчиками,зроблений за запитом. Якщо потрібна аналітика по співробітникам, є Відомість за розрахунками з контрагентами, з якої можна відкрити Оборотну відомість по конкретному співробітнику.

**Comment by Anestezia** [comment]
Додати звіт Оборотна відомість по контрагентах по 651 рахунку.
