### ISSUE TITLE
нова операція в бух довідці Нарахування компенсуючих ПЗ з ПДВ

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#1855]
дебет - вибір потрібного рахунку (927, 949,.....) - кредит 643 (контрагент - моє підприємство).
перевірити, щоб закрилося в оборотці по 643 за моїм контрагентом

<img width="875" alt="image" src="https://github.com/user-attachments/assets/dfd9cf0f-ef67-4db8-a9f9-acb379c460e1">

**Comment by htrofymova** [comment]
що за рахунок 927?

**Comment by kattrina-brekhova** [comment]
перепрошую, 947
