### ISSUE TITLE
Застосування нової ставки ВЗ податковими агентами з 01.12.2024р.

### ISSUE THREAD

**Issue by OlenaIvanova1603** [a2develop/bugTracker#1858]
**1. До лікарняних, відпускних, які будуть нараховані до 01.12.2024р., застосовується ставка ВЗ 1,5%, незалежно від нарахування у грудні. 
 Лікарняні, відпускні, які будуть нараховані після 01.12.2024р. оподатковуються ВЗ у 5%. 

2. До доходу за ЦПХ, орендної плати, процентів за депозитами, дивідендів, які будуть нараховані після 01.12.2024р. – ставка ВЗ у 5%**

**Comment by kattrina-brekhova** [comment]
ФОП - з 1 січня

**Comment by kattrina-brekhova** [comment]
https://news.dtkt.ua/taxation/other/94566-zastosuvannia-novoyi-stavki-vz-podatkovimi-agentami-z-1-grudnia-roziasnennia-vid-dps?utm_source=tg_messenger&utm_medium=Tg&utm_campaign=news_03122024
