### ISSUE TITLE
[Верстка] правая колонка в списках контрагентов/операций и т.д. в разных разделах разной ширины + не везде озаглавлена Дії

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#189]
Правая колонка в списках контрагентов/операций и т.д. в разных разделах разной ширины + не везде озаглавлена Дії.
Разнобой - нехорошо.

IMHO имеет смысл:
- везде озаглавить эту колонку "Дії";
- выводить ее с фиксированной шириной по размеру пиктограмм, доступных в текущем разделе;
- выводить пиктограммы действий сразу, без клика (сделано на пробу на dev. в Контрагентах - прошу идею обругать).

Там же в Контрагентах краткое название предприятия выделено Болдом, чтобы виднее было куда тыкать для попадания вовнутрь.
Возражайте.

**Comment by AlexeyTishkin** [comment]
Сделал для Объектов и товарных операций.
Кстати, "выводить пиктограммы действий сразу, без клика" потом убрали.

**Comment by alex-kukhtin** [comment]
Вроде везде сделали. Если где-то зевнули - заводите отдельный issue
