### ISSUE TITLE
Свойства моей фирмы. Вынести на общую панель, под меню ника.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#190]
Свойства моей фирмы довольно трудно найти в первый раз. Да и во второй.
Однако от них зависит поведение и заполнение документов.
Хорошо бы его вынести на панель.

![2018-05-29](https://user-images.githubusercontent.com/35918141/40648922-47817776-6338-11e8-91f9-52d5e3a3a06b.png)

**Comment by AndriyNesterenya** [comment]
+++

**Comment by nik-man** [comment]
Конечно, на Главной удобнее. Это здорово. Однако:
Если пользователь знает, что это в Сервисе -- ему надо переключаться в Сервис.
Если пользователь знает, что это на Главной -- ему надо переключаться на Главную.
Может удобнее сделать доступ к свойствам без выхода из текущего раздела-подраздела?
