### ISSUE TITLE
[Bug] в списке КВЕДов позволяет вручную вводить коды и названия

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#192]
![image](https://user-images.githubusercontent.com/38098758/40837807-5f06e9e4-65a4-11e8-8792-e2f639445441.png)

Первая строка внесена руками, остальные - разным способом из каталога
Работает все замечательно в обоих случаях, но по вашей же задумке ручной ввод не нужен.

ИМХО переименуйте кнопку "Из каталога" в что-то типа "Добавить КВЕД", а нынешнее добавление удалите - и нет проблемы
Нынешнее добавление из каталога чудесно добавляетновую строку и предлагает выбрать из списка удобно и красиво
Смысл в отдельной кнопке, добавляющей строку, не вижу пока

**Comment by alex-kukhtin** [comment]
Fixed in 7203

**Comment by AndriyNesterenya** [comment]
Переименуйте кнопку "Додати з каталогу" на что-нибудь про код или КВЕД
