### ISSUE TITLE
[Верстка] плывет верстка на странице логотипа своей фирмы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#193]
![image](https://user-images.githubusercontent.com/38098758/40842734-8592e5be-65b7-11e8-81f7-0d8e052ac044.png)

Картинка - JPEG весом 250Кб размером 960*960

**Comment by AndriyNesterenya** [comment]
На Dev работает, на Beta нет

**Comment by alex-kukhtin** [comment]
Пробуй сейчас. Вроде починилось.
