### ISSUE TITLE
[МЕЛКИЕ КОСЯКИ ПРИ РЕГИСТРАЦИИ] - список некрасивостей при начале работы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#194]
1. Подправить сообщение о неподтвержденной e-mail при регистрации - чтобы первая строка начиналась с заглавной буквы, хотя бы "Ваш email...".
2. Дополнить письмо для подтверждения e-mail. Начать с приветствия + немного инфы/воды.
3. Выводить список КВЕДов отсортированным по коду
4. Убирать красную подсветку на обязательных полях и валидаторах сразу после ввода корректного значения, а не после клика вне поля
5. Кнопка "Профиль" в правом верхнем углу до сих пор никуда не ведет. Стоит линковать туда же, куда ведет "Налаштування моєї фірми" с главной
6. На главной вместо Inventory + Inventory text вывести абзац приветственного текста со списком основных фич и ограничений. Просто чтобы не так убого выглядело на входе.
7. Некорректная подсказка при нажатии на (?) в общей информации при регистрации ФОП
"Прізвище та ініціали, яким передує абревіатура "ФОП", є назвою особи, що веде господарську діяльність. Використовується в документах, для швидкого пошуку б списках, фільтрах тощо."
Там нет инициалов, там вводится целиком ФИО в тр разных поля.
8. Подсказка по (?) у поля Паспорт неинформативна. Содержит текст о том, зачем системе паспорт. Не сообщает ничего о том, что именно нужно вводить в поле - только номер, или еще и дату выдачи и орган, который выдал паспорт.
9. Добавить в подсказку по (?) у поля ИПН для ФОПа, что его ИПН является и кодом ЕДРПОУ.
10. Подсказка  по (?) у поля Система оподаткування не несет никакой полезной информации.  Справочные данные а-ля Википедия там не нужны.
11. Слегка по-дебильному (С)Добкин выглядят двойные подписи над и под полями ввода на формах регистрации. Не очень понятно зачем вверху над полем писать "Код банка", и тут же внизу "Код банка (МФО)". Как по мне достаточно второй надписи вверху, а внизу если что писать - то никак не повтор, а развернутые пояснения.
12. В "Про програму" .../app/about написать что-нибудь адекватное

**Comment by alex-kukhtin** [comment]
1. Исправлено
3. Не согласен. Гемморно реализуется, а нафига - не очень понятно. Обычно как вводим, так и отображаем. Кроме того, есть понятие "основного кода" - типа первый в списке.
