### ISSUE TITLE
[Пожелание] Добавить возможность управления договорами (создания + просмотр) в окно контрагента (между Операциями и Звитами)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#197]
Очень хочется иметь возможность создать договор прямо из окна контрангента.
И посмотреть список договоров с текущим контрагентом.
Прямо отсюда
![image](https://user-images.githubusercontent.com/38098758/40873847-8acdffb4-6670-11e8-89b0-e9a34a3822b0.png)

Думается, самый простой способ - добавить между Операциями и Звитами вкладку/пункт меню "Договори", в котором отображать список связанных договоров + кнопку создания нового.

**Comment by alex-kukhtin** [comment]
Done in 7207
