### ISSUE TITLE
[Пожелание] вставить перевод строки между кодом и номером контрагента в списке контрагентов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#201]
В нынешнем виде телефон полного формата, который мы требуем при регистрации, нечитабельный вообще
![image](https://user-images.githubusercontent.com/38098758/40877250-2acbe5c0-6686-11e8-8a13-b9cce1e8a088.png)

Предлагаю вставить перевод строки после кода перед номером и минимальную ширину столбца подогнать под 7 символов.

**Comment by alex-kukhtin** [comment]
Сделал по другому
![image](https://user-images.githubusercontent.com/26379138/40877620-c26b1634-668c-11e8-8379-9c22aae5e7a0.png)
