### ISSUE TITLE
Изменить формулировки в Акте выполненых работ

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#205]
Нужно править текст в Акте.

У нас сейчас :
Ми, представник**и** ЗАМОВНИКА | з одного боку, та представник**и** ВИКОНАВЦЯ |  
з iншого боку, склали цей Акт про те, що:
(таблица с услугами из рубрикатора услуг)

Нужно как-то в стиле:
Ми, представник ЗАМОВНИКА | з одного боку, та представник ВИКОНАВЦЯ |  
з iншого боку, склали цей Акт про те, що ВИКОНАВЕЦЬ надав, а ЗАМОВНИК прийняв послуги в складі: (таблица с услугами из рубрикатора услуг)
Послуги надано в повному обсязі.

+ ВИКОНАВЕЦЬ є платником Єдиного податку, если сумма без ПДВ.

**Comment by AlexeyTishkin** [comment]
Подобный текст был, но он был привязан к договору. Если договор не был выбран - текст не отображался. Сейчас сделал так, что текст отображается всегда. Посмотри на дев.

**Comment by AndriyNesterenya** [comment]
Симпатично. 
Если "ВИКОНАВЦЕМ виконані в повному обсязі роботи (наданi послуги)" выводить всегда,
а "згiдно договору №  від 01.01.1900" только если есть договор - получится красиво.

там еще в первом предложении "представники ЗАМОВНИКА" и виконавця во множественном числе, что неправильно - по одному с каждой стороны представителю.

**Comment by AlexeyTishkin** [comment]
Изменил. Проверь.

**Comment by AlexeyTishkin** [comment]
Сделал. Варианты: если контрагент - физ. лицо, то никаких доп. полей на рабочей форме не выводится и на печати выводится ФОП ..... Если контрагент - юр. лицо, то на рабочей формы появляется "В особі", "Посада". Если заполнены то при печати выводится <посада> Контрагент <особа>, если не заполнены, то только Контрагент.
