### ISSUE TITLE
Неподтвержденный емейл становится недоступным.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#209]
Пользователь зарегистрировался, но по каким-то причинам не подтвердил емейл.
Ссылка на регистрацию становится неактивной (кстати, через сколько времени?)
Зайти невозможно, просит подтверждения.
Повторная регистрация невозможна.
Фактически такой емейл сейчас становится "замороженным".

Надо что-то придумать для таких случаев.
Самый простой вариант - удалять заявку на регистрацию из систему одновременно
с дезактивацией ссылки для регистрации. Если это несложно, конечно.

**Comment by DenisClone** [comment]
Штука нужная, за два дня уже попалось на глаза две регистрации, явно ошибка в заполнении e-mail. Шансов на подтверждение такого мыла - ноль.

22.08.2018 07:14	bukovyna-sport@ukr.net
22.08.2018 06:58	bukovyna-sport@ykr.net

21.08.2018 12:02	119130@ukr.net
21.08.2018 11:57	11913@ukr.net

**Comment by DenisClone** [comment]
Снова появились такие пользователи. Регистрируются, через 24 часа ссылка становиться не действительной, они о ней вспоминают на следующий день. В итоге не могут ни повторно зарегистрироваться ни воспользоваться ссылкой для подтверждения.

**Предлагаю** сделать механизм повторного получения ссылки на подтверждение e-mail .
Либо в таком случае подтверждать e-mail через механизм восстановления паролей.

**Comment by alex-kukhtin** [comment]
Сделал простое удаление неподтвержденных мейлов.
Проблема решена.
