### ISSUE TITLE
Help. Диалог свойств контрагента

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#21]

**Comment by nik-man** [comment]
Неверная ссылка: http://help.a10.com.ua/catalog/agents
Правильная ссылка: http://help.a10.com.ua/reference/catalogs/agents

**Comment by alex-kukhtin** [comment]
А почему ты закрываешь issue? 
Заставь Вадима поставить правильную ссылку.
Закрывать можно только тогда, когда оно исправлено и лежит на dev.

**Comment by nik-man** [comment]
Понял.

**Comment by shevchuk-vadim** [comment]
Исправлено, проверьте.

**Comment by nik-man** [comment]
Там не надо полную ссылку, потому что получается такое:
http://help.a10.com.ua%20http//help.a10.com.ua/reference/catalogs/agents
Нужно относительную, только все, что после help.a10.com.ua

**Comment by shevchuk-vadim** [comment]
Сделал локальную ссылку.
