### ISSUE TITLE
Странное поведение по оприходованию и списанию запасов

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#211]
оприходовала запасы
![photo_2018-06-04_13-46-14](https://user-images.githubusercontent.com/38099938/40915204-d4f5f328-6803-11e8-9844-c2c0bd8c7d98.jpg)
в операции по списанию система считает что количество меньше 1. при этом документ проводит
![photo_2018-06-04_13-48-10](https://user-images.githubusercontent.com/38099938/40915289-2d4e667c-6804-11e8-82aa-51f978920b5b.jpg)

**Comment by AlexeyTishkin** [comment]
Исправил.
