### ISSUE TITLE
Список доступных отчетов для сдачи.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#213]
Пользователю трудно понять, есть ли необходимый ему отчет в системе.
Для этого ему приходится пройтись по всем периодам.
Хорошо бы как минимум вывести список доступных отчетов для справки.
Но еще лучше -- возможность создать отчет из полного списка отчетов.
Может быть, оставить два варианта создания отчета:
- по периоду
- из списка

Вадим предложил отличный вариант автоматически выставлять период отчета исходя из текущей даты и вида отчета. В таком случае пользователю не придется самому выбирать период вообще. Тем более, пользователю в общем случае может быть непонятно, какой период верный -- III квартал или 9 месяцев. Система же не ошибется.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AlexeyTishkin** [comment]
По поводу автоматического выбора периода. Отчет "Декларация плательщика единого налога". Сейчас июнь. За первый квартал сдавать поздно за первое полугодие - рано :) Какой период ставить ? Сейчас сделал так, что в этом случае период автоматом не ставится и пользователю нужно его выбрать самостоятельно.

**Comment by nik-man** [comment]
Отчет можно сдать позже срока. Ну бывает, не успел. Но нельзя сдать раньше срока.
В целом теперь ок. А зачем выбор периода перенес вниз?

**Comment by AlexeyTishkin** [comment]
> Отчет можно сдать позже срока. 

В этом случае период автоматом не ставится и пользователю нужно его выбрать самостоятельно.

> А зачем выбор периода перенесен вниз?

Чтобы соблюсти логику:
1. От периода. Выбираем период -> бланк.
2. От бланка. Выбираем бланк -> период.
