### ISSUE TITLE
Акт оказанных услуг: отсутствует місце складання

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#215]

**Comment by kattrina-brekhova** [comment]
может. 4 года назад нас проверяли по этому моменту в том числе. как сейчас - точно не знаю

**Comment by AlexeyTishkin** [comment]
4 года назад был точно обязательным. Отменили, по-моему, в конце прошлого года. Попрошу Колю узнать точно...

**Comment by nik-man** [comment]
Вадим Шевчук, [05.06.18 10:49]
Место составления документа сейчас не является обязательным реквизитом документа. Раньше за него придирались, теперь не имеют права.
Но исторически так сложилось, что в форме акта всегда был город (а он и есть место составления). Поэтому наши клиенты неизбежно столкнутся с тем, что их заказчики будут требовать в акте город, а иначе они этот акт не подпишут.

Александр Кухтин, [05.06.18 10:52]
Я бы просто текстовое поле добавил, чтобы не заморачиваться.

**Comment by AlexeyTishkin** [comment]
Добавил в "Реализации услуг".
