### ISSUE TITLE
[Bug] снова беда с телефонами нерезидентов и выводом в списке контрагентов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#218]
В списке контрагенттов криво выводятся не-украинские номера
![image](https://user-images.githubusercontent.com/38098758/40972051-27a76bdc-68c8-11e8-837c-bb5cb3c9e725.png)
![image](https://user-images.githubusercontent.com/38098758/40972089-4ed5ca6e-68c8-11e8-94b3-8449909f45d1.png)

**Comment by AndriyNesterenya** [comment]
Пытался скопипастить в свойства контрагента-нерезидента реальный номер
+7 (499) 110-03-07
Копипастится, но сжирает часть номера

В результате в таблице контрагентов  после редактирования выглядит вообще адски (подставляет наш код 380)

![image](https://user-images.githubusercontent.com/38098758/40978258-ca5a3c20-68db-11e8-987a-5096faf2b982.png)

**Comment by alex-kukhtin** [comment]
Увидел, подправлю.
