### ISSUE TITLE
В счетах и накладных значок "№" сдвинут вниз, под название документа.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#220]
![2018-06-05](https://user-images.githubusercontent.com/35918141/40974980-10f2899e-68d2-11e8-96a3-1c1b5c76e23a.jpg)

**Comment by nik-man** [comment]
В счетах и накладных все ок.
Акты (оба) в деве и бете еще остались:

![2018-05-07](https://user-images.githubusercontent.com/35918141/41093382-d1f45bf4-6a53-11e8-97fe-71b67dffabb4.png)

**Comment by AlexeyTishkin** [comment]
Проверь Акты на дев.

**Comment by nik-man** [comment]
На деве ок.
