### ISSUE TITLE
[User’s Manual] Дописать в мануал требование разрешить всплывающие окна в браузерах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#222]
Стоит дописать в мануал, что всплывающие окна в браузере на нашем сайте должны быть разрешены, иначе предпросмотры печатных форм и т.д. будут срабатывать со второго раза.

Удобнее всего дождаться появления сообщения о блокировке всплывающего окна в строке дреса Хрома при первом же тычке на "Друк/Экспорт" и прямо там разрешить.

**Comment by kattrina-brekhova** [comment]
и какое это может быть волшебное место, куда все пользователи попадали, читали, и понимают, что нужно разрешить всплывалку? ))))

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/70803709-5cbaec80-1dbd-11ea-9871-68fecceead51.png)
и даже когда-то об этом писала
