### ISSUE TITLE
Трудно найти кнопку "Закрыть" в документе

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#227]
Кнопка закрыть в документе должна быть недалеко от кнопки "Сохранить и закрыть" и у нее должна быть нормальная иконка, а не просто крестик. Сейчас она вообще не над документом, а над информационным окном.

**Comment by nik-man** [comment]
Вообще-то да, мне тоже кажется, что кнопка "закрыть" слишком далеко справа.
Особенно на большом мониторе. :))))
Может ее просто в конце, сразу за кнопкой "Печать/Экспорт" ?
Завтра обсудим.

**Comment by alex-kukhtin** [comment]
А какая иконка "нормальная" для "закрыть"?

**Comment by Paul-Brustinov** [comment]
Что-то квадратное с заполнением наподобии такого: 
![image](https://user-images.githubusercontent.com/16268850/41084812-cf4ef92e-6a3d-11e8-9a0d-2ec2d35e50b0.png)

**Comment by alex-kukhtin** [comment]
Смотри Windows 10. Они отказались.
И вообще - мы с тобой не в тренде. Почитай материалы с Google I/O. Material Design 2.
Все дела.

**Comment by alex-kukhtin** [comment]
Закрывать этот issue?
