### ISSUE TITLE
Для неверного емейла выдавать отдельное сообщение?

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#23]
Ввожу пароль - ошибка, еще раз - ошибка, пробую третий -- ошибка.
Ну думаю, забыл пароль. Потом вижу, буковку в емейле пропустил.
Может быть, для таких случаев выдавать сообщение типа
"Такой емейл не зарегистрирован в системе."

**Comment by alex-kukhtin** [comment]
Нет. Так сделано специально. Это безопасность. Нельзя показывать, что е-mail существует.
