### ISSUE TITLE
Ввел акт, в проводках не отразился объект учета

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#230]
Ввел акт, в проводках не отразился объект учета. 
![image](https://user-images.githubusercontent.com/16268850/41062978-021b37cc-69e0-11e8-9891-1a87e5b7ac3c.png)

**Comment by AlexeyTishkin** [comment]
Обсуждаемо...
Учитывая то, что мастера отчетов нет, в каком отчете ты хочешь увидеть объект "Послуги"?
Имей ввиду то, что:
1. По Дб и Кр аналитика не зависимая, т.е. по Кр в Journal можно записать сгруппировать только по контрагенту,  а по Дб сгруппировав по контрагенту и объекту.
2. Не факт, что всю аналитику нужно брать из Journal, есть строки документа. Нужно соблюсти баланс между избыточностью и производительностью.

**Comment by Paul-Brustinov** [comment]
Я не понимаю архитектуру системы, поэтому спрошу иначе. А в каком тогда отчете можно будет смотреть доход от реализации той или иной услуги, либо затраты на услугу.

**Comment by AlexeyTishkin** [comment]
В реализации услуг, по 703 объект в Journal записывается (посмотри операцию "Реализация услуг").
По поводу затрат. Там обычно хотят видеть более укрупненный анализ, чем название объекта, который нам дал поставщик. По хорошему - это статья затрат... Статей затрат в системе пока нет :)
