### ISSUE TITLE
Добавить полный список действующих банков с НБУ по принципу нашего каталога КВЭД

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#232]
Юзеры просят сразу список действующих банков 

https://bank.gov.ua/control/uk/bankdict/search

**Comment by nik-man** [comment]
Data.gov.ua http://data.gov.ua/passport/962846a2-4c2e-4483-84da-f024e3be6435

Bank.gov.ua https://bank.gov.ua/files/opendata/05_Dovidnyk_bankiv_Ukrajiny_in_xml.xml

https://bank.gov.ua/files/opendata/05_Dovidnyk_bankiv_Ukrajiny_in_json.json

**Comment by nik-man** [comment]
Вот добавляю расчетный счет, добавляю банк.
У банка есть обязательное поле "код ЕДРПОУ". А где его взять?
Код банка не так просто найти обычному пользователю.
Еще одна причина.

**Comment by AndriyNesterenya** [comment]
Да, квест еще тот.
Не говоря уже о ИНН, которого и на сайте у банке не всегда добыть можно
Думаю, стоит таки запилить

**Comment by AlexeyTishkin** [comment]
Сделал.
