### ISSUE TITLE
[Предложение] Добавить печать Доверенности на основе входящего счета (изменено)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#234]
Сабж

товарно-транспортная, на основании расходной 
и доверенность, на основании входящего счета.

**Comment by AndriyNesterenya** [comment]
... И связать тему с недавно возникшим вопросом интенграции с Новой Поштой ?

**Comment by AndriyNesterenya** [comment]
... клиент через форму обратной связи тоже просил.

**Comment by kattrina-brekhova** [comment]
и опять просили по доверенностям на основании счета
