### ISSUE TITLE
[Регистрация-логин] - безопасность и т.д.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#235]
Шото сделать с логином- паролем на странице логина в плейн-текст.
Вариант - разделить логин на две страницы а-ля Гугл + капча с галочкой .
за счет этого попутно попробовать победить Internal Server Error при повторном логине.

![image](https://user-images.githubusercontent.com/38098758/41082518-526332fa-6a37-11e8-8438-74e94587ccd1.png)

Ошибки при вводе несуществующего адреса (снова чегого-то на Яжур недоложили?)

![image](https://user-images.githubusercontent.com/38098758/41082413-ef1ab600-6a36-11e8-98ad-658384fba0b1.png)

![image](https://user-images.githubusercontent.com/38098758/41082428-fca93472-6a36-11e8-8fcc-3922f88859ad.png)

**Comment by alex-kukhtin** [comment]
Погоняй. Я думаю что все сделано. Можно закрывать.
