### ISSUE TITLE
[Bug] С зеленой кнопки с плюсом в "шапке" не создаются контрагенты и объекты учета

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#237]
С зеленой кнопки с плюсом в "шапке" не создаются контрагенты и объекты учета

![image](https://user-images.githubusercontent.com/38098758/41123378-2746aef6-6aa7-11e8-81fe-3107770321e1.png)

![image](https://user-images.githubusercontent.com/38098758/41123337-fc4b3a78-6aa6-11e8-817a-597136841bb8.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
