### ISSUE TITLE
Разработать (и уже сейчас предоставить клиентам на покрутить-поругать с точки зрения удобства) формат файла для импорта данных в приложение. 

### ISSUE THREAD

**Issue by MaksymTikhomirov** [a2develop/bugTracker#239]

**Comment by AlexeyTishkin** [comment]
Первый вариант сделал.

**Comment by nik-man** [comment]
https://drive.google.com/open?id=1AolOUc7E4fOiE5Og6LzWY6AuD0u4k9L5

**Comment by nik-man** [comment]
Новый (текущий) вариант, расширеный, украинский:
https://drive.google.com/open?id=1jZTRjjV1PDGPOWjF4eZOQ1uMA9exMVw-
