### ISSUE TITLE
Свойства ОУ. Некоторые картинки слишком сдвинуты вниз.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#24]
![114](https://user-images.githubusercontent.com/35918141/38458327-cd58691a-3aa5-11e8-803f-76d76e10c126.jpg)
![img_test](https://user-images.githubusercontent.com/35918141/38458328-cd741dcc-3aa5-11e8-80c0-2d2b6204e931.png)
![photo_2018-03-26_19-27-25](https://user-images.githubusercontent.com/35918141/38458331-d9b3998c-3aa5-11e8-8083-cdd8ca088c18.jpg)
Если попробовать прицепить эти картинки -- они получаются слишком сдвинуты вниз. Кстати, одна из этих картинок -- скриншот, на которой видно, как это выглядит.
В диалоге свойств ОУ картинка тоже сдвинута вниз и появляется линейка прокрутки. Иногда ненужная, как мне кажется.

**Comment by alex-kukhtin** [comment]
Fixed in 7152
