### ISSUE TITLE
[Кодировки] на MacBook в Outlook 2011 бьется кодировка сабжекта

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#240]
На MacBook в Outlook 2011 в сабже письма о подтверждении почты бьется кодировка
![image](https://user-images.githubusercontent.com/38098758/41152195-9b02f42a-6b1b-11e8-9e15-1e7f95bd02e3.png)

**Comment by AndriyNesterenya** [comment]
Пробовали на Dev с того же Мака с тем же Аутлуком 2011 - не помогло.
Думаю, что и не поможет :(
Попробую найти 2016 у кого-то для проверки, он менее глючный.

**Comment by alex-kukhtin** [comment]
Fixed in 7271.
Хакнул нафиг.

**Comment by alex-kukhtin** [comment]
Проверь пожалуйста, по возможности.
