### ISSUE TITLE
Номер исходящего счета - допускать буквы и спецсимволы типа / - _

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#242]
Сабж

**Comment by shevchuk-vadim** [comment]
Есть и другие проблемы с номерами документов, например, сортировка.

У нас в структуре два номера документа – числовой No и текстовый SNo. Первый используется только в документах, которые нумерует наша фирма, а второй - которые нумеруют контрагенты.

Для решения все проблем предлагаю сделать так:
Поле No во всех документах использовать для:
1. Поиска очередного номера при автонумерации, если она нужна в данном документе (при этом его значение копируется в поле SNo).
2. Сортировки документов.
Поле SNo во всех документах использовать для:
1. Редактирования номера (при этом из него выделяется число и записывается в поле No).
2. Отображения в списках документов, ссылках на документ, в отчетах, и т.д.
3. При поиске по номеру документа.

**Comment by AlexeyTishkin** [comment]
> при этом из него выделяется число и записывается в поле No

Была нумерация по порядку: 100, 101... потом пользователь в определенном документе вносит 08062018/суперпроект!!! Создает следующий документ и получает номер 8062019 (т.к. "No во всех документах использовать для: Поиска очередного номера при автонумерации").
Всем понятно откуда взялся следующий номер ?

**Comment by AlexeyTishkin** [comment]
Или меняет в очередном документе номер на 2147483647. Строка - имеет право. Выделили, записали в число. Автонумерация. Поиск номера. Следующий - 1 ? Тоже всем понятно ?
