### ISSUE TITLE
Счета, накладные, акты. Сумма прописью "... гривень 00 коп."

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#243]
Можно писать полностью "... гривень 00 копійок"
Можно писать сокращенно "... грн. 00 коп."
Сейчас стоит смешанный вариант "... гривень 00 коп."
Наверное, надо выбрать какой-то один.
Наверное, проще "грн.коп."

**Comment by alex-kukhtin** [comment]
Проще гривень, копійок.

**Comment by AlexeyTishkin** [comment]
> "... гривень 00 копійок"

Сделал.

**Comment by nik-man** [comment]
В деве ок. В облаке еще нет.

**Comment by AlexeyTishkin** [comment]
А зачем Done убрал ? Cloud достаточно. Не удобно же фильтровать...
