### ISSUE TITLE
[Улучшайзинг] Неудобная/непонятная форма обратной связи из системы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#245]
Обратная связь из системы в нынешнем виде технически работает, но юзеру не совсем удобно и понятно.
Замечания:
1. Увеличить предельную длину сообщения (сейчас навскидку 250-300 символов) - не хватает для описания проблемы.
2. При повторной отправке сообщения (например, если текст не поместился в ограничения) отображает текст предыдущего отправленного сообщения. Нужно или просто очищать форму, или еще и показывать историю.
3. Думаю, стоит увеличить дефолтный размер поля ввода до 5 строк - психологически понятно, что можно вводить довольно длинный текст.

Ну и стоит на уровне идеи определиться с будущим механизмом этого дела.
Это будет онлайн-чат, классическая система саппорта с тикетами, или простейшая отправлялка заявок, как сейчас?

**Comment by alex-kukhtin** [comment]
fixed in 7219

**Comment by AndriyNesterenya** [comment]
А еще просю обсудить тексты, заголовки и кнопку.
Если эта система будет использоваться не только для получения фидбеков при мучении беты, а и как будущая принималка проблем и пожеланий от юзеров, то само приветствие-пояснение стоит углубить и расширить, чтобы не сбивать юзера с толку - раз он полез писать в саппорт, то возмождных вариантов у него в голове было всего три : сообщить об ошибке, предложить улучшайзинг, или просто послать нас всех нахрен из тгривых побуждений.

Плюс нынешнее "Чи подобається вам наш сервіс" изменить  на что-то более нейтральное типа "Повідомити про помилку або пропозицію" + переименовать кнопку в просто "Надіслати"

**Comment by alex-kukhtin** [comment]
Обсуждайте. Дадите тексты - я вставлю что нужно.

**Comment by nik-man** [comment]
Дев: Обратная связь позволяет внести текст больше 255 символов, но при отправке выдает ошибку.
