### ISSUE TITLE
Отчет ЕН F0103306 - уведомлять пользователя о невыполненном начислении налога

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#250]
Сейчас в декларации ЕН ФОП F0103306 заполнение документа работает только если предварительно выполнена операция начисления налога.
Все те, кто отчитывался с Экселя, будут тупить и нервничать.
Предлагаю показывать уведомление о неначисленном налоге при входе в отчет или при нажатии на "Заполнить" - подумаем, как проще и удобнее.

**Comment by AlexeyTishkin** [comment]
Сделал.
