### ISSUE TITLE
[Верстка] Главная не влазит в мелкие экраны

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#252]
Главная страница не влазит по высоте в ноутбучные экраны 1366*768.
Вылесчится убиранием ссылки на параметры своей фирмы, но в виду стоит иметь.

Также чтоит не забывать, что по бедным бухгалтериям до сих пор стоит много "квадратных" мониторов с разрешением 1280*1024, в которые мы и по ширине не влезем.

Предлагаю минимальные размеры главной подгонять под размер порядка 1200*750, чтобы влазило вместе с панелями избранного в Хроме и прочих боковых панелей Оперы

**Comment by mik-man** [comment]
Можно сделать график "Рух грошових коштів" сворачиваемым, как все соседние окошки.
