### ISSUE TITLE
[Нумерация документов] распространить практику произвольной нумерации счетов на накладные и акты + кривой номер на печатной форме

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#254]
IMHO нужно распространить возможность присваивать номер произвольного формата со счетов еще и на накладные и акты.
Если юзер дает сложные номера счетам - 99,9% будет пробовать давать такие же номера актам и накладным.

Сейчас при попытке присвоить не-числовой номер типа "1-0618" или "Акт-1-0618" поле сбрасывается в 0.

**Comment by AlexeyTishkin** [comment]
Сделал.
