### ISSUE TITLE
В форме исходящего счета переименовать "Номер рахунку" в "Розрахунковий рахунок" + подставлять счет автоматически, если он единственный/основной

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#255]
Сейчас на ворме счета имеем подряд две надписи "Рахунок №" и "Номер рахунку" , что многих сбивает с толку.

![image](https://user-images.githubusercontent.com/38098758/41230984-5ae44ae4-6d8a-11e8-8f8c-3165111b8994.png)

Поле выбора своего счета стоит переименовать попонятнее, например "Розрахунковий рахунок"
И подставлять туда автоматом единственный основной счет, как договаривались давненько.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Получилось чуть криво за счет появление второй строки в надписи
![image](https://user-images.githubusercontent.com/38098758/41256090-47fb9062-6dd1-11e8-834c-0ac7174dd205.png)

Или сократить до Р/рахунок, или выводить выше, чтобы обе строки центровались .

**Comment by AlexeyTishkin** [comment]
Посмотри сейчас.
