### ISSUE TITLE
[Bug] в расходной накладной не дает отгрузить товар - не видит остатка по складу

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#256]
Не видит остатка по складу,
![image](https://user-images.githubusercontent.com/38098758/41235676-ed3bfea2-6d97-11e8-89b9-a2a660c6fda9.png)
несмотря на "Начальный баланс"
![image](https://user-images.githubusercontent.com/38098758/41235808-415a8b66-6d98-11e8-9727-6eb4128916d7.png)
и приобретение
![image](https://user-images.githubusercontent.com/38098758/41235860-66c0675e-6d98-11e8-913a-32fb61704ada.png)

**Comment by AlexeyTishkin** [comment]
Сделал обновление остатка при смене склада.
