### ISSUE TITLE
Расходная накладная - кривое поле Відправник, Приходная накладная - кривое поле Одержувач.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#257]
Криво формируется печатная форма Расходной накладной
в поле Відправник - юзерское название нашего склада, которое никому особо не нужно.

Хотелось бы шапку видеть примерно такой:
Постачальник: Наша фирма + реквизиты
Одержувач: Название контрагента.
При желании можно добавить "Через: ФИО представителя получателя"

Подобрая история в Приходной накладной - поле Одержувач вместо названия нашей фирмы содержит внутреннее название склада, не нужное на печатной форме.

Должно быть:
Постачальник: Название контрагента
Одержувач: Наша фирма

**Comment by AlexeyTishkin** [comment]
Два склада. Как покупатель узнает с какого склада получать ?

**Comment by Illya-Lykhachov** [comment]
Для склада нужен внутренний документ "Требование на склад". Вполне нормальная практика **одной** накладной отпускать товар с нескольких складов и для каждого склада формировать **отдельное** требование.
Накладная - это документ для бухгалтерий контрагентов, который подтверждает передачу права собственности на ТМЦ.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Ага, работает.
Только в самих докуменах обоих селектор складов называется"Одержувач"

![image](https://user-images.githubusercontent.com/38098758/41322810-c7ef3c0a-6eb3-11e8-9203-07609ade8c15.png)

![image](https://user-images.githubusercontent.com/38098758/41322896-248ffbd4-6eb4-11e8-8674-0d06ab721790.png)

Назовем их "Склад:" ?

**Comment by Illya-Lykhachov** [comment]
Раз в этом поле можно выбрать только склад, то и подпись должна быть "Склад".
Плохо то, что нет склада по умолчанию, каждый раз приходится его выбирать даже если он всего один.
Раз без склада нельзя (и э\то правильно), то при создании тенанта нужно сразу создавать "Основной склад" и делать его основным.
Твоё мнение, Андрей?

**Comment by AlexeyTishkin** [comment]
> Плохо то, что нет склада по умолчанию, каждый раз приходится его выбирать даже если он всего один.

Здрасьте :) А опция "Основной" зачем ?

> Раз без склада нельзя (и э\то правильно), то при создании тенанта нужно сразу создавать "Основной склад" и делать его основным.

И еще раз здрасьте :) Создай новый тенант.

**Comment by AlexeyTishkin** [comment]
https://github.com/a2develop/bugTracker/issues/52

**Comment by Illya-Lykhachov** [comment]
таки да, основной в свойствах прощёлкал и тенанты давно не создавал :)

**Comment by AlexeyTishkin** [comment]
> Назовем их "Склад:" ?

Переименовал.

**Comment by AndriyNesterenya** [comment]
Чудово. 
Еще бы туда в поле Склада подставлять по умолчанию склад, у которого галка "Основной" или единственный - было б вообще щасте :)

**Comment by AndriyNesterenya** [comment]
Пилять....
У меня он за давностию лет был без автоматической галки.
Которую я потом ставил-снимал, и в результате оставил неустановленной.
Сорри, закрываем тему.
