### ISSUE TITLE
[Предложение] Исходящий счет (invoice_out) - добавить на печатную форму под реквизитами "Не є платником ПДВ", если не стоит соотв. галочка в параметрах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#258]
На печатной форме исходящего счета хорошо бы добавить под реквизитами текстовую строку 
"Не є платником ПДВ" или "Є платником єдиного податку" 
если в параметрах своей фирмы не стоит галка плательщика НДС и выбран ФОП.

**Comment by AlexeyTishkin** [comment]
Сделал.
