### ISSUE TITLE
Для ФОП на общей системе (а также обычных физ. лиц, не ФОП) нужна "Декларація про майновий стан і доходи"

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#259]
Отчет для ФОП на общей системе имеет ту же самую печатную форму,
что и отчет для обычных самозанятых физ.лиз (не ФОП).
Формат XML-файла отличается незначительно.

**Comment by Illya-Lykhachov** [comment]
Нигде не нашел, что эта декларация нужна (обязательна). Вадим, вопрос к тебе: если обязательна делаем сейчас, если нет ставим в план развития?

**Comment by mik-man** [comment]
Взял в работу.

**Comment by MaksymTikhomirov** [comment]
> Нигде не нашел, что эта декларация нужна (обязательна). Вадим, вопрос к тебе: если обязательна делаем сейчас, если нет ставим в план развития?

НУЖНА
