### ISSUE TITLE
Поведение правой колонки в старых документах после перехода с ЕН на ПДВ.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#260]
Обнаружился мелкий идеологический гемор :
Был себе ФОП, формировал документы без НДС.
Перебрал оборот, стал плательщиком НДС, с этого момента документы формируются с НДС и в правой колонке появляется пункт "Податкове зобов`язання".
Старые документы продолжают отображаться правильно, без НДС, но при этом в правой колонке предложение сформировать для них Податкове зобов`язання тоже появляется, что неправльно.

Как бы в этом случае правую колонку показывать в старом виде?
Если есть какой-то признак, что документ еще без ПДВ формировался, правую колонку стоит формировать с учетом этого признака, а не только галки ПДВ в свойствах фирмы.

**Comment by AlexeyTishkin** [comment]
Изменил алгоритм отображения. Попробуй.
