### ISSUE TITLE
[Регистрация][dev] регистрирующийся юзер попадает на /app/changelog, которая закрывается насовсем по "Закрити"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#262]
Народ жалуется, что при регистрации по нашим ссылкам попадают на страницу /app/changelog на весь экран, откуда по кнопке закрытия вообще все закрывалось и продолжить можно, только если догадаться нажать на логотип и перейти с него на главную.

ЕМНИП по задумке регистрирующийся юзер должен попадать на главную с открытым визардом своей фирмы.
Нахрена ему открытый Changelog на весь экран?

**Comment by alex-kukhtin** [comment]
Возникает если он перешел по ссылке https://beta.bookkeepertech.com/app/changelog но был не залогинен.
