### ISSUE TITLE
В оборотке по материалам нет средней цены.

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#269]
Мне кажется, что средняя себестоимость товара - важнейший и простейший для понимания показатель, должен быть в оборотке.
![-](https://user-images.githubusercontent.com/16268850/41472084-131b9b86-70be-11e8-839d-862b586b0064.PNG)

**Comment by AlexeyTishkin** [comment]
Добавил. Смотри в следующим релизе (19/05).
