### ISSUE TITLE
Договора. При создании операции из договора не подставляется контрагент.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#27]
В свойствах договора обязательно есть контрагент.
Логично, что при создании документа из списка договоров должен подставляться не только выбранный договор, но и контрагент из его свойств.

**Comment by shevchuk-vadim** [comment]
В кассовых ордерах и платежных поручениях работает.

**Comment by AlexeyTishkin** [comment]
В возвратах исправил. Проверяй.
