### ISSUE TITLE
Странные проводки - не понятно где Дт, где Кт и странный их порядок

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#270]
Странные проводки - не понятно где Дт, где Кт и странный их порядок. Операция вступительного баланса по материалам.
![-](https://user-images.githubusercontent.com/16268850/41472162-4dd15d6a-70be-11e8-8c09-a03001acd92a.PNG)

**Comment by AlexeyTishkin** [comment]
> не понятно где Дт, где Кт 

Строка подписана: Дебет, Кредит.

**Comment by AlexeyTishkin** [comment]
> странный их порядок

Да, сортировку надо изменить...

**Comment by AlexeyTishkin** [comment]
> странный их порядок

Изменил. Смотри в следующим релизе (19/05).

**Comment by Paul-Brustinov** [comment]
Из рисунка не понятно какой Кт относится ко всем строкам проводки кроме первой. То есть я догадался что в первой строке Кт 0 (хотя это не очевидно), а какой Кт у остальных проводок не понятно вообще. Я бы предпочел видеть их парами по горизонтали, как пишут бухгалтера Дт Кт.
