### ISSUE TITLE
Когда изменяешь свойства "Конечного потребителя" первая закладка "Наименование" ставит в тупик. Поскольку никакого наименования там нет вообще.

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#272]
Когда изменяешь свойства "Конечного потребителя" первая закладка "Наименование" ставит в тупик. Поскольку никакого наименования там нет вообще.
Наименование должно быть, но должно быть понятно что его нельзя изменить, а в идеале чтобы было написано "Конечный потребитель - системная сущность и менять его наименование нельзя".
Сейчас там понятно только что это контрагент [12]
![kp](https://user-images.githubusercontent.com/16268850/41473145-17e28550-70c1-11e8-925b-d92bb6cb0d7b.PNG)

**Comment by alex-kukhtin** [comment]
Fixed in 7231
