### ISSUE TITLE
Всплывающий диалог выбора контрагента - нелогичная пагинация

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#274]
Сейчас в диалоге выбора контрагента выводится 15 записей, все остальные переносятся на следующую страницу.
Но при этом в само окно диалога помещается порядка 10 контрагентов, остальную половину списка нужно скроллить.

![image](https://user-images.githubusercontent.com/38098758/41542445-a552f542-731d-11e8-8b2a-9dfcd28258e1.png)

IMHO стоит или отказаться от страниц и позволить пользователю скроллить весь список, или выводить какое-то определенное кол-во записей без скролла с разбивкой по страницам.

**Comment by alex-kukhtin** [comment]
Очень спорный вопрос. Если бы не было переносов в названиях, то да.
А с переносами - полная задница. Будет появляться скроллер всего экрана. 
На мой взгляд - еще хуже.

**Comment by alex-kukhtin** [comment]
Закрывай наверное этот issue.
Все равно абсолютно непонятно, что с этим делать.
