### ISSUE TITLE
Если дубликат переводить с директора на кого-то другого, особенно с пометкой кассира, то вернуть взад уже нельзя - пишет про ограничения по поголовью

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/bugTracker#280]
от Андрея

**Comment by Illya-Lykhachov** [comment]
не понял что есть "дубликат".

**Comment by AndriyNesterenya** [comment]
Там были проблемы с переводом сотрудников с должности на должность.
Не хотело принимать двух кассиров как минимум.

**Comment by Illya-Lykhachov** [comment]
Сейчас (в реализации для ФОП) я не даю принять второго кассира (и директора с главбухом). Это даёт однозначность при подстановке кассира в расходные кассовые ордера.
Не сколько кассиров будет после добавления подразделений и касс.

**Comment by AndriyNesterenya** [comment]
Нашли в чем был баг.
И есть пока.

У ФОПа был принят на работу кассир.
Потом кассир был уволен.
И взять на работу нового кассира не давало и  не даёт до сих пор, даже если это другое физлицо.

**Comment by Illya-Lykhachov** [comment]
исправлено
