### ISSUE TITLE
Деклрация единого налога ФОП 3 группа: не формирует отчет наростающим результатом

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#281]
Отчет за 1 квартал
![photo_2018-06-22_10-20-00](https://user-images.githubusercontent.com/38099938/41763136-e4f73eca-7605-11e8-963e-74e715197bc7.jpg)
налоги заплатила
сформировала отчет за полугодие
![photo_2018-06-22_10-22-02](https://user-images.githubusercontent.com/38099938/41763186-27e388ba-7606-11e8-8a82-73489bd998b2.jpg)
и сюда попал результат только 2 квартала, а не 6 месяцев

**Comment by AlexeyTishkin** [comment]
Исправил на http://dev.a2start.com

**Comment by kattrina-brekhova** [comment]
Сформировала в dev
![photo_2018-06-22_11-24-19](https://user-images.githubusercontent.com/38099938/41766184-f67b78e2-760e-11e8-81e9-9678ce527da2.jpg)
строка 13: в предыдущем квартале сумма налога 500 грн (сервис автоматически не проставил, вручную ввела). строку 14 сервис не вычислил автоматически.

**Comment by AlexeyTishkin** [comment]
Сделал автоматическое заполнение.
