### ISSUE TITLE
ПКО. Валидатор в проведенном документе на сумме НДС.

### ISSUE THREAD

**Issue by AlexeyTishkin** [a2develop/bugTracker#282]
![image](https://user-images.githubusercontent.com/35917940/41764466-dee0032e-7609-11e8-897d-5dc412a39e0e.png)

**Comment by shevchuk-vadim** [comment]
Когда документ проведенный, то параметр sum, который передается в валидатор, является строкой, которая не преобразуется в число из-за пробела между сотнями и тысячами. Потом сравниваются не числа, а строки, и результат сравнения оказывается неправильным.
А если документ непроведенный, то sum - это число, и все OK.
Заглушку я поставил. Но странное поведение параметра валидатора может вылезти боком где-то еще.

**Comment by AlexeyTishkin** [comment]
Так может надо issue в A2v10?

**Comment by AlexeyTishkin** [comment]
Кстати, при сумме, к примеру 1000.00, можно поставить НДС 1.00. Это нормально?
