### ISSUE TITLE
[Предложение] Возможность создавать контрагента - конкретное физлицо

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#284]
Сабж.
Важно для юристов/туристов/услужников, как оказалось.
Прозвучало в т.ч. от
Максим Мокрый
https://www.facebook.com/maxmokry?fref=gs&hc_ref=ARTFblpa7U25hwin1MMPIZC63QdvbagOgw-9tTMD4vrUpfIvyfmn8VNSZBS113mllWs&dti=200810250551970&hc_location=group

**Comment by alex-kukhtin** [comment]
fixed in 7291
