### ISSUE TITLE
[Предложение] Возможность вывода комментариев к счету на печатную форму

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#285]
Уже обсуждалось устно.
У нас сейчас есть поле произвольных текстовых примечаний к исходящему счету, которое выводится как коммент в списке операций, но не выводится на печать.
У нас, видимо, это поле рассматривалось как информация для себя любимого.
Юзерами воспринимается как информация для контрагента.

В результате часть народу хочет, чтобы это примечание могло быть распечатано на бланке счета.

Мысль : приделать рядом с примечанием галочку типа "Роздрукувати на бланку рахунку", если установлена - выводить на печать.

Прозвучало в т.ч. от
Максим Мокрый
https://www.facebook.com/maxmokry?fref=gs&hc_ref=ARTFblpa7U25hwin1MMPIZC63QdvbagOgw-9tTMD4vrUpfIvyfmn8VNSZBS113mllWs&dti=200810250551970&hc_location=group

**Comment by AlexeyTishkin** [comment]
Может без галочки. Просто всегда печатать ?

**Comment by AlexeyTishkin** [comment]
Сделал.
