### ISSUE TITLE
[Предложение] Давать возможность редактировать номенклатуру в счете произвольно

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#286]
Сейчас выводим в счет только те позиции, что предварительно добавлены в об`єкти обліку.
народ просит иметь возможность кастомизировать/персонализировать позицию на лету, не внося изменений в об’єкти.

Например, есть стандартная услуга "Регистрация доменного имени в зоне .com" 
Юзер хочет иметь возможность пр выписывании счета на лету исправить текст в счете на  "Регистрация доменного имени shopopalo.com до 09/2019".
И эту же формулировку использовать в акте.

Прозвучало в т.ч. от
Максим Мокрый
https://www.facebook.com/maxmokry?fref=gs&hc_ref=ARTFblpa7U25hwin1MMPIZC63QdvbagOgw-9tTMD4vrUpfIvyfmn8VNSZBS113mllWs&dti=200810250551970&hc_location=group

**Comment by AlexeyTishkin** [comment]
Сделал.
