### ISSUE TITLE
Курсовая разница покупка валюты - не корректно названа строчка

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#287]
![photo_2018-06-23_17-51-28](https://user-images.githubusercontent.com/38099938/41810901-a9af7288-770e-11e8-9f36-761a4d99c19f.jpg)
1. пропустили пробел
2. не совсем корректно называется строчка: потому что документ считает правильно сумы, если вводить значение стоимости 1 EUR в гривне
![photo_2018-06-23_18-02-18](https://user-images.githubusercontent.com/38099938/41810945-9bd474e6-770f-11e8-98bf-c39d58c39a59.jpg)

**Comment by shevchuk-vadim** [comment]
1. пробел добавил.
2. не понял.

**Comment by kattrina-brekhova** [comment]
строчка называется "Офіційний курс за 1 UAH", тогда бы стоимость 1 гривны нужно было бы ставить в евро, например 1 UAH = 0.032 Евро. Но сервис считает значение, учитывая что в этой строчке стоимость "Офіційний курс за 1 Євро" (или доллара, или другая валюта) в гривне. тут название строчки нужно правильно указано. но тогда нужно, чтобы это название менялось, исходя из выбранной валюты

**Comment by shevchuk-vadim** [comment]
Изменил формулировку метки курса, и в валютных платежных поручениях тоже.

**Comment by shevchuk-vadim** [comment]
Изменил формулировку метки курса, и в валютных платежных поручениях тоже.

**Comment by kattrina-brekhova** [comment]
Строчка "сума купівлі" - указываем сумму в гривнах?
если так, то что-то не получается
смотрю здесь: beta.bookkeepertech.com

сточка называется "Оф. курс за 100 UAH"
значит здесь стоимость нужно указать в евро.
считаю
например 1 евро = 31 гривна
х (евро) = 100 гривен
100/31 = 3,226 евро (стоимость 100 гривен)
![photo_2018-06-25_16-04-01](https://user-images.githubusercontent.com/38099938/41851715-74f9cf00-7891-11e8-95b4-3e8de270811d.jpg)

или что-то напутано с названием строчки "сума купівлі"?
или я туплю?
правда, что-то у меня не сходится
