### ISSUE TITLE
Отчет по НДС - не формируется

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#288]
У меня два акк на beta.bookkeepertech
1. ФОП 3 группа - не плательщик НДС - декларация формируется. 
2. юр лицо 3 группа, плательщик НДС - выдает ошибку
![photo_2018-06-25_18-31-17](https://user-images.githubusercontent.com/38099938/41859937-ff9848da-78a5-11e8-997a-e4cecd489bb7.jpg)
также во втором случае не могу сменить юр лицо с 3 группы на общее налогообложение, изменения вроде сохраняются, но при повторном открытии свойств фирмы, данные остаются прежними

**Comment by AlexeyTishkin** [comment]
А на дев ?

**Comment by kattrina-brekhova** [comment]
На дев - и юр лицо и ФОП - 3 группа, плательщик НДС - отчет формирует. но тоже не изменяет на общую систему налогообложения.
ишью создам

**Comment by AlexeyTishkin** [comment]
Можешь кинуть скриншоты свойств "моей фирмы" ?

**Comment by kattrina-brekhova** [comment]
![photo_2018-06-25_21-33-26](https://user-images.githubusercontent.com/38099938/41868664-72bb0672-78bf-11e8-8147-c979b2d57840.jpg)
![photo_2018-06-25_21-34-08](https://user-images.githubusercontent.com/38099938/41868728-8acf6618-78bf-11e8-8674-7a942d9cdd0d.jpg)
![photo_2018-06-25_21-35-30](https://user-images.githubusercontent.com/38099938/41868772-ba6384c2-78bf-11e8-8c21-29c4edb13302.jpg)
![photo_2018-06-25_21-36-06](https://user-images.githubusercontent.com/38099938/41868811-db986324-78bf-11e8-9da5-e7dcd5b431a5.jpg)

**Comment by AlexeyTishkin** [comment]
Еще нужна страница "Контакти". Рахунки, Логотип - не нужно.

**Comment by AlexeyTishkin** [comment]
Исправил.
