### ISSUE TITLE
Свойства моей фирмы: юр лицо 3 группа не изменяет на общее налогообложения

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#289]
"изменить и сохранить" можно, но войдя повторно в настройки, система налогообложения остается прежней - 3 группа

**Comment by alex-kukhtin** [comment]
fixed in 7234

**Comment by kattrina-brekhova** [comment]
Увидела пометку, что сделано, перепроверила у себя, но не меняет

**Comment by kattrina-brekhova** [comment]
работает!!
