### ISSUE TITLE
Счет, накладная. Большая таблица - линейка прокрутки прыгает вверх.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#290]
Табличная часть любого документа, счет, накладная и пр.
Создать несколько строк, можно пустых, только чтобы появилась линейка прокрутки.
Прокрутить вниз, чтобы шапка документа скрылась.
Стать на любую строку и воспользоваться селектором (быстрым поиском по части названия).
Результат: линейка прокрутки прыгает вверх.

**Comment by alex-kukhtin** [comment]
Не могу повторить. Все отображается как нужно.
