### ISSUE TITLE
Счет исходящий. Для одинаковых ОУ печатает одинаковое печатное название, первое.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#291]
![2018-06-26](https://user-images.githubusercontent.com/35918141/41905870-0b7fc12e-7945-11e8-912b-5e6ece2a9186.png)

Если в исходящем счете поставить 2-3 одинаковых ОУ, то печататься будут одинаковые названия из первой строки.

**Comment by AlexeyTishkin** [comment]
Исправил.
