### ISSUE TITLE
[Bug] В исходящем счете на печати обрезает последние 40-50 символов из Примітки

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#293]
Мелкий глюк в Примітке к счету.
В документе позволяет вбить текста больше, чем выводит на печать.
При формировании допускает 254 символа в поле, на печатной форме выводится обрезанній вариант, последних символов 40-50 не отображается.

**Comment by AlexeyTishkin** [comment]
Исправил.
