### ISSUE TITLE
[Улучшайзинг] текстовое поле для вывода сообщений о смене реквизитов на всех счетах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#295]
Давно обсуждалось с моей подачи - отложили на потом.
Снова всплыло от имени Владимир Ю. с ФБ.

Суть : 
Дать возможность на всех исходящих счетах под реквизитами/над номером и данными выводить выделенное сообщение о смене реквизитов или чем-то подобном важном.

Возникла идея текстовое поле для этого приделать на страницу счетов в свойствах своей фирмы.
И выводить текст из этого поля на счет, если поле непустое.
Или по галке рядом.

**Comment by AlexeyTishkin** [comment]
Если делать "второе примечание", то это назначение должно быть общим, а не только для сообщения о смене реквизитов, поэтому располагать его нужно точно не на закладке "Счета"...
А вот где ? И как его понятно назвать ?

**Comment by AlexeyTishkin** [comment]
"Второе примечание" может быть изменено в конкретном счете ?

**Comment by AndriyNesterenya** [comment]
Нет. По задумке это самое второе примечание нужно для того, чтобы бросаться в глаза всем клиентам и напоминать, что изменились реквизиты для оплаты, склад переехал, а директор с печатью  в отпуске еще две недели.

**Comment by nik-man** [comment]
Мне кажется, лучше всего сделать два Примечания произвольного размера -- одно вверху, одно внизу. Это закроет все пожелания по примечаниям. И возможность "запоминать" текст, который там хранится. Можно даже автоматически, что-то вроде классической автоподстановки в браузерах.

**Comment by AndriyNesterenya** [comment]
Как по мне, ДВА комментария не нужны вообще.
Персональные комменты на конкретном счете придет в голову писать единичным юзерам (пока даже не придумал в каких ситуациях это кому-то может понадобиться).
А вот предупреждайка о глобальных изменениях в конторе нужна многим и часто.

Даже мелькнула шальная мысль, избавиться от нынешнего варианта комментариев для конкретного счета, и выводить в то же поле общий для всех исходящих счетов коммент, хранимый не в документе, а на уровне свойств своей фирмы.

В этом смысле галка возле коммента, заставляющая сохранить комментарий, написанный в текущем счете, и выводить его же во всех последующих счетах, пока галка не снимется и коммент не удалится, выглядит каким-никаким решением.

**Comment by nik-man** [comment]
https://github.com/a2develop/bugTracker/issues/76

**Comment by AlexeyTishkin** [comment]
С точки зрения структуры это все разные решения:
1. Два (один) самостоятельных комментария в счете. Хранятся в документе. Возможно заполнение из каких-то свойств + редактирование внутри конкретного счета.
2. Два (один) связанных комментария в счете. Берутся из каких-то свойств. В документе не хранятся, соответственно в конкретном счете изменить нельзя.
3. Варианты п. 1 + п. 2, т.е. один самостоятельный + один связанный.

Надо решать какой из...

**Comment by AlexeyTishkin** [comment]
Сделал.
