### ISSUE TITLE
[Bug] Отпуск. При создании через Персонал-Новый документ не подсвечивает пустое поле ФИО + ошибка при проведении

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#296]
При создании через Персонал -> + Новий документ ->Відпустка не подсвечивает пустое поле ФИО.
Позволяет сохранить не заполняя имя (назначив только даты, например) - без ошибок.
Подсвечивает кнопку Провести без имени.
При попытке провести - ошибка 
Cannot insert the value NULL into column 'RowHire', table 'Segment1.a2.JournalHR'; column does not allow nulls. INSERT fails.

**Comment by Illya-Lykhachov** [comment]
исправлено
