### ISSUE TITLE
Кнопка "Приянть на работу" в диалоге выбора сотрудника.

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#298]
1. Входящий счет. Какой там может быть "Виписав"? Да еще наш сотрудник???
2. Если все-же нажать кнопку выбора, а в диалоге "Прийняти співробітника" - то поведение становится вообще неадекватным. Нужно закрывать диалог перед открытием документа.

**Comment by Illya-Lykhachov** [comment]
Убрал нафиг эту кнопку. Сотрудники - это не произвольные элементы справочника, они просто так не добавляются, на это нужно решение руководителя (приказ). Их не может кто-попало создавать.

**Comment by Illya-Lykhachov** [comment]
а насчёт возможности выбора сотрудника в поле "Выписал" особых проблем не вижу. Эта возможность реализована необязательной - хочешь выбирай, хочешь пиши руками.

**Comment by Illya-Lykhachov** [comment]
Лёш, нужно убрать выбор **наших** сотрудников из входящих документов

**Comment by AlexeyTishkin** [comment]
Убрал.
