### ISSUE TITLE
Возвратная накладная. Отдел Продажи.  Нарушение логики

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#30]
Завожу новую накладную на возврат от 10.04. (не на основании расходной - здесь все работает корректно). А с нуля. Ситуация: у меня есть две расходные накладные по одному контрагенту "Вайкон" 07.04. и 09.04. на сумму 300 и 4500 соответственно. Создаю возвратную, в графе "основание до видаткової накладної" - программа подтягивает не расходную, а приходную накладную от этого же контрагента от 06.04. на сумму 1500. Контрагент для меня и продавец и покупатель
#bug

**Comment by AlexeyTishkin** [comment]
Исправлено.
