### ISSUE TITLE
Декларация НДС: не формирует суммы по обязательствам и кредиту

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#300]
![photo_2018-07-02_12-59-56](https://user-images.githubusercontent.com/38099938/42158023-f1ba4d9c-7df7-11e8-8946-1d3c391a8054.jpg)
![photo_2018-07-02_13-00-12](https://user-images.githubusercontent.com/38099938/42158026-f4ac0694-7df7-11e8-9c61-5f097f3459ae.jpg)
![photo_2018-07-02_13-01-33](https://user-images.githubusercontent.com/38099938/42158080-1eee2ef0-7df8-11e8-8df8-69ea5ca39979.jpg)
![photo_2018-07-02_13-02-15](https://user-images.githubusercontent.com/38099938/42158101-2e76ef74-7df8-11e8-9eeb-fc0b824d8ace.jpg)

**Comment by AlexeyTishkin** [comment]
Декларация пока только для ручного заполнения.

**Comment by kattrina-brekhova** [comment]
а в перспективе будет рассчитывать? ишью закрывать?

**Comment by AlexeyTishkin** [comment]
Будет. Ишью пусть висит.

**Comment by AlexeyTishkin** [comment]
Сделал в первом приближении.
