### ISSUE TITLE
[Bug] Проводим операции с сотрудником с датой более ранней, чем дата приема на работу самого сотрудника

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#301]
Позволяем проводить операции (типа Звіт про використання коштів) с датой более ранней, чем дата приема сотрудника на работу.
IMHO достаточно у операций с участием сотрудника перед сохранением и/или проведением сравнивать даты.
Учитывать ли при этом больничные/отпуска - вопрос к знатокам.

**Comment by shevchuk-vadim** [comment]
В кассовых ордерах и авансовом отчете сделал запрет проведения документа, если работник на дату документа еще не принят или уже уволен.

Теперь, если я правильно понимаю, для полного счастья нужно сделать запрет снятия проведения приказа о приеме на работу, если работник присутствует в операциях, у которых дата >= дате приема. У таких операций Operation.AgentKind = 'PERS'. Илья?

**Comment by AndriyNesterenya** [comment]
Ждем от Ильи уточнений? Или можно закрывать?

**Comment by shevchuk-vadim** [comment]
Уточнение. Не 'PERS', 'EMPL'.

**Comment by Illya-Lykhachov** [comment]
В отмену проведения приказа о приёме добавил проверку на использование сотрудника в качестве подписанта
