### ISSUE TITLE
После того как в отчете меняется период, он не обновляется 

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#303]
После того как в отчете меняется период, он не обновляется, в результате можно получить такой противоречивый отчет, в котором расходная накладная не входит в отчетный период.
![image](https://user-images.githubusercontent.com/16268850/42204435-62633be6-7eaa-11e8-9fa9-3ed57c8ce69b.png)

**Comment by alex-kukhtin** [comment]
Вопрос очень спорный. Можно конечно обновлять автоматом. Но тогда запросов будет слишком много.

**Comment by alex-kukhtin** [comment]
А вот то, что основное поле тоже обновляется вместе с параметрами до того, как отчет обновлен - вот это как раз совсем не правильно.

**Comment by alex-kukhtin** [comment]
Fixed in 7249
