### ISSUE TITLE
В РН шрифт итогов меньше чем текст в таблице 

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#304]
В расходной накладной шрифт итогов меньше чем текст в таблице

![image](https://user-images.githubusercontent.com/16268850/42204491-8cd154d0-7eaa-11e8-8f86-5ce6db7d7302.png)

**Comment by AlexeyTishkin** [comment]
Уменьшен шрифт строк.
Следующий релиз в пятницу.
