### ISSUE TITLE
Проводки все равно выглядят некрасиво. Сложно понять какой Дт соответствует какому Кт

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#306]
Проводки все равно выглядят некрасиво. Сложно понять какой Дт соответствует какому Кт.
![image](https://user-images.githubusercontent.com/16268850/42204577-c6c72db8-7eaa-11e8-88d3-9e20402eef12.png)

**Comment by alex-kukhtin** [comment]
Done (7425)
