### ISSUE TITLE
Рахунок - Товар почему-то называется "Объект"

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#307]
Товар почему-то называется "Объект" - нигде такого не встречал.

![image](https://user-images.githubusercontent.com/16268850/42204618-df38f598-7eaa-11e8-8a6e-5c3401458272.png)

**Comment by AlexeyTishkin** [comment]
Переименовано в "Номенклатура товарів/послуг".
Следующий релиз в пятницу.

**Comment by nik-man** [comment]
Зачем вставлять лишние слова? Можно просто "Товари/послуги"
