### ISSUE TITLE
Отчет Д5: в таблицу по обязательствам не попадают ИНН покупателей (в таблице по кредиту ИНН поставщиков отображаются)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#309]

**Comment by AlexeyTishkin** [comment]
На дев ? Как можно увидеть ?

**Comment by kattrina-brekhova** [comment]
нет, на бета

**Comment by kattrina-brekhova** [comment]
![photo_2018-07-03_17-55-57](https://user-images.githubusercontent.com/38099938/42227545-699203c6-7eea-11e8-83e3-b58c4f90095d.jpg)
![photo_2018-07-03_17-56-57](https://user-images.githubusercontent.com/38099938/42227599-86c13fc0-7eea-11e8-9b15-4db1f081de59.jpg)
![photo_2018-07-03_17-57-52](https://user-images.githubusercontent.com/38099938/42227660-a38a6a14-7eea-11e8-9174-5b624adad1b6.jpg)
![photo_2018-07-03_17-58-33](https://user-images.githubusercontent.com/38099938/42227699-bd41b048-7eea-11e8-82cd-c28455e568ba.jpg)

**Comment by kattrina-brekhova** [comment]
появилось....
странно
снимаю ишью

**Comment by kattrina-brekhova** [comment]
да, так и есть, перепровела налоговую. 
а что с порядковым номером? он не ставится
![photo_2018-07-03_18-35-27](https://user-images.githubusercontent.com/38099938/42229753-e3c362de-7eef-11e8-96ac-d5397f74f702.jpg)

**Comment by AlexeyTishkin** [comment]
Порядковые номера в ближайшее время будут переделываться...

**Comment by AlexeyTishkin** [comment]
Нумерацию можно посмотреть на dev.

**Comment by kattrina-brekhova** [comment]
спасибо, ок
