### ISSUE TITLE
Создание операции из элемента. Новая операция не появляется сразу.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#31]
При создании операции из любого элемента (договора, ОУ, СУ) она не появляется в списке операций.
Надо нажимать кнопку "Обновить".
Из объекта учета вообще не появляется, даже после "Обновить"
Также при изменении существующей операции -- не обновляются свойства операции (вероятно, это связанно, поэтому пока не будет отдельный issue создавать)

**Comment by shevchuk-vadim** [comment]
Так копку "обновить" специально и добавили, потому что новая операция не появляется в списке сама, если она была открыта в новом окне.

**Comment by nik-man** [comment]
Да, вспомнил. Был разговор об этом.
Не знаю, насколько это правильно.
Закрывать issue?
