### ISSUE TITLE
Вступительный баланс на главной странице.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#310]
Ввод вступительного баланса обладает двумя особенностями.
1. Он нужен сразу вначале работы. Буквально после заполнения свойств Моей фирмы.
2. После того как его внесут, он совсем почти не нужен.

Понятно, эти пункты противоречат друг другу. Выходит, что его нужно разместить где-то на очень видном месте, буквально рядом с Мастером свойств моей фирмы. А потом его лучше вообще убрать, будет зря место занимать. Как это правильно сделать, не знаю.

Можно убирать автоматически, можно дать такую возможность пользователю.

**Comment by MaksymTikhomirov** [comment]
++
Надо шото придумать, да. 
Дискасс в общем.

**Comment by AndriyNesterenya** [comment]
По поводу вообще убрать - может и не стоит.
Возможно, что сходу не все внесут или с ошибкой внесут.
 Думаю, именно для того, чтобы не занимать драгоценное место в списке операций, имеет смысл где-то в свойствах фирмы или в бухгалтерии запилить отдельный раздел/пункт меню со всеми вступительными делами по банку и объектам учета.
