### ISSUE TITLE
Розрахунок коригування податкового кредиту: документ формирует неправильную проводку

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#311]
не правильно формируется проводка.
вот операция по получению кредита:

![photo_2018-07-04_17-05-43](https://user-images.githubusercontent.com/38099938/42281558-9362e64e-7fac-11e8-81e5-d69d746accf8.jpg)
тогда по корректировке нужно
здесь нужна проводка: Д644 - К6411 без сторно
или д6411 - К644 - но тогда уже сторнировать

**Comment by AlexeyTishkin** [comment]
На дев исправил. Это наведенная ошибка...
