### ISSUE TITLE
Коригування податкових зобов’язань: не проставляет номер родительской налоговой накладной, и изменить его нельзя, проводит с №0

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#312]
![photo_2018-07-04_17-24-45](https://user-images.githubusercontent.com/38099938/42282435-2d0f7c60-7faf-11e8-9315-a4ec7604c459.jpg)

**Comment by AlexeyTishkin** [comment]
На бете вариант с не верной нумерацией.
Проверь на дев.

**Comment by kattrina-brekhova** [comment]
та же история

**Comment by AlexeyTishkin** [comment]
Корректировку нужно удалить и создать заново.

**Comment by kattrina-brekhova** [comment]
все ок
