### ISSUE TITLE
Банки, добавленные из списка -- не отображаются свойства.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#316]
Для тех банков, которые не созданы вручную, а добавлены из списка банков -- диалог свойств пустой. Нельзя посмотреть реквизиты.
![2018-07-05](https://user-images.githubusercontent.com/35918141/42321096-5e2e2fec-8060-11e8-8370-5f3d40338a5e.png)

**Comment by alex-kukhtin** [comment]
И еще - даблклик по банку просто закрывает окно и ничего не добавляет.

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by nik-man** [comment]
При просмотре свойств банка в каталоге еще до добавления в локальный справочник тоже пусто.
Или сделать новый ишью?

![2018-07-09](https://user-images.githubusercontent.com/35918141/42459468-51e8c7be-83a4-11e8-984e-1dbb66537f31.png)

**Comment by AlexeyTishkin** [comment]
Для записи из каталога нет смысла показывать диалог свойств. Убрал колонку с "Редактировать", "Удалить".

**Comment by nik-man** [comment]
Может пользователь просто хочет посмотреть реквизиты какого-то банка.
Почему бы ему не дать возможность? Нам же не жалко.

**Comment by AlexeyTishkin** [comment]
> Может пользователь просто хочет посмотреть реквизиты какого-то банка.

А зачем тогда нажимал "Импортировать" ?

**Comment by nik-man** [comment]
Ну вот нужно тебе посмотреть реквизиты банка для чего-нибудь.
И тут вспоминаешь, что в системе есть полный и актуальный список банков.
Который доступен только по кнопке "Импортировать".
Зашел и посмотрел.

**Comment by AlexeyTishkin** [comment]
Ну список же есть. Диалог нафига ?
