### ISSUE TITLE
Диалог свойств Моей фирмы. Кнопка "Зберегти" не запускает валидацию.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#319]
Если создать расчетный счет с пустыми или неправильными полями, то кнопка "Зберегти" выдает ошибку.
(кнопка "Зберегти і закрити" работает правильно)

![2018-07-05](https://user-images.githubusercontent.com/35918141/42324016-a490ef42-806a-11e8-983d-ffcb6b0cc29c.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7243
