### ISSUE TITLE
Любая операция. Смена контрагента должна влиять на выбранный договор.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#32]
При смене или выборе контрагента в операции остается выбранный договор.
Может получится, что стоит договор от другого контрагента.
Смена контрагента должна очищать поле договор.
Может быть -- подставлять договор по умолчанию.

**Comment by AlexeyTishkin** [comment]
Давай подробней. К примеру, "Отримання рахунку". При выборе контрагента, у которого есть основной договор, он сразу подставляется в "Договор". При выборе другого контрагента, договор меняется на основной другого контрагента, либо удаляется. Что не так ?

**Comment by nik-man** [comment]
Девид Блейн! Не работало же утром!
Да, сейчас все правильно. Со сменой контрагента меняется договор.
Раньше оставался старый.

**Comment by AlexeyTishkin** [comment]
Ты похоже попал в междубилднье :) Это работало давно, потом появилась наведенная ошибка, потом исправили...
