### ISSUE TITLE
[Верстка] таблички со скроллом во всплывающих диалогах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#321]
На всплывающих диалогах типа свойств своей фирмы длинные списки со скроллом а-ля КВЕД стоит выделять рамкой (по моему скромному мнению).
Нижняя граница сразу уезжает вниз и поле таблицы визуально не выделено, при скроллинге пропадает и верхняя - в результате выглядит некрасиво.

![image](https://user-images.githubusercontent.com/38098758/42326615-496584c2-8072-11e8-962f-c2f5ccc9d780.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7311
