### ISSUE TITLE
Единицы измерения и их формат при импорте

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#322]
После возни с импортом оказалось, что по невнимательности можно ненароком надублировать себе единиц измерения и получить что-то в стиле
![image](https://user-images.githubusercontent.com/38098758/42331954-790ccf84-807f-11e8-9531-6f159e366843.png)

Думается, имеет смысл при импорте принудительно загонять пользовательские единицы в нижний регистр + откусывать точки и пробелы и проверять на совпадение с имеющимися.

Были мысли о стандартном предустановленном списке общеупотребительных единиц типа штук/метров/литров/килограммов, но мы тут никогда не угадаем с тоннами/километрами/декалитрами + в любом случае будут пользовательские типа а-ля пара/упаковка/комплект/бочка.

**Comment by AlexeyTishkin** [comment]
Сделал.
