### ISSUE TITLE
Приказ о принятии на работу. При печати нет названия Моей фирмы - юрлица.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#323]
В печатной форме приказа не печатает название Моей фирмы, если это юридическое лицо.
(Название ФОП печатает)

![2018-07-06](https://user-images.githubusercontent.com/35918141/42372802-e9259d90-811b-11e8-856b-31e9cf92c2a2.png)

**Comment by Illya-Lykhachov** [comment]
исправлено
