### ISSUE TITLE
Расширенный список (оу, су, договора). Кнопка возврата в обычный список неочевидна.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#325]
![2018-07-06](https://user-images.githubusercontent.com/35918141/42447797-ba3363c2-8383-11e8-8320-8a5854b23abb.png)

Мне кажется, было бы удобно, чтобы название ОУ оставалось ссылкой (только буквы, не вся ячейка)
Один раз кликнул название -- перешел в расширенный список,
второй раз кликнул название -- вернулся в обычный.

**Comment by mik-man** [comment]
Оказывается, пользователи не видят кнопку возврата:
 "< Контрагенти"
Логично, она выглядит как просто заголовок.
Одни передергивают разделы, другие передергивают подразделы.
А как вы возвращаетесь в обычный список? ))

**Comment by alex-kukhtin** [comment]
Итого? Ваши предложения?
