### ISSUE TITLE
Счет исходящий. Нет контроля остатков.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#326]
![2018-07-09](https://user-images.githubusercontent.com/35918141/42448712-cf44467a-8386-11e8-9d62-df0091fe1a2e.png)

Понятно, что количество в счете на оплату может превышать реальные остатки. Если фирма работает по предоплате, например. С другой стороны, какое-то предупреждение желательно. Иначе потом, для корректировки кол-ва в счете приходится удалять расходную накладную и отменять проведение счета.

Не нужно строгого запрета на проведение, как для расходной, но как-то предупреждать, наверное, желательно.

**Comment by Illya-Lykhachov** [comment]
Нестрогий валидатор, как в накладной.

**Comment by AlexeyTishkin** [comment]
Сделал.
