### ISSUE TITLE
Пользователю кажется неудобным ввод цен через свойства ОУ.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#327]
![2018-07-09](https://user-images.githubusercontent.com/35918141/42449086-040aa506-8388-11e8-9f4c-ffe69cced847.png)

Понятно, что желательно, но явно не первоочередная задача.
Может быть закладку в расширенном списке ОУ добавить со временем.

**Comment by AlexeyTishkin** [comment]
> Нужна возможность вводить и цену продажи.

Свойства объекта - Закладка "Цена".

**Comment by AlexeyTishkin** [comment]
Добавилось:
1. Операция "Створення прайс-листа".
2. Из операции "Придбання" можно создать связанную операцию "Створення прайс-листа".
