### ISSUE TITLE
Help. Раздел остался на русском.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#328]
http://help.bookkeepertech.com/operations/personnel/payroll/order

**Comment by kattrina-brekhova** [comment]
Не меняла. жду пока документ будет доработан. пока вплывает информационное сообщение 
![photo_2018-07-10_09-55-32](https://user-images.githubusercontent.com/38099938/42493952-7f85e5f2-8427-11e8-86d1-c8a3aece247a.jpg)
