### ISSUE TITLE
Help. Нет описания ввода вступительных остатков по счетам и субъектам.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#331]
http://help.bookkeepertech.com/start/initbalance
http://help.bookkeepertech.com/operations/other/cahs
http://help.bookkeepertech.com/operations/other/bank
... и далее.

**Comment by kattrina-brekhova** [comment]
до вчерашнего дня операции не создавались. до конца недели подготовлю
https://github.com/a2develop/bugTracker/issues/299
