### ISSUE TITLE
РКО (расходный кассовый ордер). Выдача денег юр.лицу должна быть запрещена.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#334]
Практически нет возможности выдачи налички юр.лицу (чисто теоретически есть).
В таком случае, наверное, нужно закрыть возможность в РКО указывать получателя-юр.лицо.
(ФОПа указывать можно)

**Comment by shevchuk-vadim** [comment]
Закрыл возможность указывать юрлицо.

**Comment by mik-man** [comment]
В разделе "Придбання" осталась возможность создать операцию "Видаток з каси - Оплата постачальнику" -- в этом документе можно указывать юр.лицо.
