### ISSUE TITLE
[Стимулсофт] Окно просмотра и печати - непонятное для юзера

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#338]
"Друк з попереднім переглядом" ведет себя неинтуитивно и вводит юзера в ступор - открывается просмотр, на который можно только смотреть и закрыть, напечатать нельзя.
По нынешней логике требуется нажать Ctrl-P вручную, но масса юзеров о такой возможности даже не догадывается.

Нужно добавлять явную кнопку печати или что-то в этом духе.

**Comment by alex-kukhtin** [comment]
Напишите им (я серьезно). Может там какая птичка есть, чтобы это поведение изменить.

**Comment by AlexeyTishkin** [comment]
Коля писал:
![image](https://user-images.githubusercontent.com/35917940/42630089-414423b8-85de-11e8-813d-b156ca513a2b.png)

**Comment by nik-man** [comment]
Можно еще написать.
Чем больше подергают, тем быстрее сделают. Все ж так работают. ))
Внизу кнопка "Начать чат"
https://www.stimulsoft.com/ru
