### ISSUE TITLE
Нет информации о доверенности на расходной накладной

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#339]
На бланке расходной накладной отсутствует упоминания о доверенности. 
 Сдал/принял есть, а на основании чего принял - нет.

**Comment by AlexeyTishkin** [comment]
Добавил.

**Comment by kattrina-brekhova** [comment]
все классно, строчка "Через кого" позволяет ввести ФИО получателя и прописать №, дату доверенности. сомнения вызывает само название строчки. уже есть строки "сдав", "прийняв", куда можно указать лица получателя и отправителя. как насчет переименовать строку на "Через кого, підстава". Изначально это и имел в виду Андрей.
