### ISSUE TITLE
Мастер свойств моей фирмы. Лишний значок валидации.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#340]
Открыть мастер свойств моей фирмы.
Дойти до закладки "Рахунки" (рахунков нет)
Создать расчетный счет и сразу удалить.
В названии закладки остается висеть значок некорректной валидации.
(правда он не мешает продолжить работать и сохранить)

![2018-07-10](https://user-images.githubusercontent.com/35918141/42509976-34e72108-8456-11e8-8854-e862be9ddb1b.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7317
