### ISSUE TITLE
Табличные отчеты. При печати отображается линейка прокрутки.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#341]
Если отчет достаточно широкий, чтобы появилась линейка прокрутки -- она печатается на бумаге.
Хорошо бы внизу убрать линейку прокрутки.
И названия накладных подправить (это сделано)

![2018-07-10](https://user-images.githubusercontent.com/35918141/42514884-1b8ea14c-8463-11e8-8b9e-f6fe41951a14.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7246
