### ISSUE TITLE
Заполнение отчета по единому налогу для ФОП. Предупреждение об отсутствии начислений.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#343]
Для правильного заполнения отчета необходимо, чтобы были начислены налоги за предыдущие периоды. Т.е. если, например, я хочу сдать отчет за полугодие, я должен сначала начислить налоги за 1 квартал, затем за 2 квартал и тогда уже отчет за полугодие заполняется правильно.

На практике получается что: при заполнении отчета, система не проверяет наличие всех необходимых начислений (за 1 и 2 квартал). Поэтому предлагает сделать только одно из них (за 2 квартал). После чего заполняет отчет без предупреждений.

Мне кажется, если система сообщает об отсутствии начислений, необходимых для заполнения отчета, она должна сообщать об отсутствии **всех** необходимых начислений, а не только за последний период.

Upd:
Для правильного заполнения отчета, кстати, нужны все предыдущие отчеты. Об этом тоже предупреждать надо, наверное.

**Comment by AlexeyTishkin** [comment]
> Для правильного заполнения отчета, кстати, нужны все предыдущие отчеты. 

Нет. Из предыдущего отчета берется только строка 13.

> Об этом тоже предупреждать надо, наверное.

Если нет отчета за предыдущий период в системе, то уже все, поздно его формировать, сроки прошли. А если сдавался не из системы, то ручной ввод.

**Comment by AlexeyTishkin** [comment]
Проверку начисления налогов сделал.
