### ISSUE TITLE
Вступительный баланс - использование корреспондирующего счета 0 - не во всех операциях используется

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#345]

**Comment by AlexeyTishkin** [comment]
Так и должно быть. 0 - счет вступительного баланса.

**Comment by kattrina-brekhova** [comment]
По остальным операциям начального баланса этот счет не используется, а только пополняемые счета.

**Comment by shevchuk-vadim** [comment]
Леша, это в Акценте у нас обязан был быть счет 0, и только потому, что проводка была одной записью в БД, и требовала обязательного наличия и дебета, и кредита. А в Буккипере у нас две записи. И мы можем делать односторонние проводки, только дебет или только кредит. Вторая сторона со счетом 0 абсолютно бесполезна. Давай ее уберем.

**Comment by shevchuk-vadim** [comment]
Счет "0" из проводок удален.
