### ISSUE TITLE
Декларация о едином налоге ФОП. Название XML-файла неверное.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#346]
При сохранении отчет в  XML-файл, название файла должно соответствовать правилам формирования.

На картинке пример правильного и существующего названия.
![2018-07-10](https://user-images.githubusercontent.com/35918141/42561101-0da6f36a-8501-11e8-8306-ad3529a16cba.png)

**Comment by AlexeyTishkin** [comment]
У тебя возникла проблема с импортом в какую программу для отправки ? В какую ? Стандартная от налоговой EDZV прекрасно понимает это имя.

**Comment by nik-man** [comment]
Проблем не возникло. Ок, пока закроем. ))
