### ISSUE TITLE
Начисление зарплаты: после начисления аванса невозможно провести документ за вторую половину месяца

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#349]
но по закону расчет з/п должен проводится два раза в месяц
![photo_2018-07-12_09-39-19](https://user-images.githubusercontent.com/38099938/42616603-92dd0874-85b7-11e8-9650-f09b67dc54b1.jpg)

**Comment by Anestezia** [comment]
Если этого не сделать в скором времени, то получается, мы заставляем наших пользователей нарушать законодательство о труде, что повлечет за собой громадные штрафы.

**Comment by MaksymTikhomirov** [comment]
++
