### ISSUE TITLE
Предложение по последовательности операций в разделах

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#35]
В разделах Приобретение, Продажи предлагаю выстроить последовательность операций не в алфавитном порядке, а согласно соответствующей документации конкретного раздела: получение (выставление) счета, получение (отгрузка) запасов, возвратная накладная, получение (реализация) услуг..... и в конце добавить оплату поставщику с кассы, или счета банка...  Потому что в документы по оплате, насколько я понимаю, можно будет зайти с раздела Бухгалтерия?
Либо выстроить документы по такой логике: получение (выставление) счета, оплата, получение (отгрузка) запасов...

**Comment by shevchuk-vadim** [comment]
Я согласен с первым вариантом - оплата в конце.

**Comment by AlexeyTishkin** [comment]
А в разделах Контрагенты (Договора) - Операции какая должна быть последовательность ? Сейчас Касса/Банк, потом товарные операции.

**Comment by kattrina-brekhova** [comment]
по контрагентам мне удобно по алфавитному порядку работать. но сложно так сразу сказать, потому что не заводила большой список

**Comment by shevchuk-vadim** [comment]
Я бы делал везде одинаковый порядок операций, если нет каких-то особых соображений.

**Comment by kattrina-brekhova** [comment]
В разделе Бухгалтерия - Банковские операции было бы удобнее разбить операции по "группам" , например, сначала расчеты с поставщиками, потом с покупателями, потом расчетно-кассовое обслуживание, выдача с банка в кассу, внесение с кассы в банк, выплата на платежные карты, перечисление группы налогов

**Comment by kattrina-brekhova** [comment]
в разделе Запасы последовательность операций очень нравится!

**Comment by kattrina-brekhova** [comment]
С кассовыми операциями тоже было бы удобнее работать в последовательности по аналогии с банковскими операциями

**Comment by shevchuk-vadim** [comment]
Изменил порядок банковских и кассовых операций.
