### ISSUE TITLE
Вход-регистрация. Имя пользователя. Изменение и ограничение длины.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#351]
При регистрации поле "Имя пользователя" позволяет вводить очень длинный текст.
В целом это неплохо, можно оставить как фичу. :)
Но, наверное, требуется добавить возможность изменения имени в дальнейшем.

![2018-07-12](https://user-images.githubusercontent.com/35918141/42629324-9aa4ace6-85db-11e8-9ee2-be5daedb5b09.png)

**Comment by alex-kukhtin** [comment]
fixed in 7246

**Comment by nik-man** [comment]
Уже все так. Это я еще вчера снимал.
Длинные имена обрезает.
Но вот переименоваться нет возможности. Сделать новый ишью?

**Comment by alex-kukhtin** [comment]
Конечно.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
