### ISSUE TITLE
Отображение названия Моей фирмы.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#352]
Может быть пора добавить вверху краткое название Моей фирмы?

![2018-07-12](https://user-images.githubusercontent.com/35918141/42629804-48d56494-85dd-11e8-8426-716bdcbc25f5.png)

**Comment by alex-kukhtin** [comment]
Ну вот  нафига это надо?
Ты не помнишь, как твоя фирма называется?

**Comment by nik-man** [comment]
Все равно ведь придется когда-то добавить. Сам знаешь. ))
Даже пока одна фирма в тенанте.
Я сейчас веду две, например: ФОП Мануйленко и ТОВ Буккипер Саас.
И вынужден их различать только по имени пользователя.
Но я не настаиваю. Могу закрыть ишью. Закрывать? ))

**Comment by alex-kukhtin** [comment]
Сделай метку "отложено" (deferred) и закрой. Потом разберемся
