### ISSUE TITLE
Акт списания: не работает кнопка выбора статьи затрат

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#354]

**Comment by AlexeyTishkin** [comment]
Откуда в Акте статья затрат ?

**Comment by kattrina-brekhova** [comment]
![photo_2018-07-13_09-16-48](https://user-images.githubusercontent.com/38099938/42679224-dba5c62c-8689-11e8-9a0b-0a914ecedd45.jpg)
"списать на" - работает в том случае если нажать на сам текст

**Comment by AlexeyTishkin** [comment]
Да, какое-то странное поведение комбобокса.

**Comment by alex-kukhtin** [comment]
fixed in 7246
