### ISSUE TITLE
[Улучшайзинг] на форме F3040111 выбор кода основного вида деятельности - выбирать из списка своих КВЕД 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#355]
Сейчас на F3040111 есть обязательное поле основного вида деятельности, которое требуется заполнять вручную.
IMHO правильнее по тычку на поле показать список КВЕД своего предприятия и дать выбрать основной.
Или вообще в свойствах своего предприятия приделать признак "Основной вид деятельности" типа галочки на нужной записи, и впредь подобные поля заполнять автоматом.

**Comment by AlexeyTishkin** [comment]
Поторопился с issue :)
Сделан первый этап - бланк, второй этап - заполнение. На следующей неделе будет.

**Comment by Illya-Lykhachov** [comment]
этот отчёт уже полностью заполняется программно, в т.ч. вид деятельности
