### ISSUE TITLE
Разделы: Бухгалтерия, Персонал, Отчетность - нет иконки хэлпа - "?"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#356]
Как здесь:
![photo_2018-07-17_10-40-57](https://user-images.githubusercontent.com/38099938/42803287-371cf53a-89ae-11e8-858d-fdb5b87e877e.jpg)

**Comment by AlexeyTishkin** [comment]
В Отчетности куда ссылку делать ?

**Comment by kattrina-brekhova** [comment]
отчета посвящено 2 части хэлпа: разделы учета - отчетность и отчеты - налоговые и по зарплате.
но наверное будет правильнее выделить ссылку на разделы учета - отчетность: http://help.bookkeepertech.com/work/fiscal
А отсюда будут ссылки на каждый из отчетов с дальнейшим описанием на соответствующих страницах

**Comment by AlexeyTishkin** [comment]
Для Отчетности сделал.

**Comment by alex-kukhtin** [comment]
Done in 7291
