### ISSUE TITLE
Профиль пользователя. Редактирование.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#358]
Наверное, нужна возможность редактирования профиля.
Чтобы переименовать имя пользователя (то, что отображается вверху).
Ну и телефон может смениться.

![2018-07-18](https://user-images.githubusercontent.com/35918141/42874244-4644f144-8a89-11e8-9f47-11460018b1ec.png)

**Comment by alex-kukhtin** [comment]
Done in 7265
