### ISSUE TITLE
Системное сообщение об ошибке. Выделение текста.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#359]
Когда выскакивает системная ошибка, которую надо показать разработчику, приходится сохранять ее картинкой. Мелочь конечно, но будет удобнее, если текст ошибки будет выделяться для копирования.

Вот типа такого:
![2018-07-17](https://user-images.githubusercontent.com/35918141/42875165-aa7f715a-8a8b-11e8-9e2d-6979dcc55fc7.jpg)

**Comment by alex-kukhtin** [comment]
Fixed in 7249

**Comment by nik-man** [comment]
Да, на деве текст выделяется.

![2018-07-19](https://user-images.githubusercontent.com/35918141/42938311-8dbcb2ba-8b5a-11e8-85dc-6616a06f9fd7.png)

А на ажуре пока не смог проверить. Эта зараза не всегда показывает текст.

![2018-07-19](https://user-images.githubusercontent.com/35918141/42940913-adddd926-8b63-11e8-8060-98f4784a6d0b.png)

**Comment by AlexeyTishkin** [comment]
Точнее всегда не показывает :)

**Comment by alex-kukhtin** [comment]
Я же говорил, что юзер сообщение не увидит :-)
А тут некоторые типа "я бы не был так уверен"
