### ISSUE TITLE
Документ Платежное поручение в разделе Приобретение

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#36]
Создаю с нуля Платежное поручение, ввожу получателя, сумму, провожу документ. Окно сразу же выбрасывает меня на новое платежное поручение, не давая увидеть проводку проведенного предыдущего документа.
Если создавать платежное поручение на основании счета такого не происходит.

**Comment by AlexeyTishkin** [comment]
https://github.com/alex-kukhtin/A2v10/issues/49

**Comment by AlexeyTishkin** [comment]
Исправлено.
