### ISSUE TITLE
Внесок статутного капіталу (на р/р). Добавить операцию.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#360]
Кстати, ФОП тоже может ложить деньги на свой расчетный счет.
Обычно такая операция называется: "Внесення власних коштів"

Ну и напоминалка, что надо еще сделать "Отримання відсотків"

**Comment by mik-man** [comment]
А "Внесення власніх коштів" ФОПом на свой расчетный счет как происходит?
