### ISSUE TITLE
Удаление ед. измерения невозможно, если она была в свойствах удаленного ОУ.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#363]
Создать новую ед. измерения.
Создать ОУ. Установить в свойствах эту ед. измерения.
Удалить ОУ.
Попытаться удалить ед. измерения из справочника.

Update:
Со справочником "Групи" то же самое. 
Если група была в свойствах удаленного ОУ, ее уже нельзя удалить.

**Comment by AlexeyTishkin** [comment]
Исправил.
