### ISSUE TITLE
Повторное создание расчетного счета невозможно.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#364]
Создать контрагента.
Установить в свойствах расчетный счет (например "123").
Удалить контрагента.
Попытаться установить этот расчетный счет ("123") в свойствах другого контрагента.

**Comment by AndriyNesterenya** [comment]
Более того, есть подобная ситуация в персонале. 
Если кассир был принят на работу, и потом уволен - нового касира на работу взять нельзя.
Где-то идеологический косяк в способе проверки на совпадения.

**Comment by alex-kukhtin** [comment]
В проверке нужно void добавить.
И при удалении контрагента ставить void для всех дочерних записей (в частности для расчетных счетов)
