### ISSUE TITLE
В диалоге импорта банка осталась кнопка "Імпортувати". Рекурсия, однако.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#365]
Прикольно выглядит, если несколько раз нажать.
![2018-07-23 - -](https://user-images.githubusercontent.com/35918141/43074798-3497323e-8e87-11e8-8743-82c11319bbcb.png)

**Comment by MaksymTikhomirov** [comment]
Красиво, чо. Оставляем :smile:

**Comment by AlexeyTishkin** [comment]
Исправил.
