### ISSUE TITLE
Пожелание. Увеличить поле "Назва" в свойствах ОУ.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#366]
Не очень удобно редактировать длинные названия.
Хорошо бы сделать многострочным. Место на диалоге есть.

![2018-07-23](https://user-images.githubusercontent.com/35918141/43079857-ee0eccae-8e96-11e8-8f98-411e9b2d79bf.png)

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by nik-man** [comment]
О, и правда!
Ровно 25 минут. Это, наверное, самый быстрый закрытый ишью. ))
(среди действительно закрытых)
