### ISSUE TITLE
Видатковий Касовий ордер. Насколько это нормально что можно выбрать юр.лицо?

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#368]
Видатковий Касовий ордер. Насколько это нормально что можно выбрать юр.лицо?
Даже если можно выбрать юр.лицо, то должны бить реквизиты представителя который получил деньги с его паспортными данными?

**Comment by nik-man** [comment]
Повтор: https://github.com/a2develop/bugTracker/issues/334

**Comment by shevchuk-vadim** [comment]
Закрыл возможность указывать юрлицо.
