### ISSUE TITLE
Возврат товара от покупателя - показывает в списке реализации другим покупателям.

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#370]
Возврат товара от покупателя - показывает в списке реализации другим покупателям.
![_ _ _ 0 _-_google_chrome_2018-07-23_20-58-02](https://user-images.githubusercontent.com/16268850/43094296-2e4f756a-8ebb-11e8-99f8-a2cadfd425ff.png)

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by AlexeyTishkin** [comment]
Во вторник не было публикации.
