### ISSUE TITLE
Акт приема/сдачи услуг. Подписи.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#372]
1. Желательно внизу указывать краткие ФИО подписантов (как в накладной).
Вообще говоря, это необязательно, поскольку в заголовке они есть. Но, скорее всего, возникнут вопросы. Да и просто удобнее.

2. Ну и наверное, поля в шапке лучше сделать многострочными. В нашем случае уже слегка не помещается.

![2018-07-24](https://user-images.githubusercontent.com/35918141/43133706-41a0895a-8f48-11e8-858c-bc061cb1ffa5.png)

**Comment by AlexeyTishkin** [comment]
Создай, пжл, в тестовом аккаунте такого виконавця.

**Comment by nik-man** [comment]
http://dev.a2start.com/document/service_act_in/edit/6786
"Основано на реальных событиях" :)

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AlexeyTishkin** [comment]
Поменял.
