### ISSUE TITLE
Справочник банков. Неверное ЄДРПОУ.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#373]
Укрсиббанк
МФО: 351005
ЄДРПОУ: 09807750

Видимо, поскольку ЄДРПОУ начинается с нуля, первый нуль отбросило и в свойствах банка оказалось ЄДРПОУ из семи цифр.

Причем, вероятно, эту ошибку совершили программисты НБУ, когда выгружали справочник в JSON. Поскольку в json-файле тоже неверный Єдрпоу. А в Html-файле верный.

![2018-07-24](https://user-images.githubusercontent.com/35918141/43141368-61ec19f2-8f5e-11e8-9d65-133deb0bdb6a.png)

**Comment by AlexeyTishkin** [comment]
Да, проблема в JSON: "IKOD": 9807750
Попробую поиграться с форматом при импорте...

**Comment by AlexeyTishkin** [comment]
Сделала форматирование кода.
