### ISSUE TITLE
По проекту невозможно построить никакой отчет.

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#377]
По проекту невозможно построить никакой отчет. Возможно просто не понятно где он есть.

**Comment by AlexeyTishkin** [comment]
В отчеты "Відомість по взаєморозрахунках з постачальниками", "Оборотна відомість за розрахунками з постачальниками",  "Відомість по взаєморозрахунках з покупцями", "Оборотна відомість за розрахунками з покупцями" добавлен фильтр по проекту.

**Comment by kattrina-brekhova** [comment]
Леша, два отчета: "Відомість по взаєморозрахунках з постачальниками" и  "Відомість по взаєморозрахунках з покупцями" (обороток нету)
в обоих выбор проекта позможен
после того как я выбрала один проект, могу выбрать и другой. но чтобы потом отменить фильтрацию, чтоб снова увидеть по всем проектам - невозможно

**Comment by AlexeyTishkin** [comment]
Оборотки строятся по одному контрагенту и детализируют движение по датам.
Запускаются:
1. Из основного отчета при клике на конрагенте.
2. Контрагенты - Определенный - Звіти.

**Comment by AlexeyTishkin** [comment]
Меню "..." в селекторе проекта (при выбранном проекте) - Очистити.
