### ISSUE TITLE
При заполнении группы у объекта выводит странное сообщение, потом работает.

### ISSUE THREAD

**Issue by Paul-Brustinov** [a2develop/bugTracker#379]
При заполнении группы у объекта выводит странное сообщение, потом работает.
![_ _-_google_chrome_2018-07-25_21-52-53](https://user-images.githubusercontent.com/16268850/43221307-2e976172-9055-11e8-994b-a36fced9e5e9.png)

**Comment by alex-kukhtin** [comment]
А как ты это получил?  Какой-то очень странный глюк.

**Comment by Paul-Brustinov** [comment]
Уже не повторяется, закрываю ишью.
