### ISSUE TITLE
Пожелания в панель управления.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#38]
Частые операции
Счета 
Отчеты (общую тумбу)

Остатки в банке и кассе, задолженность дебеторская и кредиторская
нагляднее в динамике, период - неделя. изменяемый период - вообще кайф

Можно последние действия. это даст возможность напомнить на чём остановился и продолжить работу.

Последние незакрытые счета входящие и исходящие (документы-кандидаты на создание из них дочерних оплат и поставок/отгрузок)

Календарик с напоминалками (в идеале,  настраиваемыми) - по срокам сдачи отчетности,  налогам и тыды.  Ну и типа по раб.  дням/выходным. К нему можно добавить какую-то напоминалку ближайшего события типа "для уплаты ЕСВ осталось 7 дней"

Быстрый доступ к справочникам - ЕДРПОУ,  МФО,  курса валют, ставка НБУ и тыды.

У ФОПа обычно используется небольшой набор операций:
Выставить счет, Сделать акт, Отметить оплату. Посмотреть должников. Посмотреть остаток на счете, Затащить данные из клиент-банка...
Может быть сделать что-то вроде галочки "Вынести на рабочий стол", но это должна быть такая галочка, которая будет взводиться сама, автоматически. Причем для самых разных сущностей:  вид операции, контрагент, договор, объект учета.
Хотя, например, я бы хотел сам устанавливать или убирать эту галочку. И умные пользователи тоже, есть любители. Настроил себе рабочий стол и можно вовсе внутрь не залезать.

**Comment by alex-kukhtin** [comment]
Закрывай этот issue нафиг. Если еще актуально - расшифруй
