### ISSUE TITLE
Свойства контрагента. Поля "Назва" и "Повна назва" сделать многострочными.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#383]
Иногда названия субъектов бывают очень длинными.
Хорошо бы сделать поля "Назва" и "Повна назва" сделать многострочными и автоматически расширяемыми, по аналогии с диалогом объекта учета (поле названия ОУ).

**Comment by alex-kukhtin** [comment]
Коля, ну вот какая нафиг в этом срочность?

**Comment by mik-man** [comment]
Расширить поле "Примітка" в закладке "Інше". Места дофига, а поле в три строки.

![2018-10-04](https://user-images.githubusercontent.com/35918141/46469445-18f14e00-c7dc-11e8-9013-a6175851a1be.png)

**Comment by mik-man** [comment]
Многострочные -- да. Автоматическое увеличение -- еще нет.
Имел в виду пожелание, чтобы поля "Назва", "Повна назва" і "Примітка" увеличивались в размере. Как "Назва" для ОУ:
![2018-10-10](https://user-images.githubusercontent.com/35918141/46729273-81817480-cc8d-11e8-9fe1-22970b7439fb.png)
