### ISSUE TITLE
Окошко "Показать проводки" привязать выше "Підстава".

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#384]
В некоторых документах есть документ-основание. В некоторых нет. 
Получается, что окошко "Показать проводки" отображается то выше, то ниже.  Пользователю приходится концентрировать внимание, куда он клацает. Хорошо бы, привязать проводки всегда вверху. Возможно, хорошо бы заголовки окна "Проводки" и "Підстава" сделать разным цветов. Сейчас они оба желтые и слишком похожие.

![2018-07-27](https://user-images.githubusercontent.com/35918141/43311790-08b7c1a0-9194-11e8-9e47-2453beccb4da.png)

**Comment by AlexeyTishkin** [comment]
> Возможно, хорошо бы заголовки окна "Проводки" и "Підстава" сделать разным цветов.

Каким ?

**Comment by mik-man** [comment]
> Каким ?

Не знаю. Светло-зеленый еще свободен, например.

**Comment by AlexeyTishkin** [comment]
В товарных операциях сделал. Посмотри.

**Comment by mik-man** [comment]
Удобно и красиво. Проводки всегда вверху и они зеленые.
Кстати, удачно получилось, что сообщение "Документ проведено..." и кнопка "Показати проводки" взаимосвязаны логически и подсвечены одним цветом.

**Comment by AlexeyTishkin** [comment]
> Кстати, удачно получилось, что сообщение "Документ проведено..." и кнопка "Показати проводки" взаимосвязаны логически и подсвечены одним цветом.

Да, очень.
