### ISSUE TITLE
Платежная ведомость и связанный РКО. Добавить проверку остатка в кассе.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#385]
При проведении Платежной ведомости создается РКО. РКО создается и сразу проводится.
(Кстати, может в этом и вопрос. Может быть не надо сразу проводить?)
Так вот, РКО проводится, но проверка остатка в кассе не запускается.

**Comment by shevchuk-vadim** [comment]
Теперь РКО проводится не сразу.
