### ISSUE TITLE
Расширенный справочник (оу, су, дог). Исчезает перечень документов после правки.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#386]
Справочник ОУ, СУ или договора.
Зайти в расширенный список. Закладка "Операции".
Выбрать любой элемент по которому есть операции.
Изменить свойства элемента.
Перечень операций исчезает.
Можно переключать вид списка, закладки, ходить по другим элементам -- операций не видно.
Помогает только или кнопка "Обновить" или переключение в другой раздел.

**Comment by alex-kukhtin** [comment]
FIxed in 7273
