### ISSUE TITLE
[Улучшайзинг] Сделать физлиц нормальными контрагентами. 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#388]
Масса народу требует возмо;ности работать с физлицами как контрагентами со всеми вытекающими последствиями.

Барыгам почти все равно, а вот продавцы услуг и т.п. массово плюются и считают систему непригодной.

масса народу хочет работать с физиками персонализировано
видеть контакты/операции по каждому физику

и таки да, с элементами оперативного учета и "CRM за 200 грн"(tm)

**Comment by nik-man** [comment]
https://github.com/a2develop/bugTracker/issues/284

**Comment by alex-kukhtin** [comment]
Done in 7297
