### ISSUE TITLE
Главная страница. При положительном балансе панель"Ваш личный счёт" должна быть зелёной

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/bugTracker#389]
Сейчас красная всегда

**Comment by alex-kukhtin** [comment]
Done in 7302

**Comment by Illya-Lykhachov** [comment]
![image](https://user-images.githubusercontent.com/35328100/45263178-2e699700-b42d-11e8-9b67-560a904bbe5c.png)
Версия последняя.
this.Tenant.$IsTrial = False
Balance.Amount никак не проверяется

**Comment by alex-kukhtin** [comment]
Fixed in 7303
