### ISSUE TITLE
Бухгалтерія - Інші операції. - Операції: Непонятный фильтр по вступ. балансу.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#390]
В фильтре по типу операций не совсем понятно названы операции по вступительному балансу.
Например, тип операции называется просто "По касі" (а що по касі?)
И остальные также.

![2018-07-30](https://user-images.githubusercontent.com/35918141/43392068-322da748-93fb-11e8-9628-6f64ad1b46ad.png)

С другой стороны, типов операций по вступительному балансу много, а использоваться будут редко. Может быть сделать какой-то общий фильтр "Вступительный баланс" ?

**Comment by shevchuk-vadim** [comment]
Я выделил операции вступительного баланса в отдельный пункт меню.
А в курсовых разницах дописал в начале "Курсові різниці".
