### ISSUE TITLE
Дубликаты документов. Сохранение или Проведение может создавать дубликаты.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#393]
Давно уже заметил этот глюк. Но его сложно поймать.
Появляется как будто само, просто не замечаешь.
Создаешь документ, что-то внес, сохранил, что-то внес, сохранил...
В какой-то момент видишь, что создал два документа. Обычно кажется, что затупил.
Касается любых документов.

Сегодня понял, когда это появляется.
В случае, если процесс сохранения или проведения занимает какое-то время, но при этом кнопка "Сохранить" или "Провести" все еще активна, можно клацнуть ее второй или даже третий раз.
Потом всплывает одно, второе, третье окно подтверждения и пользователь автоматически подтверждает. Получается такое:

![2018-07-30](https://user-images.githubusercontent.com/35918141/43398446-bfa16a0a-9410-11e8-9171-be84eb638f8c.png)

А в базе появляется два или даже три идентичных документа:
![2018-07-30](https://user-images.githubusercontent.com/35918141/43398821-cb139826-9411-11e8-8c2b-ca7ad6b070d7.png)

**Comment by mik-man** [comment]
Кстати, кнопка "Заповнити", например, тоже может сработать два раза:

![2018-07-30](https://user-images.githubusercontent.com/35918141/43399579-19fd921e-9414-11e8-8279-ac9fd2daa050.png)

Хотя, конечно, это не так важно, как задвоение документов.

**Comment by alex-kukhtin** [comment]
Fixed in 7302
