### ISSUE TITLE
Инвентаризация. Поля "Ціна" и "Кількість" узкие и не расширяются.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#396]
Даже в самом широком варианте документа цены и количество документов остаются узкими.

![2018-07-31](https://user-images.githubusercontent.com/35918141/43450988-9959360a-94bc-11e8-9f25-a323d6110664.png)

**Comment by AlexeyTishkin** [comment]
https://github.com/alex-kukhtin/A2v10/issues/109

**Comment by AlexeyTishkin** [comment]
Сделать автоширину пока нельзя. Сделал колонки шире. Посмотри.

**Comment by mik-man** [comment]
Стало лучше. )
