### ISSUE TITLE
Оприбуткування из Інвентаризації. Не печатается номер документа.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#397]
Если создать "Оприбуткування" как отдельный документ, то все ок.
А если из "Інвентарізації", то при печати нолик вместо номера.

![2018-07-31](https://user-images.githubusercontent.com/35918141/43452654-a1729f12-94c0-11e8-8132-33a3e630afbd.png)

**Comment by mik-man** [comment]
Да, "Акт списання" из инвентаризации то же самое:

![2018-07-31](https://user-images.githubusercontent.com/35918141/43453859-dda75812-94c3-11e8-85d4-a814ec795244.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
