### ISSUE TITLE
Экспорт услуг. Замечания по печатной форме.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#398]
В левой (английской) части не хватает:
* название Моей фирмы
* адрес Моей фирмы
* договор

Наименование услуг нет на английском (может оно и правильно, не знаю)

Если не заполнено поле "Сплатити до" то внизу появляется дата оплаты "01.01.1900"

![2018-07-31](https://user-images.githubusercontent.com/35918141/43461045-185dcf06-94db-11e8-9836-c232b258a3c4.png)

**Comment by AlexeyTishkin** [comment]
название Моей фирмы, адрес Моей фирмы - в свойствах "моей фирмы" заполнено наименование и адрес на наглийском ?
договор - в свойствах договора заполнен предмет на английском ?
Наименование услуг нет на английском - наименование только одно, пиши сразу двойное.
Если не заполнено поле "Сплатити до" то внизу появляется дата оплаты "01.01.1900" - а что там должно отображаться ?

**Comment by mik-man** [comment]
Разве в свойствах Моей фирмы есть наименование и адрес на английском?

`Если не заполнено поле "Сплатити до" то внизу появляется дата оплаты "01.01.1900" - а что там должно отображаться ?`
Не знаю, может ставить плюс месяц к дате документа, например?

**Comment by AlexeyTishkin** [comment]
> Разве в свойствах Моей фирмы есть наименование и адрес на английском?

Потерялось при последних переделках в мастера... Создай отдельный issue по поводу свойств "моей фирмы".

**Comment by AlexeyTishkin** [comment]
В свойствах договора закладка "ЗЕД" осталась.

**Comment by AlexeyTishkin** [comment]
> Не знаю, может ставить плюс месяц к дате документа, например?

Чем это будет лучше ?
Надо узнать, является ли эта дата для инвойса обязательной. Если является, то в документе ее надо подсвечивать, если не является, то как должен выглядеть текст.

**Comment by mik-man** [comment]
`Надо узнать, является ли эта дата для инвойса обязательной. Если является, то в документе ее надо подсвечивать, если не является, то как должен выглядеть текст.`
Дата не является обязательной.
Если ее нет, надо ставить пустое место для даты типа "__  _______ 20___"

**Comment by alex-kukhtin** [comment]
Вместо 01.01.1900  нужна пустая строка.

**Comment by alex-kukhtin** [comment]
А что - пустая дата в базу пишется не как null? - это неправильно. Если так - напишите мне issue в A2v10.

**Comment by AlexeyTishkin** [comment]
В базу пишется все правильно. Stimulsoft с null оригинально работает. Сейчас переделаю.

**Comment by AlexeyTishkin** [comment]
> Вместо 01.01.1900 нужна пустая строка.

Переделал.

**Comment by mik-man** [comment]
Теперь фразы получились какие-то незаконченные. Может там вместо пустой даты ставить какие-то подчеркивания, типа "_____________".

![2018-08-03](https://user-images.githubusercontent.com/35918141/43636840-e8ff070a-971b-11e8-9b0b-d3b10e8cac4f.png)

**Comment by AlexeyTishkin** [comment]
Изменил.
