### ISSUE TITLE
Диалог свойств Моей фирмы. Нет закладки "ЗЕД"

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#399]

**Comment by Anestezia** [comment]
Все еще нет вкладки ЗЕД.
![image](https://user-images.githubusercontent.com/42540074/52421593-02962e80-2afd-11e9-99b5-e370ba672721.png)
Здесь нужно название банка? Для чего это поле?

**Comment by AndriyNesterenya** [comment]
Все еще нет.

**Comment by AlexeyTishkin** [comment]
Добавлены свойства: "Здійснюється зовнішньоекономічна діяльність", "Назва англійською мовою", "Адреса англійською мовою".
