### ISSUE TITLE
[Dev][Bug] Запасы -> Операции  - не отображается список операций

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#401]
На Dev в Запасы -> Операции  - не отображается список операций.
Кол-во операций отображается.

![image](https://user-images.githubusercontent.com/38098758/43541443-2069adb6-95d3-11e8-894b-0291e21a18e3.png)

**Comment by AlexeyTishkin** [comment]
Кто-то запустил старый скрипт... Починил.
