### ISSUE TITLE
[Bug] Не дает принять на работу кассира

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#402]
Был принят на работу сотрудник в роли кассира.
В последствии был уволен (до того отправлен на больничный и в отпуск).
При попытке взять на работу нового кассира - сообщение 
![image](https://user-images.githubusercontent.com/38098758/43547080-e647a3ee-95e2-11e8-978a-e8315c11a521.png)

От принимаемого физлица не зависит.

**Comment by Illya-Lykhachov** [comment]
Повторить проблему не удалось. Подозреваю, что проблема в понимании даты увольнения. В приказе об увольнении дата увольнения - рабочий день для увольняемого сотрудника. Т.е. нового кассира нужно принимать следующим днём.
