### ISSUE TITLE
Человек смертен, даже если он - сотрудник. Нужна причина увольнения "Смерть".

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/bugTracker#404]
Кроме того, когда работодатель хочет уволить вполне живого, но нерадивого сотрудника, ему могут понадобиться такие причины:

Невідповідність посаді (ст.40 п.2 КЗпПУ),
Поява у нетверезому стані (ст.40 п.7 КЗпПУ),
Розкрадання майна (ст.40 п.8 КЗпПУ),
Позбавлення волі (ст.36 п.5 КЗпПУ).

**Comment by Illya-Lykhachov** [comment]
Пользователь может добавлять причины в справочник самостоятельно. На старте добавил только часто встречающиеся. Для облегчения участи пользователей и для примера. Все случаи жизни добавлять не нужно!

**Comment by Illya-Lykhachov** [comment]
"40.2 Невідповідність працівника займаній посаді", кстати есть

**Comment by shevchuk-vadim** [comment]
И все таки "Смерть" надо добавить. К сожалению, работники умирают. И клиенты будут звонить на поддержу с вопросами, как это отразить в отчете. А причина увольнения в таблице 5 должна быть "Інша". Если об этом заранее не знать, то сам не догадаешься.

**Comment by Illya-Lykhachov** [comment]
добавил

**Comment by shevchuk-vadim** [comment]
Не совсем правильно. Підстава звільнення повинни бути просто "Інша", а не "ст. КЗпПУ - Інша". У тому й справа, що у КЗпПУ немає такої статті.

**Comment by Illya-Lykhachov** [comment]
"Інша" теперь имя и системная
