### ISSUE TITLE
Статус партнера. В некоторых случаях не показывает номер документа или счета.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#405]
В настоящий момент не показывает номера расчетных счетов,
номера Акт услуг и номера корректировок НН.
(думаю, еще что-то есть, надо просматривать)

![2018-08-02](https://user-images.githubusercontent.com/35918141/43578173-a22d4e9c-9656-11e8-8fdf-106e94c84c38.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
