### ISSUE TITLE
Возможно установить дубликат ЄДРПОУ/ІПН.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#408]
Открыть свойства любого контрагента.
Ввести дубликат.
Подсветит красным.
Нажать кнопку "Сохранить и закрыть"
Краснота исчезает.
Снова нажать кнопку "Сохранить и закрыть"
Готово.

В мастере создания тоже так работает, но сначала надо ввести корректный код, чтобы допустило до кнопки "Готово", а потом уже по той же схеме.

**Comment by alex-kukhtin** [comment]
Done in 7302
