### ISSUE TITLE
Створення прайс-листа - при изменения типа цен с основного на другой, исчезает строка для вывода цены

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#409]
![photo_2018-08-03_13-30-14](https://user-images.githubusercontent.com/38099938/43638443-8b98a30e-9721-11e8-9f37-7d2a2621707f.jpg)
![photo_2018-08-03_13-30-26](https://user-images.githubusercontent.com/38099938/43638444-8eccedbe-9721-11e8-8a65-f9707c5208d2.jpg)

**Comment by AlexeyTishkin** [comment]
А в новом выбранном прайсе есть виды цен ?

**Comment by kattrina-brekhova** [comment]
вот собственно и хотела сделать новый прайс лист с ценами.

**Comment by AlexeyTishkin** [comment]
Виды цен добавляются в свойствах прайс-листа. В операции "Створення прайс-листа" устанавливаются значения цен.
