### ISSUE TITLE
Нет возможности принять одного и того же человека на основное место работы и за совместительством - запрет

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#410]
Логика в том, чтобы запретить есть. Но может рассмотреть вариант возможности принятия, если в одном из приказов о приеме на работу, установить ""работа за совместительством"
![photo_2018-08-03_13-40-51](https://user-images.githubusercontent.com/38099938/43638817-dd557e0a-9722-11e8-94ef-5c58bf6e8f27.jpg)

**Comment by Illya-Lykhachov** [comment]
И это правильно. Основное место работы или совмещение - это где его трудовая находится. Она не может быть одновременно и у нас и у другого предприятия.
Не нужно путать с "внутренним совмещением", когда сотрудник работает на нескольких должностях (одна основная, другие совмещает). Такого нет и в простой зарплате не предусматривалось
