### ISSUE TITLE
Больничный лист. Валидация даты закрытия.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#411]
Требует дату закрытия больничного листа не позже чем дату самого больничного.
Хотя обычно дата больничного листа совпадает с датой начала болезни, т.е. заведомо раньше закрытия.
Наверное, просто не с той датой сравнение. :)

![2018-08-03](https://user-images.githubusercontent.com/35918141/43643032-77774b94-9732-11e8-880f-b15044090824.png)

**Comment by Illya-Lykhachov** [comment]
"Хотя обычно дата больничного листа совпадает с датой начала болезни..."
Ни разу больничный не получал, но по-моему больничный лист выписывается в момент окончания болезни (выписки человека из больницы)

**Comment by AlexeyTishkin** [comment]
Нет. Больничный может многократно продлеваться. Есть дата закрытия. А выписывается в момент начала болезни.

**Comment by Illya-Lykhachov** [comment]
т.е. заболел, пришел в больницу, тебе выписали больничный (с непонятной датой закрытия) и пошел болеть строго до этой даты?
При продолжением болезни каждый раз выписывается новый больничный

**Comment by AlexeyTishkin** [comment]
Без даты закрытия. Просто открыли. После каждых 10 дней больничный должен быть продлен или закрыт. Новый выписывается если предыдущий закрыт и прошло какое-то время. Также новый выписывается если текущий продлевался много раз (на бланке нет места для продления).

**Comment by Illya-Lykhachov** [comment]
т.е. в случае продления больничного, сотрудник каждый раз приносит в бухгалтерию один и тот же больничный лист (пока на бланке есть место)?

**Comment by AlexeyTishkin** [comment]
Не закрытый больничный на руки не выдается. В бухгалтерию нечего приносить, т.к. если больничный еще не закрыт и может быть продлен, то сотрудник еще болеет.

**Comment by Illya-Lykhachov** [comment]
если не выдаётся, то подозреваю что и не оформляется. Когда всё же доходит до оформления (по любой причине: выздоровел, бланк закончился (который и не оформлялся!)), какая дата самого больничного ставится: дата начала болезни или дата оформления (выписки) этого листа?

**Comment by AlexeyTishkin** [comment]
Оформляется и хранится в твоем деле (карточке). Есть журнал регистрации. Больничный задним числом открыть нельзя.

**Comment by shevchuk-vadim** [comment]
Больничный открывается в начале болезни. И дата у больничного - это дата начала болезни. Или может быть раньше даты болезни, если больничный выписываеотся не по факту болезни, а в плановом порядке (например, больничный по беременности и родам).
Продление больничного - это не дописывание, а закрытие старого, и выписка нового. Например, человек лежал в стационаре, ему там закрыли больничный, и выписали на амбулаторное лечение по месту жительства, где ему выписали новый больничный. В бухгалтерии этот второй больничный должен бвть проведен полностью за счет фонда.

**Comment by AlexeyTishkin** [comment]
Даты самого больничного, как таковой - нет. Есть "Виданий" - дата выдачи, в большинстве случаев дата оформления. Если закрывается, то есть "Стати до роботи" - фактически дата закрытия листа. Если будет продлеваться, то "продовжує хворіти" и номер след. больничного.

**Comment by Illya-Lykhachov** [comment]
Ты не понял. Если сотрудник болеет больше 10 дней, ему выписываю больничный лист, который должен попасть в бухгалтерию для начисления. Через 10 дней ему выписывают очередной больничный лист с отметкой "Продолжение" и датой начала болезни из первого больничного. И так пока не выздоровеет. Второй и последующие больничные в нашей программе создаются из первого или последующих как связанный документ со всеми вытекающими.
В любо случае это будет несколько больничных листов

**Comment by AlexeyTishkin** [comment]
> и выписали на амбулаторное лечение по месту жительства, где ему выписали новый больничный

И этот новый больничный может продлеваться каждые 10 дней.

**Comment by AlexeyTishkin** [comment]
> Через 10 дней ему выписывают очередной больничный лист с отметкой "Продолжение"

Нет. Не новый. Продлевают текущий. На руки не выдают до закрытия.

**Comment by Illya-Lykhachov** [comment]
> Даты самого больничного, как таковой - нет. Есть "Виданий" - дата выдачи, в большинстве случаев дата оформления. 

Именно в этой дате вопрос!
Именно дата оформления (выписки листа, выдачи)и имеется в виду

**Comment by Illya-Lykhachov** [comment]
> Оформляется и хранится в твоем деле (карточке). Есть журнал регистрации. Больничный задним числом открыть нельзя.

Ты не понял. Если сотрудник болеет больше 10 дней, ему выписываю больничный лист, который должен попасть в бухгалтерию для начисления. Через 10 дней ему выписывают очередной больничный лист с отметкой "Продолжение" и датой начала болезни из первого больничного. И так пока не выздоровеет. Второй и последующие больничные в нашей программе создаются из первого или последующих как связанный документ со всеми вытекающими.
В любо случае это будет несколько больничных листов

**Comment by shevchuk-vadim** [comment]
Это дата выписки (открытия) листа.

**Comment by AlexeyTishkin** [comment]
> Именно в этой дате вопрос! Именно дата оформления (выписки листа, выдачи)и имеется в виду

Это дата начала болезни.

**Comment by AlexeyTishkin** [comment]
Илья, у тебя дубликат ответа пошел.

**Comment by Illya-Lykhachov** [comment]
т.е. сотрудник заболел 5-го, выздоровел 10-го, ему выписали больничный лист 10-го и дату самого листа указали 5-е?

**Comment by AlexeyTishkin** [comment]
Выписали 5-го, закрыли 10-го. Дата выписки будет 5-е, т.к. неизвестно когда он будет закрыт.

**Comment by shevchuk-vadim** [comment]
Леша прав.

**Comment by Illya-Lykhachov** [comment]
Вот бланк больничного листа:
![listok_nepracezdatnosti](https://user-images.githubusercontent.com/35328100/44390351-c31b5c00-a535-11e8-8217-4e8f5a445b07.gif)

там есть поле "Виданий". В этом поле какая дата ставится: выдачи или начала болезни?

**Comment by AlexeyTishkin** [comment]
Дата оформления. Она меньше или равна началу болезни.

**Comment by mik-man** [comment]
"Наказу" -- опечатка, наверное. По больничному же не появляется приказ.

![2018-08-22](https://user-images.githubusercontent.com/35918141/44454371-fe845c00-a603-11e8-8044-2fb3e2662571.png)

**Comment by Illya-Lykhachov** [comment]
сделал другое сообщение
