### ISSUE TITLE
Передача денег из кассы в банк. Платежное поручение не заполняется и не проводится.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#413]
Бухгалтерія - Кассові операції - Операція "Видаток на рахунок в банк"

При проведении РКО появляется связанное платежное поручение.
Там не заполнены поля "Платник" и "Код платника", (они подсвечены розовым)
и при этом они закрыты для редактирования.
Проведение платежки невозможно.

![2018-08-03](https://user-images.githubusercontent.com/35918141/43644214-b3f882f0-9736-11e8-8531-fa6e9fee27c8.png)

**Comment by shevchuk-vadim** [comment]
Разрешил выбирать контрагента.

**Comment by mik-man** [comment]
В деве все ок.

А на бете и сервисе теперь еще и не работает автонумерация и поточний рахунок не подставляется.

![2018-08-10](https://user-images.githubusercontent.com/35918141/43964888-7fb2295c-9cc6-11e8-9a44-6411671c19a6.png)
