### ISSUE TITLE
Уникальность телефонного номера аккаунта.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#416]
Если оплата будет идентифицироваться по номеру телефона, то он должен быть уникальным для каждого аккаунта?

**Comment by alex-kukhtin** [comment]
То есть ты хочешь завести пару аккаунтов на один телефон?

**Comment by mik-man** [comment]
> То есть ты хочешь завести пару аккаунтов на один телефон?

Такое вполне возможно. Человек может завести сколько угодно емейлов, но кол-во телефоннных номеров всегда ограниченно.

**Comment by mik-man** [comment]
https://github.com/a2develop/bugTracker/issues/493
Ну, похоже, что закрыто.
