### ISSUE TITLE
Подтверждение телефонного номера. Непонятная ошибка и успех.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#417]
* Если код оператора/города неверный -- выдает непонятную ошибку.

![2018-08-06](https://user-images.githubusercontent.com/35918141/43715960-f623a302-998a-11e8-8152-ada4f4a09996.png)

* Ну и желательно в случае успеха, всплывающее сообщение мол "Підтверджено вдало"

**Comment by mik-man** [comment]
* Наверное, имеет смысл сделать небольшое ограничение по кол-ву неудачных попыток подряд.
Пользователь может анонимно спамить чужой телефон (намеренно или по криворукости).
Например, не более 3-х попыток в час.

**Comment by alex-kukhtin** [comment]
Fixed in 7293
