### ISSUE TITLE
Емейл с большой буквы и восстановление пароля.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#419]
При восстановлении пароля для одних аккаунтов выдает ошибку, для других просто ничего не высылает. (на деве все ок)

![2018-08-07](https://user-images.githubusercontent.com/35918141/43779311-c621ab00-9a60-11e8-8f53-2598937a133a.png)

Ошибку выдает для:
anestezia44@gmail.com
nikman@a2.net.ua
2@a2.net.ua
info@bookkeepertech.com

**Comment by mik-man** [comment]
Скорее всего как-то связано.
При входе, если емейл с большой буквы, выдает ошибку.

![2018-08-07](https://user-images.githubusercontent.com/35918141/43831198-0446f1aa-9b0c-11e8-9a9e-14b2619501cd.png)

**Comment by alex-kukhtin** [comment]
Вроде уже починили.
Проверь.

**Comment by mik-man** [comment]
1. Восстановление пароля работает.
2. Логин с большой буквы -- осталось как было.

**Comment by alex-kukhtin** [comment]
Логин на деве попробовал. Работает.
В облаке пока не исправляли. Публикации же не было :-)

**Comment by alex-kukhtin** [comment]
Подправил для сброса пароля. Только на деве. Пробуй и закрывай
