### ISSUE TITLE
Раздел "Бухгалтерія" - список документов создания не отображается.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#425]
Только для новых аккаунтов. В существующие все ок.
Только в разделе "Бухгалтерія", для всех подразделов.

![2018-08-13](https://user-images.githubusercontent.com/35918141/44021481-986bae54-9eed-11e8-833a-d03c0eeb442a.png)

**Comment by alex-kukhtin** [comment]
Вадим! Забыл onCreateTenant!

**Comment by shevchuk-vadim** [comment]
Да ничего я не забыл.

Проблема была только до тех пор, пока не отредактируешь свойства моей фирмы.

Потому что  Agents.Type where Id = 1 было равно null. Добавил coalesce.
