### ISSUE TITLE
Довідники. Вид диалогов свойств.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#426]
Диалоги некоторых справочников имеют недоработки:

- [x]  Одиниці виміру:		Властивості (чого?).
- [x]  Групи об'єктів:		Новий (що?), Властивості (чого?), нема кнопки хелпу.
- [x]  Проекти:			Новий (що?), Властивості (чого?), нема кнопки хелпу.
- [x]  Склади:				Новий (що?), Властивості (чого?), нема кнопки хелпу.
- [x]  Валюти:			Новий (що?), Властивості (чого?).
- [x]  Країни:				Новий (що?), Властивості (чого?), нема кнопки хелпу.
- [x]  Прайс-листи:		Новий (що?), Властивості (чого?), нема кнопки хелпу.
- [x]  Посади:			нема кнопки хелпу.
- [x]  Причини звільненя:	нема кнопки хелпу.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by mik-man** [comment]
Остались кнопки хелпа в довідниках персоналу. Но то мелочь, думаю, сделаем по ходу релиза. Закрываю.

**Comment by Illya-Lykhachov** [comment]
добавил
