### ISSUE TITLE
Ошибка списания. ФИФО можно нарушить.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#429]
1. Создать расходную накладную (например, за 5-е число)
2. Создать расходную накладную более ранним числом (например, за 4-е)
В итоге первыми спишутся более поздние партии.

![2018-08-14](https://user-images.githubusercontent.com/35918141/44082685-9db898b8-9fba-11e8-8ada-349a69e85827.png)

Насколько я помню, ранее планировалось, что проведение расходной накладной должно запускать перепроведение всех более поздних расходных накладных с этим товаром.

**Comment by shevchuk-vadim** [comment]
Проще всего в данной ситуации запрещать проведение задним числом. То есть, если в документе есть объекты, по которым уже есть проведенные документы со списанием более поздней датой.

**Comment by AlexeyTishkin** [comment]
Абсолютно согласен.

**Comment by alex-kukhtin** [comment]
Надо вставить эту проверку и закрыть эту ошибку.

**Comment by AlexeyTishkin** [comment]
Добавил проверку.
