### ISSUE TITLE
Опечатка на форме подтверждения телефона

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#431]
Опечатка на форме подтверждения пароля

![image](https://user-images.githubusercontent.com/38098758/44108345-c322718a-a002-11e8-9b3d-fabd48df26b2.png)

"неОдоступними"

И не стоит ли заменить "Телефон не підтверджено" на "Номер телефону не підтверджено".
Или даже "Ви не підтвердили номер телефону."

**Comment by alex-kukhtin** [comment]
fiexd in 7274
