### ISSUE TITLE
[Улучшайзинг] Страница входа - дизайн и дополнения

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#433]
Консолидирую мысли по доделке страницы входа для обсуждения:

1. Расположить форму логина/пароля по центру экрана (?) ;
2. В footer`е О системе/Контакты/Условия сделать более заметными (шрифт увеличить);
3. Явно написать о бесплатном тестовом периоде.

to be continued...

**Comment by alex-kukhtin** [comment]
Сделано совсем по другому. Наверное можно закрывать?
