### ISSUE TITLE
Расчетная ведомость. Начисления и удержания нужно разнести по разным проводкам (TrNo).

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/bugTracker#435]

**Comment by Illya-Lykhachov** [comment]
теперь всё плоско - список проводок никак не группируется

**Comment by shevchuk-vadim** [comment]
Когда все плоско - это хорошо, и будет работать. Но идеологически правильнее (раз уж у нас дебет отделен от кредита) было бы сделать в удержаниях кредит - две проводки (для НДФЛ и ВС), а по дебету - одну, на общую сумму.

Еще нужно перепровести существующие документы. Проверочный запрос у меня все еще показывает несколько документов:
select Operation, TenantId, Document, TrNo, [1], [-1]
from
(
	select D.Operation, J.TenantId, J.Document, J.TrNo, J.DbCr, count(distinct J.AccCode) as [Count]
	from a2.Journal as J
	inner join a2.Documents as D on D.TenantId = J.TenantId and D.Id = J.Document
	group by D.Operation, J.TenantId, J.Document, J.TrNo, J.DbCr
) as src
pivot (sum([Count]) for DbCr in ([1], [-1])) as pvt 
where [1] > 1 and [-1] > 1;

**Comment by Illya-Lykhachov** [comment]
> Когда все плоско - это хорошо, и будет работать. 

Пока так и оставим.
Операции перепровёл, ошибок больше не наблюдается
