### ISSUE TITLE
[Улучшайзинг] Админка - дополнительный функционал

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#437]
Пока нет интеграции с CRM, пригодился бы следующий функционал в админ панеле:
- [x] Экспорт списка тенантов, с полной информацией о них (логин, имя, телефон, число транзакций и т.д.) в формате XLS или XML.
- [x] Отображение номера телефона в таблице тенантов (либо в отдельно открывающейся карточке тенанта).
- [ ] Удаление тенантов. Хорошо бы сделать какой-то предохранитель. Например, один админ помечает на удаление, другой админ просматривает и удаляет.
- [x] С целью оптимизации места в таблице, можно в колонке Хост, отбрасывать все что идет после первой "точки".
- [ ] Колонку "Пробный период до" заменить на "Оплачено до" или "Истекает" и использовать ее для понимания, в каком режиме сейчас работает пользователь (полный или ограниченный). В случае истечения срока, можно подсвечивать другим цветом (текст или ячейку).
- [ ] Добавить поле "Количество оплат", в нем отображать число платежей от этого тенанта. Если подсчет сложен, то хотя бы отображать "+" или "-", были или небыли оплаты.

**Comment by alex-kukhtin** [comment]
Насчет удаления - вообще нужно думать.

**Comment by DenisClone** [comment]
Добавил еще один пункт.

**Comment by DenisClone** [comment]
Добавил еще два пункта.
По поводу поля "Количество оплат" - нужно думать.
Как я понимаю в дальнейшем будет сформирован расширенный биллинг для партнеров. Там должна быть выборка по платежам за месяц от их клиентов, для расчета вознаграждения. Возможно тогда это будет отдельный финансовый блок в админке.

**Comment by alex-kukhtin** [comment]
Само собой. 
Просьба. Пожалуй не нужно делать такие сложные issue. Их потом очень неудобно отслеживать.
Этот оставь, но в дальнейшем лучше отдельные.

**Comment by DenisClone** [comment]
ОК.

**Comment by alex-kukhtin** [comment]
Изменил названия для хоста регистрации

**Comment by DenisClone** [comment]
Основные вопросы решены, остальное будем дорабатывать после принятия концепции админки.
