### ISSUE TITLE
На Бете ограничить новые регистрации (акк активируется только админом вручную) 

### ISSUE THREAD

**Issue by MaksymTikhomirov** [a2develop/bugTracker#438]

**Comment by MaksymTikhomirov** [comment]
?
На бете по-прежнему регятся все подряд

**Comment by alex-kukhtin** [comment]
Done in 7279

**Comment by mik-man** [comment]
Хорошо бы оставить возможность регистрации для тестерования и внутренних нужд, но сделать ее с дополнительным промежуточным этапом.

Например, письмо со ссылкой-подтверждением регистрации приходит не на указанный емейл, а на емейл администратора. Администратор, если считает нужным -- пересылает письмо уже пользователю. Либо пишет -- в регистрации отказано, обратитесь в службу поддержки.

**Comment by alex-kukhtin** [comment]
Хорошо бы научить всех мужиков французскому языку, чтобы они вдоль дороги стояли и барина приветствовали (с)

**Comment by alex-kukhtin** [comment]
Можешь себе записать в список того, что будем делать, когда сделаем все и будет скучно.
И закрыть нафиг этот issue.
