### ISSUE TITLE
Создать классификатор валют с возможностью импорта.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#439]

**Comment by alex-kukhtin** [comment]
Ну вот нафига он нужен? Нужно просто забить десяток используемых валют и не морочить голову ни себе, не людям.

**Comment by alex-kukhtin** [comment]
Леша, забей в тенанты десяток валют.
Доллар, евро, фунты, швейцарские франки.
Рубли НЕ НУЖНО!

**Comment by AlexeyTishkin** [comment]
Есть один момент... StimulSoft в прописи поддерживает только  "UAH", "USD", "EUR", "RUR".

**Comment by AlexeyTishkin** [comment]
Не кажется, что USD и EUR вполне достаточно для стандартного тарифа ?
