### ISSUE TITLE
Прайс-лист - отчет

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#441]
Было бы хорошо, если б можно было печатать документ. Например, для того, чтобы его давать потенциальным клиентам....это упрощает работу отдела продаж

**Comment by AlexeyTishkin** [comment]
Документ нужен для того, чтобы изменить цену на определенный набор товаров. Для просмотра (и печати) всего прайс-листа существует отчет (Продажи - Отчеты - Прайс-лист). Отчеты можно будет экспортировать в Excel.

**Comment by kattrina-brekhova** [comment]
я про него и говорю. только что подсказали, что можно делать это через Ctrl+P. А чайники, как я, без кнопки на панели не сразу догадаются. Значит здесь попрос кнопки

**Comment by AlexeyTishkin** [comment]
Ok.

**Comment by AlexeyTishkin** [comment]
Добавил кнопку "Печать".
