### ISSUE TITLE
Регистрация. При втором переходе по ссылке из письма выдает ошибку.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#443]
Регистрация нового аккаунта в целом проходит успешно, все  ок.
Но если второй раз перейти по ссылке, которая приходит в письме для подтверждения регистрации -- выдает сообщение об ошибке.

![2018-08-20](https://user-images.githubusercontent.com/35918141/44330582-0ca17380-a470-11e8-9660-2fa03e14e7dc.png)

Пользователю может быть непонятно это сообщение.
Наверное, лучше написать что-то вроде:
"Ваш обліковий запис вже активовано. Переходьте до сторінкі [входу в систему.](url)"

Ссылки-примеры для демонстрации:

дев: http://dev.a2start.com/Account/confirmemail?userId=486&code=gxcemeM9utJzmkBoWdwwkrlFltrFNjxlWZw%2BEcHBTiwAyrnCNHNYSObeT4T4P3gQMeuMA6UzI9SJhwKedAZXh4c3yF2pOoNlFOmd86foL%2BaxCBPDsOawte%2FP1%2FQ%2FM1Ygcm%2FPqA%3D%3D

бета: https://beta.bookkeepertech.com/Account/confirmemail?userId=261&code=VIgdgn6mu%2FkvobHRANRaLtm14Yfxn6cCahQQBTLOP33wc9MokR37ZOgt9ifvo5cYbyM4F%2FFY%2FFVHI8t%2FPBAkjHAJZY1c%2B9sMjqVUlLdIs5HxpDRlUV39mSvq4jLyr3yqYnxd%2FR3lzS9el%2Bw7M3uBBw%3D%3D

сервис: https://service.bookkeeper.kiev.ua/Account/confirmemail?userId=264&code=1g6cW3qIiXbgQCG%2Bki67d%2BRBmL%2FD6MBSMElHIBQ3mBZKnPylr%2BJd43dMT%2BJCOEUDBx5gtJMmLyuap2tOni0%2FaG6qBZuAgulECZMoqvVhZsAyZvk%2BcPL%2BQyYo7svMM9x5mS55pS6Wj%2BFRJhCqa4ivJQ%3D%3D

**Comment by alex-kukhtin** [comment]
Done in 7292

**Comment by mik-man** [comment]
Ссылка на дев и на бету выдают ок "При обробці запиту виникла помилка. Ваш емейл вже підтверджено."

А ссылка на сервис выдает только "При обробці запиту виникла помилка..."
