### ISSUE TITLE
Удалить операцию оплата поставщику из кассы раздел Приобретение

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#445]

**Comment by kattrina-brekhova** [comment]
![photo_2018-08-20_14-23-03](https://user-images.githubusercontent.com/38099938/44337814-9ce9b380-a484-11e8-9f0e-a07403d0706d.jpg)

**Comment by mik-man** [comment]
Платить наличкой поставщику-юр.лицу, конечно, нельзя.
Но поставщик может оказаться физ.лицом.
Поэтому совсем удалять данную операцию не надо.
Надо сначала добавить в Контрагенты тип "Физлицо", а затем данную операцию "Оплата постачальнику" переделать, чтобы можно было платить деньги только физ.лицу.

**Comment by kattrina-brekhova** [comment]
сейчас эта операция позволяет выбрать только юр.лицо. 
если речь идет о физиках - то да, приобретение юриками у физ лиц допустимо, только эти операции проблематичны. помимо обычной оплаты юрики начисляют пдфо и военный сбор, а потом еще суммы по таким операциям нужно показывать в отчете пдфо. 
на практике налоговые придираются к таким операциям..., но предприятия периодически их используют, да

**Comment by AlexeyTishkin** [comment]
> Надо сначала добавить в Контрагенты тип "Физлицо"

Уже добавлено.
Что теперь с этим issue ?

**Comment by shevchuk-vadim** [comment]
В этой операции теперь можно выбирать только физлиц и ФОП. Удалять эту операцию из списка уже не надо. Ишью можно закрывать.
