### ISSUE TITLE
Экспорт в Сонату. Непонятная ошибка при отсутствии лицензии на Сонату.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#446]
При попытке экспортировать отчет в Сонату выдает стандартное сообщение об ошибке.

![2018-08-20](https://user-images.githubusercontent.com/35918141/44351376-67f05780-a4aa-11e8-9dc0-912d3ff12fcc.jpg)

И не экпортирует.
Причина -- отсутствие лицензии на Сонату у конкретного ФОПа (или юрлица).
Надо это прописать соответствующим сообщением. Например: "Відсутня ліцензія на Сонату для ІПН (або ЄДРПОУ) 343400112244. Звіт не експортовано."

**Comment by alex-kukhtin** [comment]
Fixed in 7284

**Comment by alex-kukhtin** [comment]
fixed in 7285
