### ISSUE TITLE
Склады. Остатки по складам.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#45]
Поскольку есть склады, надо иметь возможность смотреть остатки по складу. И движение.
Варианты:
1. Запасы-Отчеты: добавить возможность указания склада в отчете. И добавить отдельно отчеты: "Обороты" и "Остатки"
2. В справочнике "Склады" должна закладка. И отчеты по складу: осв, обороты, остатки.
3. В справочнике "Объекты учета" можно добавить селектор склада:
Если склад не выбран — значит как сейчас, просто перечень общих остатков.
Если выбран — только остатки по текущему складу.

**Comment by AlexeyTishkin** [comment]
В диалог выбора объекта в товарных документах добавлен склад.

**Comment by AlexeyTishkin** [comment]
В справочнике "Объекты учета" в колонке "Залишок" добавлена ссылка. При клике на ссылке открывается окно с информацией об остатках в разрезе складов.

**Comment by AlexeyTishkin** [comment]
Отчеты - Оборотная ведомость по складу. Добавлена возможность выбора склада.
Объекты - Отчеты - Оборотная ведомость по складу. Добавлена возможность выбора склада.

**Comment by AlexeyTishkin** [comment]
> И добавить отдельно отчеты: "Обороты" и "Остатки"

Зачем нужны отдельные отчеты по оборотам и по остаткам ?

**Comment by AlexeyTishkin** [comment]
> В справочнике "Склады" должна закладка. И отчеты по складу: осв, обороты, остатки.

Нужно обсуждать необходимость перевода "Складов" в полноценный справочник (по аналогии с контрагентами).

**Comment by AlexeyTishkin** [comment]
> В справочнике "Объекты учета" можно добавить селектор склада:

В перечне остатки общие. Для детализации - popup.

**Comment by nik-man** [comment]
> Зачем нужны отдельные отчеты по оборотам и по остаткам ?
А разве не нужны? Посмотреть остатки на дату, посмотреть объем продаж за период.

**Comment by AlexeyTishkin** [comment]
> Отдельно посмотреть остатки на дату.

Чем в ОСВ остаток не нравится ?

> Отдельно посмотреть объем продаж за период.

Это вообще другой отчет. По складу не продажи, а расход, к тому же в ценах себестоимости.
