### ISSUE TITLE
Обратная связь. Продублировать контакты в форме.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#450]
Ссылка "контакты" внизу маленькая и неприметная.
Имеет смысл продублировать ее на форме обратной связи.

![2018-08-23](https://user-images.githubusercontent.com/35918141/44511852-6a78ca00-a6c1-11e8-8f09-039feaf5f9d2.png)

А может и весь список контактов показать -- места хватает.

**Comment by alex-kukhtin** [comment]
Done in 7285
