### ISSUE TITLE
Расширенный список (су, оу, договора). Закладка "Інформація" - сделать текст выделяемым.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#454]
Смотришь свойства СУ -- пытаешься скопировать емейл, чтобы отправить письмо и ой.

![2018-08-27](https://user-images.githubusercontent.com/35918141/44650337-fdca3c00-a9ee-11e8-9ef6-0dedf91e7fe7.png)

**Comment by alex-kukhtin** [comment]
Done in 7291
