### ISSUE TITLE
Об’єкти обліку: чи можна в картках додатково зробити можливість перегляду всіх цін за позиціями?

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#455]

**Comment by AlexeyTishkin** [comment]
Внутри диалога свойств или в списке на какой-то из закладок ?

**Comment by kattrina-brekhova** [comment]
на один объект может существовать 1 цена, а на другой - 5 разных цен.
я изначально подразумевала чтоб эта информация была в карточке объекта учета...
хотя может и не надо... у нас есть прайс-лист

**Comment by AlexeyTishkin** [comment]
В самом диалоге свойств не удобно будет. Есть мысль сделать отдельной закладкой, так чтобы история была видна...

**Comment by kattrina-brekhova** [comment]
да, учитывать даты изменений и созданий было бы хорошо, потому что отчет прайс-лист не дает возможности видеть эту историю

**Comment by AlexeyTishkin** [comment]
Добавлен диалог редактирования цен. Вызывается: при нажатии кнопки "Изменить" во всплывающем диалоге "Ціни", в списке объектов при клике на действие "Ціни". По смыслу - это развитие закладки "Цены", которая была раньше в свойствах объекта учета. Добавлен выбор прайс-листа, вида цены. Добавлена колонка "Створена", для значения цен, которые были добавлены операцией "Створення прайс-листа" в ней отображается гиперлинк с датой и номером документа (при нажатии открывается документ).

**Comment by mik-man** [comment]
Там ссылка на хелп неверная.
http://help.bookkeeper.kiev.ua/catalogs/prices
Точнее, ссылка как раз правильная.
В самом хелпе почему-то ссылка в единственном числе "price".

**Comment by kattrina-brekhova** [comment]
Ссылка на материал по прайс-листам вот: http://help.bookkeeper.kiev.ua/operations/sales/price
