### ISSUE TITLE
Інвентарізація. Треба три члена комісії.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#456]
Во всех бланках Акта инвентаризации, что можно нагуглить -- голова + три члена комиссии.
Причем есть свидетельства очевидцев, что в реальности действительно бывает четыре подписанта.
У нас сейчас только три (голова и два члена).
Наверное, надо сделать три члена комиссии.

![2018-08-27](https://user-images.githubusercontent.com/35918141/44652260-230d7900-a9f4-11e8-8084-a5d93a0e95ca.jpg)

**Comment by AlexeyTishkin** [comment]
Сделал четыре.
