### ISSUE TITLE
Прайс-лист, рахунок-фактура: при виборі тмц списком - номенклатура, що знаходиться на різних сторінках довідника, потрапляє лише однією (останньою) позицією

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#457]
Якщо позиції в довіднику знаходяться на різних сторінках, то в документ потрапляє лише одна позиція - та що була вибрана останньою
![photo_2018-08-27_12-32-26](https://user-images.githubusercontent.com/38099938/44652786-7fbd6380-a9f5-11e8-9401-92a0ddb637a3.jpg)
![photo_2018-08-27_12-33-00](https://user-images.githubusercontent.com/38099938/44652790-84821780-a9f5-11e8-95a9-534509ffa91b.jpg)
![photo_2018-08-27_12-33-33](https://user-images.githubusercontent.com/38099938/44652793-877d0800-a9f5-11e8-9989-15409ed086af.jpg)

**Comment by alex-kukhtin** [comment]
Это не баг а фича :-)
Переделать не получится - слишком неочевидная логика получается.
Будут добавляться "невидимые" записи.
Так что лучше всего как-то это написать,
Катя?
