### ISSUE TITLE
Окно ввода кода проверки телефона

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#459]
При вводе кода подтверждения из СМС, после заполнения поля, кнопка "Ок" остается не активной.
Кнопку нельзя нажать, пока не щелкнешь мышь по окну или не нажмешь кнопку "Enter".
Просьба от Сергея Черноуса, сделать кнопку активной без доп. манипуляций.

**Comment by alex-kukhtin** [comment]
Done in 7291

**Comment by alex-kukhtin** [comment]
Done in 7291
