### ISSUE TITLE
Порядок оповещений о необходимости подтверждения телефона.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#460]
По итогам разговора предлагается следующий порядок:
1. Для нового пользователя вообще не выводить на главной странице предложения подтвердить номер (в кабинете можно оставить как есть).
2. Через три дня сообщение появляется -- зеленого цвета и текст предлагающий.
3. Через половину триального периода сообщение становится желтое и текст меняется на напоминающий.
4. За три дня до окончания триального периода сообщение становится красным и текст предупреждающий.

Вот так, например:

(зеленый, появляется через три дня)
Приємно, що ви обрали наш сервіс! Для підвищення надійності вашого облікового запису пропонуємо вам активувати другий ступінь аутентифікації за номером телефону.

(желтый, через половину триала)
Сподіваємося, вам подобається працювати з нашим сервісом! Нагадуємо, для підвищення безпеки облікового запису бажано підтвердити ваш номер телефону.

(красный, за три дня до окончания триала)
Увага! Номер телефону не підтверджено. Деякі можливості сервісу недоступні. Для активації всіх можливостей сервісу, потрібно підтвердити ваш номер телефону.

**Comment by alex-kukhtin** [comment]
Done in 7295
