### ISSUE TITLE
Добавление в код страницы регистрации от Сонаты

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#461]
Предлагаю внести изменение в код страницы регистрации от Сонаты:

1. Скопируйте этот код в качестве первого элемента в разделе <HEAD> каждой страницы, которую нужно отслеживать. Если на странице уже есть Global Site Tag, просто добавьте в него строку config из фрагмента ниже. Это код от google analytics для отслеживания переходов.

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122489769-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-122489769-2');
</script>

2. Добавление тега <meta> для поисковых роботов. Этот тег запретит всем роботам не выводить указанную страницу в результатах поиска. Тоже (наверное) нужно выводить на всех страницах этого домена.

<head>
<meta name="robots" content="noindex" />
</head>

**Comment by alex-kukhtin** [comment]
Done in 7295.
