### ISSUE TITLE
[Улучшайзинг] Админка - Выделение не подтвержденных данных

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#462]
Сейчас в админке, возле не подтвержденных данных, отображается это сообщение – не підтверджено
Оно сильно съедает длину текущего поля, тем самым уменьшая длину других полей. Например поле имя, на моем скрине, слишком узкое.
Предлагаю это сообщение не выводить, а просто подсвечивать оранжевым цветом саму ячейку, данные в которой не подтверждены.
Если это сложно реализуемо, то хотя бы выводить короткой сообщение - «н/п» или «н.п.» или «нп»
![admin_panel](https://user-images.githubusercontent.com/42002015/44714567-51578b00-aabe-11e8-8feb-046f9223cef2.jpg)

**Comment by alex-kukhtin** [comment]
Там вообще-то строка подсвечивается желтым :-)

**Comment by DenisClone** [comment]
Да, строка целиком. Если убрать надпись "не підтверджено" в той или иной ячейке, то не будет понятно какие именно данные не подтверждены. 
А если подсвечивать только ячейку, сразу будет наглядно, без доп. подписей.

Либо, еще вариант: вместо текста выводить значок (картинку или юникод символ), или знак "-" с тем же оранжевым фоном.

В общем, что-то более короткое :)

http://www.webmasters.by/articles/html-coding/3397-useful-unicode-symbols.html

**Comment by alex-kukhtin** [comment]
Done in 7299

**Comment by DenisClone** [comment]
Супер!
