### ISSUE TITLE
295 грн. за что?

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#464]
Внутри системы в двух местах можно увидеть сумму 295 грн.
И нигде (внутри системы) не написано, за что или за какой период эта сумма.

![2018-08-29 295](https://user-images.githubusercontent.com/35918141/44773818-31859d00-ab7a-11e8-9810-06b43f56d758.png)

Наверное, везде надо добавить что-то вроде "(295 грн. на місяць)"

**Comment by mik-man** [comment]
Почему "done" ? В приведенных скриншотах ничего не изменилось.

**Comment by alex-kukhtin** [comment]
А что должно измениться? Согласовывайте!
Мне нужно КОНКРЕТНОЕ ЗАДАНИЕ. Добавить текст "ЧЧЧЧЧЧЧ" в "НННННН"!!!!!

**Comment by mik-man** [comment]
Вот так:

![2018-08-29 295 4](https://user-images.githubusercontent.com/35918141/45027438-0ef7f600-b04a-11e8-88db-cb3a39379e3f.png)

Слова "тарифного плану" можно сделать ссылкой на страницу с тарифами. Поскольку ее еще нет, пока просто на сайт http://bookkeeper.kiev.ua

**Comment by alex-kukhtin** [comment]
Все таки Done :-)
