### ISSUE TITLE
В личном кабинете добавить возможность создавать счет и платежку с реквизитами для оплаты абонплаты за доступ к системе

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#466]

**Comment by mik-man** [comment]
up
Есть ли определенность со сроками реализации?

**Comment by AlexeyTishkin** [comment]
Счет добавил.

**Comment by mik-man** [comment]
- [x] Нужно в номере счета указывать личный рахунок (ID клиента). Или телефон?
- [x] Еще нужно формировать платежку для оплаты наличкой через кассу банка.

**Comment by AlexeyTishkin** [comment]
В номере счета указал лицевой счет.

**Comment by AlexeyTishkin** [comment]
Платежка второй страницей.

**Comment by mik-man** [comment]
- [x] Если у ФОПа нет отчества пишет в названии "undefined"
- [x] Может быть надежнее указывать в назначении платежа номер и дату Рахунку "Згідно рахунку № 375/1809 від 18.09.05 за ліцензію... и т.д." ?
- [x] Раньше в примечании к Рахунку было четкие инструкции -- может быть их вернуть?
- [x] Может быть лучше печатать Рахунок и платежку на одной странице? Так сразу не видно, что там есть платежка.
- [x] В счете в поле "Виписав _______" можно добавить "директор Тіхоміров М.В."
- [x] Если будет на одной странице, то примечание к счету можно сделать в виде "Назначение платежа строго как указано в платежном поручении."
 
![2018-09-05](https://user-images.githubusercontent.com/35918141/45083586-eaad1f80-b104-11e8-95ef-11d472fa33fa.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
