### ISSUE TITLE
[Локализация]  При регистрации с неправильным email - кацапо-англоязычное сообщение об ошибке

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#467]
Если при регистрации ввести кривой мейл типа
shopopalo@ukr.net2
- имеем нелокализованное сообщение об ошибке

![image](https://user-images.githubusercontent.com/38098758/44799885-b2b25380-abbd-11e8-9c04-6d413436f46e.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7299
