### ISSUE TITLE
[Регистрация] Добавить на дашбоард надпись типа "Інформацію про рахунки ще надано" или скрывать блок счетов, пока счета не созданы.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#468]
Сразу после регистрации на дашбоарде светится некрасивый пустой блок счетов
![image](https://user-images.githubusercontent.com/38098758/44803307-c0b8a200-abc6-11e8-870a-b57c5ad3d62d.png)

Его стоит или скрывать, пока ни один счет не введен, или выводить строчку, что счета еще не созданы.

**Comment by alex-kukhtin** [comment]
Done in 7303
