### ISSUE TITLE
При отказе от оплаты - лишнее сообщение

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#470]
Если юзер полез в Ксбинет - Стан рахунку - Оплата картой, а потом по какой-то причине не смог/не захотел оплатить, но начал что-то вводить на форме оплаты и закрыл эту форму - при попытке просто закрыть нашу страницу оплаты появляется сообщение

![image](https://user-images.githubusercontent.com/38098758/44803887-6c162680-abc8-11e8-8eda-18a98e830d5e.png)

В результате от юзера требуется подтвердить изменения, которых с его точки зрения он не совершал.
Отказ от сохранения или закрытие сообщения не дает выйти из окна оплаты стандартной закрывалкой с крестиком, если не ткнуть на другой пункт меню.

**Comment by alex-kukhtin** [comment]
Fixed in 7299
