### ISSUE TITLE
Нет внятного уведомления о сроке триала и стоимости у новых юзеров + требования согласиться с правилами.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#471]
Таки нет ни в письме о регистрации, ни в сообщениях после первого входа нового юзера, сообщений, куда он вообще попал, сколько времени может пользоваться сервисом бесплатно и почем это будет стоить по истечении триального периода.

ИМХО стоит явно писать в письме об успешной активации - которого тоже нет, или хотя бы а дашбоарде при первом входе показывать всплывающее окно с текстом и галкой согласия с правилами предоставления услуг.

**Comment by alex-kukhtin** [comment]
Done in 7299
