### ISSUE TITLE
[Bug] Мелкий баг при создании контрагентов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#472]
Жмем на кнопку создания нового контрагента.
Кликаем на ФОПа
Передумали, кликаем на Юр. особу 
В поле "Назва" автоматом подставляется значение "ФОП"
В поле "Повна назва" автоматом подставляется значение "Фізична особа-підприємець"

**Comment by AndriyNesterenya** [comment]
Та же хрень при переключении с ФОПа на Нерезидента

**Comment by alex-kukhtin** [comment]
Fixed in 7297
