### ISSUE TITLE
Код счетчика переходов на страницах сервиса

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#473]
Для корректной фиксации переходов на страницы регистрации/входов на сервис, необходимо отображать код счетчика Гугла, только на трех доменах:
service.bookkeeper.kiev.ua
beta.bookkeeper.kiev.ua
sonata.bookkeeper.kiev.ua
Нужно изменить вывод метатегов по полному имени домена, а не только по первому слову, как сейчас.

Пример года счетчика Гугла:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122489769-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122489769-3');
</script>

**Comment by alex-kukhtin** [comment]
Done in 7298
