### ISSUE TITLE
ОУ. Импорт файла-образца для импорта не работает.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#477]
Обьекты учета, кнопка "Імпортувати"
Загрузить образец файла, выбрать образец файла, импортировать -- ошибка.

![2018-08-30](https://user-images.githubusercontent.com/35918141/44845916-89de9c80-ac57-11e8-8b0c-c73e78aefe48.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
