### ISSUE TITLE
[Улучшайзинг] Поведение поиска банка при пустом списке банков

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#480]
Мелкий интерфейсный косячок - непонятка

Человек зарегистрился в системе, начинает заполнять свойства фирмы.
При попытке создать счет попадает в список банков, который пока еще пуст.
Видит вверху строку поиска с "лупой" - возникает мысль поискать банк по названию.
Но пока список пустой, человек пишет название своего  банка в поле поиска, жмет Enter, ему показывают в поле %имябанка% и ничего больше не происходит.
Нужно как-то подсказать ему воспользоваться импортом.
Или автоматом вызывать импорт, если например список банков или результаты поиска пустые.
Или текстом на месте пустого списка написать "Заюзай Импорт справа вверху, и будет тебе щасте".

**Comment by shevchuk-vadim** [comment]
На эту тему уже есть ишью #223.
