### ISSUE TITLE
[Bug] очищать инфу в полях ФИО - названия при переключении типа предприятия в свойствах Своей фирмы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#481]
Продолжение уже исправленного бага в контрагентах.
Если при заполнении свойств Своей фирмы зайти в ФОП, начать заполнять любое поле, а потом переключиться на Юрлицо - криво переносит данные 
Пришли к необходимости очищать эти поля при переключении

**Comment by shevchuk-vadim** [comment]
По ходу возник вопрос, а в реальной работе будет ли когда нибудь пользователь переключать тип агента? Это потенциальный источник ошибок. Может, эту возможность надо давать только в мастере, на этапе создания?

**Comment by alex-kukhtin** [comment]
Done
