### ISSUE TITLE
[Администрирование] Удаление фиксированного списка тестовых аккаунтов на dev, beta, service

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#482]
Обсуждали задачу 
1. Создать фиксированный список тестовых аккаунтов на dev, beta, service, которые подлежат регулярному удалению после каждого круга тестирования.
2. Сделать какую-то страницу с кнопками вне админки, позволяющую убивать аккаунты на dev, beta, service все сразу или поштучно.
3. Запустить на эту страницу меня (+ уполномоченных лиц, ежели таковые понадобятся).

**Comment by alex-kukhtin** [comment]
Done
