### ISSUE TITLE
Задвоение военного сбора

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#485]
Я насчитала аванс и провела (станом на 16.04. за першу пол. квітня). 

Теперь автозаполнение документа Розрах. відомість за квітень. станом на 30.04. 
ПДФО береться з урахуванням раніше виплаченого, ЄСВ також, а от військовий збір не враховує раніше сплачене та задвоюється врешті решт. Например, из суммы 10 000 сняло в общем не 150 грн, а 221, 05 грн.
![1](https://user-images.githubusercontent.com/42540074/44984242-bc083b00-af84-11e8-8f6f-231170efe6fd.jpg)
![2](https://user-images.githubusercontent.com/42540074/44984243-bc083b00-af84-11e8-96e8-a1285e8b5855.jpg)

**Comment by Illya-Lykhachov** [comment]
Исправлено. Создай заново (или сними проведение и заполни) расчётную ведомость
