### ISSUE TITLE
Срочно!!! Невозможно сделать выплату аванса

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#486]
По некоторым месяцам при попытке выплатить аванс

 Документ Виплата.Каса. после нажатия кнопки Заполнить, ничего не происходит, хотя документ Начисление аванса за этот период уже проведен.
![3](https://user-images.githubusercontent.com/42540074/44984382-2c16c100-af85-11e8-9faa-1cb30554a52c.jpg)

**Comment by Anestezia** [comment]
Важно!!!!! В дальнейшей цепочке этих же документов идет непонятная накопительная логика из месяца в месяц при автозаполнении. И суммы не меняются даже если платеж проведен через кассу. Деньги выплачены, а документ показывает, что в прошлом месяце задолженность. начислено, но не выплачено.

**Comment by Illya-Lykhachov** [comment]
не повторяется проблема

**Comment by Illya-Lykhachov** [comment]
Выплату аванса не получится делать тем же документом, что и выплата задолженности. Выплачивая аванс мы ещё ничего не должны сотруднику (начислений ещё нет)
Сделаю отдельную операцию

**Comment by Illya-Lykhachov** [comment]
Для выплаты аванса нужно из документа расчёта аванса создать документ выплаты

**Comment by Anestezia** [comment]
Все работает корректно, я проверила. Арифметика подбивается верно в ведомости выплаты с учетом предыдущих выплат, даже с учетом старых не перепроведенных документов.
