### ISSUE TITLE
Отсутствует привязка расчета ЗП к срокам приема сотрудника

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#487]
Сотрудник принят с 27.04. Расчет ЗП за апрель от 30.04. Проработал 1 рабочий день, а не 19, как ставится по умолчанию при заполнении. 
![1](https://user-images.githubusercontent.com/42540074/44985040-93ce0b80-af87-11e8-9dc1-0ea13aa56e96.jpg)

П.С. Если сотрудник принят с 27.04., а мне нужно перепровести начисление аванса, то этот сотрудник отображается в ведомости за более ранний период, т.е. с начала месяца, да еще и с полным сроком, и его уже не удалить. Максимум могу 0 дней поставить и 0 грн. соответственно.
![3](https://user-images.githubusercontent.com/42540074/44985104-c7a93100-af87-11e8-896d-f4aa6414d35d.jpg)

**Comment by Illya-Lykhachov** [comment]
Как посчитать отработанные дни с учётом даты приёма?

**Comment by Anestezia** [comment]
Хотя бы сопоставлять дату документа (Аванс) и дату приема , и ставить запрет на подтягивание его данных, если он еще не принят в этом периоде. 
Количество отработанных дней в документе Розрахункова відомість можно пока не трогать. Вручную выставить не проблема.

**Comment by Illya-Lykhachov** [comment]
Изменил заполнение документа аванса. Если на дату документа сотрудник не принят, то и в документ он теперь не попадает.
Отработанные дни посчитать не могу, поэтому подставляю плановые. Возможно стоит отработанные дни вообще не проставлять, пусть всем вводят руками

**Comment by Anestezia** [comment]
Да, больше раньше времени не подтягивается сотрудник в расчет. Проверила.
