### ISSUE TITLE
Налоговая накладная - налоговый кредит - хочет, чтоб я приняла на работу глав буха, но мои налоговые по обязательствам проводит, т. к. ответственное лицо на предприятии есть

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#488]
![photo_2018-09-03_16-42-17](https://user-images.githubusercontent.com/38099938/44990091-9d13a400-af98-11e8-8dd6-18b2313dd9c1.jpg)
![photo_2018-09-03_16-43-42](https://user-images.githubusercontent.com/38099938/44990097-a0a72b00-af98-11e8-92de-68d7726cdea3.jpg)

**Comment by AlexeyTishkin** [comment]
Исправил.
