### ISSUE TITLE
Не заполняются автоматически отчеты регламентированные

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#490]
Додаток до декларации з ПДВ (Д1).

**Comment by AlexeyTishkin** [comment]
Предлагаю отсюда ПДВ убрать. Во-первых в одной issue не стоит смешивать разные проблемы. Во-вторых для ПДВ уже есть [300](https://github.com/a2develop/bugTracker/issues/300).

**Comment by Illya-Lykhachov** [comment]
Только ПДВ и оставили :)
Так что теперь это твоё  ;)

**Comment by AlexeyTishkin** [comment]
Подробней. Что имеется ввиду ?
