### ISSUE TITLE
Свойства ФОПа. Отчество -- неточная подсказка.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#492]
Для поля "По батькові" подсказка "Введить прізвище та ініціали"
Наверное, нужна типа "Введить по батькові"

![2018-08-30](https://user-images.githubusercontent.com/35918141/44994899-6abe7280-afa9-11e8-8129-fed2eeaff887.png)

**Comment by shevchuk-vadim** [comment]
ФОПами могут быть иностранцы, а у них может не быть отчества. Валидатор на отчестсве я пока отключил.
