### ISSUE TITLE
[Identification] Нужна надежная идентификация тенанта при оплате - телефон может быть неуникальным

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#493]
Выяснилось, что при оплате единственным идентификатором пользователя для нас является номер телефона.
А номер телефона может быть неуникальным - мы нигде не проверяем его на уникальность, в отличие от почты, и считали, что у юзера на одном телефоне может быть несколько аккаунтов.

Но если юзер решил заплатить за один из своих аккауунтов и попутно похерить второй - мы не можем отличить, за который из аккаунтов заплачено.

Выходов видится два:
1. Вводить уникальный "особовий рахунок" конкретного тенанта.
или
2. Требовать уникальности еще и номера телефона, что ИМХО не очень удобно всем.

**Comment by alex-kukhtin** [comment]
Done in 7300
