### ISSUE TITLE
Оплата не отобразилась в личном кабинете в сервисе

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#494]
Провели 3 тестовые транзакции на боевом сервисе, две на домене service и одна на sonata.
Ни одна из транзакций не отобразилась на личном счете в сервисе.
![tas_pay](https://user-images.githubusercontent.com/42002015/45021321-eff16800-b039-11e8-9695-a28f9214ca94.jpg)

**Comment by DenisClone** [comment]
Квитанция на e-mail тоже не пришла. Кто ее шлет, мы или они?

**Comment by alex-kukhtin** [comment]
Шлют они

**Comment by alex-kukhtin** [comment]
У тебя прикольный callback в настройках сервиса :-)

{requestUrl: 'https://api.tascombank.com.ua/api/checkout/url/', merchant: '****', password:'*********', callbackUrl:'http://dev.a2start.com/api/billing/callback'}

**Comment by alex-kukhtin** [comment]
Как ты понимаешь должно быть
https://service.bookkeeper.kiev.ua/api/billing/callback

**Comment by alex-kukhtin** [comment]
Коллбеки честно пришли на dev :-)

**Comment by alex-kukhtin** [comment]
Напиши мне новый issue с кодами BK-####, которые нужно подтвердить

**Comment by DenisClone** [comment]
По поводу квитанции им писать, или это может быть связано с неправильным колбеком от нас?

**Comment by DenisClone** [comment]
Я подумал что вы подправили строку колбэка, а вы подумали что я. Теперь я понял))
