### ISSUE TITLE
Перенести оплату с тестового на боевой сервер

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#495]
Три платежа ушли на тестовый сервер, вместо рабочего, их необходимо перенести.
Номера:
BK-2045 | 5*1891 | nikman@a2.net.ua | 2018-09-04 11:46:52 | 295.00 UAH | Успешен | 102
BK-2044 | 5*1891 | manklan@ukr.net | 2018-09-04 11:27:13 | 0.01 UAH | Успешен | 532
BK-2042 | 5*1891 | manklan@ukr.net | 2018-09-04 10:52:56 | 1.00 UAH | Успешен | 509

**Comment by alex-kukhtin** [comment]
Проверьте, плиз!
