### ISSUE TITLE
1 ДФ некорректный перенос в Сонату

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#496]
Дата принятия сотрудника на работу в 1ДФ заполняется автоматически правильно, но при переносе в Сонату теряется.
![1 1](https://user-images.githubusercontent.com/42540074/45026980-c25feb00-b048-11e8-9d57-79e896e62ab5.jpg)
![1 2](https://user-images.githubusercontent.com/42540074/45026981-c2f88180-b048-11e8-9598-59fe4bb047e1.jpg)

**Comment by AlexeyTishkin** [comment]
Попробуйте перезаполнить сейчас.

**Comment by Anestezia** [comment]
Уже все ок)
