### ISSUE TITLE
Податковий кредит Зайва людина підтягується в чужу накладну

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#499]
У документі Податковий кредит не повинно взагалі бути заповненим поле Посадова (уповноважена) особа / фізична особа (законний представник), тому що підтягується головний бухгалтер нашої фірми, по суті в чужу накладну. Хоча вона й не роздруковується, Користувачів це лякає.
![default](https://user-images.githubusercontent.com/42540074/45032306-3060de00-b05a-11e8-96c1-6de71f035a50.jpg)

**Comment by AlexeyTishkin** [comment]
Убрал заполнение.

**Comment by Anestezia** [comment]
У меня ничего не изменилось при  перепроведении старых накладных. В создании новых все ок.

**Comment by AlexeyTishkin** [comment]
В старых ничего не поменяется. А надо ?

**Comment by Anestezia** [comment]
Ладно, разберутся. Не будем усложнять. Главное, что в новых все ок.
