### ISSUE TITLE
1 ДФ отображение аренды в отчете

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#500]
Нужна функция отображения в отчете 1 ДФ, при автоматическом заполнении, данных о начислении доходов физическим лицам или ФОПам при аренде. (Ознака 106 та 157) 

физическое лицо - предприниматель пpи выплате доходов другoму физическому лицу - предпринимателю, кoторый нахoдится на общей системе налогооблoжения либo уплачивaет единый или фиксированный налог, oбязанo oтразить выплаченные доходы в налoговом расчете пo ф. N 1ДФ пoд признаком дохода "157" незaвисимo oт тoго, подлежат налoгообложению данные выплаты или нeт.

**Comment by Illya-Lykhachov** [comment]
Т.е. вопрос не только в аренде, а в любом перечислении денег с ФОП на ФОП?

**Comment by shevchuk-vadim** [comment]
Вопрос не только в ФОП, а и в простых физлицах. Разница в том, что нужно начислять и уплачивать налог за простых физлиц, а ФОПы это делают сами. Но в 1ДФ нужно включать и тех, и других.

**Comment by Illya-Lykhachov** [comment]
Дайте перечень операций, которые нужно включать в 1ДФ

**Comment by Anestezia** [comment]
Там большой список, пусть вручную вносят, кому что нужно. Не так это и много, чтоб автоматизировать. Снимаю задание.

**Comment by Anestezia** [comment]
Таки просят по ФОПам сделать автоподтягивание информации по 157 признаку.  Можно это?

**Comment by Illya-Lykhachov** [comment]
таки сделал
