### ISSUE TITLE
1 ДФ Звітна нова та Уточнююча. Не должна подбиваться сумма в І разделе

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#501]
Не должна подбиваться сумма в І разделе, так как мы вносим исправления, то есть записываем один рядок с ошибкой, а другой рядок уже без ошибки (и ставим соотвественно в гр.9 цифру 1 или 0). Указание общей суммы этих рядков - нонсенс. То же самое и в Уточняющей. У нас эти суммы даже вручную не уберешь.
![1](https://user-images.githubusercontent.com/42540074/45036118-483d5f80-b064-11e8-9aaa-83671757ce81.jpg)
![2](https://user-images.githubusercontent.com/42540074/45036119-483d5f80-b064-11e8-9f3e-54bd7c74ad5c.jpg)

**Comment by AlexeyTishkin** [comment]
Сделал.
