### ISSUE TITLE
1 ДФ проводится когда стоят все три варианта формы, а не должен.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#502]
Ставлю отметку в клеточке Звітна, Звітна нова та уточнююча одновременно, документ проводится. Передается в Сонату как Звітна и корректировке это поле больше не подлежит в Сонате. Желательно, чтоб единовременно можно было выбрать только один вариант формы документа.
![default](https://user-images.githubusercontent.com/42540074/45036513-5d66be00-b065-11e8-9d5b-14998bfb0781.jpg)

**Comment by AlexeyTishkin** [comment]
Изменил.

**Comment by Anestezia** [comment]
То же самое и в других отчетах наблюдается. Д5, Д1, Декларация з ПДВ, Д4.ЕСВ

**Comment by AlexeyTishkin** [comment]
В одном issue не смешиваем проблемы.

**Comment by Anestezia** [comment]
Работает корректно, можно задействовать только одну форму документа.
