### ISSUE TITLE
Податковий кредит та Розрахунок коригування Не удаляется причина не надання ПН отримувачу

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#504]
Если в ПН поставить галочку Не підлягає поданню отримувачу з причини...., а потом указать код причины, а потом стало ясно, что накладную все же нужно "выдать", то отменить это действие уже нельзя, остается только удалять эту накладную и создавать заново, так как код причины не удаляется, а при обновлении страницы еще и добавляется галочка - Не підлягає поданню отримувачу з причини.
![default](https://user-images.githubusercontent.com/42540074/45081329-a3706000-b0ff-11e8-87e0-5f7faa35608b.jpg)

**Comment by Anestezia** [comment]
В Податковому зобов'язанні та Розрахунку коригування это убирается, если нажать кнопку Оновити. А в ПКредите - нет.

**Comment by AlexeyTishkin** [comment]
Я переделаю логику. Причина будет зависеть от чекбокса. Чекбокс снят - причина пустая.

**Comment by AlexeyTishkin** [comment]
Причина теперь зависит от чекбокса.
