### ISSUE TITLE
Оплата поставщику с валютного счета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#505]
![photo_2018-09-05_11-59-55](https://user-images.githubusercontent.com/38099938/45082994-4a0a3000-b103-11e8-8e62-513b2bf02650.jpg)
сам валютный счет заведен
![photo_2018-09-05_12-00-52](https://user-images.githubusercontent.com/38099938/45083031-61491d80-b103-11e8-88e6-dd4582070f89.jpg)

**Comment by shevchuk-vadim** [comment]
Это был баг не в платежке, а во вступительном балансе. Там нельзя было выбрать валютный счет. Исправил.
