### ISSUE TITLE
Самостоятельный документ Податковий кредит не активно обязательное поле ипн

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#506]
если создавать не из счета ПН, а как самостоятельный документ, то при выборе контрагента его ИПН сам не подтягивается, хотя в карточку внесен и вручную написать его нельзя - поле не активно, при этом является обязательным для заполнения. Документ, вследствие этого, не провести.
![default](https://user-images.githubusercontent.com/42540074/45083653-14fedd00-b105-11e8-90b3-1d28bfb7d105.jpg)

**Comment by AlexeyTishkin** [comment]
Исправил.
