### ISSUE TITLE
Расходная накладная. Установить курсор на выбранном ОУ.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#51]
В Расходной накладной, когда объект учета уже установлен.
Пользователь нажимает на значок "лупа" и попадает на список ОУ.
При этом в списке не выделен тот ОУ, который установлен, его вообще может быть не видно.
Его приходится снова искать в списке.

**Comment by AlexeyTishkin** [comment]
А зачем его снова искать в списке ?

**Comment by nik-man** [comment]
Переименовать (если ошибка в названии).
Установить/изменить ед. измерения.
Установить/проверить цену.
Поменять на соседний, если случайно выбрал не тот.

**Comment by shevchuk-vadim** [comment]
Есть вариант - сделать в селекторе после иконки выбора иконку редактирования свойств выбранного элемента.

**Comment by nik-man** [comment]
Да, Алексей предложил то же самое.
Этот ишью закрываю, но открываю новый. ;)
Теперь везде будет иконка редактирования.

**Comment by nik-man** [comment]
Может быть иконку редактировани добавить на уровне платформы?
Т.е. любое поле выбора из списка должно иметь ее по умолчанию?

**Comment by AlexeyTishkin** [comment]
Добавил "гамбургер" во всех документах по товарам/услугам. Проверяй.

**Comment by nik-man** [comment]
Вау! Хорошо!

**Comment by AlexeyTishkin** [comment]
Если все ок - закрывай issue.

**Comment by nik-man** [comment]
Проверил. Работает. Ура! ))
