### ISSUE TITLE
Выписка ПН. Нет возможности редактировать некоторые поля раздела Б. Колонки 3.2, 9, 11.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#510]
Нужна возможность редактировать в Разделе Б колонки 3.2 Ознака импортного товару, 9 - код пільги, 11 - код виду діяльності сільгоспників. Сейчас они недоступны. 
![image](https://user-images.githubusercontent.com/42540074/45089675-99f1f280-b115-11e8-9249-5addabfadc07.png)

**Comment by AlexeyTishkin** [comment]
Ознака импортного товару - в свойствах товара "Країна походження".

**Comment by AlexeyTishkin** [comment]
9 - код пільги, 11 - код виду діяльності сільгоспників. Какая логика их установки ? В определенной накладной или привязка к какой-то сущности ?

**Comment by Anestezia** [comment]
Предлагается 9 и 11 просто сделать редактируемыми в бланке Податковий кредит та Податкове зобов'язання, чтоб не делать сложных привязок к объектам учета и добавление в них же отдельных граф.

**Comment by AlexeyTishkin** [comment]
Ок.

**Comment by AlexeyTishkin** [comment]
Сделал.
