### ISSUE TITLE
Отчет Д5 Невозможно создать Уточненку и Звитний новый

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#511]
Из-за того, что в документе "Розшифровка податкових зобов'язань і податкового кредиту в розрізі контрагентів (Д5)" нет кнопки Додати рядки и возможности **удалять рядки**, его возможно заполнить только кнопкой "Заполнить". Но данные подтягиваются только за текущий период не зависимо от того, какое число я ставлю и какой период указываю. При этом Позначка форми документа ставится автоматически на Звітний, и период, например, с 4 месяца меняется на 8 - текущий период. Соответственно, это делает невозможным создание форм Звітний новий та Уточнюючий.
![image](https://user-images.githubusercontent.com/42540074/45092304-a8440c80-b11d-11e8-8b12-616ada06dfcc.png)

**Comment by AlexeyTishkin** [comment]
Добавил возможность добавления/удаления строк.
