### ISSUE TITLE
[Улучшайзинг] Для новых регистраций ссылку на Початковий баланс - на дашбоард или в попап окно

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#512]
Новым юзерам при первом входе стоит явно предлагать вводить начальные балансы.
На дашбоарде или во всплывающем окне.

**Comment by alex-kukhtin** [comment]
Вопрос только в том, что считать первым входом?

**Comment by alex-kukhtin** [comment]
Вроде сделано в Welcome

**Comment by AndriyNesterenya** [comment]
Не вижу.

На дашбоарде есть счета и ссылка на свойства фирмы.

На окне приветствия есть только текст "Далі — створіть кілька елементів в довідниках «Об’єкти обліку» та «Контрагенти». І внесіть вступні залишки."
Где юзеру залишки искать - непонятно.

**Comment by alex-kukhtin** [comment]
Вот Коля пусть в свое окошечко и добавит :-)
Меня забанили - сказали я не понимаю нифига в окнах приветствия

**Comment by mik-man** [comment]
Добавил ссылку на Початковий баланс в окно приветствия.
