### ISSUE TITLE
Переименование пользователя - нелогично работает

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#513]
Мы позволяем изменить имя пользователя в личном кабинете

При этом в Информации о документах, даже созданных после переименования, продолжает отображаться старое имя. 
![image](https://user-images.githubusercontent.com/38098758/45094967-80f13d80-b125-11e8-98a4-64584bbb320c.png)

Какой смысл давать переименовывать юзера, если в системе это не отражается?

**Comment by alex-kukhtin** [comment]
Hужно перезайти в сервис.
Я никак не выкручусь - там так сделано.

**Comment by alex-kukhtin** [comment]
Нужно как-то эту фичу обыграть. Типа после переименования нужно перезайти. И по OK безусловно на страницу входа.

**Comment by AndriyNesterenya** [comment]
После переименования юзера и выхода-входа все равно ничего не меняется....

**Comment by alex-kukhtin** [comment]
fixed in 7348
