### ISSUE TITLE
[На обсуждение] Прайс-листы - логика, частности

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#514]
Очень непонятно работают прайс-листы.
Я лично вообще адски туплю, мне на голову не налазит как оно у нас работает.

На старте непонятно выводятся проценты 
![image](https://user-images.githubusercontent.com/38098758/45095562-0d503000-b127-11e8-9271-474a97e28e08.png)
Юзер сотворил товар.
Купил\получил по накладной по накладной по такой-то цене
Создал прайс-лист
В прайсе у него текущая цена значится нулевой и действующий процент отображается -100%

Что ему сделать, чтобы текущая цена стала ненулевой - не указывается нигде. 

Нужны или подсказки, или внятное описание логики работы

**Comment by AlexeyTishkin** [comment]
> В прайсе у него текущая цена значится нулевой и действующий процент отображается -100%

Так новый же товар, цены действующей нет. Что не так ?

**Comment by AlexeyTishkin** [comment]
> Что ему сделать, чтобы текущая цена стала ненулевой - не указывается нигде.

Текущая не может стать ненулевой. Нужно задать новую цену.

**Comment by AlexeyTishkin** [comment]
> Нужны или подсказки, или внятное описание логики работы

Где и какие ?

**Comment by AndriyNesterenya** [comment]
Просто инструкция пошаговая, как мы себе представляем правильную последовательность действий по формированию цен реализации, или как мы там их называем.

Как создать объект учета сам по себе или при оформлении входящего счета - интуитивно понятно.
Как принять счет, на его основе создать оплату и приходную накладную - интуитивно понятно.
У товара в этот момент есть входящая цена, но это делу не помогает :)
А вот что и как нужно сделать, чтобы появились какие-то отпускные цены и прайс-лист - без инструкцЫи нихрена не ясно даже после чтения хелпа в части http://help.bookkeeper.kiev.ua/catalogs/price .

Может какую-то демонстрационную последовательность действий на примере одного объекта учета сочинить?

**Comment by AlexeyTishkin** [comment]
> Может какую-то демонстрационную последовательность действий на примере одного объекта учета сочинить?

Может... Тогда это, наверное, к Коле...
