### ISSUE TITLE
[Улучшайзинг] Проекты - нельзя ли выводить информацию по проектам по аналогии с договорами?

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#517]
Напрашивается возможность вывести Проекты в левое меню, рядом с Договорами (хотя бы в Придбаннях та Продажах), и давать получать по ним информацию с том же стиле.
Насколько технически близки Договора с Проектами?
Очень геморройная затея?

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Щасте!
