### ISSUE TITLE
Розрахунок коригування до ПН. Нет возможности корректировать цену и др. причины

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#518]
Графа 2 «Причина коригування». Це може бути: «Повернення товару», «Зміна номенклатури», «Повернення попередньої сплати», «Зміна ціни», «Зміна коду товару за УКТ ЗЕД», «Виправлення помилки», у деяких випадках податківці вимагають помилкову причину конкретизувати, наприклад «Виправлення помилки в індивідуальному податковому номері покупця»
 
У нас только повернення товару, т.е. корректируется количество. А если изменилась цена, то нет возможности это отразить. Например:
![default](https://user-images.githubusercontent.com/42540074/45100430-198dba80-b132-11e8-85a7-a92e2c8aeb45.jpg)

**Comment by AlexeyTishkin** [comment]
>  А если изменилась цена, то нет возможности это отразить. 

Сделал.

**Comment by AlexeyTishkin** [comment]
Продолжаем в https://github.com/a2develop/bugTracker/issues/543
Этот можно закрывать.
