### ISSUE TITLE
ЕСВ табл. 5 некорректное автозаполнение

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#519]
- [x] 1.Отметка о том, что человек гражданин Украины по умолчанию ставит НЕТ. 
- [x] 2.Код категории особы - поставило, что нет трудовой книжки (2), лучше, чтоб по умолчанию была (1). 
- [x] 3. не подтянулась информация про посаду (15 рядок), документ прийому на роботу (16)
![image](https://user-images.githubusercontent.com/42540074/45148280-9b7ff100-b1cf-11e8-8403-b1f78e5274be.png)
- [x] 4. Код в ячейке 13 по умолчанию стоит 0. При переносе в Сонату выдает ошибку. Лучше, чтоб та строка была пустой и редактируемой.
- [x] 5. Дата увольнения в ячейке 11 ставит по умолчанию 0. При переносе в Сонату выдает ошибку. Лучше, чтоб та строка была пустой и редактируемой.

**Comment by Illya-Lykhachov** [comment]
"1.Отметка о том, что человек гражданин Украины по умолчанию ставит НЕТ."

Исправлено, теперь все граждане.

**Comment by Illya-Lykhachov** [comment]
"2.Код категории особы - поставило, что нет трудовой книжки (2), лучше, чтоб по умолчанию была (1)."
Если в приказе о приёме указано "Основное место работы" - код 1, в противном случае - код 2 (совместитель, трудовая книжка не у нас).

**Comment by Illya-Lykhachov** [comment]
"3. не подтянулась информация про посаду (15 рядок),"
Добавлено заполнение колонок с 12 по 15.

**Comment by Illya-Lykhachov** [comment]
"документ прийому на роботу (16)"
заполняеся

**Comment by Illya-Lykhachov** [comment]
Лёша, пункты 4 и 5 за тобой

**Comment by AlexeyTishkin** [comment]
> Лёша, пункты 4 и 5 за тобой

Сделал.

**Comment by Anestezia** [comment]
Подтверждаю. Все ок!
![image](https://user-images.githubusercontent.com/42540074/45423526-4bf06800-b69c-11e8-9181-7e8ded7f502c.png)
