### ISSUE TITLE
Новая база. Должен существовать один "Основной склад" по умолчанию.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#52]
Все равно **каждый** пользователь будет вынужден создавать хоть один склад. И подставлять его во все документы.
В справочнике "Склады" должен быть один склад и у него должна быть установлена
галочка "склад по умолчанию".

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by nik-man** [comment]
А как проверить? ))

**Comment by AlexeyTishkin** [comment]
У склада появилась опция "Основной", поставь какому-то складу и этот склад в документы будет попадать автоматом.
Создание склада - придется регистрировать нового пользователя.

**Comment by nik-man** [comment]
Галочка, если ее установить -- работает хорошо. :)
В новой учетке склад появляется, но он называется @MainWarehouse и в свойствах не стоит галочка, что он основной.

**Comment by nik-man** [comment]
Все отлично! Спасибо!
