### ISSUE TITLE
Отдельное внесение счетов затрат на ЗП

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#521]
Есть пожелание пользователей, чтоб отдельно можно было выбирать нужные счета затрат по ЗП. Например, сделать привязку к должностям и добавить в карточках возможность выбирать счет затрат самостоятельно из 4 предложенных вариантов. 91,92,93,23

**Comment by Illya-Lykhachov** [comment]
Увы, не всё та просто. Счёт затрат зависит не только от должности, но ещё и от метода начисления и периода. Например, оплата больничных не может относиться в дебет счёта затрат, а переходящие отпускные должны относиться к расходам будущих периодов. По сути, это таблица настройки.
Для простой зарплаты ФОП-ов мы специально прятали или не делали бухгалтерские тонкости, чтобы не распугать клиентов. Полноценная зарплата - это отдельная задача.

**Comment by Illya-Lykhachov** [comment]
Если придумаю как сделать это просто "снаружи", добавлю.

**Comment by shevchuk-vadim** [comment]
Не надо все усложнять. В отдельных видах начисления ты можешь по особому ставить счет дебет. Ты и сейчас не относишь больничные на 91 счет, правда? А по умолчанию его надо брать из должности. Даже если зарплата неполноценная. Иначе такая зарплата никому не нужна.

**Comment by Anestezia** [comment]
Клиенты все больше требуют такой функционал

**Comment by Illya-Lykhachov** [comment]
сделано
