### ISSUE TITLE
Нет возможности сдать Декларацию по ПДВ квартальную, полугодовую

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#522]
![image](https://user-images.githubusercontent.com/42540074/45214601-87a5bf00-b2a3-11e8-8ebb-aac55f943fbb.png)
ДПІ в Оболонському районі ГУ Міндоходів у м. Києві звертає увагу, що згідно із пунктом 202.1 статті 202 Податкового кодексу України для платників ПДВ звітним періодом є один календарний місяць, а у випадках, особливо визначених Податковим кодексом України,###  календарний квартал.

  Відповідно до пункту 49.18 статті 49 та статті 203 Податкового кодексу України податкові декларації, крім випадків, передбачених Податковим кодексом України, подаються за базовий звітний період, що дорівнює:

* календарному місяцю (у тому числі в разі сплати місячних авансових внесків) - протягом 20 календарних днів, що настають за останнім календарним днем звітного місяця;

### * календарному кварталу або календарному півріччю (у тому числі в разі сплати квартальних або піврічних авансових внесків) – протягом 40 календарних днів, що настають за останнім календарним днем звітного кварталу (півріччя).

**Comment by AlexeyTishkin** [comment]
Полугодовых нет.

**Comment by AlexeyTishkin** [comment]
Сделал.
