### ISSUE TITLE
[Авторизация] неприятный косяк при авторизации после брошенной сессии

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#525]
Ситуация:
Юзер авторизовался с установленной галкой "Оставаться в системе"
Юзер сидел, чего-то в системе делал, потом бросил и ушел по делам, браузер просто закрыл.
Юзер вернулся, запустил браузер, у него там висит закладка с Буккипером, на которой остался тогдашний текущий документ или операция.
Юзеру уже не интересна эта операция, он жмет на "Закрыть" - и у него вообще все закрывается.
Юзер пробует войти обратно через страницу авторизации - иногда еще и получает традиционный Internal Server Error при повторной авторизации.

Как бы нам при пустой истории не закрывать окно намертво, а перегонять юзера на /home ?

**Comment by alex-kukhtin** [comment]
Не выйдет, к сожалению.
Надо бы это обсудить. 
Возможно мы вообще откажемся от всплывающих окон.
Сделаем через iframe.

**Comment by alex-kukhtin** [comment]
Попробуй. Я вроде починил.
