### ISSUE TITLE
Реквизиты сторон в акте

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#527]
Просят добавить в акте реквизиты сторон
![dokument-1](https://user-images.githubusercontent.com/42540074/45476815-a47d3f00-b748-11e8-89d7-7fee2161cb7c.jpg)

**Comment by AlexeyTishkin** [comment]
Добавил.
Набор реквизитов такой как в наших документах "Счет", "Расходная накладная".

**Comment by Anestezia** [comment]
Все ок, благодарю!
