### ISSUE TITLE
Не переносится название товара для печати из счета выставленного в акт на основании

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#528]
![image](https://user-images.githubusercontent.com/42540074/45477053-4ef56200-b749-11e8-8f9d-9edc401e423f.png)
![image](https://user-images.githubusercontent.com/42540074/45477086-63395f00-b749-11e8-88f5-1a67c8759fb5.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
