### ISSUE TITLE
Табличная часть счета выставленного не соответствует табличной части акта на основании

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#529]
Клиент просит, чтоб табличная часть счета соответствовала табличной части акта, введенного на основании, даже если введена одна и та же товарная позиция несколько раз, но с разными ценами.
![image](https://user-images.githubusercontent.com/42540074/45477293-e8bd0f00-b749-11e8-8aef-89c0559c3ebb.png)
![image](https://user-images.githubusercontent.com/42540074/45477308-f96d8500-b749-11e8-9138-3e26c85680fc.png)

**Comment by AlexeyTishkin** [comment]
Это issue до Акта с наименованиями для печати ?
