### ISSUE TITLE
В счете выводится на печать Примечание

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#530]
На друк виводиться примітка (на мою думку примітка це, для користувача, а не для друку на документі. (Наприклад дати відправки, курс, кому передано документ, ....)

Возможно, стоит создать для напоминания об изменениях и вывода на печать другое поле, соответственно. А это примечание закрыть для печати
![image](https://user-images.githubusercontent.com/42540074/45477598-8ca6ba80-b74a-11e8-974d-2f7919d1b26c.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
