### ISSUE TITLE
Обсуждение!!!  Вартість з ПДВ в акті - форма для друку.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#531]
Клиент написал, что из-за такой формулировки в конце документа могут возникнуть проблемы с налоговой:  
5. Якщо фірма або ФОП без ПДВ то в акті або в рахунку не потрібно виводити
- пдв 0 
- загальна вартість з ПДВ 2200.00 з цим можуть виникнути проблеми (власний досвід).
![image](https://user-images.githubusercontent.com/42540074/45478599-02138a80-b74d-11e8-8457-34074440a6ba.png)

Может лучше сделать как в счете? 
![image](https://user-images.githubusercontent.com/42540074/45478399-86b1d900-b74c-11e8-99e8-6a8a6dcd4668.png)

**Comment by shevchuk-vadim** [comment]
Писать в акте "Загальна вартість робіт послуг без ПДВ" или "Загальна вартість робіт послуг з ПДВ" нет никакой необходимости, достаточно написать "Разом" и "Усього". И никто ни придерется.
НДС 0,00 писать можно, это говорит не о ставке НДС, а о сумме. Но еще лучше тут будет не показывать нули.

**Comment by AlexeyTishkin** [comment]
Сделал.
