### ISSUE TITLE
[Mozilla] ошибка при неразрешенных всплывающих окнах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#532]
Продолжение старой проблемы с высплывающими окнами:

При неразрешенных всплывающих окнах в Мозилле дает ошибку
![image](https://user-images.githubusercontent.com/38098758/45480077-cd093700-b750-11e8-8710-e47d5e22f2f9.png)

В Хроме просто молча не открывает окно.

**Comment by alex-kukhtin** [comment]
Не могу повторить, хоть убей

**Comment by AndriyNesterenya** [comment]
...
