### ISSUE TITLE
[Регистрация] текстовые мелочи в почтовых сообщениях при регистрации и около

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#534]
- [x] 1. При регистрации письмо с подтверждением почты имеет Subject "Підтвердження е-mail".
Стоит конкретно указать что-то типа "БукКіпер: Підтвердження е-mail"

- [x] 2.  Письмо об окончании тестового периода озаглавлено "Безкоштовний період використання сервісу БукКіпер."
Стоит уточнить в стиле "Попередження: Безкоштовний період використання сервісу БукКіпер завершується."

- [x] 3. Письма от саппорта с support@bookkeepertech.com приходят от англоязычного  имени Support Department BookKeeper
Пора переименовывать в "Департамент підтримки БукКіпер".

**Comment by DenisClone** [comment]
Второй и третий пункт - мои

**Comment by DenisClone** [comment]
2. Подправил шаблон у себя. На данный момент эти письма рассылаются вручную.
3. Имя ящика сменил, данные уже обновились.

**Comment by alex-kukhtin** [comment]
Done in 7317
