### ISSUE TITLE
Мелкий баг при регистрации после нескольких неуспешных входов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#536]
Ситуация:
Дятел после беты переходил на боевой сервис.
Аккаунт на сервисе удален, дятел об этом не знает.
Пытался пару раз войти - соответственно оба раза неуспешно.
Потом понял, что аккаунт убит - пошел регистрироваться.
Внес все данные как положено, нажал регистрацию - получил красное сообщение о слишком большом кол-ве регистраций, но письмо с подтверждением пришло как надо, после подтверждения вход без проблем.

![image](https://user-images.githubusercontent.com/38098758/45487161-35aede80-b766-11e8-9bc1-ab584b119b6b.png)

Ситуация маловероятная для живого пользователя, но сообщенние о превышении кол-ва регистраций было некорректное.

**Comment by alex-kukhtin** [comment]
Fixed in 7363.
Вроде нашел. Нужно бы проверить. Х.З как?

**Comment by AndriyNesterenya** [comment]
Вчера как раз перед публикацией 7363 на подобное наехал на Сервисе.
Понаблюдаю.
