### ISSUE TITLE
Странное поведение ОСВ по счетам в банке в иностранной валюте

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#539]
Формирую ОСВ по валютному счету через подраздел Банковские операции - и прямо со счета "Звіти" - все ок
![image](https://user-images.githubusercontent.com/38099938/45550478-9c4dfe00-b833-11e8-8b2e-57a20000ee77.png)
а когда формирую с подраздела Отчеты и выбираю ОСВ по счету в иностранной валюте - пусто
![image](https://user-images.githubusercontent.com/38099938/45550520-b7b90900-b833-11e8-86dd-1b07b2ee3487.png)

**Comment by kattrina-brekhova** [comment]
с нац. валютой таких проблем нет

**Comment by shevchuk-vadim** [comment]
Если убрать признак основного счета у счетов в национальной валюте, то проблема тоже есть.
Данные в отчете появляются только после нажатия Обнвить в браузере.
Я сделал подстановку в отчет по-умолчанию счета, который использовался последним. А когда есть счет по-умолчанию, то проблема исчезает.

**Comment by kattrina-brekhova** [comment]
работает
