### ISSUE TITLE
Платежные документы должны иметь возможность привязки к Счету-основанию.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#54]
Приходный кассовый ордер
Расходный кассовый ордер
Приход по банку
Платежное поручение

Эти документы должны иметь возможность быть привязаны к Счету-основанию.

**Comment by Illya-Lykhachov** [comment]
Технологически связь устанавливается сверху-вниз, из счёта создаётся оплата. Делается это пока только для удобства создания документов оплаты.
В установке связи снизу-вверх не вижу смысла. Документ оплату **уже** создан, а сама связь нигде не используется.

**Comment by nik-man** [comment]
Обычно связи используются, чтобы отслеживать, какие счета/отгрузки и насколько закрыты оплатами. Также могут использоваться для отслеживания первого-второго события.

**Comment by Illya-Lykhachov** [comment]
Это "обычно". Ещё связи нужны в полноценном налоговом учёте для отслеживания первых событий. Но СЕЙЧАС мы их не используем НИКАК. Добавлять ненужный СЕЙЧАС функционал на данном этапе нецелесообразно.

**Comment by nik-man** [comment]
И то верно. Всему свое время.

**Comment by nik-man** [comment]
![2018-07-09](https://user-images.githubusercontent.com/35918141/42450005-7088357e-838b-11e8-9e25-f745560f4f24.png)

**Comment by Illya-Lykhachov** [comment]
пришло время

**Comment by AlexeyTishkin** [comment]
Насколько я понимаю, этот функционал надо делать в платежных документах, не в счете.

**Comment by Illya-Lykhachov** [comment]
Ну да. Операции оплаты (банк и касса) нужно связывать с операцией счёта-основания

**Comment by AlexeyTishkin** [comment]
Я именно с точки зрения assigned уточнял...

**Comment by Anestezia** [comment]
Сделать в платежке подбор счетов с возможностью прикрепить несколько счетов к одной платежке, типа такого:
![image](https://user-images.githubusercontent.com/42540074/50226135-1221b280-03ab-11e9-858e-7c249909c8a5.png)

**Comment by Illya-Lykhachov** [comment]
Остались кассовые ордера

**Comment by htrofymova** [comment]
готово
