### ISSUE TITLE
Звіт Д4 - рядок Середньооблікова кількість працівників: при расчете - учитывает рожениц

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#540]
![image](https://user-images.githubusercontent.com/38099938/45636973-fbb94180-bab1-11e8-9918-d5b081fd9658.png)

![image](https://user-images.githubusercontent.com/38099938/45637011-0ffd3e80-bab2-11e8-9231-09a6a3ae44ce.png)

![image](https://user-images.githubusercontent.com/38099938/45637036-20adb480-bab2-11e8-8ebd-26f25694e69d.png)

при этом согласно Инструкции: 
При  обчисленні  середньооблікової  кількості  штатних 
працівників   облікового   складу   враховуються   всі   категорії 
працівників облікового складу,  зазначені у пунктах 2.4,  2.5 цієї 
Інструкції,  крім  працівників,  які  перебувають  у  відпустках у 
зв'язку з вагітністю та пологами або для  догляду  за  дитиною  до 
досягнення  нею  віку

**Comment by kattrina-brekhova** [comment]
ага, нашла в чем дело - этот сотрудник совместитель

**Comment by kattrina-brekhova** [comment]
получается, что в Д4 тоже не нужно указывать рожениц. а значит в штатную численность работников указываем 4, но в среднеучетную - 2 (1 - совместитель не указывается)
![image](https://user-images.githubusercontent.com/38099938/45638250-530ce100-bab5-11e8-9577-4ec982fcae52.png)

**Comment by shevchuk-vadim** [comment]
В этом отчете "Штатна чисельність працівників" - это количество штатных единиц по штатному расписанию, а не количесвто принятых работников.

**Comment by kattrina-brekhova** [comment]
штатна чисельність - это : и совместилети, и роженицы....

исходя из логики инструкции, в  Д4, в рядок 15 мы должны показать "2". потому что 1 работник - рожает, и еще 1 - совместитель?

3.2.2. При  обчисленні  середньооблікової  кількості  штатних 
працівників   облікового   складу   враховуються   всі   категорії 
працівників облікового складу,  зазначені у пунктах 2.4,  2.5 цієї 
Інструкції,  крім  працівників,  які  перебувають  у  відпустках у 
зв'язку з вагітністю та пологами або для  догляду  за  дитиною  до 
досягнення  нею  віку, 

2.6. Не   включаються   до   облікової   кількості    штатних 
працівників такі категорії:
     2.6.1 прийняті на роботу за сумісництвом з інших підприємств.

**Comment by Illya-Lykhachov** [comment]
Это не баг, это фича. У нас пока нет отпуска в связи с беременностью и родами и по уходу за детьми до 3-х и 6-ти лет. Поэтому вопрос не в отчёте, а в "глубине проработки задачи".

**Comment by Illya-Lykhachov** [comment]
Придётся делать ещё и приказ на бесплатный отпуск по уходу за детьми

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/47634514-728a3580-db5a-11e8-9ce9-f30b72cfe0c1.png)

больничный в связи с беременностью и родами есть - он проводится больничным листом (в инструкции этот больничный называют отпуском). в сервисе нету только по уходу за детьми

**Comment by Illya-Lykhachov** [comment]
Больничный для беременности и родов есть, но на этом женщины не останавливаются.

**Comment by Illya-Lykhachov** [comment]
Добавлен бесплатный отпуск.
