### ISSUE TITLE
[Регистрация] Лишнее сообщение при регистрации

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#542]
При регистрации на Деве свежеудаленного юзера - лишнее сообщение 
![image](https://user-images.githubusercontent.com/38098758/45736679-56f34d00-bbf4-11e8-870d-5bffd4142092.png)

Лишних попыток регистрации не было.
Поработали под старой регистрацией, убили юзера, регистрились по новой.
Собственно процедура прошла штатно.

**Comment by alex-kukhtin** [comment]
Нужно бы проверить.
Должно было починиться начиная с 7380.

**Comment by AndriyNesterenya** [comment]
На слово верю, но пока не закрываю - на Деве удалялка дятлов поломалась, погоняю с пристрастием как только починится.

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/49856342-394f1180-fdf8-11e8-8867-621a973346d8.png)

Обычная дятлорегистрация.
Письмо приходит как обычно.
Сообщение о множественных попытках присутствует.

**Comment by AndriyNesterenya** [comment]
Продолжаю набирать статистику.
Сегодня снова поймал это же сообщение на Бете при нормальной регистрайии.

Последовательность действий :
Утром регался на Деве
Удаляю дятла с Беты
Иду регистрироваться сам.
В процессе пишу телефон, занятый другой учетной записью - получаю ошибку
Меняю телефон
Регистрируюсь
