### ISSUE TITLE
В налоговой накладной не выводится название получателя, если не заполнено полное название.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#545]
В случае, если у контрагента не заполнено полное название, в налоговую накладную не подтягивается получатель
![image](https://user-images.githubusercontent.com/38098758/45752596-aea6ae00-bc1e-11e8-96fb-55303c46d956.png)

Вариант - требовать обязательного заполнения полного названия при создании контрагента (не очень хорошо, когда контрагент создается на лету).
Вариант - если нечего выводить - подсвечивать поле красным и требовать заполнить полное название в свойствах контрагента (предполагаю, непросто реализуется).
Вариант - при отсутствии полного выводить туда краткое название.

**Comment by AlexeyTishkin** [comment]
Теперь если не указано полное, то отображается обычное.
