### ISSUE TITLE
Платежи из счета. Примечание.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#546]
Думаю, будет удобно при создании платежа из счета сразу добавлять в назначение платежа строку вида:
"... згідно рахунку № 123 від 2018.09.20. Без ПДВ."

И в платежку и в кассовый ордер тоже можно, наверное.

**Comment by AlexeyTishkin** [comment]
А если НДС есть ? Какая формулировка ?

**Comment by mik-man** [comment]
Если есть НДС:
"... В т.ч. ПДВ 166 грн. 67 коп."

**Comment by AlexeyTishkin** [comment]
Сделал.
