### ISSUE TITLE
Виставлення рахунку - не подтягивается цена

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#547]
Не подтягивается цена вообще никакая, ни основная, ни при выборе разных видов цены и прайса.
![image](https://user-images.githubusercontent.com/42540074/45824732-5bedf480-bcf9-11e8-9752-e383031dc9e7.png)

**Comment by AlexeyTishkin** [comment]
Подробней. Создал счет. Выбрал объект. Цена загрузилась.

**Comment by Anestezia** [comment]
не, все. ложная тревога. Там свои нюансы. Видимо другие так же тестили и не разобрались сразу.
