### ISSUE TITLE
В Акте услуг, созданном из счета выставленного сбивается цена

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#548]
Если из выставленного счета именно по услуге сформировать АКТ (реализация услуг), то при изменении даты сразу сбивается цена, и, как следствие, сумма документа. Если формировать по товару, то такого эффекта нет.
![image](https://user-images.githubusercontent.com/42540074/45866121-6b684e80-bd88-11e8-93c8-ea2225f60e9f.png)

**Comment by AlexeyTishkin** [comment]
Цена в прайс-листе есть на эту дату ?

**Comment by Anestezia** [comment]
да, в этом причина.
