### ISSUE TITLE
В проведенных печатных документах изменяются данные при изменениях свойств Моей фирмы

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#549]
Грандиозный идеологический косяк:

При изменении (например) основного расчетного счета в свойствах Своей фирмы изменяется расчетный счет во всех документах, в т.ч. старых проведенных.
Распечатать копию старого документа в первозданном виде при этом становится невозможно (разве что вручную данные в исходный вид привести).

По всей видимости, та же ситуация со всеми данными, хранящимися вне документа.

Выход - хранить данные прямо в документах.

**Comment by alex-kukhtin** [comment]
Это очень плохой подход. И приведет к огормному росту базы и попыткам согласовать все со всем.
Знаем, плавали.

**Comment by alex-kukhtin** [comment]
В действительности, в жизни ты с этим не столкнешься.
Ты ведь поменял свойства существующего расчетного счета. А в реальности будешь создавать новый.

**Comment by alex-kukhtin** [comment]
Закрывай этот issue нафиг.

**Comment by AndriyNesterenya** [comment]
Я честно пытался, но не смог :)
Простите, будущие юзеры.
