### ISSUE TITLE
измените название операции Наказ про приймання на роботу

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#551]
в списке операций слева -неверно. в документе правильно
![image](https://user-images.githubusercontent.com/38099938/45929867-48909280-bf60-11e8-8b34-9b46c8911263.png)

**Comment by Illya-Lykhachov** [comment]
У всех операций сервиса (не только персонал) есть два названия: полное и короткое. В списке документов и в открытом документе отображается полное, в меню новых документов - короткое. Так сделано специально, чтобы меню было быстрочитаемым. Если я правильно понял, то не устраивает именно короткое название. Какое будет лучше?

**Comment by kattrina-brekhova** [comment]
да, наказ про "приймання" на роботу не используется, коректное название наказ про прийняття на роботу

**Comment by Illya-Lykhachov** [comment]
исправил
