### ISSUE TITLE
Новый хост для фиксации регистраций в сервисе привлеченных нашими сотрудниками

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#553]
По результатам встречи с Путятиным (21.09) предлагается добавить еще один хост, для фиксации клиентов привлеченных нашими сотрудниками. Назвать его - office.bookkeep......

Содержание тега заголовка страницы должно быть сформировано по аналогии с хостом sonata, чтобы страница не появлялась в выдаче поисковых систем.

**Comment by MaksymTikhomirov** [comment]
Я бы рекомендовал не office, а шото типа sales.book.......

**Comment by DenisClone** [comment]
1. Настройки ДНС для хоста создал.
2. Код для счетчика Гугл необходимо вставить в тег <HEAD>, на каждой странице:


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122489769-5"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-122489769-5');
</script>

**Comment by DenisClone** [comment]
> Я бы рекомендовал не office, а шото типа sales.book.......

Поменял на sales.book......
Код счетчика указанный выше - актуален.

**Comment by MaksymTikhomirov** [comment]
Окк

> > Я бы рекомендовал не office, а шото типа sales.book.......
> 
> Поменял на sales.book......
> Код счетчика указанный выше - актуален.

ОК

**Comment by DenisClone** [comment]
Коды счетчиков добавил. 
Поддомен исключен из индексации поисковиками.
