### ISSUE TITLE
Накладная. Запретить отмену проведения при наличии более поздних.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#554]
Пользователь может зайти в любую накладную и отменить проведение.
И попадает в ловушку.
Снова провести он не может, потому что существуют накладные с этим товаром более поздней даты.
Теперь он вынужден будет отменять проведение всех поздних накладных, которых может оказаться очень много.

Наверное, нужно запрещать отменять проведение при наличии таких накладных.
И выводить соответствущее сообщение типа:
"Для отмены проведения данного документа требуется отменить документы более поздней даты."

**Comment by AlexeyTishkin** [comment]
Сделал.
