### ISSUE TITLE
Вид цены "Основная"

### ISSUE THREAD

**Issue by Illya-Lykhachov** [a2develop/bugTracker#556]
Нужно дать возможность пользователям переименовать вид цены "Основная". Изменить признак "Основная" можно, а название нет. Это название никого не устроит. Не стоит делать этот вид системным.

**Comment by AlexeyTishkin** [comment]
> Не стоит делать этот вид системным.

В таком случае для нового тенанта не дожно быть созданного прайс-листа и вида цены ?

**Comment by Illya-Lykhachov** [comment]
Для нового тенанта, в качестве образца, нужно создавать один прайс-лист и один вид цены. Оба основные. Оба не системные. Названия: "Отпускные цены" и "Розничная".

**Comment by AlexeyTishkin** [comment]
Сделал для нового тенанта.
