### ISSUE TITLE
Декларация НДС, нулевой РК - нет возможности убрать ее вообще

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#557]
В декларации НДС при отсутствии корректировки НДС нет возможности снять галочку и соответственно открепить от пакета Д 1. Ведь он в такой ситуации не подается. А провести декларацию не проводя нулевой Д1 не получается вообще.

**Comment by AlexeyTishkin** [comment]
Не подается совсем ? Даже пустой ?

**Comment by Anestezia** [comment]
Пустой подаваться не должен, нужно снять галочку о додатке 1 и открепить из пакета, чтоб можно было провести декларацию только с Д5.

**Comment by AlexeyTishkin** [comment]
Тогда нужно иметь возможность удаления дочернего отчета.

**Comment by AlexeyTishkin** [comment]
Сделал возможность удаления/повторного создания.
