### ISSUE TITLE
[отчетность ФОП] - некорректная работа с датами при начислении

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#558]
Из обращения живого юзера:
_Добрий день 
Коли тестував і пробував зробити звіт (по єдиному податку ФОП), то потрібно зробити нарахування податків. Я стикнувся з тим що потрібно зробити нарахування за 1 квартал. А якщо у мене фірма була створена в 2 кварталі, як тоді бути._

Суть проблемы :
Если ФОП начал работать не с начала года, при формировании текущих отчетов у него все равно требуют сформировать отчет за 1 квартал и прочие ранние периоды.

По этому поводу думаю следующее:
1. Можем добавить дату регистрации ФОП в свойства Моей фирмы и учитывать ее при формировании отчетности, подставляя нулевые значения в соотв. цифры периодов до начала работы.
2. Подумать о ситуации, когда юзер переходит к нам из другой программы, где уже сданы более ранние отчеты, и ему лень вводить все данные предыдущик кварталов, и может быть достаточно где-то ввести оборот/сумму ранее уплаченных налогов.
3. Стоит подумать с т.з. теории, о ситуации, когда человек сначала зарегистрировался ФОПом, а потом через какое-то время написал заяву о переходе на упрощенную систему. (почти невероятно, но возможно)

**Comment by AlexeyTishkin** [comment]
> у него все равно требуют

Требования нет.

**Comment by AndriyNesterenya** [comment]
А он считает, что есть.
В смысле там окошко, предлагающее заполнить отчет за 1 квартал, и не предлагающее альтернатив.

**Comment by AlexeyTishkin** [comment]
> В смысле там окошко, предлагающее заполнить отчет за 1 квартал, и не предлагающее альтернатив.

![image](https://user-images.githubusercontent.com/35917940/46344755-f7ad2800-c64a-11e8-8e5d-1b80a3240d1d.png)

Разве есть требование и нет альтернатив ?

**Comment by AndriyNesterenya** [comment]
Юзер считает, что нет.
Он не понимает, нахрена ему насчитывать предыдущий квартал, когда он еще зарегистрирован не был.
И не понимает, что будет, если отказаться.

Если я правильно понимаю, при отказе наша система пробегается по всем предыдущим периодам, и если везде отказ - считает текущий с нулевыми значениями предыдущих?

Хоть текстом явно приписать "Натисніть "Скасувати", якщо в Х кв. діяльність не велася" или что-то в этом духе.
Потому как пипл не догоняет и дергается.

**Comment by AlexeyTishkin** [comment]
> Если я правильно понимаю, при отказе наша система пробегается по всем предыдущим периодам, и если везде отказ - считает текущий с нулевыми значениями предыдущих?

Нет. Декларация строится нарастающим итогом, т.е. Декларация за третий квартал, это, на самом деле, не за третий квартал, а с начала года, включая третий.
Сообщение - это предупреждение о том, что в периоде заполнения (с начала года) не хватает данных. Это просто напоминалка.

**Comment by Anestezia** [comment]
Текст мягче в напоминалке
1. Согласна, но, наверное (Sorry! but it's gemorroable)
2. Согласна полностью. Надо такое предусмотреть.
3. Типа сначала зарегился фопом, но на общем основании, а потом перевелся на единый? Кстати, чаще бывает наоборот, взяли да перевели с единого на общую систему, мало ли из-за чего. Это бы тоже предусмотреть, резкая смена системы налогообложения.

**Comment by AndriyNesterenya** [comment]
Про нарастающий итог - понятно.
Задача не напугать юзера, дать ему понять, что раз он деятельности в 1-2 кварталах не вел - то можно просто отменить напоминалку.
А была бы дата регистрации - можно было бы и не показывать ему этих предупреждений, т.к. данных нет потому, что их там и не должно быть.

Но с датой, думаю, геморрой....
Проще чёто дописать, чтобы юзера отменять не боялись.

**Comment by Anestezia** [comment]
А если просто кнопки в этом конкретном диалоге переименовать? 
Нарахувати зараз?
ТАК     НІ
Так будет более понятна сама возможность дальнейшей работы

**Comment by shevchuk-vadim** [comment]
Согласен с Настей. Пользователя ввела в ступор кнопка "Скасувати".

**Comment by AndriyNesterenya** [comment]
Ничего не имею против. 
Если обозвать кнопку попонятнее + приписать комментарий в стиле "не работал - на заполняй" проблемы не будет.

**Comment by Illya-Lykhachov** [comment]
Нужно просто предупредить пользователя о неполных данных в отчёте, и  пусть решает сам что ему с этим делать. Сообщение типа: "В системе нет данных за предыдущие кварталы, поэтому отчёт может быть неполным. Продолжить заполнение? (Да, нет)".
Не нужно предлагать сделать ещё что-то вне отчёта (рассчитать налоги, ввести данные и т.п.)

**Comment by AndriyNesterenya** [comment]
До сих пор ничего не изменилось (или изменилось, и затёрлось).
Если юзер зарегистрировался (к примеру) в 3 квартале, и у него в первых двух кварталах деятельности вообще не было, ему все равно настойчиво предлагают начислить налоги в 1 и 2 квартале.
Вопрос поставлен так, что у юзера не возникает мысли, что за 1-2 квартал он может что-то не начислять.
Даже если налоги начислены с нулями - сам отчет не заполняется, по новой просят начислить.

**Comment by AlexeyTishkin** [comment]
Так не решили ничего. Илья написал, что "Не нужно предлагать сделать ещё что-то вне отчёта (рассчитать налоги, ввести данные и т.п.)".
На чем останавливаемся ?

**Comment by Illya-Lykhachov** [comment]
Нужно при заполнение отчёта выполнить 2 процедуры:

- проверка возможности правильного заполнения программой (полноты данных);
- заполнение по тем данным, которые есть в базе.

Если на первом шаге есть сомнения в правильном заполнении, нужно показать предупреждение с описанием проблем и дать возможность пользователю самостоятельно сделать выбор: продолжить или отказаться.
Не нужно здесь же предлагать пользователю что-то сделать (пусть сам решает как исправлять проблему, нужно ли её исправлять и есть ли проблема вообще).
Не нужно принимать решение за пользователя, наше дело **только** предупредить.

**Comment by AlexeyTishkin** [comment]
> Если на первом шаге есть сомнения в правильном заполнении, нужно показать предупреждение с описанием проблем 

Какой критерий ? Нет данных, потому, что их и не должно быть ? Или ошибка ?

**Comment by AndriyNesterenya** [comment]
Вот вопрос поддержу.
Нет данных, потому что ФОП не был зарегистрирован?
Или просто бездельничал 3 месяца?

**Comment by Illya-Lykhachov** [comment]
Нам не нужно знать **почему** нет данных. Мы не решаем ошибка это или нет.
Написать: "Нет данных за ... период. Продолжить или отменить?" И пусть сам решает что делать дальше. Если и не должно быть - нажмёт продолжить, а если забыл рассчитать - рассчитает и заполнит снова. Если же заполнит и получит некорректный отчёт - сам виноват, мы предупредили.

**Comment by AlexeyTishkin** [comment]
Будет предупреждение о том, что нет начислений налога за определенные кварталы, без предложения его начислить. Утверждаем такой вариант ?

**Comment by AndriyNesterenya** [comment]
Думаю, да

**Comment by AlexeyTishkin** [comment]
Ок. Тогда к следующему релизу.

**Comment by AndriyNesterenya** [comment]
Лишь бы не было ситуации, что после отказа от начислений по таким-то кварталам по новой не начинало появляться требование доначислить :)

**Comment by AlexeyTishkin** [comment]
Так требования не будет. В момент заполнения (каждого) будет сообщение "Не начислен налог в 1, 2 кварталах. Продолжить ?"

**Comment by AndriyNesterenya** [comment]
Годится

**Comment by AlexeyTishkin** [comment]
Сделал.
