### ISSUE TITLE
На странице входа сделать пожирнее и понятнее кнопку перехода к регистрации для первого входа

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#559]
Клиенты не понимают, слишком мелко написано и не понятно, что это именно ссылка для входа на регистрацию

**Comment by Anestezia** [comment]
Будем что-то с этим делать?

**Comment by alex-kukhtin** [comment]
Закрывайте нафиг.
Если все еще вопрос остался, пишите новый issue и назначайте его на дизайнера.
