### ISSUE TITLE
Нужна операция отображение монетарной курсовой разницы, например при возврате предоплаты от поставщика-нерезидента

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#562]
Ситуация: поставщик-нерезидент возвращает нам предоплату
проводки: 
предоплата: Д632 - К312 - 100$ = 2500 грн
возврат денег: Д312 - К632 - 100$ = 2800 (курс прменялся)

нужна закрыть 632:
Д632 - К714 - 300 грн

+ и отрицательная курсовая разница

**Comment by kattrina-brekhova** [comment]
вообще нужна операция для отражения монетарной курсовой разницы. как сегодня показал пример, бух справка не дает возможности закрыть хвост по курсовой разнице, если курс валют по датам операций отличается

**Comment by kattrina-brekhova** [comment]
в принципе курсовую разницу можно было бы начислить и бухгалтерской справкой. но почему-то не отражаются в отчетах нужные суммы и проводки
например
делаю проводку Д362 -К714
в новом интерейсе ручной проводкой вообще кнопка "провести" не активная - ишью в "васт ишью" писала
в старом интерфейсе проводит
![image](https://user-images.githubusercontent.com/38099938/59770320-8385e380-92b0-11e9-8103-69ae5c4c4a49.png)
но эти проводки не попадают в отчеты и в проводки по контрагенту. например наш контрагент не попал сюда
![image](https://user-images.githubusercontent.com/38099938/59770392-a1ebdf00-92b0-11e9-8e74-a7a8970eea81.png)
в отчете реестр документов есть
![image](https://user-images.githubusercontent.com/38099938/59770472-c5af2500-92b0-11e9-9992-e43d7f8a339c.png)

но в разрезе контрагента и увеличения Д362 сумма не отражается

**Comment by htrofymova** [comment]
Наверно, нужно сделать соответствующую валютную операцию к документу Бухгалтерська довідка (НЕ Бухгалтерсьвка довідка (вручну)). Тем более, что уже есть две операции по курсовым разницам при покупке-продаже валюты.
В отчет не попадают именно потому, что в операциях нет валюты. 
Сделаю.

**Comment by htrofymova** [comment]
готово. 
Сделала две операции: доход и расход отдельно.
Бывают еще неоперационные курсовые разницы, а также предприятие может вступать в иновалютные отношения со своими собственниками, но то таке, изыски уже.
