### ISSUE TITLE
[Улучшайзинг]Подтягивать банк по МФО при создании контрагента.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#563]
В мастере создания нового контрагента импорт банка работает только из списка названий.
Просится автоматическое подтягивание банка при вводе МФО в поле.
![image](https://user-images.githubusercontent.com/38098758/46411310-22b77a80-c724-11e8-84b6-d9792435622b.png)
Или вызов процедуры импорта вместо пустого окна создания банка.

**Comment by shevchuk-vadim** [comment]
При нажатии на "+" и открытии мастера создания банка туда подгружаются данные из каталога банков, если найден банк по введенному МФО.

**Comment by AndriyNesterenya** [comment]
Победили, ура
