### ISSUE TITLE
В ПН от ФОПа подтягивается в поле подписи само слово ФОП.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#564]
![image](https://user-images.githubusercontent.com/42540074/46598332-6d524180-caec-11e8-9e94-24759578530b.png)
Это если в карточке фирмы ФОП  не установлено право подписи Головний бухгалтер. 
2. Предлагается сделать в самой ПН это поле редактируемым, а также поле ИНН рядом. 
Сейчас если у меня была создана ПН и право подписи Главный бухгалтер было дано другому человеку, потом я решила изменить подписанта ПН, сняла проведение ПН, передала право подписи другому человеку либо не установила вообще никому, то накладную остается только удалить, так как эти изменения не отображаются в созданной заранее, но не проведенной накладной и вручную это не поменяешь.

**Comment by AlexeyTishkin** [comment]
П.1 сделал.

**Comment by AlexeyTishkin** [comment]
По поводу п. 2. У нас в других документах (в частности в кассовых ордерах) такой же механизм (на создании взяли текущее ответственное лицо, сохранили в документе, ручного редактирования нет). Должно быть единообразие. Если такой механизм действительно нужен - нужно выносить на обсуждение и делать везде одинаково.

**Comment by AlexeyTishkin** [comment]
Кстати, лицо перезаполняется при смене даты документа.
