### ISSUE TITLE
Виставлення рахунку, в ПДФ не влазить адреса, написана на 2 або 3 строки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#566]
![image](https://user-images.githubusercontent.com/42540074/46665929-ef666700-cbcd-11e8-900b-27de04c2e580.png)

Якщо у Властивостях моєї фірми на вкладці Контакти написати адресу у дві або у три строки, тобто, якщо в когось адреса дуже велика, то маємо такий глюк при зберіганні в форматі ПДФ.

**Comment by AlexeyTishkin** [comment]
Напиши в комментариях текст, чтобы было на чем проверить.

**Comment by Anestezia** [comment]
Там либо идет длинный текст, либо, если кто-то переносит абзац ниже на вторую и третью строку. при просмотре печатной версии их видно, а при сохранении в ПДФ - строки комкаются.
![image](https://user-images.githubusercontent.com/42540074/46726165-7545e900-cc86-11e8-8885-750a341f200e.png)
Вот все, что влазит так.
А вот то, что остается в ПДФ
![image](https://user-images.githubusercontent.com/42540074/46726231-9dcde300-cc86-11e8-87a4-4453e023f46d.png)
текст:
01001, м. Київ, вул. Паркова дорога, 2ттттППППППППППППППППППППППППППППППППТТТТТТТТТТТТТТТТТТТТТТТТВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВВАААААААААААААААААААААААААААААААААААААААААААЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫПППППППППППППППППППППЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕ

**Comment by AlexeyTishkin** [comment]
Исправил.
