### ISSUE TITLE
Звіт з ЄСВ 5 табл. коли не подається, повинна відкріплюватись (видалятись) з пакета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#567]
По аналогії з декларацією з ПДВ, потрібно зробити можливість видалення з пакету звітів той, що іноді не подається (наприклад, табл. 5), та щоб прибрати з головного звіту позначку про подання у пакеті дод.5.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by Anestezia** [comment]
Есть!
