### ISSUE TITLE
Свойства физлица. Дата народження і стать. Добавить объяснение, что они из ИНН.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#569]
Пользователи не понимают, почему они не могут редактировать дату рождения и пол.
Думаю, можно добавить небольшое обьяснение типа:
"Дата народження і стать автоматично обчислюються з ІПН"

![2018-10-10](https://user-images.githubusercontent.com/35918141/46725631-40856200-cc85-11e8-9ac2-1632b226495a.png)

**Comment by alex-kukhtin** [comment]
А я бы разрешил их редактировать. В ИНН ошбики бывают.

**Comment by alex-kukhtin** [comment]
Хотя объяснение не помешает.

**Comment by Illya-Lykhachov** [comment]
Вместо сообщения почему мы не даём изменять дату рождения и пол, сделал их редактируемыми. Добавил проверку их соответствия ИНН.
