### ISSUE TITLE
В счете выставленном выводить на печать ячейку "Договор"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#570]
Клиенты просят выводить на печать.
- Добрий день, є ще питання. В рахунку для покупця моживо вивести на друк графу "Договір"? Підстава поставки продукції . З одним покупцем може бути декілька договорів. Інформацію про договір ми вводимо в рахунок.
![file_2](https://user-images.githubusercontent.com/42540074/46726721-9b1fbd80-cc87-11e8-9b26-e101fec01394.jpg)

**Comment by AlexeyTishkin** [comment]
Сделал.
