### ISSUE TITLE
Запретить некоторым пользователям менять пароль.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#573]
А то поменяли уже в демо-базе. :)

**Comment by alex-kukhtin** [comment]
Done in 7317

**Comment by mik-man** [comment]
Изменение пароля запрещено, хорошо. Но при чем здесь ошибка? Пользователь будет думать, что ошибка в системе и звонить с вопросами.

![2018-10-13](https://user-images.githubusercontent.com/35918141/46904209-4e3b2180-cee9-11e8-8237-ce955cc255ff.png)

Наоборот надо дать понять пользователю, что ситуация штатная, и дать какое-то краткое объяснение. Например: "Зміна пароля заборонена для цього облікового запису. Цей обликовий запис має бути загальнодоступним."
![2018-10-13](https://user-images.githubusercontent.com/35918141/46904213-572bf300-cee9-11e8-9e92-c27450b8b72c.png)

А коли з'явиться управління правами користувачів, будем писати: "Зміна пароля заборонена для цього облікового запису. Якщо вам потрібно змінити пароль, зверніться до адміністратора вашої бази даних."
