### ISSUE TITLE
[Печать] В Расходной накладной левая граница таблицы печатается криво

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#574]
Мелкий косяк на печати

В расходной накладной печать левая граница на экране выглядит ОК
![image](https://user-images.githubusercontent.com/38098758/46853692-82d6ac80-ce07-11e8-901b-2a50dc3b5434.png)
а при выводе на печать в предпросмотре и на бумаге- левая граница тонкая
![image](https://user-images.githubusercontent.com/38098758/46853857-fed0f480-ce07-11e8-9d8d-29d2b57a8f21.png)

**Comment by AlexeyTishkin** [comment]
Какой-то глюк стимулсофта с рендерингом. Сейчас на экране выглядит толще, на просмотре - как остальные. Попробуй.

**Comment by AndriyNesterenya** [comment]
ОК
