### ISSUE TITLE
Кассовые ордера, ошибка в подстановке права подписи кассира

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#575]
Если кассир не принят на работу, и право подписи кассира назначено главному бухгалтеру, то в документах все равно подставляет в поле кассир - фамилию  директора.
![image](https://user-images.githubusercontent.com/42540074/46856943-6c811e80-ce10-11e8-9d96-2b795fda75c4.png)
![image](https://user-images.githubusercontent.com/42540074/46856961-773bb380-ce10-11e8-8a13-331a553faa5a.png)

**Comment by htrofymova** [comment]
Готово
