### ISSUE TITLE
Нарахування авансу - Документ Платіжна відомість. Кнопка "Заповнити" обнуляє таблицю.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#576]
Доводиться  натиснути кнопку Оновити, щоб відновити дані по виданим сумам.

П.С. - У документі Платіжна відомість, створена на базі Розрахункової відомості напряму формуються невірні суми. Щоб сформувати вірні суми - з урахуванням раніше виданого авансу, потрібно-таки натиснути кнопку Заповнити. Це неочевидно для користувача (буде вносити вручну). Потрібна або однакова поведінка обох документів, або підказка.

**Comment by Illya-Lykhachov** [comment]
При выплате аванса заполнять документ не нужно, он заполняется при создании. Чтобы ошибочно не нажимали на заполнить, кнопку заблокировал, если выплачивается аванс.

**Comment by Anestezia** [comment]
Ок. Кнопка заблокирована.
