### ISSUE TITLE
Персонал-Співробітники-Вкладка Документи - Не всі документи по особі відображаються.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#577]
Думаю, це пов'язано з великою кількістю створених з участю особи документів. В кого мало операцій - відображаються всі, в кого багато - немає початкових операцій. Створюється лише одна сторінка з переліком документів.
![image](https://user-images.githubusercontent.com/42540074/46858656-6c831d80-ce14-11e8-9999-f531dae51083.png)

**Comment by Illya-Lykhachov** [comment]
Исправлено

**Comment by Anestezia** [comment]
В сервисе вроде исправлено. Странно, что на Деве - нет.

**Comment by Illya-Lykhachov** [comment]
Странно. Накатил исправленный скрипт на базу ещё раз, проверил - работает

**Comment by Anestezia** [comment]
теперь все есть
