### ISSUE TITLE
Розрахункова відомість - невірний розрахунок робочих днів при відпустці.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#578]
Наприклад, серпень 2018 р. В людини відпустка з 02.08 по 15.08. = 14 к.д. Всього робочих днів у серпні = 22 дні. Фактично людина працювала 1.08, та 16, 17,20,21,22,23,27,28,29,30,31.08   т.е. 12 днів. Програма розраховує за принципом 22 робочих дні мінус 14 днів відпустки = 8 "робочих", а повинно бути 12.
![image](https://user-images.githubusercontent.com/42540074/46859076-70fc0600-ce15-11e8-8bce-10bba3aef722.png)

**Comment by Illya-Lykhachov** [comment]
Это одна проблема с [https://github.com/a2develop/bugTracker/issues/579](url)
