### ISSUE TITLE
Розрахунок зп. Нет привязки к дате приема на работу при расчете рабочих дней.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#579]
Человек принят с 20.08.18. С 23.08 по 29.08 на больничном. Фактически отработал дней 5. Программа считает по принципу 22 рабочих дня в августе минус 7 больничных = 15 "рабочих". 
![image](https://user-images.githubusercontent.com/42540074/46859402-54ac9900-ce16-11e8-97f9-798a79d60d2f.png)
А в таблице 6 Додатка 4 ЕСВ считает количество к.д. у трудових відносинах правильно, с привязкой к дате приема сотрудника.

**Comment by Illya-Lykhachov** [comment]
"принят с 20.08.18. С 23.08 по 29.08 на больничном. Фактически отработал дней 5". Как определить **рабочие** дни, если не смотреть в календарь? Иными словами - задача: принят 20-го, на больничном с 23 по 29 в текущем месяце 31 день, сколько дней работал?

PS. С определением **календарных** дней вопросов нет.

**Comment by Anestezia** [comment]
Видимо, только через привязку к календарю.
