### ISSUE TITLE
В таблице Зарплатных документов смещается дата документа на 1 день назад. 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#580]
Насчитываю зп 30.09., провожу, внутри документа "Розрахункова відомість" и "Відомість на виплату готівки" стоит дата 30.09., а в списке документов отображаются 29.09.18.
![image](https://user-images.githubusercontent.com/42540074/46860353-ef0ddc00-ce18-11e8-9352-ce43c531ff60.png)
См. Первый и выделенный документы.

**Comment by Illya-Lykhachov** [comment]
Проблема была в платформе. Исправлено.
Для исправления достаточно "передёрнуть" дату документа.
