### ISSUE TITLE
Справочник "Банки" - некорректно подтягивает номер телефона.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#581]
![image](https://user-images.githubusercontent.com/42540074/46867133-a06a3d00-ce2c-11e8-97ee-ea47bd62481c.png)
![image](https://user-images.githubusercontent.com/42540074/46867167-b7a92a80-ce2c-11e8-90c0-d9cecb0bd0a7.png)

**Comment by AlexeyTishkin** [comment]
Справочник банков взят с официального сайта НБУ. В справочнике - бардак с телефонами. Либо так, либо телефоны вообще не импортировать.

**Comment by mik-man** [comment]
Вообще, справочник банков до двух сотен. И его часто обновлять/перезаписывать не надо. Может быть имеет смысл один раз сесть мне или Насте, просмотреть весь справочник и подправить номера телефонов? По крайней мере мере вот такие откровенно кривенькие.

**Comment by AlexeyTishkin** [comment]
Подправить вручную можно. Но мы тогда теряем возможность полного обновления перечня с сайта НБУ. Новые банки придется добавлять вручную.

**Comment by mik-man** [comment]
А что, нельзя подтягивать все, кроме телефона? Все равно в НБУ с номерами телефонов бардак. Всякий хлам там более, чем в 50%

**Comment by AlexeyTishkin** [comment]
Подтягивать можно без номеров. Но где ты собираешься менять номера ? Непосредственно в таблице ?

**Comment by mik-man** [comment]
Да прям тут могу: https://github.com/a2develop/app/blob/develop/apps/main/catalog_full.sql
:)

**Comment by AlexeyTishkin** [comment]
Вот здесь как раз не надо :) этот файл каждый раз заново генерим

**Comment by AlexeyTishkin** [comment]
Можно было бы здесь https://github.com/a2develop/app/blob/develop/apps/main/catalog/bank/catalog.sql

Но тогда будет, то о чем говорил выше, т.е. не сможем взять новый перечень с сайта.
