### ISSUE TITLE
Імпорт запасів: рядок курс валюти на дату не активний, не можна встановити через документ валюту на зазначену дату

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#582]

**Comment by AlexeyTishkin** [comment]
Валюта выбрана? Курс запрещается, если не выбрана валюта.

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/46952711-51264580-d094-11e8-8a49-65d14675ef55.png)
валюта выбрана. курс вручную в строке можно указывать , и документ пересчитывает, но нет выхода в справочник валют (как в остальных операциях с валютой). это баг, или фича? :)

**Comment by AlexeyTishkin** [comment]
Меню ... в селекторе валют: свойства, курсы.

**Comment by kattrina-brekhova** [comment]
ок
