### ISSUE TITLE
[Улучшайзинг] Более внятная поддержка работы c USB сканнерами штрих-кодов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#583]
Обсуждали 16.10 варианты показать юзеру, что мы умеем удобно работать с USB сканнерами штрих-кодов.
Речь шла о введении некоторой комбинации клавиш или кнопки, включающей сценарий получения новых штрих-кодов в объекты учета или известных товаров в счета/накладные.

**Comment by alex-kukhtin** [comment]
Done (7608)
Сделан акселератор в TextBox.
Посмотреть можно в Продажі / Операції (бета) / Рахунок
