### ISSUE TITLE
сайт beta - Митна декларація: курс валюти не показується в документі і сума операції не перераховується 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#584]
![image](https://user-images.githubusercontent.com/38099938/47069373-65368800-d1f7-11e8-9445-c8eb4f54e685.png)

![image](https://user-images.githubusercontent.com/38099938/47069383-6a93d280-d1f7-11e8-8e1f-69be23cc1a12.png)

перерахунок з’являється лише після того як вручну вводжу курс валюти.

**Comment by AlexeyTishkin** [comment]
Повторить не смог. Какая последовательность действий ?

**Comment by kattrina-brekhova** [comment]
очень странно, но сегодня все корректно отобразило
