### ISSUE TITLE
в списку операцій за певним контрагентом не показується операція по документу МД: сума мита та ПДВ 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#586]
![image](https://user-images.githubusercontent.com/38099938/47172051-0bc37b80-d313-11e8-97d3-70fb68510666.png)

![image](https://user-images.githubusercontent.com/38099938/47172075-1f6ee200-d313-11e8-8883-56f85f25eda2.png)

![image](https://user-images.githubusercontent.com/38099938/47172093-2eee2b00-d313-11e8-9768-e633e962d26a.png)

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by kattrina-brekhova** [comment]
отражается
