### ISSUE TITLE
Реалізація послуг - фізична особа (Друк акта) Не відображається адреса контрагента, питання щодо відображення ІПН

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#588]
1. У картці контрагента є поле "Фактична адреса", воно заповнене, але в акті на друк не виводиться.
![image](https://user-images.githubusercontent.com/42540074/47204760-cb084880-d38c-11e8-93ee-a610c99c0144.png)
![image](https://user-images.githubusercontent.com/42540074/47204810-e70bea00-d38c-11e8-8bf5-4ab0dd5ff53e.png)
2. Якщо покупець - фізична особа, в систему в реквізитах вводимо ії ІПН. В документі ІПН відображається як ЕДРПОУ. Юридично це не вірно (?).

**Comment by AlexeyTishkin** [comment]
Добавил.
