### ISSUE TITLE
В "Платіжному дорученні" допускает ввод отрицательного числа в поле "Сумма". 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#59]
В "Платіжному дорученні" допускает ввод отрицательного числа в поле "Сумма".  
Символы игнорирует - при вводе сбрасывает суму в 0.

**Comment by shevchuk-vadim** [comment]
Сделал проверку на отрицательную сумму.

**Comment by nik-man** [comment]
Исправлено. Проверяйте и закрывайте.
