### ISSUE TITLE
В акте услуг вписывать и материалы

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#593]
Клиенты хотят, чтоб можно было выписывать акт оказания услуг и чтоб в нем еще был список материалов, и все одним документом, а не разными, как сейчас.

**Comment by AlexeyTishkin** [comment]
Это уже не акт услуг. А какой-то "Наряд-заказ", к примеру.

**Comment by Anestezia** [comment]
Добавить по желанию таблицу материалов? Сделать как третий вариант документа, который будет подставляться, если в выставленном счете сразу указаны и услуги и материалы.
![default](https://user-images.githubusercontent.com/42540074/47220706-3b2dc300-d3bb-11e8-8992-cab19b2abb8f.jpg)
Нижняя таблица: При виконанні робіт (наданні послуг) використано наступні матеріали: (не нашла в лучшем качестве образец)

**Comment by shevchuk-vadim** [comment]
Наряд-заказ - так этот документ принятно называть на СТО. А в других случая он называется "акт", как обычно.

Думаю, что в акт сдачи услуг нужно добавить еще одну таблицу с материалами. Но если она пустая, то на печать ее не выводить.

**Comment by AlexeyTishkin** [comment]
Печатная форма может называться и "Акт".
А рабочая форма должна быть другая.

**Comment by AlexeyTishkin** [comment]
> Сделать как третий вариант документа

Да. Отдельный документ (рабочая форма).

**Comment by AlexeyTishkin** [comment]
Добавлена операция "Реалізація послуг з матеріалами".
