### ISSUE TITLE
Добавить подсказку "Элементов еще нет" с бегущей стрелочкой .

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#595]
Придбання:
- [x] Операції
- [x] Контрагенти
- [x] Договори
- [x] Проекти
- [X] Об'єкти обліку
- [x] Довідники/Групи об'єктів

Продажі:
- [x] Операції
- [x] Контрагенти
- [x] Договори
- [x] Проекти
- [X] Об'єкти обліку
- [x] Довідники/Групи об'єктів

Запаси:
- [x] Операції
- [x] Контрагенти
- [X] Об'єкти обліку
- [x] Довідники/Групи об'єктів

НА:
- [x] Операції
- [x] Об'єкти обліку

Бухгалтерія:
- [x] Рахунки в банках
- [x] Банківські операції
- [x] Касові операції
- [x] Інші операції
- [x] Початковий баланс
- [x] Контрагенти
- [x] Договори
- [x] Довідники/Банки

Персонал:
- [x] Документи
- [x] Фізичні особи
- [x] Співробітники
- [x] Довідники/Посади
- [x] Довідники/Професії

Звітність:
- [x] Створені сьогодні
- [x] Створені у цьому місяці
- [x] Чернетки
- [x] Відправлені
- [x] Прийняті
- [x] Не прийняті
- [x] Усі звіти

**Comment by AlexeyTishkin** [comment]
И куда в Продажах/Прайс-листы стрелку вести ? :)

**Comment by Illya-Lykhachov** [comment]
Персонал. Сделано.

**Comment by htrofymova** [comment]
НА - добавлено

**Comment by mik-man** [comment]
Везде добавлено. ))
