### ISSUE TITLE
Добавить селектор вида группировки операций.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#596]
- [x] Придбання / Операції
- [x] Продажі / Операції
- [x] Запаси / Операції
- [ ] НА / Операції
- [X] Бухгалтерія / ...
- [x] Персонал / Документи

**Comment by Anestezia** [comment]
1. Работает корректно, и в сочетании с отбором в указанном периоде, и с главным отбором по конкретной операции, тоже все ок.
2. Аналогично.
3. Аналогично.
4. Не реализовано.
5. По всем операциям ок.
6. Не реализовано.

**Comment by Illya-Lykhachov** [comment]
Персонал . Сделано
