### ISSUE TITLE
Свойства расчетного счета. Добавить возможность установки овердрафта.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#599]
Дополнительное числовое поле "Сумма овердрафта". По умолчанию ноль.
Если там установлено какое-то значение, значит по этому счету разрешать уходить в минус до указанной суммы.

**Comment by DenisClone** [comment]
Может лучше два поля?
- чек бокс, есть овердрафт или нет
- второй сумма овердрафта, если ноль то без ограничения
