### ISSUE TITLE
Предложение : В "Платіжному дорученні" изменить вид/название полей ввода

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#60]
На данный момент в "Платіжному дорученні" у нас просто дублируются поля плательщика и получателя.
При этом поле "Номер счета" (в котором должен быть номер расчетного счета) периодически людьми воспринимается как "Номер счета-фактуры", хоть и не логично :)

Предлагаю обсудить :
Убрать вообще (или скрыть под кат) блок полей плательщика - по идее эти данные подтаскиваются из собственного текущего предприятия.
Блок полей получателя выделить (например рамкой, серым фоном), как-то а-ля платеж в новом интерфейсе Приват24 для бизнеса.

Или хотя бы уточнить в названиях полей :
"Номер рахунку (код, банк, код банку) платника" 
"Номер рахунку (код, банк, код банку) отримувача"

У Привата это выглядит так : 
![image](https://user-images.githubusercontent.com/38098758/38667207-8454473c-3e49-11e8-9fd6-1121c6b29e17.png)

**Comment by shevchuk-vadim** [comment]
Блок полей плательщика удалять нельзя, потому что там счет в банке может выбираться.

Поля я называл так, как они названы в утвержденной форме платежного поручения. Если считаешь, что их необходимо уточнить, дописывая "плтаника/отримувача" - сделаю.

**Comment by shevchuk-vadim** [comment]
У Привата банк - только Приват. У нашего клиента могут быть разные банки. Поэтому, только номера счета недостаточно.

**Comment by MaksymTikhomirov** [comment]
У нас на первом этапе счет клиента - счет в Айбоксе

**Comment by shevchuk-vadim** [comment]
Макс, ты хочешь на первом этапе убрать в платежке банк моей фирмы? Для моей фирмы убрать возможность заводить счета в других банках?

**Comment by MaksymTikhomirov** [comment]
Не, не для всех
Но у части клиентов (условно бесплатных) возможность заводить счета в других банках будет забанена

**Comment by shevchuk-vadim** [comment]
В названиях полей дописал "плтаника/отримувача".

**Comment by nik-man** [comment]
Пожалуйста, проверяйте и закрывайте.
