### ISSUE TITLE
Нужен импорт готовой базы контрагентов (из 1с)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#602]
Клиенты уже интересуются по полной.

**Comment by mik-man** [comment]
+1 Для начала можно не из 1С, а из Excel-файла.

**Comment by mik-man** [comment]
up:
Звонил клиент, интересовался, почему для ОУ есть кнопочка загрузки, а для СУ нет. ))

**Comment by AlexeyTishkin** [comment]
Сделал механизм импорта из файла в формате Excel.
