### ISSUE TITLE
Митна декларація - експорт запасів - не змінює курс валюти: нашла алгоритм возникновения ошибки о коротой уже писала

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#603]
Таки нашла алгоритм, как система не учитывает изменения в курсе валюты 
Таможенная декларация - экпорт запасов
ввела номер, выбрала покупателя, валюту... сразу система подтянула курс на предыдущую дату, выбрала товар

вспомнила, что курс поменялся
ввела новый
![image](https://user-images.githubusercontent.com/38099938/47304377-1fcaee00-d62f-11e8-8448-22ace650bd75.png)
и на этом все - курс новый не подтягивает
![image](https://user-images.githubusercontent.com/38099938/47304405-3c672600-d62f-11e8-9ecf-5f28914499ac.png)
только если ручками ввожу, то появляется кнопка "перерахувати"
![image](https://user-images.githubusercontent.com/38099938/47304437-586ac780-d62f-11e8-8b2a-29315c0f283a.png)

**Comment by AlexeyTishkin** [comment]
В данном случае новый курс нужно устанавливать в меню "..." селектора валюты в пункте "Курси валют". Во- первых, так быстрее, а во вторых второй путь (если вначале свойства, потом в списке курсы валют) не приводит ни к каким изменениям в документе (валюта не перевыбиралась).

**Comment by kattrina-brekhova** [comment]
что-то не так. прохожу по тому же алгоритму (забывчивый пользователь):
все ввела - выбрала валюту, заполнила ассортимент
![image](https://user-images.githubusercontent.com/38099938/47634883-ae71ca80-db5b-11e8-9629-99bbd8169ff2.png)
потом вспомнила, что курс валюты не указала на текущую дату
![image](https://user-images.githubusercontent.com/38099938/47634914-c8aba880-db5b-11e8-9bcc-019f91d71449.png)
установила нужную
![image](https://user-images.githubusercontent.com/38099938/47634939-dcefa580-db5b-11e8-978f-a526ed5d2576.png)
выбрала валюту с учетом нового курса, а в документе все-равно старый курс
![image](https://user-images.githubusercontent.com/38099938/47634960-ee38b200-db5b-11e8-80f6-b1bfb48983a7.png)
после нажатия кнопки "перерахувати" она исчезла
![image](https://user-images.githubusercontent.com/38099938/47634983-06103600-db5c-11e8-9bdf-9b50e6d1be9d.png)

**Comment by AlexeyTishkin** [comment]
> установила нужную

Была USD, стала USD - ничего не поменялось.

**Comment by AlexeyTishkin** [comment]
> после нажатия кнопки "перерахувати" она исчезла

"перерахувати" повляется при смене курса, когда нужно что-то пересчитать. После нажатия пересчитавать нечего. Если понадобится опять что-то пересчитать, то "перерахувати" появится.

**Comment by AlexeyTishkin** [comment]
> потом вспомнила, что курс валюты не указала на текущую дату

Не надо идти в выбор валюты, в меню "..." пункт "Курси валют".

**Comment by kattrina-brekhova** [comment]
я меняла курс на текущую дату. в диалог редактирования курса входила через таможенную декларацию.

**Comment by AlexeyTishkin** [comment]
> я меняла курс на текущую дату. в диалог редактирования курса входила через таможенную декларацию.

Судя по картинкам путь был такой: селектор валюты - выбор валюты - диалог со списком валют - в списке на валюте кнопка "Курсы".
А надо: селектор валюты - меню "..." - "Курсы".
При выбранной валюте не нужно заново заходить в диалог выбора валюты.

**Comment by kattrina-brekhova** [comment]
ишью закрываю. уникальным продукт делают фичи :)

**Comment by kattrina-brekhova** [comment]
> > я меняла курс на текущую дату. в диалог редактирования курса входила через таможенную декларацию.
> 
> Судя по картинкам путь был такой: селектор валюты - выбор валюты - диалог со списком валют - в списке на валюте кнопка "Курсы".
> А надо: селектор валюты - меню "..." - "Курсы".
> При выбранной валюте не нужно заново заходить в диалог выбора валюты.

Леша, а если серьезно, то в таких документах после выбора и установки валюты возможно заново заходить в валюты через соответствующую строку, изменять курс и чтоб пересчитывало? Можно перенастроить алгоритм, чтоб документ все-таки перерасчитывал в соответсвии с измененим валюты?
Честно - даже зная об этой фиче, я все так же забываю сразу установить нужный курс и приходится потом заново пересоздавать документ

**Comment by AlexeyTishkin** [comment]
Зачем заходить в валюты ?
Измение курса - меню "..." - Курсы.

**Comment by AlexeyTishkin** [comment]
![image](https://user-images.githubusercontent.com/35917940/48200568-3465f080-e368-11e8-9caa-4707385ba4bd.png)

**Comment by kattrina-brekhova** [comment]
так и есть, выбирала и меняла валюту через это окошко рабочей формы ТД
в вертикальное меню справочник валют в данном случае не обращалась

**Comment by AlexeyTishkin** [comment]
1. Выбрали валюту.
2. Увидели, что не внесен курс на дату.
3. В этом меню пункт "Курсы валют".
