### ISSUE TITLE
Вставить в личный кабинет ссылку на инструкцию по оплате сервиса через платежный терминал 

### ISSUE THREAD

**Issue by MaksymTikhomirov** [a2develop/bugTracker#612]

**Comment by DenisClone** [comment]
В инструкции мои личные данные указаны. Мы их для тестирования указывали, так они их и добавили в инструкцию :)

**Comment by MaksymTikhomirov** [comment]
> В инструкции мои личные данные указаны. Мы их для тестирования указывали, так они их и добавили в инструкцию :)

Надо переделывать )))

**Comment by kattrina-brekhova** [comment]
инструкцию в хелпе сделала, файл отправила на гит. нужно опубликовать
+ мне еще задание небольшие инструкции по оплате: безнал, банковская карта...и ты говорил Ощад?

**Comment by MaksymTikhomirov** [comment]
?

**Comment by MaksymTikhomirov** [comment]
Up

**Comment by MaksymTikhomirov** [comment]
Up

**Comment by MaksymTikhomirov** [comment]
UP блин

**Comment by Anestezia** [comment]
![2](https://user-images.githubusercontent.com/42540074/50842328-1c621b80-136f-11e9-8c18-ba5dcf540e44.jpg)
Как-то так

**Comment by alex-kukhtin** [comment]
Вставил ссылку в ЛК
![image](https://user-images.githubusercontent.com/26379138/51144757-ab34d380-185a-11e9-9e38-baf09d66729e.png)
