### ISSUE TITLE
Было бы хорошо, если б документы и операции сервиса четко вели на соответсвующие страницы в хэлпе

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#613]
например, страницы отчеты пусть ведет  на хэлп отчетность http://help.bookkeeper.kiev.ua/fiscal/index
и т.д... а то сейчас большинство знаков вопроса в отдельном разделе ведут только на соответствующие разделы хэлпа - 
если нужно подвязать, покидать ссылки куда к чему - я только за!

**Comment by kattrina-brekhova** [comment]
кто подтянет ссылки помощи на документы сервиса? кому и в каком виде подготовить файл название операций - ссылки на хэлп?

**Comment by AlexeyTishkin** [comment]
Добавил в документы разделов "Придбання", "Продажі", "Запаси".

**Comment by htrofymova** [comment]
Добавлено в документы раздела Необоротні активи

**Comment by Illya-Lykhachov** [comment]
Добавлено в документы раздела "Персонал"

**Comment by htrofymova** [comment]
Добавлено в документы раздела "Бухгалтерия" (кроме банковских).
