### ISSUE TITLE
Приделать "крутилку" или любую развлекуху юзера при задержке в получении выписки

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#615]
При импорте выписки за достаточно большой период появляется пауза в 2-3-4 секунды. При этом не экране ничего не меняется, юзер успевает напрячься.

Желтой полоски не видно - сливается с фоном заголовка.

Нужна какая-то заметная крутилка или любой другой вариант отвлечь пользователя от тягостных дум и сомнений.

**Comment by Anestezia** [comment]
Ага, Как монетки безконечно сыпятся
