### ISSUE TITLE
Добавьте в описании карточки объекта учета вспомогательные подсказки. Вставила текст в тело ишью

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#619]
Група – Визначає спосіб класифікації і сортування об’єктів обліку в групи за спільними ознаками, або характеристиками. Наприклад: «Побутова техніка», «Мобільні телефони», «Комп’ютери».

Ставка ПДВ – Встановлена ставка ПДВ буде визначати розмір нарахованого податку на операції придбання/продажу створеного об’єкта обліку.

Код УКТ ЗЕД – Код із українського класифікатора товарів, розробленого для зовнішньоекономічної діяльності. Визначає розмір мита та інших платежів, що стягуються при переміщенні об’єкта обліку через митний кордон України. Є обов’язковим реквізитом в податковій накладній.

Країна походження – Вказується країна, де товар було вироблено, або піддано достатній переробці. Визначає розмір мита та інших платежів, що стягуються при переміщенні об’єкта обліку через митний кордон України.

Код ДКПП – Код із Державного класифікації продукції та послуг. Є обов’язковим реквізитом в податковій накладній для послуг.

**Comment by AlexeyTishkin** [comment]
Сделал.
