### ISSUE TITLE
Операция Безоплатне одержання запасів Не проводится ни для юр.лиц, ни для физ.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#621]
![image](https://user-images.githubusercontent.com/42540074/47555603-e509d400-d914-11e8-8a68-7625f0d210e5.png)
Здесь моя фирма юр. лицо, плательщик НДС, общие основания.

**Comment by AlexeyTishkin** [comment]
Исправлено.

**Comment by Anestezia** [comment]
Хорошо,спасибо!
