### ISSUE TITLE
При импорте выписки относить контрагентов с МФО 899998 к Держ Органам 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#625]
Сейчас при импорте платежек из выписки мы проверяем совпадение ЕДРПОУ контрагента с ранее созданным списком контрагентов тенанта, и если совпадения не находим - назначаем контрагенту роль Покупець.

У нового юзера велика вероятность попадания в Покупатели органов налоговой, потом удем иметь головную боль с объяснениями, как поменять.

Думаю, при отсутствии ЕДРПОУ в списке стоит проверять МФО, и при совпадении с единым МФО Казначества 899998 назначать контрагенту роль Держ. орган

**Comment by AlexeyTishkin** [comment]
Сделал.
