### ISSUE TITLE
Админка, добавление сортировки платежей по "Статусу"

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#627]
В админке, в разделе "Биллинг" необходимо добавить сортировку операций по "Статусу".
Как вариант сделать фильтр, который будет отображать операции только одного выбранного статуса.

**Comment by DenisClone** [comment]
Для вычисления суммы выплаты дилерам, необходимо добавить еще два фильтра.
В левом меню будет находиться 3 фильтра:
- По статусу (отбирать по любому из существующих статусов, либо все статусы)
- По источнику (отбирать по любому из существующих источников: Соната, Сервис, ТАС, Офис и т.д. , либо все источники)
- По периоду (достаточно будет выбор месяца, но для большей гибкости, можно сделать ручной выбор периода, либо за все время)

**Comment by alex-kukhtin** [comment]
Чтобы удобно было считать суммы - нужно просто отчет написать :-)

**Comment by DenisClone** [comment]
Ну в отчете то тоже нужно параметры выбирать. 
А он уже будет формироваться через кнопочку - Ексель :)

**Comment by alex-kukhtin** [comment]
Done in 7369
