### ISSUE TITLE
Админка, добавление в раздел Биллинг отображение источника прихода тенанта

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#628]
В админке, в разделе "Биллинг" необходимо добавить отображение канала, через который пришел клиент: Соната, Сервис, ТАС и т.д.
Это необходимо для расчета с дилерами.

**Comment by DenisClone** [comment]
И сразу пришло понимание, что нужна будет сортировка по этому полю.  Добавлю в 627-е ишью.

**Comment by alex-kukhtin** [comment]
Done in 7369
