### ISSUE TITLE
Предмет договору ЗЕД, маленькое поле для печати. Експорт услуг - печать.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#629]
![image](https://user-images.githubusercontent.com/42540074/47649250-5485fa80-db85-11e8-9b45-1259c1066399.png)
П.С. Где ЗЕД-вкладка нашей фирмы? Имя и адрес?

**Comment by AlexeyTishkin** [comment]
Изменил.

**Comment by Anestezia** [comment]
Проверила, все ок.

**Comment by Anestezia** [comment]
В ПДФ не видно, по-старому.
![image](https://user-images.githubusercontent.com/42540074/48477328-f9e9d100-e809-11e8-8239-fc8d56ed3fa4.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
