### ISSUE TITLE
В приказе о приеме на работу добавить пробел "2018р."->"2018 р."

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#630]
В приказе о приеме на работу добавить пробел в дате между годом и "р."
![image](https://user-images.githubusercontent.com/38098758/47711755-b35b7a80-dc3e-11e8-90de-a88ccd22f41e.png)

тут пишется "2018р.", во всех остальных местах у нас "2018 р." или "2018 року"

**Comment by Illya-Lykhachov** [comment]
исправлено
