### ISSUE TITLE
Немає донарахування до мінімальної зп, якщо не всі дні відпрацьовано, навіть при лікарняному.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#631]
![image](https://user-images.githubusercontent.com/42540074/47775974-e7e03c80-dcf9-11e8-8fda-7eb6cc96d9b9.png)

**Comment by Illya-Lykhachov** [comment]
так и должно быть

**Comment by shevchuk-vadim** [comment]
Если был больничный, и сумма его сумма вместе с зарплатой меньше минимальной зарплаты, то доначисление базы ЕСВ до минимальной зарплаты делать надо.

**Comment by Illya-Lykhachov** [comment]
А если 2 больничных, один из которых закончился, а второй ещё нет?
Проблема в невозможности точно определить полный месяц работал/болел/был в отпуске сотрудник или нет. Дни по графику не ориентир - нельзя складывать рабочие дни и календарные (больничный). Без табеля проблема не решается.
В качестве временной меры буду доначислять ЕСВ, если дни отработанные + дни болезни + дни отпуска >= дни по графику. Не совсем правильно, но максимально близко.

**Comment by Illya-Lykhachov** [comment]
закрыть пора
