### ISSUE TITLE
Договоры отображаются по предмету. Если он длинный - недоступны кнопки редактировать и удалить.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#632]
![image](https://user-images.githubusercontent.com/42540074/47776454-1f9bb400-dcfb-11e8-8b5c-d545d3e19e89.png)

**Comment by alex-kukhtin** [comment]
Извращенец :-)
Ну нафига делать одно слово из 300 символов?
Ладно. Все равно поправил в 7352.

**Comment by mik-man** [comment]
> Извращенец :-)

Настя, он такой, да. ))

**Comment by alex-kukhtin** [comment]
Ты ж научил. Я уверен.
Не верю, что ей это в голову могло прийти.

**Comment by Anestezia** [comment]
Я проверяла просто количество печатных символов, пробел - тоже символ, поэтому и не заморачивалась. В голову не могло прийти, что наличие пробелов в данной ситуации значимо.

Теперь все в порядке, спасибо!
