### ISSUE TITLE
Табличные отчеты. Пока нет кнопки "Друк/експорт", сделать подсказку как печатать.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#633]
Пользователи не могут распечатать отчеты. По большому счету это не проблема, можно нажать "Ctrl+P", но сами пользователи до этого не догадываются.
- [x] Может быть на отчетах сделать значок вопроса с соответствующей подсказкой?
- [x] Или как вариант — сделать кнопку "Печать", но неактивную, а при наведении мышки будет выводить подсказку "Печать в разработке. Нажмите "Ctrl+P" для печати."

![2018-10-31](https://user-images.githubusercontent.com/35918141/47779891-e8310580-dd02-11e8-96bf-7b9350fc0cb4.png)

**Comment by AlexeyTishkin** [comment]
Добавил кнопку "друк" в отчеты:
Відомість за розрахунками з постачальниками
Відомість за розрахунками з постачальниками у валюті
Відомість за розрахунками з покупцями
Відомість за розрахунками з покупцями у валюті
Відомість за розрахунками з іншими дебіторами
Оборотна відомість по складу
Валовий прибуток
Оборотність запасів

**Comment by AlexeyTishkin** [comment]
Я думаю, что нужно создать отдельный issue где перечислить отчеты, в которых еще нет кнопки "друк".

**Comment by mik-man** [comment]
Согласен. Так и сделаю.
