### ISSUE TITLE
Удаление выписки - не учитываем проведенные платежки

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#634]
Была выписка с несколькими платежками.
Часть проведена, у части проведение отменено.
Понадобилось выписку удалить.
Нажали удалить - выписка удалилась и окно браузера закрылось окно насовсем.

Видимо, при наличии проведенных платежек нужно запрещать удалять выписку?

**Comment by AlexeyTishkin** [comment]
Сделал.
