### ISSUE TITLE
Добавить документ "Внесення власніх коштів" (ФОПом на свой расчетный счет)

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#638]

**Comment by Illya-Lykhachov** [comment]
Уточнить является ли такая операция доходом и проводки

**Comment by htrofymova** [comment]
из свежего -  https://news.dtkt.ua/debet-kredit/partner-news/53477
это от 15/02/2019
ключевая фраза: "Отже, вкотре можемо зробити висновок, що кошти, які внесені на розрахунковий рахунок, не є доходом виключно тоді, якщо призначення платежу буде «Виторг за період»."

**Comment by Illya-Lykhachov** [comment]
Тогда, при выборе операции, нужно подставлять «Виторг за період» в назначение платежа.

**Comment by htrofymova** [comment]
проводку бы... придумать

**Comment by kattrina-brekhova** [comment]
https://bk.kiev.ua/chi-vklyuchati-do-dohodu-vlasni-koshti-fop-vneseni-na-rozrahunkovij-rahunok/
общесистемник фоп может вносить деньги на счет и это не будет считаться доходом
также не будет доходом если будет внесена выручка фоп 1-3 групп
во всех остальных случаях - считается доходом

**Comment by kattrina-brekhova** [comment]
как вариант проводка Дт301 КТ685 (отправитель - ФИО самого ФОП). Дт311 Кт301
но єто не точно

**Comment by htrofymova** [comment]
готово. проводка: дт311 кт 682
