### ISSUE TITLE
[Улучшайзинг] Автоматически определять кодировку файлов импорта из клиент-банков

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#639]
Вадим предложил не напрягать юзера выбором кодировки при импорте файла выписки, и убрать вообще эту настройку с глаз долой, просто чтобы исключить объяснение особо тёмным что это вообще такое.
Утверждает, что можем определять кодировку всех файлов выписок достоверно.

Идею всецело поддерживаю.

**Comment by alex-kukhtin** [comment]
Done in 7349
