### ISSUE TITLE
Недоработка: Добавить операцию и документ по списании запасов в процессе основной деятельности

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#64]
Во время работы с разделом Запасы возникла сложность. К примеру, я ФОП, моя деятельность связана с предоставлением услуг по макияжу, я пользуюсь косметикой, стоимость которой нужно будет списать и включить в сумму расходов основной деятельности. Документа по списанию таких материалов я не нашла.

**Comment by nik-man** [comment]
В "Списании" в дебете могут быть такие счета:
23, 91, 92, 93, 947
Соответственно, нужно пять видов операций.
Еще есть счет 949.
Так, что даже шесть.

**Comment by AlexeyTishkin** [comment]
В "Акте списания" появилась возможность выбора счета. Выбор в "Списання на". Проверяйте.
