### ISSUE TITLE
Подраздел "Операції". Сортировка по виду операции, колонка "Назва".

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#640]
Отсутствует возможность сортировки списка операций по колонке "Назва" в разделах:
- [ ] "Придбання"
- [ ] "Продажі"
- [ ] "Запаси"

Кстати, почему бы не сделать сортировку по колонке "Стан" ?

**Comment by AlexeyTishkin** [comment]
Так обсуждали же, что нужно отключить. Сортировка из-за словаря - не правильная.

**Comment by mik-man** [comment]
Временно закрою. ;)
