### ISSUE TITLE
Оплата картой - нет обратной ссылки на сервис с окна подтверждения платежа

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#642]
Очень раздражает, что после оплаты картой и подтверждения платежа нет возможности человеческим способом  вернуться обратно на Бкпр

На ТАСовском окне ничего подобного "Повернутися на сайт" нет
![image](https://user-images.githubusercontent.com/38098758/47842780-5c80ad00-ddc6-11e8-9cb3-2a7b5ad06c96.png)

Если мы можно было вызывать ТАСовскую страницу внутри нашей, например - было б щасте.

**Comment by alex-kukhtin** [comment]
Вроде как уже у нас диаложек. И давно.
Надо закрыть
