### ISSUE TITLE
Не корректное название строки в банковской выписке

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#643]
![image](https://user-images.githubusercontent.com/38099938/47858559-0840f180-ddf5-11e8-80f8-abef9a4c928d.png)

строка Контрагент - при наведении сервис пишет "Оберіть платника", в данном случае у нас расход - поэтому у нас получатель
 или менять название "Оберіть платника"/"Оберіть отримувача" - в зависимости от платежного поручения, или сделать единую подсказку "Оберіть контрагента"

**Comment by AlexeyTishkin** [comment]
Исправил.
