### ISSUE TITLE
Сделать запрет на проведение документа Виплата ЗП банк по причине "Особа не прийнята на роботу"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#644]
В кассовом такое сделано, а в банке нет. Можно выплатить кому угодно.
![image](https://user-images.githubusercontent.com/42540074/47913106-8b208580-dea3-11e8-8720-b1e41d8e49ee.png)
Или поменять каталог подстановки лиц для оплаты. В банке - это контрагенты (физ. лица), а в Виплате ЗП в кассовых операциях - Фізичні особи. Или вообще и туда и туда прикрутить каталог Співробітники.

**Comment by htrofymova** [comment]
На данный момент, в кассовом расходном ордере такой запрет отключен. Это сделали после появления раздела Зарплата. также для возможности выплатить зарплату уже уволенному сотруднику. Может не актуально уже?
