### ISSUE TITLE
Кнопка "Отправить в банк" в платежном поручении - недопилено

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#645]
Имеем проблемы с кнопкой "Отправить в банк" в платежном получении:

1. Кнопка видна даже если обмен по API не настроен.
При настройке на импорт из файла - выдает ошибку 
![image](https://user-images.githubusercontent.com/38098758/47911984-b608da80-de9f-11e8-86b6-06579c31d923.png)
Если настроить API и снова переклюдчиться - ошибка пропадает, показывается желтая бегущая полоска и ничего не происходит.
Думаю, при ненастроенном обмене по API нужно эту кнопку вообще прятать, как и для всех остальных не-приватовских юзеров (точнее даже у юзеров банков, с которыми нет обмена в онлайне).

2. Никак не отслеживаем отправку непроведенной платежки.
Как идеологически мы себе алгоритм представляли?
Можно отправлять непроведенную платежку?
Ну и при отправке в самом Привате ничего не появляется.
Сообщений об успешной отправке или ошибке не появляется.

**Comment by alex-kukhtin** [comment]
fixed in 7376
