### ISSUE TITLE
Регистрация новой учетной записи неавтоматическая.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#65]
По-прежнему нового пользователя нужно активировать вручную.

**Comment by alex-kukhtin** [comment]
Сделали, проверяйте и закрывайте.

**Comment by nik-man** [comment]
Так выглядит, как будто еще какой-то скрипт не запущен.
Нет списка создания документов через разделы "Операции/СУ/ОУ/Договора"
Нет Моей фирмы.
Нет склада.
Нет страны.

**Comment by AlexeyTishkin** [comment]
Попробуй сейчас.

**Comment by nik-man** [comment]
Да, теперь ок.
