### ISSUE TITLE
Процедура обработки учетки пользователя, который не подтвердил мыло

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#652]
Много думал об этом, и пришел к выводу, что слишком много действий мы планируем делать. По сути все это только ради того, чтобы сохранить данные пользователя.
Сначала делаем копию учетки с добавлением символов к текущему мылу, потом удаляем старую учетку. Потом следим когда он заведен новую учетку, и если все хорошо, то удаляем временную. А если он снова не подтвердил мыло, вторая временная учетка будет конфликтовать по названию мыла с первой временной. В общем много действий только ради сохранения данных пользователя.
Предлагаю все упростить:
1. Делаем проверку на подтверждение мыла, по всем учеткам созданным за предыдущие сутки (запуск процедуры в 23:50 каждый день)
2. Если такие находятся, то отправляем письмо о удалении такой учетки двум адресатам: владельцу учетки и на мыло нашего Саппорта.
3. Удаляем учетку.

Таким образом у нас останется информация о удаленном пользователе и не будет конфликтов при последующих регистрациях.

**Comment by alex-kukhtin** [comment]
А сам написать сможешь?

**Comment by alex-kukhtin** [comment]
Можно проще.
1. Все таки делаем процедуру в runbook. Она ищет неудачные регистрации, переписывает их в другую таблицу и сразу удяляет.
2. В админке делаем раздел "Неудачные регистрации" А там уже админ сам смотрит, что с ними делать. Отправить мейл или просто удалить, если там, например, ошибка в имени домена.
3. Профит!

**Comment by DenisClone** [comment]
Сам? Я бы себя не подпускал к удалению пользователей :) Опыта то нету
Можно сделать и таким способом, он более трудоемкий в разработке, но более удобный в дальнейшей эксплуатации. И получается в этой новой таблице, не должно быть проверки на уникальность, т.к. одно и тоже мыло в нее может попасть несколько раз.

**Comment by alex-kukhtin** [comment]
Хорошо. Я процедуру напишу и табличку сделаю.
А ты потом runbook сделаешь, чтобы она запускалась периодически.

**Comment by DenisClone** [comment]
Появилась еще одна мысль: можно удалять такие учетки вручную. Т.к. такие ситуации не частые.
Если мыло не подтверждено, то возле него в админке, выводить кнопку - "Удалить". 
Это позволит нам оперативно удалить учетку, в которой указано несуществующее мыло, и дать возможность клиенту зарегистрироваться заново, указав тот же самый номер телефона.

**Comment by alex-kukhtin** [comment]
7554. Тупо добавил кнопку удаления.

**Comment by DenisClone** [comment]
Удалил старую тестовую запись)
