### ISSUE TITLE
В актах выполненных работ нужно сделать возможность выбора 377 для начисления таможенного сбора при экспорте с дальнейшей его оплатой

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#653]

**Comment by Anestezia** [comment]
И не только подакцизных. Есть товары, норма экспорта которых искусственно ограничивается. Например, мед. Он не подакцизный, Есть квота на определенное количество. Допустим, сто тысяч тонн. Эти сто тысяч вывозятся по ставке мыта 0%. А вот стотысяче-первая тонна вывозится уже с таможенным платежем при экспорте.  Просто внесение в учет таможенных платежей при экспорте.

**Comment by AlexeyTishkin** [comment]
Сделал.
