### ISSUE TITLE
Импорт выписки - косячит справочник

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#656]
Если при импорте выписки ткнуть 
![image](https://user-images.githubusercontent.com/38098758/48197443-6a05dc00-e35e-11e8-8895-22f3e29e7bfe.png)
имеем мелкий косяк 
![image](https://user-images.githubusercontent.com/38098758/48197459-75590780-e35e-11e8-91f0-0b8bc9762970.png)
после чего справочник открывается с виду нормально
![image](https://user-images.githubusercontent.com/38098758/48197501-8c97f500-e35e-11e8-888d-2932e6ecda18.png)

**Comment by alex-kukhtin** [comment]
Леш, сделай мне пример. Я не вижу проблему

**Comment by AlexeyTishkin** [comment]
1. Создать выписку.
2. Добавить строку.
3. Выбрать любую операцию.
4. Начать выбор платежного поручения.
5. В открывшемся диалоге в фильтре по операции не сработал словарь.

**Comment by AlexeyTishkin** [comment]
Исправлено.
