### ISSUE TITLE
Документ Бухгалтерская Справка с самостоятельным подбором проводок и формулировок операций

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#657]
Предлагается сделать такой документ, чтоб клиент мог в нестандартных ситуациях закрывать свои вопросы по проводкам, пока у нас не учтены все возможные операции для ведения полноценного учета. (продумать внутренний план счетов и взаимодействие с ним других документов).

П.С. При выборе этой операции через диалоговое окно три раза спросить Точно ли в списке существующих операций нет искомой? и Точно ли хватает мозгов все ввести правильно?

**Comment by AlexeyTishkin** [comment]
Сделана первая версия. Пробуем.
