### ISSUE TITLE
Кнопка Сохранить в Word-Excel внутренние отчеты, оборотки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#659]
Клиенты просят добавить возможность сохранять отчеты

**Comment by alex-kukhtin** [comment]
Сделан экспорт в Excel

**Comment by Anestezia** [comment]
Остались еще: 
- [x] Відомість за розрахунками з постачальниками у валюті
- [x] Оборотна відомість по складу
- [x] Відомість за розрахунками з покупцями у валюті
- [x] Валовий прибуток
- [x] Оборотність запасів
- [x] Необоротні активи. Відомість по групах
- [x] Відомість за необоротними активами
- [x] Оборотно-сальдова відомість по касі
- [x] Оборотно-сальдова відомість по рахунку в банку
- [x] Оборотно-сальдова відомість по рахунку в банку в іноземній валюті
- [x] Cписок прийнятих
- [x] Cписок співробітників
- [x] Середньооблікова кількість працівників
- [x] Розрахунково-платіжна відомість

**Comment by htrofymova** [comment]
Відомість по групах необоротних активiв,  Відомість за необоротними активами - готово

**Comment by alexeijur** [comment]
Добавлены кнопки с экспортом в Excel:
- Cписок прийнятих
- Cписок співробітників
- Середньооблікова кількість працівників
- Розрахунково-платіжна відомість

**Comment by Anestezia** [comment]
Чьи остальные три отчета?

**Comment by Anestezia** [comment]
1. Оборотность запасов чуть подкрутить, в екселе скомкана строка
![image](https://user-images.githubusercontent.com/42540074/51978111-e7d71080-2491-11e9-9e23-58cc343adf92.png)
2. Ведомость по необоротным активам чуть окошки растянуть
![image](https://user-images.githubusercontent.com/42540074/51978237-51efb580-2492-11e9-8413-a6f157c9b8bd.png)
3. Инвентарная карта окошки больше сделать, относительно названия объекта
![image](https://user-images.githubusercontent.com/42540074/51978362-b1e65c00-2492-11e9-80eb-59496b3900d9.png)
4. Общая ОСВ длинные названия счетов не влезают, вручную растянуть можно, но их немало
![image](https://user-images.githubusercontent.com/42540074/51978485-fffb5f80-2492-11e9-8292-ae79451c3a04.png)
5. Акт сверки расчетов нижняя часть
![image](https://user-images.githubusercontent.com/42540074/51978608-494baf00-2493-11e9-8fe8-d3581fa2a4f0.png)
6. Розрахунково-платижна ведомость чуть подправить шапку
![image](https://user-images.githubusercontent.com/42540074/51978800-e0b10200-2493-11e9-858d-59ca926e663f.png)

**Comment by mik-man** [comment]
> Чьи остальные три отчета?

ОСВ по кассе и банку приведены к новому виду.

**Comment by Anestezia** [comment]
Касса и банк желательно сделать ширину строк в екселе по ячейке с названием счета учета.
![image](https://user-images.githubusercontent.com/42540074/52330287-c92ac980-29fd-11e9-8bb4-053d6c5c12a5.png)
и в валютном банке желательно расширить ячейки под большие суммы
![image](https://user-images.githubusercontent.com/42540074/52330564-5d952c00-29fe-11e9-9965-a0e8a18164b1.png)
