### ISSUE TITLE
Недоработка: создать документ, которым можно проводить операции по оприходованию на склад изделия/товары собственного производства

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#66]
еще есть ситуация.... например, я ФОП, и делаю украшения. каким документом я смогу проводить поступление готовых изделий на склад?

**Comment by nik-man** [comment]
Название документа: "Оприбуткування з виробництва" или просто "Оприбуткування"
Проводки: Дб (тип ТМЦ) Кр 23

**Comment by AlexeyTishkin** [comment]
Добавил в Акте выбор счета "Оприбуткування з". Пробуй.
