### ISSUE TITLE
В документе Начисление налогов сделать возможность удалять строки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#660]
В документе Начисление налогов сделать возможность удалять строки, если в квартале деятельность велась не с первого месяца. И чтоб документ при этом нормально проводился и согласовывался с отчетами.

**Comment by mik-man** [comment]
Возможно, где-то в свойствах фирмы нужно вносить дату регистрации юр.лица.

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/660#issuecomment-438197940
И чтоб эта дата куда надо принималась в расчет

**Comment by htrofymova** [comment]
готово
