### ISSUE TITLE
Разослать приглашения на семинар (персональные).

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#667]
Перечень приглашенных (иногда с емейлами):
https://docs.google.com/spreadsheets/d/1xGbAZ6A_WQ4OfWMuCUC8Cm9hc62f0aWlttYxR_ugmpU/edit?usp=sharing

Если каких-то емейлов нет -- приглашение не получит. ;)

Текст приглашения:
https://docs.google.com/document/d/1ChlrJEGqr4ynr24TNq5NqwBCUCLGlTPQoX6l12vQCOU/edit?usp=sharing

- [x] Попович Володимир Іванович  vlip67@live.ru
- [x] Сажин Володимир Георгійович  sazhvg@gmail.com
- [x] Чорноус Сергій Олександрович  s.chornous@gmail.com
- [x] Сердюк Микола Миколайович  serdnik1965@gmail.com
- [x] Левин Александр  alexander.levin75@gmail.com
- [x] Возняк Андрей Петрович  andrey.voznyak@aska.ua
- [x] Мошкола Артур Ярославович  artur.moshkola@gmail.com
- [x] Миняйло Лариса Анатольевна  l.minyaylo@bmc.dp.ua
- [x] Нестеренко Антон  toxanes@gmail.com
- [x] Черновцы 1 Ходаковская Н.И.  nadija.khodakovska@gmail.com
- [x] Черновцы 3 Савко Саша  oleksandr.savko@gmail.com
- [x] Хубеджев Павел  Pavlo.Khubedzhev@infopulse.com
- [x] Юмашев Владимир   andriy.servetnyk@gmail.com
- [x] Зоя Степанова  zstepanova@fdu.org.ua
- [x] Виряскин Александр  Viryaskin.o.m@ukr.net

**Comment by mik-man** [comment]
Разослал официальное приглашение по списку выше.
Если кому-то еще надо, говорите.

**Comment by alex-kukhtin** [comment]
Сам issue открыл, сам сделал, сам и закрывай :-)

**Comment by MaksymTikhomirov** [comment]
Рано, итогового списка ещё нет
