### ISSUE TITLE
При записи в базу пользовательских полей триммить первые и последние пробелы.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#668]
При записи в базу пользовательских полей триммить первые и последние пробелы.
Иначе иногда печатные формы ломаются.

**Comment by alex-kukhtin** [comment]
Я тут намедни хорошо подумал.
И решил, что это мы делать не будем.
Если ломаются печатные формы - править будем в формах.
А то изменение слишком глобальное. Стремно как-то.
