### ISSUE TITLE
Создать окно сквозного быстрого поиска всего.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#670]

**Comment by alex-kukhtin** [comment]
Мудрый ты конечно :-)

**Comment by alex-kukhtin** [comment]
Гугл свой что-ли написать?
Закрывай нафиг это.
Нужно что-то поконкретнее придумать.

**Comment by mik-man** [comment]
Типа такого.

![qb global search](https://user-images.githubusercontent.com/35918141/48828941-ba773380-ed79-11e8-9e03-9a27471a3aa2.png)

Ок, подождем. ))
