### ISSUE TITLE
Создать возможность убирать (сдвигать в сторону) раздел Що нового

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#673]

**Comment by alex-kukhtin** [comment]
И что это даст? По крайней мере сейчас? Еще кусок пустого места, чтобы думать ,что туда засунуть?

**Comment by mik-man** [comment]
На маленьких экранах уже существующие элементы в ширину не помещаются. А у них ширина фиксированная. Так что имеет смысл.
