### ISSUE TITLE
[BUG][Регистрация] На Dev пустое окно при подтверждении регистрации

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#675]
Поломали регистрацию на Деве.
После перехода по подтверждающему мейлу загружается полностью пустая страница

Загружается нормально только по обычной ссылке из второго письма
Ссылка из первого письма : 
http://dev.a2start.com/Account/confirmemail?userId=605&code=m0qWQNdR33k3+5aNW5WVL84nKDVVRLMeC+9zpIRaCjgi07um1SzKBpOFmgwAkoiFYvm4dKTeriX7r2Ez8t+iWOFjbBdrvKjDztOB4NOabjM2VfwxxetFMxS9FK6yUTYp1sXP6A==

**Comment by alex-kukhtin** [comment]
Вроде починили...
