### ISSUE TITLE
Сделать запрет рассчета амортизации, на которые уже она была начислена

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#677]
![image](https://user-images.githubusercontent.com/38099938/48697586-a1da1280-ebed-11e8-8691-4dd66cd7e296.png)

![image](https://user-images.githubusercontent.com/38099938/48697659-c59d5880-ebed-11e8-9999-5aa69f656359.png)

**Comment by htrofymova** [comment]
готово
