### ISSUE TITLE
Операція "Виставлення рахуноку". Додати поле "сплатити до <дата>"

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#68]
Наверное, желательно, чтобы дата "сплатити до" при редактировании даты подставлялась автоматически. Например плюс месяц к дате. А потом позволяла править вручную.

**Comment by AlexeyTishkin** [comment]
Добавил.

**Comment by nik-man** [comment]
![invoice_date_to](https://user-images.githubusercontent.com/35918141/38884026-2d2f8516-4277-11e8-8627-5dd8a9603c0f.png)
Может вверху лучше рядом с датой документа?
И чуток выровнять другие в документе.
Ага, я зануда. ))

**Comment by AlexeyTishkin** [comment]
С левой вертикальной чертой не согласен. Ты взял самое короткое наименование документа. А теперь посмотри, к примеру, Расходную накладную. Поле "Покупатель" будет с очень большим левым отступом. Я специально делал две области: наименование, номер, дата и остальные реквизиты.

**Comment by AlexeyTishkin** [comment]
"Сплатити до" - фактически отсрочка должна зависеть от покупателя (может даже опускаться до договора), поэтому логично вносить ее после выбора зависящих сущностей. В будущем, наверное, надо будет добавить свойство "Отсрочка" покупателю и договору.

**Comment by Illya-Lykhachov** [comment]
Пока нет однозначного критерия для определения значения срока оплаты, его вообще заполнять не нужно. Стандартные 3 рабочих дня не подойдут -  у нас нет календаря. Самое главное - мы не можем за пользователя решать. Пусть пока сам указывает, если нужно.
В печатной форме, если дата оплаты не указана, то и поле с ней отображать не нужно.

**Comment by Illya-Lykhachov** [comment]
Вообще мне не нравится подход с абсолютной датой, гораздо гибче и проще подход с относительным смещением - "счёт действителен в течение {Bind DeltaDays}-х рабочих дней"
Кол-во дней можно хранить в свойствах предприятия (по умолчанию - 3)

**Comment by AlexeyTishkin** [comment]
У абсолютной даты есть преимущество в заделе на платежный календарь.

**Comment by Illya-Lykhachov** [comment]
одно другому не мешает. Когда потребуется, будем из имеющегося относительного смещения предлагать абсолютную дату. Опять же при наличии производственного календаря

**Comment by AlexeyTishkin** [comment]
> Кол-во дней можно хранить в свойствах предприятия (по умолчанию - 3)
Фактически это и есть "отсрочка".

**Comment by Illya-Lykhachov** [comment]
если есть договор - то да

**Comment by AlexeyTishkin** [comment]
По идее, надо вначале смотреть у покупателя, потом в договоре.

**Comment by Illya-Lykhachov** [comment]
Это не отсрочка. Отсрочка - это легальная задержка оплаты **после** фактической отгрузки. В данном случае мы имеем дело со счётом на **предоплату**. Речь идёт о сроке жизни счёта, т.е. о сроке резервирования заказанного в счёте товара. Никак это платёжного календаря не касается. Не нужно смотреть ни на покупателя, ни на договор

**Comment by AlexeyTishkin** [comment]
В данном случае мы имеем дело со счётом на предоплату.

[ТА] Почему ? По хорошему, мы любую цепочку должны начинать со счета. Кроме того, первая фактическая отгрузка может быть меньше выставленного счета.

**Comment by Illya-Lykhachov** [comment]
Цепочка начинается со счёта - правильно. Дата отгрузки меньше даты счёта - неправильно. Счёт - это документ-основание всей цепочки. Как ты "натянешь" основание на отгрузку (назначишь ей родительский документ)?
Какой вообще смысл в дате оплаты в счёте, если счёт на предоплату? Что имеется в виду: оплата счёта или оплата накладной (не известно есть ли она)?
Короче,:
- убираем дату оплаты из счёта
- оставляем только относительный период оплаты (из свойств нашего предприятия) для всех счетов
- платёжный календарь будем формировать из неоплаченных отгрузок и условий договора
- просрочку оплат контролируем по отчёту "Дебеторская задолженность" (по накладным, а не по счетам)

PS. Отсрочка считается не с даты счёта, а с даты накладной, поэтому к счёту она не относится никак.

**Comment by nik-man** [comment]
Вы поговорили? :)))))
Можно issue закрывать?

**Comment by AlexeyTishkin** [comment]
Вы поговорили? :)))))

[ТА] Еще потом по телефону 30 минут… :)

Можно issue закрывать?

[ТА] Я сейчас выложу последнюю версию, опишу принцип работы и можно закрывать.

**Comment by AlexeyTishkin** [comment]
После длительных консультаций решили:

1. Дата оплаты в счете остается.
2. При создании счета - пустая.
3. Если дата оплаты не указана, то в печатной форме "Рахунок дійсний до сплати протягом 3-х банківських днів.". 3 - фиксированное число, потом будет из каких-то свойств.
4. Если дата оплаты указана, то в печатной форме "Рахунок дійсний до сплати до <дата>."

Посмотрите, если все ок - закрываем issue.

**Comment by nik-man** [comment]
Во входящих будем делать?
Как правильно заметил Илья -- в дальнейшем это будет напоминалка о необходимости платежа.

**Comment by AlexeyTishkin** [comment]
Илья написал: "платёжный календарь будем формировать из неоплаченных отгрузок и условий договора". Дата в исходящих сейчас только для печатной формы. Во входящих, соответственно не нужна.

**Comment by nik-man** [comment]
Ну пусть не нужна (пока). Но эта информация, она же есть во входящем счете. На нее могут ориентироваться, смотреть.

**Comment by Illya-Lykhachov** [comment]
счёт в систему вводится только в случае, если по нему собираются платить. Т.е. напоминать о чём-то уже поздно. Никаких обязательств эта дата не предполагает. Вопрос: нафиг она нужна?

**Comment by nik-man** [comment]
Ок. Ладно, входящий счет -- другое issue.
В этом только вставь пожалуйста проверку, чтобы нелья было меньше даты счета.

**Comment by AlexeyTishkin** [comment]
Проверку сделал.
