### ISSUE TITLE
Описать ошибку более понятно для клиента. ПН уже существует в Сонате

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#680]
![image](https://user-images.githubusercontent.com/42540074/48766349-ebddf980-ecbc-11e8-8266-2247352ba30a.png)

**Comment by alex-kukhtin** [comment]
fixed in 7384

**Comment by alex-kukhtin** [comment]
Done in 7384

**Comment by Anestezia** [comment]
Теперь сколько раз ни нажимай, сообщение об ошибке не выдается, Звіт успішно передано, и передает столько копий отчета в Сонату, сколько раз ты нажал на кнопку.
