### ISSUE TITLE
Сделать подсказку более информативной Начальный баланс по валютным счетам.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#683]
![image](https://user-images.githubusercontent.com/42540074/48833500-25c60300-ed84-11e8-87ac-31d34cb9845f.png)
Предлагается для непонятливых и придирчивых написать в подсказке при наведении на клетку: Введіть суму в гривні (або Введіть еквівалент у гривні) Также сделать и по всем валютным операциям

**Comment by mik-man** [comment]
Сделал подсказку "Введіть суму в гривнях".
Хотя, возможно, правильнее добавить поле "Курс" (как во всех валютных операциях).
