### ISSUE TITLE
Ссылка "Перейти к счетам" с главной - косячит

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#684]
После регистрации при переходе по ссылке видим:
![image](https://user-images.githubusercontent.com/38098758/48838544-60826800-ed91-11e8-8cb0-88bc88f7ac0d.png)

Если добавить счет и перейти по ссылке:
![image](https://user-images.githubusercontent.com/38098758/48838615-91fb3380-ed91-11e8-8f37-79f41771c89b.png)

В обоих случаях левое меню пустое.

При попытке обновить страницу:
![image](https://user-images.githubusercontent.com/38098758/48838665-afc89880-ed91-11e8-9c1b-1fb9d320c24b.png)

**Comment by alex-kukhtin** [comment]
fixed in 7365
