### ISSUE TITLE
Платежное поручение - "Отправить в банк"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#686]
В Оплате по банку желтая кнопка Отправить в банк (при настроенном API) выдает ошибку "Object reference not set to an instance of an object."
![image](https://user-images.githubusercontent.com/38098758/48900006-d6ea9d00-ee59-11e8-8b23-08b90f4e10e1.png)

При ненастроенном API кнопка тоже видна и дает ту же ошибку.

Как по мне, при ненастроенном API кнопки "Отправить в банк" вообще не должно быть видно

**Comment by alex-kukhtin** [comment]
fixed in 7376

**Comment by AndriyNesterenya** [comment]
Работает.
Для не-Привата кнопка скрыта.
Для Привата без API кнопка скрыта.
Для Привата с API кнопка видна.

**Comment by alex-kukhtin** [comment]
Ну если все работает - закрывай этот issue.
