### ISSUE TITLE
Необоротні активи - не работает "Створити придбання" из счета.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#687]
В "необоротних активах" создаем счет - все ОК
На основе счета создаем оплату - создается
На основе счета создаем Придбання (приходную накладную) - спрашивает 
![image](https://user-images.githubusercontent.com/38098758/48901324-bcb2be00-ee5d-11e8-98f5-c48ee8f98392.png)
и ничего не происходит

**Comment by AlexeyTishkin** [comment]
Сделал.
