### ISSUE TITLE
Переключение между списками (су, оу, договоры) с линейкой прокрутки.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#69]
При переключениями между видами списков -- ползунок линейки сбрасывается вверх.
Есть возможность сохранять положение ползунка?

Например:
Создать в списке (контрагенты, объекты или договора) элементов достаточно много, чтобы появилась линейка прокрутки.
Выбрать нижний элемент. (Ползунок будет внизу)
 Клацнуть, чтобы переключиться в расширенный список.
(Ползунок оказывается вверху)
И слева не видно выбранный элемент.

**Comment by alex-kukhtin** [comment]
Fixed in 7166

**Comment by nik-man** [comment]
Проверил. Закрыл.
