### ISSUE TITLE
Розділ "Бухгалтерія". "Рахунки в банках" -- додати кнопку "Створити" і стрілку-підказку.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#690]
Раздел "Рахунки в банках" для нового пользователя выглядит как-то пусто и безжизненно.
Добавить кнопку "+ Створити" та стрілку-підказку.

![2018-11-23](https://user-images.githubusercontent.com/35918141/48938225-3fe51a00-ef19-11e8-98a1-a408b211fcc1.png)

**Comment by alex-kukhtin** [comment]
Ну конечно, кому же еще делать? Больше же некому.

**Comment by alex-kukhtin** [comment]
done in 7381
