### ISSUE TITLE
Формат ввода даты в документах - любой символ между цифрами при вводе с клавиатуры распознавать как точку.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#692]
Іноді люди, щоб зекономити час користуються боковою цифровою клавіатурою для швидкого набору символів, а там є клавіша "кома". І коли вводити значення дати через цю кому, то воно не зберігається. Ще можливо, якщо англійська розкладка, то на місці крапки - слеш.

**Comment by mik-man** [comment]
+1
Разделители в формате даты бывают разные. И, вообще говоря, нет "правильного разделителя".
Мне кажется, лучше всего, если любой символ будет восприниматься как разделитель.
Это закроет все вопросы и будет маленьким, но ощутимым удобством.

**Comment by alex-kukhtin** [comment]
Done in 7405
