### ISSUE TITLE
В админке не корректно отображается общая сумма оплаты клиента

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#693]
В разделе "Оплаты" у клиента есть два платежа
![image](https://user-images.githubusercontent.com/42002015/49068321-11c04c80-f22f-11e8-878f-934136d3a005.png)
А в разделе "Користувачі" по этому клиенту стоит сумма оплаты только за один месяц.
![image](https://user-images.githubusercontent.com/42002015/49068496-8dba9480-f22f-11e8-9ae9-87cea0821f87.png)

**Comment by alex-kukhtin** [comment]
А с чего ты взял, что это сумма оплаты? Это баланс.
Щелкни по клиенту - там все написано.

**Comment by DenisClone** [comment]
Супер! Такой возможности не знал.
