### ISSUE TITLE
Нужна возможность формировать Оборотку по конкретному счету.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#694]

**Comment by mik-man** [comment]
+1
Насколько я понял, подразумевается возможность развертки каждой строки в ОСВ. Чтобы можно было понять, откуда суммы-обороты на конкретном счете взялись.

**Comment by AndriyNesterenya** [comment]
Добавка из хотелок юзеров :
"Очень хочется понимать, откуда берутся те или иные цифры в общей оборотно-сальдовой ведомости. Предлагаю суммы по оборотам сделать активными, т.е. при нажатии на сумму любого оборота по Дт или Кт будет раскрываться история этой цифры, т.е. список документов и сумма из документа за выбранный период  (и хорошо было бы пройти внутрь каждого такого документа). Пока я работаю с 2-5 операциями, и я помню все цифры по операциям, но как только их станет больше, с ними будет очень трудно справляться."

**Comment by alex-kukhtin** [comment]
Done in 7476
