### ISSUE TITLE
Нужна операция Списание производственных расходов

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#695]

**Comment by Illya-Lykhachov** [comment]
Уточнить какой счет какими проводками закрывается

**Comment by kattrina-brekhova** [comment]
наверное речь идет о производстве, когда можно на 23 отправить и акты по электроэнергии, и амортизацию, и зарплату.
это то можно и сейчас, но штука в том, что в документе производство нельзя подтянуть эти суммы. таким образом, даже если в производстве используются эти затраты, они не увеличивают себестоимость изготовленной единицы продукции, а просто подвисают на 23 счете
