### ISSUE TITLE
Нужно отображение срока, до которого проплачен сервис в хорошо видимом для клиента месте

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#698]
Возможно даже при входе за три дня до окончания действия проплаченого периода Сообщение типа приветствия. Клиенты не помнят, когда нужно платить.

**Comment by Anestezia** [comment]
И не только на главной, так как клиенты месяцами не заходят на главную.

**Comment by Anestezia** [comment]
Вот это бы ускорить

**Comment by MaksymTikhomirov** [comment]
UP
Подгорает - многие клиенты пропускают сроки, потом истерики, слезы, кровь мозги кишки по стенам

**Comment by alex-kukhtin** [comment]
Done in 7466
