### ISSUE TITLE
Длинное примечание выдает ошибку.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#7]
В свойствах любого элемента очень длинное примечание выдает ошибку:
http://joxi.ru/82Q7oGxfj0oL0r.png
или
http://joxi.ru/Y2LqgNRI945q0A.png

**Comment by alex-kukhtin** [comment]
Fixed in 7150. Test it.

**Comment by nik-man** [comment]
Да, теперь все ок. Не дает внести более 255 символов.
