### ISSUE TITLE
Корректировка даты вступительного баланса. Неправильное отображение.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#700]
Начальный баланс, Дата документа 31.12.17, а в акте сверки он от 30.12.17. В списке операций - от 30.12.17. В акте сверки при отборе на дату 30.12.17 этот документ есть, а при отборе на 31.12.17. этого документа нет.
![image](https://user-images.githubusercontent.com/42540074/49157651-f9ccf380-f328-11e8-98cb-d76589c9a234.png)
![image](https://user-images.githubusercontent.com/42540074/49157662-02252e80-f329-11e8-9c2c-06550618276b.png)
![image](https://user-images.githubusercontent.com/42540074/49157665-07827900-f329-11e8-8d3c-f88c81d773ac.png)
![image](https://user-images.githubusercontent.com/42540074/49157678-0ea98700-f329-11e8-8172-1a0640ee1574.png)
И второе, остатки внесены на дату 30(31).12.17 и в акте за весь период они отображаются, а в акте за 2018 год их нет

В карточке вступительного баланса не будет даты вообще. Вступительный баланс в любой отчет будет всегда попадать в виде остатков. Вадим (с)

**Comment by shevchuk-vadim** [comment]
Проблема решена в связи с удалением даты.
