### ISSUE TITLE
[Платежное поручение] - подставлять единственный счет контрагента, даже если он не указан основным

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#701]
Наехал на ситуацию:
Когда контрагент создается автоматически при импорте выписки, его счет помечается Активным и не помечается Основным.
Также народ часто не утруждается установкой галки Основной в счетах контрагентов
В платежных поручениях сейчас автоматически подставляется основной счет - в описанных выше случаях поле счета не заполняется и народ дергается.

Имеет смысл в Платежки подтягивать автоматом не только Основной, а еще и единственный, независимо от состояния галки "основной".

**Comment by alex-kukhtin** [comment]
Сделано в новых платежках.
