### ISSUE TITLE
Добавить в документ Инвентаризация и др. документы вкладки Запасы и Необ. активы выбор МОЛ рядом со складом

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#702]
Добавить Материально-ответственных лиц как необязательный для заполнения пункт в документах Приходования, перемещения, инвентаризации, списания, выбытия.

**Comment by AlexeyTishkin** [comment]
С Инвентаризацией согласен.
Какой смысл в остальные добавлять ?

**Comment by Anestezia** [comment]
Какой смысл в остальные добавлять ?

Чтоб учет велся по МОЛ, кроме складов. Приход на МОЛ, с остальными тоже.
