### ISSUE TITLE
Перетащить кнопку импорта банка внутрь мастера создания.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#705]
По аналогии с субъектами.

![2018-12-04](https://user-images.githubusercontent.com/35918141/49428645-47c17b80-f7af-11e8-991c-ead5102fe694.png)

Сначала для банков, затем для всех остальных классификаторов (валют, стран и пр.)

**Comment by alex-kukhtin** [comment]
А нафига теперь там ссылка "Імпотртувати" осталась?
Чтобы еще больше запутать?

**Comment by mik-man** [comment]
Там удобный поиск банков, не только по МФО, но и по названию, по городу.
Может лучше оставить?

**Comment by mik-man** [comment]
> А нафига теперь там ссылка "Імпотртувати" осталась?
> Чтобы еще больше запутать?

Спрятал кнопку "Імпортувати" в меню кнопки "+ Новий". Теперь ок?
