### ISSUE TITLE
По всем документам где еще нет, добавить возможность "Добавить списком" объекты учета

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#707]
![image](https://user-images.githubusercontent.com/42540074/49431974-4f851e00-f7b7-11e8-8747-fa6ac737a07b.png)
 Неудобно каждый раз по одной строке вносить, делать отбор.

**Comment by AlexeyTishkin** [comment]
Добавил в "Придбання", "Продажі", "Запаси".
