### ISSUE TITLE
Док. Придбання матеріальних активів, созданный из разных разделов при поиске тоже отображается порознь.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#710]
Я в разделе Придбання создала 7 документов Придбання матеріальних активів, в разделе Необоротные активы создала еще один - восьмой. Находясь в разделе Необоротные активы я выполняю поиск по операции и отображается только один, созданный здесь документ, остальные можно увидеть только при отборе в разделе Придбання. Неудобно. Операция одна и та же. должна быть видна из любого раздела, либо, если она дублируется в двух разделах - убрать из одного, чтоб только в одном была.

**Comment by AlexeyTishkin** [comment]
Разве удобно будет видеть в "Необоротных активах" приобретение товаров ?

**Comment by Anestezia** [comment]
Я поняла в чем причина: На вкладке Придбання и Запасы есть операция Придбання матеріальних активів, если внести объект учета не Основний засіб, Інші необоротні матеріальні активи или Нематеріальні активи, то эти операции отображаются и на вкладке Необоротные активы. Если этой операцией оформить покупку товаров других видов, то они не отображаются в Необоротных активах. Все верно.
