### ISSUE TITLE
Не корректное зачисление средств через iBox

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#711]
Коля сегодня оплатил сервис через терминал iBox
Сумма зачисленная в сервисе - 0 грн.
![image](https://user-images.githubusercontent.com/42002015/49511396-b7a93200-f893-11e8-87ef-4bfa06adeaa1.png)

По чеку 300 грн.
![image](https://user-images.githubusercontent.com/42002015/49511406-c09a0380-f893-11e8-8648-c70d8d51a977.png)

**Comment by DenisClone** [comment]
Проверили в учетке Коли - оплата отображается с корректной суммой, но без описания.

**Comment by mik-man** [comment]
![2018-12-05](https://user-images.githubusercontent.com/35918141/49513394-7f0c5700-f899-11e8-8d58-b38ef53f27b4.png)

Время кстати, неточное. Это было в 9:24 (в системе 7:24)

**Comment by DenisClone** [comment]
Это ишью закрываю, дублируется с ишью https://github.com/a2develop/bugTracker/issues/932
