### ISSUE TITLE
Оборотно-сальдова відомість по рахунку в банку - проблема при выборе счетов 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#713]
И еще проблема странная : 

Идем в "Бухгалтерия - Рахунки в банках"
Выбираем счет на котором есть деньги, идем в "Оборотно-сальдова відомість по рахунку в банку" - все показывает.
Выбираем в самой ведомости счет, на котором нет денег - не показывает.
Возвращаемся на счет, где есть деньги - снова показывает.

А потом снова идем в "Бухгалтерия - Рахунки в банках"
Выбираем счет на котором НЕТ денег - не показывает
Меняем там же на счет, на котором есть деньги - все равно НЕ показывает.

**Comment by alex-kukhtin** [comment]
Починено в 7384
