### ISSUE TITLE
Вход в Демо аккаунт

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#719]
Предлагаю создать на сервисе отдельный УРЛ, что-то типо: service.com/test-acc
при переходе на который, система сразу запустит в учетку Демо пользователя (сейчас это demo@demo.com), соответственно без ввода логина и пароля.
Мы разместим ссылку на этот УРЛ на продающем сайте.  Это облегчит потенциальному клиенту доступ к демонстрационному аккаунту.

**Comment by MaksymTikhomirov** [comment]
Up
Важно
