### ISSUE TITLE
Банковская выписка, заменить сообщение при первом проведении документа

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#721]
![photo_2018-12-10_17-21-01](https://user-images.githubusercontent.com/42540074/49743740-17447a80-fca4-11e8-8274-5ce8ae13e670.jpg)
Либо автоматически сохранять созданный документ и не спрашивать (это при ручном вводе выписки), либо дать более понятную инструкцию пользователю.  Кнопки сохранить нет рядом с этим документом, получается, нужно нажать на "провести" еще раз. Это непонятно.

**Comment by AlexeyTishkin** [comment]
Исправил.
