### ISSUE TITLE
Мелкие косяки в отчете "Звіт про використання коштів, виданих на відрядження або під звіт"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#727]
![image](https://user-images.githubusercontent.com/38098758/49943439-8e6e4e80-fef0-11e8-8abb-ebeabd4432b4.png)

![image](https://user-images.githubusercontent.com/38098758/49943530-c7a6be80-fef0-11e8-8946-9650cfd3a72e.png)

**Comment by htrofymova** [comment]
готово
