### ISSUE TITLE
на основании счета на приобретение нематериальных активов формируется приходная материальные активы (при этом проводки правильные)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#728]
создала счет на покупку нематериальных активов
![image](https://user-images.githubusercontent.com/38099938/49945508-b9a76c80-fef5-11e8-8108-0914a2bb9e1a.png)
но приходный документ, который сервис формирует на основе этого акта - приходная накладная материальный активов
![image](https://user-images.githubusercontent.com/38099938/49945596-ed829200-fef5-11e8-8865-6b001f6933bb.png)
проводки правильные конечно
но может тогда, если в счет внести объект нематер активов, пусть автоматически подтягивает акт прийома-передачи нематериальных активов?

**Comment by AlexeyTishkin** [comment]
Сделал
