### ISSUE TITLE
Недоработка/Предложение: при создании накладной на внутреннее перемещение не отображаются реальные остатки на конкретном складе, показаны только общие на всех местах хранения

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#73]
Было оприходовано 5 единиц на основной склад, 3 из них переместила на другой. При дальнейшем перемещении этих же запасов в табличной части накладной не отображается реальный остаток на конкретном складе, откуда делаю перемещение, а только общее количество
Предложение: создать возможность отображения остатков на выбранном складе
![30726551_1969513593299482_7268320275383451648_n](https://user-images.githubusercontent.com/38099938/38870629-13cb2eb0-4257-11e8-9418-8877eeeaa7d3.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
