### ISSUE TITLE
Печатная форма оборотной ведомости по складу - косячит ширина столбцов

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#732]
![image](https://user-images.githubusercontent.com/38098758/50079922-90d3ef80-01f3-11e9-80d4-5e678853c36d.png)

Об`єкти обліку- звіти- оборотна ведімість-друк
косячит ширина столбцов

**Comment by AlexeyTishkin** [comment]
Это браузер таким образом делает подгонку ширины под лист А4. В этом случае можем посоветовать:
1. В окне печати уменьшить масштаб.
2. Дождаться экспорта таких отчетов в Excel.

**Comment by AndriyNesterenya** [comment]
На нет и суда нет :)
