### ISSUE TITLE
передача товаров комисионеру: исправить название рядка склад комитента

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#740]
нужен склад комиссионера
![image](https://user-images.githubusercontent.com/38099938/50167341-a62f4380-02f1-11e9-8819-192a843b2001.png)

**Comment by AlexeyTishkin** [comment]
В этой операции происходит передача товаров с Основного склада (281) на склад Комитента (283). Склада Комиссионера здесь еще нет.

**Comment by kattrina-brekhova** [comment]
єто не ошибка, а задумка творца?)

**Comment by AlexeyTishkin** [comment]
Фактически мы передает товар Комисионеру, а с точки зрения учета перекладываем на свой же (Комитента) склад.

**Comment by kattrina-brekhova** [comment]
я не знаю, как будет правильно, если считаете так, не лезу

**Comment by AlexeyTishkin** [comment]
Может надо операцию как-то переименовать ? Изначально было описано здесь: https://docs.google.com/document/d/1uC7NuE5Cn9zej8W302NCIK-t5wjof3yQAscB63MnlHU/edit

**Comment by kattrina-brekhova** [comment]
нет, все понятно

**Comment by kattrina-brekhova** [comment]
единственное, в чате уточняла у Вадима, как правильно, он написал, что склад комиссионера
![image](https://user-images.githubusercontent.com/38099938/50169719-cdd4da80-02f6-11e9-8cb1-2842113f92b5.png)

ишью не закрываю

**Comment by kattrina-brekhova** [comment]
вот еще Вадим добавил : Тот склад, с которого передается товар - это поле "Склад". Склад, на который передается товар. это поле "Склад комітента". А должен быть "Склад комісіонера", поскольку товар передается от комитента комиссионеру.

**Comment by AlexeyTishkin** [comment]
Счет 283 - это же наш счет. По учету мы перемещаем между нашими складами. Как этот склад может быть складом Комисионера ?

**Comment by AlexeyTishkin** [comment]
А получает комисионер к себе на склад на забалансовый 024.

**Comment by shevchuk-vadim** [comment]
Передача товаров на комиссию - это не операция внутреннего перемещения. Комитент передал товар со своего склада, и у него на складах товаров в наличии нет. Товары фактически находятся у комиссионера, и комитента совершенно не волнует, на каком складе комиссионер их у себя хранит, лишь бы побыстрее продал.

Когда комитент строит у себя отчет по товарам на комиссии, то он должен их видеть в разрезе комиссионеров, а не складов. Если он видит какие-то склады, то он может не понять, кто же ему должен денег за этот товар.

Вывод: склад получения при операции передачи на комиссию - лишний элемент, затрудняющий работу по комиссионной торговле.

Предложение:
1. Удалить из документом по комиссионной торговле склад комитента или комиссионера. В качестве места хранения использовать не склад, а контрагента.
2. Удалить в свойствах склада тип склада.
3. Сделать отчет "Ведомость по товарам на комиссии", который будет показывать остатки товаров в разрезе комиссионеров.

**Comment by AlexeyTishkin** [comment]
> В качестве места хранения использовать не склад, а контрагента.

В ОСВ по 283 должен фигурировать контрагент ?

**Comment by AlexeyTishkin** [comment]
> Удалить в свойствах склада тип склада.

У нас не может быть на складах одного товара купленного (281) и принятого на комиссию (024) ?

**Comment by shevchuk-vadim** [comment]
У комиссионера и собственые (281), и взятые на реализацию (024) товары хранятся на его собственном складе. В отчетах по этим счетам нет никакой разницы.
У комитента товары, переданные на реализацию (283), на складах отсутствуют, а на каких складах они находятся у комиссионера, не имеет значения. Потому в отчете по счету 283 желательно, чтобы товары числились не на складах, а на комиссионерах.

**Comment by AlexeyTishkin** [comment]
> В отчетах по этим счетам нет никакой разницы.

Отчет строится не по счету а по складу. Для этого и нужен тип.

**Comment by AlexeyTishkin** [comment]
> Потому в отчете по счету 283 желательно, чтобы товары числились не на складах, а на комиссионерах.

Т.е. в ОСВ по 283 должен фигурировать контрагент ?

**Comment by shevchuk-vadim** [comment]
Да.

**Comment by Illya-Lykhachov** [comment]
Сделать отчет "Ведомость по товарам на комиссии", который будет показывать остатки товаров в разрезе комиссионеров.
