### ISSUE TITLE
Отримання товарів від комітента: при выборе контрагента, который также является продавцом, автоматом подтягивает ранее созданный не комиссионный договор (значение было проставлено "Основной")

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#741]
![image](https://user-images.githubusercontent.com/38099938/50168820-fcea4c80-02f4-11e9-9ce5-3bee6e3ea853.png)
![image](https://user-images.githubusercontent.com/38099938/50168850-05428780-02f5-11e9-9777-4bd7e1d5e93c.png)

**Comment by AlexeyTishkin** [comment]
Вопрос: какая область действия свойства "Основной" ? Если для контрагента может быть только один основной договор - тогда все верно. Если основной должен быть внутри вида, т.е. у контрагента может быть больше одного основного договора (сейчас их может быть два) - тогда нужно дорабатывать функционал.

**Comment by kattrina-brekhova** [comment]
система дает возможность поменять, создать новый договор комиссии не выходя из документа - т.е. для меня, как для пользователя — ситуация не критична

**Comment by AlexeyTishkin** [comment]
Да. Вопрос только в том, какой договор подставить автоматом при выборе контрагента.

**Comment by kattrina-brekhova** [comment]
ага, договор подтягивается к контрагенту, но не учитывает суть операций?
т.е. к комиссионным операциям - только комиссионный договор, ко всем остальным - основной

**Comment by AlexeyTishkin** [comment]
> ага, договор подтягивается к контрагенту, но не учитывает суть операций?

Да. Загружается "Основной". А основной сейчас только один.

**Comment by AlexeyTishkin** [comment]
> т.е. к комиссионным операциям - только комиссионный договор, ко всем остальным - основной

Это то, что я писал в первом коментарии: в таком случае основной должен быть внутри вида (основной для общих, основной для комиссионных и т.д.)

**Comment by shevchuk-vadim** [comment]
Поскольку виды договоров у нас четко разделены по операциям, и не смешиваются, то логично основной договор сделать по каждому виду отдельно.
То, что основной договор, если он общий, не должен попадать в операции комиссионной торговли, не вызывает сомнений.

**Comment by AlexeyTishkin** [comment]
> Поскольку виды договоров у нас четко разделены по операциям, и не смешиваются, то логично основной договор сделать по каждому виду отдельно.

Согласен. Для складов так и сделано (основной внутри вида).

**Comment by AlexeyTishkin** [comment]
Признак "Основний" теперь устанавливается внутри вида договора, т.е. теперь у контрагента может два основных договора: один "загальний", второй "комісії".
Операция "Отримання товарів від комітента". При выборе контрагента, у которого два договора ("загальний", "комісії") в операцию будет подставлен основной комиссионный договор.
