### ISSUE TITLE
Уменьшить высоту окна приветствия (или приделать явный скролл) - не влазит в экран 1366*768

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#742]
![image](https://user-images.githubusercontent.com/38098758/50182139-2e740f80-0317-11e9-98d5-5d54d4c542bc.png)

Не помещается наше окно приветствия в экраны типа 1366х768, коих немало среди бухгалтерских ноутбуков.
В результате не видно кнопки закрывания и галки "Больше не показывать".
Думаю, стоит слегка подсократить текст за счет литературных изысков и отступов, или формировать окно с ограничением max-height процентов в 90 и приделать внутренний скролл в идеале с постоянно видимой закрывалкой.

**Comment by MaksymTikhomirov** [comment]
+++

**Comment by AndriyNesterenya** [comment]
![image](https://user-images.githubusercontent.com/38098758/50272416-69be2d80-0440-11e9-841d-d2a4f338ac27.png)

Окно уменьшилось, но опустилось ниже, и нижний край все равно не виден.
Если мышкой потянуть его вверх - в экран помещается

![image](https://user-images.githubusercontent.com/38098758/50272495-a68a2480-0440-11e9-88ed-9d70414de5d6.png)

**Comment by mik-man** [comment]
Все диалоги появляются на одном уровне.
Можно сделать окно более широким. Или что-нибудь выкинуть.
