### ISSUE TITLE
Карточный счет в зарплатном проекте не должен быть обязательным

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/bugTracker#743]
У Приватбанка в зарплатных проектах нет никаких карточных счетов. Требуется только ИНН. Счет на всех физлиц один, и принадлежит самому Приватбанку.

Предложение:
1. Добавить в договор по зарплатному проекту расчетный счет банка, куда перечислять зарплату. Он нужен в любом случае, для того, чтобы подставляться в платежное поручение, если оно создается из платежной ведомости.
2. Сделать признак необходимости картчных счетов. Если необходимости нет, то столбец с карточным счетом не показывать.

**Comment by Illya-Lykhachov** [comment]
В шапку договора "зарплатный проект" нужно добавить combobox "Способ идентификации" с двумя значениями: Карточный счёт и(ли) ИНН. В зависимости от выбора, в таблице со списком отображать колонку со счётом или ИНН сотрудника.

**Comment by alexeijur** [comment]
Добавлен выбор способа идентификации сотрудника в зарплатном проекте. В выплате по банку на печать идёт соответствующая форма (без карточных счетов).
