### ISSUE TITLE
Когда кнопка "Нова операція +" сьезжает вниз, выпадающее меню не видно.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#745]
Или сделать, чтобы кнопка не съезжала или что-то с выпадающим меню решить.

![2018-12-20](https://user-images.githubusercontent.com/35918141/50275710-abeb6d00-0448-11e9-97d6-e890c118cc8c.png)

**Comment by alex-kukhtin** [comment]
fixed in 7403
