### ISSUE TITLE
Нужен документ по оплате ЗП по банку (зарплатному проекту), который формирует проводки и осуществляет платежи с нашего счета на счета сотрудников

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#748]
Я так понимаю, в каждом банке к платежке идет ведомость сотрудников как приложение, кому сколько и куда заплатить. Нужны образцы от каждого банка, чтоб можно было осуществлять платежи в реале.

**Comment by shevchuk-vadim** [comment]
В ведомости на пополнение карточных счетов добавлена возможность создания связанного платежного поручения, которое формирует проводки в разрезе физлиц.
