### ISSUE TITLE
Чужие документы при импорте из клиент-банка -- непонятное сообщение.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#749]
Если по причине несовпадения ИНН/ЕДПОУ -- выписка считается "чужой" -- сообщение об этом является неинформативным.
![2018-12-20](https://user-images.githubusercontent.com/35918141/50279921-ce36b800-0453-11e9-999d-dd559a2f1826.png)

По сути, попытка импорта завершается неудачей. И нужно объяснить пользователю по какой причине.
Что-то вроде: "ЕДРПОУ вашої фірми не співпадають з ЕДРПОУ фірми із файлу імпорту. Будь ласка перевірте властивості вашої фірми (и ссылка на диалог свойств)."
Аналогічно для ИНН.

**Comment by AlexeyTishkin** [comment]
MsgBox заменен на колонку "Стан" в таблице транзакций.
