### ISSUE TITLE
Пожелание: возможность разместить логотип компании на форме счета.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#75]
Просят реализовать возможность размещения логотипа компании на форме счета.

Например:
Сама картинка оговоренного размера (или через наш обработчик с обрезанием/ресайзом до нужных параметров) загружается в свойствах своего предприятия.
При наличии картинки - лого выводится в шапке счета.
При отсутствии - форма остается той же, что имеем сейчас.

**Comment by alex-kukhtin** [comment]
done in 7174
