### ISSUE TITLE
Рахунок і Накладна: Платник, Покупець, Одержувач

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#750]
"Рахунок на сплату."
- [x] Вместо "Покупець" должно стоять "Платник"
- [x] Подпись "Рахунок дійсний протягом 3-х днів" должна иметь возможность изменяться на другой срок.
![2018-12-20 -](https://user-images.githubusercontent.com/35918141/50281028-dcd29e80-0456-11e9-81bc-0a161b61826f.png)

"Видаткова накладна"
- [x] Вместо "Покупець" должно стоять "Одержувач"
![2018-12-20 -](https://user-images.githubusercontent.com/35918141/50281039-e22fe900-0456-11e9-9cb0-55eff2724cf2.png)

**Comment by AlexeyTishkin** [comment]
> Подпись "Рахунок дійсний протягом 3-х днів" должна иметь

Кому должна ? :)

**Comment by AlexeyTishkin** [comment]
Рахунок дійсний протягом 3-х днів - значение по умолчанию. Для остальных случаев - дата в "Сплатити до".

**Comment by nik-man** [comment]
О, хорошо, спасибо! Предлагаю также изменить рабочую форму.
И еще, может где-то под полем "Сплатити до" сделать динамическую подсказку серенькую?

![2018-12-21](https://user-images.githubusercontent.com/35918141/50333511-495ca480-050e-11e9-880b-801a3b3ed850.png)

**Comment by mik-man** [comment]
О, хорошо, спасибо!
Теперь также можно изменить рабочую форму.
Может под полем "Сплатити до" добавить серенькую динамическую подсказку?

![2018-12-21](https://user-images.githubusercontent.com/35918141/50333791-1a92fe00-050f-11e9-88ea-a9de87c64e45.png)

**Comment by AlexeyTishkin** [comment]
Не понял. При чем здесь "протягом 30 днів"? Рахунок сплатити до 31.12.2018.

**Comment by mik-man** [comment]
Ну неважно, что именно будет написано в подсказке.
Сейчас рабочей форме поле вверху, в печатной -- строка внизу.
Связь не очевидна.

Хорошо бы их как-то связать логически, чтобы вопросов не возникало.
Ведь стиль нашей системы предполагает такие длинные серенькие подсказки под полями. ))

![2018-12-21](https://user-images.githubusercontent.com/35918141/50334431-f20c0380-0510-11e9-9390-da1d44990402.png)


И тут как раз будет уместна такая подсказка.

**Comment by AlexeyTishkin** [comment]
> Сейчас рабочей форме поле вверху, в печатной -- строка внизу. Связь не очевидна.

Вспоминаем эпопею по поводу размещения этой даты... Решили, что логично рядом с основной датой.

**Comment by AlexeyTishkin** [comment]
> Ну неважно, что именно будет написано в подсказке.

Так и написать ? Давай текст.

**Comment by mik-man** [comment]
> Так и написать ? Давай текст.

Думаю, было бы круто, если бы вычислялось кол-во дней из даты.
"Рахунок від" 21.12.2018,
"Сплатити до" 4.01.2018
и подпись "Рахунок дійсний протягом 14-ти днів"

> Вспоминаем эпопею по поводу размещения этой даты... Решили, что логично рядом с основной датой.

Да это и правильно. Только дата в шапке трансформируется в подпись, которая в подвале. )) А это уже не сразу понятно.

**Comment by AlexeyTishkin** [comment]
> Думаю, было бы круто, если бы вычислялось кол-во дней из даты.

А пользователь хочет, чтобы до сплати до конкретной даты. Обсуждали же уже... Кому не нужна конкретная дата - стандартный текст "3-х днів".

**Comment by mik-man** [comment]
> А пользователь хочет, чтобы до сплати до конкретной даты. Обсуждали же уже... Кому не нужна конкретная дата - стандартный текст "3-х днів".

Ок-ок! ))

**Comment by AlexeyTishkin** [comment]
Так подсказку какую ?

**Comment by mik-man** [comment]
> Так подсказку какую ?

"Рахунок дійсний протягом N днів"

**Comment by AlexeyTishkin** [comment]
Тогда уже текст как в счете: если дата пустая - дійсний протягом 3-х днів, если нет - дійсний до даты.

**Comment by mik-man** [comment]
> Тогда уже текст как в счете: если дата пустая - дійсний протягом 3-х днів, если нет - дійсний до даты.

Ок! ))))))

**Comment by AlexeyTishkin** [comment]
Текст как в печатной форме в качестве подсказки выглядит не красиво. Слишком длинный, переносится на три строки... Сделал "Термін дійсності рахунку".
