### ISSUE TITLE
[Улучшайзинг] в форме выписки добавить плейсходер на выбор ПП

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#752]
Просится плейсхолдер с серенькой подсказкой курсивом (чтобы визуально отличалась от рабочего текста) в поле выбора платежки.
Народ не догадывается туда мышкой ткнуть.

![image](https://user-images.githubusercontent.com/38098758/50284563-0f35c900-0462-11e9-9fae-bcf9de99faa5.png)

**Comment by AlexeyTishkin** [comment]
Сделал. Если делать курсивом, то основной текст тоже будет курсивом.

**Comment by AndriyNesterenya** [comment]
Ура, красиво и понятно.
Вопрос по формулировке и логике работы.

Сейчас подсказка звучит как "Введите платежку".

Там по нашей задумке предлагается ВВЕСТИ от фонаря произвольный текст?
Или ВЫБРАТЬ ранее созданное платежное поручение для привязки?

**Comment by AlexeyTishkin** [comment]
> Сейчас подсказка звучит как "Введите платежку".

Такая формулировка у нас везде в селекторах: Введите контрагента, введите должность, введите объект... Селектор подразумевает два варианта: выбор в диалоге, который открывается при клике на "лупу", либо ввод текста, после которого открывается отфильтрованный список.

**Comment by AndriyNesterenya** [comment]
Забыл же ж сказать.
Подобные же плейсходдеры нужны для Договора и Проекта, потому как никто не догадывается, что они там вообще есть.

**Comment by AlexeyTishkin** [comment]
Добавил.
