### ISSUE TITLE
[Bug] Выписка - проблема при отмене проведения.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#757]
Импортирую выписку, пробежался глазами, нажал "провести" над таблицей - все провелось. Потом замечаю, что один платеж в списке был возвратом матпомощи - нужно исправлять. Жму "отменить проведение" - все расроводится, НО! у всех записей неактивно поле типа платежа.

![image](https://user-images.githubusercontent.com/38098758/50355540-bb0d1080-0557-11e9-9b82-2777722d1871.png)

+ всплывающее окно выбора типа платежа озаглавлено криво - "Выбор платежного поручения"

**Comment by AndriyNesterenya** [comment]
По результатам разбора полетов выяснилось, что если удалить запись о платежном поручении из левого поля - правое становится активным и можно все исправить. 

После проведения исправленной выписки обнаружилось создание двух операций - остается непроведенная операция со старым типом + проведенная копия с исправленным типом.

Договорились удалять автоматически создаваемые операции при отмене проведения.

**Comment by AlexeyTishkin** [comment]
> Договорились удалять автоматически создаваемые операции при отмене проведения.

Сделал.
