### ISSUE TITLE
Добавить книги для ФОПов, доходов, доходов и затрат

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#759]
Часто спрашивают.

**Comment by Illya-Lykhachov** [comment]
Давай внешний вид (если это отчёт).
Ну и уточни возможность вести её в электронном виде

**Comment by AndriyNesterenya** [comment]
Формы обоих книг есть тут:
https://zakon.rada.gov.ua/laws/show/z0800-15#n20
https://zakon.rada.gov.ua/laws/show/z0801-15#n3
 
Насколько я понимаю, возможность ведения этой самой книги в электронном виде декларируется, но на данный момент не до конца регламентирована.

В самом приказе пишут следующее (из того же документа):
> 4. У разі обрання платником податку ведення Книги в електронній формі:
> 
> 1) платник податку зобов’язаний отримати в акредитованому центрі сертифікації ключів, включеному до системи подання податкових документів в електронному вигляді, посилені сертифікати відкритих ключів; укласти договір про визнання електронних документів з контролюючим органом за основним місцем обліку; сформувати та надіслати до такого контролюючого органу заяву про обрання способу ведення Книги в електронній формі засобами електронного зв’язку в електронній формі з дотриманням умови щодо реєстрації електронного підпису підзвітних осіб у порядку, визначеному законодавством, використовуючи такий електронний сервіс;
> 
> 2) контролюючий орган за основним місцем обліку реєструє заяву про обрання способу ведення Книги в електронній формі в реєстрі поданих заяв та протягом 3 робочих днів формує і надсилає платнику податку повідомлення про реєстрацію Книги із зазначенням реєстраційного номера Книги та дати її реєстрації;
> 
> 3) після отримання платником податку повідомлення про реєстрацію Книги така особа здійснює операції з її ведення згідно з цим Порядком. Внесення даних за підсумками робочого дня здійснюється щоденно, але не пізніше наступного календарного дня;
> 
> 4) у Книзі в електронному вигляді допускаються виправлення помилок або коригування шляхом доповнення рядка, в якому відображається від’ємне або позитивне значення.
> 
> 5. Записи у Книзі виконуються за підсумками робочого дня, протягом якого отримано дохід, зокрема про кошти, які надійшли на поточний рахунок платника податку та/або які отримано готівкою, вартість безоплатно отриманих товарів (робіт, послуг).
>
