### ISSUE TITLE
Пожелание: дополнительное поле комментариев для вывода в форме счета

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#76]
Просят реализовать возможность выводить в печатной форме счета произвольный текстовый комментарий.
У нас сейчас  есть отдельное текстовое поле с комментариями, которые не отображаются при печати.
Просят сделать еще одно поле, которое выводилось бы на печать где-нибудь в "шапке" формы жирным шрифтом, и в которое помещались бы сообщения типа "ВНИМАНИЕ! Изменились реквизиты ...." или "Отгрузка товара в праздничные дни производится с 3 по 5 января с 11:00 до 15:00. 
6го и 7го склад закрыт." на пару строк текста.

**Comment by AlexeyTishkin** [comment]
Этот комментарий должен быть один для предприятия или вноситься индивидуально в каждый счет ?

**Comment by AndriyNesterenya** [comment]
Скорее общий для предприятия.
Такого плана уведомления обычно нужны на срок от недели до пары месяцев.

**Comment by nik-man** [comment]
У меня есть клиент, который потестировал нашу систему и тоже попросил дополнительные поля в счете. У него там вообще масса дополнительной информации.
![2018-06-11](https://user-images.githubusercontent.com/35918141/41219266-727d99e0-6d66-11e8-98ae-127b08ffd082.png)

Хотя в итоге его пожелания сравнительно скромные -- добавить вверху и внизу счета по одному текстовому полю произвольной длины.

**Comment by AlexeyTishkin** [comment]
> Хотя в итоге его пожелания сравнительно скромные -- добавить вверху и внизу счета по одному текстовому полю произвольной длины.

Внизу примечание уже печатается.

**Comment by AlexeyTishkin** [comment]
Сделал верхний и нижний колонтитулы.
