### ISSUE TITLE
Добавить возможность редактирования Примечания в проведенных документах!

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#761]
Начиная от счета, так как он самый первый в цепочке созданных. Чтоб не нужно было каждый раз удалять всю цепочку, если, например, в примечание нужно внести какую-то информацию и со временем изменить ее. Реальный случай.

**Comment by mik-man** [comment]
https://github.com/a2develop/bugTracker/issues/216

**Comment by AlexeyTishkin** [comment]
Сделано.
