### ISSUE TITLE
Внутри документа как-то выделять, подцвечивать проведенные дочерние документы

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#762]
У нас иногда в счете создаются дочерние документы, иногда это происходит пачками, да даже если и нет. Есть возможность проведенные документы как-то подсвечивать другим цветом в списке доков внутри родительского документа? Это удобно, чтоб сразу видеть, что уже провели, а что нет.

![image](https://user-images.githubusercontent.com/42540074/50373867-88adf280-05ed-11e9-8906-15206dc46c0c.png)

**Comment by AlexeyTishkin** [comment]
В таблице с дочерними документами колонка код заменена на колонку "Стан".
