### ISSUE TITLE
Ввести в каждый документ поле Основание, чтоб подкреплять в цепочку любой док. из любой точки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#763]
Например, как здесь
![image](https://user-images.githubusercontent.com/42540074/50373920-65d00e00-05ee-11e9-96f2-5b9adbb35c95.png)

Это поможет снять проблему, когда либо двумя частями по одному счету заплатили, либо одна оплата на несколько счетов. Это явление довольно распространенное.

**Comment by mik-man** [comment]
https://github.com/a2develop/bugTracker/issues/54

**Comment by AlexeyTishkin** [comment]
> в каждый документ

С чем будем связывать Счет ? С тремя другими Счетами ? :)

>  любой док. из любой точки

Акт изготовления с Приказом об увольнении ? :)

**Comment by Anestezia** [comment]
![1](https://user-images.githubusercontent.com/42540074/50374251-cb72c900-05f3-11e9-985a-74ac7f3b52e0.png)
![i_274](https://user-images.githubusercontent.com/42540074/50374257-e04f5c80-05f3-11e9-86f6-cc0a42ce5ac0.jpg)
Вот на этой видно два параллельных счета. Есть лучше решение задачи, как зафиксировать одну оплату по двум счетам? В 1С это прекрасно работает и никто не теряется, наоборот упорядоченно, а у нас только ограниченная структура.

![6454cb041849](https://user-images.githubusercontent.com/42540074/50374267-37edc800-05f4-11e9-9199-721ee978637a.jpg)

**Comment by AlexeyTishkin** [comment]
Мой комментарий касался "любой" и "каждый" :)

**Comment by AlexeyTishkin** [comment]
> Есть лучше решение задачи, как зафиксировать одну оплату по двум счетам?

В банковской выписке оплата дробится двумя строками. Каждая строка однозначно привязывается к родительскому счету.

**Comment by Anestezia** [comment]
https://github.com/a2develop/bugTracker/issues/763#issuecomment-449566417 Понятно же, что в пределах разумного.

Нам бы такую цепочку потом выводить на просмотр отдельным окном.

**Comment by AlexeyTishkin** [comment]
> Нам бы такую цепочку потом выводить на просмотр отдельным окном.

Да. Такое надо сделать. С навигацией.

**Comment by AndriyNesterenya** [comment]
... и добавить в нынешнюю таблицу импорта выписки еще и возможность выбора существующего ранее выписанного счета.

Юзера жалуются, что не видят, какой счет оплачен, а какой нет, чем убивается вся прелесть автоматизированного импорта.

**Comment by AlexeyTishkin** [comment]
> и добавить в нынешнюю таблицу импорта выписки еще и возможность выбора существующего ранее выписанного счета.

Это - отдельным issue.
Текущий слишком общий...

**Comment by AlexeyTishkin** [comment]
Предлагается этот issue детализировать, т.е. сделать отдельные issue для каждого вопроса.
Уже есть:
1. Для выписок: [778](https://github.com/a2develop/bugTracker/issues/778)
2. Для платежных документов: [54](https://github.com/a2develop/bugTracker/issues/54)

А этот - закрыть.
