### ISSUE TITLE
На экранах типа 1366х768 косячит всплывалка со списком операций

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#766]
Криво выводится всплывающее окно со списком операций на ноутах с экраном 1366х768

![image](https://user-images.githubusercontent.com/38098758/50482610-263f6280-09f0-11e9-848a-b952af6814ca.png)

Если свернуть левую панель - нормально, но не до всех доходит.

![image](https://user-images.githubusercontent.com/38098758/50482663-78808380-09f0-11e9-8ae0-1ca64de35a5a.png)

**Comment by mik-man** [comment]
https://github.com/a2develop/bugTracker/issues/745

**Comment by alex-kukhtin** [comment]
fixed in 7403
