### ISSUE TITLE
Пожелание: поле "Оплатить до" на форме счета + контроль даты оплаты (?)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#77]
В обсуждении формы счета прозвучало пожелание добавить поле "Оплатить до".
Для полного счастья с прицелом на будущую CRM можно подумать о контроле за поступлением оплаты до указанной даты + о связи с резервированием товара на срок до указанной даты.

**Comment by AlexeyTishkin** [comment]
Это к Илье в  ice box.
