### ISSUE TITLE
Експорт услуг - некорректное сохранение в ворд и пдф

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#770]
![image](https://user-images.githubusercontent.com/42540074/50536180-5571e300-0b5a-11e9-8830-5da1dc87572d.png)
 обрезается информация про адрес и представителя.
![image](https://user-images.githubusercontent.com/42540074/50536189-6f132a80-0b5a-11e9-8a52-668db8f3709b.png)
А вот просто при первом просмотре, кнопка друк-експорт.
![image](https://user-images.githubusercontent.com/42540074/50536196-79352900-0b5a-11e9-91b1-5e17afab05c4.png)

Также некрасиво на печать выводится: к левому краю сдвинуто - неудобно
![image](https://user-images.githubusercontent.com/42540074/50536215-abdf2180-0b5a-11e9-9e1e-dbffd762ee55.png)

**Comment by AlexeyTishkin** [comment]
> Также некрасиво на печать выводится: к левому краю сдвинуто - неудобно

Ориентация - Альбомная.

**Comment by AlexeyTishkin** [comment]
Исправил.
