### ISSUE TITLE
консевація і нарахування амортизації - нюанси

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#773]
насколько поняла из правил бух учета , то Нарахування амортизації припиняється починаючи з наступного місяця після місяця виводу його з експлуатації (консервації).
у нас:
![image](https://user-images.githubusercontent.com/38099938/50541001-5bd97c80-0ba5-11e9-9b61-e6809f0ba046.png)
в ведомость начисления амортизации за январь этот объект не попадает
![image](https://user-images.githubusercontent.com/38099938/50541007-89262a80-0ba5-11e9-945e-ecaad3724374.png)

еще тут такое дело, что:
Якщо протягом місяця здійснено виведення з експлуатації окремого об’єкта на кілька днів та його зворотне введення в експлуатацію, то нарахування амортизації не припиняється.

еще есть вопрос - как вводим в эксплуатацию разконсервированный объект?

**Comment by htrofymova** [comment]
1. Таким образом, амортизируется все, что есть в эксплуатации на начало месяца? - Исправлено. 
2. А вывод из эксплуатации на несколько дней - предлагаю считать не существующим в природе, ввиду полной бессмысленности оного. 
3. "Обратный" ввод в эксплуатацию - будет добавлен в следующих релизах.
