### ISSUE TITLE
Принудительно обновлять список выписок после импорта (как минимум по API)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#775]
Народ впадает в ступор и непонятку, когда после успешного импорта выписки список выписок остается пустым или содержит только ранние выписки.
Для появления новых необходимо вручную обновлять список.

Очень хочется, чтобы обновление списка происходило автоматом по окончании процедуры получения выписок.

**Comment by AlexeyTishkin** [comment]
Сделано в новом интерфейсе.
