### ISSUE TITLE
Добавить в импорт выписки возможность выбора существующего ранее выписанного счета.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#778]
На данный момент отсутствует возможность связать импортируемый платеж с ранее выписанным счетом, что нехорошо.

Было бы очень полезно добавить в импорт выписки возможность выбора существующего ранее выписанного счета.
Например по логике выбора типа операции + видимо с возможностью фильтрации списка по дате/контрагенту/еще чему-то.

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Ага, наблюдаю.
Даже как-то работает.
Буду тестить.
