### ISSUE TITLE
Разрешить заводить контрагента с одинаковым кодом ЄДРПОУ при условии разных МФО (банки)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#779]

**Comment by Anestezia** [comment]
Например, 
![image](https://user-images.githubusercontent.com/42540074/50828689-c0859b80-134a-11e9-8a7b-d0ed1180d4d6.png)

**Comment by mik-man** [comment]
Пример:
https://bank.gov.ua/control/uk/bankdict/search?name=&type=&region=&mfo=&edrpou=14305909&size=&group=&fromDate=&toDate=

**Comment by MaksymTikhomirov** [comment]
Надо сделать - клиенты Аваля и тыды попадают в тупик

**Comment by Illya-Lykhachov** [comment]
Вариант решения: добавить вид контрагента "Обособленное подразделение без образования юридического лица" (филиал, представительство, удалённое подразделение). Жестко связан с родительским ЕГРПОУ, но имеющий собственные свойства (адрес, название, расчётные счета, ...).
При обработке банковских выписок, подбирать контрагента не только по ЕГРПОУ, но и по счёту в банке

**Comment by MaksymTikhomirov** [comment]
> Вариант решения: добавить вид контрагента "Обособленное подразделение без образования юридического лица" (филиал, представительство, удалённое подразделение). Жестко связан с родительским ЕГРПОУ, но имеющий собственные свойства (адрес, название, расчётные счета, ...).



> Вариант решения: добавить вид контрагента "Обособленное подразделение без образования юридического лица" (филиал, представительство, удалённое подразделение). Жестко связан с родительским ЕГРПОУ, но имеющий собственные свойства (адрес, название, расчётные счета, ...).
> При обработке банковских выписок, подбирать контрагента не только по ЕГРПОУ, но и по счёту в банке

Илья, назначь исполнителя

**Comment by Illya-Lykhachov** [comment]
Посовещавшись решили:
1. Филиальную структуру контрагентов реализовывать после добавления возможности иметь нескольких предприятий в одном тенанте.
2. Для контрагентов-банков сделать свою процедуру проверки повторений, - по двойному ключу: МФО и ЕГРПОУ.
