### ISSUE TITLE
Пожелание: добавьте возможность в табличной части документа отображать полностью названия объектов учета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#78]
![image](https://user-images.githubusercontent.com/38099938/38933408-80dcaa7c-4321-11e8-922c-82374923a7af.png)

**Comment by AlexeyTishkin** [comment]
Это какое разрешение экрана ?

**Comment by kattrina-brekhova** [comment]
Монитор 15 дюймов

**Comment by kattrina-brekhova** [comment]
Я не знаю относительно разрешения

**Comment by AlexeyTishkin** [comment]
Монитор 15 дюймов

[ТА] А именно разрешение ? На рабочем столе правая кнопка – Разрешение экрана.

**Comment by kattrina-brekhova** [comment]
:) 1366 * 768

**Comment by nik-man** [comment]
Можно еще правую панельку убирать. :)
Кстати, может для Инвентаризации ее убирать по умолчанию?

**Comment by AlexeyTishkin** [comment]
Можно еще правую панельку убирать. :)

[ТА] В момент редактирования.

Кстати, может для Инвентаризации ее убирать по умолчанию?

[ТА] По умолчанию – нельзя, там Акты.

**Comment by AlexeyTishkin** [comment]
я закрываю предложение?

[ТА] Пока не надо. Сейчас будет вариант с подгонкой ширины колонок с количеством и суммой. А скрытие панели – если все равно ширина наименования будет маленькой.

**Comment by AlexeyTishkin** [comment]
Сделал подгонку.
