### ISSUE TITLE
Сделать возможность учета в сформированных счетах вводимой суммы оплаты в личном кабинете 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#780]
И (или) поле ввода количества оплачиваемых месяцев.
![image](https://user-images.githubusercontent.com/42540074/50837497-701b3780-1364-11e9-86dd-afe213fc1feb.png)

**Comment by AlexeyTishkin** [comment]
Имеется ввиду это:
https://github.com/a2develop/bugTracker/issues/503
?

**Comment by Anestezia** [comment]
да, суть похожа.
