### ISSUE TITLE
Добавить проводку при реализации не введенного в эксплуатацию ОС

### ISSUE THREAD

**Issue by shevchuk-vadim** [a2develop/bugTracker#782]
Не введенное в эксплуатацию ОС числится на 152 счете, а в проводках списывается с 286. Оно и должно списываться с 286, но оно туда сейчас попадает только после вывода из эксплуатации с целью продажи. Поэтому в операции реализации нужно добавить проводку Д 266 К 152 для тех объектов, которые не были введены в эксплуатацию. Непосредственно со 152 реализацию делать нельзя, согласно инструкции по использованию плана счетов.

**Comment by htrofymova** [comment]
проводка добавлена
