### ISSUE TITLE
Друк отчета Середньоолбікова кількість працівників - Неправильный разрыв страницы

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#783]
![photo_2019-01-10_10-52-27](https://user-images.githubusercontent.com/42540074/50959919-cc00d000-14cc-11e9-9734-dc96d89b791c.jpg)
![photo_2019-01-10_11-41-46](https://user-images.githubusercontent.com/42540074/50959924-cefbc080-14cc-11e9-8ea7-662ea8bb9bed.jpg)
Проверить также сохранение в форматах после устранения неполадки.

**Comment by alex-kukhtin** [comment]
Нужно переделать в "новом стиле" с использованием объекта SheetPage
