### ISSUE TITLE
Отцентровать названия колонок в отчетах

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#784]
![image](https://user-images.githubusercontent.com/42540074/50960025-12eec580-14cd-11e9-8926-887f3ac0a24a.png)

**Comment by AlexeyTishkin** [comment]
В отчетах в "Придбання", "Продажі", "Запаси" названия отцентрированы.

**Comment by htrofymova** [comment]
В отчетах по НА - названия колонок отцентрованы

**Comment by alexeijur** [comment]
В отчетах в разделе "Персонал" отцентрированы
