### ISSUE TITLE
Акт сверки расчетов Подправить подписи сторон внизу

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#785]
![image](https://user-images.githubusercontent.com/42540074/50960190-72e56c00-14cd-11e9-8cec-7e92909c8b72.png)
![image](https://user-images.githubusercontent.com/42540074/50960210-80025b00-14cd-11e9-9ded-f59640d80119.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
