### ISSUE TITLE
Нужна кнопка сохранения Прайс-листов в разных форматах в меню Прайс-Листы и в документе Створення прайс-листа

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#788]

**Comment by AlexeyTishkin** [comment]
Для вывода на печать прайс-листов есть отчет "Прайс-лист".
Экспорт этого отчета в Excel и др. форматы (также как и остальных отчетов внутри системы) предмет отдельного issue. И этот issue уже есть.

**Comment by Anestezia** [comment]
не нашла ишью соответствующих

**Comment by AlexeyTishkin** [comment]
https://github.com/a2develop/bugTracker/issues/659

Отчет "Прайс-лист" - это такой же "внутренний" отчет. Как только появится такой функционал - он сразу будет во всех таких отчетах.

**Comment by AlexeyTishkin** [comment]
Reopened - https://github.com/a2develop/bugTracker/issues/47
Его и оставить, остальные - закрыть.
