### ISSUE TITLE
Предложение: создать возможность оприходования безоплатно полученных ТМЦ...

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#79]
Проводка Д201, 203,....281 - К745 Дохід від безоплатно одержаних активів
Сомневаюсь, что бухгалтера, которые показывают подобные доходы, существуют. Но по правилам, операция должна существовать

**Comment by AlexeyTishkin** [comment]
Это в Акте оприходования ?

**Comment by kattrina-brekhova** [comment]
Да
