### ISSUE TITLE
начальный баланс по НА: не видит все объекты учета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#790]
что произошло:
зашла в подраздел объекты учета, создал стоматолог. стул
![image](https://user-images.githubusercontent.com/38099938/51043838-511cdf80-15c8-11e9-82c1-df8ee9c224af.png)
в карточке начального баланса не отражается этот объект
![image](https://user-images.githubusercontent.com/38099938/51043870-65f97300-15c8-11e9-9e36-27e7949dee5b.png)

**Comment by htrofymova** [comment]
исправлено
