### ISSUE TITLE
Уточнить заголовки в отчетах по операциям с валютой

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#792]
У нас заголовки в отчетах по гривне и по валюте почти везде одинаковые.

Думаю, стоит 
http://dev.a2start.com/reports/agents/turnoversheetagent632/new
Изменить заголовок на "Відомість за розрахунками з постачальниками у валюті"

http://dev.a2start.com/reports/agents/turnoversheetagent362/new
Изменить заголовок на "Відомість за розрахунками з покупцями у валюті"

http://dev.a2start.com/reports/bank/currencyturnover/new
Изменить заголовок на "Оборотно-сальдова відомість по рахунку в банку в іноземній валюті"

**Comment by AlexeyTishkin** [comment]
Изменил.
