### ISSUE TITLE
Персонал. Нужен вид операции "Доплата до минимальной зарплаты"

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#794]

**Comment by alex-kukhtin** [comment]
Что это за странная операция такая?

**Comment by mik-man** [comment]
> Что это за странная операция такая?

На текущий момент сложилась интересная ситуация.
Размер должностного оклада должен быть не менее прожиточного минимума (1921 грн.)
При этом минимальная заработная плата составляет 4173 грн.

Например, организация может устанавливать оклад 2000 грн., но начислять обязаны 4173 грн. (Почему некоторые организации не хотят или не могут просто увеличить оклад -- не знаю, логики не вижу). В этом случае делается доплата до минимальной в размере 2173 грн.

**Comment by alex-kukhtin** [comment]
Ну то-есть мы будем реализовывать забаганки всех извращенцев?

**Comment by mik-man** [comment]
> Ну то-есть мы будем реализовывать забаганки всех извращенцев?

Как скажете.
