### ISSUE TITLE
Добавить импорт выписки ПУМБ в валюте

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#797]
Примеры файлов выписок в DBF/CSV/XLS добавлены на ГуглДиск
https://drive.google.com/drive/folders/1BlDJ8ZuCkSMlXNqnHWjv5P48tE3ttOb7

с интексом ТХ - гривна.
без индекса ТХ - валюта (в примере - ЕВРО)

**Comment by alex-kukhtin** [comment]
7422

**Comment by AndriyNesterenya** [comment]
написанному "с интексом ТХ - гривна. без индекса ТХ - валюта (в примере - ЕВРО)" - НЕ ВЕРИТЬ.
Оказалось, там при сохранении в DBF клиент-банк ПУМБа зачем-то сохраняет ДВА файла вместо одного.
В первом заголовок, во втором данные.
Договорился, что меня пустят в клиент-банк посмотреть, как именно оно там происходит, по результатам выдам внятное описание процесса.
