### ISSUE TITLE
Ведомость на выплату зп касса, банк Нужна возможность удалять рядки

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#798]
![image](https://user-images.githubusercontent.com/42540074/51249287-84ca8180-199b-11e9-92a2-bc5092211211.png)

**Comment by Anestezia** [comment]
в банк решили не добавлять?

**Comment by Illya-Lykhachov** [comment]
про банк забыл, сейчас сделаю

**Comment by Illya-Lykhachov** [comment]
готово

**Comment by Anestezia** [comment]
Да, есть
