### ISSUE TITLE
Опечатка в оплате через IBox

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#799]
Опечатка в оплате через IBox

![image](https://user-images.githubusercontent.com/38098758/51310540-8b1a3580-1a4f-11e9-8187-d74baae316af.png)

**Comment by AndriyNesterenya** [comment]
+ режет глаз слово "емейл".
"Введіть адресу електронної пошти, що була вказана при реєстрації..." ?

**Comment by kattrina-brekhova** [comment]
ну как вариант "Введіть електронну пошту, що була вказана при реєстрації в BookKeeper".
чем меньше знаков, тем юзабильнее для пользователей

**Comment by AndriyNesterenya** [comment]
... так никто ничего и не исправил.
Все еще висит опечатка

**Comment by kattrina-brekhova** [comment]
готово, будет уже доступно для след релиза
