### ISSUE TITLE
Предложение: показывать в разделе Персонал непроведенные приказы с пометкой

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#80]
Обнаружил непонимание пользователями нашей логики работы раздела "Персонал".
Народ с ходу  идет в Персонал -> Сотрудники, оттуда создает Физлицо, пишет на него приказ, СОХРАНЯЕТ (о проводке сразу никто не думает), а потом сильно удивляется, почему в Сотрудниках ничего не появилось.
Предлагаю : показывать в Сотрудниках в т.ч. непроведенные приказы, выделив их цветом и/или с пометкой "не проведено", и по клику переходить на соотв. приказ в Документах для возможности его проведения.

**Comment by Illya-Lykhachov** [comment]
В списке сотрудников отображаются не приказы, а состояние физлиц (принят, но ещё не уволен).
Если в сотрудниках показать "недопроведенного" сотрудника, то никто не обратит внимание на его непроведенность и будут думать шо так и надо (он же в списке).
Предлагаю бороться не со следствиями, а с причинами. Напоминалку о необходимости провести приказ о приёме добавить в сам приказ. Как в проведенном документе вверху висит зелёный alert "Документ проведен в учёте. Изменение и удаление невозможно", так в непроведенном вешать оранжевый алерт "Документ непроведен. Нихера у Вас не получится"
Кстати, вышесказанное касается вообще всех документов.
Ваше мнение?

**Comment by MaksymTikhomirov** [comment]
> В списке сотрудников отображаются не приказы, а состояние физлиц (принят, но ещё не уволен).
Если в сотрудниках показать "недопроведенного" сотрудника, то никто не обратит внимание на его непроведенность и будут думать шо так и надо (он же в списке).
Предлагаю бороться не со следствиями, а с причинами. Напоминалку о необходимости провести приказ о приёме добавить в сам приказ. Как в проведенном документе вверху висит зелёный alert "Документ проведен в учёте. Изменение и удаление невозможно", так в непроведенном вешать оранжевый алерт "Документ непроведен. Нихера у Вас не получится"
Кстати, вышесказанное касается вообще всех документов.
Ваше мнение?


Я за, тащемта.

**Comment by Illya-Lykhachov** [comment]
Сделал для приказа о приёме на работу. Посмотрите. Если устраивает, размажем по всем документам
