### ISSUE TITLE
Создать документ для приходования Лицензии на БукКипер у пользователей

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#803]
Резюме по обсуждению:
Наша лицензия - это нематериальный актив. Только он краткосрочный, поскольку лицензия действует месяц. Поэтому необоротным активом являться не может. И его стоимость нужно сразу списывать на расходы, подобно услугам. Они должны списываться сразу в приходной накладной! Нужно только понять по какому критерию. Даже может птичку сделать - списывать сразу.
Не приходной, а в Акте приема-передачи объекта нематериальных активов.
Тупо птичку - "Списывать на затраты сразу" со всплывалкой что это значит.
![image](https://user-images.githubusercontent.com/42540074/51467203-a600e880-1d74-11e9-9fd6-1bc331a968ad.png)

 
Если покупатель - конечный потребитель ПО, то у него есть два варианта. Если лицензия долгосрочная, то он должен рассматривать ее, как нематериальный актив, оприходовать на счет 154, и ввести в эксплуатацию на счет 127. А если краткосрочная, то он должен в момент приобретения относить стоимость лицензии на расходы. В случае бухгалтерского ПО это счет 92.

Если покупатель покупает ПО для того, чтобы зарабатывать на нем, например, распространять, или включать в собственные продукты (как мы СтимулСофт), то стоимость лицензии нужно относить на расходы в любом случае, потому что это роялти.

С проводками тут все понятно. Непонятно, какую терминологию использовать. У объектов, используемых в вышеперечисленных операциях, нет общепринятого общего названия.

Предлагаю поступить так. "Акт прийому-передачі об'єкта нематеріальних активів" переименовать в "Акт приймання-передачі нематеріальних об'єктів". В нем допускать выбор объектов вида "Нематеріальні активи" и "Інші нематеріальні об'єкти". Если объекты второго вида присутствуют в документе, то отображать список "Списання на:", как в акте приема услуг, и ставить в проводки по этим объектам соответствующий счет в дебет.

**Comment by mik-man** [comment]
Для начала не помешает сделать в разделе "Продажі" документ "Акт прийому-передачі об'єкта нематеріальних активів". А то пока мы своим клиентам и напечатать не можем его.

**Comment by mik-man** [comment]
На текущий момент нужны три похожих документа:

- [ ] Продажі та НА: видатковий "Акт прийому-передачі об'єкта нематеріальних активів"

- [ ] Продажі: видатковий "Акт прийому-передачі нематеріальних об'єктів"
- [ ] Придбання: прибутковий "Акт прийому-передачі нематеріальних об'єктів"

**Comment by htrofymova** [comment]
Видатковий  "Акт прийому-передачі об'єкта нематеріальних активів" - согласна. А еще два таких же, но немного с другим названием зачем? чтобы что?
И зачем придумывать название объектам? Нематериальные активы кого-то запутают? Активы - они и есть активы, товар - тоже активы. Имеем право нематериальные активы сразу списать на затраты, ну и списываем. Зачем эти сложности лишние?

**Comment by Anestezia** [comment]
Тогда сформируйте новое ишью, а это я закрою, как выполненное.

**Comment by htrofymova** [comment]
То, что сформулировано в заголовке - уже существует.
