### ISSUE TITLE
створення рецептури: не работает кнопка провести, сохранить - не активна

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#804]
![image](https://user-images.githubusercontent.com/38099938/51549501-3c1b3880-1e73-11e9-8a91-fe403717fc68.png)

**Comment by AndriyNesterenya** [comment]
... и ссылка на Help ведет на http://help.bookkeeper.kiev.ua/index , потому что статьи нет еще.

**Comment by kattrina-brekhova** [comment]
не об этом речь шла. вчера операция не проводилась, наверное что-то чинили. сегодня все есть
