### ISSUE TITLE
Добавить вводимое количество символов инвентарного номера, Срочно!!!

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#807]

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
Все ок, единственный момент: слишком длинный номер не печатается
![image](https://user-images.githubusercontent.com/42540074/51756537-eee4d400-20c9-11e9-91ce-89e749c6ca5b.png)

**Comment by htrofymova** [comment]
исправлено - длинный инв. номер теперь помещается

**Comment by Anestezia** [comment]
подтверждаю, все ок
