### ISSUE TITLE
Налоговая накладная. Откорректировать перенос пустых полей в Сонату и хмл.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#808]
![image](https://user-images.githubusercontent.com/42540074/51756183-1be4b700-20c9-11e9-8f78-de49dea14c31.png)
Наша налоговая накладная
После переноса в Сонату выглядит так. Пустые поля заполняются нулями. Проверку корректности проходит.
![image](https://user-images.githubusercontent.com/42540074/51756255-3ae34900-20c9-11e9-9251-d476081d577f.png)
Вручную убрала в Сонате нули - проверку корректности проходит. Клиенты жалуются, если нули есть, так как неудобно отправлять контрагентам, приходится переделывать вручную.
![image](https://user-images.githubusercontent.com/42540074/51756327-66663380-20c9-11e9-9ae6-66493c1157a6.png)

**Comment by AlexeyTishkin** [comment]
Сделано.
