### ISSUE TITLE
Начисление бонусных месяцев при оплате за 6 и 12 месяцев

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#809]
Необходимо реализовать начисление бонусных месяцев, клиентам оплатившим сразу за 6 и 12 месяцев:
за 6 оплаченных (период от 6 до 11 месяцев) - один бонусный месяц.
за 12 оплаченных - два бонусных месяца.

P.S. уже сейчас нужно начислить:
тенант 896 - 2 месяца
тенант 546 - 1 месяц
тенант 677 - 1 месяц

**Comment by DenisClone** [comment]
И еще начислить тенанту 716 - 1 месяц

**Comment by DenisClone** [comment]
Up.

**Comment by alex-kukhtin** [comment]
Done. v7429

**Comment by DenisClone** [comment]
Начислил 4 бонуса
