### ISSUE TITLE
Предложение: сделать возможность удаления документа прямо в окне документа

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#81]
У нас в данный момент можно удалить документ или операцию только из общего списка, если документ/операция не была проведена или проводка отменена.
Отменить проводку при этом можно только собственно в окне документа/операции.

Предлагаю : сделать кнопочку удаления на панели рядом с проводилкой, и активировать соответственно состоянию проводки.

**Comment by AlexeyTishkin** [comment]
Сделал в товарных документах.

**Comment by AndriyNesterenya** [comment]
Оч. нравится. Покажу теткам.
