### ISSUE TITLE
в Д4 не отражаються ФЛ и начисления за ЦПД

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#810]
![image](https://user-images.githubusercontent.com/38099938/51837049-e9c29780-230a-11e9-8e28-a4ac34a38055.png)
![image](https://user-images.githubusercontent.com/38099938/51837056-f0510f00-230a-11e9-8622-e28b4028b6d9.png)
![image](https://user-images.githubusercontent.com/38099938/51837073-f941e080-230a-11e9-89ee-c8e23a23ccf7.png)

**Comment by kattrina-brekhova** [comment]
в таблицу 6 моя Панова тоже не попала

**Comment by Illya-Lykhachov** [comment]
Добавлены ГПХ в таблицы 1, 5, 6
