### ISSUE TITLE
Нужна операция внесения в уставной фонд Необоротных активов  

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#811]
Дт 10, 12, 11 Кт 46 — відображено внески засновників необоротними активами (основними засобами, нематеріальними активами, іншими необоротними активами)
с приходованием на склад, чтоб потом можно было ввести в эксплуатацию.

1) Факт передачі майна від засновника (учасника) до створюваного підприємства прийнято оформляти актом приймання-передачі. Акт підписують сторони, що передають і приймають: тобто учасник (фізособа за себе, від імені юрособи – її керівник або інша уповноважена особа) і підприємство (це може бути керівник підприємства або інша уповноважена ним або зборами засновників особа). 

2) Якщо в юрособи всього один засновник, який також є і керівником підприємства, то акт приймання-передачі може підписати одна й та сама особа, (НУЖНО ПРЕДУСМОТРЕТЬ ВАРИАНТ ДВУХ СТОРОН-ПОДПИСАНТОВ, ЯВЛЯЮЩИХСЯ ОДНИМ И ТЕМ ЖЕ ЛИЦОМ!!! ) яка в цьому випадку представлятиме як сторону, що передає, так і сторону, що приймає (лист Держкомпідприємництва від 10.09.08 р. № 7667). 

Акт приймання-передачі внеску до СК складається в довільній формі, проте рекомендуємо: включити в акт усі реквізити, які згідно із ч. 2 ст. 9 Закону № 996 є обов'язковими для первинного документа; якщо внесок робиться у вигляді транспортного засобу або об'єкта нерухомості – передати правовстановні документи на таке майно (за їх наявності), про що зробити зауваження в акті. (ЗДЕСЬ ПРИМЕЧАНИЕ С ДОСТАТОЧНЫМ ЧИСЛОМ СИМВОЛОВ С ВЫВОДОМ НА ПЕЧАТЬ, ЛИБО ПО ПРИНЦИПУ КОЛОНТИТУЛА, ЕСЛИ КЛИЕНТУ НУЖНО БУДЕТ И ПРИМЕЧАНИЕ НЕПЕЧАТНОЕ ДЛЯ СЕБЯ И ПОЛЕ ДЛЯ ИНФОРМАЦИИ ОБ ОБЪЕКТЕ!)

зафіксувати в акті докладні характеристики майна, що передається. Наприклад, якщо це автомобіль, то в акті фіксують його марку, модель, рік випуску, колір, держномер та інші необхідні характеристики. При цьому засновник повинен зняти автомобіль з обліку, а підприємство, що отримало цей внесок, – зобов'язане поставити авто на облік. Взяття на облік здійснюється відповідно до Порядку, затвердженого постановою КМУ від 07.09.98 р. № 1388. Якщо передається нерухомість, то в акті зазначається її адреса, площа (загальна, житлова), кількість поверхів тощо, інформація про документ, що підтверджує право власності учасника на цю нерухомість. Під час переоформлення права власності «на себе» підприємству необхідно керуватися Порядком, затвердженим постановою КМУ від 25.12.15 р. № 1127.

**Comment by Anestezia** [comment]
В печатной форме документа от эмитента внизу не подставилась фамилия подписанта, исполнителя.
![image](https://user-images.githubusercontent.com/42540074/52331782-b74b2580-2a01-11e9-8167-9200b8186079.png)
После проведения документа от инвестора со склада не списался объект учета, переданный.
![image](https://user-images.githubusercontent.com/42540074/52332599-c206ba00-2a03-11e9-995d-af1f0f27d4e7.png)
В моем примере автомобиль.

**Comment by htrofymova** [comment]
исправлено

**Comment by htrofymova** [comment]
печать - повторить не могу
