### ISSUE TITLE
Акт виконаних робіт ФОПа - Реалізувати можливість додавання в графу "Представник виконавця" самого ФОПа, а не тільки співробітника.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#813]
При заповненні акту виконаних робіт в графі "представник виконавця" пропонується на вибір тільки хтось із працівників, немає можливості внести в цю графу самого ФОПа

**Comment by AlexeyTishkin** [comment]
Это поле для ручного заполнения.

**Comment by AlexeyTishkin** [comment]
И как будеть выглядеть текст в печатной форме ?
"з одного боку, та представник ВИКОНАВЦЯ ФОП Іванов І. І. Іванов І. І." ?
