### ISSUE TITLE
[ЗЕД] Добавить инвойс (экспорт товара)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#816]
Пора добавлять инвойс на экспорт товара.
Видимо, уже с учетом перехода на IBAN

**Comment by MaksymTikhomirov** [comment]
Видимо, уже с учетом перехода на IBAN

Пока нет, тупо снимем ограничение (которое только цифры в номере счета)

**Comment by AlexeyTishkin** [comment]
Сделал.

**Comment by AndriyNesterenya** [comment]
Наблюдаю.
С виду ОК.
