### ISSUE TITLE
Счет исходящий - сохранение в формате рисунка исправить

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#822]
1. Не подтягивает шапку: Постачальник
![image](https://user-images.githubusercontent.com/42540074/52340275-0603ba00-2a18-11e9-8d57-044deb9c778d.png)
Отображается только если поставить в настройках этого отдельного сохранения галочку Обрезать края.
![image](https://user-images.githubusercontent.com/42540074/52340328-29c70000-2a18-11e9-8744-0fcf90004f93.png)
2. Не отображается на рисунке вообще содержание предмета договора. (видно на картинке)
Вот исходник:
![image](https://user-images.githubusercontent.com/42540074/52340395-5b3fcb80-2a18-11e9-85da-36f4fc08227b.png)

3. Не влезает длинная строка предмета договора

**Comment by AlexeyTishkin** [comment]
Глюки с картинкой повторить не могу.

**Comment by AlexeyTishkin** [comment]
> Не влезает длинная строка предмета договора

Исправил.
