### ISSUE TITLE
Виправлення помилок додати у документи розділів НА, Бухгалтерія, Персонал

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#823]
- [x] НА
- [x] Бухгалтерія
- [x] Персонал

**Comment by AlexeyTishkin** [comment]
В "Бухгалтерию" добавил.

**Comment by htrofymova** [comment]
В НА - добавила

**Comment by Anestezia** [comment]
Персонал. Наказ, номер не отображается
![image](https://user-images.githubusercontent.com/42540074/52846911-7e066a00-3113-11e9-9f5e-1571786b3792.png)
Все доки по персоналу надо проверить по процедуре отображения
![image](https://user-images.githubusercontent.com/42540074/52847005-c02fab80-3113-11e9-931d-62a45852aa1d.png)
