### ISSUE TITLE
В налоговой накладной инициалы подписанта поставить перед фамилией

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#824]
![image](https://user-images.githubusercontent.com/42540074/52400474-e75cfc00-2ac7-11e9-8164-68468dcbcfbf.png)

**Comment by Illya-Lykhachov** [comment]
А вам не кажется, что это бред?
Это просто текстовое поле

**Comment by AlexeyTishkin** [comment]
Изменил.
