### ISSUE TITLE
[Верстка] Мелкий косяк с всплывалкой на кодах объекта учета

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#826]
Мелкий косяк с всплывалкой на кодах объекта учета :

![image](https://user-images.githubusercontent.com/38098758/52468910-be556d80-2b92-11e9-8603-b549c771b802.png)

Подсказка отображается обрезанной и появляется скролл

**Comment by AlexeyTishkin** [comment]
Исправил.
