### ISSUE TITLE
Метатеги добавляются не на все страницы сервиса

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#827]
Файлы с метатегами, которые расположены по пути - App_apps/main/_meta
Добавляются не во все страницы сервиса. Например не вижу этих метатегов на странице - https://______.kiev.ua/home
Подозреваю что так на всех страницах, которые находятся "за авторизацией".

**Comment by alex-kukhtin** [comment]
Конечно.
А нахрена они в /home? Гугл к ним все равно не достучится.

**Comment by alex-kukhtin** [comment]
Или ты ему пароль дашь :-)

**Comment by DenisClone** [comment]
Ок. Закрываю.
