### ISSUE TITLE
Выводить коды УКТЗЕД в счетах/накладных

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#828]
Хотят коды УКТЗЕД в счетах/накладных.
Мотивируют следующими соображениями :

Ситуация 1.
Мы отгрузили товар посреднику, но налоговую еще не зарегистрировали. Соответственно он не видит кода. Но посредник продал этот товар своему клиенту и хочет зарегистрировать налоговую ему. И тут начинается. Звонки, переписки … чтобы узнать код.

Ситуация 2.
Нормальная практика ставить на приход товар от ФОПа. И это самое геморное. Какой код? Ведь ФОПы, как правило, работают без НДС.

Решили приписывать код в строке под наименованием.

Добавить в формы:
- счет
- расходная накладная
- еще думаю

**Comment by AlexeyTishkin** [comment]
Сделал вместо колонки "Артикул". Решили, что т.к. артикул - это внутренний код, то для исходящих документов его печать не имеет смысла.
