### ISSUE TITLE
Некорректное отображение суммы в Д4 по договору ГПХ, табл.1

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#829]
![image](https://user-images.githubusercontent.com/42540074/52567345-c290bd80-2e14-11e9-8654-280d7682b269.png)
А эти цифры Соната считает корректными.
![image](https://user-images.githubusercontent.com/42540074/52567458-0edbfd80-2e15-11e9-986c-e256c9934e85.png)
 Сумма в рассчете задваивается по ГПХ
![photo_2019-02-11_15-46-30](https://user-images.githubusercontent.com/42540074/52567827-e1438400-2e15-11e9-8939-9738d2b0d0b5.jpg)

**Comment by Illya-Lykhachov** [comment]
исправлено
