### ISSUE TITLE
Не отображается кол-во дней по ГПХ в табл.6 Д4.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#830]
![image](https://user-images.githubusercontent.com/42540074/52568796-6f206e80-2e18-11e9-8665-72b05f9c58a5.png)
15. Кількість календарних днів перебування у трудових / цивільно- правових відносинах, проходження військової служби протягом звітного місяця

**Comment by Illya-Lykhachov** [comment]
исправлено
