### ISSUE TITLE
Доработка номера счета за оплату сервиса

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#831]
Предлагается в номер счета, который формируем за оплату нашего сервиса, добавить две цифры дня месяца.
Например: 0001/190212 
Уже есть случаи дублирования счета, полученного второй раз за месяц.

**Comment by AlexeyTishkin** [comment]
Имеется в ввиду: Особистий кабінет - Стан рахунку - Сформувати рахунок ?

**Comment by MaksymTikhomirov** [comment]
> Имеется в ввиду: Особистий кабінет - Стан рахунку - Сформувати рахунок ?

Да

**Comment by AlexeyTishkin** [comment]
Сделал.
