### ISSUE TITLE
Акт списання -- додати Проект.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#834]

**Comment by AlexeyTishkin** [comment]
Зачем ?
Проект по 631/361 счетам.

**Comment by mik-man** [comment]
Проект -- это единственная универсальная аналитика. Ее используют в разных целях. Вообще говоря, она должна быть везде. И, по-хорошему, ее нужно как-нибудь переименовать. ;)

Например, звонил клиент -- завел в Проектах свои транспортные средства, хочет списывать на них ГСМ и расходники.

**Comment by AlexeyTishkin** [comment]
Укажет пользователь в "Акте списания" проект. Дальше что ? Увидит, что на нем висят документы... И ? Как это анализировать ?

**Comment by AlexeyTishkin** [comment]
> Например, звонил клиент -- завел в Проектах свои транспортные средства, хочет списывать на них ГСМ и расходники.

Для этого нужно делать ЦФО и статьи затрат.

**Comment by AlexeyTishkin** [comment]
> Проект -- это единственная универсальная аналитика

Нет, не универсальная. Только расчеты.

**Comment by mik-man** [comment]
Ну и ладно. )
