### ISSUE TITLE
Диалог выбора фискального отчета - добавить фильтр по виду налогообложения Моей фирмы.

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#835]
Отчетов становится все больше, пользователи начинают путаться.
Например есть два отчета "Податкова декларація платника ЄП ФОП" -- годовая и квартальная.
Они ничем не различаются, кроме того, что квартальная -- для ФОП 3-й группы,
а годовая -- для 1-й и 2-й групп.
Причем обе могут строиться за год.

**Comment by AlexeyTishkin** [comment]
Сделал.
