### ISSUE TITLE
Рассмотреть возможность реализации выставления счета за лицензию клиентам, пришедшим из П24, на наш счет в ПБ

### ISSUE THREAD

**Issue by MaksymTikhomirov** [a2develop/bugTracker#838]

**Comment by DenisClone** [comment]
Вижу такой вариант логики:
- создаем справочник наших платежных реквизитов. 
- для начала вносим туда реквизиты в ТАС и Приват.
- при нажатии клиентом на кнопку «Сформировать счет», проверяем его поле - «источник регистрации клиента». Если оно равно Privat, то добавляем в счет реквизиты Привата, иначе добавляем в счет реквизиты по умолчанию – ТАС.
В дальнейшем, при необходимости, справочник можно наполнить реквизитами под все банки-партнеры, и формировать счета отдельно, для клиентов пришедших от них.

**Comment by DenisClone** [comment]
Или вообще дать возможность выбора клиенту :)
Возле кнопки «Сформировать счет», расположить радио баттон: Приват, ТАС и т.д.
Клиент перед нажатием на кнопку, сам выбирает, счет в какой банк ему формировать.

**Comment by alex-kukhtin** [comment]
Согласен. Создаем справочник.
Насколько быстро надо?

**Comment by alex-kukhtin** [comment]
Done in 7459
