### ISSUE TITLE
Механизм выборки в разделе Биллинг

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#839]
Раздел «Биллинг» нужно сразу строить так, чтобы им в дальнейшем пользовались наши дилеры (и скорее всего субдилеры), то есть должны учитываться разграничения доступа к информации. Дилер видит оплаты только своих клиентов и клиентов своих субдилеров. Субдилер видит оплаты только своих клиентов. Сотрудники БК видят все оплаты.

**Раздел «Користувачі»**
 
Над таблицей расположен механизм выборки, который содержит: раскрывающийся список, временной интервал, источник регистрации, строку поиска и кнопку “Найти”.
- Раскрывающийся список имеет следующие пункты: Все клиенты, Действующая оплата (0 и больше), Просроченная оплата (минус на счете), Только одна оплата.
В дальнейшем список может быть дополнен.
- Временной интервал выбирается при помощи двух граничных дат, с помощью инструмента «календарь». Даты используются с признаком «включительно». Фильтр применяется к полю «Остання оплата».
- Источник регистрации выбирается из раскрывающегося списка, первый пункт которого «Все источники», дальше все существующие источники.
Список может «захламится» дилерами и сублилерами (фактически все реф.ссылки). Пока вопрос, как удобно реализовать.
 
Все значения элементов сортировки, при нажатии кнопки «Найти», соединяются логическим «И». В результатах выборки можно сортировать данные по любой колонке.
 
В правом верхнем углу расположена кнопка экспорта в Exсel. Выгружает результат сортировки (что видим то и экспортируем).
 
**Раздел «Оплаты»**
 
Над таблицей расположен механизм выборки, который содержит: статус операции, временной интервал, источник оплаты, источник регистрации, строку поиска и кнопку “Найти”.
- Статус операции выбирается из раскрывающегося списка и имеет следующие пункты: первый пункт «Все статусы», дальше все существующие статусы.
- Временной интервал выбирается при помощи двух граничных дат, с помощью инструмента «календарь». Даты используются с признаком «включительно». Фильтр применяется к полю «Сплачено».
- Источник оплаты выбирается из раскрывающегося списка, первый пункт которого «Все источники», дальше все существующие источники.
- Источник регистрации выбирается из раскрывающегося списка, первый пункт которого «Все источники», дальше все существующие источники.
 
Все значения элементов сортировки, при нажатии кнопки «Найти», соединяются логическим «И». В результатах выборки можно сортировать данные по любой колонке.
 
В правом верхнем углу расположена кнопка экспорта в Exсel. Выгружает результат сортировки (что видим то и экспортируем).
 
**Уровни доступа**
Для группы «Дилеры» и «Администраторы Биллинга» (подразумеваю что это только сотрудники БК) нужно ввести две роли: «просмотр биллинга» и «кассир». В настройках пользователя админки, на ряду с группой указывается нужная роль.
Роль «просмотр биллинга» дает возможность видеть все оплаты и статистику оплат по пользователям. Роль «кассир» - это «просмотр биллинга» + дает доступ к кнопкам «Создать оплату» и «Добавить бонус».

Например:
Пользователь-А имеет группу «Администраторы Биллинга» и роль «просмотр биллинга» - видит все оплаты в разделе «Биллинг» но внести ничего не может (условная Настя)
Пользователь-Б имеет группу «Дилеры» и роль «кассир» - видит все оплаты своих клиентов и оплаты клиентов своих субдилеров а так же может внести безнальную оплату для своих клиентов и клиентов своих субдилеров. (условный Сергей Ч.)

**Comment by alex-kukhtin** [comment]
Похоже это уже надо закрывать.
Все по другому переделали нафиг.

**Comment by DenisClone** [comment]
Под диллеров нужно будет что-то делать в любом случае. Но наверное, уже когда будет реальная необходимость.
