### ISSUE TITLE
Ошибка: в документе оприходование запасов замените номер корреспондирующего счета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#84]
Я ошиблась в новой проводке, которую вчера просила создать в документе Оприходование запасов по бесплатно полученным запасам.
Сейчас: (Д201... - К745).
Нужно заменить на: Д201, 203, 205, 207, 209, 281 - К719 Інші доходи від операційної діяльності. Замените, пожалуйста.
Также я еще думаю, что может быть в строке прописывать не название бухгалтерских счетов, а название хоз операций?
Відшкодування раніше списаних активів на Оприбуткування надлишків 
А Інші доходи від операційної діяльності на Безоплатно отримані запаси
Как считаете?
![30715441_1970430303207811_6904455331875651584_n](https://user-images.githubusercontent.com/38099938/39001318-b2afc6b4-43fe-11e8-9a96-df77aaf0e2ee.png)

**Comment by AlexeyTishkin** [comment]
745 убрать ?

**Comment by kattrina-brekhova** [comment]
да, заменить К719 Інші доходи від операційної діяльності. 
Спасибо!!

**Comment by AlexeyTishkin** [comment]
> Также я еще думаю, что может быть в строке прописывать не название бухгалтерских счетов, а название хоз операций?

"Інші доходи від операційної діяльності" явно не относятся только к "Безоплатно отримані запаси" ? Там же, наверняка, еще есть хоз. операции ?

**Comment by kattrina-brekhova** [comment]
Вот и я вчера решила, что в кредит нужно ставить 745 счет. Но сейчас понимаю, что на этом счете отображается информация по бесплатно полученным НЕОБОРОТНЫМ активам, которые в дальнейшем будут амортизироваться.
И кажется я туплю. Вы правы
Есть еще счет К 718 Дохід від безоплатно одержаних оборотних активів

**Comment by AlexeyTishkin** [comment]
745 убрал, 719 добавил.
718 добавлять ?

**Comment by kattrina-brekhova** [comment]
Я думаю да, К 718 Дохід від безоплатно одержаних оборотних активів - будет правильным
Пусть бы еще Николай нас перепроверил

**Comment by kattrina-brekhova** [comment]
Алексей, проконсультировалась у Николая, пришли к мнению, что в этих операциях ни 719, ни 745 не используем, а заменяем на К 718 Дохід від безоплатно одержаних оборотних активів

**Comment by AlexeyTishkin** [comment]
719 убрал, 718 добавил.
Проверяйте.
