### ISSUE TITLE
[Улучшайзинг] Отделить визуально в таблице выписки платежи один от другого

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#841]
Разбирался с живым клиентом с выписками - выяснил, что в нынешнем состоянии при разнесении выписки уже глаза разбегаются, и выделить нужную ячейку уже непросто.

Предлагаю визуально отделить ячейку каждой операции от соседних.

Например более темной / жирной линией.
Или spacing какой-то  между ячейками приделать.

![image](https://user-images.githubusercontent.com/38098758/52879255-5c36d280-3167-11e9-9359-085c83071c97.png)

**Comment by AlexeyTishkin** [comment]
Выписка уже сделана в новом интерфейсе. Предлагаю этот issue закрыть как не актуальный.

**Comment by alex-kukhtin** [comment]
Уже не нужно по идее.
