### ISSUE TITLE
Введення в експлуатацію ОЗ після тимчасового виведення - не видит объекту учета - нужна помощь

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#848]
есть объект - зеркало
![image](https://user-images.githubusercontent.com/38099938/53400739-32777a00-39b7-11e9-9d93-619730a006ab.png)
временно вывела из эксплуатации
![image](https://user-images.githubusercontent.com/38099938/53400768-44f1b380-39b7-11e9-9a70-44411d592ef0.png)
хочу снова ввести, но его не видно в списке. что не так делаю?
![image](https://user-images.githubusercontent.com/38099938/53400843-62268200-39b7-11e9-8399-d2cb413db216.png)

**Comment by htrofymova** [comment]
группа НА не соответствовала типу объекта учета. Добавлен валидатор в Акт ввода в эксплуатацию, чтобы можно было выбрать только соответствующую группу.
