### ISSUE TITLE
В приказ об отпуске добавить ячейку с ручным указанием количества дней отпуска для оплаты работодателем

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#849]
Вопрос об отображении праздничных дней попавших на отпуск. Они не оплачиваются. Как временную меру, пока нет календаря: в приказе на отпуск сделать поле: "Подлежит оплате, дней", чтоб человек сам руками туда ставил кол-во дней, которое будет оплачиваться и которое подтянется в ведомость расчетную. А на печать в приказ выводиться не будет.
И с отчетами  чтоб не конфликтовало.

**Comment by Anestezia** [comment]
Клиент срочно просит!

**Comment by Illya-Lykhachov** [comment]
Сделал и убрал. Не сработает, когда отпуск переходящий на другой месяц :(

**Comment by Illya-Lykhachov** [comment]
Сделал.

**Comment by Anestezia** [comment]
У меня отпуск проходит через 2 месяца, и есть праздники в этот период, я вручную поставила дней отпуска 11, а не 14
![image](https://user-images.githubusercontent.com/42540074/57765682-9ab03f00-770e-11e9-921a-065e0909fa67.png)
Потом смотрю в ведомости начисления ЗП, там указывается 14 дней и вручную их не поправить
 
![image](https://user-images.githubusercontent.com/42540074/57765770-c6332980-770e-11e9-9e1b-99645eb19a6b.png)

**Comment by Illya-Lykhachov** [comment]
Уже можно
