### ISSUE TITLE
В администрировании тенантов нужен толковый поиск по номеру телефона

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#850]
![image](https://user-images.githubusercontent.com/42540074/53411989-c30e8400-39d0-11e9-80e1-0eb4ea92eb3d.png)
Не ищет, как номер не набирай. Часто требуется найти номер тенанта по номеру телефона звонившего.

**Comment by alex-kukhtin** [comment]
Набирай только цифры. Без пробелов, скобок и тире.
А вообще - сделаю.

**Comment by alex-kukhtin** [comment]
v 7501
