### ISSUE TITLE
Банк. Платежи. Все ошибки

### ISSUE THREAD

**Issue by alex-kukhtin** [a2develop/bugTracker#851]
20. Переформулировать названия операций. Нифига не понятно.

**Comment by Anestezia** [comment]
4. Может сделать кнопку "Очистити" внутри платежки, чтоб не путаться в шаблонах?
_**Это еще актуально ?**_

Ладно, пусть остается как есть. Возможно это можно будет использовать как своеобразный инструмент заполнения.

(с возможностью копирования (добавления) строки и добавления второго документа-основания)
_**Пока решли отказаться от связи одного платежа к нескольким счетам. Платеж делим на две части.**_



5. **ИСПРАВИЛ** Странное поле рядом с номером в ворде валютной платежки 
![image](https://user-images.githubusercontent.com/42540074/55956641-15e48800-5c6d-11e9-9d21-aa45ca67991c.png)

**Comment by AndriyNesterenya** [comment]
22. Слегка напрягает "Є ПОМИЛКИ!" на каждой строке свежезагруженной выписки. Это не ошибки есть, а незаполненные поля, до которых у юзера еще руки не дошли

**Comment by AndriyNesterenya** [comment]
26. Хочется продублировать кнопку провести/отменить проводку в нижней строке вместе с сохранением и отменой. 
Нынешнее расположение удобно, если знаешь где эта кнопка и возишься между выбором операции и скроллом строк выписки.
В остальных случаях хочется кногпку в привычном месте.

27. А цифирь возде "начала дня" всегда ноль?
![image](https://user-images.githubusercontent.com/38098758/54717051-f374b880-4b5f-11e9-9208-67aa2985e2b1.png)

**Comment by AndriyNesterenya** [comment]
28. Слегка гуляет верстка, а именно меняется ширина поля Операция  при наведении курсора и появлении подсказки.

**Comment by AndriyNesterenya** [comment]
29. Дико неудобная пажинация. Постоянно теряются верхние или нижние строки, которые не влазят в экран и до которых нужно скроллить.
_**Увеличена высота списка**_

**Comment by Anestezia** [comment]
> 1. Хочется продублировать кнопку провести/отменить проводку в нижней строке вместе с сохранением и отменой.
>    Нынешнее расположение удобно, если знаешь где эта кнопка и возишься между выбором операции и скроллом строк выписки.
>    В остальных случаях хочется кногпку в привычном месте.
> 2. А цифирь возде "начала дня" всегда ноль?
>    ![image](https://user-images.githubusercontent.com/38098758/54717051-f374b880-4b5f-11e9-9208-67aa2985e2b1.png)

Поле "Сума Прибутку" мне кажется юридически не правильным, как прибыль это поступление еще никто не признал на этом этапе. Может Надходження?

**Comment by AlexeyTishkin** [comment]
> Поле "Сума Прибутку" мне кажется юридически не правильным, как прибыль это поступление еще никто не признал на этом этапе. Может Надходження?

Прибуток - не прибыль, а приход (к примеру: Прибутковий касовий ордер).
Можно, наверное, заменить на Наджодження....
В клиент-банках как обычно пишут ?

**Comment by alex-kukhtin** [comment]
Некрасивая разметка
![image](https://user-images.githubusercontent.com/26379138/55241301-76260380-5243-11e9-9576-1bf0520fe7de.png)

**Comment by AndriyNesterenya** [comment]
Пришла мысля, что на общем списке выписок хорошо бы иметь или селектор счета или хотя бы фильтр по счетам.
Если счетов несколько, да еще и в разных банках - в общей куче сложно разобраться.

**Comment by AlexeyTishkin** [comment]
> А то у нас внутри конкретной записи выбор счета есть

Это не тот счет, это не наш, а контрагента счет. Наш в одном месте в шапке.

**Comment by GalinaLuk** [comment]
Я для Васи Кодикова описываю кейс и приходится проводить и распроводить одну и ту же платежку по нескольку раз. Столкнулась с одной особенностью: в разделе "бухгалтерия", "платежи" создала и провела платежку (оплата от покупателя) без номера. А когда ее же открыла из раздела "продажи", то поле проведенного документа с номером было с красной обводкой. Распровела (для своих целей), но не смогла провести снова,  пришлось вводить номер входящий, красное поле не давало провести. Надо было бы, чтобы уже либо везде красное, либо везде позволяло проводить без номера

**Comment by AlexeyTishkin** [comment]
> А когда ее же открыла из раздела "продажи"

Наверняка она открылась в старом интерфейсе, т.е. в форме ?
Надо составить перечень мест, где Платежные поручения и Кассовые ордера открываются не в диалоге.

**Comment by GalinaLuk** [comment]
Еще работая над кейсом Васи Кодикова пришла такая идея: что если после ввода основания к платежу и после проведения - это основание появлялось бы в активной форме для ввода документов. Например, если мы ставим договор основанием, то после проведения, можно увидеть в правой колонке, что на основании договора можно ввести  - 1. акт. 2. счет. 3. отгрузку  ну и т.д.

**Comment by GalinaLuk** [comment]
Еще работая над кейсом Васи Кодикова пришла такая идея: что если после ввода основания к платежу и после проведения - это основание появлялось бы в активной форме для ввода документов. Например, если мы ставим договор основанием, то после проведения, можно увидеть в правой колонке, что на основании договора можно ввести - 1. акт. 2. счет. 3. отгрузку ну и т.д.

**Comment by GalinaLuk** [comment]
> > А когда ее же открыла из раздела "продажи"
> 
> Наверняка она открылась в старом интерфейсе, т.е. в форме ?
> Надо составить перечень мест, где Платежные поручения и Кассовые ордера открываются не в диалоге.

Да, я это делаю на Beta, потому что Дев мне нужен для текущего тестирования

**Comment by GalinaLuk** [comment]
Закрыла issue случайно, постараюсь больше такого не повторить

**Comment by AlexeyTishkin** [comment]
> Да, я это делаю на Beta, потому что Дев мне нужен для текущего тестирования

Если где-то открывается в старом интерфейсе, то:
1. Проверяем это место на Дев.
2. Если на Дев тоже старый - пишем сюда это место.

**Comment by AndriyNesterenya** [comment]
Просят добавить список выписок (для контроля дебета/кредита) в 
[[https://service.bookkeeper.kiev.ua/accounting/bank_accounts]](url)
![image](https://user-images.githubusercontent.com/38098758/56676298-aa67d500-66c6-11e9-97b3-56fb034c6fbb.png)

Народу гораздо понятнее искать выписки в счетах, а не в платежах

**Comment by AndriyNesterenya** [comment]
Про список счетов - сюда же?
Хочется какой-то признак на не оплаченные или не полностью оплаченные счета.
На главной мы такого рода инфу показываем (не до конца оплаченные счета).

У нас сейчас при появлении проплат возле счета появляется плюсик, открывающий список связанных оплат.

А просят добавить наглядности в сам список, чтобы сразу глазами было видно где не оплаченные или не полностью оплаченные счета.

**Comment by AlexeyTishkin** [comment]
> Хочется какой-то признак на не оплаченные или не полностью оплаченные счета.

Так есть же. Придбання - Операції (beta)

**Comment by AndriyNesterenya** [comment]
Традиционно не везде копипастятся видимые данные.
Например, при разнесении выписки было бы весьма полезно позволить юзеру малой кровью копировать номер и/или дату счета из назначения платежа, чтобы потом удобнее искать счет в списке.
У нас сейчас можно копипастить из полей внизу, но нельзя из текста в списке платежей
![image](https://user-images.githubusercontent.com/38098758/57107461-bee84500-6d38-11e9-92d7-2bec4842d357.png)
Соответственно нельзя обработать несколько платежей,не выходя из закладки Додатково.
Мелочь, но неприятно.

**Comment by AndriyNesterenya** [comment]
Еще кейсовая задачка про выписки :
Контора продает что-то, например услугу, физлицу.
Физик берет счет, лезет в Приват24 (Айбокс, Монобанк etc.) и платит с личной карты по счету или или идет в отделение банка и платит через кассу.
Соответственно в выписке Плательщиком значится Приват со своим счетом.
Бухгалтер втягивает выписку, руками меняет Плательщика с Привата на соотв Физлицо (которое создано как Інше без ЕДРПОУ и р/с), и от него требуют ввести расчетный счет, которого у такого контрагента нет и не будет.
Народ пока просто пишет номер от фонаря.

Вопрос: 
Можно ли для конкретной ситуации, когда в выписке плательщиком назначается контрагент из категории "Інше", отменить требование обязательного ввода р/с или автоматом подставлять туда что угодно типа 00000000000, чтобы проводилось без лишних бессмысленных действий?

**Comment by AlexeyTishkin** [comment]
> и от него требуют ввести расчетный счет, которого у такого контрагента нет и не будет.

Для входящего платежа р/с не является обязательным.
