### ISSUE TITLE
Операция: приймання-передача ОЗ в операційну оренду - не дає обрати об’єкт

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#852]
может что-то не так делаю....
открываю документ, внутри создаю объект учета - банер, выбираю
![image](https://user-images.githubusercontent.com/38099938/53417949-564eb600-39df-11e9-821c-d0b75220f1e5.png)
но внутрь документа не попадает
![image](https://user-images.githubusercontent.com/38099938/53417972-649cd200-39df-11e9-864d-bd09d9a06c81.png)

**Comment by kattrina-brekhova** [comment]
не получается корректно провести операцию: причем проводка формируется
что происходит:
открываю документ, создаю объект учета, указываю все характеристики
![image](https://user-images.githubusercontent.com/38099938/53494485-8c0aa200-3aa6-11e9-8c61-6a8f04884109.png)

заполняю табличную часть
![image](https://user-images.githubusercontent.com/38099938/53494534-ab093400-3aa6-11e9-9045-0816076a32e2.png)
и при проведении дает такую ошибку
![image](https://user-images.githubusercontent.com/38099938/53494560-b9575000-3aa6-11e9-8df7-790752a45c5b.png)
при этом документ проводится
![image](https://user-images.githubusercontent.com/38099938/53494605-d1c76a80-3aa6-11e9-8151-eb2a73d86ea8.png)

**Comment by htrofymova** [comment]
исправлено
