### ISSUE TITLE
операция Введення в експлуатацію ОЗ - при выборе группы ОЗ, НМА... - ругается, но проводит

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#855]
вот алгоритм проведения
выбираю Транспортные средства
![image](https://user-images.githubusercontent.com/38099938/53477133-b6e00080-3a7c-11e9-8fc7-55d746aefd81.png)

при проведениии ячейку очищает
![image](https://user-images.githubusercontent.com/38099938/53477256-f870ab80-3a7c-11e9-8410-115c6eb6c2e4.png)
а потом выделяет красным "Группа не отвечает типу объекта
![image](https://user-images.githubusercontent.com/38099938/53477159-c4958600-3a7c-11e9-87c5-540708decdfb.png)
но проводит, проводки формирует

акк тот же - логин test@3.ua
пароль behappy1204

**Comment by htrofymova** [comment]
исправлено
