### ISSUE TITLE
Операция Внесення ОЗ до статутного фонду - облік інвестора - смущают две нижние проводки

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#856]
проводки 5 и 6:
смущает, что дважды за кредитом задействован счет 712

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/53489378-b5710100-3a99-11e9-962f-e8aab0139082.png)

**Comment by kattrina-brekhova** [comment]
нашла альтернативный вариант формирования проводок
http://www.ug.com.ua/ukr/articles?iid=91

**Comment by htrofymova** [comment]
исправлено
