### ISSUE TITLE
Не работает сброс фильтра по выставленной дате группирования документов (раздел Кадры, Персонал)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#859]
выставила 2 фильтра по названию операции и дате, нашла необходимые доки, хочу сбросить, жму "скасувати", но без изменений, полный перечень документов не отражает
![image](https://user-images.githubusercontent.com/38099938/53747961-096e5200-3ead-11e9-8749-ad5cef581ca2.png)
по факту вот так - после того как вышла с пунтка меню и перезагрузила страницу
![image](https://user-images.githubusercontent.com/38099938/53748095-50f4de00-3ead-11e9-80df-6f8eba8d0ddc.png)

**Comment by Illya-Lykhachov** [comment]
уже нет такого раздела
