### ISSUE TITLE
Разрешить ручную корректировку суммы аванса

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#861]
Можно в аванс добавить колонку типа аванс по отпуску, в которой ставить количество дней вручную, чтоб можно было с чистой совестью отработанные дни поставить 0.
Сумма аванса в этом случае будет вводиться руками.
Решение: сумма аванса либо расчётная из кол-ва отработанных дней, либо руками, в случае отпуска.
А в конце месяца как обычно рассчитываются уже четко отпускные.

**Comment by Illya-Lykhachov** [comment]
Пока только в зарплате (beta)

**Comment by Anestezia** [comment]
Есть ручной ввод суммы, все работает. Нам бы это в хелпе и в что нового хорошо и доходчиво объяснить, чтоб люди знали, что это за инструмент.
И еще в основную ЗП добавить, в персонал, так как это нужно было человеку, который только в персонале может работать.

**Comment by Illya-Lykhachov** [comment]
Ещё добавление и удаление строк

**Comment by Illya-Lykhachov** [comment]
Теперь и в персонале
