### ISSUE TITLE
При импорте контрагента ФОПа создать перенос кода ИНН при постановке галочки и разрешить редактировать это поле

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#862]
Допустим при импорте контрагента человек не продублировал код ИНН, чтоб система его как плательщика НДС идентифицировала, или, сначала он был неплательщик, а потом стал им, что бывает и уже на ошибку пользователя никак не сопрешь. Получается, что если таким импортированным контрагентам потом попытаться поставить галочку Плательщик НДС, то номер туда не переносится и в Налоговые не подтягивается. Такие налоговые уже не провести.

![image](https://user-images.githubusercontent.com/42540074/53802715-31ac8e00-3f4b-11e9-9c1f-66391bc75c2f.png)
вручную для редактирования поле закрыто.

**Comment by Anestezia** [comment]
Желательно, чтобы поле это стало редактируемым для тех, кто уже позаводил контрагентов, которые участвуют в хоз. деятельности. Чтоб не удалять всю базу, а просто исправить, у кого налоговые накладные не проводятся и кому выдается ошибка, что нет ИНН. Увидел, тут же зашел в свойства контрагента и перекопировал верхний номер.

**Comment by AlexeyTishkin** [comment]
> Чтоб не удалять всю базу, а просто исправить

Для этого сейчас достаточно "передернуть" код ІПН.

**Comment by Anestezia** [comment]
То есть полностью удалить и заново вставить. Потом установить галочку Платник ПДВ и тогда номер появляется и в нижней части настроек. 
1. Неочевидно, вот бы всплывающую подсказку на этот случай.
2. Это уже готовое решение или временное, и будет еще что-то добавляться? Если готовое, я закрываю ишью, а у кого такие проблемы будут, в службе поддержки на словах объясню что делать.

**Comment by AlexeyTishkin** [comment]
Это именно сейчас.
Вначале исправим импорт (думаю, что к следующему релизу) и обновим у существующих проблемных контрагентов.

**Comment by AlexeyTishkin** [comment]
Исправил.
