### ISSUE TITLE
отчеты: Фінансовий звіт суб’єкта малого підприємництва  и Спрощений фінансовий звіт суб’єкта малого підприємництва внизу шапок указаны одинаковое название форм: 1мс и 2 мс

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#865]
![image](https://user-images.githubusercontent.com/38099938/54115508-3d89cb80-43f5-11e9-87b9-0101b6c47aad.png)
![image](https://user-images.githubusercontent.com/38099938/54115524-467a9d00-43f5-11e9-95a9-2692f2194c77.png)

правильно:
— Фінансовий звіт суб’єкта малого підприємництва (форма № 1-м и 2-м;

— Спрощений фінансовий звіт суб’єкта малого підприємництва — форма № 1-мс и форма № 2-мс

**Comment by AlexeyTishkin** [comment]
Исправил
