### ISSUE TITLE
1 ДФ при подстановке новой строки сделать кнопку выбора из Контрагентов и Физ.лиц

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#871]
Чтоб туда код подтягивался их. 
Информативно фирмы, работающие с ФОПами должны в нем указывать кому и сколько заплатили за период. 
У нас это автоматически не подтягивается, только вручную, плюс полностью через вбивание кодов.  У кого таких много, им неудобно. Можно ли для начала хотя бы сделать возможным подбор из списка контрагентов ФОПов и Физлиц, в добавочных пустых строках отчета? Суммы и коды дохода пусть пока сами подставляют.

А в дальнейшем выяснить, действительно ли все поголовно должны указывать там любые сделки с ФОПами (даже не ГПХ) и автоматически их тоже подтягивать. Может через диалог (галочку), типа "указать сделки с ФОП"

**Comment by Illya-Lykhachov** [comment]
[Здесь решение](https://github.com/a2develop/bugTracker/issues/985)
