### ISSUE TITLE
Строка 6 Декларации на прибыль при отрицательном значении не должна заполняться

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#872]
06 | (Строка 04 - строка 05 ПЗ) х 18 % : 100 %.Будьте внимательны: значение этой строки должно быть только положительным. При отрицательной или равной нулю разнице строк 04 и 05 строку 06 не заполняют
-- | --

![image](https://user-images.githubusercontent.com/42540074/54293242-44147080-45b8-11e9-96f3-3929521a1a22.png)

17 | Строка 06 + строка 08 + строка 10 + строка 12 + строка 15 - строка 16 ЗП.Для обычных плательщиков эта формула трансформируется в разницу строк 06 и 16 ЗП.Нюанс: даже при общем убытке за отчетный период (значение строки 04 отрицательное) у плательщика может возникнуть обязательство по уплате налога . Это возможно, если убыток по льготируемой деятельности превысил прибыль от нельготируемых видов деятельности (т. е. если отрицательное значение строки 05 больше значения строки 04).В общем случае показатель строки 17 должен быть положительным
![image](https://user-images.githubusercontent.com/42540074/54293292-60181200-45b8-11e9-837e-5d60d3c62b0f.png)

19*** | Годовые плательщики переносят сюда показатель из строки 17 декларации. При этом у них это значение может быть только положительным.Квартальные плательщики указывают здесь разницу между значениями строк 17 и 18 декларации. У них значение строки 19 может быть как положительным, так и отрицательным. При этом положительное значение показывает сумму налога, которую предприятие должно уплатить в бюджет по итогам отчетного периода. Именно эту сумму отражает в бухучете проводкой: Дт 98 — Кт 641 / налог на прибыль.Отрицательное же значение может возникнуть у квартального плательщика в случае, когда налоговое обязательство за год оказалось меньше обязательства за 3 квартала 2017 года. Оно сигнализирует о наличии переплаты

**Comment by AlexeyTishkin** [comment]
Изменил расчет.
