### ISSUE TITLE
Добавить 903 и 902 счет в акты услуг

### ISSUE THREAD

**Issue by mik-man** [a2develop/bugTracker#873]
1.Основною діяльністю мого підприємства є надання бухгалтерських та консультаційних послуг.
Для виконання безпосередньої діяльності  наше підприємство придбаває у інших підприємств юридичні, консультаційні або інші послуги (іншими словами - Субпідрядні  послуги), які прямо відносяться на собівартість реалізованих послуг.
При проведенні акта виконаних робіт від таких постачальників послуг доречно було б робити проводку:
Дт 903 - Кт 631
2. Моє підприємство обслуговує підприємство, яке займається продажем садової техніки. Я їх теж перевела на Вашу програму - ТОВ "ХЕЧТ УКРАЇНА". 
Приклад стосується їх діяльності.
Крок 1: Відвантажили товар (транспортуванням, погрузкою і розгрузкою займається стороння фірма)
Крок 2: Після відвантаження товару, на наступний день, ця транспортна фірма виставляє рахунок на послуги. (Раніше виставити рахунок вона не може, тому що вартість їх послуг залежить від кількості годин і кілометражу)
Фактично на 281 рахунку товару вже немає, тому ми не можемо збільшити собівартість товару на суму цих послуг.
Але це витрати, які належать до собівартості проданого товару.
Тому єдиним виходом віднести на собівартість проданого товару зробити проводки при проведення акту виконаних робіт
Д-т 902, К-т 631

**Comment by AlexeyTishkin** [comment]
Добавил.
