### ISSUE TITLE
Улучшение пользовательского интерфейса: варианты, пожелания.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#874]
![image](https://user-images.githubusercontent.com/42540074/54437178-c0d05780-473c-11e9-89c7-01b9d2a7b468.png)

1.Оказалось неочевидным, что это еще дополнительная кнопка с другим функционалом (зеленая квадратная со стрелочкой вниз). Также было пожелание, что удобнее была бы всплывающая при наведении подсказка, как при наведении на функцию Експорта списка.

2.  Поставила в тупик колонка "Дії" в списке операций, Было бы понятнее, если бы там было подписано Дії з документом, або Дії з елементом

3.  
![image](https://user-images.githubusercontent.com/42540074/54437431-46540780-473d-11e9-9e12-937ec5c06f4d.png)

Выход из информации по контрагенту к общему списку контрагентов так и не удалось найти. Может его подписать "До списку контрагентів/об'єктів"?

**Comment by Illya-Lykhachov** [comment]
Нужно привести к единообразному поведению списки документов всех разделов.
Моё предложение (работающий вариант в "Зарплатном калькуляторе") - использовать следующий принцип:
 - двойной клик - открывает документ (переходим в другой контекст);
 - одинарный клик - всплывает окно с подсказкой, расшифровкой и т.п. (остаёмся в текущем контексте).
Избыточные (и неявные) ссылки в номерах документов или датах только приводят к лишним открытиям при **нечаянных** кликах. Список превращается в "минное поле" (как бы чего лишнего не нажать).

**Comment by alex-kukhtin** [comment]
Двойной клик на планшете? Будешь народу объяснять.

**Comment by Illya-Lykhachov** [comment]
> Двойной клик на планшете?

А в чём проблема? Планшеты поддерживают двойной клик. Для непонятливых есть однокликовая кнопка в колонке "Действия".

**Comment by htrofymova** [comment]
Согласна, что нужно привести к нормальному, не перегруженному поведению. Но двойной клик не нравится в принципе.

**Comment by alex-kukhtin** [comment]
Закрывайте этот issue. 
Только глаза мозолит. Все равно никто ничего делать из этого не будет.
