### ISSUE TITLE
Вывести в НН из свойств контрагента поле "Страна" для нерезидента

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#876]
Зазначається найменування (П. І. Б.) нерезидента та через кому — країна, в якій зареєстрований продавець (нерезидент) ( п. 12 Порядку № 1307).
Найменування нерезидента зазначається державною (українською) мовою, а в разі неможливості перекладу допускається зазначати найменування нерезидента іноземною мовою (див. консультацію із БЗ, підкатегорія 101.17)
И чтоб подтягивалось через запятую от названия в определенной операции по НДС.

**Comment by AlexeyTishkin** [comment]
В свойствах контрагента страна уже есть.
Только в НН надо выводить...

**Comment by AlexeyTishkin** [comment]
Сделал.
