### ISSUE TITLE
Таможенная декларация. Исправить отображение инвойса в подборе.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#879]
При заполнении митной декларации выбираю инвойс из списка, у меня в списке их два. выбрала один, подставился номер и дата, и табличные значения тоже, выбрала другой — подставилось слово инвойс и табличное значение.
![image](https://user-images.githubusercontent.com/42540074/54743428-cb6f6e80-4bcc-11e9-8f3e-f004de375d3d.png)
![image](https://user-images.githubusercontent.com/42540074/54743449-d3c7a980-4bcc-11e9-8a09-e8724a5bb014.png)
Теперь клацаю между ними, табличные значения меняются, номер и дата уже ни в одном не подставляются. После проведения тоже.

**Comment by AlexeyTishkin** [comment]
Исправил.
