### ISSUE TITLE
Нужен перевод сообщений об ошибке при регистрации

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#88]
Пора переводить сообщения при регистрации :
![image](https://user-images.githubusercontent.com/38098758/39059132-60d87d18-44c6-11e8-95b0-dfc586b4dada.png)

**Comment by alex-kukhtin** [comment]
Fixed in 7162

**Comment by nik-man** [comment]
Андрей, проверь пожалуйста и закрой, если все ок.
