### ISSUE TITLE
Платежка. При копировании возникает непроведенный дубль

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#880]
Например, я создала одну платежку по налогам, провела, скопировала, провела. В журнале платежек три, две проведенных и одна непроведенная. Я обновляю, непроведенная исчезает.
![image](https://user-images.githubusercontent.com/42540074/54748001-12fbf780-4bd9-11e9-93a4-b2b285d76503.png)
Это не только по налогам, по остальным и небюджетным платежам тоже.

**Comment by alex-kukhtin** [comment]
fixed

**Comment by Anestezia** [comment]
Дубля нет, но и у созданного и проведенного документа в списке операций нет отметки о проведении
![image](https://user-images.githubusercontent.com/42540074/54815295-50748980-4c9a-11e9-9c42-aab65d1f19c1.png)
![image](https://user-images.githubusercontent.com/42540074/54815320-6124ff80-4c9a-11e9-80ee-5e653ae0da53.png)
Помогает только кнопка Обновить. Можно ли автоматически обновлять?

**Comment by alex-kukhtin** [comment]
Подправил. Все должно работать правильно.
