### ISSUE TITLE
Инструкция при импорте контрагентов списком. Утверждаем текст.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#881]
![image](https://user-images.githubusercontent.com/42540074/54749048-10e76800-4bdc-11e9-984c-4d83e4b75975.png)
Для коректного внесення даних в довідник:
1. Завантажте зразок файлу на комп’ютер;
2. Відкрийте вказаний файл;
3. Заповніть даними ваших контрагентів за порядком, наведеним у файлі зразку, та збережіть;
4. Завантажте цей файл в сервіс. Перетягніть у вказане поле або клацніть на цьому полі, щоб обрати зі списку файлів на комп’ютері.

**Comment by AlexeyTishkin** [comment]
Изменил.
