### ISSUE TITLE
Вопросы по Бета-операции Перемещение и списку этих операций

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#882]
1. В самой операции не ищет при наборе с клавиатуры Основной Склад, остальные ищет.
![image](https://user-images.githubusercontent.com/42540074/54749327-dfbb6780-4bdc-11e9-91f1-c2328adb287b.png)
Тут же видно справа увеличено поле. если так надо, то ок.
2. Режим копирования недоступен
![image](https://user-images.githubusercontent.com/42540074/54749475-53f60b00-4bdd-11e9-8089-55358259e496.png)
3. Сначала в списке ставит номер документа 0, после разных действий через кнопку Дії, номер появляется
![image](https://user-images.githubusercontent.com/42540074/54749560-961f4c80-4bdd-11e9-8f56-325fecdedab0.png)
4. Сами операции по названию щелкнув открыть нельзя, не активны (черные. не синие), не только эту, а все в списке. А перемещение имеет разные варианты Действия, отличные от остальных документов. (Изменить и удалить)
5. Когда я выбираю позицию, раньше показывало красным, если ее не было на остатке, сейчас вроде как на остатке есть нужное количество, красного поля нет, провожу, но при проведении на пол секунды это поле мигает красным. Или вот так
![image](https://user-images.githubusercontent.com/42540074/54750421-455d2300-4be0-11e9-9bae-aad5cddb0ec6.png)
6. Если открывать документ через кнопки Действий, то не открывается
![image](https://user-images.githubusercontent.com/42540074/54750448-632a8800-4be0-11e9-944d-97c50da1fe4f.png)
7. Залишок 1 шт. 
![image](https://user-images.githubusercontent.com/42540074/54751688-69226800-4be4-11e9-8178-03995da44618.png)
А тут залишок 5 шт.
![image](https://user-images.githubusercontent.com/42540074/54751719-7b9ca180-4be4-11e9-8b52-deaf560366b2.png)
Скорее всего было групповое введение в эксплуатацию и подбор воспринимает это как одну позицию, а склад, как несколько. Конфликт интересов)
8. Разные функции действий с документом: 
После проведения "перемещения" в списке операций в колонке Дії  три символа: открыть, копировать, удалить.
![image](https://user-images.githubusercontent.com/42540074/54752027-4f355500-4be5-11e9-90e3-b8a5fcf19860.png)
Нажимаю на открыть, потому что двойным щелчком на названии документа не открывает.
![image](https://user-images.githubusercontent.com/42540074/54751904-ffef2480-4be4-11e9-87a0-a489a5d3e745.png)
Вернула окно назад. Символов убавилось в Действиях.
![image](https://user-images.githubusercontent.com/42540074/54751969-27de8800-4be5-11e9-8e47-51556a945fc6.png)

**Comment by htrofymova** [comment]
Исправлено и учтены пожелания. Просьба - проверить.

**Comment by Anestezia** [comment]
1. Перемещение объектов, введенных группой теперь лучше, сумму общую сохраняет, сколько бы ни ставил количество, например, у меня 10 ед. я ввела 2, документ провелся. на печати 2 шт, из склада МОЛ вообще эта позиция ушла, сумма тоже за все 10 снялась.  Может можно сделать запрет ввода другого количества (защита от дурака)? 
2. Проведенный документ идет вниз списка операций до обновления страницы.

По предыдущим моментам - все ок.
