### ISSUE TITLE
Акт с материалами - ПН на основании, позиции теряют порядок, указанный ранее

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#883]
![image](https://user-images.githubusercontent.com/42540074/54762591-15704880-4bfd-11e9-9274-3c8a2a7844ad.png)
в акте так, а в НН так, и людям неудобно сравнивать, если хотят проверить, все ли строки внеслись или где-то ошибка и сумма не идет.
![image](https://user-images.githubusercontent.com/42540074/54762688-3df84280-4bfd-11e9-9a9d-ec519e9e2d66.png)
Системы сортировки не увидели.

**Comment by AlexeyTishkin** [comment]
Исправил.
