### ISSUE TITLE
Некорректная передача цен из Акта с материалами в НН

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#884]
![image](https://user-images.githubusercontent.com/42540074/54814564-b19b5d80-4c98-11e9-9f5f-b3505ef7978f.png)
![image](https://user-images.githubusercontent.com/42540074/54814584-b9f39880-4c98-11e9-9bc9-2a42912cc94d.png)
І ще один момент: програма самостійно змінює цінй постачання одиниці товару/послуги в податковій накладній, додаючи числа після коми ( замість 191.67 ставить 191.675 або 191,6667).Такого не повинно бути.
В акті ціни вносяться без ПДВ.
Зверніть увагу, наприклад: рядок 1 в акті і рядок 1 в нодатковій накладній; рядок 2 в акті і рядок 4 в податковій накладній; рядок 3 в акті і рядок 5 в ПН і т.д....

**Comment by AlexeyTishkin** [comment]
Изменил механизм создания НН.
