### ISSUE TITLE
СРОЧНО!!! Добавить кнопки "З ПДВ" та "ПДВ в т.ч." в Исходящий счет и Накладную (Акт услуг)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#885]
Вот как здесь во входящих! 
![image](https://user-images.githubusercontent.com/42540074/54814990-8e24e280-4c99-11e9-8129-3030cf347ceb.png)

**Comment by AlexeyTishkin** [comment]
Добавил.
