### ISSUE TITLE
Расходная накладная прошлым числом не анализирует возврат товара будущим числом.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#888]
1.Я импортнула партию товара 01.03., потом ее всю продала 25.03. 
2.Дальше клиент мне вернул 26.03 по 10 единиц в двух позициях. 
3.Потом я создала Реализацию запасов на эти две позиции по 10 единиц и спокойно ее провела, так как на складе они были. Только прикол в том, что провела вторую реализацию я 25.03, а на склад товар попал по факту 26.03.

Во время подбора товара отображается список объектов учета текущей датой с остатками, без понимания, что на прошлую дату (дату составления Реализации запасов) этого товара еще не было на складе.
![image](https://user-images.githubusercontent.com/42540074/54985774-22ed5000-4fba-11e9-988c-1d39011a7c2e.png)

**Comment by AlexeyTishkin** [comment]
Исправил.
