### ISSUE TITLE
операция "виготовлення ОЗ": в таблице документа "материалы" не видит список всех объектов учета

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#889]
![image](https://user-images.githubusercontent.com/38099938/55060932-46c49a80-507b-11e9-894f-ea48f422c544.png)
на остатке имеются различные материалы
![image](https://user-images.githubusercontent.com/38099938/55061024-72478500-507b-11e9-9d5c-84e9f3f013ff.png)
то же самое касается таблицы "расходы по монтажу", не выводит в документ сохраненные типы услуг
![image](https://user-images.githubusercontent.com/38099938/55061129-a7ec6e00-507b-11e9-8dd4-81b4f9660e44.png)

**Comment by htrofymova** [comment]
Материалы и услуги должны быть на  остатке: 152-го - для основных средств (10 счет), 153-го - для малоценных необоротных активов (11 счет) или 154-го - для нематериальных активов (12 счет).

**Comment by kattrina-brekhova** [comment]
вопрос, касаемый отнесения на 153 и 154
например, у меня есть запасы, которые я могу актом списания отнести на 152 счет 
![image](https://user-images.githubusercontent.com/38099938/55237335-9b624400-523a-11e9-9d2e-cbf3087c2ab7.png)

и отразить на в акте изготовления
![image](https://user-images.githubusercontent.com/38099938/55237268-740b7700-523a-11e9-947b-59c832d211d6.png)

следуя правилу что для изготовления малоценных необоротных активов или нематериальных активов я не могу использовать материалы с 152 счета, как мне списать на 153 или 154 - если это не предполагает акт списания

**Comment by kattrina-brekhova** [comment]
и насколько я поняла этим документом можно создать только ОС и другие необоротные материальные активы?
остальные не предполагаются?
![image](https://user-images.githubusercontent.com/38099938/55237874-cb5e1700-523b-11e9-8ef3-5d20ae301308.png)
