### ISSUE TITLE
Збільшення собівартості придбаного товару при імпорті.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#890]
Приклад 1.
Отримано товар по ГДТ
Нараховані витрати за транспортні перевезення за межами України і по Україні 
Оплачені послуги митного терміналу
оплачено погрузочно-розгрузочні роботи
нарахована зарплата експедитору
Все це йде на собівартість товару, збільшує 281 рахунок, а не лягає на витрати поточного періоду.
Якщо ми залишим у витратах поточного періоду, то податкова нам зніме ці витрати і донарахує податок на прибуток.
Це, звичайно, в тому випадку якщо товар не реалізовано на звітну дату.

Надаю 2 приклад по імпорту зі збільшення собівартості придбаного товару.
 Резидент отримує товар від нерезидента товар. Документ - митна декларація, а саме:
                     1. Дровокол електричний  HECHT6120 - 44шт  по ціні 100 дол. на суму 4400 дол.
                     2. Дровокол електричний  HECHT6160 - 5шт по ціні 120 дол. на суму 600 дол.
                     3. Дровокол електричний  HECHT6180 - 4шт. по ціні 140 дол. на суму 560 дол.
                                           Загальна сума = 5560 дол.США (Проводки Дт 281 - Кт 632)  ДОКУМЕНТ - МИТНА ДЕКЛАРАЦІЯ
                                            Мито =9400 грн (Проводки Дт 281 - Кт 377), ДОКУМЕНТ - МИТНА ДЕКЛАРАЦІЯ
                                            Вартість перевезення до кордону з Україною = 8000 грн (Проводки Дт 281 Кт 631), ДОКУМЕНТ - АКТ виконаних  робіт, довідка транспортних послуг, яка додається до митної декларації
                                            Послуги митного брокера = 5000 грн. (Проводки Дт 281- Кт 631 або 685), ДОКУМЕНТ - АКТ виконаних  робіт
                                            ПДВ= 34000 (проводки Дт 641 - Кт 377), ДОКУМЕНТ - МИТНА ДЕКЛАРАЦІЯ
Код УКТ ЗЕД у всього товару однаковий, тому мито можна ввести однією сумою в митній декларації, яка пропорційно розподіляється по всьому товару.
По такому ж принципу розподіляється вартість перевезення та послуги митного брокера.
Збільшення собівартості придбаного товару на додаткові витрати застосовується не тільки при імпорті товару, але й при купівлі ТМЦ на території України.

**Comment by AlexeyTishkin** [comment]
Сделал.
