### ISSUE TITLE
Раздел "Каса" - новый интерфейс: операция "пополнение статутного капитала" - в самом документе автоматически ставит галочку "с НДС", проводку по НДС не формирует

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#892]
![image](https://user-images.githubusercontent.com/38099938/55233923-97cabf00-5232-11e9-9d0f-03a41fa94539.png)

в печатной форме документа почему-то не проставляется кореспондирующий счет 46
![image](https://user-images.githubusercontent.com/38099938/55233895-871a4900-5232-11e9-9498-7728fbcfd334.png)

**Comment by htrofymova** [comment]
исправлено. А проводки по НДС и не должно быть, вне зависимости от "птички".
