### ISSUE TITLE
Выписка по API - при повторном импорте ранее проведенной выписки не показывает признак Проведено

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#893]
Затягивал собственную выписку за 1 квартал (часть выписок уже была разнесена). 
Период выбрал c запасом  - "Предыдущий квартал". 
Вытащилось все гладко, написало где повтор, а где новое, но в списке выписок все ранее проведенные выписки оказались без признака Проведено.
Хотя внутри выписок все ОК, строки помечены соответственно состоянию

![image](https://user-images.githubusercontent.com/38098758/55344897-4b43e580-54b7-11e9-81c2-d3166c204aae.png)

На картинке в выписке одна строка и она проведена.
Признак появляется, если перепровести выписку.

И верните плиз возможность распровести всю выписку и провести всю выписку одним нажатием.
Гораздо удобнее пройтись по списку, правильно расставить операции по строкам и одним махом все провести.
Ну и в случае ошибок и косяков распроводить удобно весь документ сразу.

**Comment by AndriyNesterenya** [comment]
Плюс очень неудобно получается, когда при проведеннии строки курсор / активная строка  прыгает на верхнюю строчку выписки.
Каждый раз скроллить вниз и искать нужную строку задалбывает жутко. 
Пока платежей 2-3 еще терпимо, но если больше - чистый стресс.

**Comment by AndriyNesterenya** [comment]
PS если в выписке несколько строк - пометка появляется при перепроведении хотя бы одной строки.

**Comment by AlexeyTishkin** [comment]
Исправил.

**Comment by AndriyNesterenya** [comment]
Еще один мелкий косяк там же.
Ситуация.
Утром получил и разнес выписку.
За день сделал еще несколько операций.
Снова (в тот же день) получил выписку - в выписке за сегодня появились непроведенные строки, а весь день все еще маркируется как проведенный.
