### ISSUE TITLE
[Верстка] Мелкий косяк в таблице отчета по единому налогу

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#894]
В отчете по единому единого налогу в списке КВЕД правая граница таблицы дублируется.

![image](https://user-images.githubusercontent.com/38098758/55346902-39187600-54bc-11e9-8083-b11cc42573fb.png)

**Comment by AlexeyTishkin** [comment]
Это в каком ?
В F0103306 - исправил.

**Comment by AndriyNesterenya** [comment]
А еще там кнопки печати теперь нету.
Отправить в сонату можно, в XML сохранить можно, а напечатать - нельзя.

**Comment by AlexeyTishkin** [comment]
> А еще там кнопки печати теперь нету.

Ее там никогда не было. Как и в остальных фискальных отчетах

**Comment by AndriyNesterenya** [comment]
В смысле считаем, что и не нужно?

**Comment by AlexeyTishkin** [comment]
> В смысле считаем, что и не нужно?

В смысле, что это отдельный большой вопрос...
