### ISSUE TITLE
Мелкий баг в платежках при изменении даты

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#895]
Мелкий баг поймал.

Violation of PRIMARY KEY constraint 'PK_Documents'. Cannot insert duplicate key in object 'a2clientbank.Documents'. The duplicate key value is (134, 35696).

В следующей ситуации : 
Сделал платежку. 
Провел. 
Матюкнулся, что нет кнопки отправки в банк. 
Распровел.
Отправил в банк.
Провел.
Подумал, что лучше бы поставить в платежке завтрашнее число, потому что опердень кончился и лишнюю комиссию на платеж снимут.
Удалил платежку в банке.
Снова распровел платежку в БКПР.
Заменил дату на завтрашнюю.
Нажал кнопку "Отправить в банк" - ошибка.
При этом платежка в банк передается с первоначальной датой.
В БКПР дата изменяется.

**Comment by AndriyNesterenya** [comment]
Та же ситуация при попытке изменить номер.

**Comment by AlexeyTishkin** [comment]
Исправил
