### ISSUE TITLE
Добавить перенос в строку ФИО получателя в расходной накладной.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#897]
Если вдруг юзер вздумает написать полное ФИО - не влезает.

![image](https://user-images.githubusercontent.com/38098758/55507224-dbbd2a00-565f-11e9-9f5f-468201d960d7.png)

На всякий случай нужно вставить перенос

**Comment by AlexeyTishkin** [comment]
Сделал.
