### ISSUE TITLE
Редизайн стартовой страницы сервиса

### ISSUE THREAD

**Issue by MaksymTikhomirov** [a2develop/bugTracker#898]
- явно выделить кнопку создания/редактирования "моей фирмы"
- явно выделить альтернативную кнопку входа в Личный кабинет клиента
- возможно, явно показать состояние лицевого счета клиента и тайминг (остаток триал-периода, остаток оплаченного периода и т.д.)
- явно выделить кнопку/ссылку на общее описание функционала сервиса (возможно, в том числе, и на видеообзор)
- явно выделить кнопку/ссылку на описание процедуры интеграции с П24 (возможно, в том числе, и на видеообзор)
- явно выделить кнопку/ссылку на описание взаимодействия с Сонатой (возможно, в том числе, и на видеообзор)
- добавить окно "задачи" 
- общий косметический редизайн

**Comment by alex-kukhtin** [comment]
![image](https://user-images.githubusercontent.com/26379138/55588131-a551de80-5735-11e9-8bbd-4e6201e65488.png)

**Comment by alex-kukhtin** [comment]
Как может быть на странице десяток "явно выделенных" кнопок?

**Comment by MaksymTikhomirov** [comment]
![image](https://user-images.githubusercontent.com/35782741/55713398-415f3c80-59f9-11e9-9a3d-bdc6b0c64407.png)

**Comment by alex-kukhtin** [comment]
Это к чему?

**Comment by AndriyNesterenya** [comment]
1. При наличии валютных счетов с ненулевыми остатками - показывать их явно в столбик, в нынешнем варианте не влезет с норимальными суммами на 5-6 разрядов.
2. наш нынешний график можно оставлять, но можно спокойно делать ниже процентов на 40 + там же гармонизировать высоту графика и столбцов (при большом остатке на счету и небольших текущих операциях выглядит криво)
3. Хочу где-то там же предупреждалку о сроках сдачи отчетности (заготовка под календарь?).

**Comment by alex-kukhtin** [comment]
1. 5-6 разрядов. Готовишься к победе Зе? :-)
2. Типа не с нуля начинать?
3. Где-то там? Это где. Я полдня убил на то, чтобы эту фигню разместить.  :-( ДумайТЕ!

**Comment by alex-kukhtin** [comment]
Кстати - валютный счет ФОПа (не физлица) не требует ли регистрации в ТПП и открытия ВЭД?

**Comment by MaksymTikhomirov** [comment]
> Кстати - валютный счет ФОПа (не физлица) не требует ли регистрации в ТПП и открытия ВЭД?

Нет

**Comment by GalinaLuk** [comment]
У меня вопрос: Если мы приходуем деньги в кассу от покупателя за заказ, то счет уже не будем указывать? Как будет цепляться аналитика? Даже, если его не будет, то предполагается аналитика по договору, но почему-то развертка стандартных проводок из приходного кассового ордера не показывает и его. А если деньги внесут одной суммой по двум разным заказам?
