### ISSUE TITLE
Новая касса-Отримання цільового фінансування Подправить 

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#899]
1. Не проводится документ
![image](https://user-images.githubusercontent.com/42540074/55564130-e4653d00-56ff-11e9-8ff9-73593a660bda.png)
2. Во внешнем ордере нет в проводке второго счета, в данном случае по кредиту. 
Внутри в проводках есть этот счет. При печати по этой операции также не подставляется корреспондирующий.
3. Список Вид надходжень / Вид видатків не такой, как в старой версии этой операции
![image](https://user-images.githubusercontent.com/42540074/55564422-8422cb00-5700-11e9-8c0e-aaa39cc87959.png)
![image](https://user-images.githubusercontent.com/42540074/55564500-b3d1d300-5700-11e9-9743-235167420eba.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by Anestezia** [comment]
Список все еще не такой как в старой версии и счета по кредиту на вкладке справа Операции -- нет.
![image](https://user-images.githubusercontent.com/42540074/55786102-4933e500-5abc-11e9-8112-d2ae6d94bda9.png)

**Comment by htrofymova** [comment]
исправлено
