### ISSUE TITLE
Платежки новые -Целевое финансирование - Поле Операция - Нет второго счета учета по кредиту

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#901]
Даже если выбрать вид поступления.
Даже если провести документ, этот счет не появляется.
Внутри при нажатии на Показать проводки, эти счета есть. 
![image](https://user-images.githubusercontent.com/42540074/55803065-464beb00-5ae2-11e9-936f-5f0bbc4b59df.png)

**Comment by Anestezia** [comment]
В кассовых ордерах по той же операции такое тоже было, но уже исправлено.

**Comment by AlexeyTishkin** [comment]
Исправил.
