### ISSUE TITLE
Валютная платежка контрагенту-банку. Кнопка создать новый банк!

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#904]
В операции Отримання відсотків в валюті за залишком нет возможности изнутри создать банк-нерезидент, только выбор (да еще и из резидентов).
![image](https://user-images.githubusercontent.com/42540074/55957647-7eccff80-5c6f-11e9-8e6e-23ababb06340.png)

**Comment by Anestezia** [comment]
В выписках вручную то же самое.

**Comment by AlexeyTishkin** [comment]
Сделал.
