### ISSUE TITLE
Авансовый отчет - Выдача денег, нужна выдача частями суммы, на основании отчета.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#907]
Перевитрата видана только один раз, не зависимо от суммы. Я выдала через банк часть суммы, а часть хотела из кассы. Но такой возможности нет ни в старом интерфейсе, ни в новом.

**Comment by htrofymova** [comment]
готово

**Comment by Anestezia** [comment]
На данный момент возможно проведение выплаты из кассы и из банка, но нет автоматического определения остатка задолженности. Т.е. если у меня сумма 30 000,00, и я заплатила 10 000,00 из кассы, 10 000,00 из банка, и дальше нет возможности выплатить еще, например, другой датой (если сразу денег не было)
![image](https://user-images.githubusercontent.com/42540074/57226368-8fc32380-7017-11e9-9d81-c86bb9d18c30.png)
И колонки сумма и дата в правом меню платежей внутри документа авансового пусты.

**Comment by Anestezia** [comment]
Кстати, нет отображения статуса связанного документа, а также дата и сумма. Справа на картинке Перевитрата видана.

**Comment by htrofymova** [comment]
Сделала, чтобы можно было создавать ордера и (или) платежки пока не исчерпается сумма перевитрати/залишку аванса.
Правая табличка - это документы выдачи "ДО" авансового отчета, новые связанные документы не должны там отображаться.
Отображение связанных документов в левой табличке исправила.
