### ISSUE TITLE
Выписки Приват из нового интерфейса - CSV

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#908]
Будем иметь проблему с файловыми выписками Привата у упоротых, которые не хотят настраивать АПИ.
В данный момент корректно работаем с ДБФ из старого интерфейса.
В новом путаем ЕДРПОУ у прихода.

Возникла идея переделаться под CSV новом интерфейсе.

Во вложении - CSV из нового интерфейса для ЕДРПОУ 2730909875

[0000001503106888.1.0.zip](https://github.com/a2develop/bugTracker/files/3088663/0000001503106888.1.0.zip)

**Comment by AlexeyTishkin** [comment]
Сделал.
