### ISSUE TITLE
Bug: Internal Server Error при регистрации (плавающая ошибка)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#91]
Периодически появляется и исчезает ошибка при попытке регистрации.
При возникновении юзер не был залогинен.

![image](https://user-images.githubusercontent.com/38098758/39124457-392f7128-4704-11e8-8bb1-4b257c05b8df.png)

После обновления страницы -  ошибка исчезла и показывает нормальное сообщение об ошибке с теми же данными.

**Comment by AndriyNesterenya** [comment]
ЗЫ не первый раз на такое поведение попадаем - четко отловить пока не получилось.
Наблюдалось 23.04 днем и в пятницу 20.04 вечером.
По легенде никаких работ/обновлений на системе в этот момент не производилось.

**Comment by alex-kukhtin** [comment]
Вроде нашел. Нужно погонять.

**Comment by AndriyNesterenya** [comment]
Вроде бы проблема исчезла, пока повторить не удалось.
Еще погоняем
