### ISSUE TITLE
Создать ТОВАРНО-ТРАНСПОРТНІ НАКЛАДНІ при продажі товарів на основі ВИДАТКОВИХ НАКЛАДНИХ

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#911]

**Comment by AndriyNesterenya** [comment]
Было старое на ту же тему
https://github.com/a2develop/bugTracker/issues/234

**Comment by AndriyNesterenya** [comment]
Последние шевеления мин. Инфраструктуры на тему сабжа
https://mtu.gov.ua/projects/view.php?P=195

**Comment by AlexeyTishkin** [comment]
> Последние шевеления мин. Инфраструктуры на тему сабжа

Там же только проект ?

**Comment by Illya-Lykhachov** [comment]
Отдельный документ (операция)
