### ISSUE TITLE
[Улучшайзинг] Группировка операций в списке при разнесении выписки

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#914]
Хорошо бы в выпадающем списке выбора операций вынести вверх списка наиболее часто используемые операции.
В идеале автоматически, или хотя бы назначить принудительно.
ИМХО (например) для среднестатистического ФОПа в основном используется
- оплата постачальнику/покупцю
- комиссия банка
- списание для личных нужд
+ налоги поквартально
остальное в лучшем случае несколько раз в год, и то не у всех.

**Comment by alex-kukhtin** [comment]
В связи с появлением нового интерфейса, предлагаю просто закрыть это нафиг.
