### ISSUE TITLE
Отделить в валидации проведения по дате Приходные накладные от расходных

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#918]
Партия берется последняя в приходе, и если расходная накладная более ранней датой, она не проводится, хотя на складе товар есть. Выпадает сообщение, что нельзя создать документ предыдущим числом. Последнее движение: и указывается дата последней приходной накладной.

**Comment by AlexeyTishkin** [comment]
Изменил механизм проверки.
