### ISSUE TITLE
Сохранять состояние фильтра по периоду при  переходе между счетами в Бухгалтерия - Рахунки

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#920]
Сохранять состояние фильтра по периоду при  переходе между счетами в Бухгалтерия - Рахунки.

Сейчас при переходе между счетами выбранный период сбрасывается в "Сьогодні"

**Comment by Illya-Lykhachov** [comment]
Глобальный период. При переключении между подразделами надоело менять период. Даже при возврате в предыдущий подраздел он сбрасывается

**Comment by alex-kukhtin** [comment]
Ну так сделай сам. Зачем на меня назначать? Чтобы подвесить на неопределенный срок?
