### ISSUE TITLE
Визуализировать оплаченные/частично оплаченные/не оплаченные вх/исх счета в Придбаннях/Продажах

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#921]
Очень хочется в общем списке выписанных и полученных счетов видеть состояние оплаты не заходя в сам счет.

Предлагаю (чтобы минимизировать геморрой и не переделывать форму) менять цвет фона под суммой счета например по следующей логике:
1. Счет выставлен - красный (как наши ошибки/запреты)
2. Есть частичная оплата - желтый
3. Полностью оплачен - белый, как все остальное.

При этом неоплаченные счета будут бросаться в глазаа, а оплаченные выглядеть как все остальные операции.

**Comment by AlexeyTishkin** [comment]
А чем не нравится визуализация в Придбанні?

**Comment by AndriyNesterenya** [comment]
Ненаглядностью не нравится.
У нас традиционно все выглядит так:
![image](https://user-images.githubusercontent.com/38098758/57030389-2b861580-6c4d-11e9-8d1c-66e5e77e54b5.png)
Т.е. счет с какими-то операциями отличается от неоплаченного/незакрытого только наличием плюсика в левом столбце.
Для того, чтобы узнать, что там вообще происходило - нужно ткнуть мышкой на плюс и смотреть глазами.
По самому списку состояния не видно, на лишние клики уходит время.
Народ просит сделать какую-то индикацию, чтобы прямо по списку счетов (и входящих и исходящих) были видны долги.

**Comment by AlexeyTishkin** [comment]
Операции (beta)

**Comment by AndriyNesterenya** [comment]
Убил полдня на консультации.
Решили, что версия из "Операции (beta)" достаточно информативна и годится
