### ISSUE TITLE
В новом интерфейсе списка документов реализовать отбор по типу операции

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#925]
А.К. : Реестр документов по 631/361 счету с фильтрами Период, Операция, Контрагент, Фрагмент текста.

Возможно, сделать общий реестр документов по каждому разделу, добавить в Звиты и уже внутри этого отчета делать отбор, показывать один тип документа (операции), сразу решится вопрос и с сохранением/распечаткой списка отобранных тут же. 
![image](https://user-images.githubusercontent.com/42540074/57536313-966dd580-734c-11e9-82fb-6d8edc993cdf.png)

**Comment by AlexeyTishkin** [comment]
В отчет "Реестр документов по счету" добавлены фильтры по операции и контрагенту.

**Comment by AlexeyTishkin** [comment]
Есть ли смысл добавлять фильтр по фрагменту текста ?

**Comment by Anestezia** [comment]
Фрагмент текста имелось в виду. чтоб можно было сделать отбор по примечанию, Например, документы менеджера Пети, они разные по операциям, но все его и только его.

**Comment by AlexeyTishkin** [comment]
> Например, документы менеджера Пети

Для этого нужна аналитика "Менеджер", которая вносится в документе, и которая является фильтром по аналогии с Контрагентом.
