### ISSUE TITLE
Реализовать отбор по тексту комментария

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#926]
если менеджеры будут в комментах подписываться, то так можно отбирать и контролировать кто и что делает, хотя бы поверхностно. Или распределять работу по отделу используя наш существующий на данный момент функционал

**Comment by AlexeyTishkin** [comment]
Добавлено в фильтр списка документов в разделах "Бухгалтерія - Рахунки", "Бухгалтерія - Платежі", "Бухгалтерія - Платежі в валюті", "Придбання - Операції (beta)", "Продажі - Операції (beta)".
