### ISSUE TITLE
Ведомость на выплату налички: после применения округления, потом изменить или отменить округления нельзя

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#929]
после округления к 1 - вернуть на исходную нельзя, но можно округлить к 10
после округления к 10 невозможно уменьшить округление

**Comment by kattrina-brekhova** [comment]
вернуть прежние цыфры можно только после нажатия "заповнити". не критично, но сразу не разобраться, можно помучиться, выбирая необходимое

**Comment by alex-kukhtin** [comment]
А как вы себе это представляете?
Как по мне - вполне нормальное поведение.
