### ISSUE TITLE
Выписка Приват через API - не работает с пробелом перед номером счета

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#931]
Ситуация:
Юзер регистрируется и при заполнении реквизитов своей фирмы случайно копирует лишний пробел в начале номера счета.
Например вместо "26005052654617" скопипастил " 26005052654617".

При этом файловая выписка затаскивается нормально.
При попытке настроить обмен по API проверка проходит ОК, но собственно выписка не вытаскивается, от смены периода не зависит.

По-моему проблема решается обрезанием лишних пробелов при вводе в мастере свойств своей фирмы.

**Comment by alex-kukhtin** [comment]
Проверьте, плиз!
