### ISSUE TITLE
Некорректное отображение оплаты через терминал iBox

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#932]
В админке, в разделе "Биллинг-Оплата" некорректно отображается сумма оплаты через терминал iBox. 
Платеж от 18.05.2019 10:56, тенанта №1205 - стоит сумма 0 грн. Хотя в разделе "Биллинг-Пользователи" - стоит корректная сумма 300грн.

**Comment by DenisClone** [comment]
Выяснилось, что ошибка старая и устойчивая, вот ишью от декабря:
https://github.com/a2develop/bugTracker/issues/711

**Comment by DenisClone** [comment]
Ошибка снова повторилась - 22.06.2019

**Comment by DenisClone** [comment]
Up!

**Comment by alex-kukhtin** [comment]
Done in 7552

**Comment by DenisClone** [comment]
В боевой админке не починилось (или не применилось к старым записям), в "Билинг - Оплаты", у тенанта №1205 так и висит "0" по всем платежам.
