### ISSUE TITLE
НА - размер окна диалога Акта введения в эксплуатацию 

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#934]
Кривой размер окна диалога Акта введения в эксплуатацию НА (что с дашбоарда, что классическим способом)

По высоте очень маленькое окно даже на больших экранах
Скроллится добрая половина рабочего поля
![image](https://user-images.githubusercontent.com/38098758/58257318-6295a580-7d79-11e9-924b-bf7ddeec84a2.png)

**Comment by htrofymova** [comment]
исправлено

**Comment by AndriyNesterenya** [comment]
Окно увеличилось, но увеличились и отступы между элемеентами, и получилось еще больше скролла
![image](https://user-images.githubusercontent.com/38098758/58465712-efa57980-8140-11e9-8ca9-048fe178742b.png)

**Comment by htrofymova** [comment]
исправлено
