### ISSUE TITLE
Авансовый отчет: добавить возможность выбирать контрагента Физ.лицо (Інше)

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#938]
Доброго дня. Опишу свою проблему: керівник бере з каси гроші на закупівлю сільськогосподарської продукції у населення. Складає закупівельний акт і згідно нього авансовий звіт. В авансовому звіті не можна вибрати контрагента - фізичну особу лише ФОП. Прибуткова накладна на оприбуткування продукції виписується від фізичної особи. Як провести їй оплату , якщо не можна підтягнути її в авансовий звіт?

или
Там не может быть приходной накладной, закупки сельхозпродукции у населения оформляются Закупочным Актом, по которому и оформляется поступление: дт 201 (281) - кт 685. Задолженность закрываетс Авансовым отчетом подотчетного лица : дт 685 - кт 372. Так как приход и зачет задолженности всегдва один к одному, то и учет по-фамильно на 685 не нужен ( это  ж всех крестьян завети что ли?). Можно создать какого-то условного корреспондента, если надо, или не вводить вообще.
типа "Закупки у населения" без реквизитов, как условный покупатель в р=рознице = "конечный потреьитель"

**Comment by htrofymova** [comment]
готово
