### ISSUE TITLE
Выплата ЗП из кассы ФОП, добавить Отримувача - ФОПа в список физлиц, даже если он не принят.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#939]
Есть 2 варианта выплаты зарплаты из кассы: массовый (сотрудники в  ведомости + кассовый ордер на кассира) и индивидуальный (кассовый ордер непосредственно на сотрудника)

Дело в том, что если ФОП себя на работу не принимает, но у него есть другие работники. Он сам Является кассиром, бухгалтером и директором, это в качестве подписантов ордера кассового. Если у ФОПа нет кассира, то он и есть кассир. 

Значит Отримувач = кассир = он же ФОП, а так как он не принят на работу, то в списке Физлиц, которые идут в отборе Отримувача, его нет

**Comment by htrofymova** [comment]
готово
