### ISSUE TITLE
Добавить платежи в бюджет (штрафы, пени) в платежку.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#940]
![image](https://user-images.githubusercontent.com/42540074/58462542-cb469e80-813a-11e9-8f09-c6e1896da5db.png)
делаем платежи в бюджет (штрафы,пени)- при разноске платежки нет подходящих операций, как разнести?
![image](https://user-images.githubusercontent.com/42540074/58462571-d8fc2400-813a-11e9-985b-566a61d14566.png)
Определиться  с проводками.

**Comment by AlexeyTishkin** [comment]
Останавливаемся на том, что оплата штрафа осуществляется тем же шаблоном, что и перечисление налога ?

**Comment by Anestezia** [comment]
Я им систему предложенную описала, спросила подходит ли. Не ответили, наверное все ок.
