### ISSUE TITLE
Повернення коштів покупцю, в выписке нужна привязка к счету, в счете к платежке.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#941]
В выписке нет возможности привязать счет, по которому деньги возвращаются. Поле неактивно при выборе данной операции. 
Кейс: Выставили счет, деньги клиент оплатил, потом товар не отгружен или услуга не оказана, деньги надо вернуть, или часть денег. В счете также привязать возврат нет возможности.

**Comment by AndriyNesterenya** [comment]
Просю не забыть....
Юзера жалуются.

**Comment by Anestezia** [comment]
Какое же это улучшение? Это баг! 

Як зробити, щоб баланс був 0.00 грн? Отримали рахунок на 5000 грн. (гарантійний платіж, без ПДВ), сплатили. Потім постачальник гарант. платіж повернув. Якщо не робити придбання, то на головній сторінці світиться - очікує оприбуткування. Якщо робити оприбуткування, то баланс по даному контрагенту ТОВ "Будпрокат- Україна" дорівнює -5000 грн. Яким документом мені закрити повернення коштів. Коли робила виписку підв'язала договір оренди, рахунок підв'язати не вдається.
![image](https://user-images.githubusercontent.com/42540074/74164798-ee63a080-4c2c-11ea-88df-8635d8106877.png)
