### ISSUE TITLE
Справочники: Страны. Создаю - добавляю со встроенного справочника страну Италия. Сохраняю. В списке отражается. Перехожу в другой справочник, затем возвращаюсь в этот - Италия исчезла из моего списка стран

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#943]
Это на сервисе

**Comment by AlexeyTishkin** [comment]
На dev работает ?
И какая точная последовательность действий ?

**Comment by kattrina-brekhova** [comment]
На дев тоже не работает. да все как обычно - зашла в справочник, нажала "додаты", в поске ввела "италия" на укр. выбрала, сохранила. перешла в справочник валюты, потом сразу же спустилась в станы - италии нету

**Comment by AlexeyTishkin** [comment]
> На дев тоже не работает.

Под каким логином ?

Зашел под test@a2.net.ua, проблему повторить не могу.

**Comment by AlexeyTishkin** [comment]
Нашел одну ситуацию: если страну добавить, потом удалить, а потом опять импортировать, то наблюдается описанное поведение.
Исправил. Сейчас работает импорт ?

**Comment by kattrina-brekhova** [comment]
работает, спасибо!
