### ISSUE TITLE
В расчете ЗП при увольнении создать механизм синхронизации данных с авансовой ведомостью

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#945]
Так как в этом расчете нет промежуточной ведомости на выплату, а после расчета сразу идет кассовый ордер, то нет возможности учесть уже выплаченный аванс.
Например, аванс выплачен 15 числа, а человек решил уволиться 18 числа (по 36 статье договорились). 15 аванс выплатили, сколько рабочих дней ставить в расчете зп при увольнении? 11 или 1? За 10 было заплачено в аванс.

**Comment by Illya-Lykhachov** [comment]
02.06.2019
(ИЛ) Выплата зарплаты при увольнении. Изменён расчёт суммы выплаты. Теперь это сумма задолженности в расчётах с сотрудником (с учётом авансовых выплат и задолженности во взаиморасчётах по зарплате).
