### ISSUE TITLE
Создать возможность редактировать родительский документ-основание (связанный с ним документ создан, но не проведен)

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#95]
Редактировать родительский документ удалось лишь после того, как я удалила связанную с приходной накладной - накладную на возврат.
![31224049_1972494349668073_8708744807725400064_n](https://user-images.githubusercontent.com/38099938/39179820-f5e76b0e-47bd-11e8-91e4-07e2de32e6b8.png)

**Comment by AlexeyTishkin** [comment]
Так и задумано... Нужно глобальное обсуждение... Коля, выноси вопрос в aBox.

**Comment by kattrina-brekhova** [comment]
Не очень удобно, потому что я создала приходную накладную, на ее основе сделала возврат. потом увидела, что допустила ошибку, сняла проведение в возврате, чтобы корректировать приход - а она не пускает. после чего последовало 4 дополнительных действия: выйти, зайти в возвратную, удалить и зайти в приходную снова
