### ISSUE TITLE
Аванс и ЗП - В выплате по кассе нет нужной операции - Виплата зарплати

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#951]
![image](https://user-images.githubusercontent.com/42540074/58800816-8e364c80-8611-11e9-8456-00fef8d891f0.png)
![image](https://user-images.githubusercontent.com/42540074/58800930-d48bab80-8611-11e9-8f28-1e64da58f8e6.png)
Дело в том, что сама ведомость на выплату формирует проводки по зарплате 
![image](https://user-images.githubusercontent.com/42540074/58801259-b07c9a00-8612-11e9-8e95-db7e36f30f20.png)
(имеется в виду не корреспонденция счетов), и ордер в таком виде тоже их формирует. В Отчете-Расчетно-платежная ведомость и непосредственно в расчетах на руки эта сумма дублируется из-за этого.
Это недостающая операция и в ней в проводках одна вкладка
![image](https://user-images.githubusercontent.com/42540074/58801139-5e3b7900-8612-11e9-8ab0-7f91cb8933f0.png)
А здесь две:
![image](https://user-images.githubusercontent.com/42540074/58801179-790ded80-8612-11e9-8ad6-5ebad51a60cd.png)
![image](https://user-images.githubusercontent.com/42540074/58801199-81662880-8612-11e9-8472-bc757036e4d8.png)
![image](https://user-images.githubusercontent.com/42540074/58801306-d013c280-8612-11e9-9f15-fad6ad9a19b0.png)

**Comment by htrofymova** [comment]
готово
