### ISSUE TITLE
Идентификация клиента для тех.поддержки

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#957]
Для более удобной идентификации клиента, сотрудниками техподдержки, необходимо формировать и показывать "client ID".
"client ID" формируется из буквы и номера тенанта, пример: "b0123"
Буква указывает на принадлежность к источнику регистрации, например
b - это наши прямые клиенты
p - клиенты Прив....
s - клиенты Сонат....
t - клиенты Тас....
и т.д.

Отображаем "client ID" для клиента - в его учетке, возле ФИО клиента, в правом верхнем углу сервиса. Например: Иванов Иван (id: b0123)
Отображаем "client ID" для сотрудника техподдержки - в админке сервиса, в таблице клиентов, возле "тенант ID".

**Comment by MaksymTikhomirov** [comment]
Надо, уже прям подгорает (((

**Comment by alex-kukhtin** [comment]
v 7501
