### ISSUE TITLE
Объект учета НА: не получается удалить сам объект и удалить строку с этим объектом в ранее проведенном и распроведенном документе 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#958]
создала объект Основные средства, оприходовала его от инвестора. нужно заменить: распровела документ, но убрать строку с этим объектом не удается - на этапе сохранения такое сообщение
![image](https://user-images.githubusercontent.com/38099938/59179950-42812700-8b6c-11e9-83d7-fe58c0abbea3.png)
то есть получается, что нужно создавать новый документ по новому. так же не удается удалить документ и сам объект учета

**Comment by htrofymova** [comment]
Предлагаю делать операции с НА уже из нового раздела: Операции (beta). 
Именно такая операция -  Створити документ - Прийом-передача необоротних активів (прийом) - внутри выбрать операцию Внесення майна до статутного капіталу (емітент).

**Comment by htrofymova** [comment]
А так - не могу повторить.
