### ISSUE TITLE
Убрать режим "Печать с просмотром"

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#959]
Предлагаю вообще удалить режим "Друкувати з попереднім переглядом"
![image](https://user-images.githubusercontent.com/38098758/59296455-b287ce00-8c8e-11e9-9370-788466dbbe66.png)

От него сейчас вред один:
Если юзер просит печатать БЕЗ просмотра - ему откроется стандартный диалог печати с просмотром.
Если юзер просит печатать С предпросмотром - ему показывают печатную форму в окне без контроллов, чем загоняют юзера в непонятку, потому что далеко не каждый поймет, как ее дальше напечатать.

IMHO достаточно оставить сохранение в PDF + стандартный диалог печати.

**Comment by alex-kukhtin** [comment]
Переход всего и вся на диалоги потихоньку вообще уберет это окно.
Будет как в платежках - сразу печать или экспорт.

**Comment by AndriyNesterenya** [comment]
Тады ОК
