### ISSUE TITLE
Страница "Вхід в систему", поле "E-mail" тултип некорректный.

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#96]
![tool tip register](https://user-images.githubusercontent.com/35918141/39180095-b3756b6c-47be-11e8-87c1-1c0330ede148.png)

"Відновлення паролю" і "Реєстрація" мают тултіп "некоректний e-mail"
Сторінка "Вхід в систему" має тултіп "Неправильний e-mail"

Треба зробити однаковий тултіп для всіх трьох (і з маленької літери)

**Comment by nik-man** [comment]
"Відновлення паролю" і "Реєстрація" мают тултіп "некоректний e-mail"
Сторінка "Вхід в систему" має тултіп "Неправильний e-mail"
Треба зробити однаковий тултіп для всіх трьох (і з маленької літери)

**Comment by alex-kukhtin** [comment]
Fixed in 7163

**Comment by nik-man** [comment]
Проверил. Все хорошо.
