### ISSUE TITLE
Раздел Необоротные активы подраздел Операции (бета): в операции Приём необоротных активов не пзволяет выбрать контрагента с ролью "Поставщик"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#960]
К выбору возможен контрагент, у которого роль "Покупатель" и "Поставщик" одновременно

**Comment by htrofymova** [comment]
Не понятно, какая операция имеется ввиду. Если документ "Прийом-передача необоротних активів (прийом)", то в нем можно выбрать 2 операции, в которых можно выбрать любого контрагента в качестве поставщика.

**Comment by kattrina-brekhova** [comment]
Приём-передача необоротных активов (приём) - "Приобретение объектов нематериальных активов"
при выборе контрагента с ролью поставщик - тут же исчезает из рядка. при выборе контрагента с ролью поставщик-покупатель - контрагент остается в рядке документа

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/59490365-27285b80-8e8d-11e9-96ff-68260f5ce9b8.png)

**Comment by kattrina-brekhova** [comment]
хотя очень странно. у меня создан контрагент БукКипер, я хочу его выбрать в документ на приход нематериальных активов. если следовать логике, то добавила роль в учете - поставщик, покупатель. но все равно почему-то не могу выбрать в документ
это на сервисе
логин behappy120486@gmail.com
пароль behappy1204
посмотрите пожалуйста, почему не получается

**Comment by htrofymova** [comment]
исправлено
