### ISSUE TITLE
Добавить возможность создать контрагента физлицо и ФОП под одним ИНН.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#961]
![image](https://user-images.githubusercontent.com/42540074/59417867-b28fe700-8dd0-11e9-9b95-519b29be61c7.png)
В базе есть контрагент Физлицо, и нельзя добавить этого же человека ФОПом, так как коды одинаковые. Даже если я первого добавила через физлиц в персонале.

Вдруг у меня человек работает на предприятии, а еще он ФОП и я решила у него что-то купить.
Или бывший сотрудник ушел на аутсорс. 
Или, наоборот, подрядчика взяли в штат.

**Comment by AlexeyTishkin** [comment]
Сделал.
