### ISSUE TITLE
В Выписке при выборе Отрим. цільового фінансування добавить выбор вида финансирования

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#962]
Просят на этом этапе в этой операции добавить прямо в выписку выбор вида целевого финансирования, так как создается по умолчанию проводка по 483 счету, и потом приходится заходить в саму платежку сформированную этой выпиской, снимать проведение, выбирать подвид, чтоб поставило в данном случае 484 счет. И таких операций у клиента почему-то много. Вот сюда:
![image](https://user-images.githubusercontent.com/42540074/59418087-10bcca00-8dd1-11e9-8ec0-a74e2a601c97.png)
Как здесь:
![image](https://user-images.githubusercontent.com/42540074/59418107-1a463200-8dd1-11e9-80c0-c700484d9db7.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
