### ISSUE TITLE
Добавить в платежке на Перказ між своїми рахунками возможность создать на его основании Поступление на другой счет.

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#963]
Также как и у нас был вопрос о создании из операции нового интерфейса Видаток з рахунку в банку в касу, сделать Приход в кассу тут же. Так и с этой операцией: в старом виде из нее можно сразу и приход сделать было.а в новом такого нет. Я бы добавила.

**Comment by AlexeyTishkin** [comment]
Платеж "Переказ між своїми рахунками" создает сразу две операции: "Видаток на інший власний рахунок" и "Надходження з іншого власного рахунку".

**Comment by Illya-Lykhachov** [comment]
В кассе нужно сделать как в банке
