### ISSUE TITLE
Сделать на основании парные операции Видаток з каси на рахунок в банку и Тут же приход в банк этих сумм

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#964]
Как в старом интерфейсе было:
https://github.com/a2develop/bugTracker/issues/105
![image](https://user-images.githubusercontent.com/42540074/59423431-d0fae000-8dda-11e9-87cf-b1c0d1aa3878.png)
![image](https://user-images.githubusercontent.com/42540074/59423514-f8ea4380-8dda-11e9-935d-1abeaf9146e7.png)

**Comment by htrofymova** [comment]
готово
