### ISSUE TITLE
Раздел НА: не удаляется не проведенный документ Придбання об’єктів нематеріальний активів

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#966]
![image](https://user-images.githubusercontent.com/38099938/59507184-f5c28680-8eb2-11e9-9711-2f53fb23ad0b.png)

**Comment by kattrina-brekhova** [comment]
на сервисе
логин behappy120486@gmail.com
пароль behappy1204

**Comment by htrofymova** [comment]
исправлено. Чтобы "все получилось", надо заново провести-"распровести" документ, а потом уже удалить.
