### ISSUE TITLE
Раздел НА: не возможно внести изменение в проведенном документе Акт прийома-получения ОС в статутных капитал

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#968]
ситуация. сделала документ, оприходовала объекты учета на склад. есть необходимость разбить документ на два - часть объектов на один склад, а часть на другой. ни один из объектов учета не вводила в эксплуатацию
но переделать документ не получается. не удобно. получается, что я не могу внести изменения, удалить и отменить проведение документа 
![image](https://user-images.githubusercontent.com/38099938/59510532-9c5f5500-8ebc-11e9-943e-d48e0da6dfdf.png)

**Comment by htrofymova** [comment]
исправлено. То же, что #966
