### ISSUE TITLE
Вхідний рахунок. Создание накладной неочевидно из названия "документ"

### ISSUE THREAD

**Issue by nik-man** [a2develop/bugTracker#97]
![invoice_link_bill](https://user-images.githubusercontent.com/35918141/39180886-bce11802-47c0-11e8-883a-b789f9ec4996.png)
"Створити документ" -- не сразу понятно, какой документ.
Наверное, лучше написать "Створити накладну"
или может даже "Створити прибуткову накладну"

**Comment by AlexeyTishkin** [comment]
"Створити документ" -- не сразу понятно, какой документ.

[ТА] В названии группы написано «Придбання».

**Comment by AlexeyTishkin** [comment]
А если в счете услуги, то создается Акт...
А если в счете Услуги и Запасы, то создается Акт и накладная...

**Comment by nik-man** [comment]
Ааа... классно сделано. Ок, принято.
Следующий вопрос. Может вместо ID отображать краткое название?
А то вот сейчас не очень понятно, какие здесь документы:
![invoice_link_names](https://user-images.githubusercontent.com/35918141/39182150-a6c3a798-47c4-11e8-82cc-be4237625e5d.png)

**Comment by AlexeyTishkin** [comment]
> А то вот сейчас не очень понятно, какие здесь документы:

Ты же в счете находишься, перечень связанных документов ограничен... По названию группы понятно. Зачем в перечне из нескольких строк видеть еще подтип (банк, касса) ?

> Может вместо ID отображать краткое название?

Краткого наименования нет. Можно вывести наименование операции, но для него нет места...

**Comment by nik-man** [comment]
Хорошо. Закрываю. )
