### ISSUE TITLE
[Urgent] Вернуть возможность новой в выписке подставлять плательщиком физлицо без ИНН

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#970]
В старой версии выписки был глюк, позволявший подставлять физлицо типа "Інше" без ИНН в качестве плательщика при оплате физлицом через банк (по умолчанию плательшиком значится собственно платящий банк).
Это была ценнейшая возможность для всех продавцов услуг типа юристов/турфирм/ремонтников и т.д.

Живые клиенты бунтуют и требуют вернуть таковую возможность взад.

**Comment by AlexeyTishkin** [comment]
Сделал.
