### ISSUE TITLE
В карточке объекта учета расширить поле наименование, больше символов

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#971]
Нужно, чтоб влезло такое

Сервер HPE DL360 Gen10 4LFF CTO Server у складі: 1 шт. 860663-L21 HPE DL360 Gen10 Xeon-G 5118 FIO Kit 1 шт. 860663-B21 HPE DL360 Gen10 Xeon-G 5118 Kit 2 шт. 815098-B21 HPE 16GB 1Rx4 PC4- 2666V-R Smart Kit 2 шт. 861691-B21 HPE 1TB SATA 7.2K LFF SC DS HDD 2 шт. P04693-B21 HPE 300GB SAS 15K LFF SCC DS HDD 1 шт. 804394-B21 HPE Smart Array E208ip SR Gen10 Ctrlr 2 шт. 865414-B21 HPE 800W FS Plat Ht Plg LH Pwr Sply Kit 1 шт. BD505A HPE iLO Adv 1-svr Lic 3yr Support 1 шт. 734811-B21 HPE 1U CMA for Easy Install Rail Kit 1 шт. 789388-B21 HPE 1U Gen9/10 LFF Easy Install Rail Kit 1 шт. H7J32A3#WAG HPE DL360 Gen10 Support

**Comment by AlexeyTishkin** [comment]
Сделал.
