### ISSUE TITLE
В акте услуг добавить 949 счет

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#972]
Добрый день.
Пытаюсь вести учет в системе двух неприбыльных организаций. 
Хочется и надо, чтоб система была удобна, полезна и для бухгалтера, не только для предпринимателя, не имеющего понятия о бухучете, а нуждающемуся в "кто-то правильно сделает". может через признак, кто вводит доки - предприниматель или бухгалтер, как-то давать возможность бухгалтеру изменять проводки. Попытаюсь ниже уточнить.
Уже писала (через режим "зворотний зв'язок") о том, что в списке счетов при приходовании услуг нет счета 94 (949). Неприбыльные организации обязаны соблюдать правило, что административные расходы не должны превышать 20% общих затрат. В бухучете такие затраты отражаются на счете 92, о затраты, относящиеся к основной (общественной, благотворительной, социально-проектной) деятельности учитываются на счете 949.  На данный момент я выкручиваюсь, приходуя проектные расходы на счет 23, планирую закрыть их на 949 счет с использованием документа бухгалтерская справка. Это как временная мера. Просьба учесть заявку и добавить в список счетов для списания затрат 949.
Продолжение на тему счета 949:
У благотворительных организаций предоставление (перечисление) благотворительной помощи (целевой, нецелевой) никак не является административными расходами, поэтому проводки под банковским расходным документом на перечисление БП сразу в Дт 92 - печаль печальная. Кроме того, мне неудобно сразу перечисление на затраты относить. Есть необходимость учитывать БП через 377 счет (перечислено в Дт 377 благополучателю), затраты закрывать с учетом целевых позиций (объект учета есть) тем же актом приходования услуг ( в Дт 949 с Кт 377)..
Но хотелось бы иметь инструмент погибче. Пока попытаюсь выкручиваться бухсравкой. 
Пока закругляюсь с хотелками. Хочу понять заинтересованы ли разработчики в том, чтобы мы (мои подопечные  неприбыльные) остались вашими клиентами-пользователями.
С ув. З.Степанова .

**Comment by AlexeyTishkin** [comment]
Сделал.
