### ISSUE TITLE
Отображение "client ID" в учетной записи пользователя

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#973]
Для удобства идентификации клиента, необходимо быстро найти "client ID". Для этого нужно отображать ID на всех страницах учетной записи.
Предлагаем делать это возле ФИО клиента, в правом верхнем углу сервиса. Например: Иванов Иван (id: b0123)

![image](https://user-images.githubusercontent.com/42002015/60004130-b6dfbe00-9674-11e9-9e6a-2e214302e893.png)

**Comment by alex-kukhtin** [comment]
Сделано в личном кабинете
