### ISSUE TITLE
виготовлення на основе рецептуры

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#974]
зачем нужен документ "Створення рецептуры", если даже подтянув в документ "виготовлення" соотвествующую рецептуру, материалы и сырье нужно все равно вводить вручную. возможно ли автоматизировать этот учет?
![image](https://user-images.githubusercontent.com/38099938/60100435-6777bb80-9762-11e9-83ad-6c4e423debc2.png)

**Comment by kattrina-brekhova** [comment]
![image](https://user-images.githubusercontent.com/38099938/60100611-c50c0800-9762-11e9-9a68-260c08e0e93e.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
