### ISSUE TITLE
1 ДФ не подтягивается информация про договоры ГПХ

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#975]
![image](https://user-images.githubusercontent.com/42540074/60183175-6f9d2d00-982e-11e9-993a-464a900f3d79.png)
В 1ДФ не разграничивает трудовые договоры и ГПХ, а должно. Все валит на трудовые.

**Comment by Illya-Lykhachov** [comment]
Заодно выделены начисления и удержания по договорам ГПХ в отдельные строки с признаком дохода 102. В т.ч. если один и тот же сотрудник работал и в штате, и по договору ГПХ.
