### ISSUE TITLE
Неприбыльные "просьбы"

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#976]
[Використання цільового фінансування для придбання основних засобів.docx](https://github.com/a2develop/bugTracker/files/3330288/default.docx)

**Comment by htrofymova** [comment]
Когда вводятся документы, зачисляющие целевые посупления, то выбирается "вид поступления". Перечень видов посуплений привязан к Отчету неприбыльной организации J0101911. Т.е. вид послуплений соотвествует строке отчета. Если "Надходження  коштів на придбання основних засобів" в отчет должны попасть в строку 1.6, то, сначала они долны попасть в одну из строк 1.6.1 (Благодійна допомога), 1.6.2ГД (гуманітарна допомога), 1.6.3 (допомога військового характеру).  Все эти виды поступлений относятся на 483 счет. Однако средства на приобретение необоротных активов должны таки попадать на 484. Не сростается! Какой вид поступления относить на 484? Что бы и в строку 1.6 попадало и чтобы на 484? Еще следует учесть, что 1.6 = 1.6.1 + 1.6.2 +.1.6.3.
Может не 1.6 все-таки? Я разъяснений не нашла.

**Comment by htrofymova** [comment]
готово
