### ISSUE TITLE
В выписке лишняя проверка при проведении по счету с отрицательным балансом

### ISSUE THREAD

**Issue by Anestezia** [a2develop/bugTracker#977]
Изначально на счете отрицательный остаток, операцию по нему провести дает, а вот снять проведение уже не дает.
Если бух не посмотрел счет расчетный или остаток провтыкал, то ошибку он уже не исправит
В новых платежах выбросили все эти проверки. В выписке оставались для совместимости со старой.
![image](https://user-images.githubusercontent.com/42540074/60255978-61581b00-98d9-11e9-8f92-0d7092595ad8.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
