### ISSUE TITLE
Запретить в счете процент скидки больше 100% :)

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#978]
Оказалось, что у нас в счете допускается ввод процента скидки больше 100%, и в результате общая сумма уходит в минус.
На жизнь особо не влияет, но ИМХО стоит для приличия приделать туда валидатор, ограничивающий значения числами от 0 до 100.

Разрешать ли отрицательные значения для наценки - сами думайте :)

![image](https://user-images.githubusercontent.com/38098758/60401323-3ba46d80-9b88-11e9-958b-d4ba51c2755d.png)

**Comment by AlexeyTishkin** [comment]
Сделал.
