### ISSUE TITLE
Bug: При попытке Сохранить и закрыть операции Повернення коштів постачальником в касу, Оплата постачальнику з каси, Оплата покупця в касу и Повернення коштів покупцю з каси выдает ошибку, но операция создается.

### ISSUE THREAD

**Issue by AndriyNesterenya** [a2develop/bugTracker#98]
При попытке Сохранить и закрыть операции Повернення коштів постачальником в касу, Оплата постачальнику з каси, Оплата покупця в касу и Повернення коштів покупцю з каси выдает ошибку, но операция создается.

![image](https://user-images.githubusercontent.com/38098758/39185457-e5f97f0e-47cf-11e8-8557-24e162f346d1.png)

**Comment by shevchuk-vadim** [comment]
Моя форма - юрлицо, а руководитель не принят?
Я могу просто не выводить сообщение об ошибке в этом случае.
Или нужно выводить осмысленное сообщение типа "Сначала примите на работу руководителя предприятия"? В какой момент?
