### ISSUE TITLE
"Оплата покупця з комісією" новый вид операций в платежах

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#980]
Новый вид операций при создании платежного поручения и или/ввода выписки
"Оплата покупця з комісією"
При выборе этой операции  будет показываться поле "Комиссия", обязательное для заполнения. По сумме, указанной пользователем будут создаваться дополнительные проводки   (кроме обязательной для банковской выписки Дт 311 - Кт 361  оплата покупателя)
Дб 93 - Кт 361 
Дт 791 - Кт 93

**Comment by AlexeyTishkin** [comment]
Сделал.
