### ISSUE TITLE
При отнесении стоимости услуг на 152 счет, суммы этих услуг суммируются, а когда хочу отразить в Акте модернизации 1 из услуг, мне выбирает среднее арифметичное

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#981]
у меня 2 услуги разными актами, и с разной ценой, но одной датой отнесены на 152 счет, 
![image](https://user-images.githubusercontent.com/38099938/60674738-76a5ea00-9e83-11e9-9281-90941126d83f.png)
и я хочу отразить каждую из них на разный акт модернизации
но я не могу выбрать одну из них, считает среднее арифметичное
![image](https://user-images.githubusercontent.com/38099938/60674823-a9e87900-9e83-11e9-83a4-9837cecc6bdd.png)

**Comment by htrofymova** [comment]
ну, не согласна,что это баг.

**Comment by kattrina-brekhova** [comment]
так а если у меня 2 отдельные позиции услуг на два различных объекта, то как выбрать каждый из них? только по одному создавая...?

**Comment by htrofymova** [comment]
создавая разные объекты или количеством регулировать.

**Comment by kattrina-brekhova** [comment]
если технически єто сложно реализовать - я отстаю )) действительно, что єто не совсем типичная ситуация, я в ней оказалась случайно, но ощутила неудобство

**Comment by htrofymova** [comment]
я сделаю, чтобы можно было редактировать сумму услуг.

**Comment by htrofymova** [comment]
готово. Також і в операції Виготовлення ОЗ.

**Comment by kattrina-brekhova** [comment]
галина, наверное нужен этот механизм и в операцию "введение в эксплуатацию". так как при выборе услуг тоже считает среднеарефметическое, и сумма не корректируется

**Comment by htrofymova** [comment]
сделала в Акте ввода в експлуатацию
