### ISSUE TITLE
менять счет затрат, чтобы указывать счет затрат для каждого объекта необоротных активов, например, в Акте ввода в экусплуатацию

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#982]
Как на счет того, чтобы возможно было создавать несколько ведомостей амортизации в 1 месяц? 
в Амортизац ведомость включила некоторые ОЗ и отнесла амортизацию на 23 счет
хочу сделать еще одну, на другие объекты но с отнесением на другой счет
сервис не позволяет, пишет, что уже начисление амортизации было создано

**Comment by htrofymova** [comment]
Если все это ради того, чтобы менять счет затрат, то было как-то обсуждение, чтобы указывать счет затрат для каждого объекта необоротных активов, например, в Акте ввода в экусплуатацию, но issue так и не написали. Делать?

**Comment by kattrina-brekhova** [comment]
значит да, эта тема. это нужно для этого. меняю название ишью

**Comment by htrofymova** [comment]
Готово

**Comment by kattrina-brekhova** [comment]
Галина, в ведомости начисления амортизации по дебету подтягивает счет, который указан в соответсвующей строке
![image](https://user-images.githubusercontent.com/38099938/61290085-b1891580-a7d3-11e9-83c1-22fe3f154cd4.png)
счет отнесения затрат, который указала при вводе в експлуатацию, система не учла
![image](https://user-images.githubusercontent.com/38099938/61290171-e09f8700-a7d3-11e9-8e6d-7d6705d09758.png)

**Comment by kattrina-brekhova** [comment]
если мы указываем в карточке ввода в експлуатацию счет затрат, тогда необходимость в амортизационной ведомости строки с указанием счета - не нужна
но если ее убрать, не полетит ли учет у наших клиентов?

**Comment by htrofymova** [comment]
Я добавила подсказку, о том, что счет общий выбирается только, если надо установить одинаковый для всех объектов счет отнесения затрат (появляется, если навести мышку на метку "Рахунок віднесення витрат"). По умолчанию, этот счет - пустой. И если он пустой, то при проведении счет подставляется из свойств объекта. Таким образом, приоритет у счета выбраного в конкретном документе. При чем, выбор счета в документе НЕ меняет счет в свойствах объекта. Если надо как-то по-другому, переделаю. Я долго думала и придумала вот так.

**Comment by kattrina-brekhova** [comment]
в принципе понятно. может как то выделить строку "рахунок віднесення витрат" - ну или желтым, или знак вопроса со всплывалкой сделать, так как вероятность того, что подсказку увидят 0,01%
еще в подсказке допущены опечатки
![image](https://user-images.githubusercontent.com/38099938/61364079-c629e400-a88d-11e9-9f15-0883fffcdef6.png)
"Заповнюється, якщо треба обрати спільний рахунок для всіх об’єктів"

**Comment by kattrina-brekhova** [comment]
и возможно ли сделать в перечне счетов выбор "пустого поля" - без счета. или например название "Рахунки, вказані в Акті введення в експлуатацію". чтоб если отмена выбора какого-то счета, то не нужно было удалять и заново пересоздавать документ
![image](https://user-images.githubusercontent.com/38099938/61364308-3fc1d200-a88e-11e9-9319-80b290d38e13.png)

**Comment by htrofymova** [comment]
опечатки исправила. 
Добавила в список позицию "не обрано"
