### ISSUE TITLE
Таможенная декларация - импорт товаров: сделать возможность отнесения на себистоимость услуг - брокера, транспортых и т.д...

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#983]
по аналогии, как сделано в распределении транспортно-заготовительных затрат

**Comment by AlexeyTishkin** [comment]
Повтор.
https://github.com/a2develop/bugTracker/issues/890

**Comment by kattrina-brekhova** [comment]
упс, это я вдохновилась семинаром по вед )))
