### ISSUE TITLE
При создании ОСВ по банковскому счету создавать сообщение о непроведенных документах

### ISSUE THREAD

**Issue by GalinaLuk** [a2develop/bugTracker#984]
При создании оборотно-сальдовой ведомости по банковскому счету создавать всплывающее сообщение о непроведенных документах, если за выводимый период есть такие документы.

Увага! В данному періоді існують непроведені документи!
Подивитись детальніше можливо в розділі "Платежі" - "Чернетки"

**Comment by AlexeyTishkin** [comment]
Сделал.
