### ISSUE TITLE
кейс: расчет НДС в операциях импорт услуг

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#986]
1.	Відповідно 186.2.1 ПКУ, місцем постачання послуг, пов’язаних з рухомим майном, є місце їх фактичного постачання, тобто місця, де вони фактично здійснені. Це транспортно-допоміжні послуги, навантаження, розвантаження, перевантаження, складської обробки товарів, переробітки сировини, проведення експертизи та оцінки рухомого майна, послуги перевезення пасажирів і вантажів, постачання продуктів харчування й напоїв, ремонтні роботи, а також інші послуги, що пов’язані з рухомим майном.
2.	Відповідно до 186.2.2 ПКУ, місцем постачання послуг, які пов’язані з нерухомим майном, є фактичне місцезнаходження нерухомого майна. Це послуги агентств з нерухомості, підготовка та проведення будівельних робіт та інші.
3.	Відповідно до 186.2.3 ПКУ, місцем постачання послуг у сфері культури, мистецтва, освіти, науки, спорту, розваги, проведення конференцій, семінарів є місце фактичного надання послуг, тобто місця, де надаються такі послуги та відбуваються заходи.
4.	Пунктом 186.3 ПКУ передбачено винятки, для яких місце постачання послуг визначається місцем реєстрації отримувача послуг. Серед них є: рекламні, консультаційні, інжинірингові, інженерні, юридичні, бухгалтерські, аудиторські послуги, консультації з питань інформатизації, надання персоналу, надання в оренду (лізинг) рухомого майна, телеконукаційні, радіо- та телевізійного мовлення, транспортно-експедиторські послуги, надання майнових прав інтелектуальної власності тощо. ПДВ-зобов’язання за операціями з імпорту таких послуг визнає замовник.

вот: Якщо у нерезидента замовляємо транспортно-експедиторські послуги, місцем постачання яких визначається реєстрацією отримувача (пп. 186.3 ПКУ), нараховуємо зобов’язання з ПДВ. Якби ми надавали такі послуги нерезиденту, об’єкта оподаткування не виникало.

Відображення даної операції у декларації з ПДВ побтібно за той звітний місяць, в якому відбулась операція.
Сума операції відображається як у розділі «Податкові зобов’язання» (ряд. 6), так і розділі «податковий кредит», (ряд. 13).

**Comment by kattrina-brekhova** [comment]
еще по теме http://www.visnuk.com.ua/uk/publication/100007075-poslugi-vid-nerezidenta

**Comment by kattrina-brekhova** [comment]
1.	Податкові зобов’язання з ПДВ на імпортовані послуги нараховують юрособи – платники ПДВ, і в тому числі платники ЄП 5% (не платники ПДВ).
 Стаття 180.2 ПКУ говорить про те, що особою, відповідальною за нарахування та сплату податку ПДВ до бюджету, у разі постачання послуг нерезидентами, якщо місце постачання послуг розташоване на території України, є одержувач таких послуг. З цього зробимо перший висновок: для того, щоб виник обов’язок сплати ПДВ, закон не ставить у залежність бути платником ПДВ. Але йдеться конкретно про імпорт послуг.
Особливості заповнення такої податкової накладної з ПДВ зобов’язання юридичною особою – платником ПДВ:
Податкову накладну виписуємо за першою подією — або датою передплати або датою оформлення документа, що засвідчує постачання послуг.
В пункті меню «Операції» розділу «Придбання» обираємо «Податкове зобов’язання».
У верхньому лівому кутку зазначаємо тип причини невидачі податкової накладної — «14» — «Складена отримувачем (покупцем) послуг від нерезидента». 
У рядках, відведених для заповнення даних покупця вказуємо свої дані, код ЄДРПОУ та ІПН. Допускається заповнення найменування продавця без перекладу державною мовою. А у назві продавця відображаємо найменування нерезидента і через кому країну, в якій зареєстрований нерезидент-продавець. В полі ІПН продавця вказуємо умовний ІПН: 5 і 00000000000 (11 «нулів»).
Усі інші реквізити податкової накладної розділу А і розділу Б заповнюються без особливостей.
Відображення даної операції у декларації з ПДВ побтібно за той звітний місяць, в якому відбулась операція.
Сума операції відображається як у розділі «Податкові зобов’язання» (ряд. 6), так і розділі «податковий кредит», (ряд. 13).
В податковий кредит можемо включити суму операції, якщо податкова накладна зареєстрована вчасно.

СТ. 208.4. Якщо отримувача послуг не зареєстровано як платника податку, то податкова накладна не складається. Форма розрахунку податкових зобов'язань такого отримувача послуг у вигляді додатку до декларації з цього податку, затверджується у порядку, передбаченому статтею 46 цього Кодексу.
В такому випадку не будучи платником ПДВ скласти податкову накладну неможливо, подати декларацію з ПДВ теж неможливо. Але для таких випадків законодавець винайшов іншу форму - Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ.


2.	Об’єктом оподаткування ПДВ є операції з місцем постачання на території України  Ст. 185.1 ПКУ п. Б

3.	 Абз. 3 ст. 187.8 ПКУ говорить про те, що датою виникнення податкових зобов’язань у разі постачання послуг нерезидентами, місцем надання яких є митна територія України є перша із подій: або дата списання коштів, або дата оформлення документа, що засвідчує факт постачання послуг. Тобто у випадку послуг, які постачаються нерезидентом, якщо виникає ПДВ-зобов’язання, то ми його будемо рахувати за першою із подій.

4.	Ст. 190.2. ПКУ. Для послуг, які постачаються нерезидентами на митній території України, базою оподаткування є договірна (контрактна) вартість таких послуг з урахуванням податків та зборів, за винятком податку на додану вартість, що включаються до ціни постачання відповідно до законодавства. Визначена вартість перераховується в національну валюту за валютним (обмінним) курсом Національного банку України на дату виникнення податкових зобов'язань. 

5.	Право на податковий кредит виникає в тому місяці, в якому виникло зобов’язання за такими послугами нерезидента. Але якщо ви не платник ПДВ, то у вас виникатиме лише ПДВ-зобов’язання. А той, хто є платником ПДВ, буде мати в тому ж самому місяці ПДВ-зобов’язання і ПДВ-кредит. 

6.	186.4. Місцем постачання послуг є місце реєстрації постачальника, крім операцій, зазначених у пунктах 186.2 і 186.3 цієї статті. В ПКУ наводить перелік послуг, для яких особливим чином визначається місце надання послуг і обов’язок нараховувати ПДВ.

За загальним правилом для імпорту послуг місце постачання визначається місцем реєстрації постачальника такої послуги.

Відповідно 186.2.1 ПКУ, місцем постачання послуг, пов’язаних з рухомим майном, є місце їх фактичного постачання, тобто місця, де вони фактично здійснені.
а) послуг, що є допоміжними у транспортній діяльності: навантаження, розвантаження, перевантаження, складська обробка товарів та інші аналогічні види послуг;
б) послуг із проведення експертизи та оцінки рухомого майна;
в) послуг, пов'язаних із перевезенням пасажирів та вантажів, у тому числі з постачанням продовольчих продуктів і напоїв, призначених для споживання: тут є нюанси. Якщо перевозка вантажу нерезидентом Україніи, наприклад з німеччини до києва – без зупинок – то ПДВ не нараховуватиметься. Якщо вантаж везеться нерезидентом України зі Льова до Києва – то на вартість дороги по Україні нараховується ПДВ. Тобто, якщо по території Німеччини – ПДВ не буде, якщо пункт навантаження і розвантаження на території України – ПДВ буде.
г) послуг із виконання ремонтних робіт і послуг із переробки сировини, а також інших робіт і послуг, що пов'язані з рухомим майном;

Відповідно до 186.2.2 ПКУ, місцем постачання послуг, які пов’язані з нерухомим майном, в тому числі, що будуються, є фактичне місцезнаходження нерухомого майна. 
а) послуг агентств нерухомості;
б) послуг з підготовки та проведення будівельних робіт;
в) інших послуг за місцезнаходженням нерухомого майна, у тому числі що будується;
тобто, якщо послуги надає нерезидент України на території Литви – ПДВ не нараховуємо, якщо на території України – нараховуємо.

Відповідно до 186.2.3 ПКУ, місцем постачання послуг у сфері культури, мистецтва, освіти, науки, спорту, розваг або інших подібних послуг, включаючи послуги організаторів діяльності в зазначених сферах та послуги, що надаються для влаштування платних виставок, конференцій, навчальних семінарів та інших подібних заходів, є місце фактичного надання послуг, тобто місця, де надаються такі послуги та відбуваються заходи.
Тобто якщо нерезидент України влаштовує на наше замовлення виїзний семінар в Чехії – ПДВ не буде. Якщо організовує семінар в Україні – буде.

Пунктом 186.3 ПКУ передбачено винятки, для яких місце постачання послуг визначається місцем реєстрації отримувача послуг.
а) надання майнових прав інтелектуальної власності, створення за замовленням та використання об'єктів права інтелектуальної власності, у тому числі за ліцензійними договорами, а також надання (передача) права на скорочення викидів парникових газів (вуглецевих одиниць);
б) рекламні послуги;
в) консультаційні, інжинірингові, інженерні, юридичні (у тому числі адвокатські), бухгалтерські, аудиторські, актуарні, а також послуги з розроблення, постачання та тестування програмного забезпечення, з оброблення даних та надання консультацій з питань інформатизації, надання інформації та інших послуг у сфері інформатизації, у тому числі з використанням комп'ютерних систем;
г) надання персоналу, у тому числі якщо персонал працює за місцем здійснення діяльності покупця;
ґ) надання в оренду (лізинг) рухомого майна, крім транспортних засобів та банківських сейфів;
д) телекомунікаційні послуги, а саме: послуги, пов'язані з передаванням, поширенням або прийманням сигналів, слів, зображень та звуків або інформації будь-якого характеру за допомогою дротових, супутникових, стільникових, радіотехнічних, оптичних або інших електромагнітних систем зв'язку, включаючи відповідне надання або передання права на використання можливостей такого передавання, поширення або приймання, у тому числі надання доступу до глобальних інформаційних мереж;
е) послуги радіомовлення та телевізійного мовлення;
є) надання посередницьких послуг від імені та за рахунок іншої особи або від свого імені, але за рахунок іншої особи, якщо забезпечується надання покупцю послуг, перерахованих у цьому підпункті;
ж) надання транспортно-експедиторських послуг.
ПДВ-зобов’язання за операціями з імпорту таких послуг визнає замовник.

Що потрібно зробити в програмі:
1.	Операція імпорт послуг.
2.	Для платників ПДВ – створення податкової накладної на зобов’язання з ПДВ, де покупцем є наше підприємство, а виконавцем – нерезидент. При цьому, щоб сума за цією накладною автоматично потрапляла в розділ «Податкові зобов’язання» (ряд. 6) Податкової декларації з ПДВ.
3.	Податкова накладна з податкового кредиту з ПДВ. Покупець – наше підприємство, продавець – виконавець. Суми за операцією автоматично потрапляють в  розділі «податковий кредит», (ряд. 13) декларації.
4.	Для неплатників ПДВ Розрахунок податкових зобов’язань, нарахованих отримувачем послуг, не зареєстрованим як платник ПДВ.
5.	Платіжне доручення на податок на репатріацію –  його сплачують резиденти, які здійснюють виплати нерезидентам, під час такої виплати – наприклад, за виробництво та/або розповсюдження реклами, або за Проценти за позиками або фінансовими кредитами, наданими резидентам. Сума податку розраховується із суми виплати: Дт632 — Кр641/Податок з доходів нерезидентів.: Д641/Податок з доходів нерезидентів — Кр311.
6.	Щоквартальний звіт до органу статистики – Звіт про експорт (імпорт) послуг. Форма № 9-зез (квартальна)

в 1с цього звіту немає, компанії заповнюють його ручками в медку або сонаті

**Comment by kattrina-brekhova** [comment]
нужен еще отдельный кейс для экспедиторов, которые покупают у иностранных перевозчиков услуги и их перепродают нашим компаниям.
задача: в выставленном счете и актах оказанных услуг прописываются двумя строками услуги: 1 - услуга перевозки например з Германии в Киев, по которой НДС начисляется по 0 ставке и 2 - собственно услуга экспедитора (его маржа) - НДС 20%
в счете и акте нужно вставлять отдельно две строки этих услуг - на одной начисление ндс 0%(импортная перевозка), на второй (услуга экспедитора (его доход, маржа) - ндс 20%.
тоже самое и в табличной части налоговой накладной. указывается 2 строки: услуга по 0 ставке и услуга по ставке 20%

**Comment by AlexeyTishkin** [comment]
> тоже самое и в табличной части налоговой накладной. указывается 2 строки: услуга по 0 ставке и услуга по ставке 20%

Должна быть строка с 0 ставкой ? А код ставки какой ?
Или вообще не должно быть в НН этой строки ? Т.е. в НН только одна строка со ставкой 20% ?

да, строка со ставкой 0%:
международные перевозки грузов, пассажиров и багажа облагают НДС по ставке 0 %

>А код ставки какой ? - не знаю

знаю, что некоторые компании просят, чтоб в одной налоговой была возможность указания объектов налогообложения  с разными ставками, некоторые принимают две отдельные НН

вам нужно для жестких условий создания налоговой?

**Comment by AlexeyTishkin** [comment]
> Тобто, якщо по території Німеччини – ПДВ не буде

Тут именно нет НДС ? Не НДС со ставкой 0 ? И НН тоже нет ?

Если «везет» нерезидент, то «нулевые» правила обложения международной перевозки не работают и ставку 0 % НДС не применяют. Как разъяснили налоговики в ОНК № 610 (вопрос 10 разд. II), если перевозчик — нерезидент, то налоговые обязательства по НДС со стоимости услуг по перевозке не возникают. Поэтому международную перевозку от перевозчика-нерезидента «нулевым» НДС не облагают.

**Comment by kattrina-brekhova** [comment]
по практике - перевозчики сами понимаю, что делают, и строгих условий начисления ндс при различных операциях не нужно устанавливать в системе
дать интсрумент, которым они бы считали и декларировали эти операции

**Comment by AlexeyTishkin** [comment]
> да, строка со ставкой 0%:
международные перевозки грузов, пассажиров и багажа облагают НДС по ставке 0 %

> Если «везет» нерезидент, то «нулевые» правила обложения международной перевозки не работают и ставку 0 % НДС не применяют.

Это два разных вида: НДС 0% и нет НДС.
Какие варианты выбора НДС должны быть в строке Акта ?

К примеру:
![image](https://user-images.githubusercontent.com/35917940/68143986-48bcd900-ff3b-11e9-9cf3-07485348867d.png)

Нужен вариант "Без НДС" ?
Т.е. кейс, когда мы указали, что услуга № 1 без НДС, услуга № 2 с НДС 0%, а услуга № 3 с НДС 20%. И в НН должны попасть две строки со ставками 0%, 20%. А строка без НДС в НН попасть не должна.

**Comment by AlexeyTishkin** [comment]
Или такой же механизм как в Придбанні, т.е. вначале выбрали есть ли НДС у документа:
![image](https://user-images.githubusercontent.com/35917940/68145375-5162de80-ff3e-11e9-9b32-e03195e26d60.png)
А потом уже выбираем ставку для кажой строки.
В этом случае, если НДС нет, то НН создать нельзя, а если НДС есть, то НН создается на все позиции на выбранные ставки:
![image](https://user-images.githubusercontent.com/35917940/68145517-a1da3c00-ff3e-11e9-9c2b-abce42a78e78.png)

**Comment by kattrina-brekhova** [comment]
однозначно, что строки БЕЗ НДС в НН не попадают, а со ставкой 0% попадают
нашла ИНК, в которой рекомендуют сосздавать 2 налоговіе - по 0% ставке на стоимость перепроданной перевозке и на 20% на маржу

**Comment by AlexeyTishkin** [comment]
Тогда для единообразия делаем механизм такой, как в остальном приобретении: вначале указываем с НДС или без, а потом построчно НДС. Если в одной НН не хотим смешивать ставки, то делаем два Акта с НДС: первый с 0%, второй с 20%.

**Comment by kattrina-brekhova** [comment]
да, и все строки акта где ставка ндс 0% должны попадать в НН

**Comment by AlexeyTishkin** [comment]
> да, и все строки акта где ставка ндс 0% должны попадать в НН

Конечно.

**Comment by AlexeyTishkin** [comment]
> Податкова накладна з податкового кредиту з ПДВ. Покупець – наше підприємство, продавець – виконавець. Суми за операцією автоматично потрапляють в розділі «податковий кредит», (ряд. 13) декларації.

Странный момент с Сонатой. Она настаивает на том, что суммы в строке 13 должны быть равны соответствующим строкам из Приложения № 1. Но в Приложении № 1 отражаются только корректировки.

![image](https://user-images.githubusercontent.com/35917940/68218730-78c4b480-ffed-11e9-938a-d6966b07a8c9.png)

**Comment by AlexeyTishkin** [comment]
Строку 6 (обязательства) пропустила. Хотя там сумма не равна строке из Приложения № 1.

![image](https://user-images.githubusercontent.com/35917940/68219099-191ad900-ffee-11e9-94a7-322df6c3971d.png)

**Comment by AlexeyTishkin** [comment]
> Сума податку розраховується із суми виплати: Дт632 — Кр641/Податок з доходів нерезидентів.: 

Похоже, что начисление налога нужно делать в операции "Оплата постачальнику в валюті". 632 нужно закрыть в т.ч. по валюте, а в платежке по перечислению налога (Д641/Податок з доходів нерезидентів — Кр311) нет ни валюты, ни курса, ни суммы в валюте.
