### ISSUE TITLE
Ошибка при экспорте в Excel

### ISSUE THREAD

**Issue by DenisClone** [a2develop/bugTracker#989]
При экспорте появляется ошибка:  The process cannot access the file 'D:\home\site\wwwroot\App_apps\admin\tenant\list\tenants.xlsx' because it is being used by another process.

Повторил так: под одной учеткой, два раза подряд нажал на один и тот же экспорт. Первый раз операция отработала успешно, второй раз появилась ошибка. 
Спустя несколько часов, все повторилось: удачная операция, потом ошибка.

**Comment by alex-kukhtin** [comment]
fixed in 7505

**Comment by DenisClone** [comment]
На боевой админке ошибка осталась.

**Comment by alex-kukhtin** [comment]
Уже починилось. Закрывай нафиг
