### ISSUE TITLE
При копировании акта изготовления будущим числом не учитывает новое поступление запасов 

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#991]
Ситуация: создала акт изготовления в январе, списала все остатки
![image](https://user-images.githubusercontent.com/38099938/61304563-0a67a680-a7f2-11e9-8160-7f38d0314da0.png)

в феврале было поступление запасов и на новое производство хватает
копирую акт и меняю дату, но присутствие остатков не учитывается
![image](https://user-images.githubusercontent.com/38099938/61304636-2c612900-a7f2-11e9-95d6-8732c0d9b961.png)

создать акт изготовления могу только заполнив его заново, а не копированием
![image](https://user-images.githubusercontent.com/38099938/61304778-5fa3b800-a7f2-11e9-9057-80829eb3b1d6.png)

**Comment by htrofymova** [comment]
исправлено.. Так же для Акта ремонта и Акта ввода в эксплуатацию.
