### ISSUE TITLE
Создать возможность в документах Приходования услуг и нематериальных активов выбрать для Дт счет 39 Расходы будущих периодов

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#994]
также добавить  списание с расходов будущих периодов на затраты.
Ишью появилось в ходе переписки с Зоей Степановой. вот суть:
З. Степанова:
![image](https://user-images.githubusercontent.com/38099938/61374240-8a4e4900-a8a4-11e9-8f45-e96bead0785f.png)
К. Брехова:
![image](https://user-images.githubusercontent.com/38099938/61374270-9f2adc80-a8a4-11e9-9d80-4630cefee30a.png)
З. Степанова:
![image](https://user-images.githubusercontent.com/38099938/61374305-b669ca00-a8a4-11e9-8201-a125ea47487b.png)

**Comment by htrofymova** [comment]
для неаетериальньіх активов добавила

**Comment by AlexeyTishkin** [comment]
Операция "Придбання послуг". В список счетов для списания добавлен счет 39.
