### ISSUE TITLE
Хотелка от клиента: операция "Придбання послуг з матеріалами"

### ISSUE THREAD

**Issue by kattrina-brekhova** [a2develop/bugTracker#997]

**Comment by kattrina-brekhova** [comment]
по аналогии "Реалізація послуг з матеріалами"

**Comment by kattrina-brekhova** [comment]
кейс такой:

Я виставив Замовнику "Комерційну пропозицію" (зробив ""Рахунок" на послуги з матеріалами і змінив назву на "Комерційна пропозиція") отримав замовлення. Під час складання договору з Замовником назву "Комерційна пропозиція" замінюємо на "Кошторис" і робимо додатком до договору. Замовлення самостійно виконати не можу. Залучаю субпідрядника по договору субпідряду. Субпідрядник виконує роботу і надає "Акт на послуги з матеріалами". Матеріали з'являються у мене на складі і я можу зформувати від себе замовнику "Акт на послуги з матеріалами".

Проблема оприбуткування послуг з матеріалами від виконавця стоїть лише в тому, що потрібно двома документами обліковувати таке придбання. Нюансів в обліку, віднесенні вартості, списаннні таких запасів немає

**Comment by kattrina-brekhova** [comment]
прошу пардону - смотрела как реализовано в 1с. несмотря на всю громоздкость программы, эта операция проводится одним документом.
одновременно нужна возможность материалы и услуги вешать на различные счета (20, 152, 92, 93,....) - все наши задействованные счета

**Comment by AlexeyTishkin** [comment]
В новом интерфейсе "Акта полученных услуг" есть возможность оприходования ТМЦ.
